### ISSUE TITLE
feat: Add compatible versions in patches list

### ISSUE THREAD

**Issue by xerta555** [revanced/revanced-manager#100]
### Type

Functionality

### Branch

Flutter

### Issue

Hi
I think that it should be nice to add the compatible version(s) of the YouTube application for each patches.

Actually i just get that:
![image](https://user-images.githubusercontent.com/20888017/190393799-87e213a4-5d62-49cf-b393-4bcd1a610868.png)

I use ReVanced Manager 0.0.6 actually.

### Feature

Show "YouTube version XXX.XXX or lower/higher requied" below each ReVanced modules.

### Motivation

It will be usefull for users to know which version or YT app to install on their devices for their usages.

**Comment by TheNeoStormZ** [comment]
Looks like it's already implemented. If I click on "Unsupported version" it shows me a list of compatible versions.
![supported-versions](https://user-images.githubusercontent.com/73660500/190398920-65ab0d81-b10d-49a0-8b10-e8a1d2f9de85.png)

**Comment by xerta555** [comment]
> Looks like it's already implemented. If I click on "Unsupported version" it shows me a list of compatible versions. ![supported-versions](https://user-images.githubusercontent.com/73660500/190398920-65ab0d81-b10d-49a0-8b10-e8a1d2f9de85.png)
> 
> Edit: I'm using version 0.0.6 at the time of this post

Ah yeah oups sorry, effectivly i get it also.
I close.
