### ISSUE TITLE
feat: Allow changing the patches version

### ISSUE THREAD

**Issue by q1k** [ReVanced/revanced-manager#1001]
### Type

Functionality

### Issue

I want to patch an older version of Youtube that is not supported in the current patches version.

### Feature

Allow changing the patches version so we can patch the older supported app versions.
For example I want to use Youtube v17 but I'm unable to patch it with the current patches.
If we were allowed to change the patches version we could patch that older version again.

### Motivation

It lets us repatch the version that we want to use and not always the latest. New isn't always better.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Very old patches can be incompatible with the version of the patcher used in ReVanced Manager, but in the most cases you can use slightly older versions

**Comment by leumasme** [comment]
I agree, it's currently impossible to patch an old version of an app if the patches don't support that version anymore, even if working patches for that app version existed.  
It should be possible to use previous versions of patches if required.  
These matching patch versions still exist in the git history, perhaps simply scanning through it for the appropriate patch versions would be fine.  
There are many reasons why someone would want to use an older version of an app. Maybe they don't like the UI in newer versions, maybe it's missing features, or maybe they just got a phone and want the exact same patched app experience as on their previous phone. ReVanced currently makes this impossible, even though the patches exist.

**Comment by oSumAtrIX** [comment]
In the subsequent coming releases, you will be able to choose weather you want to update anything automatically or manually.

**Comment by leumasme** [comment]
> you will be able to choose weather you want to update anything automatically or manually

I don't see how this is related to the issue, unless you somehow mean that this includes the option to manually downgrade the patch database to an older version.

**Comment by Ushie** [comment]
This isn't possible as ReVanced Patches and ReVanced Integrations are both dependent of eachother, but releases independently, ReVanced Manager has no idea how to pair them correctly

This would only be possible if both ReVanced Integrations was released as an asset in ReVanced Patches releases, but until then this isn't possible
