### ISSUE TITLE
bug: No applications found if no any app installed supports patch

### ISSUE THREAD

**Issue by w311ang** [revanced/revanced-manager#1007]
### Type

Error while running the manager

### Bug description

When I do not install any applications reflected in https://releases.revanced.app/patches and I enter `Select an application`, it will show `No applications found`

### Steps to reproduce

Step 1. Do not install any app that supports patch
Step 2. Install the manager and grant all permissions including root
Step 3. Select `Select an application`
Step 4. Then no any app in it and show `No applications found`

### Android version

12

### Manager version

1.3.9

### Target package name

not applicable

### Target package version.

not applicable

### Installation type

Root

### Patches selected.

not applicable

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
07-11 01:48:46.527  1065  1065 I Quality : Skipped: false 1 cost 11.829801 refreshRate 0 processName app.revanced.manager.flutter
--------- beginning of main
07-11 01:50:20.735  1065  1092 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
07-11 01:50:20.735  1065  1092 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
07-11 01:50:20.745  1065  1092 I OpenGLRenderer: Davey! duration=94209ms; Flags=1, FrameTimelineVsyncId=3068273, IntendedVsync=34501521830004, Vsync=34501532941115, InputEventId=0, HandleInputStart=34501533978971, AnimationStart=34501533981315, PerformTraversalsStart=34501533982096, DrawStart=34501553007878, FrameDeadline=34501554163337, FrameInterval=34501533659805, FrameStartTime=11111111, SyncQueued=34501553293138, SyncStart=34501553384232, IssueDrawCommandsStart=34501553536367, SwapBuffers=34501554979753, FrameCompleted=34595731912842, DequeueBufferDuration=1002656, QueueBufferDuration=1032760, GpuCompleted=34595731912842, SwapBuffersCompleted=34501556265326, DisplayPresentTime=0, 
07-11 01:50:21.293  1065  1065 V AutofillManager: requestHideFillUi(null): anchor = null
07-11 01:50:22.369  1065  1065 V AutofillManager: requestHideFillUi(null): anchor = null
```

### Solution

Install any one app that supports patch.

### Additional context

Some apps have the best patch version. Without installing the latest version in advance, I want to know the best version before installing.

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by EvadeMaster** [comment]
🎉 The fix for this issue have been in #1009 and released in ReVanced Manager v1.4.1

If problem persist, feels free to reopen this issue, happy patching!
