### ISSUE TITLE
feat: Add an option to hide non supported patches

### ISSUE THREAD

**Issue by xDARKxDEVILx** [ReVanced/revanced-manager#1008]
### Type

Functionality

### Issue

Currently you get supported patches that was made specificly for that app and non supported patches that are universal in the patches list, those universal patches mostly are useless or even break the app so i would like to have an option to hide them

### Feature

I would like to have the option to remove these universal patches by one or two of these suggested changes
1- first you could add a button to hide universal (non Default patches) here
![IMG_20230710_205056](https://github.com/revanced/revanced-manager/assets/120474122/7141e4b5-9672-4a39-b320-5af521b85650)

2- second you could add a button in settings to hide these patches from appearing in all app patches list
You could add it with these
![IMG_20230710_205721](https://github.com/revanced/revanced-manager/assets/120474122/9a6b6910-d1eb-40ef-9ae4-46bb54583ac5)

### Motivation

I know you guys are currently working on making a warning for selecting non Default patches or something like that but i think this request could be useful too even for just removing distraction and reducing swiping through patches you will rarely use XD

### Additional context

This would be more helpful for people using manager for first time and selecting non Default patches then complaining in discord 🙂

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Universal patches are not "non supported". Though an option can be added to hide patches that do not feature explicit compatibility with an app.

**Comment by xDARKxDEVILx** [comment]
> Universal patches are not "non supported". Though an option can be added to hide patches that do not feature explicit compatibility with an app.

I guess i could have worded it better but yeah you get what i mean, i wanted to just call them non Default patches but i think some non Default patches are not universal so i am not sure

**Comment by Ushie** [comment]
Superseded by #1080
