### ISSUE TITLE
feat: cancel operations button

### ISSUE THREAD

**Issue by ghost** [ReVanced/revanced-manager#101]
### Type

Functionality

### Branch

Flutter

### Issue

Currently it's not possible to cancel patching APK operations.

### Feature

Add a button to cancel patching task.

### Motivation

Any compiler can be prone to errors, so when patching task incur into a stuck, you can stop it and start over.

**Comment by SodaWithoutSparkles** [comment]
Or maybe when you realize you have made a mistake and forgot to include/exclude a patch

**Comment by OxrxL** [comment]
> Or maybe when you realize you have made a mistake and forgot to include/exclude a patch

Yeah...whatever. 👍
