### ISSUE TITLE
feat: <title>Ambient mode and Seekbar thing

### ISSUE THREAD

**Issue by jsjajajjajaashhbsbabhsshhshs** [revanced/revanced-manager#1012]
### Type

Cosmetic

### Issue

I have 2 devices 

one isnt rooted and has YT version 18.19.35 version and i patched it with 1.3 revanced manager and it has working ambient mode and this feature below 

![Screenshot_2023-07-11-20-43-44-310_app revanced android youtube](https://github.com/revanced/revanced-manager/assets/79274862/83520fd3-32de-45e2-b6b9-54fcecf4c544)

my other device is rooted and has a YT version 18.23.35 and patched using 1.4 revanced manager, it has an ambient mode option but it doesnt work at all and the feature above isnt showing

any tip to get those back ? or i just need to wait for the next patch ?

### Feature

I have 2 devices 

one isnt rooted and has YT version 18.19.35 version and i patched it with 1.3 revanced manager and it has working ambient mode and this feature below 

![Screenshot_2023-07-11-20-43-44-310_app revanced android youtube](https://github.com/revanced/revanced-manager/assets/79274862/83520fd3-32de-45e2-b6b9-54fcecf4c544)

my other device is rooted and has a YT version 18.23.35 and patched using 1.4 revanced manager, it has an ambient mode option but it doesnt work at all and the feature above isnt showing

any tip to get those back ? or i just need to wait for the next patch ?

### Motivation

I have 2 devices 

one isnt rooted and has YT version 18.19.35 version and i patched it with 1.3 revanced manager and it has working ambient mode and this feature below 

![Screenshot_2023-07-11-20-43-44-310_app revanced android youtube](https://github.com/revanced/revanced-manager/assets/79274862/83520fd3-32de-45e2-b6b9-54fcecf4c544)

my other device is rooted and has a YT version 18.23.35 and patched using 1.4 revanced manager, it has an ambient mode option but it doesnt work at all and the feature above isnt showing

any tip to get those back ? or i just need to wait for the next patch ?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by reisxd** [comment]
Acknowledgements not met.

**Comment by oSumAtrIX** [comment]
Open a proper issue
