### ISSUE TITLE
bug: can not update revanced extended from manager

### ISSUE THREAD

**Issue by eiko03** [revanced/revanced-manager#1014]
### Type

Error while running the manager

### Bug description

can not update revanced ir revanced extended from manager

### Steps to reproduce

install a old revanced extended app 
install the manager
try updating revanced extended app
it says app not installed as package conflicts with an existing package

### Android version

13

### Manager version

1.6.19

### Target package name

youtube revanced extended

### Target package version.

18.25.39

### Installation type

Non-root

### Patches selected.

nothing

### Device logs (exported using Manager settings).

```shell
noting
```

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by Julius8900** [comment]
We don't offer support for ReVanced Extended.

**Comment by Turhvjbufv** [comment]
Use inotia00 rvx manager https://github.com/inotia00/revanced-manager
