### ISSUE TITLE
support for armv7 devices.

### ISSUE THREAD

**Issue by TheGuyWhoo** [revanced/revanced-manager#1016]
### Type

Functionality

### Issue

Is this gonna happen any time soon? Especially with revanced builder currently archieved, it really fucks some of us over who can't update the app because archived builder fails. There is literally no way for me to patch the app right now. 

### Feature

support armv7 devices

### Motivation

So armv7 devices can patch the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
#423

**Comment by TheGuyWhoo** [comment]
Is there any way for me to patch in the meantime or am I stuck waiting for v4?

**Comment by HypeMaxers** [comment]
Yes you can use revanced cli or use another device and share the youtube apk

**Comment by TheGuyWhoo** [comment]
Okay, great. Thank you.
