### ISSUE TITLE
feat: migrate to revanced api v2

### ISSUE THREAD

**Issue by validcube** [ReVanced/revanced-manager#1020]
## 🚀 Migrate to ReVanced API V2

*oh my god, there isn't issue template that matched my standard :trollface:*

With ReVanced API v1 reaching End-of-Life, we should move to ReVanced API v2 as soon as possible to avoid potential issues with the API shutting down in the future.

### 💫 Tracking branch: [`revanced-api-v2`](https://github.com/revanced/revanced-manager/tree/revanced-api-v2)

-------------------------------------------------------

**ReVanced API v2: https://api.revanced.app**
~~ReVanced API v1: https://releases.revanced.app~~

-------------------------------------------------------

Found issues in our API system? Consider opening an issue or contributing to the repository at [🚀 ReVanced API!](https://github.com/revanced/revanced-api)

**Comment by EvadeMaster** [comment]
Tracking branch: [`revanced-api-v2`](https://github.com/revanced/revanced-manager/tree/revanced-api-v2)
