### ISSUE TITLE
home ads happens and video ads also sometimes happen

### ISSUE THREAD

**Issue by andylee516** [revanced/revanced-manager#103]
### Type

Other

### Branch

as the alpha mode you uploaded it

### Bug description

home ads are still appearing and video ads sometimes appear at my device. I had included video, general ads removal however--

### Steps to reproduce

ads appear

### Relevant log output

```shell
>
```

**Comment by oSumAtrIX** [comment]
30 minutes ago a possible fix has been created: https://github.com/revanced/revanced-integrations/releases/tag/v0.37.1

**Comment by luximus-hunter** [comment]
Isn't this a patch issue? Also, are you using the recommended version of YouTube?

**Comment by Aunali321** [comment]
Not related to manager.

**Comment by andylee516** [comment]
I had re installed micro g and had patched 3times(with 17.33.42) but video ads still happens. Unskipable ads are shown in sometimes. TT
