### ISSUE TITLE
bug: no way to identify why app installation failed 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-manager#1030]
### Type

Error at runtime

### Bug description

There will be cases where one may be forced to uninstall the manager due to some issue and the user could have forgotten to backup the keystore. In such cases when updating a patched app over an existing patched app will end app with the message "app not installed as package conflicts with an existing package". But after the recent update and l presume with the fix #1021, when clicking install the pop up after installation just disappears. If installed successfully, the manager will say installed. But if it fails there is no way to know what's the issue and manager just says installing.

### Steps to reproduce

1) Some how create a situation where the manager will come across a conflict (like mentioned above).
2) Try to install the same app over the existing one.
3) Normally there will the be conflict message but now you just sit there in the manager with unlimited install clicks.

### Android version

Android 13

### Manager version

1.4.1

### Target package name

Any

### Target package version.

Any

### Installation type

Non-root

### Patches selected.

Nil

### Device logs (exported using Manager settings).

```shell
Nil
```

### Screenshots or video

https://github.com/ReVanced/revanced-manager/assets/117499019/1809b5cc-1a3d-4c47-bed6-42c3f741976d

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by TheAabedKhan** [comment]
I am currently working on the fix. Can you please turn off the Google Play Protect for some times and try to install the app again and share me the results please.

**Comment by ILoveOpenSourceApplications** [comment]
I don't think it's due to play protect. But I did what you requested and turned of play protect and repeated the same with the results also being the same. Previously the manager would show a confirmation dialog which is part of the stock package installer. Now that it's removed there's no way of knowing what happened.

The package dialog I meant:
![Screenshot_20230716-103830~2](https://github.com/ReVanced/revanced-manager/assets/117499019/676092c0-864a-45fc-aa25-64d7b5c0c1b7)

And similarly one the installation/update of an app is done that confirmation is also gone as well. Which is fine but feels odd as the users used to see that confirmation in the previous versions.

**Comment by sssh7710** [comment]
The same happens to me when I install revanced

**Comment by KobeW50** [comment]
@TheAabedKhan Do you have an estimate for when a fix will be released? I see many users daily think that the Manager is stuck on the "Installing" phase. And many users who try to update to fix the buffer issue don't realize that the app installation might've failed.

I know this is annoying, sorry

**Comment by Ushie** [comment]
I think the callback should be removed if it's not possible to pop the dialog ONLY when it errors

The dialog needs to stay for two reasons: 
- it natively contains an "Open" button to open the installed app
- currently, many installations fail because the dialog doesn't stay up long enough to show the play protect dialog

**Comment by KobeW50** [comment]
On a related note, the package installer dialog also does not appear when updating the Manager from within the Manager.

https://github.com/ReVanced/revanced-manager/assets/84587632/979b3258-e6b1-4143-a9ca-4d76c7328fea
