### ISSUE TITLE
No warning when patching from storage without microG support

### ISSUE THREAD

**Issue by glibg10b** [ReVanced/revanced-manager#1035]
### Bug description

Revanced Manager doesn't warn before patching an APK from storage without microG support

### Steps to reproduce

1. Choose an APK file from storage
2. Untick the microG support patch
3. Press "Patch"

### Manager version

1.4.1

### Patches selected.

Not *Vanced MicroG support*

### Solution

Show a warning when pressing "Patch"

### Additional context

I waited 30 minutes for it to finish patching only to discover there was no way of installing it. Fixing this would prevent this from happening again.

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by TheAabedKhan** [comment]
Patching is supported without MicroG but installing that patched apk without root isn't. Did you not get any warning after clicking on the `Install` button after patching is completed?

**Comment by glibg10b** [comment]
Yes, I get a warning for either installation method, which means it's impossible to install. That's why I think there should be a warning *before* patching if you're patching a file from storage without MicroG support

![Screenshot_20230719-133415_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/56197853/43248519-3297-444f-b315-5ef7830077ce)
![Screenshot_20230719-133424_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/56197853/23f203af-7ec7-4adf-a90e-5235adebbb14)

**Comment by KobeW50** [comment]
I thought you can still export the apk and then mount the app.

**Comment by glibg10b** [comment]
I didn't know of that option. Ioubt many people do

What does mounting an app mean? Does it work if the MicroG support patch is missing?

**Comment by KobeW50** [comment]
> What does mounting an app mean? Does it work if the MicroG support patch is missing?

Tbh I'm not rooted and don't know what I'm talking about. But I've heard that it's possible to mount after exporting. Can't confirm if it's true.

I believe mounting is force installing an app over another app, which is what the manager does to YT/YT Music when doing a root install.

**Comment by glibg10b** [comment]
So non-root users are still screwed if they left out the MicroG support patch

Also, if the install as root button doesn't work with APK files from storage, then I don't see why the method you're talking about would work. So everyone is screwed

**Comment by KobeW50** [comment]
> Also, if the install as root button doesn't work with APK files from storage, then I don't see why the method you're talking about would work. So everyone is screwed

Oh yeah, you're totally right.

Check [this comment](https://github.com/ReVanced/revanced-manager/issues/875#issuecomment-1552995604)

**Comment by oSumAtrIX** [comment]
Closing this as the popup should not exist to begin with, a separate issue is opened to get rid of it:
https://github.com/ReVanced/revanced-manager/issues/1164
