### ISSUE TITLE
feat: Display version info on dashboard

### ISSUE THREAD

**Issue by eUnisk** [ReVanced/revanced-manager#1039]
### Type

Cosmetic

### Issue

Currently, only the installed version can be found on the dashboard, which makes it not so easy to check updates.

### Feature

It's handy to display the Latest Offical Version, Suggested Version and Installed Version. 

### Motivation

QOF

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
The installed version serves no meaning, the user only needs to know if an update is available or not, as they should always be on latest
