### ISSUE TITLE
bug: App crashes when unpacking Tiktok apk

### ISSUE THREAD

**Issue by SadLinusGuy0** [revanced/revanced-manager#104]
### Type

Error while running the manager

### Branch

Alpha under Releases

### Bug description

When attempting to unpack the Tiktok APK, the app crashes. Works fine for YouTube, YT Music and Twitter (Haven't tried the others)

### Steps to reproduce

Download a Tiktok APK file. Then go to Patcher, Select Application, select Tiktok, then try to Patch.

### Relevant log output

```shell
[Revanced Manager logs.txt](https://github.com/revanced/revanced-manager/files/9577338/Revanced.Manager.logs.txt)



### Screenshots or videos


https://user-images.githubusercontent.com/113133532/190459351-6266c98e-426c-4fc4-ac04-1d8e61e04750.mp4



### Solution

_No response_

### Additional context

I'm running this on my S20 G980F (exynos)

**Comment by Spacellary** [comment]
Still happens as of v0.0.7.

**Comment by Sherman-Liu** [comment]
Report: Updated to v0.0.7, problem stays the same.

**Comment by Aunali321** [comment]
Try again on latest build.

**Comment by Spacellary** [comment]
> Try again on latest build.

✅ Successfully patching TikTok in the latest build.

Version: 0.0.24
Model: 2201117TL
Android Version: 11 (MIUI 13)
Arch: arm64-v8a
