### ISSUE TITLE
feat: Ability to change in-app language settings

### ISSUE THREAD

**Issue by eUnisk** [ReVanced/revanced-manager#1040]
### Type

Functionality

### Issue

Not able to change in-app language display.

### Feature

Add language selection in settings.

### Motivation

Let users choose their preferred in-app language without changing the system language.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
Duplicate
