### ISSUE TITLE
Please add the ability to set the target architecture.

### ISSUE THREAD

**Issue by root-kernelhacker** [ReVanced/revanced-manager#1043]
### Type

Functionality

### Issue

Please add the ability to set the target architecture.

### Feature

Please add the ability to set the target architecture.

You said to use the CLI command, but you build it as a mobile app in an environment where you cannot use a PC, but it is created only for all architectures, so it is not good in terms of capacity or operating speed.  Since I use the CLI anyway, it would be great if there was an option to set the target architecture of the generated APK to v8a only.  thank you

### Motivation

You said to use the CLI command, but you build it as a mobile app in an environment where you cannot use a PC, but it is created only for all architectures, so it is not good in terms of capacity or operating speed.  Since I use the CLI anyway, it would be great if there was an option to set the target architecture of the generated APK to v8a only.  thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by PalmDevs** [comment]
First of all, it's not just ARMv8 that has the ability to patch. Anything other than ARMv7 works completely fine. Secondly, if the app can't be installed on a user's phone, it gives off bad user experience vibe and makes them feel in the wrong. It's better that ARMv7 users are able to install and *try* to patch using the app.

Either way, this Manager is no longer actively maintained anymore. We are working on a newer and better version of ReVanced Manager which will support every single architecture. It can be found at: [revanced/revanced-manager-compose](https://github.com/revanced/revanced-manager-compose).

**Comment by Ushie** [comment]
This issue is about patching split packages, not the ReVanced Manager releases, nevertheless this is something that's in the works in the ReVanced Patcher repository revanced/revanced-patcher#165

Closing this issue because its unrelated to ReVanced Manager
