### ISSUE TITLE
feat: youtune.apk arm64-v8a only output.

### ISSUE THREAD

**Issue by root-kernelhacker** [ReVanced/revanced-manager#1045]
### Type

Functionality

### Issue

I am writing again because the answer to the feature request seems to have been misunderstood.  What I'm saying is the following.  

1. To patch youtube when the PC is unavailable, it is only possible with revanced-manager.apk.  
The problem is that if you patch using the command line method using a PC, you can create an arm64-v8a-only apk by setting the java.exe option.  (v7a, x86, x64 are not included) 

2. However, when building with revanced-manager.apk, the corresponding option cannot be set, so youtube.apk containing all architectures is created.  

3. Revanced-manager.apk is also patched in the same way as the command method, but.  It is a tool that makes patching convenient, but I understand that the process and principle of patching are the same.  

4. To summarize, when patching youtube.apk from revanced-manager.apk, the question was whether it was difficult to add options so that the final build youtube.apk could be created exclusively for arm63-v8a.  

5. Finally, if so, is there any other way to separate the already patched youtube.apk or the original youtube.apk before the patch into v8a only for mobile phones?

(I using translation app, sorry)

### Feature

I am writing again because the answer to the feature request seems to have been misunderstood.  What I'm saying is the following.  

1. To patch youtube when the PC is unavailable, it is only possible with revanced-manager.apk.  
The problem is that if you patch using the command line method using a PC, you can create an arm64-v8a-only apk by setting the java.exe option.  (v7a, x86, x64 are not included) 

2. However, when building with revanced-manager.apk, the corresponding option cannot be set, so youtube.apk containing all architectures is created.  

3. Revanced-manager.apk is also patched in the same way as the command method, but.  It is a tool that makes patching convenient, but I understand that the process and principle of patching are the same.  

4. To summarize, when patching youtube.apk from revanced-manager.apk, the question was whether it was difficult to add options so that the final build youtube.apk could be created exclusively for arm63-v8a.  

5. Finally, if so, is there any other way to separate the already patched youtube.apk or the original youtube.apk before the patch into v8a only for mobile phones?

(I using translation app, sorry)

### Motivation

I am writing again because the answer to the feature request seems to have been misunderstood.  What I'm saying is the following.  

1. To patch youtube when the PC is unavailable, it is only possible with revanced-manager.apk.  
The problem is that if you patch using the command line method using a PC, you can create an arm64-v8a-only apk by setting the java.exe option.  (v7a, x86, x64 are not included) 

2. However, when building with revanced-manager.apk, the corresponding option cannot be set, so youtube.apk containing all architectures is created.  

3. Revanced-manager.apk is also patched in the same way as the command method, but.  It is a tool that makes patching convenient, but I understand that the process and principle of patching are the same.  

4. To summarize, when patching youtube.apk from revanced-manager.apk, the question was whether it was difficult to add options so that the final build youtube.apk could be created exclusively for arm63-v8a.  

5. Finally, if so, is there any other way to separate the already patched youtube.apk or the original youtube.apk before the patch into v8a only for mobile phones?

(I using translation app, sorry)

### Additional context

I am writing again because the answer to the feature request seems to have been misunderstood.  What I'm saying is the following.  

1. To patch youtube when the PC is unavailable, it is only possible with revanced-manager.apk.  
The problem is that if you patch using the command line method using a PC, you can create an arm64-v8a-only apk by setting the java.exe option.  (v7a, x86, x64 are not included) 

2. However, when building with revanced-manager.apk, the corresponding option cannot be set, so youtube.apk containing all architectures is created.  

3. Revanced-manager.apk is also patched in the same way as the command method, but.  It is a tool that makes patching convenient, but I understand that the process and principle of patching are the same.  

4. To summarize, when patching youtube.apk from revanced-manager.apk, the question was whether it was difficult to add options so that the final build youtube.apk could be created exclusively for arm63-v8a.  

5. Finally, if so, is there any other way to separate the already patched youtube.apk or the original youtube.apk before the patch into v8a only for mobile phones?

(I using translation app, sorry)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by reisxd** [comment]
> The problem is that if you patch using the command line method using a PC, you can create an arm64-v8a-only apk by setting the java.exe option.

That's not possible in ReVanced CLI. You cannot make an arch-specific APK in CLI or Manager. 

Also, what would anyone gain from this, other than some space (you can already do this manually by yourself)?

**Comment by root-kernelhacker** [comment]
This is because of the memory used (including cache memory).  An apk that includes all architectures will have more running memory (including cache space).  You can see this by comparing the memory usage and system load of the v8a-only build and all other builds.

**Comment by reisxd** [comment]
> This is because of the memory used (including cache memory). An apk that includes all architectures will have more running memory (including cache space). You can see this by comparing the memory usage and system load of the v8a-only build and all other builds.

Android will only load the libraries for your devices architecture. It'll not load anything else.

**Comment by root-kernelhacker** [comment]
> > This is because of the memory used (including cache memory). An apk that includes all architectures will have more running memory (including cache space). You can see this by comparing the memory usage and system load of the v8a-only build and all other builds.
> 
> Android will only load the libraries for your devices architecture. It'll not load anything else.

I basically know that, but when I monitor it on the devices I actually test, the memory occupancy (including cache) of the v8a-only apk and the apk for all architectures is different.  Also, the load on the AP is different.  It's not just the amount of storage space it takes up.  It is true that the developers who build and distribute v8a-only apk already know.  Additionally, reducing storage space is also important.  Thanks for your answer.  Lastly, is there a way to convert an already patched apk or an original apk or a built apk to a v8a-only apk?

**Comment by PalmDevs** [comment]
> > > This is because of the memory used (including cache memory). An apk that includes all architectures will have more running memory (including cache space). You can see this by comparing the memory usage and system load of the v8a-only build and all other builds.
> > 
> > Android will only load the libraries for your devices architecture. It'll not load anything else.
> 
> I basically know that, but when I monitor it on the devices I actually test, the memory occupancy (including cache) of the v8a-only apk and the apk for all architectures is different.  Also, the load on the AP is different.  It's not just the amount of storage space it takes up.  It is true that the developers who build and distribute v8a-only apk already know.  Additionally, reducing storage space is also important.  Thanks for your answer.  Lastly, is there a way to convert an already patched apk or an original apk or a built apk to a v8a-only apk?

Architecture specific APKs are basically just full APKs with removed unneeded libraries. You can simply remove other architecture's shared object files from the `lib` folder when the APK is extracted.
