### ISSUE TITLE
bug: OutOfMemoryError while patching twitch

### ISSUE THREAD

**Issue by Crafter-Y** [ReVanced/revanced-manager#1049]
### Type

Error while running the manager

### Bug description

When I try to patch the twitch app, it aborts with an OutOfMemoryError at writing modified dex files.

### Steps to reproduce

1. Download the newest Revanced Manager
2. Download the recommended twitch apk (15.4.1)
3. Select some patches
4. Patch the application 

### Android version

Android 11, Xiomi note 11

### Manager version

Newest (1.4.3)

### Target package name

tv.twitch.android.app

### Target package version.

15.4.1

### Installation type

Non-root

### Patches selected.

![Screenshot_2023-07-24-12-35-22-118-edit_app revanced manager flutter](https://github.com/ReVanced/revanced-manager/assets/71288761/fe5b9065-cbe7-4c84-9015-d0e172e984d5)

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
07-24 00:49:11.441 10211 10211 W ActivityThread: registerApplicationScoutThread result:true
07-24 00:49:11.581 10211 10211 I ForceDarkHelper: mForceDarkOrigin true
07-24 12:05:25.207 21303 21303 W ActivityThread: registerApplicationScoutThread result:true
07-24 12:05:25.282 21303 21303 I ForceDarkHelper: mForceDarkOrigin true
07-24 12:05:25.298 21303 21303 I ContentProviderMonitor: PerfMonitor installContentProviders : before publish content providers
07-24 12:05:26.013 21303 21303 W Looper  : PerfMonitor doFrame : time=0ms vsyncFrame=11976782 latency=352ms procState=2 historyMsgCount=1 (msgIndex=1 wall=360ms seq=23 running=33ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
07-24 12:06:18.394 21303 21303 I Timeline: Timeline: Activity_launch_request time:1137110052
07-24 12:06:35.707 23178 23178 W ActivityThread: registerApplicationScoutThread result:true
07-24 12:06:35.758 23178 23178 I ForceDarkHelper: mForceDarkOrigin true
07-24 12:06:35.796 23178 23178 I ContentProviderMonitor: PerfMonitor installContentProviders : before publish content providers
07-24 12:06:36.524 23178 23178 W Looper  : PerfMonitor doFrame : time=1ms vsyncFrame=11980357 latency=362ms procState=2 historyMsgCount=1 (msgIndex=1 wall=373ms seq=23 running=39ms runnable=1ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
07-24 12:06:37.583 23178 23178 W Looper  : PerfMonitor doFrame : time=0ms vsyncFrame=0 latency=312ms procState=2 historyMsgCount=1 (msgIndex=1 wall=448ms seq=94 running=42ms runnable=1ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
07-24 12:06:49.045 23178 23178 I Timeline: Timeline: Activity_launch_request time:1137140703
07-24 12:14:25.734 23178 23178 W BpBinder: Slow Binder: BpBinder transact took 322 ms, interface=android.view.IWindowSession, code=29 oneway=false
07-24 12:14:25.744 23178 23178 W Looper  : PerfMonitor doFrame : time=9ms vsyncFrame=11982382 latency=306ms procState=12 historyMsgCount=1 (msgIndex=1 wall=323ms seq=357 runnable=4ms late=1ms h=android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate w=2)
07-24 12:33:55.067  5704  5704 W ActivityThread: registerApplicationScoutThread result:true
07-24 12:33:55.118  5704  5704 I ForceDarkHelper: mForceDarkOrigin true
07-24 12:33:55.137  5704  5704 I ContentProviderMonitor: PerfMonitor installContentProviders : before publish content providers
07-24 12:33:55.788  5704  5704 W Looper  : PerfMonitor doFrame : time=0ms vsyncFrame=12040655 latency=351ms procState=2 historyMsgCount=1 (msgIndex=1 wall=351ms seq=17 running=35ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
07-24 12:35:04.509  5704  5704 I Timeline: Timeline: Activity_launch_request time:1138772757
07-24 12:36:06.629  5704  5704 I Timeline: Timeline: Activity_launch_request time:1138834877
--------- beginning of main
07-24 12:36:31.395  5704  7140 D AnrScout: AppScoutStateMachine created
07-24 12:36:31.424  5704  5704 D FrameIndicator: support status: 1 0x7059515018 0x70595154c4
07-24 12:36:31.427  5704  5704 D FrameIndicator: support status: 1 0x7059515018 0x70595154c4
```

### Screenshots or video

![Screenshot_2023-07-24-12-16-15-402_app revanced manager flutter](https://github.com/ReVanced/revanced-manager/assets/71288761/74cb1505-6912-4559-8b06-49e5c9f6e206)
![Screenshot_2023-07-24-12-16-11-714_app revanced manager flutter](https://github.com/ReVanced/revanced-manager/assets/71288761/7efb51ee-53a2-4faa-8b5d-92ef5f3194b0)

### Solution

I saw this error in other issues and the problem seems to be, that the manager can only use 256mb of ram to start the dexlib. When this limit is exceed, the patching crashed

### Additional context

I tried this a couple times, restarting my device, updating the manager, redownloading the twitch apk.

### Acknowledgments

- [ ] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by pixkk** [comment]
That is, there will be no solution to the problem, did I understand correctly?If not, what will I be asked to do as a user?

**Comment by Ushie** [comment]
In the mean time, you can use ReVanced CLI, you can join the [discord server](https://revanced.app/discord) for help with that

**Comment by pixkk** [comment]
> In the mean time, you can use ReVanced CLI, you can join the [discord server](https://revanced.app/discord) for help with that

Okay, thank you for response 👌
