### ISSUE TITLE
feat: add armv7 support to ReVanced Manager

### ISSUE THREAD

**Issue by minou2020** [ReVanced/revanced-manager#1067]
### Type

Functionality

### Issue

Currently ReVanced Manager doesn't support armv7 devices
I currently use LibreTube (as my device is armv7) but its "show dislike" is broken and shows -1 on all videos, and I can't download videos.
I tried to patch a YouTube apk device using ReVanced Manager, but it "aborted"
I can't patch via PC because I don't have admin rights

### Feature

Add support to ARMv7 devices

### Motivation

It'd allow more people to benefit from YouTube ReVanced

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by validcube** [comment]
Duplicated of #1016, #879, #480, #423, and lastly the first issue about ARMv7 #268
