### ISSUE TITLE
feat: Reddit app patch - User-Agent change to avoid blocking

### ISSUE THREAD

**Issue by ltclarke** [ReVanced/revanced-manager#1073]
### Type

Functionality

### Issue

RIF and other apps that briefly worked with the OATH patch, are now blocked based on their User-Agent value.

### Feature

In the same way we can patch the OATH ID, it would be nice if we could patch for the User-Agent to be something unique or generic to pass the test/block

### Motivation

In addition to RIF, this would help the other 3rd party reddit apps that were added to patch support recently

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
Acknowledgements not met, this belongs to ReVanced Patches
