### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by cenimm** [revanced/revanced-manager#108]
### Type

Functionality

### Branch

Revanced Manager

### Issue

It will overwrite my original app. 

### Feature

It would be awesome if manager change the name of the app it patched so we can still update the original to get the latest version all the time instead of install like YouTube then revanced it and then uninstall wait for a update uninstall the patched version install new app and repeat. 

### Motivation

For user it will be easy-to-use.

**Comment by iseos** [comment]
It would also be nice to be able to enter the name of the application yourself.

**Comment by ponces** [comment]
You are referring to package name, not app's name.
This is responsability of patches, not Manager.
