### ISSUE TITLE
Aborted

### ISSUE THREAD

**Issue by PsychoAnees** [ReVanced/revanced-manager#1081]
### Type

Error at runtime

### Bug description

after clicking patch button, it starts to patch the application but gets aborted (btw note that i was using revanced extended)

### Steps to reproduce

i just selected the same patches i use before but this time its getting aborted

### Android version

13

### Manager version

1.6.1

### Target package name

youtube

### Target package version.

v.18.29.38

### Installation type

Non-root

### Patches selected.

![Screenshot_20230804_094937](https://github.com/ReVanced/revanced-manager/assets/96819416/08cd1633-186f-4b34-86e1-3f30781d2c0a)

### Device logs (exported using Manager settings).

```shell
Version: 1.6.1
Model: SM-A525F
Android Version: 13
Supported Archs: arm64-v8a, armeabi-v7a, armeabi
```

### Screenshots or video

![Screenshot_20230804_095607](https://github.com/ReVanced/revanced-manager/assets/96819416/edca96be-360e-4106-a555-3f0265da91ed)
![Screenshot_20230804_095614](https://github.com/ReVanced/revanced-manager/assets/96819416/8ad60a0d-3106-4274-9d7a-0ea322822049)
![Screenshot_20230804_095620](https://github.com/ReVanced/revanced-manager/assets/96819416/532845e3-3463-487c-9b97-f4b2847e16e9)

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by TheAabedKhan** [comment]
No support for patching errors caused due to the use of sources other than the official ones.
