### ISSUE TITLE
bug: InvocationTargetException

### ISSUE THREAD

**Issue by Jakekick99** [ReVanced/revanced-manager#1085]
### Type

Error at runtime

### Bug description

Trying to patch with revanced manager version 1.6.1 and multiple youtube versions including v18.29.39 and v18.23.35 (which doesn't allow patches without turning on experimental) lead to the InvocationTargetException caused by java.lang.ClassNotFoundException

The class in question is com.android.tools.smali.dexlib2.AccessFlags ....

### Steps to reproduce

1. Use 1.6.1 Revanced Manager
2. Download and use Youtube APK version 18.29.18
3. Apply default patch

### Android version

Moto g73 5g
Android Version 13

### Manager version

1.6.1

### Target package name

YouTube

### Target package version.

18.29.38

### Installation type

Non-root

### Patches selected.

Default

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
08-04 15:07:10.555 26132 26132 D ViewRootImpl: update {(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION wanim=0x1030001
08-04 15:07:10.555 26132 26132 D ViewRootImpl:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
08-04 15:07:10.555 26132 26132 D ViewRootImpl:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
08-04 15:07:10.555 26132 26132 D ViewRootImpl:   bhv=DEFAULT
08-04 15:07:10.555 26132 26132 D ViewRootImpl:   fitSides=} by setView
08-04 15:07:19.806 26132 26132 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.29.38-1539044800_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #41
08-04 15:07:19.807 26132 26132 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.29.38-1539044800_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #418
08-04 15:07:22.719 26132 26132 D VRI[MainActivity]: update {(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x1030001
08-04 15:07:22.719 26132 26132 D VRI[MainActivity]:   fl=KEEP_SCREEN_ON LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
08-04 15:07:22.719 26132 26132 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
08-04 15:07:22.719 26132 26132 D VRI[MainActivity]:   bhv=DEFAULT
08-04 15:07:22.719 26132 26132 D VRI[MainActivity]:   fitSides=} by setLayoutParams
08-04 15:08:11.320 26132 26132 D VRI[MainActivity]: update {(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x1030001
08-04 15:08:11.320 26132 26132 D VRI[MainActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
08-04 15:08:11.320 26132 26132 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
08-04 15:08:11.320 26132 26132 D VRI[MainActivity]:   bhv=DEFAULT
08-04 15:08:11.320 26132 26132 D VRI[MainActivity]:   fitSides=} by setLayoutParams
08-04 15:20:32.011 26132 26132 D VRI[MainActivity]: update {(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION fmt=TRANSLUCENT wanim=0x1030001
08-04 15:20:32.011 26132 26132 D VRI[MainActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
08-04 15:20:32.011 26132 26132 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND USE_BLAST APPEARANCE_CONTROLLED FIT_INSETS_CONTROLLED
08-04 15:20:32.011 26132 26132 D VRI[MainActivity]:   vsysui=LAYOUT_STABLE LAYOUT_HIDE_NAVIGATION LAYOUT_FULLSCREEN
08-04 15:20:32.011 26132 26132 D VRI[MainActivity]:   bhv=DEFAULT
08-04 15:20:32.011 26132 26132 D VRI[MainActivity]:   fitSides=} by setLayoutParams
08-04 15:21:16.403 26132 26132 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.29.38-1539044800_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #41
08-04 15:21:16.407 26132 26132 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.29.38-1539044800_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #418
08-04 15:21:35.192 26132 26132 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com_google_android_youtube_18_23_35_1538252224_minAPI26arm64_v8a.apk Binary XML file line #41
08-04 15:21:35.193 26132 26132 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com_google_android_youtube_18_23_35_1538252224_minAPI26arm64_v8a.apk Binary XML file line #417
08-04 15:22:06.306 26132 26132 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com_google_android_youtube_18_23_35_1538252224_minAPI26arm64_v8a.apk Binary XML file line #41
08-04 15:22:06.306 26132 26132 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com_google_android_youtube_18_23_35_1538252224_minAPI26arm64_v8a.apk Binary XML file line #417
08-04 15:22:07.551 26132 26132 D VRI[MainActivity]: update {(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x1030001
08-04 15:22:07.551 26132 26132 D VRI[MainActivity]:   fl=KEEP_SCREEN_ON LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
08-04 15:22:07.551 26132 26132 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
08-04 15:22:07.551 26132 26132 D VRI[MainActivity]:   bhv=DEFAULT
08-04 15:22:07.551 26132 26132 D VRI[MainActivity]:   fitSides=} by setLayoutParams
08-04 15:22:24.040 26132 26132 D VRI[MainActivity]: update {(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x1030001
08-04 15:22:24.040 26132 26132 D VRI[MainActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
08-04 15:22:24.040 26132 26132 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
08-04 15:22:24.040 26132 26132 D VRI[MainActivity]:   bhv=DEFAULT
08-04 15:22:24.040 26132 26132 D VRI[MainActivity]:   fitSides=} by setLayoutParams
08-04 15:22:39.011 31932 31932 D ViewRootImpl: update {(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION wanim=0x1030001
08-04 15:22:39.011 31932 31932 D ViewRootImpl:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
08-04 15:22:39.011 31932 31932 D ViewRootImpl:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
08-04 15:22:39.011 31932 31932 D ViewRootImpl:   bhv=DEFAULT
08-04 15:22:39.011 31932 31932 D ViewRootImpl:   fitSides=} by setView
08-04 15:22:44.448 31932 31932 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com_google_android_youtube_18_23_35_1538252224_minAPI26arm64_v8a.apk Binary XML file line #41
08-04 15:22:44.448 31932 31932 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com_google_android_youtube_18_23_35_1538252224_minAPI26arm64_v8a.apk Binary XML file line #417
08-04 15:22:47.806 31932 31932 D VRI[MainActivity]: update {(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x1030001
08-04 15:22:47.806 31932 31932 D VRI[MainActivity]:   fl=KEEP_SCREEN_ON LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
08-04 15:22:47.806 31932 31932 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
08-04 15:22:47.806 31932 31932 D VRI[MainActivity]:   bhv=DEFAULT
08-04 15:22:47.806 31932 31932 D VRI[MainActivity]:   fitSides=} by setLayoutParams
08-04 15:23:35.994 31932 31932 D VRI[MainActivity]: update {(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x1030001
08-04 15:23:35.994 31932 31932 D VRI[MainActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
08-04 15:23:35.994 31932 31932 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
08-04 15:23:35.994 31932 31932 D VRI[MainActivity]:   bhv=DEFAULT
08-04 15:23:35.994 31932 31932 D VRI[MainActivity]:   fitSides=} by setLayoutParams
--------- beginning of main
08-04 15:24:45.681 31932 31942 W System  : A resource failed to call close. 
08-04 15:25:23.773 31932 31932 D VRI[MainActivity]: update {(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION fmt=TRANSLUCENT wanim=0x1030001
08-04 15:25:23.773 31932 31932 D VRI[MainActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
08-04 15:25:23.773 31932 31932 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND USE_BLAST APPEARANCE_CONTROLLED FIT_INSETS_CONTROLLED
08-04 15:25:23.773 31932 31932 D VRI[MainActivity]:   vsysui=LAYOUT_STABLE LAYOUT_HIDE_NAVIGATION LAYOUT_FULLSCREEN
08-04 15:25:23.773 31932 31932 D VRI[MainActivity]:   bhv=DEFAULT
08-04 15:25:23.773 31932 31932 D VRI[MainActivity]:   fitSides=} by setLayoutParams
08-04 15:25:23.787 31932 31932 D BufferQueueConsumer: [](id:7cbc00000004,api:0,p:-1,c:31932) connect: controlledByApp=false
08-04 15:25:23.798 31932 31932 D BufferQueueConsumer: [](id:7cbc00000005,api:0,p:-1,c:31932) connect: controlledByApp=false
08-04 15:25:23.811 31932 31932 E SurfaceSyncer: Failed to find sync for id=0
08-04 15:25:23.811 31932 31932 E SurfaceSyncer: Failed to find sync for id=1
08-04 15:25:23.811 31932 31932 E SurfaceSyncer: Failed to find sync for id=2
08-04 15:25:23.811 31932 31932 E SurfaceSyncer: Failed to find sync for id=3
08-04 15:25:23.818 31932 31948 D BLASTBufferQueue: [VRI[MainActivity]#4](f:0,a:1) acquireNextBufferLocked size=1080x2400 mFrameNumber=1 applyTransaction=true mTimestamp=246320471242373(auto) mPendingTransactions.size=0 graphicBufferId=137146895695888 transform=0
08-04 15:25:23.820 31932 31955 D BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#5](f:0,a:1) acquireNextBufferLocked size=1080x2400 mFrameNumber=1 applyTransaction=true mTimestamp=246320475834373(auto) mPendingTransactions.size=0 graphicBufferId=137146895695887 transform=0
08-04 15:25:27.304 31932 31932 D FilePickerUtils: Allowed file extensions mimes: [application/vnd.android.package-archive]
08-04 15:25:27.305 31932 31932 D FilePickerDelegate: Selected type */*
08-04 15:25:27.884 31932 31932 D BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#5](f:0,a:1) destructor()
08-04 15:25:27.884 31932 31932 D BufferQueueConsumer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#5(BLAST Consumer)5](id:7cbc00000005,api:0,p:-1,c:31932) disconnect
08-04 15:25:27.901 31932 31932 D BLASTBufferQueue: [VRI[MainActivity]#4](f:0,a:1) destructor()
08-04 15:25:27.901 31932 31932 D BufferQueueConsumer: [VRI[MainActivity]#4(BLAST Consumer)4](id:7cbc00000004,api:0,p:-1,c:31932) disconnect
08-04 15:25:31.425 31932 31932 I InstallPlugin: handleActivityResult(29789,-1,Intent { dat=content://com.android.providers.downloads.documents/... flg=0x1 })
08-04 15:25:31.426 31932  3884 I FilePickerUtils: Caching from URI: content://com.android.providers.downloads.documents/document/msf%3A1000005854
08-04 15:25:31.445 31932 31932 D BufferQueueConsumer: [](id:7cbc00000006,api:0,p:-1,c:31932) connect: controlledByApp=false
08-04 15:25:31.449 31932 31932 D BufferQueueConsumer: [](id:7cbc00000007,api:0,p:-1,c:31932) connect: controlledByApp=false
08-04 15:25:31.454 31932 31932 E SurfaceSyncer: Failed to find sync for id=0
08-04 15:25:31.454 31932 31932 E SurfaceSyncer: Failed to find sync for id=1
08-04 15:25:31.454 31932 31932 E SurfaceSyncer: Failed to find sync for id=2
08-04 15:25:31.454 31932 31932 E SurfaceSyncer: Failed to find sync for id=3
08-04 15:25:31.454 31932 31932 E SurfaceSyncer: Failed to find sync for id=4
08-04 15:25:31.458 31932 31948 D BLASTBufferQueue: [VRI[MainActivity]#6](f:0,a:1) acquireNextBufferLocked size=1080x2400 mFrameNumber=1 applyTransaction=true mTimestamp=246328113751989(auto) mPendingTransactions.size=0 graphicBufferId=137146895695895 transform=0
08-04 15:25:31.464 31932 31955 D BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#7](f:0,a:1) acquireNextBufferLocked size=1080x2400 mFrameNumber=1 applyTransaction=true mTimestamp=246328119943297(auto) mPendingTransactions.size=0 graphicBufferId=137146895695894 transform=0
08-04 15:25:32.138 31932  3884 D FilePickerUtils: File loaded and cached at:/data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.29.38-1539044800_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk
08-04 15:25:32.138 31932  3884 D FilePickerDelegate: File path:[com.mr.flutter.plugin.filepicker.FileInfo@61504fa]
08-04 15:25:32.146 31932 31932 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.29.38-1539044800_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #41
08-04 15:25:32.147 31932 31932 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.29.38-1539044800_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #418
```

### Screenshots or video

![image](https://github.com/ReVanced/revanced-manager/assets/55398802/884a6ed9-418d-410f-8a36-ba6361defc2b)
![image](https://github.com/ReVanced/revanced-manager/assets/55398802/cd20f263-f670-4e0a-b86d-9a24edb1a3ef)

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by TheAabedKhan** [comment]
Reading the logs, I see you are using YouTube v18.29.38 which may be causing this issue. Can you try again using the suggested version, v18.23.35? As you are not rooted, use the `nodpi` variant.

**Comment by Jakekick99** [comment]
The same error still occurs. The log is as below:

--------- beginning of system
08-04 16:07:00.988 21671 21671 D ViewRootImpl: update {(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION wanim=0x1030001
08-04 16:07:00.988 21671 21671 D ViewRootImpl:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
08-04 16:07:00.988 21671 21671 D ViewRootImpl:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
08-04 16:07:00.988 21671 21671 D ViewRootImpl:   bhv=DEFAULT
08-04 16:07:00.988 21671 21671 D ViewRootImpl:   fitSides=} by setView
--------- beginning of main
08-04 16:07:07.586 21671 21671 D FilePickerUtils: Allowed file extensions mimes: [application/vnd.android.package-archive]
08-04 16:07:07.587 21671 21671 D FilePickerDelegate: Selected type */*
08-04 16:07:08.213 21671 21671 D BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1](f:0,a:1) destructor()
08-04 16:07:08.213 21671 21671 D BufferQueueConsumer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1(BLAST Consumer)1](id:54a700000001,api:0,p:-1,c:21671) disconnect
08-04 16:07:08.222 21671 21671 D BLASTBufferQueue: [VRI[MainActivity]#0](f:0,a:1) destructor()
08-04 16:07:08.222 21671 21671 D BufferQueueConsumer: [VRI[MainActivity]#0(BLAST Consumer)0](id:54a700000000,api:0,p:-1,c:21671) disconnect
08-04 16:07:12.468 21671 21679 W manager.flutter: Cleared Reference was only reachable from finalizer (only reported once)
08-04 16:07:12.945 21671 21671 D CompatibilityChangeReporter: Compat change id reported: 78294732; UID 10424; state: ENABLED
08-04 16:07:12.946 21671 21671 I InstallPlugin: handleActivityResult(29789,-1,Intent { dat=content://com.android.providers.downloads.documents/... flg=0x1 })
08-04 16:07:12.947 21671 22711 I FilePickerUtils: Caching from URI: content://com.android.providers.downloads.documents/document/msf%3A1000005861
08-04 16:07:12.967 21671 21671 D BufferQueueConsumer: [](id:54a700000002,api:0,p:-1,c:21671) connect: controlledByApp=false
08-04 16:07:12.974 21671 21671 D BufferQueueConsumer: [](id:54a700000003,api:0,p:-1,c:21671) connect: controlledByApp=false
08-04 16:07:12.984 21671 21671 E SurfaceSyncer: Failed to find sync for id=0
08-04 16:07:12.984 21671 21671 E SurfaceSyncer: Failed to find sync for id=1
08-04 16:07:12.984 21671 21671 E SurfaceSyncer: Failed to find sync for id=2
08-04 16:07:12.989 21671 21688 D BLASTBufferQueue: [VRI[MainActivity]#2](f:0,a:1) acquireNextBufferLocked size=1080x2400 mFrameNumber=1 applyTransaction=true mTimestamp=248043456434245(auto) mPendingTransactions.size=0 graphicBufferId=93076236271625 transform=0
08-04 16:07:12.993 21671 21696 D BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#3](f:0,a:1) acquireNextBufferLocked size=1080x2400 mFrameNumber=1 applyTransaction=true mTimestamp=248043459499783(auto) mPendingTransactions.size=0 graphicBufferId=93076236271624 transform=0
08-04 16:07:13.619 21671 22711 D FilePickerUtils: File loaded and cached at:/data/user/0/app.revanced.manager.flutter/cache/file_picker/com_google_android_youtube_18_23_35_1538252224_minAPI26arm64_v8a.apk
08-04 16:07:13.619 21671 22711 D FilePickerDelegate: File path:[com.mr.flutter.plugin.filepicker.FileInfo@dbc7a0d]
08-04 16:07:13.631 21671 21671 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com_google_android_youtube_18_23_35_1538252224_minAPI26arm64_v8a.apk Binary XML file line #41
08-04 16:07:13.632 21671 21671 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com_google_android_youtube_18_23_35_1538252224_minAPI26arm64_v8a.apk Binary XML file line #417
08-04 16:07:17.795 22724 22724 W sh      : type=1400 audit(0.0:88674): avc: denied { read } for name="/" dev="dm-16" ino=59 scontext=u:r:untrusted_app:s0:c168,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-04 16:07:17.803 22724 22724 W sh      : type=1400 audit(0.0:88675): avc: denied { read } for name="/" dev="dm-16" ino=59 scontext=u:r:untrusted_app:s0:c168,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-04 16:07:17.815 22724 22724 W sh      : type=1400 audit(0.0:88676): avc: denied { read } for name="/" dev="dm-16" ino=59 scontext=u:r:untrusted_app:s0:c168,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-04 16:07:17.827 22724 22724 W sh      : type=1400 audit(0.0:88677): avc: denied { read } for name="/" dev="dm-16" ino=59 scontext=u:r:untrusted_app:s0:c168,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-04 16:07:17.835 22724 22724 W sh      : type=1400 audit(0.0:88678): avc: denied { read } for name="/" dev="dm-16" ino=59 scontext=u:r:untrusted_app:s0:c168,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
08-04 16:07:18.318 21671 21671 D VRI[MainActivity]: update {(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x1030001
08-04 16:07:18.318 21671 21671 D VRI[MainActivity]:   fl=KEEP_SCREEN_ON LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
08-04 16:07:18.318 21671 21671 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
08-04 16:07:18.318 21671 21671 D VRI[MainActivity]:   bhv=DEFAULT
08-04 16:07:18.318 21671 21671 D VRI[MainActivity]:   fitSides=} by setLayoutParams
08-04 16:07:19.244 21671 21681 W System  : A resource failed to call close. 
08-04 16:07:23.113 21671 21679 I manager.flutter: Background concurrent copying GC freed 712794(27MB) AllocSpace objects, 16(10112KB) LOS objects, 43% free, 123MB/219MB, paused 57us,24us total 189.891ms
08-04 16:07:37.916 21671 21679 I manager.flutter: Background concurrent copying GC freed 3319937(125MB) AllocSpace objects, 15(11MB) LOS objects, 46% free, 110MB/206MB, paused 48us,24us total 181.843ms
08-04 16:07:37.916 21671 21681 W System  : A resource failed to call close. 
08-04 16:07:40.727 21671 21679 I manager.flutter: Background concurrent copying GC freed 1853725(69MB) AllocSpace objects, 10(9860KB) LOS objects, 34% free, 182MB/278MB, paused 58us,16us total 336.789ms
08-04 16:08:06.969 21671 21671 D VRI[MainActivity]: update {(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x1030001
08-04 16:08:06.969 21671 21671 D VRI[MainActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
08-04 16:08:06.969 21671 21671 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
08-04 16:08:06.969 21671 21671 D VRI[MainActivity]:   bhv=DEFAULT
08-04 16:08:06.969 21671 21671 D VRI[MainActivity]:   fitSides=} by setLayoutParams
08-04 16:09:53.770 21671 21671 W LongScreenshotUtils: findMainScrollView topViewName_0; name: app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity/android.view.ViewRootImpl@8e20d33
08-04 16:09:58.605 21671 21671 W LongScreenshotUtils: findMainScrollView topViewName_0; name: app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity/android.view.ViewRootImpl@8e20d33

The screenshots are identical when patching.

Further, the manager tells me that the patches are not supported and so I enabled experimental patches support to do this

**Comment by TheAabedKhan** [comment]
Can you send a screen recording showing each step you followed?

**Comment by Jakekick99** [comment]
https://github.com/ReVanced/revanced-manager/assets/55398802/8edc1b48-bd98-450c-b21d-322f4b090b37

**Comment by TheAabedKhan** [comment]
I see. Looks like you are using custom sources. We do not provide support for them. Try to patch using the official sources and if you get any error, we will definitely look into it.

**Comment by Ushie** [comment]
It seems that ReVanced Extended no longer is compatible with the official ReVanced Patcher, and are now using their own

**Comment by KobeW50** [comment]
@Jakekick99 use the rvx Manager for revanced extended.

https://github.com/inotia00/revanced-manager/releases/latest
