### ISSUE TITLE
Showing Ads 

### ISSUE THREAD

**Issue by mjain234** [revanced/revanced-manager#109]
Hi there
After just installing Revanced, i still could see some ads in home page of the app which is more than one ad, is it a known issue?

See this video for more: https://user-images.githubusercontent.com/70900505/190494678-548f114a-e8d1-44e3-92b7-352ed247dfcd.mp4

**Comment by Aunali321** [comment]
Not manager issue. Open issue on [patches](https://github.com/revanced/revanced-patches).
