### ISSUE TITLE
bug: "Delete logs" doesn't delete logs

### ISSUE THREAD

**Issue by xehpuk** [ReVanced/revanced-manager#1094]
### Type

Error while running the manager

### Bug description

Collected manager logs do not get deleted.

### Steps to reproduce

1. Press "Delete logs" in Settings.
2. Press "Logs" in Settings.
3. Open shared file and see log entries with timestamps before the requested deletion.

### Android version

13

### Manager version

1.6.1

### Target package name

-

### Target package version.

-

### Installation type

Root

### Patches selected.

-

### Device logs (exported using Manager settings).

```shell
-
```

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by oSumAtrIX** [comment]
Reopen if this still happens.
