### ISSUE TITLE
bug: ReVanced Manager always freezes

### ISSUE THREAD

**Issue by LucaPisl** [ReVanced/revanced-manager#1095]
### Type

Error while running the manager

### Bug description

The ReVanced app freezes and opens Magisk Manager by itself. When switching back to ReVanced, I can't press any button and re-opening it lands me back at square one and simply reproduces the bug.

### Steps to reproduce

1. Download ReVanced Manager
2. Open ReVanced Manager
3. App freezes (without the standard Android close app or wait prompt)
4. Magisk Manager opens by itself

### Android version

Android 11, One UI 3.1, rooted with Magisk

### Manager version

v1.6.1

### Target package name

N/A

### Target package version.

N/A

### Installation type

Root

### Patches selected.

N/A

### Device logs (exported using Manager settings).

```shell
N/A
```

### Solution

N/A

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by oSumAtrIX** [comment]
Fill all requested information properly in a new issue.
