### ISSUE TITLE
Newest release doesn't even open

### ISSUE THREAD

**Issue by frozen905** [ReVanced/revanced-manager#1100]
### Type

Error at runtime

### Bug description

Installed latest version from GitHub onto a brand new Formuler Z11 Pro Max Android device. 

App does not even open. Shows a white screen then dumps back to the launcher with no output 

### Steps to reproduce

Open App
App Crashes 

### Android version

11

### Manager version

New

### Target package name

NA

### Target package version.

NA

### Installation type

Non-root

### Patches selected.

NA

### Device logs (exported using Manager settings).

```shell
Can't access them
```

### Screenshots or video

https://mega.nz/file/FtZxGIpa#ryzWbw7lXPDngdmUNqBQgQ6AHl1AGPJ_dLvc6-OrYLI

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by validcube** [comment]
It appears to be an Android TV box, we don't provide support for them.
