### ISSUE TITLE
bug: `Auto update?`

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-manager#1103]
### Type

Error while running the manager

### Bug description

Just like the title says, it's confusing to have an option just saying "Auto update?" within the manager. Yes, reading the description clarifies what it does but still someone could consider it as an option to auto update the manager as well. Also it's weird to have an option within a question mark. I understand it's required when opening the manager for the first time but why in the settings though. Instead it should be simple like "Auto-update ReVanced Patches" just like the other options within the ReVanced Manager settings.

### Steps to reproduce

1) Open the manager in the latest version (v1.7.0)
2) Go into settings.
3) Notice "Auto update?" option.

### Android version

Android 13

### Manager version

1.7.0

### Target package name

ReVanced Manager 

### Target package version.

ReVanced Manager 

### Installation type

Non-root

### Patches selected.

Nil

### Device logs (exported using Manager settings).

```shell
Nil
```

### Screenshots or video

ReVanced Manager settings:
![Screenshot_20230808-100713~2](https://github.com/ReVanced/revanced-manager/assets/117499019/8f31ff78-0019-465f-82b7-4e5f3778fe82)

Google Play Store settings (Motivation):
![Screenshot_20230808-102049~2](https://github.com/ReVanced/revanced-manager/assets/117499019/5adb3902-8b3e-4836-be91-ff3b7d6f1372)

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by Ushie** [comment]
This is a bug, will be resolved in the next release
