### ISSUE TITLE
bug: error while patching: "Map already initialized"

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVanced/revanced-manager#1104]
### Type

Error while running the manager

### Bug description

If the user cancels patching, and then tries to patch again, Manager gives a patcher error for all repeat patching attempts. 

### Steps to reproduce

- Start to patch any app
- Cancel the patching
- Try to patch again

Patcher gives "Map already initialized" error

### Manager version

1.9.3

## HOW TO FIX:
- Close Manager and stop it running in the background
- Reopen Manager
- Patch as usual

This problem will continue to exist until Manager can update it's Patcher dependency.

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by oSumAtrIX** [comment]
@LisoUseInAIKyrios regarding that, have you received my mail?

**Comment by oSumAtrIX** [comment]
I don't think this is an issue that the ReVanced Manager should solve or handle. The issue may be closed, either when the dependency is updated or now, in case it is considered a matter of ReVanced Patcher.

**Comment by CoyoteLeo** [comment]
To someone who encounters this issue, please clean all the data/cache of the revanced-manager. I solved the problem after the cleaning.
