### ISSUE TITLE
bug: All patches are marked as new 

### ISSUE THREAD

**Issue by xDARKxDEVILx** [ReVanced/revanced-manager#1111]
### Type

Error while running the manager

### Bug description

Using version 1.7.0 for the first time I didn't see any new labels then after patching once, all patches became new

### Steps to reproduce

Already written 

### Android version

11

### Manager version

1.7.0

### Target package name

YouTube 

### Target package version.

18.23.35

### Installation type

Non-root

### Patches selected.

.

### Device logs (exported using Manager settings).

```shell
.
```

### Screenshots or video

This is without the label for first time patching 

![IMG_20230808_134513](https://github.com/ReVanced/revanced-manager/assets/120474122/751949cc-43a1-4643-8c5e-a5f91764d450)

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by xDARKxDEVILx** [comment]
Wrong img lol, but i don't know how to edit to add new one

**Comment by xDARKxDEVILx** [comment]
![Screenshot_2023-08-08-14-00-30-908_app revanced manager flutter](https://github.com/ReVanced/revanced-manager/assets/120474122/31a3546b-6a09-4b43-a84f-5c4f8a7cab8d)

**Comment by ILoveOpenSourceApplications** [comment]
Closing as issue is resolved with #1113 .
