### ISSUE TITLE
Manager crashes right after the executing patches message 

### ISSUE THREAD

**Issue by Fi9l** [ReVanced/revanced-manager#1112]
### Type

Error while running the manager

### Bug description

When i try patching youtube it goes half way through and then i get an "executing patches" message on the log and then it crashes. 

### Steps to reproduce

Choose youtube then recommended patches then patch then wait a little until the message pops up

### Android version

I think its emui 10.0.0.231

### Manager version

The latest version 

### Target package name

Youtube recommended version too

### Target package version.

The recommended one 18.23.35

### Installation type

Non-root

### Patches selected.

All recommended patches except url button and remove cast button

### Device logs (exported using Manager settings).

```shell
I dont know how to do this
```

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by TheAabedKhan** [comment]
Screen recording would be helpful

**Comment by Ushie** [comment]
Closing due to no response + not enough information
