### ISSUE TITLE
feat: Improve the FAB in ReVanced Manager 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-manager#1117]
### Type

Cosmetic

### Issue

Right now, the manager is having two FABs, one when selecting an application to patch and the second when selecting the patches for an application. Both the screens require scrolling and with this implementation.

### Feature

By implementing a retractable(I am not sure of the terminology here) icon which expands with the icon and text by default/scrolling up and when scrolling down shrinks to just the icon.

What I mean in a different app environment:

https://github.com/ReVanced/revanced-manager/assets/117499019/402975df-154a-4066-81c6-6cd09f0d704f

### Motivation

Better visibility when selecting the patches and confirming whether all the patches selected and needed or not. Also makes the UI look better.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by AdiAr11** [comment]
Hi, I would like to try and work on this issue. Is it still needed?

**Comment by oSumAtrIX** [comment]
@AdiAr11 A PR will be very welcome
