### ISSUE TITLE
bug: snack bar position is not proper 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-manager#1118]
### Type

Cosmetic

### Bug description

Well the easiest way to reproduce a snack bar is when refresh while on the dashboard and "Refreshed successfully" snack bar pops up right in between the app layout and the navigation bar. But it should appear above the navigation bar.

### Steps to reproduce

1) Open the ReVanced manager.
2) Swipe down to refresh.
3) Notice the snack bar position.

### Android version

Android 13

### Manager version

1.7.0

### Target package name

ReVanced Manager 

### Target package version.

Any

### Installation type

Non-root

### Patches selected.

Nil

### Device logs (exported using Manager settings).

```shell
Nil
```

### Screenshots or video

![Screenshot_20230809-223022~2](https://github.com/ReVanced/revanced-manager/assets/117499019/150b7793-0d3c-4aa0-a22c-d508d79d5ddd)

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by Ushie** [comment]
This is a toast message, not a snackbar

Toast messages are displayed at android level instead of app level
