### ISSUE TITLE
Yet Another List of Suggestions

### ISSUE THREAD

**Issue by s1ddhants1** [revanced/revanced-manager#112]
### Type

Functionality

### Branch

yes

### Issue

yes

### Feature

A few suggestions for Manager :
1."Persistent Selected Patches" toggle 
2.HQ Manager logo (you should see how ugly it looks on android 12+ on the splash animation when opening)
3.Reinstall Option (in patches applications section)

### Motivation

because

**Comment by ponces** [comment]
1 - If you click on Info button on an Installed item on Dashboard, it will take you to the Patcher screen with the patches selected before.
2 - Added on https://github.com/revanced/revanced-manager/commit/257fd46e276f7965a4a4a81b65c75386405a6218.
3 - Check first topic.
Closed.
