### ISSUE TITLE
issue: Manager doesn't manage anything but manager

### ISSUE THREAD

**Issue by GeneralUser-NonDev** [ReVanced/revanced-manager#1121]
### Type

Error while running the manager

### Bug description

I have revanced installed (don't recall how) but later installed the manager and it won't update the installed revanced. Tried doing the patches on YouTube through manager and got some error about needing to use an apk and something about only being able to do something if rooted. Tried updating yourube app and it still says it (the recommended is now below the installed version on the YouTube app option)

Reason to attempt updating is revanced wouldn't load videos fully but actual YouTube app worked fine (aside from having advertisements).

### Steps to reproduce

Install manager, tell it to build YouTube.

Device: note20ultra fully updated. 

### Android version

One UI 5.1 (13 I think)

### Manager version

Latest 1.8.0

### Target package name

Youtube

### Target package version.

??? Don't know first try, second try is 18.30.36

### Installation type

Non-root

### Patches selected.

Couldn't select any

### Device logs (exported using Manager settings).

```shell
Unable to figure out how to
```

### Screenshots or video

![Screenshot_20230809_213404](https://github.com/ReVanced/revanced-manager/assets/96662916/eef4b9fb-415c-4d0f-acc2-0fa1aa2c8d58)
![Screenshot_20230809_213413](https://github.com/ReVanced/revanced-manager/assets/96662916/0e9b3e47-b252-4bb3-8a33-2c4d1182c7c0)
![Screenshot_20230809_213433](https://github.com/ReVanced/revanced-manager/assets/96662916/a0aa94b0-825d-4ec6-943e-d694e39be31d)
![Screenshot_20230809_213457](https://github.com/ReVanced/revanced-manager/assets/96662916/ff888228-dd06-4e8d-a957-f1f7c8a6da2d)

### Solution

Be able to create a working version (or better yet update installed) version of revanced (and patches) on my non-rooted device.

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by oSumAtrIX** [comment]
> something about only being able to do something if rooted.

Please re-read the popup again and follow it.
