### ISSUE TITLE
feat: Add translation functionality

### ISSUE THREAD

**Issue by LuckyKorea37** [ReVanced/revanced-manager#1129]
### Type

Functionality

### Issue

revaned(revaned, sponsorblock)관련 설정할 때 영어로 되어 있어 설정할 때마다 번역기를 쓰는데 번역 기능을 추가할 수 없나요?
RVX로 하면 동영상 배속을 커스텀할 수가 없어서 인데...

I use a translator every time I set it up because it's in English when I set it up related to revaned (revaned, sponsor block), can't I add a translation function?
It's because I can't customize the video speed with RVX...

### Feature

inotia00님의 "translation"패치를 추가하면 될 것은데 할 수 없나요?

If I add inotia00's "translation" patch, can't I do it?

### Motivation

모든 사람이 편하게 사용할 수 있게 하기위해서?

To make it easy for everyone to use?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
This is ReVanced.
