### ISSUE TITLE
bug: <Inconsistent lag in comment section>

### ISSUE THREAD

**Issue by namcicle** [ReVanced/revanced-manager#1138]
### Type

Cosmetic

### Bug description

When scrolling through the comments in a video, the frame rate rapidly plummets while the animation for the filter bar for the comments happens. I can't determine the cause and it sometimes just does not happen

As well as this, backing out from a comment results in the entire chunk of the screen containing the comment becoming white until the animation is complete.

### Steps to reproduce

1) Go to any video.
2) Go the the comments of the video.
3) Scroll

### Android version

Android 13

### Manager version

Latest (1.8)

### Target package name

YouTube

### Target package version.

YouTube 18.23.35

### Installation type

Non-root

### Patches selected.

All 

### Device logs (exported using Manager settings).

```shell
Nothing relevent
```

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [ ] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by Ushie** [comment]
Wrong repo
