### ISSUE TITLE
Addition of Japanese translation

### ISSUE THREAD

**Issue by GOG-Studio** [ReVanced/revanced-manager#1145]
### Type

Cosmetic

### Issue

Localization work to Japanese at crowdin is almost complete

### Feature

Make revanced available in Japanese

### Motivation

Because Japanese people also use revanced.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [x] The issue is related solely to the ReVanced Manager

**Comment by GOG-Studio** [comment]
I'm sorry if English is wrong.

**Comment by validcube** [comment]
🥞 This issue have been resolved by the release of v1.19.0
