### ISSUE TITLE
bug: Settings broken + loading apps

### ISSUE THREAD

**Issue by nightznero** [ReVanced/revanced-manager#1154]
### Type

Error while running the manager

### Bug description

![Screenshot_20230827_021012_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/61750641/4dc03b10-98fa-4af8-b29a-743025166400)
Settings looks like this(s20 ultra a13,just version 1.9.0 done that) and loading apps from apk takes decades to load(Patch at the bottom->Storage)

### Steps to reproduce

.

### Android version

A13

### Manager version

Newest

### Target package name

All

### Target package version.

.

### Installation type

Non-root

### Patches selected.

x

### Device logs (exported using Manager settings).

```shell
None
```

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by Shazzkid** [comment]
I'm using Androids 13 aswell, and the manager v1.9.0 but i don't experience any of these issues. Have you tried reinstalling it fresh. Export the keystore, uninstall it, and install clean from github and import the keystore

**Comment by datkush420** [comment]
I have the same issue as described by nightznero.

Android 12
OnePlus 7 Pro
Revanced Manager 1.9.0

**Comment by nightznero** [comment]
Well,yeah the update to 1.9.1 is not resolve the issue (to clarify). But this update its just a bumping a patches,its not hotfix to issue that i mentioned above. Guess we have to wait for hotfix when @oSumAtrIX will wake up hah
Best Regards, NIGHTZNERO.

**Comment by m4heshd** [comment]
Can confirm on A12. Can't load APKs anymore.

**Comment by oSumAtrIX** [comment]
Please attach logs found in the settings of ReVanced Manager.

**Comment by Shazzkid** [comment]
> Please attach logs found in the settings of ReVanced Manager.

We can't do that @oSumAtrIX, as seen in the screenshot, we can't access of those settings because of the graphical issue, its just a big grey box.

**Comment by oSumAtrIX** [comment]
Try grabbing logs using logcat

**Comment by Shazzkid** [comment]
@oSumAtrIX logcat file uploaded here: https://drive.google.com/file/d/1j9BC--P2u7olCx13RAql7Xvaet6QZ2nB/view?usp=sharing

**Comment by TheAabedKhan** [comment]
Can you clear manager data and check?

**Comment by validcube** [comment]
🎉 This issue have been fixed in #1157 and is now released as ReVanced Manager Flutter v1.9.3
