### ISSUE TITLE
bug: Blink app cannot be screen captured.

### ISSUE THREAD

**Issue by jacklollz2** [ReVanced/revanced-manager#1159]
### Type

Other

### Bug description

The screen capture and screenshot patch is not functioning on Blink, it's still black when using guiscrcpy. This is on Android 13, on a Google Pixel 7 Pro.

### Steps to reproduce

Use Blink APK, patch it with the screenshot+screen capture patches, install APK, launch guiscrcpy and try to capture the app.

### Android version

13

### Manager version

1.9.3

### Target package name

com.immediasemi.android.blink

### Target package version.

6.29.0

### Installation type

Non-root

### Patches selected.

Screenshot & Screen capture.

### Device logs (exported using Manager settings).

```shell
There was no error, and it patched "correctly", no need.
```

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [ ] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by Ushie** [comment]
Acknowledgements not met, go to https://github.com/ReVanced/revanced-patches
