### ISSUE TITLE
background playback

### ISSUE THREAD

**Issue by LostCat123** [revanced/revanced-manager#116]
### Type

Functionality

### Branch

Idk, how would I know? Please do tell me sorry

### Issue

I don't know if it because I'm using an unsupported version, ¿but everything it working fine?

### Feature

Be able to use background playback

### Motivation

Idk lot of people would also want that

### Additional context

I'm using rooted btw

**Comment by Aunali321** [comment]
Include minimzed playback patch before patching. Use 17.29.34 or 17.33.34.

**Comment by LostCat123** [comment]
> Include minimzed playback patch before patching. Use 17.29.34 or 17.33.34.

Sorry, HDR auto brightness, and minimize playback wasn't showing before, it did after I rebooted
