### ISSUE TITLE
bug: Cannot install patched youtube

### ISSUE THREAD

**Issue by Sam101011** [ReVanced/revanced-manager#1167]
### Type

Error while running the manager

### Bug description

After patching youtube, pressing the install button does nothing and exporting the patched apk crashes the manager

### Steps to reproduce

Open the Manager
Patch latest supported youtube version
Attempt installing
Attempt exporting

### Android version

10

### Manager version

1.9.4

### Target package name

com.google.android.youtube

### Target package version.

18.32.39

### Installation type

Non-root

### Patches selected.

![Screenshot_20230828_050338_app revanced manager flutter](https://github.com/ReVanced/revanced-manager/assets/90930406/c2d8b5e4-6254-4242-88aa-f7bc689dbf96)
![Screenshot_20230828_050343_app revanced manager flutter](https://github.com/ReVanced/revanced-manager/assets/90930406/21bf8a10-1226-4816-a404-1df8aaeb622f)
`

### Device logs (exported using Manager settings).

```shell
Version: 1.9.4
Model: JNY-LX1
Android Version: 10
Supported Archs: arm64-v8a, armeabi-v7a, armeabi
```

### Screenshots or video

https://github.com/ReVanced/revanced-manager/assets/90930406/0d2c0c72-8391-47c4-a362-25720480c45d

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-manager/issues/1030

**Comment by Ushie** [comment]
Please open a new issue about crashing when exporting the APK and attach logs captured through adb logcat or something similar

**Comment by Sam101011** [comment]
> Please open a new issue about crashing when exporting the APK and attach logs captured through adb logcat or something similar

How do I do that?

**Comment by oSumAtrIX** [comment]
You can find great articles about that online
