### ISSUE TITLE
bug: incorrect "original package name" 

### ISSUE THREAD

**Issue by Ushie** [ReVanced/revanced-manager#1168]
### Type

Cosmetic

### Bug description

Original package name field shows the current package name if the original one is unknown, which may result in confusion

### Steps to reproduce

1. Patch an app and change the package name in the process, through the MicroG support patch for example
2. Completely clear the data of ReVanced Manager
3. Original package name is now incorrect

### Android version

14

### Manager version

1.9.4

### Target package name

Not applicable

### Target package version.

Not applicable

### Installation type

Non-root

### Patches selected.

Not applicable

### Device logs (exported using Manager settings).

```shell
Not applicable
```

### Screenshots or video

![SmartSelect_20230828_052724_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/79272171/f59a2217-c64a-4ff4-a2d6-3c2c5d234c84)

### Solution

If the original package name is unknown, either show "Unknown" or don't show it altogether

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by ILoveOpenSourceApplications** [comment]
@Ushie, I believe the "Original package name" section is removed as I'm unable to see it anymore. So this issue can be closed as complete, right?
