### ISSUE TITLE
bug: No way to open the patched app right after installation 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-manager#1170]
### Type

Error while running the manager

### Bug description

Before #1021, the user had the Android dialog box pop up after every installation letting user install and open the patched app. But afterwards the opening part was shifted to within the manager. But that's also now gone due to the recent UI change in #1062. Now the user either has to go into the dashboard and the select the patched app and then open it the app from there or leave the manager and open it from the app drawer.

### Steps to reproduce

1) Patch any apps via ReVanced Manager.
2) After successfully patching install the app.
3) Notice that there's no open app option and the install option is still present even after the installation was completed.

### Android version

Android 13

### Manager version

1.9.4

### Target package name

ReVanced Manager 

### Target package version.

Any

### Installation type

Non-root

### Patches selected.

Recommended 

### Device logs (exported using Manager settings).

```shell
Nil
```

### Screenshots or video

![Screenshot_20230828-125148~2](https://github.com/ReVanced/revanced-manager/assets/117499019/0ed7d5ae-e81d-419a-ba73-7033cb5f29a8)

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by validcube** [comment]
Thanks for reporting this bug!

This should be an easy fix, looking to implement this fix (hopefully) during this weekend.

**Comment by validcube** [comment]
🎉 This issue have been fixed in #1233, please wait for the next ReVanced Manager version to release!
