### ISSUE TITLE
Install button appears even when patching aborts

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#1174]
### Type

Error while running the manager

### Bug description

The install button appears even if the patchers aborts. 

Also, after pressing the install button, it will say "Installing" even though it isn't installing. Also the export button will appear but when you try exporting the apk the manager will crash, but that may be https://github.com/ReVanced/revanced-manager/issues/1173

### Steps to reproduce

Patch any app

Use the back arrow while patching to manually abort

### Android version

13

### Manager version

1.9.4

### Target package name

Any. I tested with YT

### Target package version.

18.30.37

### Installation type

Non-root

### Patches selected.

Default, plus some universal patches

(Experimental patches support was enabled so I wasnt limited to the patched supported by 18.30 37)

### Device logs (exported using Manager settings).

```shell
Dont have but i can get if needed
```

### Installer logs (exported using Installer menu option) [unneeded if the issue is not during patching].

```shell
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Alternative thumbnails succeeded
Always autorepeat succeeded
Change package name succeeded
Client spoof succeeded
Comments succeeded
Copy video url succeeded
Custom player overlay opacity succeeded
Disable Shorts on startup succeeded
Disable auto captions succeeded
Disable player popup panels succeeded
Disable zoom haptics succeeded
Enable android debugging succeeded
Enable debugging succeeded
Enable tablet layout succeeded
Export all activities succeeded
External downloads succeeded
HDR auto brightness succeeded
Hide Shorts components succeeded
Hide ads succeeded
Hide album cards succeeded
Hide autoplay button succeeded
Hide breaking news shelf succeeded
Hide captions button succeeded
Hide cast button succeeded
Hide crowdfunding box succeeded
Hide email address succeeded
Hide endscreen cards succeeded
Hide filter bar succeeded
Hide floating microphone button succeeded
Hide info cards succeeded
Hide layout components succeeded
Hide load more button succeeded
Hide player buttons succeeded
Hide seekbar succeeded
Hide timestamp succeeded
Hide video action buttons succeeded
Hide watermark succeeded
Minimized playback succeeded
Navigation buttons succeeded
Old video quality menu succeeded
Open links externally succeeded
Override certificate pinning succeeded
Playback speed succeeded
Player flyout menu succeeded
Predictive back gesture succeeded
Premium heading succeeded
Remember video quality succeeded
Remove screen capture restriction succeeded
Remove screenshot restriction succeeded
Return YouTube Dislike succeeded
Seekbar tapping succeeded
SponsorBlock succeeded
Spoof app version succeeded
Spoof wifi connection succeeded
Swipe controls succeeded
Tablet mini player succeeded
Theme succeeded
Vanced MicroG support succeeded
Video ads succeeded
Wide searchbar succeeded
Compiling modified dex files
Canceling patching process
Compiling modified resources
Press back to exit
```

### Screenshots or video

https://github.com/ReVanced/revanced-manager/assets/84587632/0bb7ec14-47ca-4679-b2d8-2ddb9bf39437

### Solution

Remove the install button if patcher aborts.

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by Ushie** [comment]
ReVanced Manager v1.9.5 has been released, should be fixed
