### ISSUE TITLE
App install

### ISSUE THREAD

**Issue by Ushie** [ReVanced/revanced-manager#1180]
- [x] Regular install (Non-root) 
- [ ] Shizuku (Non-root) 
- [x] Magisk Module (Root)
- [ ] Mount script (Root, legacy)

**Comment by qorrymarzuki** [comment]
Yes we need it, especially the shizuku. it makes the installation better

**Comment by Axelen123** [comment]
I am going to close this because we have root and non-root. Shizuku can be a separate issue if we are going to implement it.

**Comment by Ushie** [comment]
Shizuku is an open PR in the previous repository

**Comment by Axelen123** [comment]
Yes, but the PR is outdated
