### ISSUE TITLE
ci: automated dependencies update

### ISSUE THREAD

**Issue by validcube** [ReVanced/revanced-manager#1183]
### Problem
Currently, there's no system in place to keep all the dependencies up-to-date so we just have to manually update the dependencies.

There are multiples dependencies in the repository most of them are app-related, others are repository automation (GH Actions)

As of writing, we have about more than 50 dependencies. (app and repository related)

### Solutions
Tool such as [Renovate bot](https://github.com/renovatebot/renovate) can benefit us by keeping all dependencies up-to-date without the need for manual update and is highly configurable.

### Benefits
<a href="url"><img src="https://github.com/ReVanced/revanced-manager-compose/assets/93124920/7388975c-f74c-4caf-ade8-8d1ff1035d3d" height="auto" width="auto"></a>

### Example
https://github.com/validcube/revanced-manager-compose

**Comment by Ushie** [comment]
I believe dependencies should be updated manually, as you ideally should test it on the spot and update any code that needs to be updated

**Comment by validcube** [comment]
This issue was finished when Dependabot was introduced. For any further suggestions consider opening new issues or comment and mention me under this issue.
