### ISSUE TITLE
feat: app updates

### ISSUE THREAD

**Issue by she11sh0cked** [ReVanced/revanced-manager#1189]
It would be great to have a feature that allows users to update all or a selection of already patched apps with ease. An app should be updated in two scenarios:

1. When the latest version number on apkmirror exceeds the current version.
1. When the versions of the patches have been bumped.

To make this feature work efficiently, you need a way to store and retrieve version information for each app and its associated patches. One possible approach for this is to use a JSON file like the following:

```jsonc
// File: versions.json
{
  "<app-id>": {
    "version": "1.2.3",
    "patches": {
      "<patch-id>": "1.2.3",
      // Additional patches...
    },
    // Additional apps...
  }
}
```

Additionally, you would need to be careful when checking for new versions on apkmirror, as to not get rate-limited.

This feature would greatly enhance the user experience and make it more convenient to keep apps up-to-date with the latest versions and patches.

**Comment by Ushie** [comment]
Closing this issue due to the current lack of patch versions, however an "Update" function is already present, under the "Repatch" name
