### ISSUE TITLE
ci: init

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1197]
## About

Currently, this repository lacks CI/CD.

## Solution

Add CI/CD to run tests, build and deploy releases.

## Additional context

- Prereleases should be dispatched manually for development branches.
- Releases should be dispatched automatically when commits are pushed to main.
- CalVer should be used for versioning
- A changelog should be generated for releases compiled from the commits following the semantic commits specification

**Comment by Ushie** [comment]
> CalVer should be used for versioning

Why

**Comment by Ushie** [comment]
> Month or week, we occupy the minor version. Our current issue with SemVer is major. How do we solve it? Not by getting rid of minor.

We have no issue with major, major in android apps is the following:

"In a major.minor.patch versioning scheme for an end-user app, you typically bump the major version when there are significant changes that might include major new features, drastic design changes, or alterations that could potentially affect compatibility or usage for the end users. It signifies substantial updates that might require users to adapt or learn new functionalities."

**Comment by oSumAtrIX** [comment]
In our case Major plays no important role and will ever change once or at max twice over the lifetime, making it practically useless for the purpose of using it to reset minor every calendar year. No drastic change or alterations are expected to occur ever again after the "upcoming" bump and unless you can approximate that properly, such as giving examples or exampary milestones where this could occur offen enough to justify major, it makes no sense to use it over YY.MINOR.PATCH.

**Comment by Ushie** [comment]
It doesn't matter if major bumps are infrequent, that doesn't invalidate the usage of major.minor.patch.

major.minor.patch is a recognized standard for android apps, transitioning mid-dev to calver does no benefit other than introduce unnecessary disruption and confusion, and by switching to CalVer we lose out on the even it's of major

**Comment by Ushie** [comment]
> YY, inheritently and intentionally for simplicity and genetlisation, has less functional use than major with the only use being to reset minor and patch

The less frequent resetting of minor.patch doesn't in any way hinder it's functionality, it allows us to communicate the meaningfulness of an update without frequent unnecessary resets which cna be confusing

Initially you may favor CalVer due to resetting, but when development slows down or becomes stale it's nothing more than unnecessary, where the app can potentially not even bump the minor at one point and end up resetting again with just 7 patch updates in the entire year, it also creates a false perception where the program may be considered outdated if a release hasn't been made in a decent amount of time, and another false perception in many cases where the entire version can be perceived as the date of release

**Comment by Ushie** [comment]
> It makes it impractical. The versioning loses its purpose.
No, it's exactly fulfilling it's purpose, it is correctly displaying the number of major versions thus far, whether or not there are anymore "major" updates after v2 doesn't matter

> This does not support Major. Major resets minor the same way YY would. But since Major is being unused, YY actually fulfills it's purpose here unlike Major.
The difference is that major doesn't randomly change just because of the time of the year, 24.5.3 -> 25.0.0 is weird even though the update could literally only hold a string update

> You deem YY as unnecessary because it may eventually be unused whereas Major is already at that stage and way before unused than YY will be. Like I said before, we can grow Minor indefinitely.
No, I deem YY as unnecessary because it can potentially be used in a way that's stupid, once development slows down which is inevitable the minor and patch versions will be unnecessarily reset, if your motivation is to prevent minor and patch from growing (which already isnt a concern, it's fine if they do and it poses no problem) then you are being overkill about it, does 24.2.3 need resetting? it's an extremely small number, and eventually less and less updates so 24.0.4 -> 25.0.0 for no reason, and when that happens the MINOR and PATCH lose their purpose because they're unused for that update

> YY corresponds to the current year. It changing every year will not cause any considerable confusion. YY has a clear purpose which it can fulfil properly each year, Major fails to.

YY = Year is clear, but MINOR and PATCH aren't, considering MINOR and PATCH won't be given room to grow anymore, they'd be viewed as MM and DD instead of MINOR and PATCH by the users

Does 23.5.12 look like a version to you? or more like a date.

**Comment by oSumAtrIX** [comment]
> No, it's exactly fulfilling it's purpose, it is correctly displaying the number of major versions thus far, whether or not there are anymore "major" updates after v2 doesn't matter

The purpose is unfulfilled. It is not progressing and future progress. It is only showing a current state. By that logic, why not also add other state attributes to the version that are static and never change?

> The difference is that major doesn't randomly change just because of the time of the year, 24.5.3 -> 25.0.0 is weird even though the update could literally only hold a string update

No, the difference is that YY has an actual purpose whereas Major does not. 24->25 is not a random change and does not represent what the update changes. The actual purpose after all is not to display how the app changed, but to reset Minor, unlike Major, which can not fulfil it's purpose.

> No, I deem YY as unnecessary because it can potentially be used in a way that's stupid, once development slows down which is inevitable, the MINOR and PATCH versions will be unnecessarily reset,

No, if development stops, it will not reset as the last released minor will be used.  Repeating: You deem YY unnecessary because it may eventually be unused whereas Major is already at that stage and way before unused than YY will be. Like I said before, we can grow Minor indefinitely.

> if your motivation is to prevent MINOR and PATCH from growing (which already isnt a concern, it's fine if they do and it poses no problem) then you are being overkill about it, does 24.2.3 need resetting? it's an extremely small number, and eventually less and less updates so 24.0.4 -> 25.0.0 for no reason, and when that happens the MINOR and PATCH lose their purpose because they're unused for that update

That's why I previously said, that you can remove YY/Major completely. Major won't change like you understood, YY will potentially reset it too early, whereas YY safeguards minor from growing too much, but Major does not.

> YY = Year is clear, but MINOR and PATCH aren't, considering MINOR and PATCH won't be given room to grow anymore, they'd be viewed as MM and DD instead of MINOR and PATCH by the users

Looking at the release date already discards this confusion. Minor and patch serve a semantical, YY a functional purpose.ajor does serve none as it does not change.

> This choice incredibly ruins the meaning of the version, the year is completely irrelevant to the state of the app, versions aren't a release date.

No, like I previously said, the meaning is defined by minor and patch, hence semantically speaking you can remove YY/Major without any semantical change, but lose the functional purpose that YY could provide, unlike Major which would add neither functional nor santical purpose.

That being said, if you say YY's functional purpose does not outweight the confusion, then you can remove YY. This does not support adding Major. If you say it does not outweight the confusion, you add YY, this once again does not support Major, as it fails to have a functional purpose

**Comment by Ushie** [comment]
> The actual purpose after all is not to display how the app changed, but to reset Minor, unlike Major, which can not fulfil it's purpose.

This is a problem, if YY doesn't represent part of the app or the changes then why is it there?? wanting to reset MINOR and PATCH is a dumb reason, given they don't need to be reset

> Looking at the release date already discards this confusion. Minor and patch serve a semantical, YY a functional purpose.ajor does serve none as it does not change.

There is no release date in revanced.app/download, and there's no reason to have one, you don't need to know the date that the release has taken place, the release date has no effect on the app as it is the latest version regardless of when it was released

> No, like I previously said, the meaning is defined by minor and patch, hence semantically speaking you can remove YY/Major without any semantical change, but lose the functional purpose that YY could provide, unlike Major which would add neither functional nor santical purpose.

That being said, if you say YY's functional purpose does not outweight the confusion, then you can remove YY. This does not support adding Major. If you say it does not outweight the confusion, you add YY, this once again does not support Major, as it fails to have a functional purpose

Yes, YY's functional purpose does not outweight the confusion, development time, and the unnecessary transition

However

> this once again does not support Major, as it fails to have a functional purpose

Although it doesn't "support' major, it also doesn't support a transition, the major version has already been in use for the past 100+ releases of ReVanced Manager, and does fulfill it's purpose in v2 by being bumped to 2.0.0 which will reset the MINOR and PATCH and also represent the current state of ReVanced Manager, as it is infact considered to be ReVanced Manager V2

**Comment by oSumAtrIX** [comment]
> This is a problem, if YY doesn't represent part of the app or the changes then why is it there?? wanting to reset MINOR and PATCH is a dumb reason, given they don't need to be reset

YY is used to reset minor. It is not a dumb reason as minor will grow indefinitely. If you think otherwise, simply remove YY. In any case, this does not support adding Major.

> There is no release date in revanced.app/download, and there's no reason to have one, you don't need to know the date that the release has taken place, the release date has no effect on the app as it is the latest version regardless of when it was released

The version does not represent the date to begin with. YY is simply used to reset minor, it being incremented each year, is just how it's being used.

> Yes, YY's functional purpose does not outweight the confusion, development time, and the unnecessary transition

Then remove YY and see for yourself that it would've been useful.

> Although it doesn't "support' major, it also doesn't support a transition, the major version has already been in use for the past 100+ releases of ReVanced Manager, and does fulfill it's purpose in v2 by being bumped to 2.0.0 which will reset the MINOR and PATCH and also represent the current state of ReVanced Manager, as it is infact considered to be ReVanced Manager V2

Besides a transition not being a problem to begin with, a transition is necessary regardless of using YY or Major. In both cases we transition from semantic release to either CalVer or Androids versioning. Even without considering that, changing the versioning to mm.pp or yy.mm.pp does not conflict with the current versioning system. The bump of Major just for the sake of doing it once for compose is a bad use of Major as it loses all meaning afterwards, whereas YY keeps its yearly functional purpose.
