### ISSUE TITLE
APKMirror downloader

### ISSUE THREAD

**Issue by OxrxL** [revanced/revanced-manager#12]
I am unfamiliar with kotlin, so I ask if it is possible to implement this feature (as I have already done on my personal patcher).

It is very convenient and saves a lot of time.

**Comment by oSumAtrIX** [comment]
APKMirror is a third-party service, the manager should not rely on it.

**Comment by DiamondMiner88** [comment]
APKMirror is still Cloudflare protected, making it impossible to scrape without doing background webview trickery like [tachiyomi does](https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/network/interceptor/CloudflareInterceptor.kt).

**Comment by OxrxL** [comment]
> APKMirror is still Cloudflare protected, making it impossible to scrape without doing background webview trickery like [tachiyomi does](https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/network/interceptor/CloudflareInterceptor.kt).

Is not much difficult to fetch the last version (and generate the download link from it).

I can eventually make my code open source, but this depends on the team's decision.

**Comment by oSumAtrIX** [comment]
You should decide that independent of the team's decision.

**Comment by OxrxL** [comment]
> You should decide that independent of the team's decision.

For me there's no problem.

Just let me prepare the project.

**Comment by OxrxL** [comment]
> You should decide that independent of the team's decision.

> APKMirror is still Cloudflare protected, making it impossible to scrape without doing background webview trickery like [tachiyomi does](https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/network/interceptor/CloudflareInterceptor.kt).

https://github.com/OxrxL/uPatcher

**Comment by OxrxL** [comment]
P.S:

Take note: this is a my personal project. If you don't find some patches already included in Vanced, it's because I didn't want to add them on purpose.

**Comment by alexandreteles** [comment]
If we're going to download the APK/OBB files I see no reason why we shouldn't do it directly from the Play Store. Besides cases where access to the Play Store is blocked somehow, unlikely as that may be, we should avoid using mirrors that can be compromised and inject malicious code in whatever is being downloaded.

In my humble opinion, if this functionality gets added to the software it should be accompanied of a small security warning and be tied to an opt-in.

**Comment by bogadana** [comment]
> can be compromised and inject malicious code in whatever is being downloaded.
apks have signatures

**Comment by OxrxL** [comment]
> If we're going to download the APK/OBB files I see no reason why we shouldn't do it directly from the Play Store. Besides cases where access to the Play Store is blocked somehow, unlikely as that may be, we should avoid using mirrors that can be compromised and inject malicious code in whatever is being downloaded.
> 
> In my humble opinion, if this functionality gets added to the software it should be accompanied of a small security warning and be tied to an opt-in.

Except from the fact that old Vanced has always been based on apkmirror apks (and no one has ever complained about it), I think it is quite complicated to modify an apk while leaving the signature unchanged.

I don'tt think it is even possible to do so at present.

**Comment by oSumAtrIX** [comment]
APKMirror is a dependency we should not have to rely on to begin with, it should be the users job to prepare the application they want to patch. It might be an application which is only available in the playstore. An apk downloader feature is too out of scope for this purpose.

**Comment by CanKolay3499** [comment]
> At best there should be an option to extract the apk from the installed app.

Manager have that

**Comment by OxrxL** [comment]
> At best there should be an option to extract the apk from the installed app.

Bleah...

Keep the original app installed is like drinking gasoline.

**Comment by alexandreteles** [comment]
> > At best there should be an option to extract the apk from the installed app.
> 
> Bleah...
> 
> Keep the original app installed is like drinking gasoline.

Unless we consistently support casting on ReVanced keeping the original app does have an important purpose for many people.

**Comment by SubZero5** [comment]
Why not get APK's from `g`oog.l directly?

**Comment by alexandreteles** [comment]
> > Why not get APK's from `g`oog.l directly?
> 
> Because google does not supply APKs.

It is possible to obtain APK/OBB data directly from Google Play programmatically using Aurora's `gplayapi` (https://gitlab.com/AuroraOSS/gplayapi). I'm not sure how hard would it be to integrate it with the manager but obtaining data directly from the Play Store is probable the best way to proceed in this case. There are other tools that could allow us to do the same (ex.: https://github.com/ClaudiuGeorgiu/PlaystoreDownloader) but it would require a different infrastructure and more careful consideration.

**Comment by OxrxL** [comment]
> > > Why not get APK's from `g`oog.l directly?
> > 
> > 
> > Because google does not supply APKs.
> 
> It is possible to obtain APK/OBB data directly from Google Play programmatically using Aurora's `gplayapi` (https://gitlab.com/AuroraOSS/gplayapi). I'm not sure how hard would it be to integrate it with the manager but obtaining data directly from the Play Store is probable the best way to proceed in this case. There are other tools that could allow us to do the same (ex.: https://github.com/ClaudiuGeorgiu/PlaystoreDownloader) but it would require a different infrastructure and more careful consideration.

If somebody is able to do it...it would be the best solution.

**Comment by TheJeterLP** [comment]
In my opinion we should not download an apk from google to modify it. This could have consequences by Google. It is the users job to get a suiting APK.

**Comment by CookieXD** [comment]
Why not just upload the used APK files somewhere (for example a private google drive folder) and let the manager always download these from (for example a specified google drive folder.) there.

**Comment by alexandreteles** [comment]
> Why not just upload the used APK files somewhere

Because redistributing proprietary software is a no-no.

**Comment by rollingmoai** [comment]
So, what is the solution for this? I don't want to install the original app in my phone.

**Comment by rollingmoai** [comment]
Something like [Aliucord](https://github.com/Aliucord/Aliucord) can download the corresponding Discord APK though, can't Revanced do the same?

**Comment by Indranil012** [comment]
What's about hosting the original apk on a separate github repo?
