### ISSUE TITLE
bug: strange scroll animation behavior in non-scrolable layouts

### ISSUE THREAD

**Issue by VanillaMaster** [revanced/revanced-manager#120]
### Type

Cosmetic

### Branch

Flutter

### Bug description

"stretch" animation on overscroll flickering if layout cant be scrolled

### Steps to reproduce

1. open any layout that cant be scrolled
2. try to scroll it

### Relevant log output

```shell
Version: 0.0.7
Model: IN2020
Android Version: 11
Arch: arm64-v8a
```

### Screenshots or videos

https://user-images.githubusercontent.com/36816539/190606465-9e38dc11-b012-4cff-9d35-dd0e1c38d3ed.mp4

**Comment by ponces** [comment]
These layouts are scrollable. Although you can't see it as it is on your recording, if the list of patches selected is big, scoll will be needed. This is expected behavior.
