### ISSUE TITLE
Resource patching is disabled and root install not working. 

### ISSUE THREAD

**Issue by Shadowtuy** [revanced/revanced-manager#121]
Been experimenting with youtube APKs and different patches. During patch process repeated error of "resource patching is disabled" seems to make the process fail. When installing "install as root" yeilds no result. Normal install does work but I'm not running microG so the app crashes immediately on opening. 

![Screenshot_20220916-064203_ReVanced Manager](https://user-images.githubusercontent.com/28229812/190622316-875e3c9d-9b6a-4920-b3ae-d414d598f9cd.png)

[revanced-manager_logcat_20220916064830472431.log](https://github.com/revanced/revanced-manager/files/9583345/revanced-manager_logcat_20220916064830472431.log)

**Comment by ponces** [comment]
Make sure you are patching a compatible version of the app.

**Comment by Shadowtuy** [comment]
I grabbed an apk that was the latest supported version and and tried a
older version as well.

17.29.34
17.33.42

**Comment by Shadowtuy** [comment]
The newest variant has fixed root install tho the resource patching error is still present the app is working.
