### ISSUE TITLE
bug: Cannot Installed successfully patched youtube app

### ISSUE THREAD

**Issue by jackj1** [ReVanced/revanced-manager#1226]
### Type

Error while running the manager

### Bug description

I can patch the app successfully but then android fails to install it, whether i try and install through the manager (v1.9.4) or through the apk exported by the manager. At first I thought it may be due to play protect, but I have disabled that and the problem persists. I already have ReVanced 18.23.35 installed and working, this problem only occurs when tring to install version 18.32.39. I tried with default patches first and then adding the "Custom Branding" patch. The problem still occurs whatever combination of patches.

### Steps to reproduce

Step 1: Download youtube 18.32.39 apk
Step 2: Select apk and patches in ReVanced manager 1.9.4
Step 3: Build is successful (no errors in output)
Step 4: Select install
Step 5: App fails to install

### Android version

Android 10 (Samsung S9+)

### Manager version

1.9.4

### Target package name

Youtube

### Target package version.

18.32.39

### Installation type

Non-root

### Patches selected.

Default (also tried Default + Custom Branding)

### Device logs (exported using Manager settings).

```shell
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Alternative thumbnails succeeded
Always autorepeat succeeded
Client spoof succeeded
Comments succeeded
Copy video url succeeded
Custom branding succeeded
Custom player overlay opacity succeeded
Disable Shorts on startup succeeded
Disable auto captions succeeded
Disable player popup panels succeeded
Disable zoom haptics succeeded
Enable debugging succeeded
Enable tablet layout succeeded
External downloads succeeded
HDR auto brightness succeeded
Hide Shorts components succeeded
Hide ads succeeded
Hide album cards succeeded
Hide autoplay button succeeded
Hide breaking news shelf succeeded
Hide captions button succeeded
Hide cast button succeeded
Hide crowdfunding box succeeded
Hide email address succeeded
Hide endscreen cards succeeded
Hide filter bar succeeded
Hide floating microphone button succeeded
Hide info cards succeeded
Hide layout components succeeded
Hide load more button succeeded
Hide player buttons succeeded
Hide seekbar succeeded
Hide timestamp succeeded
Hide video action buttons succeeded
Hide watermark succeeded
Minimized playback succeeded
Navigation buttons succeeded
Old video quality menu succeeded
Open links externally succeeded
Playback speed succeeded
Player flyout menu succeeded
Premium heading succeeded
Remember video quality succeeded
Return YouTube Dislike succeeded
Seekbar tapping succeeded
SponsorBlock succeeded
Spoof app version succeeded
Swipe controls succeeded
Tablet mini player succeeded
Theme succeeded
Vanced MicroG support succeeded
Video ads succeeded
Wide searchbar succeeded
Compiling modified dex files
Compiling modified resources
Signing APK
Patched
Installing patched file using nonroot method
Installing patched file using nonroot method
Installing patched file using nonroot method
```

### Screenshots or video

![Screenshot_20230902-141658_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/62434031/7f637313-5557-4984-97a7-799f8abf10fa)

https://github.com/ReVanced/revanced-manager/assets/62434031/95dd0bde-336c-4584-a221-a591837c007f

![Screenshot_20230902-142100_Package installer](https://github.com/ReVanced/revanced-manager/assets/62434031/ba49f79d-bcc0-4efa-adc6-92a3be5c993b)

### Acknowledgments

- [X] I have searched the existing issues; this is new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I properly filled out all of the requested information in this issue.
- [X] The issue is solely related to ReVanced Manager and not caused by patches.

**Comment by Ushie** [comment]
#1030

**Comment by MDE186** [comment]
Having the exact same issue, however what comes up for me.

![1000013841](https://github.com/ReVanced/revanced-manager/assets/8092312/d33738ba-2d24-4edf-aab8-640de12acfd8)
![1000013840](https://github.com/ReVanced/revanced-manager/assets/8092312/554c375f-7d02-4066-b0f2-3beafab7fc2d)

I have uninstalled all patches for the the original YouTube App and aslo uninstalled 18.23.35, without any success.

**Comment by Ushie** [comment]
Select default patches

**Comment by MDE186** [comment]
Tried with default patches get the same error message.

**Comment by Ushie** [comment]
Join the [discord server](https://revanced.app/discord) and ask for help in the support channel
