### ISSUE TITLE
ci: sign debug build

### ISSUE THREAD

**Issue by validcube** [ReVanced/revanced-manager#1230]
### Problem

[![SDBCurrent](https://github.com/ReVanced/revanced-manager/assets/93124920/fd219c26-bdb1-4706-b562-6314b1fff292)](#1230)

_**On the flowchart, the problem become obvious, tester have to reinstall the ReVanced Manager Debug every time they wanted to try out new features.**_

Currently, the action responsible for compiling the application when push or PR use debug keystore.

Using debug keystore means that the keystore will be reset for every run, so canary user (or tester) will have to reinstall the ReVanced Manager Debug variant every time they wanted to test something.

### Suggested Solution

[![SDBSuggested](https://github.com/ReVanced/revanced-manager/assets/93124920/33b53a11-63b4-4b57-b1b5-76de92890573)](#1230)

_**On the flowchart, we sign the APK using keystore, now tester won't have to reinstall the ReVanced Manager Debug to try out new features.**_

Sign the APK in workflow using the release keystore or use entirely different keystore specifically for debug build.

### Benefits

* Update to debug variant can be made easily, thus reducing time to setup and increasing productivity.

**Comment by BenjaminHalko** [comment]
@validcube It seems like adding the signing step has caused [several workflows](https://github.com/ReVanced/revanced-manager/actions/runs/6081713575) to crash, as pr's originating outside of the repository do not have access to the signing key.
