### ISSUE TITLE
bug: Bug while playing a video

### ISSUE THREAD

**Issue by LostCat123** [revanced/revanced-manager#124]
### Type

Other

### Branch

.

### Bug description

When you play a video that "supposed to have ads"(but removed since I patched it) it will keep showing in the video : ads in 3...2....1.... But there's no ads(since I patched it)

### Steps to reproduce

Watch any video with ads 

### Relevant log output

```shell
I don't have one
```

### Screenshots or videos

![Screenshot_20220916-194739_YouTube~2](https://user-images.githubusercontent.com/91554842/190632246-cda757a1-a2f5-4a7c-8f35-4a1b503cd538.png)

### Solution

Ignore

### Additional context

I installed via root, I tried on other YouTube version(it still exist), I tried the older manager version (it still exist)

**Comment by Aunali321** [comment]
Not a manager issue. Open this in patches repo.
