### ISSUE TITLE
bug: Don't automatically download old versions in the background

### ISSUE THREAD

**Issue by bingdong700** [ReVanced/revanced-manager#1241]
### Feature description

Every time you open ReVanced a file named ReVanced_Manager_6ada4ded.apk is automatically downloaded in the background, which is 53M in size and has a version number of 0.0.32.

### Motivation

Don't automatically download old versions in the background

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Open a detailed bug report.
