### ISSUE TITLE
bug: suspected voice phishing warning on Samsung devices

### ISSUE THREAD

**Issue by sssh7710** [ReVanced/revanced-manager#1244]
### Issue description

I think this has happened on mobile devices that have received the latest updates via Galaxy Store
I blocked the installation because it's a suspicious app related to voice phishing.

![papago_1693975987012](https://github.com/ReVanced/revanced-manager/assets/98168192/93f4e127-fe37-419e-bfbe-4a6d153f6d11)
![papago_1693975994673](https://github.com/ReVanced/revanced-manager/assets/98168192/be8f5e15-7ab4-4e0b-b437-853b93685bd0)

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
I don't understand your question

**Comment by RangHo** [comment]
Sorry for replying on the closed thread, but I am having the same issue.
My own build of Revanced Manager, starting from today, refused to run saying it is "reported to be a voice phishing app".
Is there any measure you can take as a team?

**Comment by validcube** [comment]
Re-opening this, see discussion at Discord https://canary.discord.com/channels/952946952348270622/1148754143285104670

**Comment by PalmDevs** [comment]
According to the discussion in the thread above, it seems to only be affecting Korean devices with the latest Galaxy Store update, and it's detected via package name.

**Comment by aroxu** [comment]
After some research, it seems AASA(AASApolicy) and ASKS are blocking the installation or launching app.
- Related Android Activity: `com.android.internal.app.UnknownSourcePhishingActivity` in `/system/framework/framework.jar`

**Comment by aroxu** [comment]
UPDATE: Just update a app called Security Policy Update via Galaxy Store.
You can use this link: https://apps.samsung.com/appquery/appDetail.as?appId=com.samsung.aasaservice&cId=000006570044

**Comment by Nanlemanda** [comment]
It says it's not available for my country
