### ISSUE TITLE
ReVanced Youtube Music Extended is missing

### ISSUE THREAD

**Issue by Myron472** [ReVanced/revanced-manager#1246]
### Feature description

Hello. ReVanced YT Music **Extended** mod is missing in the RV Manager.

### Motivation

Because ReVanced Youtube Extended is presented in the manager, so the RV YT Music Extended must be too.

### Additional context

I'm not sure if it's a feature request or bug, but it's definetly an issue. I actuallywant to delete feature-request tag, but I can't, sorry.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
This is ReVanced

**Comment by Myron472** [comment]
Why the ReVanced Youtube Extended is present on the app then? It's irrational.

**Comment by Ushie** [comment]
It's not, you changed your sources in settings

**Comment by Myron472** [comment]
> It's not, you changed your sources in settings

What do you mean? There's no settings in ReVanced Manager, how could I change sources?
Moreover, RV Youtube Extended is presented by default and as the first app in the list!
![Screenshot_20230906_211757](https://github.com/ReVanced/revanced-manager/assets/62944727/cd015e6b-28b9-47ea-a52c-466dd8302fb0)

**Comment by Myron472** [comment]
> This is ReVanced not Extended

This is ReVanced Manager actually

**Comment by Ushie** [comment]
That isn't ReVanced Manager, whatever you have installed is fake

You can find the official app on https://revanced.app/

**Comment by Myron472** [comment]
> That isn't ReVanced Manager, whatever you have installed is fake
> 
> You can find the official app on https://revanced.app/

Oh, my apology. It's strange I didn't notice it.
