### ISSUE TITLE
APK source

### ISSUE THREAD

**Issue by StupdNerd** [revanced/revanced-manager#125]
Hello to everyone who might read this, 

As you probably know, in it's current state, the ReVanved manager sources the APKs it needs by directly extracting them from the phone's internal storage. This is a very efficient method when it comes to data usage and speed, as the APK doesn't have to be downloaded from the internet first. 

However, this method requires the proper version of the app in question to be already installed, which requires fiddling around with the automatic update, if you want to stick to the version recommend by the ReVanved team. 

Additionally, for apps like Reddit or Twitter, where the original and patched version of the app can't coexist due to a package conflict, this means that one first has to install the original app, start the patching process, leave the manager to uninstall the original and only then, one can install the patched app. This is especially tedious when updating to a newer version of said apps, as you additionally have to uninstall the old patched app before all.

Of course, all this can be circumvented by manually downloading the APK and selecting the file in the manager, but that option is also annoying to work with, as one needs to manually search and download said APK. 

This is in contrast to the ReVanced Builder by reisxd, which just automatically downloads the required APK from APKmirror. 

Personally, I prefer that method by a huge margin and based on the responses to my initial comment about this issue in the ReVanced subreddit, it seems like many people feel the same. 

Would it be possible for you to implement such a feature in the ReVanced manager?

**Comment by ponces** [comment]
Not Manager's responsibility.
Closed.

**Comment by StupdNerd** [comment]
> Not Manager's responsibility. Closed.

Well who's responsibility is it, then?

**Comment by ponces** [comment]
Manager is a tool to patch apps, not a downloader.
Also, its app agnostic so it's not supposed to know what is the source of an APK.
I'll give you a quick example. What would be the source for the `Pflotsh ECMWF` which is one of the apps that is _patchable_ and not even available on APK Mirror?

**Comment by s1ddhants1** [comment]
> Manager is a tool to patch apps, not a downloader. Also, its app agnostic so it's not supposed to know what is the source of an APK. I'll give you a quick example. What would be the source of `Pflotsh ECMWF` which is one of the apps that is _patchable_ and not even available on APK Mirror?

how about some implementation of configuring your own custom source for the apks like the one that is done for patcher

**Comment by Aunali321** [comment]
Each source has different api/scraping structure. For example apkmirror implementation will be different from apkpure implementation. There is no generic way to get apks/

**Comment by Auncaughbove17** [comment]
how about providing a link to the current recommended version? something like
https://mobile.softpedia.com/apk/youtube/17.36.37/
or 
https://www.apkmirror.com/apk/google-inc/youtube/youtube-17-36-37-release/youtube-17-36-37-2-android-apk-download/

then you could just open it in your browser and download it.

**Comment by oSumAtrIX** [comment]
> Each source has different api/scraping structure. For example apkmirror implementation will be different from apkpure implementation. There is no generic way to get apks/

This is correct, but in the case it is necessarily or recommended, a scraping module framework can be created, this way people could agnostically include their modules into the manager. The module only would need to know the package name and the package version and return a download link, file or similar.

**Comment by Aunali321** [comment]
Let's discuss this on discord.
