### ISSUE TITLE
feat: Select bundle type, before entering the screen to add it

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1250]
Before you enter the screen to import a patch bundle, let the user first choose if they want to import a remote or local bundle:

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/73c201c0-b77d-4d4a-b0e5-0856e522eb45)

UX-wise it makes no sense to put the bundle type here as a button. Either a dropdown or a switch should be used. At best the user should first decide if they want a local or remote bundle, then enter this screen. This simplifies the screen and gets rid of the confusing UX of switching between bundle types changing the entire screens content.

The bundle type option also exists after adding the bundle. For the same reason, this should also be removed here. If the user wants to change the type, they intend to add a completely new bundle to begin with. There is no purpose in having this setting after adding the bundle.

**Comment by Axelen123** [comment]
Needs to be changed in the figma

**Comment by Ushie** [comment]
I can pick this up after #1464, #1465 and #1467
