### ISSUE TITLE
bug: ReVanced Manager freezes instantly (API problem?)

### ISSUE THREAD

**Issue by SeverinBang** [ReVanced/revanced-manager#1251]
### Bug description

App freezes nearly instantly after opening. After fresh install/data wipe it reacts to touch input **until** the API connect warning pop-up appears. When reacting fast enough (e.g. clicking on the "patch" icon) one can retain responsibility of the app, but cause without API access nothing works.

To reproduce:

1. download ReVanced Manager APK
2. Install APK
3. Open ReVanced Manager
4. Accept API warning (instant freeze) or
5. React fast/before API warning popup appears (responsive UI, will freeze while opening the second time)

### Version of ReVanced Manager and version & name of application you tried to patch

I tried all versions 1.9.0 - 1.9.5, could not reach the stage to patch something.

### Installation type

None

### Device logs

```shell
not applicable
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by TheAabedKhan** [comment]
Is your device rooted?

**Comment by SeverinBang** [comment]
yes

**Comment by TheAabedKhan** [comment]
If your device is rooted with Magisk, add ReVanced Manger to the DenyList from the Magisk settings and try again.

**Comment by SeverinBang** [comment]
Oh
