### ISSUE TITLE
bug: back button takes to phone homepage

### ISSUE THREAD

**Issue by Kuddus73** [ReVanced/revanced-manager#1254]
### Bug description

It's really similar to this bug https://github.com/ReVanced/revanced-manager/issues/233 but this time it doesn't really close the manager because when you reopen it, it starts from the tab where you left it.

However, tapping the Back button takes you to your phone's homepage instead of taking you to the previous page or to manager's homepage (Dashboard).

**Video:**

https://github.com/ReVanced/revanced-manager/assets/127908708/b9e921ee-5432-4da7-b93e-7d57ab1fdf1c

### Version of ReVanced Manager and version & name of application you tried to patch

ReVanced Manager v1.9.5

### Installation type

None

### Device logs

```shell
N/A
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by validcube** [comment]
Duplicated of #1158 #1252
