### ISSUE TITLE
Youtube shorts

### ISSUE THREAD

**Issue by Cosmicshadows112** [ReVanced/revanced-manager#1255]
### Feature description

Option to turn off shorts and another to disable scrolling (separate).

### Motivation

To stop the addictive scrolling and to enhance experience.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [ ] The issue is solely related to the ReVanced Manager

**Comment by Ushie** [comment]
This isn't related to the ReVanced Manager application, and there's already options to disable YT Shorts in ReVanced Patches

**Comment by Cosmicshadows112** [comment]
What about the disabling scrolling?
