### ISSUE TITLE
bug: "Storage" button closes the applications page without selecting anything

### ISSUE THREAD

**Issue by chocolateimage** [ReVanced/revanced-manager#1257]
### Bug description

When selecting the "Storage" option or "Select from storage", it just closes the "Select an application" page and says "Unable to use selected application" without letting me choose, in the logs it says "User did not allow reading external storage" but in the screenshot below you can see that I allowed all files.
![Screenshot_20230910-084234](https://github.com/ReVanced/revanced-manager/assets/45315451/efc8436b-467a-4a10-a46d-3b38d885ddf3)
Unchecking "Remove permissions if app isn't used" didn't help.

Screen recording:
https://github.com/ReVanced/revanced-manager/assets/45315451/122b4dbc-3de4-4e1b-b3d9-ab7eacc80935

### Version of ReVanced Manager and version & name of application you tried to patch

Version 1.9.5

### Installation type

Non-root

### Device logs

```shell
--------- beginning of main
09-10 08:40:38.130  3360  3360 D FilePickerUtils: Allowed file extensions mimes: [application/vnd.android.package-archive]
09-10 08:40:38.529  3360  3420 I flutter : [MethodChannelFilePicker] Platform exception: PlatformException(read_external_storage_denied, User did not allow reading external storage, null, null)
09-10 08:40:38.578  3360  3360 D CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10392; state: ENABLED
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by KobeW50** [comment]
Possibly related to https://github.com/ReVanced/revanced-manager/issues/737?

**Comment by chocolateimage** [comment]
> Try in the latest version and report back, most likely it's resolved

Seems to be working after updating. At first it said "Unable to use selected application", but after a restart it seems to work.
