### ISSUE TITLE
Follow the system theme

### ISSUE THREAD

**Issue by xmha97** [ReVanced/revanced-manager#1260]
### Feature description

Now I can switch between light theme and dark theme.
But I can't follow the system theme.
Please add this feature.
Thanks 🙏

### Motivation

N/A

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by KobeW50** [comment]
There's already MaterialYou on supported devices

**Comment by xmha97** [comment]
I need this option:

![Screenshot_2023-09-12-21-41-41-177_app.revanced.android.youtube.jpg](https://github.com/ReVanced/revanced-manager/assets/23485114/e289dbb2-8fd5-483d-9344-edab966a754f)

**Comment by KobeW50** [comment]
> I need this option:
> 
> ![Screenshot_2023-09-12-21-41-41-177_app.revanced.android.youtube.jpg](https://github.com/ReVanced/revanced-manager/assets/23485114/e289dbb2-8fd5-483d-9344-edab966a754f)
> 
> 

Ah, sorry, I misunderstood what following the system theme meant.
