### ISSUE TITLE
feat(ux): app migration ux

### ISSUE THREAD

**Issue by PalmDevs** [ReVanced/revanced-manager#1265]
### Feature description

# 🧭 App migration UX (from Flutter to Compose)
Since Compose Manager has a ton of new features and the whole app redesigned. Some (if not most) users will be confused on what to do. We should handle this nicely for the user to ensure it is a easy and a straightforward process.

## ✨ Progress
- [x] Flutter Manager
  - [x] ~~Migration onboarding~~ (cancelled)
  - [x] Migration activities
- [ ] Compose Manager
  - [x] ~~Migration onboarding~~
  - [ ] Coachmarks

## 🤮 Flutter Manager
Before Compose Manager releases, Flutter Manager should push changes to add onboarding migration. Ideally this should be what's shown to the user when a Compose Manager release is published:
- Dialog about a major Manager update with a lot of improvements
- If the user accepts, download and automatically install the new Manager for them

### 👾 Migration activities
Flutter Manager should also include activities that can be called by Compose Manager to easily export settings like keystore and patch selection, etc. These activities will automatically launch a dialog asking if the user wants to import the settings or not.

## 🎉 Compose Manager
Ideally, these should only be shown when Compose Manager detects that Flutter Manager is installed on the device. Like this:
- If Flutter Manager is installed:
  - Start migration process
  - Show coachmarks

### 👾 Migration process
When Compose Manager is first launched, it should detect if the user has Flutter Manager installed. If they do, start the migration process. The migration process would call Flutter Manager's activities to import settings and apply them accordingly.

If the user doesn't want to import on first-launch, we can add a settings entry to do so in: Settings > Advanced > Migrate from legacy versions. 

### 👉 Coachmarks
Coachmarks are a kind of dismissable content that's shown to the user when a new feature is added or the user interface has been moved or changed.

Compose Manager should show the coachmarks of where important features are moved to and what new features are available.

### Motivation

Users will not be familiar with the redesigned interface even if it is more intuitive.

**Comment by validcube** [comment]
I see you're taking decoration style from my PR :trollface:

**Comment by BenjaminHalko** [comment]
The settings migration portion of this has been completed.

**Comment by PalmDevs** [comment]
Now we just need coachmarks, we can add them once ReVanced Manager gets into the beta stage.

**Comment by Ushie** [comment]
Can you show where coach marks would be used? in which specific places

**Comment by PalmDevs** [comment]
> Can you show where coach marks would be used? in which specific places

Sure, for example in the home page, we can add a coachmark that says something along the lines of "Start patching apps here" (or for migrated users: "Patching apps have been moved to here").

**Comment by Ushie** [comment]
Closing as completed, "coachmarks" is superseded by #1500
