### ISSUE TITLE
feat: create debug variant with debug suffix

### ISSUE THREAD

**Issue by validcube** [ReVanced/revanced-manager#1269]
## ✨ Create debug variant with debug suffix

* Append .debug to package name with compiled with debug variant

* Change application name to ReVanced Manager Debug

Basically porting changes from fluttery

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by BenjaminHalko** [comment]
added in: #1282
