### ISSUE TITLE
feat: zipalign

### ISSUE THREAD

**Issue by optimatrix0** [ReVanced/revanced-manager#1275]
### Feature description

zip alignment is something introduced in Android a long time ago I believe it can improve the performance of applications

### Motivation

We really all want more RAM!

### Additional context

It's an important feature, I know it can be complicated with it no matter how long it takes but please consider

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
How is it importantant in the context of ReVanced CLI?

**Comment by Ushie** [comment]
This is ReVanced Manager, not CLI, but I also don't understand much from the issue either

**Comment by optimatrix0** [comment]
It would optimize the performance of applications by aligning them in four bytes, it is important as necessary, all applications that are in the play store must pass this check but when they are When modified, they lose this alignment, so this problem would aim to recover this lost performance, if you don't know what this is about, I advise you to search about and please reopen this

**Comment by optimatrix0** [comment]
I'm visually impaired and I spent a lot of time creating this problem, so please, I'm not trying to bother you, I'm just trying to improve this project even more, which is already wonderful.

**Comment by oSumAtrIX** [comment]
This is not the task of ReVanced Manager. ReVanced Manager is an application to patch apps.

**Comment by Ushie** [comment]
Maybe this issue can be opened in the [ReVanced Patcher repo?](https://github.com/ReVanced/revanced-patcher)

**Comment by optimatrix0** [comment]
Could you move my problem there?, I think it would make it a lot easier.

**Comment by oSumAtrIX** [comment]
> Maybe this issue can be opened in the [ReVanced Patcher repo?](https://github.com/ReVanced/revanced-patcher)

Neither is this the task of ReVanced Patcher. Aligning is not a matter of ReVanced as a feature.

**Comment by optimatrix0** [comment]
If increasing performance by applying alignment is not a matter of resources, this project is not as good as I expected, RV should also optimize its corrected applications because the projectvanced I did this and the performance was good now the performance sucks

**Comment by optimatrix0** [comment]
As I told you, I wouldn't win this problem if it weren't really so necessary because because of my difficulty everything becomes more difficult, so I ask you again to reconsider because performance isn't A feature that should be ignored

**Comment by oSumAtrIX** [comment]
ReVanced is a patching application and zipaligns already after patching, not a zip alignment utility. Use zipalign from Android SDK Tools.

**Comment by Axelen123** [comment]
Both Manager and CLI sign and align for you.
