### ISSUE TITLE
YouTube ReVanced crashes on start

### ISSUE THREAD

**Issue by SveyPlay** [revanced/revanced-manager#129]
### Type

Error at runtime

### Branch

Flutter

### Bug description

YouTube ReVanced crashes when this comes up before i start patching:

"Warning

You have selected a resource patch and a split APK installation was detected so patching errors can occur.

Are you sure you want to proceed with patching a split base APK?"

I'm rooted too

### Steps to reproduce

Download, general ads, video ads, remove Westermark and a few more

### Relevant log output

```shell
Idk
```

**Comment by Aunali321** [comment]
1. Uninstall updates for the app
2. Go to apkmirror and download supported version (make sure its full apk and not split).
3. Install the app and use it in manager.
4. After patching is done, uninstall original apk before installing patched apk.

**Comment by Alprnn357** [comment]
@SveyPlay 
YT ReVanced crashes because you don't have microg services installed.
Install Vanced MicroG from [here](https://github.com/TeamVanced/VancedMicroG/releases) to fix the issue.

**Comment by pietryszak** [comment]
> @SveyPlay 
> YT ReVanced crashes because you don't have microg services installed.
> Install Vanced MicroG from [here](https://github.com/TeamVanced/VancedMicroG/releases) to fix the issue.

Information about that Needs to be added to how to install

**Comment by Alprnn357** [comment]
> > @SveyPlay
> > YT ReVanced crashes because you don't have microg services installed.
> > Install Vanced MicroG from [here](https://github.com/TeamVanced/VancedMicroG/releases) to fix the issue.
> 
> Information about that Needs to be added to how to install

Yes, you're right. At least they would have been made third option in the patcher tab that detects microg is needed or not.
