### ISSUE TITLE
feat: Improve manager settings order

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#1296]
### Feature description

There are several things that should be changed in the settings:

1. The 'Team' section should be moved to the bottom, near the 'About' section. It is out of place being in middle of configurable settings. And it is conventionally at the bottom or top in similar projects 

2. The 'Import/Export' section should be renamed. Maybe 'Files' is an appropriate category name. It also should not be alphabetically sorted. This is so suggestions 3-7 would fit into the category and be ordered intuitively.

3. The 'Regenerate keystore' option should be moved to the 'Import/Export keystore' options.

4. The 'Reset patches' option should be moved to the 'Import/Export patches selection' options.

5. The 'Logs' option should be moved to the 'Import/Export' (aka 'Files') section. The 'Info' section would be removed.

6. The 'Delete logs' option should be moved next to the 'Logs' option in the  'Import/Export' (aka 'Files') section.

7. The 'Delete temporary files' option should be moved to the 'Import/Export' (aka 'Files') section.

All these changes are likely difficult to visualize so here is how it would look

**Advanced**

* API URL
* Sources
* Auto update patches
* Enable changing selection
* Experimental universal patches support 
* Experimental patches support 
___
**Files**

* Export patches selection 
* Import patches selection 
* Reset patches selection
* Export keystore 
* Import keystore 
* Regenerate keystore 
* Share logs
* Delete logs
* Delete temporary files
___
**Team**

* Contributors 
* Socials
___
**About**

* etc

### Motivation

The manager settings are currently organized poorly.

### Additional context

The 'Logs' options should be renamed to 'Share logs', but ill open a separate issue for that and another minor naming issues.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by KobeW50** [comment]
![Screenshot_20230922_120351_ReVanced Manager.jpg](https://github.com/ReVanced/revanced-manager/assets/84587632/2618c17a-8ba6-4498-aadb-2f920a6f0a20)

**Comment by validcube** [comment]
cc: @PalmDevs

**Comment by Ushie** [comment]
I personally believe this is one of the things that can be left as is until the release of ReVanced Manager rewrite in Jetpack Compose, as settings are completely redone there already

**Comment by KobeW50** [comment]
> I personally believe this is one of the things that can be left as is until the release of ReVanced Manager rewrite in Jetpack Compose, as settings are completely redone there already

Would it be impossible for me (a total noob) to figure out and pr?

**Comment by oSumAtrIX** [comment]
Can't know until you try :)

**Comment by Ushie** [comment]
Shouldn't be very complicated, but let's wait for Palm to approve the suggestion first

**Comment by PalmDevs** [comment]
I think it'd make more sense if it was

##### Appearance
Theme  
Material You

##### Advanced
Auto update patches  
Allow changing patch selection  
Allow experimental patches
Show universal patches  
Sources  
API URL  

##### Import & export
Export patch selection  
Import patch selection  
Reset patch selection  
Export keystore  
Import keystore  
Regenerate keystore  


##### Debugging
Share logs  
Clear logs  
Delete temporary files  

(device model info)

**Comment by KobeW50** [comment]
> I think it'd make more sense if it was
> 
> ##### Appearance
> Theme  
> Material You
> 
> ##### Advanced
> Auto update patches  
> Allow changing patch selection  
> Allow experimental patches
> Show universal patches  
> Sources  
> API URL  
> 
> ##### Import & export
> Export patch selection  
> Import patch selection  
> Reset patch selection  
> Export keystore  
> Import keystore  
> Regenerate keystore  
> 
> 
> ##### Debugging
> Share logs  
> Clear logs  
> Delete temporary files  
> 
> (device model info)

This organization and naming looks good. 

Should the 'Team' category be at the very top or below the device info?

**Comment by PalmDevs** [comment]
> Should the 'Team' category be at the very top or below the device info?

I think above the Debugging section.
