### ISSUE TITLE
After the last update Revanced icon is gone.

### ISSUE THREAD

**Issue by Manifoldme** [ReVanced/revanced-manager#1304]
### Bug description

With all default settings the Revanced icon was replaced by a regular YouTube one. Is the a way to return the Revanced icon?

### Version of ReVanced Manager and version & name of application you tried to patch

Version: 1.10.2
Model: SM-G998B
Android Version: 13
Supported Archs: arm64-v8a, armeabi-v7a, armeabi

com.google.android.youtube_18.32.39-1539440064_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk

### Installation type

Non-root

### Device logs

```shell
I'll provide if needed.
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Ushie** [comment]
Apply the "custom-branding" patch

**Comment by StylesClashNation** [comment]
> Apply the "custom-branding" patch

Where can I find this custom branded patch?

**Comment by oSumAtrIX** [comment]
It's available in ReVanced Patches and can be used in ReVanced Manager patches selector for example. For support, move to one of our links at https://revanced.app.
