### ISSUE TITLE
bug: root problems

### ISSUE THREAD

**Issue by CanKolay3499** [revanced/revanced-manager#131]
### Type

Other

### Branch

Flutter

### Bug description

Apps that installed with "Install as root" option can't be uninstalled. When you click uninstall button app disappears but base.apk will stay in /data/app folder and when you reinstall the patched app opens.

### Steps to reproduce

1. Select some app and patch
2. Install as root
3. Uninstall the app
4. Reinstall the app from playstore, fdroid, etc...

### Relevant log output

```shell
.
```

**Comment by AndryOut** [comment]
I have the same problem, when I restart the app always reappears but without logo and without the name youtube. I don't know how to do it

**Comment by ponces** [comment]
> When you click uninstall button app disappears but base.apk will stay in /data/app folder and when you reinstall the patched app opens.

Our intention with the uninstall button was to let the user uninstalls the patched app, not the one installed by user...
Maybe it makes sense to add an "Unpatch" button together with an "Uninstall" to be more clear to the user what the manager is able to do...

**Comment by CanKolay3499** [comment]
Uninstall button in manager may be useful but you should change permission of base.apk or other apks after installation.

**Comment by ponces** [comment]
> should change permission of base.apk or other apks after installation.

wdym?

**Comment by Aunali321** [comment]
Closing because of no user response.
