### ISSUE TITLE
Remove emojis from docs

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#1312]
### Feature description

Remove all emojis from the Manager docs.

### Motivation

They aren't useful for readers, aren't professional, and are a pain for writers of the docs because they must find appropriate emojis for all new areas of text.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
The purpose of emojis is to quickly understand the current topic, it serves a functional reason and should also be kept for consistency reasons. Nobody likes a wall of text...

**Comment by KobeW50** [comment]
> The purpose of emojis is to quickly understand the current topic

That's what the titles, headers, and descriptions are for. The emojis don't carry enough information in most cases except for very simple sections, such as the ["Configuring ReVanced Manager" and "Troubleshooting" titles in the README](https://github.com/revanced/revanced-manager/tree/main/docs#-table-of-contents)

There are so many emojis that are hardly relevant to the topic and are just there because all of the other sections have one. It would at least make sense to limit emojis to titles only.

Here are some examples of emojis that make little sense. I need to consciously wonder why these are connected to the topic:

![SmartSelect_20230926_004543_GitHub.jpg](https://github.com/ReVanced/revanced-manager/assets/84587632/b4bec4bf-ee91-4725-83e4-8e8a04935856)

I still dont know how the manager has to do with a medical pill. Is it because it is like a medication that fixes apps?

![SmartSelect_20230926_004604_GitHub.jpg](https://github.com/ReVanced/revanced-manager/assets/84587632/53f40199-943a-4cfd-9a58-20d0ef552370)

Maybe these checks are pointing out that this is the main section of the page? This is already obvious from the page layout 

![SmartSelect_20230926_004620_GitHub.jpg](https://github.com/ReVanced/revanced-manager/assets/84587632/627966d5-9a03-44ac-a314-d688ebb851d4)

![SmartSelect_20230926_004630_GitHub.jpg](https://github.com/ReVanced/revanced-manager/assets/84587632/4f3e8f0d-1a4d-4c14-9f70-2850dae5d277)

![SmartSelect_20230926_004638_GitHub.jpg](https://github.com/ReVanced/revanced-manager/assets/84587632/543a0ddb-4a2d-4bde-a4f0-599330839b70)

A star for essential settings?

![SmartSelect_20230926_004655_GitHub.jpg](https://github.com/ReVanced/revanced-manager/assets/84587632/b81c2121-51db-4631-8f19-c19ae628431b)

I dont see how a syringe has anything to do with a patching error, or how a blast is related to an installation error. Some of the other errors have sensical emojis. Its a shame that they cant be reused even where it makes sense.

![SmartSelect_20230926_004804_GitHub.jpg](https://github.com/ReVanced/revanced-manager/assets/84587632/a40eb85e-4baf-4d44-aca3-49032e314e63)








> ... and should also be kept for consistency reasons. 

Can you elaborate?

**Comment by oSumAtrIX** [comment]
> That's what the titles, headers, and descriptions are for. 

Those are not enough. Emojis help convey the topic quickly.

>  would at least make sense to limit emojis to titles only.

They'd lose all purpose they currently have which is to help readability

> Can you elaborate?

Every of our other documents follows the same style.

If the emojis themselves are in question, open a separate issue for discussion with suggestions
