### ISSUE TITLE
feat: <title>

### ISSUE THREAD

**Issue by prashantbounthiyal** [ReVanced/revanced-manager#1313]
### Feature description

i request team YouTube revanced please enable precise seeking. 

### Motivation

This feature is important because sometimes you don't want to watch a whole boring video due to its boring nature. Instead, you want to jump directly to the main part for which you clicked on the video.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Ushie** [comment]
This was an issue with ReVanced Patches, it's been fixed and should be available to use in around a week's time

Repatch your app around a week from now, this issue should be fixed

Closing as this isn't related to ReVanced Manager
