### ISSUE TITLE
bug: Error when trying to build "Compose-Dev"

### ISSUE THREAD

**Issue by TeaOwO** [ReVanced/revanced-manager#1320]
### Bug description

How do i build the Compose rewrite of the revanced manager? i tried building it but it gave me:
```
> Task :app:compileDebugAidl FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugAidl'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not resolve app.revanced:revanced-patcher:14.2.1.
     Required by:
         project :app
      > Could not resolve app.revanced:revanced-patcher:14.2.1.
         > Could not get resource 'https://maven.pkg.github.com/revanced/revanced-patcher/app/revanced/revanced-patcher/14.2.1/revanced-patcher-14.2.1.pom'.
            > Username must not be null!
```
Using the docs's method didnt work either. as i couldn't find `~/.gradle/gradle.properties` and gradle.properties didnt show me `~/.gradle/gradle.properties`, 

im sorry if this is really obvious and im just an idiot. (idk anything about building apps from the source)

### Version of ReVanced Manager and version & name of application you tried to patch

Version: https://github.com/ReVanced/revanced-manager/tree/compose-dev

### Installation type

None

### Device logs

```shell
None.
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Ushie** [comment]
You can create the gradle.properties file in ~/.gradle/, can you do that and reply back?

**Comment by oSumAtrIX** [comment]
That will solve the issue

**Comment by TeaOwO** [comment]
Thanks, I'll try that!
