### ISSUE TITLE
add a delete patch (hide full screen panel)

### ISSUE THREAD

**Issue by ZeyFoxOFF** [ReVanced/revanced-manager#1321]
### Feature description

I would like the patch "hide full screen panel" be re added to youtube because I have the following problem. When I am in full screen and I click on the title or chapters that does nothing, nothing happens

### Motivation

It would be nice to add it because it would allow to settle this problem

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [ ] The issue is solely related to the ReVanced Manager

**Comment by validcube** [comment]
👋 Hello! Unfortunately, this isn't the correct repository to open an issue as ReVanced Manager only manage and patch application.

You should open an issue at the ReVanced Patches repository which is here! https://github.com/ReVanced/revanced-patches/issues/new?assignees=&labels=patch-request&projects=&template=patch-request.yml&title=feat(youtube):%20add%20a%20hide%20full%20screen%20panel

**Comment by ZeyFoxOFF** [comment]
oh Okay thank you. sorry
