### ISSUE TITLE
tasker patcher 

### ISSUE THREAD

**Issue by rahul-rkc** [ReVanced/revanced-manager#1322]
### Feature description

earlier there used to be tasker patcher but now its removed

### Motivation

cant able to use tasker new version without patch

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [ ] The issue is solely related to the ReVanced Manager

**Comment by validcube** [comment]
👋 Hello! This issue isn't related to the ReVanced Manager, ReVanced Manager is simply tool to help you manage and patch the application.

Please see the reason why Tasker was removed from ReVanced Patches here!
