### ISSUE TITLE
bug: 0 patches

### ISSUE THREAD

**Issue by GKid94** [ReVanced/revanced-manager#1323]
### Type

Other

### Bug description

I patched and installed new YouTube version over the previous one and now it shows 0 patches in the Manager

### Steps to reproduce

1. Download the new recommended YouTube APK
2. Patch it in the Manager and install it with the previous YouTube Revanced version installed
3. When it's done go to Revanced Manager and it will show 0 patches for YouTube

### Relevant log output

```shell
/
```

### Screenshots or videos

![Screenshot_2023-09-30-13-51-57-324_app revanced manager flutter](https://github.com/ReVanced/revanced-patches/assets/18757054/f38991bb-b6c2-4758-95ae-e8fe4b8682b8)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by twinko** [comment]
Same bug here. Manager version 1.11.1
But if i remember correctly this bug exists longer than 2 months.

**Comment by twinko** [comment]
Issue is fixed. 

![Screenshot_20231114_231236_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/11973158/e90a1b29-63a5-406a-a5e4-89457fa079bb)
![Screenshot_20231114_231241_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/11973158/f2914863-a798-4457-92b5-81c9aa892b57)

**Comment by GKid94** [comment]
> Issue is fixed.
> 
> ![Screenshot_20231114_231236_ReVanced Manager](https://user-images.githubusercontent.com/11973158/282947423-e90a1b29-63a5-406a-a5e4-89457fa079bb.jpg) ![Screenshot_20231114_231241_ReVanced Manager](https://user-images.githubusercontent.com/11973158/282947474-f2914863-a798-4457-92b5-81c9aa892b57.jpg)

I don't see the patched apps in the Manager and I have YouTube Revanced

**Comment by oSumAtrIX** [comment]
Not sure what this means, reopen if still occuring.

**Comment by gio1135** [comment]
it happens when you try to mount, not install revanced package

**Comment by drooooov** [comment]
I tried still dint work

**Comment by oSumAtrIX** [comment]
Please open a new issue if relevant
