### ISSUE TITLE
Revanced Patch for Android TV

### ISSUE THREAD

**Issue by nareshmehta8520** [ReVanced/revanced-manager#1324]
### Feature description

Please add Revanced for Android TV.
I don't know how to deal with microg in TV but if it's possible please think about it.

### Motivation

TV

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by validcube** [comment]
👋 Hello! Your issue was closed because it's irrelevant to the ReVanced **Manager**.

**Comment by validcube** [comment]
Consider opening an issue at ReVanced Patches' repository instead which is here! -> https://github.com/ReVanced/revanced-patches
