### ISSUE TITLE
feat: <Question> how can I add custom repo

### ISSUE THREAD

**Issue by ansarimohammed422** [ReVanced/revanced-manager#1327]
### Feature description

This question is about revanced manager compose:-

How can I add custom repos like revanced extended or ReX repos in new manager

Can any one help

### Motivation

I want to test it

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
If the feature is implemented, via the settings.

**Comment by ansarimohammed422** [comment]
Then what's the plus button is for in patch bundle

**Comment by oSumAtrIX** [comment]
You can select patches locally or from a remote URL.
