### ISSUE TITLE
Selected patches are in strange order

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#1331]
### Bug description

The selected patches in the card are seemingly in a random order at first. And if you select new patches the most recently selected patches will be at the bottom of the list.

For example, this is the default order for the default YT Music patches.

![SmartSelect_20231005_041125_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/84587632/151bc54d-9d24-459c-b054-8ed1cee38277)

They should always be ordered alphabetically just like the patches selection menu list.

### Version of ReVanced Manager and version & name of application you tried to patch

1.11.0

### Installation type

None

### Device logs

```shell
NA
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by validcube** [comment]
👋 Hello! Thank for reporting this issue, 

Your issue has been assigned, and will be fix very shortly.

**Comment by validcube** [comment]
Nevermind, ignore that, turn out GitHub didn't give me a notification.

> 👋 Hello! Thank for reporting this issue,
> 
> Your issue has been assigned, and will be fixed very shortly.
> 
> ~wait, what's the point of saying this I've already finished~
