### ISSUE TITLE
Ignore punctuation when searching patch list

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#1333]
### Feature description

The search function should not care if you skip over any punctuation in the patch name.

### Motivation

Some patches have punctuation in the title, which makes it difficult to search for them, as demonstrated with this screen recording.

https://github.com/ReVanced/revanced-manager/assets/84587632/075200dd-5a08-43b7-8ae8-7e71befe53f2

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by validcube** [comment]
I supposed we could use approximate string matching algorithm. I'll look into it during this weekend _or next weekend._
