### ISSUE TITLE
bug: Revanced Manager completely crashing when fetching the 1.11.0 update

### ISSUE THREAD

**Issue by Timbo303** [ReVanced/revanced-manager#1334]
### Bug description

The app just flat out crashes on my samsung s21 whenever I try to apply the new 1.11.0 update. Reseting data doesnt fix it.

### Version of ReVanced Manager and version & name of application you tried to patch

v1.10.3

### Installation type

Non-root

### Device logs

```shell
Cant even get into app half the time will try my best to get the log.
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by KobeW50** [comment]
https://github.com/ReVanced/revanced-manager/issues/1330

You will need to download the new manager from revanced.app/download

**Comment by Ushie** [comment]
You'll need to install the latest ReVanced Manager from https://revanced.app/download, unfortunately there's nothing we can do to fix this bug on previous versions but it's fixed on latest
