### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by Dae-Hang-Sook** [ReVanced/revanced-manager#1337]
### Bug description

Apparently this update was so drastically that it caused the application to stop functioning so in having to re-download it. Maybe check that out?

### Version of ReVanced Manager and version & name of application you tried to patch

N/A (Before 1.11.1)

### Installation type

None

### Device logs

```shell
N/A
```

### Acknowledgements

- [ ] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Latest version fixes
