### ISSUE TITLE
bug: Notice "hide load more button" when Patching even if it is unselected

### ISSUE THREAD

**Issue by megamorphg** [ReVanced/revanced-manager#1338]
### Bug description

1. Patch YouTube 18.32.39
2. Select "Default" patch selection
3. Get a notice regarding "Hide load more button" feature even if it is manually unselected

### Version of ReVanced Manager and version & name of application you tried to patch

Revanced Manager: 1.11.1
Youtube 18.32.39

### Installation type

Non-root

### Device logs

```shell

```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Ushie** [comment]
This issue should be opened in the ReVanced Patches repository
