### ISSUE TITLE
Save apk button create empty file + crash

### ISSUE THREAD

**Issue by N4TH4NOT** [ReVanced/revanced-manager#1348]
### Bug description

After compiling new apk, the 'save' button crash the application and fresh new apk file is empty.
Same thing happens with all permission enabled.

### Version of ReVanced Manager and version & name of application you tried to patch

ReVanced Manager v1.11.2
YouTube Revanced Patch of 8th October 2023
YouTube v18.38.44 (apk file)

### Installation type

Non-root

### Device logs

```shell
Link: https://pastebin.com/KqNCM8bK
Password: Uz#36stfP_4kDz
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by KobeW50** [comment]
Try to regenerate the keystore. Then patch and export again. If the issue is then resolved, refer to https://github.com/ReVanced/revanced-manager/issues/1253
