### ISSUE TITLE
An error occurred, could not find "div#content" .

### ISSUE THREAD

**Issue by ghost** [ReVanced/revanced-manager#1352]
### Bug description

On the compose rewrite of revanced manager, when I try to see the list of downloadable apps, this error happens.

![Screenshot_20231009-174155~2](https://github.com/ReVanced/revanced-manager/assets/123305689/2e4feaa6-982a-410e-a244-fc6ea7e0c511)

### Version of ReVanced Manager and version & name of application you tried to patch

Revanced manager (Compose Rewrite)
The latest commit
Version 0.0.1 (1)
![Screenshot_20231009-174542~2](https://github.com/ReVanced/revanced-manager/assets/123305689/db7f78e9-ff81-46cd-bc4e-f06f1a524b80)

### Installation type

Non-root

### Device logs

```shell
.
```

### Patcher logs

```shell
.
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Axelen123** [comment]
What app are you trying to download? Is the app available on apkmirror?

**Comment by Axelen123** [comment]
Confirmed, although the trigger seems to be inconsistent.

@CnC-Robert can you look into this?
