### ISSUE TITLE
feat: About icons

### ISSUE THREAD

**Issue by BabyOilJohnson** [ReVanced/revanced-manager#1353]
### Feature description

Change "dashboard" icon to [selected](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Adashboard%3AFILL%401%3Bwght%40400%3BGRAD%400%3Bopsz%4024) and [deselected](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Adashboard%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Chnage "patcher" icon to [selected](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Abuild%3AFILL%401%3Bwght%40400%3BGRAD%400%3Bopsz%4024) and [deselected](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Abuild%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "settings" to [selected](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Asettings%3AFILL%401%3Bwght%40400%3BGRAD%400%3Bopsz%4024) and [deselected](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Asettings%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 

In app page;
Change "open" icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aopen_in_new%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "uninstall" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Adelete%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 

In patched page; 
Change "save" icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Asave%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "log" icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Apost_add%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "install" icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Adownload%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 

Change back arrow to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aarrow_back%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change search icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Asearch%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "storage" icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Asd_card%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "tick" icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Adone%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 

In settings page;
Change "arrow" icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aarrow_drop_down%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "reset" icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Amanage_history%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)  
Change "API" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aapi%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change *patch" icon to[this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aextension%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "integrations" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Amerge%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)

Edit(updated link)
### Motivation

More materialized(rounded).

### Acknowledgements

- [x] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Good suggestions. 

The patcher should remain a syringe as it is the "symbol" of the patcher and using the download icon for installation may not be correct.

**Comment by KobeW50** [comment]
The suggested dashboard icons for selected and deselected are identical

**Comment by BabyOilJohnson** [comment]
> The suggested dashboard icons for selected and deselected are identical

Sorry about that, I have updated the link.

**Comment by validcube** [comment]
@PalmDevs

**Comment by Ushie** [comment]
Hey! 👋 

The suggested icons are part of Material **Symbols**, rather than Material Icons, unfortunately, some suggested icons weren't available for us.

It is possible to move to Material Symbols, but with a [third-party library](https://pub.dev/packages/material_symbols_icons) to replace Flutter's first-party one

Overall, I think this issue will take a bit more time than I think would be ideal, especially considering that there's active work on a complete rewrite and redesign of the app ongoing
