### ISSUE TITLE
Universal patches cannot be used when 'Enable changing selection' is disabled

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#1355]
### Bug description

If a user enables the Universal patches, they still cant use those patches unless the Enable changing (patches) selection toggle is enabled. If the user wants to display the universal patches they probably want to be able to use them.

The solution is to allow universal patches to be selected in the patches list even when 'Enable changing (patches) selection' is disabled.

### Version of ReVanced Manager and version & name of application you tried to patch

1.11.2

### Installation type

None

### Device logs

```shell
NA
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
I'm not sure; this behavior is intended. Universal patches can be included by default, so even if you have enabled changing selection disabled, the user should not be able to change the selection.
