### ISSUE TITLE
feat: Add user agent for requests

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1359]
### Feature description

The app should specify a user agent for outgoing requests.

### Motivation

The user agent is necessary to make diagnostics properly regarding the API. An example would be to know which version of ReVanced Manager tries to request a specific endpoint multiple times:

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/d632fc3a-493e-42ae-a0db-6a40f6e723f6)

### Additional context

The user agent should follow https://www.rfc-editor.org/rfc/rfc9110#name-user-agent and be added to the current Flutter version of ReVanced Manager as well as the Compose version.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by BenjaminHalko** [comment]
@oSumAtrIX Where should the user agent string variable be initialized in Flutter? In the manager api? Or is there a better location. -

**Comment by validcube** [comment]
👋 The discussed format for User-Agent was

```http
User-Agent: ReVanced-Manager/1.12.1
```

----------------------------------------------------------

👀 Checkout the full conversation discussed in team 
https://discord.com/channels/952946952348270622/952987428786941952/1162750500266062006

**Comment by validcube** [comment]
🥞 Closing this as complete!
