### ISSUE TITLE
feat: Export and Import patch options

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#1363]
### Feature description

Add the ability to import and export the patch options. Ideally to an options.json file which would be compatible with the CLI.

### Motivation

There are many cases where this feature would be useful.

1) You can backup your set options in the case where you would need to uninstall the ReVanced Manager.

2) You can share your configurations with others.

3) You can easily switch between the CLI and Manager and have your preferences set in both.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by SodaWithoutSparkles** [comment]
I also second this as this would make trouble-shooting when using dev patches much easier

**Comment by oSumAtrIX** [comment]
ReVanced Manager will soon be released as [a full rewrite](https://github.com/ReVanced/revanced-manager/tree/compose-dev). Over time, many feature requests have been made for the current version of ReVanced Manager, but to accelerate the development of the new version of ReVanced Manager, we have to focus on it, which I am closing this issue according to the [contribution guidelines](https://github.com/ReVanced/revanced-manager/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long/ Low priority/ Maintainers un-interested/ Too complex to realize
- Feature planned/ already implemented for the new version of ReVanced Manager
- Already implemented

Regardless, anyone who comes across this feature request can PR it to the current version of ReVanced Manager until the new version is ready. Thanks for your feature request!
