### ISSUE TITLE
Required patch options can be left empty in some cases

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#1367]
### Bug description

The manager requires some patch options to be filled-in. This requirement can be bypassed by simply typing a letter and then removing the letter as demonstrated in this screen recording:

https://github.com/ReVanced/revanced-manager/assets/84587632/e6896337-a5cf-48d5-8b8f-05c3bf2ab7be

The requirement will reappear when the reset button is pressed, but it should also always appear when the required field is empty.

### Version of ReVanced Manager and version & name of application you tried to patch

1.12.1

Sync

### Installation type

None

### Device logs

```shell
Can be given if needed
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
This is not a bug but intended design. An empty string is different from null.
