### ISSUE TITLE
'Load patches selection' button is bold and off-centered

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#1372]
### Bug description

The text in the button is in bold for no reason, and there is far more space on the right of the text than to the left of the text. 

![Screenshot_20231013_165119_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/84587632/e5edf03f-6fe9-486f-b1b1-67edd831f52c)

### Version of ReVanced Manager and version & name of application you tried to patch

1.12.1

S22+

### Installation type

None

### Device logs

```shell
NA
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by validcube** [comment]
👋 Hello!

The popup menu being off-centre is expected, it's supposed to be aligned to the left like this!

![image](https://github.com/ReVanced/revanced-manager/assets/93124920/ff7b1055-f72a-4006-ba6f-0528a59dd826)

This will be fixed when popup menu has been replaced with native component. (which is what you see above!)
