### ISSUE TITLE
App Manager in Portuguese (Pt-Br)

### ISSUE THREAD

**Issue by OgaihT0313** [ReVanced/revanced-manager#1373]
### Feature description

Translate the application into Portuguese, for a better understanding of the application's functions. 

### Motivation

Many don't know what to do within the app

### Acknowledgements

- [ ] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by ILoveOpenSourceApplications** [comment]
#1383 has the potential to resolve this feature request right?

**Comment by validcube** [comment]
🥞 This issue have been resolved by the release of v1.19.0
