### ISSUE TITLE
More version support for youtube

### ISSUE THREAD

**Issue by SveyPlay** [revanced/revanced-manager#138]
### Type

Functionality

### Branch

Flutter

### Issue

There can be problems with newer, unsupported, versions of youtube (and the other apps that you can patch)

### Feature

Itk what do say, look at the title

### Motivation

Better app and more people would use it

**Comment by ViktorVoloshko** [comment]
This should be requested here: https://github.com/revanced/revanced-patches

This GitHub is for Manager, Manager devs aren't patches devs, they're only using what patches devs did and released.
