### ISSUE TITLE
bug: Patched app missing in `Patched apps` after updating from old to new version

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-manager#1391]
### Bug description

Patched app section won't display the patched app when updating from a lower version of the app to latest version. The user has to patch the latest app once again for it to show up under patched apps section.

### Version of ReVanced Manager and version & name of application you tried to patch

ReVanced Manager v1.13.1

### Installation type

Non-root

### Device logs

```shell
Nil
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by GKid94** [comment]
Same problem
![277513578-6ca5bc05-25ed-4c4d-af86-68d309c348a6](https://github.com/ReVanced/revanced-manager/assets/18757054/41c71865-6c60-4ddd-bdc1-9547880f4848)
![277513581-4be248fc-3006-4395-bc53-71aaa50bf91e](https://github.com/ReVanced/revanced-manager/assets/18757054/17b78c5d-5c6c-4489-9ee0-0f2f238a767b)
![277513582-820c5238-d0ba-4f64-9a20-ecc4becb5dcb](https://github.com/ReVanced/revanced-manager/assets/18757054/053b2a36-5c8c-401b-a7fa-9f5232d82388)

**Comment by GKid94** [comment]
Same problem 😕
![Screenshot_2023-11-16-02-25-12-383_app revanced manager flutter](https://github.com/ReVanced/revanced-manager/assets/18757054/debf3f43-f394-4319-891f-58152ab10ce9)
![Screenshot_2023-11-16-02-25-18-773_com miui securitycenter](https://github.com/ReVanced/revanced-manager/assets/18757054/b2832aee-6148-40dc-80bc-7d792b2661e8)
