### ISSUE TITLE
bug: Refresh icon animation and placement isn't proper

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-manager#1392]
### Bug description

When refreshing `Dashboard`, the refresh icon shows up and instead of doing a circular motion it does a reverse of incoming motion. (Don't judge me for phrasing it this way.)

What ReVanced Manager does:

https://github.com/ReVanced/revanced-manager/assets/117499019/b3601f3e-d398-4cf9-96e0-965141a7fbd8

What it should be doing:

https://github.com/ReVanced/revanced-manager/assets/117499019/d8a8207f-e3e0-4345-a464-f486c29fe7bc

Also, the refresh icon starts showing up all the way from the notification shade instead of showing up within the manager. It should start from the point in the `Dashboard` where `Settings` gets the padding when scrolling.

Without scrolling:
![Screenshot_20231016-004948~2](https://github.com/ReVanced/revanced-manager/assets/117499019/b6b79f65-b687-4a64-a263-ca65ea293ec3)
When scrolled down a bit:
![Screenshot_20231016-004919~3](https://github.com/ReVanced/revanced-manager/assets/117499019/5ec4b40a-d193-41a0-8de4-20845b802d5b)
The refresh icon should start after the padded area of `Settings` in `Dashboard`, like it's coming from underneath the padded area.

### Version of ReVanced Manager and version & name of application you tried to patch

ReVanced Manager v1.13.1

### Installation type

Non-root

### Device logs

```shell
Nil
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by validcube** [comment]
This issue depends on the dependency that we are using for the refresh indicator.

https://pub.dev/packages/pull_to_refresh

Please open an issue at https://github.com/peng8350/flutter_pulltorefresh

**Comment by ILoveOpenSourceApplications** [comment]
I checked out the examples provided in the repository and [`MaterialClassicHeader`](https://github.com/peng8350/flutter_pulltorefresh/blob/master/lib/src/indicator/material_indicator.dart) seems to be the one which is implemented in ReVanced Manager. But, I have no complaints on how its shown there as the refresh animation is perfect. I don't think it's a bug from his end. Correct me if I'm wrong. 
P.S: Attaching the gif for further clarity
![material_classic](https://github.com/ReVanced/revanced-manager/assets/117499019/a9b88c3b-40a5-4cdb-951e-2e175d290ae3)

**Comment by validcube** [comment]
> @validcube, so is it still an issue with the dependency or the way we implemented it? 

Ah, what I meant be that is you need to open a feature request for the refresh indicator.

**Comment by ILoveOpenSourceApplications** [comment]
Oh, okay git it. Will do that then. Thanks!
