### ISSUE TITLE
feat: Support for Android 14

### ISSUE THREAD

**Issue by githubUser01946** [ReVanced/revanced-manager#1393]
### Feature description

I am currently on Samsung One UI 6 (beta) and Revanced Manager will not stay open, as soon as it opens it closes.

### Motivation

I would like to keep my manager and the revanced up to date but this little issue prevents it.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Ushie** [comment]
Update to the latest ReVanced Manager from https://revanced.app/download
