### ISSUE TITLE
bug: Patch log info is out of order

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#1396]
### Bug description

In exported patch logs, the 'Show universal patches' bool comes before the 'Version compatibility check' bool. This is not the order that they appear in in the manager settings. 

Order in log:
![SmartSelect_20231016_030122_GitHub.jpg](https://github.com/ReVanced/revanced-manager/assets/84587632/d9f42203-b5f8-49a6-825d-12ae55d8ce8b)

Order in settings:
![SmartSelect_20231016_180943_ReVanced Manager.jpg](https://github.com/ReVanced/revanced-manager/assets/84587632/2d1c86f3-4d09-4f58-a11f-5bf40d5ff821)

### Version of ReVanced Manager and version & name of application you tried to patch

1.13.1

### Installation type

None

### Device logs

```shell
NA
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by validcube** [comment]
🥞 The fix for this issue (#1398) has been released!

**Comment by KobeW50** [comment]
Thank you @validcube 

Also, your comments and PRs are always very entertaining to read :)

And the graphics are always nice
