### ISSUE TITLE
Option to backup (or alternatively, export packages), post-build

### ISSUE THREAD

**Issue by Thisisauser6443** [revanced/revanced-manager#140]
### Type

Functionality

### Branch

Flutter

### Issue

In my opinion, it's not so much as one of the **largest** problems, but while building an APK is an easy process, in some cases, especially my experience with YouTube (`17.33.42`, at the time), the process does take a while with attempting to apply a multitude of patches, to it, and can be tedious for some _(Including myself, lol_).

### Feature

What I think could be implemented is a way to simply **backup/export the packages to the internal storage**.

Let's say, after attempting to see if a patch can function with an unrecommended build number of YT, it fails to launch/has major usability bugs, I could simply revert to the _last known good package_, without needing to rebuild, again, in less than a minute (give or take), rather than needing to try and remember all of the patches you had/didn't have, off the top of your head

And believe me, with the few braincells I have left, it's getting harder and harder

### Motivation

Truth is, a lot of us are, without admitting to it, impatient, and, like I said, this would help with interchangeability between older/newer builds of patched programs. The only issue with my request, AFAIK, is whether this could probably lead to people distributing packages, but I'm wondering what others will make of this

**Comment by nkitsaini** [comment]
I agree with you. Having an export is an easy option which I was surprised to see is not present. I'll take a look at the code and possibly open a PR if others agree.

**Comment by Aunali321** [comment]
@nkitsaini do you still planning on opening a PR?

**Comment by nkitsaini** [comment]
Yes, I'm most probably create the PR by the coming week. @Aunali321
