### ISSUE TITLE
bug: Material You toggle is broken

### ISSUE THREAD

**Issue by Kuddus73** [ReVanced/revanced-manager#1410]
### Bug description

https://github.com/ReVanced/revanced-manager/assets/127908708/55d43198-7105-48b3-8e81-2fa715685133

**Device environment:**
Samsung S22, Android 13, One UI 5.1

### Version of ReVanced Manager and version & name of application you tried to patch

ReVanced Manager v1.13.1

### Installation type

Non-root

### Device logs

```shell
N/A
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by validcube** [comment]
👋 Hello, please include your device information in the issue (It can be anywhere on the issue, but I prefer if you put them at the top!).

Example:
📱 I'm using Samsung M23 5G running on Android 13 (or One UI 5.1)

**Comment by Kuddus73** [comment]
> 👋 Hello, please include your device information in the issue (It can be anywhere on the issue, but I prefer if you put them at the top!).
> 
> Example: 📱 I'm using Samsung M23 5G running on Android 13 (or One UI 5.1)

Included.

**Comment by Danik2343** [comment]
It's working, but visual toggle broken, tap on toggle, enter in main menu and return to settings

**Comment by KobeW50** [comment]
I'm able to reproduce this. Here's the manager logs. Hope it helps

![revanced-manager_logcat_20231021201932776925.txt](https://github.com/ReVanced/revanced-manager/files/13062076/revanced-manager_logcat_20231021201932776925.txt)

**Comment by validcube** [comment]
🤔 Not sure how did I managed to reproduce, but I believe it should happens on new user.

**Comment by validcube** [comment]
I managed to find a workaround for now.

* Change App theme to Dark, and switch to System
* Try turning on the Material You toggle

**Comment by KobeW50** [comment]
> I managed to find a workaround for now.
> 
> 1. Change App theme to Dark, and switch to System
> 2. Try turning on the Material You toggle

This works. Changing the theme (to anything) will fix the issue until the manager is restarted.

**Comment by Danik2343** [comment]
> > I managed to find a workaround for now.
> > 
> > 1. Change App theme to Dark, and switch to System
> > 2. Try turning on the Material You toggle
> 
> This works. Changing the theme (to anything) will fix the issue until the manager is restarted.

Agree, works too
