### ISSUE TITLE
feat: View ReVanced patches' changelog from ReVanced Manager

### ISSUE THREAD

**Issue by drshtmstry** [ReVanced/revanced-manager#1413]
### Feature description

Add a feature to see release notes of new patch versions from Revanced manager homescreen (dashboard).
Similar to changelog of app updates seen in playstore.

### Motivation

Currently we need to go to revanced patches github page to view all the changes.
We can only see when new patches were released, but not what has changed.
Like when a newer version of is supported so that we need to patch that app again.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by TheAabedKhan** [comment]
You can read the changelogs (and then update accordingly) if you disable `Auto updates patches` from the settings page.
