### ISSUE TITLE
Apps title and icon

### ISSUE THREAD

**Issue by amijafi** [ReVanced/revanced-manager#1417]
### Feature description

Please include icon and app title for apps that are supported for patch but not installed on phone yet

### Motivation

Cause Sometimes user finds an interesting but not yet installed app in supported apps and wants to try it . For now , as the app tirle and ucon is not shown , user can't really distinguish them only from package name

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
The app is not installed, there is no way to infere the app name or icon. Any other attempt would involve having to use a limited database
