### ISSUE TITLE
feat: Preview patch list before selecting application

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#1418]
### Feature description

Allow the user to see the list of patches for an app without needing to have a non-split app installed. 

![Screenshot_20231023_101858_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/84587632/2b1033ef-4137-469f-ae35-a1dd7b461c96)

(This demonstration above is a terrible design. A better one may be to add a new line in the card which will have the amount of patches, and then that can be clickable.

![photostudio_1698071671601](https://github.com/ReVanced/revanced-manager/assets/84587632/dd217140-04ba-4b5e-b3b9-4e7cc140fa09)

Edit: Another possible design is to give the option when the user tries selecting the app card. 

![SmartSelect_20231023_143643_ReVanced Manager.jpg](https://github.com/ReVanced/revanced-manager/assets/84587632/4d29ed6b-1085-4d69-ba9c-c0c4bd2273fe)

A new popup would need to be made for apps that arent installed.

### Motivation

The user should not need to go to revanced.app/patches to see what patches are available for an app that is installed as a split APK or not installed on their device.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
The patch selector view model can include a readOnly boolean for that.

**Comment by oSumAtrIX** [comment]
>  they should just be taken straight to the patch selection menu without it being read-only.

This would introduce a new flow of action. Usually, you select an app, which brings you back to the patcher screen, and then you select the patches. Here, it would skip bringing you back to the patcher screen, which is inconsistent in behavior to the current flow of action. So either you display the patches screen readonly with the option to go back to the app selector screen, or you change the flow from "select app -> go back -> select patches" to "select app -> select patches" everywhere.

**Comment by KobeW50** [comment]
Closing in favor of https://github.com/ReVanced/revanced-manager/issues/2093

Also https://github.com/ReVanced/revanced-manager/issues/2310 is relevant

**Comment by btraas** [comment]
Can this be re-opened now that #2093 is canceled? This one should be much simpler to implement

**Comment by Ushie** [comment]
It's implemented in the upcoming Jetpack compose version of ReVanced Manager
