### ISSUE TITLE
bug: Patched apps not shown in ReVanced Manager

### ISSUE THREAD

**Issue by ikerinagy** [ReVanced/revanced-manager#1419]
### Bug description

I've patched a few apps via WSA using the official ReVanced Managed, because I couldn't patch them on my phone.
After sideloading them to my phone, ReVanced Manager states that there are no patched apps installed.
In the past sideloaded apps were also shown.

![Screenshot_20231024_073552_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/145727702/94e3e88d-f532-4140-90a0-1a432a81dffb)
![Screenshot_20231024_073624_My Files](https://github.com/ReVanced/revanced-manager/assets/145727702/1214d31a-0606-4d28-9262-be85361b8daa)
![Screenshot_20231024_073637_YouTube](https://github.com/ReVanced/revanced-manager/assets/145727702/ee1abb58-c338-4ba0-97c6-a61035cb6ede)
![Screenshot_20231024_073651_TikTok](https://github.com/ReVanced/revanced-manager/assets/145727702/e696d8f0-0193-4ef8-adfe-1baaf40316bf)

### Version of ReVanced Manager and version & name of application you tried to patch

1.14.0

### Installation type

Non-root

### Device logs

```shell
No patch selection to export
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
ReVanced Manager can't know these are patched apps if it didn't patch them

**Comment by ikerinagy** [comment]
> ReVanced Manager can't know these are patched apps if it didn't patch them

The apps were patched with ReVanced Manager, just not on this device.
I thought it's a bug, because a few months back they were shown.
