### ISSUE TITLE
feat: Truecaller premium 

### ISSUE THREAD

**Issue by Zaxx69** [ReVanced/revanced-manager#1442]
### Feature description

Please add a truecaller premium patch 

### Motivation

Ads and pop ups are irritating 

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [ ] The issue is solely related to the ReVanced Manager

**Comment by Ushie** [comment]
This issue isn't related to ReVanced **Manager**, it's related to ReVanced Patches, https://github.com/ReVanced/revanced-patches/issues?q=is%3Aissue+Truecaller+

**Comment by Zaxx69** [comment]
I am sorry ,i will delete it
