### ISSUE TITLE
S21 - Revanced Manger stuck loading patches

### ISSUE THREAD

**Issue by Gamerboi520** [ReVanced/revanced-manager#1443]
### Bug description

Just opening the app and it can't load correctly 

![Screenshot_20231028_202733_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/84089845/f1e78bb7-1588-4f52-a8b5-5dd061631ddb)

### Version of ReVanced Manager and version & name of application you tried to patch

Just revanced manager - patched apps work fine

![Screenshot_20231028_202913_Settings](https://github.com/ReVanced/revanced-manager/assets/84089845/b77f7ce6-9228-442f-9a41-69b595091bfe)

[revanced-manager_logcat_20231028203045510157.log.txt](https://github.com/ReVanced/revanced-manager/files/13196972/revanced-manager_logcat_20231028203045510157.log.txt)

### Installation type

Non-root

### Device logs

```shell
Device logs included above since i wasn't given the option to add a file.
```

### Patcher logs

```shell
Not needed as it's not the effected issue.
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Gamerboi520** [comment]
Cleared cache
Reset patches
Regenerated keystore
Deleted temporary files
Reset patch selection
Reset patch options
Reinstalled the app completely (last resort, issue still persisting)

**Comment by oSumAtrIX** [comment]
The API is currently down
