### ISSUE TITLE
Unable to select patches

### ISSUE THREAD

**Issue by Gautam-Pra** [ReVanced/revanced-manager#1448]
https://github.com/ReVanced/revanced-manager/assets/84336961/39bdb224-eb30-4c67-8cf2-03186d6a1015

I have Android 10 device before update it was working fine and able to select paches but now it showing a white screen 

### Version of ReVanced Manager and version & name of application you tried to patch

RVX manager version 1.14.3 

I tried to patch YouTube latest suggested apk

### Installation type

Non-root

### Device logs

```shell
Unable to extract patch
It showing incorrect path dialog every time
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Gautam-Pra** [comment]
Uploading 2023_10_30_15_29_52.mp4…

**Comment by TheAabedKhan** [comment]
No support for unofficial ReVanced services.

**Comment by KobeW50** [comment]
@Gautam-Pra Refer to https://github.com/inotia00/ReVanced_Extended/issues/1602
