### ISSUE TITLE
Manager crashing while patching

### ISSUE THREAD

**Issue by SveyPlay** [revanced/revanced-manager#145]
### Type

Error while running the manager

### Branch

Flutter

### Bug description

The Manager crashes when starting to patch YouTube.

I am rooted, have microg installed and have a supported version.

Version 0.0.7
### Steps to reproduce

Download YouTube apk, select apk and a few patches and start patching *crashes*

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
*Crashes*
```

### Screenshots or videos

https://drive.google.com/file/d/1--He6NkwKr4awRqd-RjZxxaf2T0poswO/view?usp=drivesdk

### Solution

Fix the bug somehow.

**Comment by Aunali321** [comment]
Go to manager settings, scroll to bottom and click on share logs and upload it here.

**Comment by SveyPlay** [comment]
> Go to manager settings, scroll to bottom and click on share logs and upload it here.

Wait, now it suddenly works!!
