### ISSUE TITLE
feat: improve performance for list items

### ISSUE THREAD

**Issue by PalmDevs** [ReVanced/revanced-manager#1453]
### Feature description

Performance of any pages with high amounts of list items need to be improved. Currently on worse devices (likely CPU-based), there are stutters when scrolling which has somewhat of a negative impact in UX. The issue stems from the usage of `LazyColumn`, worse devices cannot render them fast enough. There are three possible solutions:

1. Try to optimize the currently existing `LazyColumn`
2. Switch to use `Column` instead
   This means no lazy loading and may cause screen freeze when rendering all the items first time.
3. Switch to use native Android's `RecyclerView`
   Maybe harder to achieve but is the **best solution** in my opinion.

### Motivation

Older or worse devices *(these devices can still patch apps)* may not be able to handle `LazyColumn` which causes stutters when scrolling, this has a negative impact in UX.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Axelen123** [comment]
`LazyColumn` is being used correctly here and we cannot optimize it ourselves. The performance of `LazyColumn` can be improved with keys, but that is already implemented.

App list and patch list seem to generally run well on officially supported devices, so I am going to close this.
This issue can be reopened if devices that meet the following criteria are common enough:
- Officially supports and is running Android 8 or above
- Meets the CPU architecture and RAM requirements of AAPT2 and patcher
- Isn't generally sluggish, but experiences performance issues in our `LazyColumn` pages

**Comment by PalmDevs** [comment]
The first two requirements are met but the third one has not been confirmed. I will test on my other device (with an unfortunately broken screen, though I can use scrcpy to mirror) which has patched apps successfully before and isn't generally sluggish.
