### ISSUE TITLE
bug: <The new patch cannot be imported>

### ISSUE THREAD

**Issue by CarmelUrick** [ReVanced/revanced-manager#1461]
### Bug description

Question: Why can't the patch version be upgraded in the program settings? 
The latest patch version 2.196.0-dev.13 (2023-11-03)
It remains the default on version 2.195 

### Version of ReVanced Manager and version & name of application you tried to patch

Revanced Manager 1.14.2
Patch  2.196.0-dev.13 (2023-11-03)

### Installation type

Non-root

### Device logs

```shell
Patch selected inported
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Ushie** [comment]
Because that's a pre-release, not a release

Think of it as a beta

**Comment by CarmelUrick** [comment]
What should be done to use the pre-release version?!
Because normally it is not imported in the program! So how do we use it?

**Comment by oSumAtrIX** [comment]
You wait until it's released, this is not a support chat
