### ISSUE TITLE
feat: Warn when selecting an unsuggested app version

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1468]
### Feature description

Implement a popup that clarifies that the app they selected does not match the suggested version.
Mention the selected version and the suggested version. 
Mention that they can toggle off this popup and disable forcing selection of the suggested version in the settings
Add an "OK" button, which redirects back to the app selector screen.

### Motivation

People choose apps that ReVanced Manager does not suggest. For that reason, they experience unexpected issues.

### Additional context

Add the switch in the settings: "Require suggested app version". If enabled, do not allow selecting versions of apps that are not suggested using the popup.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by KobeW50** [comment]
How about combining the 'Require suggested app version' toggle with the 'Version compatibility check' toggle? Or at least the 'Version compatibility check' toggle should be grayed out until the 'Require suggested app version' toggle is disabled.

> Mention that they can toggle off this popup and disable forcing selection of the suggested version in the settings

Instead of mentioning that they can toggle off this popup in settings, there can be a checkbox like in this warning:

![SmartSelect_20231105_181949_ReVanced Manager.jpg](https://github.com/ReVanced/revanced-manager/assets/84587632/2f9ce1d4-e4ff-447e-9a89-a7502a159b2d)

**Comment by oSumAtrIX** [comment]
Both settings are separate. You can select versions that are not suggested, but you won't be able to select patches that don't support that version.

**Comment by TheAabedKhan** [comment]
@oSumAtrIX 
>How about combining the 'Require suggested app version' toggle with the 'Version compatibility check' toggle?

https://github.com/ReVanced/revanced-manager/assets/39409020/678e2524-57b7-4858-b8f7-60c38730450b

**Comment by oSumAtrIX** [comment]
@TheAabedKhan This works, but consider the following. The user is asked to enable it. But it does not exist because it's hidden. So now the user has to come back and ask where the toggle is. Show both toggled as both complete separate tasks. Also when the user tries to disable forcing the suggested app version, show a similar warning popup to when the user tries to disable checking for version compatibility

**Comment by TheAabedKhan** [comment]
>The user is asked to enable it. But it does not exist because it's hidden.

It's hidden only when the `Version Compatibility Check` is disabled. This means users will not see any warning dialogs when selecting any non-suggested app.

**Comment by KobeW50** [comment]
@TheAabedKhan 

Suggestion: Place the new toggle above the 'Version compatibility check' toggle because the user will need to disable the new toggle before the 'Version compatibility check' toggle has a use.
