### ISSUE TITLE
feat: <AppGallery>

### ISSUE THREAD

**Issue by Khaliid1** [revanced/revanced-manager#147]
### Type

Other

### Branch

i don't know what it means

### Issue

Not available

### Feature

please make this available on Huawei AppGallery

### Motivation

Huawei welcoming all Devs & it's easy to trust apps in official app stores & that will make it spread even more

**Comment by PandoraHayami** [comment]
💀 Do we want 5 ads every time you build an app?

**Comment by Aunali321** [comment]
Manager is still in alpha state. This version is not intended to be on any storefronts yet.
