### ISSUE TITLE
feat: downloader plugin system

### ISSUE THREAD

**Issue by Axelen123** [ReVanced/revanced-manager#1474]
### Feature description

A plugin system for downloaders should be implemented.

### Motivation

Maintaining plugins for many different APK providers is a burden that would be better dealt with by the community.

### Implementation details

(The arrow labeled null is pointing to "Select downloader")
![image](https://github.com/user-attachments/assets/54b23176-3b0e-459a-9991-fc1dbeb4e298)

Plugins are `jar` files that can be loaded by `DexClassLoader`. They can be imported from local storage or downloaded from a remote source just like patch bundles. Plugins will have a `manifest.json` file which contains information about the plugin such as the name and which class to load. The specified class will implement the [AppDownloader](https://github.com/ReVanced/revanced-manager/blob/compose-dev/app/src/main/java/app/revanced/manager/network/downloader/AppDownloader.kt) interface. A repository class will manage all plugins. Plugin information can be stored using room database if needed.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Please add implementation details to the issue.

**Comment by Axelen123** [comment]
Done
