### ISSUE TITLE
End screen and other bugsbugs: <title>

### ISSUE THREAD

**Issue by Revancedbugreport** [revanced/revanced-manager#148]
### Type

Other

### Branch

YouTube revanced endscreen not working with android 9.0
Improve The patch
And volume swipe up and down not working well
Improve the patch please

### Bug description

YouTube revanced endscreen not working with android 9.0
Improve The patch
And volume swipe up and down not working well
Improve the patch please

### Steps to reproduce

YouTube revanced endscreen not working with android 9.0
Improve The patch
And volume swipe up and down not working well
Improve the patch please

### Relevant log output

```shell
YouTube revanced endscreen not working with android 9.0
Improve The patch
And volume swipe up and down not working well
Improve the patch please
```

### Screenshots or videos

YouTube revanced endscreen not working with android 9.0
Improve The patch
And volume swipe up and down not working well
Improve the patch please

### Solution

YouTube revanced endscreen not working with android 9.0
Improve The patch
And volume swipe up and down not working well
Improve the patch please

### Additional context

YouTube revanced endscreen not working with android 9.0
Improve The patch
And volume swipe up and down not working well
Improve the patch please

**Comment by Aunali321** [comment]
This is a patch issue not a manager issue. Open a an issue [here](https://github.com/revanced/revanced-patches).

**Comment by Revancedbugreport** [comment]
Yes please solve this
