### ISSUE TITLE
feat: legacy

### ISSUE THREAD

**Issue by yonggamer** [ReVanced/revanced-manager#1481]
### Feature description

ability to use old revanced-patches and ReVanced Patcher old Releases

### Motivation

i want to use it

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Ushie** [comment]
This isn't possible because of breaking changes in ReVanced Patcher
