### ISSUE TITLE
[Feature Request] Patch Profiles

### ISSUE THREAD

**Issue by onkoe** [revanced/revanced-manager#149]
### Type

Functionality

### Branch

the one in releases, not sure sorry!

### Issue

Patching new versions requires you to manually remove patches you don't want - every time you patch!

### Feature

Make patch profiles, a feature which sets up a previous save of your patches. This addition would make it so that updates can be patched up with ease.

### Motivation

It saves literally everyone a bit of time. ;)

**Comment by ponces** [comment]
When an update is available, the Dashboard will tell you and a Patch button will be available to apply the same patches that were applied before.
Even if an update is not available, the app appears on the Installed listing of the Dashboard and clicking on the Info button will show an App Info dialog which will have the same repatch option available.
So the feature described already exists.
Closed.
