### ISSUE TITLE
bug: NVIDIA SHIELD controller can't select anything

### ISSUE THREAD

**Issue by GrabbenD** [ReVanced/revanced-manager#1491]
### Bug description

The NVIDIA Shield controller can only go back and move between options in the menu meaning it's not possible to select anything.

To Elaborate: after opening the app, granting full access to storage, it asks to `Download ReVanced Patches` where deselecting `Auto Update` is not possible and neither is clicking on `OK`. You can exit this dialog (with the back button) but you can't select anything in the menu like `Patcher` or `Settings` which makes the app unusable.

**To clarify: only the ENTER button isn't working with the NVIDIA Shield Controller**

### Version of ReVanced Manager and version & name of application you tried to patch

[v1.15.1](https://github.com/ReVanced/revanced-manager/releases/tag/v1.15.1)

### Installation type

Non-root

### Device logs

```shell
Not possible.
```

### Patcher logs

```shell
Not possible.
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by validcube** [comment]
The app isn't really designed to be able to navigate using a controller; I would suggest plugging in your mouse and navigating it using that.

**Comment by GrabbenD** [comment]
> I would suggest plugging in your mouse and navigating it using that.

Definitely the best workaround for ReVanced Manager now but it's VERY flimsy and not responsive
I have to use the controller to go back and keyboard for selecting (enter) and switching between tiles (tab)

Another approach that I found is to use a pre-compiled release like: https://github.com/NoName-exe/revanced-extended/releases (but then you lose out on automatic updates as far as I know).

> The app isn't really designed to be able to navigate using a controller

I suppose this is a feature request then 🙂

**Comment by oSumAtrIX** [comment]
Precompiled binaries of patched apps have nothing to do with ReVanced Manager therefore not an alternative solution.

**Comment by GrabbenD** [comment]
Just realized that you can't actually use ReVanced Manager with the Youtube Android app (it's not detected). Even if you download the mobile APK from [apkmirror.com](https://www.apkmirror.com/apk/google-inc/youtube), it's ~~very difficult~~ impossible to use it with a controller as it's not responsive and the scaling is completely off.

Youtube ReVanced would have to add support for Android TV first to make this bug/feature request worthwhile.

**Comment by Ushie** [comment]
ReVanced doesn't have any patches for YouTube TV, which is an entirely different app (technically it's a website)

You can use other projects like SmartTube
