### ISSUE TITLE
feat: Safety agreement signature

### ISSUE THREAD

**Issue by Angeloxdd** [ReVanced/revanced-manager#1497]
### Feature description

Let users to use his online signature for safety policy in case you will have problems with google.
Example: Im totally agree the safety policy of the revanced manager i was informed in time about his safety policy and i am totally agree with this.

### Motivation

I love revanced manager and i want to remain online forever.
Vanced manager is down let`s do something about revanced to make sure will be remain forever online.
Let users known this a request from a user and this step is not 100% necessary

### Additional context

This is not a issue.
I want to make sure the revanced manager will always remain on the internet.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Not sure what a "Safety agreement signature" is. The app is open source

**Comment by Angeloxdd** [comment]
Is a agreement of safety policy like you know exactly about his safety policy and you are agree with his. This thing can be done online and can be used if google attack revanced manager in any way.

**Comment by oSumAtrIX** [comment]
Safety for?

**Comment by Angeloxdd** [comment]
Good news.  If google cant attack revanced the scope of this post is already done.

**Comment by Angeloxdd** [comment]
Thanks for app. Please provide more ways to donate to this project.

**Comment by oSumAtrIX** [comment]
Np

**Comment by Angeloxdd** [comment]
Can you offer a  quick  transfer method? 
Like in germany:sofort klarna

**Comment by oSumAtrIX** [comment]
Unfortunately not, but thanks for considering supporting anyway

**Comment by Angeloxdd** [comment]
I will donate in the future. When you offer the right option for me (if i
cant with the actual options)

joi, 16 nov. 2023, 10:27 oSumAtrIX ***@***.***> a scris:
