### ISSUE TITLE
enhancement: community project screen.

### ISSUE THREAD

**Issue by Aunali321** [revanced/revanced-manager#15]
There should be a screen in manager that show projects that are built using ReVanced tools by the community. It will be nice as a showcase and show that ReVanced is a community project and show support for other ReVanced based projects. Currently all of the other ReVanced projects are build scripts for building ReVanced but, as time goes on new patches can be developed for other apps. We can then show this projects on the community screen. I am planning to implement this by adding a third a icon on the bottom navigation bar. We use a form that developers can fill and submit to show their projects on the screen. Having a form allows us to check if the projects is malware-free before showing it onto the homescreen.

If you have any questions/suggestions do let me know. Thanks!

**Comment by oSumAtrIX** [comment]
The ReVanced manager is not a store where third parties should appear. At max a separate app such as a store can be created to enrich the ecosystem of ReVanced furthermore.

**Comment by oSumAtrIX** [comment]
What can be added to the manager though, is a patch repo which is planned anyways where the manager can get a list of patch bundles.

**Comment by Aunali321** [comment]
Okay thank you for your suggestions!
