### ISSUE TITLE
bug: Export & import patch selection don't export & import saved patch options

### ISSUE THREAD

**Issue by Kuddus73** [ReVanced/revanced-manager#1509]
### Bug description

The saved patch options don't get exported and imported.
For example, you import the patch selection but your custom theme colour in Theme -> Patch options won't be imported.

### Version of ReVanced Manager and version & name of application you tried to patch

ReVanced Manager v1.16.0

### Installation type

None

### Device logs

```shell
N/A
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by KobeW50** [comment]
https://github.com/ReVanced/revanced-manager/issues/1363
