### ISSUE TITLE
feat: Invert color toggle in the youtube app

### ISSUE THREAD

**Issue by gguman** [ReVanced/revanced-manager#1518]
### Feature description

It would be great to have a toggle in the app to invert colors. I need to use Firefox with Dark Reader every time I want to watch any video before going to bed.

### Motivation

Watch videos at night

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Exists natively in YouTube
