### ISSUE TITLE
bug: <TROJ_GEN.R002V01JE23>

### ISSUE THREAD

**Issue by iammurad** [ReVanced/revanced-manager#1519]
### Bug description

I have checked that app in virustotal and some other websites i have reached that
![Screenshot_20231124_002313_Chrome](https://github.com/ReVanced/revanced-manager/assets/64166663/e7080bb1-3d21-48f2-adb2-2c697bb6f872)
![Screenshot_20231124_002406_Chrome](https://github.com/ReVanced/revanced-manager/assets/64166663/13804ef0-b63a-4241-b424-233e4b6fa177)

### Version of ReVanced Manager and version & name of application you tried to patch

Latest version v1.16.0

### Installation type

Non-root

### Device logs

```shell
I havent installed yet
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [ ] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [ ] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
This is not a bug.

**Comment by iammurad** [comment]
Okay with what prefix i can share that problem?
