### ISSUE TITLE
feat: use HTTP/2 for API requests

### ISSUE THREAD

**Issue by alexandreteles** [revanced/revanced-manager#152]
### Type

Functionality

### Branch

Flutter

### Issue

Currently API requests are made using HTTP/1.1

### Feature

Implement HTTP/2 requests to APIs using [dio_http2_adapter](https://pub.dev/packages/dio_http2_adapter)

### Motivation

Using HTTP/2 would help with at least three things:

1. Adoption of a newer HTTP protocol version;
2. HTTP/2's [shutdown protocol](https://datatracker.ietf.org/doc/html/rfc7540#section-6.8) would help in situations where you have a setup like `client -> load balancer -> app` where you are deploying the app on-demand so you don't get 503s as the load balancer can issue `GOAWAY` frames when necessary so the client knows to try again at a later moment (**super** edge case but whatever);
3. Small performance increase.

**Comment by alexandreteles** [comment]
Another possibility (the ideal solution imho) would be to leverage [cronet.dart](https://github.com/google/cronet.dart) to implement HTTP/3 support so we can have:

1. QUIC - to reduce response times, specially when the API servers are geographically distant from the end-user (which considering Manager's use case is very likely to happen for a large portion of the user base), and;
2. 0-RTT QUICK - to reduce the amount of round trips required to establish a TLS connection with the API server.

HTTP/3 isn't fully supported in all web servers yet, but `cronet` would take care of managing protocol selection depending on which version of the HTTP protocol is available on the API server.

As implementing `dio_http2_adapter` requires very minimal code change, I suppose that could be implemented as a transition effort to bridge the gap until devs are able to properly implement `cronet` in Manager.

https://pub.dev/packages/cronet

**Comment by Aunali321** [comment]
Implemented in https://github.com/revanced/revanced-manager/commit/c0f743df899529cddf027639ed1d6fe2d536d651.
