### ISSUE TITLE
feat: <From the security side it should have been removed TROJ_GEN.R002V01JE23 >

### ISSUE THREAD

**Issue by iammurad** [ReVanced/revanced-manager#1520]
### Feature description

In the latest version i have seen that it contains TROJ_GEN.R002V01JE23 file please solve that
![Screenshot_20231124_002406_Chrome](https://github.com/ReVanced/revanced-manager/assets/64166663/1b29bac2-982c-4964-9055-cf8712e4c206)
![Screenshot_20231124_002313_Chrome](https://github.com/ReVanced/revanced-manager/assets/64166663/33b06dd3-9877-4ee8-bd39-50824bea798b)

### Motivation

Its super application 

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
This is not a feature nor an issue on our end, solve this with virustotal.

**Comment by validcube** [comment]
VirusTotal simply aggregates the result from supported security providers, one or few matching should not be considered a threat, rather a false positive; but you should not still treat it like trusted programs (as with every program ever).

This issue depends on the security providers to remedy this which in case contacting them about false report isn't worth the hassle.
