### ISSUE TITLE
feat: Add "(root)" to "mount" install option and "(non-root)" to "install" option

### ISSUE THREAD

**Issue by JL102** [ReVanced/revanced-manager#1534]
### Feature description

When clicking install after patching, a dialog opens with "install" and "mount". I am proposing that the text be changed to "install (non-root)" and "mount (root)" or "mount (requires root)". 

### Motivation

The "mount" / "insfall" install methods are not quite clear, and I only found out that they are the root/nonroot method after I clicked them. It would be helpful if the text inside the selection dialog included the type of installation so that the user knows what it is before selecting one. 

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Just adding (Root) to the mount option should be enough

**Comment by TheAabedKhan** [comment]
@oSumAtrIX, our new dialog that has an explanation for the methods should be enough to close this issue. What do you think?

**Comment by oSumAtrIX** [comment]
I don't remember the dialog, what does it say?

**Comment by TheAabedKhan** [comment]
I just checked it. It doesn't mention root or non-root terms. So, I think we need a separate PR for this. Or should we edit the strings on the existing PR?

**Comment by ask9027** [comment]
Add option to mout or install(root) patched apk from sdcard.

**Comment by neo-neo1** [comment]
Agreed it needs better wording. I had to Google what it meant the first time I saw the option.

**Comment by oSumAtrIX** [comment]
ReVanced Manager will soon be released as [a full rewrite](https://github.com/ReVanced/revanced-manager/tree/compose-dev). Over time, many feature requests have been made for the current version of ReVanced Manager, but to accelerate the development of the new version of ReVanced Manager, we have to focus on it, which I am closing this issue according to the [contribution guidelines](https://github.com/ReVanced/revanced-manager/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long/ Low priority/ Maintainers un-interested/ Too complex to realize
- Feature planned/ already implemented for the new version of ReVanced Manager
- Already implemented

Regardless, anyone who comes across this feature request can PR it to the current version of ReVanced Manager until the new version is ready. Thanks for your feature request!

**Comment by pritster5** [comment]
Could this be added now?

**Comment by S4adam** [comment]
bump
