### ISSUE TITLE
bug: Cant access a channel via the youtuber name

### ISSUE THREAD

**Issue by githubUser01946** [ReVanced/revanced-manager#1536]
### Bug description

When searching for and then clicking on a profile image it comes with an error 400.

![Screenshot_20231129_005552_YouTube](https://github.com/ReVanced/revanced-manager/assets/117453319/a761869a-6570-427f-868b-4ae736ca44e6)

### Version of ReVanced Manager and version & name of application you tried to patch

Version: 1.17.0
Model: SM-T870
Android Version: 13
Supported Archs: arm64-v8a, armeabi-v7a, armeabi

Youtube 18.45.41

### Installation type

Non-root

### Device logs

```shell
There's no way to get the .log file here
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [ ] The issue is solely related to the ReVanced Manager

**Comment by validcube** [comment]
This issue isn't related to ReVanced Manager

**Comment by githubUser01946** [comment]
Well where do I report the issue with the revanced app? because it was patched with the manager.

**Comment by KobeW50** [comment]
> Well where do I report the issue with the revanced app? because it was patched with the manager.

In the ReVanced Patches repository, since presumably it is a patch causing the issue

https://github.com/ReVanced/revanced-patches
