### ISSUE TITLE
bug: <title>google play protect show alert harful

### ISSUE THREAD

**Issue by dailymobile** [revanced/revanced-manager#154]
### Type

Error at runtime

### Branch

when i install revanced tiktok in revanced manager google play protect show alert harful

### Bug description

when i install revanced tiktok in revanced manager google play protect show alert harful

### Steps to reproduce

google play protect show alert harful

### Relevant log output

```shell
google play protect show alert harful
```

### Screenshots or videos

google play protect show alert harful

### Solution

google play protect show alert harful

### Additional context

google play protect show alert harful

**Comment by Aunali321** [comment]
This is caused by different signatures. everything is safe. This shouldnt happen on rooted installs.
