### ISSUE TITLE
bug: Twitch Ads Showing

### ISSUE THREAD

**Issue by TronziaHQ** [ReVanced/revanced-manager#1549]
### Bug description

Alright. So I’m sorry if I can’t fill out the spaces below and I’m sure we can arrange something if it’s absolutely needed. But basically. The big that I’m experiencing is that when I try to use twitch with the default patches and try to open a stream I get an ad. Which shouldn’t be possible since there’s multiple adblocker patches that the default contains.

To reproduce the bug basically get the recommended version at apkmirror. Patch and choose default ones and install as normal. Log in and view a stream. And boom. Ads when there’s adblockers.

The patches I use is the default ones.

### Version of ReVanced Manager and version & name of application you tried to patch

Revanced Manager Version: [v1.17.1]
Application name: Twitch - the recommended version.

### Installation type

Non-root

### Device logs

```shell
Uhh.. idk if the bug pops up.
```

### Patcher logs

```shell
Uhh.. idk if the bug pops up.
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [ ] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Ads are shown if the proxy is down which we have no control over.

> The issue is solely related to the ReVanced Manager

No

**Comment by TronziaHQ** [comment]
> Ads are shown if the proxy is down which we have no control over.
> 
> > The issue is solely related to the ReVanced Manager
> 
> No

And is it fixable? Plus what proxy can you use? Is it changeable? And will it get fixed?
