### ISSUE TITLE
Where to download the official one Vanced MicroG?

### ISSUE THREAD

**Issue by sousecode** [ReVanced/revanced-manager#1558]
### Feature description

Hello Team. Where to download the official one Vanced MicroG? Sorry for question. I can't find the official app 

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Ushie** [comment]
https://github.com/TeamVanced/VancedMicroG/releases/latest
