### ISSUE TITLE
Feat: Amoled Black theme for the Revanced Manager

### ISSUE THREAD

**Issue by FawazBinSaleem** [ReVanced/revanced-manager#1561]
### Feature description

Would it be possible to add a amoled black theme for the revanced manager app? It would just be like how the youtube amoled black theme is but for the manager.

### Motivation

Amoled black looks cool + saves a bit of battery on old devices

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by validcube** [comment]
:wave: Hi there, while AMOLED theme support for the ReVanced Manager would be awesome, this feature seems unnecessary or not the focus of our priority; we only use the ReVanced Manager to patch an application or two and (hopefully) never to be touched again, which makes it not worth it in my opinion to implement this.

Sorry!
