### ISSUE TITLE
bug: Vanced MicroG not listed in YouTube patches

### ISSUE THREAD

**Issue by rombat** [ReVanced/revanced-manager#1566]
### Bug description

Hi
I've updated to the latest version of Revanced (1.17.3), but I can't find anymore Vanced MicroG support patch for YouTube 

### Version of ReVanced Manager and version & name of application you tried to patch

1.17.3
Youtube

### Installation type

None

### Device logs

```shell
https://pastebin.com/EEDkftmh
```

### Patcher logs

```shell
Can't patch (well, actually i can, but I don't want to patch without MicroG support)
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Ushie** [comment]
It's called GmsCore Support now
