### ISSUE TITLE
feat: 🗒️List the patches

### ISSUE THREAD

**Issue by DAH69** [ReVanced/revanced-manager#1567]
### Feature description

The ability to view the list of available patches without needing to download the APK file.

### Motivation

It's frustrating that you can't see the patches until you download the app.

### Additional context

I suggest holding the app to display a modal with the list of patches.
![ezgif com-video-to-gif-converted](https://github.com/ReVanced/revanced-manager/assets/60827994/a5ed999d-e955-4d67-bd93-fd04f9ce87cf)

### Acknowledgements

- [x] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by treysis** [comment]
I came here to file the same request and luckily it seems I am not the only one :)

Now there's some feature mentioned:
https://github.com/ReVanced/revanced-manager/pull/1409/commits/d55abf5ddacb37dcda48f93a5f86befbb50cf48f

Does it really do what is asked for in this feature request? Looks more like it'll just change the order of apps? Also, I don't see if it would show the list for un-installed apps?

**Comment by oSumAtrIX** [comment]
The commit is for a new version of ReVanced Manager and you can list patches for apps without installing them

**Comment by oSumAtrIX** [comment]
ReVanced Manager will soon be released as [a full rewrite](https://github.com/ReVanced/revanced-manager/tree/compose-dev). Over time, many feature requests have been made for the current version of ReVanced Manager, but to accelerate the development of the new version of ReVanced Manager, we have to focus on it, which I am closing this issue according to the [contribution guidelines](https://github.com/ReVanced/revanced-manager/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long/ Low priority/ Maintainers un-interested/ Too complex to realize
- Feature planned/ already implemented for the new version of ReVanced Manager
- Already implemented

Regardless, anyone who comes across this feature request can PR it to the current version of ReVanced Manager until the new version is ready. Thanks for your feature request!
