### ISSUE TITLE
feat: Detach Youtube from Play Store

### ISSUE THREAD

**Issue by hadiceberg** [revanced/revanced-manager#157]
### Type

Functionality

### Branch

Flutter

### Issue

Google play store might restore original Youtube app, even though "enable auto update" checkbox is cleared. 
It was happening to Youtube Vanced in root mode.

### Feature

Detaching Youtube app from playstore will prevent it from being replaced.
An app called TeMeFI can do that.

### Motivation

It'll be nice to have this feature built into the manager instead of using a 3rd party app.

**Comment by ponces** [comment]
Not Manager's responsibility.
Closed.
