### ISSUE TITLE
PlayStore 

### ISSUE THREAD

**Issue by SMOL25** [ReVanced/revanced-manager#1572]
### Feature description

It's possible to cancel updates from PlayStore for the patched apps?

![Screenshot_20231214-102023](https://github.com/ReVanced/revanced-manager/assets/6607637/0a153011-2023-4e10-8de7-e17db722ed94)
Thanks 

### Motivation

I'm always beeing notified to update patched apps 

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [ ] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Ushie** [comment]
You can use the change package name patch if you want

Or you can ignore/disable playstore notifications

I'm not sure there's anything that can be done about this without root

**Comment by Ushie** [comment]
@Axelen123 @CnC-Robert I think for rooted people, we can allow detaching separately from root install, what do you think?

**Comment by oSumAtrIX** [comment]
Following the UNIX philosophy, affecting Play Store may be problematic. ReVanced Manager has nothing to do with Google apps such as Play Store, which is why we should not attempt to solve a problem that is unrelated to us. The correct way to solve this will require a solution that does not involve implementing a solution in ReVanced Manager. ReVanced itself can provide a solution for it

**Comment by SMOL25** [comment]
> You can use the change package name patch if you want
> 
> Or you can ignore/disable playstore notifications
> 
> I'm not sure there's anything that can be done about this without root

Where can i find the change package name?

**Comment by SMOL25** [comment]
> Following the UNIX philosophy, affecting Play Store may be problematic. ReVanced Manager has nothing to do with Google apps such as Play Store, which is why we should not attempt to solve a problem that is unrelated to us. The correct way to solve this will require a solution that does not involve implementing a solution in ReVanced Manager. ReVanced itself can provide a solution for it for example as a separate tool 

Change names won't solve this?

**Comment by seirdotexe** [comment]
I can confirm that using the "Change package name" works
