### ISSUE TITLE
Venced app not install other device

### ISSUE THREAD

**Issue by tejasnikumbh1432** [ReVanced/revanced-manager#1575]
### Bug description

I will create youtube fenced using venced patch but this this apk share my other device and this is not install plz tell me what is problem this method 

### Version of ReVanced Manager and version & name of application you tried to patch

YouTube_18.45.43.apk

### Installation type

Root

### Device logs

```shell
Not null
```

### Patcher logs

```shell
Not null
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
This is not a support channel.
