### ISSUE TITLE
feat: Mod to disable Google Play Store update notifications for patched apps

### ISSUE THREAD

**Issue by randomcloudswings** [ReVanced/revanced-manager#1577]
### Feature description

A way to disable Google Play Store update notifications for previously patched apps.

### Motivation

Patched apps show on update app list of Play Store.
And when app is updated it shows app update failed and the notification just stays there on the list.
Any way to prevent play Store to ignore the updates of patched apps.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by KobeW50** [comment]
https://github.com/ReVanced/revanced-manager/issues/1572

And also you shouldn't open the same issue in both the manager and patch repository.

**Comment by Ushie** [comment]
Unfortunately this isn't possible unless you're rooted

However, you can use the Change Package Name patch

**Comment by randomcloudswings** [comment]
> Unfortunately this isn't possible unless you're rooted
> 
> However, you can use the Change Package Name patch

Can you please tell me how to change package name patch, it is not available when I'm patching reddit

**Comment by oSumAtrIX** [comment]
This is not a support channel.
