### ISSUE TITLE
Youtube 18.45.43

### ISSUE THREAD

**Issue by erophey7** [ReVanced/revanced-manager#1580]
### Bug description

Selected patches
client spoof
copy video url
custom player overlay opacity
enable debugging
enable tablet layout
hide ads
premium heading
remember video quality
return youtube dislike
sponsorblock
spoof device dimensions
theme
video ads

### Version of ReVanced Manager and version & name of application you tried to patch

ReVanced Manager v1.17.3
Youtube 18.45.43
Patches version 3.1.0
[revanced-manager_logcat_20231220141352314553.log
[patcher.log](https://github.com/ReVanced/revanced-manager/files/13722910/patcher.log)
](https://github.com/ReVanced/revanced-manager/files/13722895/revanced-manager_logcat_20231220141352314553.log)

### Installation type

Root

### Device logs

```shell
revanced-manager_logcat_20231220141352314553.log file
```

### Patcher logs

```shell
Patcher.log file
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by KobeW50** [comment]
Looking at the patch log, it seems that you are patching a split-APK, but you need a full APK.
