### ISSUE TITLE
Give feature to skip video 10 second when playing in hovering mode 

### ISSUE THREAD

**Issue by Nikhilsinha666** [ReVanced/revanced-manager#1581]
### Feature description

Give this patch 

https://github.com/ReVanced/revanced-manager/assets/134316914/f9df1521-fb6d-4dea-8ab1-b9551ba43f85

### Motivation

Give this new patch so that we can watch video vastly watch screen recording for better understanding

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
You can skip any amount of seconds as demonstrated in your recording
