### ISSUE TITLE
new version of YouTube can't patch

### ISSUE THREAD

**Issue by eivelice** [ReVanced/revanced-manager#1583]
### Feature description

hi. i have installed revanced and i can't patch the latest YouTube . 

### Motivation

can't work on the newly formatted phone with latest version of YouTube 

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
This is not a place for support. Move to one of our links on https://revanced.app
