### ISSUE TITLE
bug(patch option): removing existing option will cause assertion fail

### ISSUE THREAD

**Issue by validcube** [ReVanced/revanced-manager#1585]
![image](https://github.com/ReVanced/revanced-manager/assets/93124920/d566b6c5-83c1-4d31-a410-b516056a7575)

**Comment by oSumAtrIX** [comment]
Is this still the case?

**Comment by validcube** [comment]
> Is this still the case?

Not sure, I can't reproduce this problem now on 1.19.0-dev.17 version.
