### ISSUE TITLE
bug(textfield): incorrect background colour set

### ISSUE THREAD

**Issue by validcube** [ReVanced/revanced-manager#1587]
![image](https://github.com/ReVanced/revanced-manager/assets/93124920/a9bd8a1a-e142-4f45-b2dc-53db06c79597)

**Comment by validcube** [comment]
@Ushie 👋 Hello, can you look into this while I'm fixing #1585, should be an easy fix.

**Comment by Ushie** [comment]
Hi, I don't have time, sorry.

**Comment by validcube** [comment]
> Hi, I don't have time, sorry.

Ah, that's unfortunate, don't worry about it, I'll do it once I'm finished.
