### ISSUE TITLE
feat: Handle status codes of uninstall attempts

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#1589]
### Feature description

When there is an issue with installing a patched APK (such as a signature mismatch) and the user uses the option to uninstall the app causing the conflict, the manager should listen and act on the status of that uninstall. If the uninstall fails, it should be suggested to the user to manually uninstall.

### Motivation

There are ways that an uninstall can fail which can easily be fixed by a manual uninstall. One example would be if the conflicting app is in a different user profile (or in something like Samsung Secure Folder / Xiomi Second Space).

### Additional context

Here is a screen recording showing how the feature would act and appear.

https://github.com/ReVanced/revanced-manager/assets/84587632/77f870bd-f2db-4eca-8403-bb0d7f65e29e

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by TheAabedKhan** [comment]
What's the difference between manual uninstallation and the uninstallation dialog that appears from the manager?

**Comment by KobeW50** [comment]
> What's the difference between manual uninstallation and the uninstallation dialog that appears from the manager? 

If the conflicting app is in another profile or in something such as Samsung secure folder, the manager will not be able to uninstall it. The user will need to go to that profile/enter secure folder and uninstall it manually.

**Comment by oSumAtrIX** [comment]
Similarly apps that are installed in the system image, can only be disabled, although android should be reporting a successful uninstallation

**Comment by oSumAtrIX** [comment]
ReVanced Manager will soon be released as [a full rewrite](https://github.com/ReVanced/revanced-manager/tree/compose-dev). Over time, many feature requests have been made for the current version of ReVanced Manager, but to accelerate the development of the new version of ReVanced Manager, we have to focus on it, which I am closing this issue according to the [contribution guidelines](https://github.com/ReVanced/revanced-manager/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long/ Low priority/ Maintainers un-interested/ Too complex to realize
- Feature planned/ already implemented for the new version of ReVanced Manager
- Already implemented

Regardless, anyone who comes across this feature request can PR it to the current version of ReVanced Manager until the new version is ready. Thanks for your feature request!
