### ISSUE TITLE
bug: Remove all animations when the *Android* option to do so is enabled

### ISSUE THREAD

**Issue by stevenxxiu** [ReVanced/revanced-manager#1591]
### Feature description

I have in *Settings* -> `Accessibility` -> `Display` `Colour and motion` -> `Remove animations` turned on. However this app still has animations. The animations I can see include:

- A screen transition.
- A bounce when scrolling quickly to the bottom of the screen.

### Motivation

Some people like animations. Some people don't. The user's setting in *Android* should be respected.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by validcube** [comment]
👋 Hello, unfortunately, this request is out of our control, Flutter does not allow us to limit or disable the animation for most of its built-in components unless we create our own custom components that can disable animation based on System Information, which isn't simply worth our time.

Sorry!

**Comment by oSumAtrIX** [comment]
It's also not really a important feature, if you don't want animations, disable them. This is an app to patch apps.

**Comment by Ushie** [comment]
This issue is about ReVanced Manager animations not being disabled when system-wide animations are

**Comment by oSumAtrIX** [comment]
Then a bug report should be opened

**Comment by oSumAtrIX** [comment]
ReVanced Manager will soon be released as [a full rewrite](https://github.com/ReVanced/revanced-manager/tree/compose-dev). Over time, many feature requests have been made for the current version of ReVanced Manager, but to accelerate the development of the new version of ReVanced Manager, we have to focus on it, which I am closing this issue according to the [contribution guidelines](https://github.com/ReVanced/revanced-manager/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long/ Low priority/ Maintainers un-interested/ Too complex to realize
- Feature planned/ already implemented for the new version of ReVanced Manager
- Already implemented

Regardless, anyone who comes across this feature request can PR it to the current version of ReVanced Manager until the new version is ready. Thanks for your feature request!
