### ISSUE TITLE
bug: KernelSU compatibility

### ISSUE THREAD

**Issue by nebrassy** [ReVanced/revanced-manager#1592]
### Bug description

Kernelsu compatibility was recently broken by this commit here

https://github.com/ReVanced/revanced-manager/commit/c23275f2fe2f00f6afc1a52e2b15cdb2d4b2a16b#diff-3a871b8563714fef81752772ddd7d536b29a27637010bcb169a168518bf6cae2R155

### Version of ReVanced Manager and version & name of application you tried to patch

1.18
Youtube Music

### Installation type

Root

### Device logs

```shell
https://haste.aicp-rom.com/ekosizelom.coffeescript
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by La-Hire** [comment]
mod the sh and it works on ksu, maybe some help?

#!/system/bin/sh
#MAGISKTMP="$(magisk --path)" || MAGISKTMP=/sbin
#MIRROR="$MAGISKTMP/.magisk/mirror"

until [ "$(getprop sys.boot_completed)" = 1 ]; do sleep 3; done
until [ -d "/sdcard/Android" ]; do sleep 1; done

# Unmount any existing installation to prevent multiple unnecessary mounts.
grep com.google.android.youtube /proc/mounts | while read -r line; do echo $line | cut -d " " -f 2 | sed "s/apk.*/apk/" | xargs -r umount -l; done

base_path=/data/adb/revanced/com.google.android.youtube/base.apk
stock_path=$(pm path com.google.android.youtube | grep base | sed "s/package://g" )

chown system:system $base_path
chcon u:object_r:apk_data_file:s0  $base_path
mount -o bind $MIRROR$base_path $stock_path

# Kill the app to force it to restart the mounted APK in case it is already running
am force-stop com.google.android.youtube

**Comment by oSumAtrIX** [comment]
This is already fixed in dev
