### ISSUE TITLE
bug: Manager does not finish loading on fresh install

### ISSUE THREAD

**Issue by kozmaz87** [ReVanced/revanced-manager#1593]
### Bug description

Loading....
![Screenshot_20231225_091243_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/4070837/96d96e30-08f3-4a2c-b1de-8bf39ac5c397)
![Screenshot_20231225_091445_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/4070837/2763fe1a-9afd-4179-8eb1-7aff83a139bb)

### Version of ReVanced Manager and version & name of application you tried to patch

1.18.0

### Installation type

None

### Device logs

```shell
Attached as it is too long for github text field
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by kozmaz87** [comment]
[revanced-manager_logcat_20231225091838706919.log](https://github.com/ReVanced/revanced-manager/files/13765334/revanced-manager_logcat_20231225091838706919.log)

**Comment by Ushie** [comment]
Do you have AdGuard enabled?

**Comment by cyberfrog77** [comment]
same behavior for me too

**Comment by oSumAtrIX** [comment]
This looks like some network blocker, if not reopen
