### ISSUE TITLE
'remove-screen-capture-restriction' patch missing for Spotify

### ISSUE THREAD

**Issue by pflanzenandi** [ReVanced/revanced-manager#1594]
When trying to patch the newest spotify.apk from storage, I can only chose between 2 patches.
`remove-screen-capture-restriction` is missing completely. 

![Screenshot_20231225-114014](https://github.com/ReVanced/revanced-manager/assets/60046516/68aaaecc-b6f1-4cf8-91bf-0cbe148d2a34)

### Version of ReVanced Manager and version & name of application you tried to patch

1.18.0

### Installation type

None

### Device logs

```shell
...
```

### Patcher logs

```shell
...
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Ushie** [comment]
Click on the Selected patches card and select it
