### ISSUE TITLE
bug: cannot install YouTube revanced

### ISSUE THREAD

**Issue by alanjoseph17** [ReVanced/revanced-manager#1598]
### Bug description

Cannot install YouTube revanced. I have already uninstalled all updates and disabled the disabled YouTube app. Revanced manager shows the warning existing app conflicts with installation.
![Uploading Screenshot_20231227-141445.png…]()

### Version of ReVanced Manager and version & name of application you tried to patch

Revanced manager ver 1.18
YouTube ver 18.45.43

### Installation type

Non-root

### Device logs

```shell
.
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Ushie** [comment]
Please post the patcher log

**Comment by sneakyjoeru** [comment]
I think enabling GMS and custom branding helped. I had the same issue when had to update the app.
