### ISSUE TITLE
bug: Youtube Music crashes if "ReVanced" is selected under the "GmsCore support" patch options

### ISSUE THREAD

**Issue by slavi22** [ReVanced/revanced-manager#1614]
### Bug description

If I change the GmsCore Vendor from Vanced (com.mgoogle) to ReVanced (app.revanced) before patching, after installing and opening the app, it instantly crashes. If I keep the default vendor (Vanced - com.mgoogle) it opens without a problem.

### Version of ReVanced Manager and version & name of application you tried to patch

ReVanced Manager v1.18.0
App - Youtube Music v6.29.57 

### Installation type

Non-root

### Device logs

```shell
N/A
```

### Patcher logs

```shell
- Device Info
ReVanced Manager: 1.18.0
Model: SM-S908B
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: app.revanced.android.apps.youtube.music v6.29.57 (Suggested: Any)
Patches version: v3.2.0
Patches added: Default
Patches removed: None
Default patch options changed: GmsCore support [GmsCore Vendor: app.revanced]

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 10 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Signing APK
Patched APK
Installing patched app
Installed
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
You are missing [GMS](https://github.com/ReVanced/GmsCore) from the vendor `app.revanced`.

**Comment by slavi22** [comment]
When I try to install Youtube Revanced using the revanced vendor it works without any issues though ?
