### ISSUE TITLE
Improve "split APK" dialog

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#1617]
### Feature description

![SmartSelect_20240103_002110_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/84587632/01de5ad3-7453-4164-90fc-c171126c4479)

The above dialog can be shortened and simplified. Here is a draft:

```This application is a split APK and can only be patched with root permissions at the moment. Obtain a full APK and select it from storage or install it and select it regularly.```

### Motivation

The dialog is long/wordy, and the 3rd sentence is especially difficult to understand:

"you can still install the application by selecting its APK files from your device's storage..."

It should be saying how to select it for patching, not how to install it. 

Also almost zero non-root users (including myself) know how to select an installed app's APK files from storage. It should instruct the user to "acquire" a full APK which can be installed and then selected or selected from storage.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by otahir-21** [comment]
i changed long text to shortened and simplified.

"featureNotAvailableText": "This application is a split APK and can only be patched with root permissions at the moment. Obtain a full APK and select it from storage or install it and select it regularly."
