### ISSUE TITLE
non skippable ads on youtube videos 

### ISSUE THREAD

**Issue by sd535682** [revanced/revanced-manager#162]
While playing some videos getting Non Skippable one or two ads at the starting. Using Revanced Manager latest.

**Comment by KiGamji** [comment]
its not a manager issue. its a patches issue. and its a known issue, but devs have no clue what causes it. google does an a/b testing atm, so thats why.

**Comment by Aunali321** [comment]
Open the issue on revanced-patches.

**Comment by sd535682** [comment]
> its not a manager issue. its patches issue. and its a known issue, but devs have no clue what causes it. google does an a/b testing atm, so thats why.

using old revanced manager can fix the issue?

**Comment by KiGamji** [comment]
> its not a manager issue. its patches issue.
> using old revanced manager can fix the issue?
