### ISSUE TITLE
feat: add seperate download options for non root users

### ISSUE THREAD

**Issue by RA341** [ReVanced/revanced-manager#1620]
### Feature description

There can be a seperate tab that can query verified repositories like https://github.com/NoName-exe/revanced-extended and get direct download options for apps the repos provide.

### Motivation

This will make it easier for non root users to manage and update their apps.

### Additional context

I know #722 mentions something similar but it is unclear if it is proposing same thing. 
I can work on this if this is not planned.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [ ] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
This is a repository for ReVanced Manager and not prepared apps

**Comment by Ushie** [comment]
This is covered by #722
