### ISSUE TITLE
feat: Ability to retry downloading an update

### ISSUE THREAD

**Issue by Axelen123** [ReVanced/revanced-manager#1621]
### Feature description

There should be a retry button if the download fails or the user cancels.

### Motivation

It makes sense to have it and it is not very hard to implement.
The "new manager update available" popup takes you directly to the update page, but clicking on back will take you back to the dashboard. This is problematic if the download is aborted because now you have to go through the settings page to find it again.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Ushie** [comment]
Isn't this solved by the planned design anyways? a NotificationCard or a TopAppBar action will be placed when there's an update available

**Comment by Axelen123** [comment]
> Isn't this solved by the planned design anyways? a NotificationCard or a TopAppBar action will be placed when there's an update available

Which planned design? I am not familiar with it.

**Comment by Ushie** [comment]
Apparently it isn't in the Figma, but essentially the way I envision it is basically what I described above

**Comment by Axelen123** [comment]
You could open an issue and/or implement it yourself. An action would solve the problem of updates being buried in the settings.
