### ISSUE TITLE
feat: local Patch bundle and Integrations for flutter

### ISSUE THREAD

**Issue by yonggamer** [ReVanced/revanced-manager#1622]
### Feature description

local Patch bundle and Integrations for flutter

### Motivation

it is nice to have it

### Additional context

[https://github.com/ReVanced/revanced-manager/assets/79272171/9e588297-7283-4358-b3cd-4cea3acacd84](https://github.com/ReVanced/revanced-manager/assets/79272171/9e588297-7283-4358-b3cd-4cea3acacd84)

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Ushie** [comment]
ReVanced Manager Flutter won't have major feature additions, as it is going to be succeeded by ReVanced Manager Compose, which is what's in the screen recording you sent
