### ISSUE TITLE
feat: <support iFunny>

### ISSUE THREAD

**Issue by Elyahu41** [ReVanced/revanced-manager#1631]
### Feature description

Hello! Thank you for all the work you guys do! I benefited a lot from your patches, and I just found out the whole range of patches that are available. Really phenomenal work 👏!

I was wondering if it would be possible to add iFunny to the list of supported applications that can be patched. Their ads are the main issue for me, even if some of them are funny.

### Motivation

If you use the app iFunny, you will see two ads between almost every post, an ad banner on the bottom of the app that is always visible, and ads in the comments. This is the only social media app I use other than reddit and I believe it would be an amazing addition to the project. 

### Additional context

Not sure if this is possible, but there are many non ad pages between posts by iFunny as well. It would be amazing if you could remove those as well for seamless experience. 

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Ushie** [comment]
Hi 👋 

This repository is specific to ReVanced **Manager** only, it is separate from ReVanced Patches

You need to open an issue in the [ReVanced Patches repository](https://github.com/revanced/revanced-patches) instead
