### ISSUE TITLE
bug: <Problem package>

### ISSUE THREAD

**Issue by OXEDAN1337** [ReVanced/revanced-manager#1632]
### Bug description

I try to install last release and old version apk to nav android and didn't work for my K2001N with 9.1v Android, 1g ram, quadcore-t3 .  

How can I fix this?

### Version of ReVanced Manager and version & name of application you tried to patch

1.18.0 and 1.14.1

### Installation type

Non-root

### Device logs

```shell
There was a problem parasing the package.
```

### Acknowledgements

- [ ] This request is not a duplicate of an existing issue.
- [ ] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.
- [ ] The issue is solely related to the ReVanced Manager

**Comment by OXEDAN1337** [comment]
However, I found a compatible version that works with vanced+ and microG+ (jst try alternative vers) but when i'm logged in microG it crashed youtube vanced+ . It's works when i'm not logged in microG.. Why? How i can solve this bug?

**Comment by OXEDAN1337** [comment]
However, I found a compatible version that works with vanced+ and microG+ (jst try alternative vers) but when i'm logged in microG it crashed youtube vanced+ . It's works when i'm not logged in microG.. Why? How i can solve this bug?

**Comment by oSumAtrIX** [comment]
This is not a support channel, move to one of our social media on https://revanced.app
