### ISSUE TITLE
bug: <title> Revanced manager crash when pressing storage o s10e and note 10+ exynos variant 

### ISSUE THREAD

**Issue by Bluelytning16** [ReVanced/revanced-manager#1634]
### Bug description

Hello. When i try to patch The latest Youtube version and pressing storage for selecting The apk, The manager crashes without any message on s10e and note 10 + exynos. I waited for a fix, but even with latest version IT crashes. 

### Version of ReVanced Manager and version & name of application you tried to patch

Manager 1.18
Youtube latest compatibile 18.45.43

### Installation type

Non-root

### Device logs

```shell
Even here IT crashes so i can't share
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [ ] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.
- [x] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Please open a proper issue with  error logs using logcat and a proper title
