### ISSUE TITLE
feat: Show a dialog when an update is available 

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1637]
### Feature description

A dialogue should be shown when an update is available.

### Motivation

It has been observed that many people fail to see when an update is available because only a button is being enabled. A dialogue would solve this problem 

### Additional context

The dialogue should only show up when auto updates are enabled. The dialogue should contain a checkmark to not show again, which would disable the autoupdates.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by TheAabedKhan** [comment]
"Auto update" can be a separate feature that will not inform users about an update, instead it will download the update automatically in the background and show a dialog to users that a new update is ready to be installed.

**Comment by GKid94** [comment]
Good idea

**Comment by GKid94** [comment]
And a auto update apps option

**Comment by validcube** [comment]
🥞 This issue have been resolved by the release of v1.19.0
