### ISSUE TITLE
bug: tiktok app crashes and youtube opens with a blank screen

### ISSUE THREAD

**Issue by LoveyGoo** [revanced/revanced-manager#164]
### Type

Error while running the manager

### Branch

0.0.7 release 

### Bug description

title says it all

### Steps to reproduce

patch the app and open it

### Relevant log output

```shell
idk how to do it on my phone
```

**Comment by Aunali321** [comment]
You are using split apk. uninstall both tiktok and yt. download them from apk mirror. Make sure its full apk and not a bundle. For yt recommended version is 17.33.42.

**Comment by LoveyGoo** [comment]
welp for yt i cant even uninstall it for tiktok i just use the official app from the playstore to patch it and then uninstall it i dont really see how downloading the app from a apk mirror would change it

**Comment by Aunali321** [comment]
Manager can't patch apps from play store. Apps downloaded from playstore are splits which can't be with current patcher. You can avoid this by uninstalling tiktok and downloading a full apk from apkmirror. For yt, uninstall updates and download full apk from apkmirror (17.33.42 version.  130mb+).

**Comment by LoveyGoo** [comment]
cool ill try that

**Comment by LoveyGoo** [comment]
now on tiktok i cant login 🤔

**Comment by LoveyGoo** [comment]
well with facebook that is

**Comment by Delphox** [comment]
> well with facebook that is

Do you have the Facebook app installed? I dunno if its the same case here, but with modded Spotify app you can't login with Facebook if the FB app is installed, but it works if its not installed/disabled, then you can install it again after being logged in. You could try that.

**Comment by LoveyGoo** [comment]
ill try that thanks

**Comment by LoveyGoo** [comment]
hmm seems like i cant disable it ill try uninstalling it

**Comment by LoveyGoo** [comment]
yup worked thanks both of u for the help <3
