### ISSUE TITLE
bug(dev branch): User is able to prematurely exit out of the patching screen 

### ISSUE THREAD

**Issue by validcube** [ReVanced/revanced-manager#1645]
The change is likely the cause of the PopScope Migration

RVMF version: acb1e2434b28efca852297e0a0a8ffce155e67e4

**Comment by validcube** [comment]
https://github.com/ReVanced/revanced-manager/assets/93124920/2b3c01b8-09e7-4aae-a42f-78091a498acd

**Comment by Ushie** [comment]
Given this issue existed only in the dev branch, it makes sense to be closed as completed
