### ISSUE TITLE
bug: revanced-manager-vv1.19.0-dev.1.apk

### ISSUE THREAD

**Issue by yonggamer** [ReVanced/revanced-manager#1646]
### Bug description

revanced-manager-vv1.19.0-dev.1.apk has version code 1900001
revanced-manager-v1.18.0.apk has 101800000
can not update

### Version of ReVanced Manager and version & name of application you tried to patch

revanced-manager-vv1.19.0-dev.1.apk

### Installation type

None

### Device logs

```shell
N/A
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by validcube** [comment]
🥞 Fixed in latest dev branch, new release is out.
