### ISSUE TITLE
Internal download of versions of apps 

### ISSUE THREAD

**Issue by speedlorenzo12** [ReVanced/revanced-manager#1648]
### Feature description

choose the version of the application directly from within the app so as not to have to go to apkmirror to choose it as termux

### Motivation

the termux function of showing the version log internally in the app is very convenient, simple and fast since you don't even need the browser to load the page and you can directly download

### Acknowledgements

- [ ] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-manager/issues/722
