### ISSUE TITLE
bug: <TikTok crashes all the time>

### ISSUE THREAD

**Issue by thanasistrisp** [revanced/revanced-manager#165]
### Type

Error at runtime

### Branch

Main

### Bug description

I installed app from playstore, pathed it through manager with install as root, update through playstore a new version, crashes, uninstall and after this time each time it crashes when I install from playstore or apkmirror (older version) without having patched it again. It is likely it does not completely unintall when I request it!

### Steps to reproduce

.

### Relevant log output

```shell
.
```

**Comment by ponces** [comment]
Use unpatch or uninstall option on Manager (Dashboard -> Installed -> Info -> Unpatch or Uninstall).
Then repatch again.

**Comment by ponces** [comment]
Latest version has this fixed.

**Comment by Aunali321** [comment]
Try with 0.0.13

**Comment by ponces** [comment]
Repatch and then try to uninstall.
Or simply delete /data/local/tmp/revanced-manager and reboot.
