### ISSUE TITLE
bug: 3 issues on Manager update Section

### ISSUE THREAD

**Issue by 0xNaimulHasanTaky** [ReVanced/revanced-manager#1651]
### Bug description

Bug no 1: Using the newest Pre-release version v1.19.0-dev.2 but ReVanced Manager showing last update was about 1 month ago. Note that the latest release (not Pre-release) was 1 month ago.

![IMG_20240123_201000](https://github.com/ReVanced/revanced-manager/assets/147870580/0f15dea2-81e5-4d78-a18e-f6dbc0207d86)

Bug no 2: Installed the newest Pre-release version v1.19.0-dev.2 but update button is still active.

![IMG_20240123_202306](https://github.com/ReVanced/revanced-manager/assets/147870580/95b31edf-b990-420c-943a-fae534834a6c)

Bug no 3: On the manager update section it's showing the newest Pre-release version v1.19.0-dev.2 but when click on update it's downloading the Latest version v1.18.0 instead of the Pre-release version v1.19.0-dev.2

### Version of ReVanced Manager and version & name of application you tried to patch

v1.19.0-dev.2

### Installation type

None

### Device logs

```shell
N/A
```

### Patcher logs

```shell
N/A
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Dev.2 is a developer release and not eligible for updates in ReVanced Manager

**Comment by validcube** [comment]
Please open all of your aforementioned issues in a separate issue.

As for Issue #\1 that's intended, we only provide the last update information for the latest stable release.
