### ISSUE TITLE
bug: ReVanced keeps deleting my custom Magisk hooks

### ISSUE THREAD

**Issue by stevenxxiu** [ReVanced/revanced-manager#1656]
### Bug description

My custom *Magisk* hooks in `/data/adb/post-fs-data.d/` keep getting deleted.

The code responsible is in <https://github.com/ReVanced/revanced-manager/blob/v1.18.0/lib/services/root_api.dart#L103>.

Not all *Magisk* hooks are owned by *ReVanced*. It shouldn't be touching this.

### Version of ReVanced Manager and version & name of application you tried to patch

v1.18.0

### Installation type

Root

### Device logs

```shell
N/A
```

### Patcher logs

```shell
N/A
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
ReVanced Manager had once put post FS scripts named after the patched app file in that directory. Since those are orphaned files, there's no way for the app to know what file to delete as it can't know which of the files belongs to ReVanced. Any suggestions?

**Comment by stevenxxiu** [comment]
Thanks for the reply.

If it's the case where the app can't be sure which files to delete, then I think the next best option is to inform the user, and let him/her delete it manually.

Straight up nuking all of them, including files it shouldn't be touching, isn't a great idea. If I didn't have backups of those files I'd have lost them.

**Comment by oSumAtrIX** [comment]
The removal for orphaned files is done on app launch. If we would ask the user, any time you add something in that folder ReVanced Manager would have to treat it as an orphaned file and show a popup on app launch. Since the scripts been there for some time it can be removed.

**Comment by stevenxxiu** [comment]
You could treat this as a one-off issue. Ask the user once, and assume it's all been settled when they press ok. Then don't ask about this again.
