### ISSUE TITLE
Using latest suggested YouTube app doesn't apply patched

### ISSUE THREAD

**Issue by rdlr88** [ReVanced/revanced-manager#1660]
### Bug description

Before updating to the latest suggested YouTube app everything work fine but when using the YouTube version 19.03.35 and applying patches the app won't open and crashes, when I check which patches have been applied,  it says zero but during the process of installing those patches it doesn't show any error or nothing 

### Version of ReVanced Manager and version & name of application you tried to patch

Revanced manager version 1.18.0
YouTube version19.03.35

### Installation type

Root

### Device logs

```shell
- Device Info
ReVanced Manager: 1.18.0
Model: KB2005
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

-
```

### Patcher logs

```shell
Patch Info
App: com.google.android.youtube v19.03.35 (Suggested: v19.03.35)
Patches version: v4.0.1
Patches added: Default
Patches removed: External downloads, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, Spoof app version, Theme, Spoof device dimensions, Client spoof, Remember video quality, Playback speed, Restore old video quality menu, GmsCore support
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 49 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Signing APK
Patched APK
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Not a ReVanced Manager issue.
