### ISSUE TITLE
feat: Add option to compile only arm64-v8a

### ISSUE THREAD

**Issue by MattSolo451** [ReVanced/revanced-manager#1666]
### Feature description

It would be useful to add an option to compile only arm64-v8a as it was in Revanced Manager.
![Screenshot_20240129-210253_1](https://github.com/ReVanced/revanced-manager/assets/70535762/1d761c31-2c53-48d3-8b24-d74e0f0106f5)

### Motivation

This would certainly allow the creation of an apk that makes better use of the performance of the target device.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
ReVanced Manager is not a tool to modify apps like this. It's an app to patch apps using ReVanced. If you want to remove libraries, you can do so manually
