### ISSUE TITLE
feat: changing Revanced Manager Icon

### ISSUE THREAD

**Issue by Spaceshiprace** [ReVanced/revanced-manager#1669]
### Feature description

Can the manager's icon replaced with this icon because I think this is the icon it suppose to have 
![revanced-manager-logo](https://github.com/ReVanced/revanced-manager/assets/156727749/287be6c9-6fab-4bae-b1a7-07bbb0326ece)

### Motivation

Because ReVanced and the manager looks the same application it makes no difference between them

### Additional context

its just a silly request

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
The branding guidelines suggest the current logo as the main one, it would be arbitrary to just chose a blue one https://github.com/ReVanced/revanced-branding

**Comment by oSumAtrIX** [comment]
Wherever you got it from

**Comment by Ushie** [comment]
> Ah Ok, but from where that blue icon cames ?

To match the bluish theme of the website, it's permitted per the guidelines, but the app icon of the app doesn't need to match the theme of the app, because it isn't displayed inside the app

**Comment by Spaceshiprace** [comment]
its from the official revanced site ?

**Comment by oSumAtrIX** [comment]
The official website is https://revanced.app.

**Comment by Ushie** [comment]
> its from the official revanced site ?

Yes, it's from the official revanced site

The official revanced site, has a blue theme, so the diamond in the ReVanced icon is shown as blue, but everywhere else it's what the ReVanced Manager icon is

**Comment by oSumAtrIX** [comment]
No, the icon sent is not from the official website but a counterfeit.

**Comment by Ushie** [comment]
It is from the website, it is used in the navbar

**Comment by oSumAtrIX** [comment]
The nav bar has the shape, not the icon in question that OP sent. The icon OP sent is from a counterfeit website as they refer to as the official one

**Comment by Ushie** [comment]
The shape originates from our website, thiedparties using it are irrelevant, it is still a valid question as to why that is the case

**Comment by oSumAtrIX** [comment]
The question was if the icon was from the official website, which it isn't like I answered, whereas the counterfeit website, where it got the shape from there. I don't know what you mean by "as to why [the shape originating from our website] is the case"
