### ISSUE TITLE
bug: App info buttons not aligned properly after 0.0.8 update

### ISSUE THREAD

**Issue by SpookieGames** [revanced/revanced-manager#167]
### Type

Cosmetic

### Branch

Flutter

### Bug description

I just opened the info tab

### Steps to reproduce

1. Open info tab about an app
2. See misaligned buttons

### Relevant log output

```shell
No log output
```

### Screenshots or videos

![Screenshot_2022-09-17-17-48-17-925_app revanced manager flutter](https://user-images.githubusercontent.com/41782443/190865490-807c51a0-b16b-4edb-acc1-b4b6e1918ace.jpg)

**Comment by SadLinusGuy0** [comment]
Same here

**Comment by ponces** [comment]
Fixed on https://github.com/revanced/revanced-manager/commit/83ad7605c4d16a6916242623d48481eec4cd4075.
Closed.
