### ISSUE TITLE
bug: Error in Patching Youtube 

### ISSUE THREAD

**Issue by the-netspider** [ReVanced/revanced-manager#1677]
### Bug description

Patching youtube root mode always fails. No matter whatever patches I select. Device and Patching Logs are shared below.

**Steps to reproduce :**

Check Allow changing patch selection. Then select any of the patch in YouTube and Run the patcher. It fails

My Phone : Lg V60
Android ver. 11

### Version of ReVanced Manager and version & name of application you tried to patch

V 1.18.0

### Installation type

None

### Device logs

```shell
--------- beginning of crash
02-01 00:50:06.136 11468 11468 E AndroidRuntime: FATAL EXCEPTION: main
02-01 00:50:06.136 11468 11468 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 11468
02-01 00:50:06.136 11468 11468 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.put(java.lang.Object, java.lang.Object)' on a null object reference
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4515)
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4547)
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2084)
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7887)
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
02-01 00:50:06.136 11468 11468 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.put(java.lang.Object, java.lang.Object)' on a null object reference
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5115)
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4502)
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	... 11 more
02-01 00:50:06.136 11468 11468 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.put(java.lang.Object, java.lang.Object)' on a null object reference
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:142)
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:813)
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:432)
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:853)
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:884)
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8329)
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5108)
02-01 00:50:06.136 11468 11468 E AndroidRuntime: 	... 12 more
--------- beginning of system
02-04 13:50:26.828 20602 20602 I Timeline: Timeline: Activity_idle id: ActivityRecord{6f6cd6a token=android.os.BinderProxy@ee7753d {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}} time:170149272
02-04 13:50:26.828 20602 20602 I Timeline: Timeline: Activity_idle id: ActivityRecord{6f6cd6a token=android.os.BinderProxy@ee7753d {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}} time:170149272
02-04 13:50:32.165 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:50:32.212 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:50:32.836 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:50:32.907 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:50:35.124 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:50:35.236 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:50:36.446 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:50:36.467 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:50:38.447 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:50:38.534 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:50:40.001 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:50:40.122 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:50:42.572 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:50:42.635 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:50:43.823 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:50:43.876 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:50:44.373 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:50:44.422 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:50:44.878 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:50:44.925 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:50:49.851 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:50:49.929 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:50:58.071 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:50:58.274 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:50:59.749 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:51:00.093 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:51:08.559 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:51:08.631 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:51:12.174 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:51:12.221 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:51:13.481 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:51:14.469 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:51:15.108 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:51:15.138 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:51:16.052 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:51:16.115 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:51:56.805 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:51:56.967 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:51:57.648 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:51:57.868 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:51:59.087 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:52:00.986 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:52:09.104 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:52:09.572 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:52:28.612 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:52:29.493 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:52:32.153 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:52:32.744 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:52:37.362 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:52:41.232 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:52:42.371 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:52:42.465 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:52:43.341 20602 20602 I ViewRootImpl: ViewRoot's KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=170285782, downTime=170285782, deviceId=-1, source=0x101, displayId=0 } to DecorView@57e2581[MainActivity]
02-04 13:52:43.361 20602 20602 I ViewRootImpl: ViewRoot's KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=170285803, downTime=170285782, deviceId=-1, source=0x101, displayId=0 } to DecorView@57e2581[MainActivity]
02-04 13:52:44.873 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:52:44.936 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
02-04 13:52:47.684 20602 20602 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
02-04 13:52:47.755 20602 20602 I ViewRootImpl
```

### Patcher logs

```shell
- Device Info
ReVanced Manager: 1.18.0
Model: LM-V600
Android version: 11
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v19.03.35 (Suggested: v19.03.35)
Patches version: v4.0.2
Patches added: Default
Patches removed: Hide ads, Copy video URL, Remove viewer discretion dialog, External downloads, Disable precise seeking gesture, Seekbar tapping, Swipe controls, Disable auto captions, Hide video action buttons, Hide autoplay button, Hide captions button, Hide cast button, Navigation buttons, Hide player buttons, Hide album cards, Hide breaking news shelf, Comments, Hide crowdfunding box, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Hide 'Load more' button, Player flyout menu, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Disable player popup panels, Custom player overlay opacity, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, SponsorBlock, Spoof app version, Change start page, Disable resuming Shorts on startup, Enable tablet layout, Tablet mini player, Theme, Alternative thumbnails, Announcements, Always repeat, Enable debugging, Spoof device dimensions, Client spoof, Bypass URL redirects, Minimized playback, Remove tracking query parameter, Disable zoom haptics, HDR auto brightness, Remember video quality, Playback speed, Restore old video quality menu, GmsCore support, Open links externally
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 1 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~PiIGXV90_xKxJSYNWTHJsw==/app.revanced.manager.flutter-L_4g6daUOviT6kXVbbwKuA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNBOPL/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1544019392, --version-name, 19.03.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL7276137881360894824.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNBOPL/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNBOPL/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNBOPL/cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:128)
	at app.revanced.patcher.Patcher.get(Patcher.kt:265)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:371)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~PiIGXV90_xKxJSYNWTHJsw==/app.revanced.manager.flutter-L_4g6daUOviT6kXVbbwKuA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNBOPL/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1544019392, --version-name, 19.03.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL7276137881360894824.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNBOPL/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNBOPL/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-VNBOPL/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
	... 7 more
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Review the warnings you got when changing the settings in ReVanced Manager and reset them to your default configuration

**Comment by the-netspider** [comment]
Here are the Logs after default configuration ..


:

- Device Info
ReVanced Manager: 1.18.0
Model: LM-V600
Android version: 11
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v19.03.35 (Suggested: v19.03.35)
Patches version: v4.0.2
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 61 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~PiIGXV90_xKxJSYNWTHJsw==/app.revanced.manager.flutter-L_4g6daUOviT6kXVbbwKuA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WSADEK/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1544019392, --version-name, 19.03.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4385795832747142308.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WSADEK/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WSADEK/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WSADEK/cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:128)
	at app.revanced.patcher.Patcher.get(Patcher.kt:265)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:371)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~PiIGXV90_xKxJSYNWTHJsw==/app.revanced.manager.flutter-L_4g6daUOviT6kXVbbwKuA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WSADEK/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1544019392, --version-name, 19.03.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4385795832747142308.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WSADEK/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WSADEK/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WSADEK/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
	... 7 more

**Comment by oSumAtrIX** [comment]
Patch a full APK

**Comment by the-netspider** [comment]
> Patch a full APK

I think same result in Patching Full YouTube APK too

:

- Device Info
ReVanced Manager: 1.18.0
Model: LM-V600
Android version: 11
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v19.03.35 (Suggested: v19.03.35)
Patches version: v4.0.2
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 61 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~PiIGXV90_xKxJSYNWTHJsw==/app.revanced.manager.flutter-L_4g6daUOviT6kXVbbwKuA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DJDXES/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1544019392, --version-name, 19.03.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL3337130344560923687.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DJDXES/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DJDXES/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DJDXES/cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:128)
	at app.revanced.patcher.Patcher.get(Patcher.kt:265)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:371)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~PiIGXV90_xKxJSYNWTHJsw==/app.revanced.manager.flutter-L_4g6daUOviT6kXVbbwKuA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DJDXES/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1544019392, --version-name, 19.03.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL3337130344560923687.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DJDXES/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DJDXES/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DJDXES/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
	... 7 more

**Comment by oSumAtrIX** [comment]
Follow this 
![image](https://github.com/ReVanced/revanced-manager/assets/13122796/52653a04-1073-4e56-abe6-bba9e6f9ea2f)

**Comment by the-netspider** [comment]
Reinstalled everything, Stopped Auto Update, Detached from Playstore Now It worked smoothly.

Thanks for the advice.

May be there were errors because YouTube automatically updates and it was not supporting any patch in the Updated version.

**Comment by Fell** [comment]
I had a similar issue when using the "manual download" feature of the Aurora Store. Installing YouTube from the .apk file and patching that worked.
