### ISSUE TITLE
where is official source for vanced microg? 

### ISSUE THREAD

**Issue by picarica** [ReVanced/revanced-manager#1679]
### Feature description

So i got new phone i want to installed revamced youtube and YouTube music but last time i got my vanced microg from some Reddit thread, is there official source for this micro g fork? It's not using normal official one right? 

### Motivation

It's hard to track where is the official source for micro g

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by picarica** [comment]
I know where to download micro g but as i read on forums cancelled it's using some special version of micro g i wondered if it's available from somewhere
Searching vanced micro g leads to malware

**Comment by picarica** [comment]
Thank you very much

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ReVanced/revanced-manager/issues/1679#issuecomment-1927273483

@Ushie, that's archived. Does [`ReVanced/GmsCore`](https://github.com/ReVanced/GmsCore) replace it?

**Comment by oSumAtrIX** [comment]
Yes

**Comment by beedell-roke** [comment]
> https://github.com/ReVanced/revanced-manager/issues/1679#issuecomment-2868988731

@oSumAtrIX, in which case, how does one report a bug with it? I ask because its `/issues` is inaccessible - the sole template transfers me to GitHub Discussions. As an example:

<blockquote>

~~~YAML
FATAL EXCEPTION: McsHandler
Process: com.mgoogle.android.gms:persistent, PID: 11028
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.NetworkInfo.getTypeName()' on a null object reference
    at org.microg.gms.gcm.McsService.connect(Unknown Source:46)
    at org.microg.gms.gcm.McsService.handleMessage(Unknown Source:279)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at org.microg.gms.gcm.McsService$HandlerThread.run(Unknown Source:85)
~~~

</blockquote>

**Comment by oSumAtrIX** [comment]
I am not sure when but it seems GitHub has pushed an update disallowing anyone from using an empty template. I can't find the setting to enable it

**Comment by beedell-roke** [comment]
> https://github.com/ReVanced/revanced-manager/issues/1679#issuecomment-2869009159

@oSumAtrIX, if you manage to, just notify me and I'll report the bug. Thanks for getting on top of it. x
