### ISSUE TITLE
Manager don't work on fire tv stick

### ISSUE THREAD

**Issue by GeAd23** [ReVanced/revanced-manager#1682]
### Bug description

I can select buttons but I can't install any App on the fire tv stick 4K. 
If I click one button in the Manager App nothing happens. I want to install the SmartTube App on the TV-Stick. 
Please fix this problem. 

### Version of ReVanced Manager and version & name of application you tried to patch

1.9.11
SmartTube TV App

### Installation type

Non-root

### Device logs

```shell
Can't click on this button.
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
ReVanced Manager is not designed to run on TV Android and instead conventional Android systems.
