### ISSUE TITLE
feat: YT PC-like customizability for Subtitles on the Android YT App.

### ISSUE THREAD

**Issue by Claymeister** [ReVanced/revanced-manager#1683]
### Feature description

![image](https://github.com/ReVanced/revanced-manager/assets/97406383/254fe78f-5c36-40bb-a1d1-369e3320b4a8)
![image](https://github.com/ReVanced/revanced-manager/assets/97406383/cc2e2cce-ddb5-42e8-a6aa-aedcc707d62e)
YT PC has numerous options for subtitle customization, and I for one would love to have them on Android. The mobile subtitles suck, they obstruct more video, and are unchangable. Just look!
![image](https://github.com/ReVanced/revanced-manager/assets/97406383/6e3c8bb3-b94d-47b6-98d9-360e29294d4e)
![Screenshot_20240206-012839](https://github.com/ReVanced/revanced-manager/assets/97406383/40040a7c-f350-4463-8958-77b239f08711)

Until the official app fixes that, would be nice if someone managed to port over some of the PC code to the Revanced app. If it's possible of course.
If it's entirely on Youtube to add, or it's already a package on Revanced that i haven't noticed, sorry for making the post. And if it is the latter, gimmie a pointer!

### Motivation

It screws with visibility, the overall video watching experience, especially on a channel like Primitive Technology, where the only explainations are in the YT subtitles.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [ ] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
#subtitle
