### ISSUE TITLE
Add option to use system font

### ISSUE THREAD

**Issue by 0-BlackSpectrum-0** [ReVanced/revanced-manager#1689]
### Feature description

As the title suggests I'd like to have my system font that my phone is using, either use that or add an option under theme to select and use system font.

### Motivation

Consistency!

### Acknowledgements

- [ ] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
#502
