### ISSUE TITLE
[bug] revanced manager crashes when I try patching an app

### ISSUE THREAD

**Issue by forwardslashh** [revanced/revanced-manager#169]
On the latest version 0.0.8, revanced manager crashes when I click patch and wait for a few seconds when reddit and when I try to patch YouTube it loads and loads and when it's almost done it just crashes but he notification that says _revanced manager is patching_ remains
EDIT:now the same happens to yt when I try patching yt

**Comment by SadLinusGuy0** [comment]
For me it crashes when I try patch Reddit from storage

**Comment by forwardslashh** [comment]
> For me it crashes when I try patch Reddit from storage

I'm sorry if I sound stupid but what does that mean?

**Comment by Alprnn357** [comment]
@forwardslashh send logs

**Comment by LambdaSoft** [comment]
Same for me with TikTok when I try to update the patch (only with this last 0.0.8 version).
https://paste.evolution-x.org/gYrl2Y

**Comment by Aunali321** [comment]
0.0.8 is broken. please use 0.0.7 or wait for next build.
