### ISSUE TITLE
feat: Remove unused library

### ISSUE THREAD

**Issue by CobalTitan** [ReVanced/revanced-manager#1696]
### Feature description

Add an option to remove libs not necessary to compile only arm64-v8a architecture

### Motivation

Arm64-v8a it now only used to new chipsets and reduced apk size.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
This is not the managers responsibility. Either supply an APK that doesn't have them, remove the libs manually, or use a patch that strips them
