### ISSUE TITLE
feat: Add Note for rooted user only support magisk official and / or kernelSU

### ISSUE THREAD

**Issue by cyberboh** [ReVanced/revanced-manager#1697]
### Feature description

My humble request to devs, that is to add notes only support [magisk official by topjohnwu](https://github.com/topjohnwu/Magisk) and/or [KernelSU](https://github.com/tiann/KernelSU)

### Motivation

There are so many magisk forks e.g Magisk Alpha, Magisk Delta, Magisk Kitsune, etc etc.
1. Magisk Alpha is developed by top contributor in magisk official repo. They are LSPosed devs (yujincheng08, canyie, vvb2060). Mostly the code is just for testing purpose before pushed into magisk official. I can not find its source code. Only download link available `https://install.appcenter.ms/users/vvb2060/apps/magisk/distribution_groups/public`
And if you see this commit https://github.com/LSPosed/Magisk/commits/c8c75a52610721ebc95c8c7fb76245b16698373b its in private repo
2. Magisk Delta and Magisk Kitsune is developed by Husky, Vietnamese Guy. 
Source code located in this repo `https://github.com/KitsuneMagisk/Magisk/tree/kitsune`
Download link `https://github.com/HuskyDG/magisk-files/releases`
See the differences from official magisk, they are huge. 

### Additional context

Imagine random peeps using random rooting methods thats far away from magisk official. If some broken, they will blame us, and we don't know is caused by using unofficial root method or using any blahblah root method.
So, we can reduce bug reports (for root) from random peeps.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-manager/issues/1592 This is a bug that has been already fixed in dev

**Comment by oSumAtrIX** [comment]
those versions are supported

**Comment by validcube** [comment]
> those versions are supported

This issue is about adding a warning dialog (or note) to the ReVanced Manager app when its detect that user is using 3rd-party Magisk or KernelSU client which might have different implementation.

**Comment by oSumAtrIX** [comment]
The hypothetical scenario that a fork apart from the current one emerges that is so different that it does not work for us is very unlikely and not worth the trouble, especially when the current forks are known to work.

**Comment by Ushie** [comment]
Those forks do not work because of the bug mentioned by osumatrix, which has since been fixed in dev
