### ISSUE TITLE
small bug: White stripe at the bottom

### ISSUE THREAD

**Issue by MarcaDian** [ReVanced/revanced-manager#1698]
### Bug description

On last dev 14.
If enabled Dark theme there's a white stripe in the bottom. If enable again Dark theme this stripe being dark, but after restart again White.

![Screenshot_2024-02-20-23-32-24-891-edit_app revanced manager flutter](https://github.com/ReVanced/revanced-manager/assets/152095496/01abdacd-ad1c-472b-b369-301559af9de6)

### Version of ReVanced Manager and version & name of application you tried to patch

1.19.0 dev.14

### Installation type

Non-root

### Device logs

```shell
None
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Does it happen on stable builds

**Comment by Ushie** [comment]
No, it's introduced in the dev branch

**Comment by MarcaDian** [comment]
This wasn’t there on version dev.7, then I updated to dev.14 and it’s already there
stable builds don't have this bug

**Comment by oSumAtrIX** [comment]
Please find the exact version then that introduced it

**Comment by MarcaDian** [comment]
i find that this bug appear if i enabled `Material You`, 
`dev.8` is a version where it appeared.

![Screenshot_2024-02-22-17-49-58-599_app revanced manager flutter](https://github.com/ReVanced/revanced-manager/assets/152095496/6dadb3b7-dd03-4593-9547-92d0d821ffd7)
![Screenshot_2024-02-22-17-51-11-989_app revanced manager flutter](https://github.com/ReVanced/revanced-manager/assets/152095496/c315a84e-165a-4d4f-ba23-bf93fa7d952b)

**Comment by Ushie** [comment]
> i find that this bug appear if i enabled `Material You`

Yep, to be more specific, anything that re-applies the theme fixes it, so essentially just switching from system to dark or anything else

That means the issue is in the default state of the theme, specifically

**Comment by BenjaminHalko** [comment]
@oSumAtrIX Yeah it also appears on my end, I'll see what I can do to fix it.

**Comment by BenjaminHalko** [comment]
It looks like it started appearing on commit [f82c439](https://github.com/ReVanced/revanced-manager/commit/f82c439b26b894d03deff9bd7e0547519d7cc40f).
