### ISSUE TITLE
Setup translations with crowdin

### ISSUE THREAD

**Issue by koukichi7010** [revanced/revanced-manager#17]
You must first create a crowdin translation project before submitting the **open source projects** request form:
https://crowdin.com/createproject

Open Source Project request form:
https://crowdin.com/page/open-source-project-setup-request

• Keeping Track

**Comment by koukichi7010** [comment]
No need to reply to this, this is for keeping track as Osu stated in the Discord Server👀

**Comment by PatrykMis** [comment]
Should be crowdin, why not Weblate?

**Comment by oSumAtrIX** [comment]
Why Weblate over Crowdin?

**Comment by koukichi7010** [comment]
Weblate might have more control over translations, but crowdin makes it easy to navigate compared to weblate's ui...also Crowdin gives Open Source projects free of charge @PatrykMis

**Comment by PatrykMis** [comment]
Weblate is also more accessible to people using screen readers.

But if translations by pull request will be accepted in parallel it should not be a huge problem.

**Comment by ponces** [comment]
Ok, so...
Crowdin or Weblate?

**Comment by PalmDevs** [comment]
Crowdin imo

**Comment by xerta555** [comment]
> Ok, so... Crowdin or Weblate?

I suggest Crowdin personally.

**Comment by alpha4041** [comment]
> Ok, so... Crowdin or Weblate?

Crowdin is better imo

**Comment by ViktorVoloshko** [comment]
I think that Crowdin will be better too.
