### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by Fertanima** [revanced/revanced-manager#170]
why the manager won't support version below android 8?
YouTube supports android 6 version, YouTube cannot be installed on android 6 device without Revanced Manager

**Comment by Canny1913** [comment]
Newer Youtube versions only support Android ≥8 now.

**Comment by Fertanima** [comment]
Why did they do that?

**Comment by pietryszak** [comment]
> Why did they do that?

Because android 7 is 6 years old, and can do. That's why.

**Comment by alan-ford** [comment]
@pietryszak 
I hope you are being sarcastic.

**Comment by alan-ford** [comment]
@Canny1913 
Is the recommended YouTube version no longer 17.33.42? It is also compatible with Android 6.0.

**Comment by Canny1913** [comment]
> @Canny1913 Is the recommended YouTube version no longer 17.33.42? It is also compatible with Android 6.0.

That version is still supported.

**Comment by pietryszak** [comment]
> @pietryszak I hope you are being sarcastic.

The newest version of YT is only android 8 and newer, so it's obvious that manager support android 8+.

**Comment by Canny1913** [comment]
> > @pietryszak I hope you are being sarcastic.
> 
> The newest version of YT is only android 8 and newer, so it's obvious that manager support android 8+.

No. ReVanced is not limited to Youtube.

**Comment by pietryszak** [comment]
> > > @pietryszak I hope you are being sarcastic.
> > 
> > 
> > The newest version of YT is only android 8 and newer, so it's obvious that manager support android 8+.
> 
> No. ReVanced is not limited to Youtube.

I know, but it's redicullus to expect support 6 years old systems. 6 years old system is a security unsecure, even google not support it, so...
