### ISSUE TITLE
feat: Support shizuku app

### ISSUE THREAD

**Issue by alr86** [ReVanced/revanced-manager#1700]
### Feature description

Use shizuku app to patch apks apps instead of root access

### Motivation

.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Root is needed for mounts.

**Comment by validcube** [comment]
Note: Support for Shizuku has been reopened. However under ReVanced Manager Compose

See Discussion@https://discord.com/channels/952946952348270622/952987428786941952/1416040749891584090

**Comment by validcube** [comment]
Note: Support for Shizuku has been reopened. However under ReVanced Manager Compose

See Discussion@https://discord.com/channels/952946952348270622/952987428786941952/1416040749891584090
