### ISSUE TITLE
bug: Can't enter "null"  in patch options

### ISSUE THREAD

**Issue by Shane9248** [ReVanced/revanced-manager#1704]
### Bug description

In the patch 'Custom Branding' there should be an option to not change the icon, just like you can choose not to touch the app name 
![1000024100](https://github.com/ReVanced/revanced-manager/assets/83491863/3f0edfa2-8a1b-4b97-a9b7-9734ae9874b3)

The only options are "ReVanced logo" and "Custom value" 
![1000024101](https://github.com/ReVanced/revanced-manager/assets/83491863/e41f7561-a23d-4465-90af-869a655c38fc)

### Version of ReVanced Manager and version & name of application you tried to patch

Version - 1.18.0
Application - YouTube Revanced

### Installation type

None

### Device logs

```shell
.
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [ ] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Shane9248** [comment]
https://github.com/ReVanced/revanced-patches/issues/2762#issuecomment-1963009921 as mentioned here i am now told ro redirect to here

**Comment by Ushie** [comment]
Doesn't deleting the option count as null?

@oSumAtrIX @Shane9248 
![image](https://github.com/ReVanced/revanced-manager/assets/79272171/64c2b0b9-f023-4c43-95c2-96bb149b33e4)

**Comment by oSumAtrIX** [comment]
Deleting resets the option value to default.

**Comment by Ushie** [comment]
That sounds weird, if the default is a non-null value then the option by default is added in ReVanced Manager, removing it then should make it null

**Comment by oSumAtrIX** [comment]
This is not the case. If you haven't configured any options, the options are not added in this view. Instead you have to click on plus to add them and change them. The reason for this is to cover this scenaro:

An option value is null by default. You want to change it, so you add it. Now you want to set it back to null. As you can not input "null", you click on the icon to delete it which resets the value to null. This issue refers to the problem, when the option accepts null, but isn't null by default, so you have no way to set it to null.

To improve UX some changes can be made:

**Comment by Ushie** [comment]
You're overcomplicating it, the issue here is that "Delete" and "Reset" are being used in a single button, simply adding a Reset button is enough

**Comment by oSumAtrIX** [comment]
I'd like an elaboration on what is being complicated here. From what I am seeing, my suggestion simplifies the usage.

> simply adding a Reset button is enough

No, as the current delete functionality is to reset. By adding a reset button, you try repurposing this as a way to set it to null, whereas the dropdown menu is the correct purpose for abstract inputs such as paths to folders files, or null in this case.

**Comment by Ushie** [comment]
Null is just the computer way of saying nothing, a Delete button makes something nothing.

The issue here is that the delete button isn't a delete button, it's a reset button, a proper delete button should be added to fix the weird UX and impossibility of manually setting null, without introducing an odd interface to the user.

This is an end-user app, explain to me the difference between "Set to null" and "Delete", there's no difference, so why complicate it and make it less recognizable? what the hell is "null"?

**Comment by oSumAtrIX** [comment]
> Null is just the computer way of saying nothing, a Delete button makes something nothing.

Adding a delete button to the option does not imply setting the option value to null. It implies deleting an option. This semantic is weird. You cant "delete options" you can set the option value to null.

The correct place therefor to add a "Delete" semantic is therefor next to the input label. By your approach we would have to add an "Chose folder" button to the top right of the option card as well, which does not make sense for the same reason as adding a delete button. Instead, the "Delete" functionality, which in reality is a "Set to null" functionality should be added next to the input label, as it is not used to delete the option but to set the option value to null. As there's no space for buttons next to the input label, it is added to the dropdown just like any functionality that is dedicated to setting option values, such as setting the option value to a path, or in this case setting the option value to null

The only issue I see with a "Set to null" submenu item is that an empty string is indistinguishable from a null input.
This could be solved by when pressing on "Set to null", the input value shows a placeholder that could, for example, say "Null value". Once you type something in it, or delete everything in the textbox, it'll be an empty textbox without that placeholder. Here is a mockup:

<img width="410" alt="image" src="https://github.com/ReVanced/revanced-manager/assets/13122796/551d7b38-8153-41de-adf0-a65139ae252a">

**Comment by oSumAtrIX** [comment]
"Delete option" is a semantical problem. This already disqualifies it as a solution. Null being unclear is a problem, that does not justify using a semantically incorrect problem instead.

Scenario:

You want to change the icon but not the label.
You set label to "null" and the patch wont change it. As you identified, "Null" is unclear to an enduser.

But with delete option you completely break the semantic:

You want to change the icon but not the label.
You "delete the icon option?" What does that mean, why is an option "deleteable?" How would the user understand that "Deleting" the option label means not applying a label? Here you don't only have a clearness issue, but also the semantic issue

**Comment by oSumAtrIX** [comment]
I think the label could say "Value set to null" is better than my previous example. Little more clearer

**Comment by Shane9248** [comment]
what is the status of this ?

**Comment by Shane9248** [comment]
@oSumAtrIX nothing on this so far ?

**Comment by Indranil012** [comment]
> @oSumAtrIX nothing on this so far ?

Set as custom value and make the value field empty for now as an workaround.

**Comment by Shane9248** [comment]
@TheAabedKhan are u aware of this ? as u have been assigned to it
