### ISSUE TITLE
bug: <title>Revanced Does not save history.

### ISSUE THREAD

**Issue by MasterFerrary** [ReVanced/revanced-manager#1711]
### Bug description

YouTube Revanced suddenly stopped showing videos I watched in the past.  It only shows shorts in the past.  I deleted the application and microG and reinstalled them.  I restarted my phone but it didn't help.  Please help me

### Version of ReVanced Manager and version & name of application you tried to patch

Version: 19.04.37  (Last version)

### Installation type

Non-root

### Device logs

```shell
"custom_playback_speeds": "0.25\n0.5\n1.0\n1.5\n2.0\n2.5\n3.0",
"hide_shorts_button": false,
"hide_shorts_navigation_bar": false,
"start_page": "MAIN"
```

### Patcher logs

```shell
"custom_playback_speeds": "0.25\n0.5\n1.0\n1.5\n2.0\n2.5\n3.0",
"hide_shorts_button": false,
"hide_shorts_navigation_bar": false,
"start_page": "MAIN"
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by MasterFerrary** [comment]
I also cleared the history.  And I turned off the save history option and turned it on again, but it didn't work.  Only videos I watched on YouTube shorts appear in the past.

**Comment by Ushie** [comment]
This repository is regarding ReVanced Manager only
