### ISSUE TITLE
bug: <Youtube Watch History dosen't sync>

### ISSUE THREAD

**Issue by KillerGER87** [ReVanced/revanced-manager#1712]
### Bug description

Youtube Watch History dosen't sync since monday. No Adblocker Installed
Playstore Version does function correcty
### Version of ReVanced Manager and version & name of application you tried to patch

All Lates Version and Patches even did a reinstall 

### Installation type

Non-root

### Device logs

```shell
-------- beginning of system
02-29 11:41:29.070  7253  7253 D ViewRootImpl: update {(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION wanim=0x1030001
02-29 11:41:29.070  7253  7253 D ViewRootImpl:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
02-29 11:41:29.070  7253  7253 D ViewRootImpl:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
02-29 11:41:29.070  7253  7253 D ViewRootImpl:   bhv=DEFAULT
02-29 11:41:29.070  7253  7253 D ViewRootImpl:   fitSides=} by setView
--------- beginning of main
02-29 11:41:40.394  7253  7266 W manager.flutter: Cleared Reference was only reachable from finalizer (only reported once)
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Joshuapavan** [comment]
I raised the same bug, but was closed.🙄

**Comment by Ushie** [comment]
This repository is only about ReVanced Manager

**Comment by Ushie** [comment]
It seems like it has already been raised here https://github.com/ReVanced/revanced-patches/issues/2779

**Comment by KillerGER87** [comment]
thank you
