### ISSUE TITLE
bug: Save history not being saved on the YouTube Revanced Extended app

### ISSUE THREAD

**Issue by luigiymario2** [ReVanced/revanced-manager#1713]
### Bug description

I am using the YouTube Revanced Extended app and whenever I watch a YouTube video it's not saving on my watched history and it's messing up my recommends as well because it doesn't register videos I fully watched as watched... I believe this bug is also affecting other users as well.

### Version of ReVanced Manager and version & name of application you tried to patch

Revanced Manager version: 1.9.11
MicroG: 0.3.0.234415
YouTube Revanced Extended: 19.02.39

### Installation type

Non-root

### Device logs

```shell
I don't see settings on the ReVanced Manager app
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
This is ReVanced
