### ISSUE TITLE
The `es-AR` locale does not have the country name

### ISSUE THREAD

**Issue by agatemosu** [ReVanced/revanced-manager#1714]
### Bug description

The `es-AR` locale does not have the country name, I don't think that should be the main Spanish, in Crowdin, `es-ES` is the language that does not have the country name.

### Version of ReVanced Manager and version & name of application you tried to patch

1.19.0-dev.17

### Installation type

None

### Device logs

```shell
.
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
<img width="234" alt="image" src="https://github.com/ReVanced/revanced-manager/assets/13122796/e24bc114-62ba-4101-9c65-27d5a65563f8">

Looks to be present.

**Comment by oSumAtrIX** [comment]
I think this is an issue with the underlying lib

**Comment by Ushie** [comment]
Yes, we can PR upstream, maintainer is quite responsive, just make sure before PRing

**Comment by validcube** [comment]
🗿 Quick status update here, relevant change has been purposed to upstream and hopefully we can get it merged just in time for the next release of ReVanced Manager Flutter.
* https://github.com/lamnhan066/language_code/pull/3

**Comment by validcube** [comment]
🥞 Relevant change has been merged to upstream and we have updated the version constraint for it. Consider checking out changes at ReVanced Manager v1.19.4-dev.2 (or v1.19.4-next) once it's published.
