### ISSUE TITLE
bug: 0.0.8 and 0.0.9 crashed when patch clicked

### ISSUE THREAD

**Issue by pietryszak** [revanced/revanced-manager#172]
### Type

Error while running the manager

### Branch

Flutter

### Bug description

App crash after clicking patch button

### Steps to reproduce

1) Download 0.0.8 apk
2) Choose YT app 17.33.42
3) Choose all patches, except debbuging
4) Click patch
5) App Crash

### Relevant log output

```shell
https://pastebin.com/uVHec5hp
```

### Additional context

Android 12
Samsung S21 FE (SM-G990B/DS)

**Comment by Aunali321** [comment]
0.0.8 is broken. please try 0.0.9 and 0.0.7 and check if any of them work.

**Comment by pietryszak** [comment]
> 0.0.8 is broken. please try 0.0.9 and 0.0.7 and check if any of them work.

0.0.7 work. I try 0.0.9

**Comment by karmakarmeghdip** [comment]
Same here, not only does it not work for YT but also for Twitter and Reddit

**Comment by pietryszak** [comment]
I check once again. 0.0.7 working fine, 0.0.8 and 0.0.9 crash.

**Comment by Vesek** [comment]
Just tried this, the same happens to me as well. The last frame of the app has "Unpacking input apk" as the last line.

Android 13 on an Poco X3

**Comment by SpookieGames** [comment]
Same issue

**Comment by devlocalhost** [comment]
https://user-images.githubusercontent.com/56504654/190875088-1a5e2b6c-932d-4dfb-9365-0e3f76db1dfd.mp4

Facing this issue on 0.0.9 too, Xiaomi mi a3, Google pixel 5 qpr1 beta 1 GSI

And as Vesek said, it crashes at "Unpacking input APK"
![Screenshot_20220917-232032](https://user-images.githubusercontent.com/56504654/190875185-9cfa51ff-b543-4e51-b22a-7df7a7df88a5.png)

**Comment by pietryszak** [comment]
So we can confirm that Manager crash when patch YT app, and Reddit

**Comment by devlocalhost** [comment]
> So we can confirm that Manager crash when patch YT app, and Reddit

It crashes with any app actually, not only YouTube and reddit. One person also included crash log (#176)

**Comment by steve51184** [comment]
0.0.9 didn't fix this had to roll back to 0.0.7 otherwise it doesn't work on .8 or .9

**Comment by ponces** [comment]
Thank you for logs and info provided.
Fixed on https://github.com/revanced/revanced-manager/commit/bb96c3ed63cff2ecd298bafdd1f84d462e6f190a.

**Comment by rapdodge** [comment]
Same on YT Music

```
java.util.NoSuchElementException: Array is empty.
	at kotlin.collections.ArraysKt___ArraysKt.first(_Arrays.kt:1012)
	at app.revanced.manager.flutter.utils.AaptKt.resolveAapt(Aapt.kt:12)
	at app.revanced.manager.flutter.utils.AaptKt.access$resolveAapt(Aapt.kt:1)
	at app.revanced.manager.flutter.utils.Aapt.binary(Aapt.kt:8)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-18(MainActivity.kt:143)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$-gNqYPzZb-BzxULVb2BYsca-Uls(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda12.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:920)
```

Video:
https://user-images.githubusercontent.com/33513626/190882644-f31ff6a7-4cbd-4bb0-a727-f0c3d55f77d8.mp4
