### ISSUE TITLE
bug: revanced-manager crash when opend

### ISSUE THREAD

**Issue by yonggamer** [ReVanced/revanced-manager#1720]
### Bug description

1. Download [revanced-manager-v1.19.0-dev.20.apk](https://github.com/ReVanced/revanced-manager/releases/download/v1.19.0-dev.20/revanced-manager-v1.19.0-dev.20.apk)
2. install revanced-manager-v1.19.0-dev.20.apk
3. press on revanced-manager app icon
4. crash

### Version of ReVanced Manager and version & name of application you tried to patch

revanced-manager v1.19.0-dev.20 

### Installation type

None

### Device logs

```shell
.
```

### Acknowledgements

- [x] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Petteroes** [comment]
Same here, crash.
