### ISSUE TITLE
bug: Language change breaks UI

### ISSUE THREAD

**Issue by n1cKz1** [ReVanced/revanced-manager#1730]
### Bug description

I made a new issue since the last one I commented in regarding this was for some reason closed. The screenshot is from v1.19.0-dev.17 but the issue is still present in v1.19.1. Changing the app language to Greek results in this:

![Screenshot_2024-03-02-15-58-28-524_app revanced manager flutter](https://github.com/ReVanced/revanced-manager/assets/107653639/b0f89f98-17b8-4b92-9ac8-7f513c834840)

### Version of ReVanced Manager and version & name of app you are patching

v1.19.1

### Installation method

None

### ReVanced Manager logs

```shell
.
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
How do you suggest to fix this?

**Comment by n1cKz1** [comment]
Not sure. Perhaps adding a new line in the button's string if a specific character count is reached and thus scaling the button vertically in the process, instead of horizontally, which seems to be the cause of this issue. Of course this could very well not look ideal, hell I'm not sure if it would even work or break something else in the process.

If nothing can be done about this in the current design then worst case scenario I could try to translate this string a bit differently, although the current translator did so perfectly, and is also a proofreader I believe so who knows if a new translation would even go through. Greek is admittedly a tough language to translate to from English.
