### ISSUE TITLE
bug: Old language remains in settings tab after switching language

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#1731]
### Bug description

When you change the language, all but one of the strings in the settings tab will remain in the old language until you switch to the patcher or dashboard tab (and then return to the settings tab).

**Steps to reproduce**

1. Set the language of the Manager to English.
2. Fully close and restart the Manager.
3. Set the language to any language other than English and press "OK".

(You will now be in the settings tab but only the widget for language selection will be in the newly selected language.)

5. Switch to the patcher or dashboard tab.
6. Switch back to the settings tab.

(Now all of the widgets with strings in the new language will be in the new language.)

https://github.com/ReVanced/revanced-manager/assets/84587632/2791ee73-c6c2-46dc-8691-e0abc1d9672c

### Version of ReVanced Manager and version & name of app you are patching

1.19.1

### Installation method

None

### ReVanced Manager logs

[revanced-manager_logcat_20240304220102205740.log.txt](https://github.com/ReVanced/revanced-manager/files/14489860/revanced-manager_logcat_20240304220102205740.log.txt)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by validcube** [comment]
We would only need to reload the page every time the language changed, this should be a very easy fix. (I HOPE)

I have noticed this issue since the feature was introduced, but I forgot to file it. *Whoops, too late for this now.*

**Comment by KobeW50** [comment]
Manager logs: [revanced-manager_logcat_20240304220102205740.log.txt](https://github.com/ReVanced/revanced-manager/files/14489851/revanced-manager_logcat_20240304220102205740.log.txt)
