### ISSUE TITLE
bug (Alternative sources): Toast says "Restart the app to apply changes" when no changes were made

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#1733]
### Bug description

When you enable/disable Alternative sources, or select "OK" in the alternative sources menu, or select "OK" in the API URL menu, the manager gives a toast saying that you should restart the app to apply changes, even if no changes were made.

A simple check between the before and after states can make it so the manager only gives this toast if the new state of the sources is different than the previous state.

Here is a demonstration of the issue. In this screen recording, the sources are always set to the default.

https://github.com/ReVanced/revanced-manager/assets/84587632/bbe97b77-cd5c-4b5b-9e59-bd35375ce4c6

### Version of ReVanced Manager and version & name of app you are patching

1.19.1

### Installation method

None

### ReVanced Manager logs

```shell
I'll provide if needed. Doubt it is necessary :)
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
Enabling already is a change.

**Comment by validcube** [comment]
Can reproduce, we can add a simple if check to the code.

**Comment by oSumAtrIX** [comment]
> When you press "OK" in the alternative sources and API URL menus it should not give this toast if nothing was changed.

It clears the cache and forces redownloading from the API URL. If you want to exit the screen without doing so, press cancel. Ok is "Save". Demonstration of expected behaviour:

https://github.com/ReVanced/revanced-manager/assets/13122796/5cfd9aec-879f-446a-b122-e6c6990ac0fa

**Comment by KobeW50** [comment]
> It clears the cache and forces redownloading from the API URL.

Just run the `if` statement before deciding to clear the cache.

 > If you want to exit the screen without doing so, press cancel. 

I understand this, but a toast is big notice telling the user what to do. It should not be misleading. It's just bad UX 🤷🏻‍♂️

> Demonstration of expected behaviour:

Saving files is different because the file's metadata is usually changed when you save it. Like the timestamp of when the file was last edited.

Anyways, regardless of technicalities, it will always be bad UX in the case of alternative sources and API URL.

**Comment by oSumAtrIX** [comment]
> I understand this, but a toast is big notice telling the user what to do. It should not be misleading. It's just bad UX 🤷🏻‍♂️

The notice is placed correctly. Pressing OK saves whatever is inputted. That action clears cache and so on which requires a restart to apply the change.

**Comment by oSumAtrIX** [comment]
> Saving files is different because the file's metadata is usually changed when you save it. Like the timestamp of when the file was last edited.

The same happens here. In this case "metadata" like the cache is evicted.

**Comment by oSumAtrIX** [comment]
Clearing the cache is useful if you want to update immediately instead of waiting for the cache to get evicted. Of course this is a "hack" to clear the cache, but it is part of the action to set the API URL and the reason why its expected UX to run when you click OK. If you want to cancel that, you can click cancel.
