### ISSUE TITLE
feat: Allow free scrolling in patching screen

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#1736]
### Feature description

Allow the user to scroll freely in the patching screen and read the patch logs if they want to. The view should (still) lock to the bottom of the patch log if the user scrolls back to the bottom of the page (and/or put an arrow to scroll to the bottom, like in Discord).

### Motivation

Currently, the user is allowed to scroll up but the manager will force the view back to the bottom of the patch log every time a new line is added, making it impossible to read the patch log until it is finished. Why even allow the user to scroll up while patching is still ongoing?

Freely scrolling in the patch screen will allow users to properly read the patch logs and immediately start investigating if an error or failure occurs.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by Domenic-MZS** [comment]
This is so annoying. Please, let me tackle this one.

**Comment by oSumAtrIX** [comment]
@Domenic-MZS  Sure, thanks for your multitude on recent contributions

**Comment by Domenic-MZS** [comment]
> @Domenic-MZS Sure, thanks for your multitude on recent contributions

Hey, thanks a bunch for the shoutout! It means a lot. Glad I could help out 🚀!

**Comment by KobeW50** [comment]
Thank you @Domenic-MZS
