### ISSUE TITLE
feat: Add warning when installing if any patching errors occured

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#1737]
### Feature description

If a patch fails or errors (but patching doesn't abort), the manager should warn the user about it when the user tries to install or export the APK.

One of the buttons on the popup should copy the patch logs. And, if possible, the warning popup should specify which patches failed. 

(Note that some patching errors aren't related to patches, but rather regarding the APK, (de)compiling, etc. These miscellaneous errors also need to be addressed in the dialog.)

### Motivation

1. I see so many users on Discord and Reddit who don't realize that patching errors occured. 

2. When a user doesn't realize a patching error occured, they may be missing a critical patch (such as `GmsCore support` in the case of YT and YT Music). Even for non-critical patches, the user should be notified that a patch which they selected couldn't be applied.

3. When a patching error occurs, it may cause the installed app to crash or have bugs. This warning will prevent this from occurring in many cases, or at least give the user a hint as to why their patched app is crashing/buggy.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
ReVanced Manager will soon be released as [a full rewrite](https://github.com/ReVanced/revanced-manager/tree/compose-dev). Over time, many feature requests have been made for the current version of ReVanced Manager, but to accelerate the development of the new version of ReVanced Manager, we have to focus on it, which I am closing this issue according to the [contribution guidelines](https://github.com/ReVanced/revanced-manager/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long/ Low priority/ Maintainers un-interested/ Too complex to realize
- Feature planned/ already implemented for the new version of ReVanced Manager
- Already implemented

Regardless, anyone who comes across this feature request can PR it to the current version of ReVanced Manager until the new version is ready. Thanks for your feature request!
