### ISSUE TITLE
feat: Abort patching if no patches successfully apply

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#1738]
### Feature description

If all of the selected patches fail to apply, the patcher should abort.

### Motivation

There are times when all patches may fail, such as when there is only a single patch.

(I understand this is not a very strong motivation, and it will be partially solved by https://github.com/ReVanced/revanced-manager/issues/1737)

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
A patch can partially execute. It is an arbitrary decision to abort patching
