### ISSUE TITLE
bug: Manager 0.0.9 Installed apps literally duplicating

### ISSUE THREAD

**Issue by SpookieGames** [revanced/revanced-manager#174]
### Type

Cosmetic

### Branch

Flutter 

### Bug description

Installed apps duplicating every time I click app info or launch manager 

### Steps to reproduce

1. Go to installed apps screen
2. See apps duplicate

### Relevant log output

```shell
https://pastebin.com/kUBLsFAg
```

### Screenshots or videos

![Screenshot_2022-09-17-21-28-30-184_app revanced manager flutter](https://user-images.githubusercontent.com/41782443/190873710-a0bf9d18-628a-4d3c-a80d-63191d36e5c2.jpg)

**Comment by ponces** [comment]
Please confirm if issue is fixed on [v0.0.10](https://github.com/revanced/revanced-manager/releases/tag/v0.0.10).

**Comment by SpookieGames** [comment]
Currently on 0.0.11 and seems to be fixed

**Comment by SadLinusGuy0** [comment]
It still happens on 0.0.12

**Comment by SpookieGames** [comment]
Try to reinstall as for me it's fixed
