### ISSUE TITLE
feat: Option to rename app 

### ISSUE THREAD

**Issue by randomcloudswings** [ReVanced/revanced-manager#1740]
### Feature description

A patch Option to change the app name would be good

### Motivation

sometimes when two same apps are installed, it is hard to distinguish between them, like for example, there are two yt music apps are installed on my phone, one is normal one and other is revanced patched. It makes it hard to distinguish.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by Ushie** [comment]
This should be opened in the ReVanced Patches repository
