### ISSUE TITLE
White overlay when trying to install YT patch APK 

### ISSUE THREAD

**Issue by gozes** [ReVanced/revanced-manager#1745]
### Bug description

After applying all the patches to the YouTube app and trying to install the patch APK I get a white overlay that that stays there and dose noting. It never returns a successful installation message and it also doesn't update the YouTube app in the background 
![Screenshot_20240305-105049](https://github.com/ReVanced/revanced-manager/assets/632922/c9d589b6-c14f-4933-aba4-fc473056deb1)

### Version of ReVanced Manager and version & name of app you are patching

 - Device Info
 ReVanced Manager: 1.19.1
 Model: FP4
 Android version: 13
 Supported architectures: arm64-v8a, armeabi-v7a, armeabi
 Root permissions: No
 
 - Patch Info
 App: com.google.android.youtube v19.04.37 (Suggested: 19.04.37)
 Patches version: v4.3.0
 Patches added: Default
 Patches removed: Remove viewer discretion dialog, Disable precise seeking gesture, Seekbar tapping, Swipe controls, Disable auto captions, Hide video action buttons, Hide autoplay button, Hide captions button, Hide cast button, Navigation buttons, Hide player buttons, Hide album cards, Comments, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Hide 'Load more' button, Player flyout menu, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Disable player popup panels, Custom player overlay opacity, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, Change start page, Disable resuming Shorts on startup, Enable tablet layout, Tablet mini player, Theme, Alternative thumbnails, Announcements, Enable debugging, Spoof device dimensions, Bypass URL redirects, Remove tracking query parameter, Disable zoom haptics, HDR auto brightness, Restore old video quality menu, GmsCore support
 Default patch options changed: None
 
 - Settings
 Allow changing patch selection: true
 Version compatibility check: true
 Show universal patches: false
 Patches source: revanced/revanced-patches
 Integration source: revanced/revanced-integrations
 
 - Logs
 Reading APK
 Decoding app manifest
 Loading patches
 Merging integrations
 Deleting existing temporary files directory
 Decoding resources
 Executing patches
 Applied 14 patches
 Compiling patched dex files
 Compiled 8 dex files
 Compiling modified resources
 Aligning out.apk
 Signing out.apk
 Patched APK
 Installing patched app
 Installation failed
 Installing patched app

### Installation method

Regular

### ReVanced Manager logs

```shell
- Device Info
 ReVanced Manager: 1.19.1
 Model: FP4
 Android version: 13
 Supported architectures: arm64-v8a, armeabi-v7a, armeabi
 Root permissions: No
 
 - Patch Info
 App: com.google.android.youtube v19.04.37 (Suggested: 19.04.37)
 Patches version: v4.3.0
 Patches added: Default
 Patches removed: Remove viewer discretion dialog, Disable precise seeking gesture, Seekbar tapping, Swipe controls, Disable auto captions, Hide video action buttons, Hide autoplay button, Hide captions button, Hide cast button, Navigation buttons, Hide player buttons, Hide album cards, Comments, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Hide 'Load more' button, Player flyout menu, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Disable player popup panels, Custom player overlay opacity, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, Change start page, Disable resuming Shorts on startup, Enable tablet layout, Tablet mini player, Theme, Alternative thumbnails, Announcements, Enable debugging, Spoof device dimensions, Bypass URL redirects, Remove tracking query parameter, Disable zoom haptics, HDR auto brightness, Restore old video quality menu, GmsCore support
 Default patch options changed: None
 
 - Settings
 Allow changing patch selection: true
 Version compatibility check: true
 Show universal patches: false
 Patches source: revanced/revanced-patches
 Integration source: revanced/revanced-integrations
 
 - Logs
 Reading APK
 Decoding app manifest
 Loading patches
 Merging integrations
 Deleting existing temporary files directory
 Decoding resources
 Executing patches
 Applied 14 patches
 Compiling patched dex files
 Compiled 8 dex files
 Compiling modified resources
 Aligning out.apk
 Signing out.apk
 Patched APK
 Installing patched app
 Installation failed
 Installing patched app
```

### Patch logs

```shell
- Device Info
 ReVanced Manager: 1.19.1
 Model: FP4
 Android version: 13
 Supported architectures: arm64-v8a, armeabi-v7a, armeabi
 Root permissions: No
 
 - Patch Info
 App: com.google.android.youtube v19.04.37 (Suggested: 19.04.37)
 Patches version: v4.3.0
 Patches added: Default
 Patches removed: Remove viewer discretion dialog, Disable precise seeking gesture, Seekbar tapping, Swipe controls, Disable auto captions, Hide video action buttons, Hide autoplay button, Hide captions button, Hide cast button, Navigation buttons, Hide player buttons, Hide album cards, Comments, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Hide 'Load more' button, Player flyout menu, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Disable player popup panels, Custom player overlay opacity, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, Change start page, Disable resuming Shorts on startup, Enable tablet layout, Tablet mini player, Theme, Alternative thumbnails, Announcements, Enable debugging, Spoof device dimensions, Bypass URL redirects, Remove tracking query parameter, Disable zoom haptics, HDR auto brightness, Restore old video quality menu, GmsCore support
 Default patch options changed: None
 
 - Settings
 Allow changing patch selection: true
 Version compatibility check: true
 Show universal patches: false
 Patches source: revanced/revanced-patches
 Integration source: revanced/revanced-integrations
 
 - Logs
 Reading APK
 Decoding app manifest
 Loading patches
 Merging integrations
 Deleting existing temporary files directory
 Decoding resources
 Executing patches
 Applied 14 patches
 Compiling patched dex files
 Compiled 8 dex files
 Compiling modified resources
 Aligning out.apk
 Signing out.apk
 Patched APK
 Installing patched app
 Installation failed
 Installing patched app
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by xDARKxDEVILx** [comment]
Can reproduce but i was able to get the same white overlay elsewhere too when i went to patch options for gms core, a restart fixed it and i was able to see things right, don't know if this is helpful or not

**Comment by oSumAtrIX** [comment]
Try @xDARKxDEVILx suggestion or find an older version of ReVanced Manager that works so we can track down where the issue came up

**Comment by gozes** [comment]
Ok so try restarting my phone and repatching but I still get the white overlay

**Comment by xDARKxDEVILx** [comment]
> Ok so try restarting my phone and repatching but I still get the white overlay 

The white overlay only disappeared after restarting manager for the patch options menu of gmscore only, the installation didn't but i haven't tried doing it a second time yet, and will do soon

**Comment by xDARKxDEVILx** [comment]
Yeah, so restarting manager doesn't fix the white overlay for installation

**Comment by ILoveOpenSourceApplications** [comment]
I have actually found an easily replicable pattern for this issue. If you're someone who's constantly asked by Google play protect to scan an app during installation and you press `Don't install app` instead of the hidden  `Install without scanning`, voila, the white overlay screen appears.

https://github.com/ReVanced/revanced-manager/assets/117499019/9915b11d-d76f-4d89-a21e-8779216c637b

**Comment by ActualMasterOogway** [comment]
Having the same issue, decided to save the Patched APK and install it not from Revanced. I got an error message saying "Failed to install APK. Package is invalid"

**Comment by DeerAndy** [comment]
Same issue as above, tried installing from saved patch apk and getting rid that something went wrong and it wasn't installed. Getting white overly when installing from revanced manager, able to hit back to get out of it but patching from existing install or downloaded APK doesn't help.

**Comment by oSumAtrIX** [comment]
The issue is fixed locally and caused by trying to apply a parameter on a translation string that doesn't have a parameter

**Comment by gozes** [comment]
> The issue is fixed locally and caused by trying to apply a parameter on a translation string that doesn't have a parameter 

So I guess we wait for a new version to be released with this  fixed?

**Comment by gozes** [comment]
So I don't think this is close. I updated to 1.19.2 which has the above or and now I'm getting 

```
- Device Info
ReVanced Manager: 1.19.2
Model: FP4
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.04.37 (Suggested: 19.04.37)
Patches version: v4.3.0
Patches added: Default
Patches removed: Copy video URL, Remove viewer discretion dialog, Disable precise seeking gesture, Seekbar tapping, Swipe controls, Disable auto captions, Hide video action buttons, Hide autoplay button, Hide captions button, Hide cast button, Navigation buttons, Hide player buttons, Hide album cards, Comments, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Hide 'Load more' button, Player flyout menu, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Disable player popup panels, Custom player overlay opacity, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, Change start page, Disable resuming Shorts on startup, Enable tablet layout, Tablet mini player, Theme, Alternative thumbnails, Announcements, Always repeat, Enable debugging, Spoof device dimensions, Bypass URL redirects, Remove tracking query parameter, Disable zoom haptics, HDR auto brightness, Restore old video quality menu, GmsCore support
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 12 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Aligning APK
An error occurred:
java.io.FileNotFoundException: /data/app/~~A-0shl3r1-9_2oX_8JsAdA==/com.google.android.youtube-xT_LRpddEGZBjLN4lW-lbw==/base.apk: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
	at n1.s0.M0(Unknown Source:105)
	at n1.s0.Q0(Unknown Source:2)
	at n1.s0.P0(Unknown Source:21)
	at n1.s0.close(Unknown Source:9)
	at kotlin.io.CloseableKt.closeFinally(Unknown Source:4)
	at app.revanced.library.ApkUtils.applyTo(Unknown Source:323)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:517)
	at app.revanced.manager.flutter.MainActivity.k(Unknown Source:0)
	at app.revanced.manager.flutter.f.run(Unknown Source:20)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7818)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 11 more
```

**Comment by gitdine** [comment]
@gozes gozes

I'm also getting this since updating to 1.19.2 🙁
Trying to patch apps now fails and throws an 'EACCES (Permission denied)' error.
I'm rooted and using mount method.

**Comment by gozes** [comment]
> @gozes 
> 
> I'm also getting this error since updating to 1.19.2 🙁
> Trying to patch apps now fails and always throws an '_EACCES (Permission denied)_' error.
> I'm rooted and using mount method.

@gitdine  I'm not rooted so I don't think that's the issue here

**Comment by oSumAtrIX** [comment]
That issue is unrelated to this.

**Comment by gozes** [comment]
> That issue is unrelated to this.

@oSumAtrIX is there an issue for this or should I open one?

**Comment by gitdine** [comment]
I downgraded to 1.19.1 and everything is working fine again. So I guess I'll just wait for the next update.

**Comment by gozes** [comment]
> I downgraded to 1.19.1 and everything is working fine again. So I guess I'll just wait for the next update.

I was on 1.19.1 and that's when I saw this issue so not sure how is it working for you

**Comment by gitdine** [comment]
> > I downgraded to 1.19.1 and everything is working fine again. So I guess I'll just wait for the next update.
> 
> I was on 1.19.1 and that's when I saw this issue so not sure how is it working for you

I'm talking about the _EACCES (Permission denied)_ error. I started getting it after upgrading to 1.19.2, after downgrading everything went back to normal. I never faced the overlay bug in the OP.

**Comment by xDARKxDEVILx** [comment]
The white overlay is gone but it is now replaced with requiring root permissions when using normal install way XD
I think i will open a new issue for this

**Comment by gozes** [comment]
So I'm getting when I try to install @oSumAtrIX any idea what is going on? Sadly I already uninstalled the old version of Vance's app so I'm left with only default YT 🤢
![Screenshot_20240309-181545.png](https://github.com/ReVanced/revanced-manager/assets/632922/9d42e3b0-2ef3-4b97-b6f8-5b6f60de30fe)

**Comment by oSumAtrIX** [comment]
If you need support move to one of our links on https://revanced.app
