### ISSUE TITLE
feat: play the youtube videos in customised queue(a preimium feature)

### ISSUE THREAD

**Issue by Gyan-Singh** [ReVanced/revanced-manager#1747]
### Feature description

**Queue Management:** Users can add, remove, and rearrange videos in the queue according to their preferences.
**Customization Options:** Users have the flexibility to create multiple queues and customize each queue with different sets of videos.
**Playback Control:** Seamless playback controls allow users to play, pause, skip, and repeat videos within the queue.
**Persistence:** The created queues are persisted across sessions, ensuring that users can access their customized playlists at any time.

### Motivation

**Enhanced User Experience:** By allowing users to create customized video queues, the application becomes more user-centric, catering to individual preferences and tastes.
**Personalized Content Consumption:** Users can create queues based on specific themes, moods, or interests, providing a more personalized and enjoyable viewing experience.
**Improved Engagement:** Customized queues encourage users to spend more time within the application, increasing user engagement and retention rates.
**Competitive Advantage:** Implementing this feature sets the application apart from competitors by offering a unique and valuable feature that enhances user satisfaction.
**Adaptability:** In today's dynamic media landscape, users expect customizable options to tailor their experiences. Implementing a customized video queue feature demonstrates responsiveness to user needs and market trends.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by Ushie** [comment]
This repository is about ReVanced Manager, move to the [ReVanced Patches repository](https://github.com/ReVanced/revanced-patches)
