### ISSUE TITLE
[BUG]Update to v 1.19.3 breaks every patch attempts in dex building faze

### ISSUE THREAD

**Issue by EbanNox** [ReVanced/revanced-manager#1757]
### Bug description

Befire updating, I had everything working smoothly , and never ever experiansed fails of any kinde during apk patching... never ever , every patch was always completed succsesfully ...
Now later today i got the urge to hit that uppdate button witch appended me to v 1.19.3 ...

And now in this version, no matter what, every patch i attempt to push on any app, faills mid way during compiling faze on dex files ... 

### Version of ReVanced Manager

1.19.3

### Installation method

None

### ReVanced Manager logs

[revanced-manager_logcat_20240309114623223153.log](https://github.com/ReVanced/revanced-manager/files/14546025/revanced-manager_logcat_20240309114623223153.log)

### Patch logs

```shell
- Device Info
ReVanced Manager: 1.19.3
Model: SM-G998B
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: tv.twitch.android.app v16.9.1 (Suggested: 16.9.1)
Patches version: v4.3.0
Patches added: Debug mode, Remove screen capture restriction, Remove screenshot restriction
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 9 patches
Compiling patched dex files
Compiled 12 dex files
Compiling modified resources
An error occurred:
t0.b: d1.a: could not exec (exit code = 1): [/data/app/~~8Pq0WfRKGVYnMHiOd4EHxw==/app.revanced.manager.flutter-0Jhd6cFxW6VghNkchNW9RA==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QXOUMA/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QXOUMA/revanced-temporary-files/apk/build/resources.zip]
	at r0.a.f(Unknown Source:144)
	at r0.a.d(Unknown Source:104)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:1)
	at app.revanced.patcher.Patcher.get(SourceFile:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.k(Unknown Source:0)
	at app.revanced.manager.flutter.f.run(Unknown Source:20)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: d1.a: could not exec (exit code = 1): [/data/app/~~8Pq0WfRKGVYnMHiOd4EHxw==/app.revanced.manager.flutter-0Jhd6cFxW6VghNkchNW9RA==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QXOUMA/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QXOUMA/revanced-temporary-files/apk/build/resources.zip]
	at f1.h.b(Unknown Source:75)
	at r0.a.f(Unknown Source:122)
	... 7 more
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
Resource compilation breaking is caused by including patches that aren't enabled by default

**Comment by EbanNox** [comment]
> Resource compilation breaking is caused by including patches that aren't enabled by default

What that supposed to mean?! 

And how does this help me? Sins it all worked fine previus version, and not on this one?

**Comment by oSumAtrIX** [comment]
It means that one of the patches you included that are not used by default broke compiling the resources
