### ISSUE TITLE
feat: Manual Patching Support Using Local jar File for Faster Access to Latest Patches

### ISSUE THREAD

**Issue by ayoubelmhamdi** [ReVanced/revanced-manager#1771]
### Feature description

We can easily build the `branch dev` to have the latest  `revanced-patches-4.4.0-dev.6.jar` file using `./gradlew build`, but the process of using it to patch an APK isn't well-documented and requires some patience. I think if you provided a way to use it directly in the Revanced APK, it would be easier to use, like an `API_URL`.

<p align="left">
  <img width="144"  src="https://github.com/ReVanced/revanced-patcher/assets/34358145/5763b281-37aa-4029-a13f-36a2df77b541">
</p>

### Motivation

This feature is very useful for easily testing the latest patches without having to wait for a new stable Revanced APK release, which can take a long time to arrive.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Using patches locally can be done using ReVanced CLI

**Comment by ayoubelmhamdi** [comment]
`Revanced APK` is more user-friendly than `ReVanced CLI` for handling patches.

**Comment by oSumAtrIX** [comment]
ReVanced Manager will soon be released as [a full rewrite](https://github.com/ReVanced/revanced-manager/tree/compose-dev). Over time, many feature requests have been made for the current version of ReVanced Manager, but to accelerate the development of the new version of ReVanced Manager, we have to focus on it, which I am closing this issue according to the [contribution guidelines](https://github.com/ReVanced/revanced-manager/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long/ Low priority/ Maintainers un-interested/ Too complex to realize
- Feature planned/ already implemented for the new version of ReVanced Manager
- Already implemented

Regardless, anyone who comes across this feature request can PR it to the current version of ReVanced Manager until the new version is ready. Thanks for your feature request!
