### ISSUE TITLE
bug: dev releases are offered as update

### ISSUE THREAD

**Issue by masterflitzer** [ReVanced/revanced-manager#1774]
### Bug description

if you open revanced manager, dev releases are offered as regular updates (can be seen by tapping the update button)

to install the latest releases one therefore has to go to GitHub and manually download it

### Version of ReVanced Manager and version & name of app you are patching

Revanced Manager 1.18.0
Currently offered update to 1.19.4-dev.1

### Installation method

None

### ReVanced Manager logs

```shell
N/A
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
Update the app
