### ISSUE TITLE
Shizuku support

### ISSUE THREAD

**Issue by weiliang011** [ReVanced/revanced-manager#1775]
### Feature description

Pls can you add shizuku support? So i dont need to root ty (for split apks) 

### Motivation

-Why should this feature be implemented?
So we don't need root
-What are the benefits? 
Using split apks without root
-What makes this feature important?
No root for split apks

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
Shizuku does not grant permissions to mount over apps
