### ISSUE TITLE
Shizuku download

### ISSUE THREAD

**Issue by weiliang011** [ReVanced/revanced-manager#1777]
### Feature description

Pls enable support for shizuku to install or upgrade 

### Motivation

Benefits are that we can download with less problems

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-manager/issues/1775

**Comment by weiliang011** [comment]
> https://github.com/ReVanced/revanced-manager/issues/1775

Hi, this is not the samd

**Comment by Ushie** [comment]
https://github.com/ReVanced/revanced-manager/issues/357
