### ISSUE TITLE
bug: Video playblack blocked 

### ISSUE THREAD

**Issue by xDoge26** [ReVanced/revanced-manager#1779]
### Bug description

![Screenshot_2024-03-23-12-51-53-902_app revanced android youtube](https://github.com/ReVanced/revanced-manager/assets/92904701/5682bd26-8a4a-43e8-a346-341b29a38dbf)

### Version of ReVanced Manager and version & name of app you are patching

Version: 1.19.3
Model: 2201117TG
Android Version: 12
Supported Archs: arm64-v8a, armeabi-v7a, armeabi

youtube-revanced_v19.04.37-patches_v4.3.0

### Installation method

Regular

### ReVanced Manager logs

```shell
none
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by validcube** [comment]
👋 Hello, @xDoge26!

Thanks for filing this issue, but however this issue is out-of-scope for this repository (ReVanced Manager), the correct repository to file this issue is in our [ReVanced Patches repository](https://github.com/ReVanced/revanced-patches).
