### ISSUE TITLE
bug: <Trying to Update the Manager from the App does nothing> 

### ISSUE THREAD

**Issue by GitExploraa** [revanced/revanced-manager#178]
### Type

Error while running the manager

### Branch

Latest Github Release 0.0.9 Apk file

### Bug description

Trying to Update the Manager from the App does nothing, the Download Starts, but the file is nowhere to be found, thus needing to grab the new Apk from Github to Install it eachtime

### Steps to reproduce

1. Open the Manager
2. Select the Update Manager Button

### Relevant log output

```shell
None
```

**Comment by pietryszak** [comment]
Think... you use latest version 0.0.9. How update can work if you have the latest version ?

**Comment by GitExploraa** [comment]
> 

hey, my bad... i cant test it on 0.0.9 indeed, but it didnt work with all the previous versions too, ill update this thread if anything changes

**Comment by pietryszak** [comment]
> > 
> 
> hey, my bad... i cant test it on 0.0.9 indeed, but it didnt work with all the previous versions too, ill update this thread if anything changes

look at imgur that I send. It's works. But first click update button, the download app message was visible, when message disappear, the click update button once again and app starts to install.

**Comment by GitExploraa** [comment]
> > > 
> > 
> > 
> > hey, my bad... i cant test it on 0.0.9 indeed, but it didnt work with all the previous versions too, ill update this thread if anything changes
> 
> look at imgur that I send. It's works. But first click update button, the download app message was visible, when message disappear, click update button once again and app starts to install.

i dowgraded to a previous version and tried this, and it indeed works Thank you, Still i think it needs some improvements, like notifications for new releases and a better update experience

**Comment by pietryszak** [comment]
> > > > 
> > > 
> > > 
> > > hey, my bad... i cant test it on 0.0.9 indeed, but it didnt work with all the previous versions too, ill update this thread if anything changes
> > 
> > 
> > look at imgur that I send. It's works. But first click update button, the download app message was visible, when message disappear, click update button once again and app starts to install.
> 
> i dowgraded to a previous version and tried this, and it indeed works Thank you, Still i think it needs some improvements, like notifications for new releases and a better update experience

So you shoud close this issue labeled as bug, and create new with Feature request :)

**Comment by GitExploraa** [comment]
Sure, will do

**Comment by pietryszak** [comment]
> Sure, will do

Great :)
