### ISSUE TITLE
Add Dark Mode patch for TikTok 

### ISSUE THREAD

**Issue by Monvey0** [ReVanced/revanced-manager#1784]
### Feature description

Tiktok one of few apps that doesn't support Dark mode in android, if you can please support dark mode patch for tiktok

### Motivation

It's 2024 and almost all social media support dark mode, tiktok provide dark mode in iOS but not Android

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [ ] The feature request is only related to ReVanced Manager

**Comment by alreadyhaveanaccount-signin** [comment]
it exists now
