### ISSUE TITLE
ReVanced/GmsCore should track microg/GmsCore

### ISSUE THREAD

**Issue by alexsch01** [ReVanced/revanced-manager#1786]
Currently https://github.com/ReVanced/GmsCore tracks https://github.com/oSumAtrIX/GmsCore which is an archived repo

---

https://github.com/ReVanced/GmsCore should track https://github.com/microg/GmsCore

**Comment by Ushie** [comment]
Hi, open this in the GmsCore repository please

**Comment by alexsch01** [comment]
moved to https://github.com/ReVanced/GmsCore/issues/3
