### ISSUE TITLE
microG problem

### ISSUE THREAD

**Issue by DVSVIDEO** [ReVanced/revanced-manager#1789]
### Bug description

When I install the youtube revanced app, it plays the video without any problems, but when I log in to my account using microG, the video does not play.
The gist of the error message is "this content is not available in this app" "can be viewed in the latest version of youtube"

### Version of ReVanced Manager and version & name of app you are patching

any ReVanced, any microG

### Installation method

None

### ReVanced Manager logs

```shell
none
```

### Patch logs

```shell
none
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Ushie** [comment]
Hey, we're aware of this issue, you can find updates here: https://github.com/ReVanced/revanced-patches/issues/2878

P.S. this repository is solely for ReVanced Manager, MicroG is not recognized in this repo
