### ISSUE TITLE
bug(Repository level): ReVanced lego not loaded on issue template

### ISSUE THREAD

**Issue by validcube** [ReVanced/revanced-manager#1793]
Create issue, during creating or filling out the issue, the logo is invisible because of missing (404) asset

![image](https://github.com/ReVanced/revanced-manager/assets/93124920/a3f6b7bb-7d34-41ae-b680-348483262e88)
![image](https://github.com/ReVanced/revanced-manager/assets/93124920/85678655-3caf-4625-9016-0b7a480e6a1e)

**Comment by validcube** [comment]
This only affected our repository, we don't have revanced-logo.svg but revanced-logo-round.svg
![image](https://github.com/ReVanced/revanced-manager/assets/93124920/8d8cbb2a-e370-40c6-a0ef-9aee0730a05c)

**Comment by SotGrank** [comment]
does your youtube vanced work? mine doesn't work

**Comment by Aniket8195** [comment]
> does your youtube vanced work? mine doesn't work

No
