### ISSUE TITLE
Add ability to install / update GmsCore

### ISSUE THREAD

**Issue by peat80** [ReVanced/revanced-manager#1801]
### Feature description

It would be great if we could install and update the GmsCore app from inside the Revanced Manager.

### Motivation

Everything would be in one place then for non-root-installations.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
GmsCore is a patch specific dependency and ReVanced Manager is agnostic towards patches
