### ISSUE TITLE
bug: <YouTube keeps stopping and crashing>

### ISSUE THREAD

**Issue by Vegetagiy123** [revanced/revanced-manager#181]
### Type

Other

### Branch

YouTube keeps crashes when I patch it through apk file 

### Bug description

YouTube keeps crashing while I patch it through patcher  it just shows a grey screen it doesn't load all the way 

### Steps to reproduce

Step 1 make sure YouTube gets fixed 
Step 2 make sure YouTube doesn't crash and stop 
Step 3 make sure YouTube loads all the way

### Relevant log output

```shell
YouTube keeps stopping on Revanced manger it just shows a grey screen
```

### Screenshots or videos

![Screenshot_20220917-195941](https://user-images.githubusercontent.com/113322179/190883720-cf86d9b4-14b7-49c2-9e73-88e67959d5d4.png)

**Comment by ponces** [comment]
Are crashings occuring after patching or during patching?

**Comment by Vegetagiy123** [comment]
It only crashes when the latest version of YouTube is installed version 17.36.37 it just leaves a grey screen

**Comment by escape0707** [comment]
> It only crashes when the latest version of YouTube is installed version 17.36.37 it just leaves a grey screen

https://github.com/revanced/revanced-patches#-comgoogleandroidyoutube

Please only patch against supported versions.
