### ISSUE TITLE
bug: Patch not working 

### ISSUE THREAD

**Issue by Sourav0357** [ReVanced/revanced-manager#1818]
### Bug description

There is Upgrade button and get music premium tab in YouTube music,Even after applying remove upgrade button & hide get music premium patch.

### Version of ReVanced Manager and version & name of app you are patching

RV - 1.19.3
Yt Music - 6.44.54
![Screenshot_20240401_142528](https://github.com/ReVanced/revanced-manager/assets/165359639/15738bca-ae00-4590-b9d6-c5f577fb32b3)
![IMG_20240401_143424_962](https://github.com/ReVanced/revanced-manager/assets/165359639/547b8070-8640-4e19-88f2-f0aabab1c625)

### Installation method

Regular

### ReVanced Manager logs

```shell
Nil
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
Backwards compatibility won't be added, the latest version will eventually be available to everyone
