### ISSUE TITLE
bug: <title> youtube crashing when opened after patching

### ISSUE THREAD

**Issue by bogoch** [revanced/revanced-manager#182]
### Type

Other

### Branch

Youtube keep crashing when opened after patching.

### Bug description

After i patch youtube , when i try to open the app , it will just keep crashing and wont open. 

YouTube version - 17.33.42
reVanced Manager version - 0.0.10
Installed as root.

### Steps to reproduce

.

### Relevant log output

```shell
09-18 07:03:17.829 26718 26736 D AppScoutStateMachine: 26718-ScoutStateMachinecreated
09-18 07:03:17.923 26718 26718 D SurfaceView: UPDATE Surface(name=SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity])/@0xd2fbf78, mIsProjectionMode = false
09-18 07:03:17.923 26718 26718 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
09-18 07:03:17.923 26718 26718 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
09-18 07:03:17.923 26718 26718 D SurfaceControl: nativeSetScreenProjection ===> setScreenProjection
09-18 07:03:17.942 26718 27019 I OpenGLRenderer: Davey! duration=103047ms; Flags=1, FrameTimelineVsyncId=4547975, IntendedVsync=47962721725678, Vsync=47962730059011, InputEventId=701944839, HandleInputStart=47962732073629, AnimationStart=47962732075973, PerformTraversalsStart=47962732076702, DrawStart=47962756627119, FrameDeadline=47962741725677, FrameInterval=47962732058056, FrameStartTime=8333333, SyncQueued=47962757121077, SyncStart=47962757175035, IssueDrawCommandsStart=47962757234202, SwapBuffers=47962758725504, FrameCompleted=48065769564059, DequeueBufferDuration=1079583, QueueBufferDuration=626459, GpuCompleted=48065769564059, SwapBuffersCompleted=47962759745608, DisplayPresentTime=14651610,
```

### Screenshots or videos

https://user-images.githubusercontent.com/63978357/190885012-d97f6845-82af-4f33-b7a5-0b47b6485ed7.mp4

**Comment by escape0707** [comment]
How did you installed YouTube?

**Comment by bogoch** [comment]
I uninstalled youtube from playstore, then I downloaded abd installed version 17.33.42 from apkmirror , i selected the apk i just installed and selected all the available patches.

**Comment by Vegetagiy123** [comment]
I install it with the patcher on YouTube and. Manger and it only crashes on version 17.36.37 it leaves a grey screen and then it stopes

**Comment by Vegetagiy123** [comment]
YouTube stopes completely and it doesn't give me the option to choose what version to patch

**Comment by escape0707** [comment]
> I install it with the patcher on YouTube and. Manger and it only crashes on version 17.36.37 it leaves a grey screen and then it stopes

That version is not supported as I've told you in your issue.

**Comment by bogoch** [comment]
BTW , it says on the app info 0 applied patches even though the installation was successful.

**Comment by ponces** [comment]
> I uninstalled youtube from playstore, then I downloaded abd installed version 17.33.42 from apkmirror , i selected the apk i just installed and selected all the available patches.

You should skip MicroG patch if you're installing on root mode.
Not manager's fault.
Closed.
