### ISSUE TITLE
[BUG ]Hiding like or dislike button hides other buttons in Shorts

### ISSUE THREAD

**Issue by ilko-k** [ReVanced/revanced-manager#1820]
### Bug description

Hiding the like or the dislike button in short videos also hides other buttons (comments, share...)

### Version of ReVanced Manager and version & name of app you are patching

Manager v1.19.3
YouTube v19.09.37

### Installation method

Regular

### ReVanced Manager logs

```shell
Cleared, sorry.
```

### Patch logs

```shell
Default patch selection untouched.
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Ushie** [comment]
This repo is about ReVanced Manager only, check for an existing issue or make one in https://github.com/ReVanced/revanced-patches
