### ISSUE TITLE
feat: Change "Show changelog" buttons text.

### ISSUE THREAD

**Issue by base-13** [ReVanced/revanced-manager#1822]
### Feature description

the text of the buttons "Show changelog" should be changed to just "Changelog" which is better and simple.
![IMG_20240402_003749](https://github.com/ReVanced/revanced-manager/assets/86418442/a741bdd5-f563-4530-94bd-f5b73d1228a6)
[Image is taken from ReVanced Manager 1.19.3]

### Motivation

changing the text would be better as:
- it is shorter.
- easier to read.
- makes button size smaller, helpful for people who use big text size and/or small displsy.
- better UX

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
Changelog would not indicate an action. One could fail to understand that it shows the changelog. Buttons are labeled after actions, such as "Cancel", "Start", "Update" and more.
