### ISSUE TITLE
OFFLINE SUPPORT

### ISSUE THREAD

**Issue by jcfyre** [ReVanced/revanced-manager#1823]
### Feature description

PLEASE add the ability to start up and use the app offline without internet. No intitial internet causes blank app list. At least be able to have universal patches available immediately such as make an app debuggable patch without the need for internet on initial startup.

### Motivation

I believe in immediate usability without internet as that allows one to install and use a downloaded app anywhere without reliance on internet or if the app data needed to be cleared but there was no internet to get it running again to show all list. This is very relevant to modding apps because modding is about making changes and lifting restrictions and having an app usable offline immediately is essential to having true control, even if it is a one time start up it is still inconvenient. At least make all the files for start up and patches available, and also installable without internet (assuming they have been downloaded already).

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
The app works offline
