### ISSUE TITLE
bug: t0.b: d1.a: could not exec

### ISSUE THREAD

**Issue by FlyByKnight23** [ReVanced/revanced-manager#1825]
### Bug description

Happens whenever I try to patch the currently suggested version of YouTube 19.09.37.

Steps to Reproduce:

1. Uninstall Revanced Manager 1.4.1
2. Download and install Revanced Manager 1.19.3
3. Download Youtube 19.09.37
4. Patch Youtube

Installation type is non-root. Vanced MicroG does not appear in the patch list.

![Screenshot_20240402_081150_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/119979024/d2a7ec87-3856-4d6f-817a-948a372159e5)
![Screenshot_20240402_081203_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/119979024/641e2522-8213-41ac-b41c-c1f08fed17ae)
![Screenshot_20240402_081209_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/119979024/c316be21-b81a-4478-892c-d3ca143461cc)
![Screenshot_20240402_081215_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/119979024/96401b81-d81c-43ec-9296-221eb0bab05c)

### Version of ReVanced Manager and version & name of app you are patching

Revanced Manager version: 1.19.3

YouTube version: 19.09.37

### Installation method

Regular

### ReVanced Manager logs

```shell
Too long. Can't copy and paste or post it.
```

### Patch logs

```shell
{"com.google.android.youtube":["Alternative thumbnails","Always repeat","Announcements","Bypass URL redirects","Change start page","Client spoof","Comments","Copy video URL","Custom player overlay opacity","Disable auto captions","Disable fullscreen ambient mode","Disable player popup panels","Disable precise seeking gesture","Disable resuming Shorts on startup","Disable rolling number animations","Disable suggested video end screen","Disable zoom haptics","Downloads","Enable debugging","Enable tablet layout","GmsCore support","Hide 'Load more' button","Hide Shorts components","Hide ads","Hide album cards","Hide autoplay button","Hide breaking news shelf","Hide captions button","Hide cast button","Hide crowdfunding box","Hide endscreen cards","Hide filter bar","Hide floating microphone button","Hide info cards","Hide layout components","Hide player buttons","Hide seekbar","Hide timestamp","Hide video action buttons","Minimized playback","Navigation buttons","Open links externally","Playback speed","Player flyout menu","Remember video quality","Remove tracking query parameter","Remove viewer discretion dialog","Restore old seekbar thumbnails","Restore old video quality menu","Return YouTube Dislike","Seekbar tapping","SponsorBlock","Spoof app version","Spoof device dimensions","Swipe controls","Tablet mini player","Theme","Video ads","Wide searchbar"]}
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Axelen123** [comment]
Which Android version are you running?
Try moving ReVanced Manager from the SD card to internal storage.

**Comment by FlyByKnight23** [comment]
> Which Android version are you running? Try moving ReVanced Manager from the SD card to internal storage.

Android version 13

**Comment by FlyByKnight23** [comment]
> Did you grant ReVanced Manager root permissions?

I don't have a root app to do that

**Comment by oSumAtrIX** [comment]
I don't know why but you fail to execute AAPT:

<img width="401" alt="image" src="https://github.com/ReVanced/revanced-manager/assets/13122796/24175e00-267e-4000-96ce-97908f29a365">

**Comment by fillwithjoy1** [comment]
Same here, Android 14. Can't patch YouTube app at all

**Comment by FlyByKnight23** [comment]
> I don't know why but you fail to execute AAPT:
> 
> <img alt="image" width="401" src="https://private-user-images.githubusercontent.com/13122796/318945401-24175e00-267e-4000-96ce-97908f29a365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMTg3OTksIm5iZiI6MTcxMjExODQ5OSwicGF0aCI6Ii8xMzEyMjc5Ni8zMTg5NDU0MDEtMjQxNzVlMDAtMjY3ZS00MDAwLTk2Y2UtOTc5MDhmMjlhMzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA0MjgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YTU3ZmJlNWUxNmM3OTE1ZmRhNTBkYzAxZWVhNDUzNGU5NDE4NTU0ZTViY2NlZjJlZGJkZTY5YzA0YmEwMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LJn-qXYxUDDSVxAf5tV2trd4mR5xLPV1PQuBz_BF82I">

do you know how i can fix it?

**Comment by fillwithjoy1** [comment]
> > I don't know why but you fail to execute AAPT:
> > <img alt="image" width="401" src="https://private-user-images.githubusercontent.com/13122796/318945401-24175e00-267e-4000-96ce-97908f29a365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMTg3OTksIm5iZiI6MTcxMjExODQ5OSwicGF0aCI6Ii8xMzEyMjc5Ni8zMTg5NDU0MDEtMjQxNzVlMDAtMjY3ZS00MDAwLTk2Y2UtOTc5MDhmMjlhMzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA0MjgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YTU3ZmJlNWUxNmM3OTE1ZmRhNTBkYzAxZWVhNDUzNGU5NDE4NTU0ZTViY2NlZjJlZGJkZTY5YzA0YmEwMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LJn-qXYxUDDSVxAf5tV2trd4mR5xLPV1PQuBz_BF82I">
> 
> do you know how i can fix it?

I suspect it's something to do with revanced/revanced-patches as this problem exists even on an older version of revanced manager. Currently I cannot even patch YouTube with any patches using v4.6.0 of revanced-patches on the device.

**Comment by fillwithjoy1** [comment]
Did some more digging. It's actually revanced/revanced-patcher that's probably the culprit

This file seems like the culprit to look into https://github.com/ReVanced/revanced-patcher/blob/main/src/main/kotlin/app/revanced/patcher/data/ResourceContext.kt

**Comment by Axelen123** [comment]
> > I don't know why but you fail to execute AAPT:
> > 
> > <img alt="image" width="401" src="https://private-user-images.githubusercontent.com/13122796/318945401-24175e00-267e-4000-96ce-97908f29a365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMTg3OTksIm5iZiI6MTcxMjExODQ5OSwicGF0aCI6Ii8xMzEyMjc5Ni8zMTg5NDU0MDEtMjQxNzVlMDAtMjY3ZS00MDAwLTk2Y2UtOTc5MDhmMjlhMzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA0MjgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YTU3ZmJlNWUxNmM3OTE1ZmRhNTBkYzAxZWVhNDUzNGU5NDE4NTU0ZTViY2NlZjJlZGJkZTY5YzA0YmEwMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LJn-qXYxUDDSVxAf5tV2trd4mR5xLPV1PQuBz_BF82I">
> 
> do you know how i can fix it?

The /mnt/asec path tells me that you probably have installed manager to an sd card. Try moving it to internal storage like I said before.

**Comment by oSumAtrIX** [comment]
That's very likely the explanation and thus a duplicate

**Comment by fillwithjoy1** [comment]
But it's on internal storage

**Comment by oSumAtrIX** [comment]
Not according to OPs logs. If you need support move to one of our links at https://revanced.app

**Comment by FlyByKnight23** [comment]
> > > I don't know why but you fail to execute AAPT:
> > > <img alt="image" width="401" src="https://private-user-images.githubusercontent.com/13122796/318945401-24175e00-267e-4000-96ce-97908f29a365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMTg3OTksIm5iZiI6MTcxMjExODQ5OSwicGF0aCI6Ii8xMzEyMjc5Ni8zMTg5NDU0MDEtMjQxNzVlMDAtMjY3ZS00MDAwLTk2Y2UtOTc5MDhmMjlhMzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA0MjgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YTU3ZmJlNWUxNmM3OTE1ZmRhNTBkYzAxZWVhNDUzNGU5NDE4NTU0ZTViY2NlZjJlZGJkZTY5YzA0YmEwMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LJn-qXYxUDDSVxAf5tV2trd4mR5xLPV1PQuBz_BF82I">
> > 
> > 
> > do you know how i can fix it?
> 
> The /mnt/asec path tells me that you probably have installed manager to an sd card. Try moving it to internal storage like I said before.

I moved it to internal and I'm still having the same issue. I should also note that ive already disabled play protect

**Comment by oSumAtrIX** [comment]
If you get the same error message, you have not moved it away from the sdcard.

**Comment by FlyByKnight23** [comment]
Since posting this, I've tried patching YouTube with Revanced on Internal and External Storage, and YouTube installed and uninstalled. This is the latest result of having Revanced on Internal Storage and YouTube installed:

![Screenshot_20240403_123735_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/119979024/c39d517f-073c-473e-a1a8-fb01fa0bff01)
![Screenshot_20240403_123739_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/119979024/9d541e0e-d8e9-449a-af7b-5d44e395b27e)

**Comment by oSumAtrIX** [comment]
You do not have enough space.

**Comment by FlyByKnight23** [comment]
> If you get the same error message, you have not moved it away from the sdcard.

I do have it in internal storage

![Screenshot_20240403_124024_Settings](https://github.com/ReVanced/revanced-manager/assets/119979024/ec36ee7c-51fe-4c6c-804d-bd785bbfc560)

**Comment by oSumAtrIX** [comment]
You did not get the same error message therefore

**Comment by FlyByKnight23** [comment]
I managed to patch Youtube. From what I can tell, it was a space issue. The only thing I did differently between attempts was uninstall some apps and delete some old files.
