### ISSUE TITLE
feat: Please make videos with quality of 720p or over downloadable without YouTube premium

### ISSUE THREAD

**Issue by ImperialStranger** [ReVanced/revanced-manager#1827]
### Feature description

Revanced Manager can modify original YouTube to a great extent. But when I try to download a YouTube video with quality of 720p or over on modified YouTube it still requires purchasing YouTube premium.
My request is to add a feature to modify YouTube which can make YouTube download videos with quality of 720p or over without YouTube premium 
![Screenshot_2024-04-02-19-57-08-36_64ef5fc2000c1caa954c114bb372e1d5](https://github.com/ReVanced/revanced-manager/assets/34884277/8c584c13-a2e1-4352-8a36-7f3988e123cd)

### Motivation

I think that paying for YouTube premium just for higher quality video downloads makes no sense. It's just a waste of money. Moreover some videos require to be watched at higher quality for better understanding. Specially keeping 720p behind paywall is sign of excessive money hunger.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
External downloads patch exists already which can do that
