### ISSUE TITLE
bug: DontKillMyApp webpage opens everytime I try to open YouTube Music

### ISSUE THREAD

**Issue by Straxan** [ReVanced/revanced-manager#1829]
### Bug description

I had to rebuild YouTube Music ReVanced due to crashing. Now when I try to open the app, it opens a new tab in my mobile browser and spams the DontKillMyApp page. My brand of phone (Honor) is not supported on that site and I can't access the app because it demands that I follow non-existent instructions.

I have adjusted the battery-saving options available to me, but the page still opens. A toast message also gets spammed on the YouTube app for this same issue.

I'm looking to be able to remove this popup and webpage, as the ReVanced apps have work perfectly fine on my device until now. 

### Version of ReVanced Manager and version & name of app you are patching

ReVanced Manager: 1.18.0
YouTube Music: v6.44.54
YouTube: v19.09.37

### Installation method

Regular

### ReVanced Manager logs

```shell
--------- beginning of main
04-02 20:43:54.785 25976 25976 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
04-02 20:43:54.819 25976 25990 E BehaviorCollectManager: Fail to acquire dataAnalyzerService...
04-02 20:43:54.843 25976 25996 E AwareLog: AtomicFileUtils: readFileLines file not exist: AtomicFile[/data/user/0/app.revanced.manager.flutter/files/hw_cached_resid.list]
04-02 20:43:54.861 25976 26001 E GamesAware: isInSupportList 'app.revanced.manager.flutter' is a game? no; or product supported? no
04-02 20:43:54.861 25976 26001 E manager.flutter: open file error
04-02 20:43:55.003 25976 25999 E OpenGLRenderer: Unable to match the desired swap behavior.
04-02 20:44:58.420 25976 25999 E OpenGLRenderer: Unable to match the desired swap behavior.
04-02 20:45:55.043 25976 25999 E OpenGLRenderer: Unable to match the desired swap behavior.
04-02 20:46:37.702 25976 25999 E OpenGLRenderer: Unable to match the desired swap behavior.
04-02 20:47:14.322 25976 25999 E OpenGLRenderer: Unable to match the desired swap behavior.
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [ ] The bug is only related to ReVanced Manager

**Comment by validcube** [comment]
Honor are basically the same device
