### ISSUE TITLE
bug: Can't Sign Apk after patch 

### ISSUE THREAD

**Issue by cyberastr4l** [ReVanced/revanced-manager#1835]
### Bug description

I installed a CI version and had to disable multithread patch for me to be able to patch the classes.dex due to memory problems. I passed that and the apk couldn't be signed. The error log can be viewed in the image below as on the exported log it would only go up to the INFO Signing Apk and would show the error. 
![Screenshot_20240314_203841_ReVanced Manager Debug](https://github.com/ReVanced/revanced-manager/assets/140955525/bb18d77b-ccae-4a29-8669-5d8c2a0744e5)

### Version of ReVanced Manager and version & name of app you are patching

CI version 0.0.1

### Installation method

None

### ReVanced Manager logs

```shell
Log couldn't be exported with the error as described above.
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Axelen123** [comment]
Turns out this has nothing to do with apkzlib and was caused by Compose Manager's incorrect usage of `PatcherResult.applyTo`.

The issue has been fixed in https://github.com/ReVanced/revanced-manager/commit/ce134224a819df9d464f899871cebd2b03a83c7c
