### ISSUE TITLE
feat: Improve the language update settings

### ISSUE THREAD

**Issue by lamnhan066** [ReVanced/revanced-manager#1837]
### Feature description

There is a TODO in this file:
https://github.com/ReVanced/revanced-manager/blob/e80ee098930a70bb3ddd6d8cf293adf917eb95f1/lib/ui/views/settings/settingsFragment/settings_update_language.dart#L66
I can update this file to make it clearer and more readable.

You can take a look at [this file](https://github.com/lamnhan066/revanced-manager/blob/improve-language-updating/lib/ui/views/settings/settingsFragment/settings_update_language.dart) and [this diff](https://github.com/ReVanced/revanced-manager/compare/dev...lamnhan066:revanced-manager:improve-language-updating) to see how it will be implemented.

Here is the final look:

https://github.com/ReVanced/revanced-manager/assets/91940731/1a8eea66-efcf-47d8-a3ea-649fd8286c09

### Motivation

As a package `language_code` maintainer, I can update the `language_code` and this file at the same time to make it consistent.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by validcube** [comment]
🥞 This issue have been closed as associated PR have been merged, feel free to reopen.
* #1838 

###### Usually GitHub would automatically close this.
