### ISSUE TITLE
feat: ability to add custom keystore

### ISSUE THREAD

**Issue by rollingmoai** [revanced/revanced-manager#184]
### Type

Other

### Branch

Flutter

### Bug description

Cannot upgrade or reinstall YouTube ReVanced when repatching

### Steps to reproduce

1. Patch and install YouTube ReVanced
2. Repatch YouTube ReVanced and reinstall
3. reinstallation fails

### Relevant log output

```shell
‎
```

### Solution

Make upgrades and reinstallations work

**Comment by ponces** [comment]
Did you clean Manager's cache or uninstalled it between the first time you patched it and that repatch attempt?

**Comment by rollingmoai** [comment]
> uninstalled it between the first time you patched it and that repatch attempt?

No. I want to reinstall the app without uninstalling it because that would lose my data.

**Comment by ponces** [comment]
I mean, if you made that. I'm not saying as a suggestion...
Repatching and reinstalls are possible with manager if the keystore which is used to sign apps after patching is preserved between updates.

**Comment by rollingmoai** [comment]
Ok, so how do I do that? How do I add my own keystore so it is the same for all devices that I install?

**Comment by ponces** [comment]
Currently, you can't but it's a planned feature.

**Comment by Aunali321** [comment]
Closing in favour of #263.
