### ISSUE TITLE
feat: Use system MicroG instead of ReVanced MicroG 

### ISSUE THREAD

**Issue by MrNessuno** [ReVanced/revanced-manager#1858]
### Feature description

I already use microG system wide with lineage with microG so installing microG again is a duplicate thing for me.

### Motivation

2 microG apps installed 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
Not possible, system MicroG checks signatures, and patched apps don't pass the checks

**Comment by nikmax42** [comment]
> Not possible, system MicroG checks signatures, and patched apps don't pass the checks

What microG / GmsCore support patch does? Is it not for that?

**Comment by itsmartashub** [comment]
If your device is **rooted** in any case and has installed original [gmsCore](https://github.com/microg/GmsCore) (with package name `com.google.android.gms`), you could try to patch it **without** `GmsCore support` patch enabled, and install it with `Mount` (root) option.

At least it works for me on another AOSP ROM.
I have installed and microG's `com.android.vending` app. Idk if that matters too for this to work

**Comment by oSumAtrIX** [comment]
> What microG / GmsCore support patch does? Is it not for that?

The patch changes the app to make it use a GMS package with the package name specified in the patch option.

**Comment by nikmax42** [comment]
> If your device is **rooted** in any case and has installed original [gmsCore](https://github.com/microg/GmsCore) (with package name `com.google.android.gms`), you could try to patch it **without** `GmsCore support` patch enabled, and install it with `Mount` (root) option.
> 
> At least it works for me on another AOSP ROM. I have installed and microG's `com.android.vending` app. Idk if that matters too for this to work

Thanks for the reply! You are right. I've already figured it out, thanks to the [guide from XDA](https://xdaforums.com/t/app-guides-unofficial-revanced-megathread.4523967/post-87930367)
