### ISSUE TITLE
bug: when i tab on blue colored text in changelog nothing happens

### ISSUE THREAD

**Issue by kotenok2000** [ReVanced/revanced-manager#1862]
### Bug description

I expect blue text to be link.
When i tap on blue text in changelog nothing happens.

### Version of ReVanced Manager and version & name of app you are patching

Manager version 1.20.1

### Installation method

Regular

### ReVanced Manager logs
[revanced-manager_logcat_20240409170239473003.log](https://github.com/ReVanced/revanced-manager/files/14919551/revanced-manager_logcat_20240409170239473003.log)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by kotenok2000** [comment]
[revanced-manager_logcat_20240409170239473003.log](https://github.com/ReVanced/revanced-manager/files/14919551/revanced-manager_logcat_20240409170239473003.log)

**Comment by Aunali321** [comment]
Fixed in https://github.com/ReVanced/revanced-manager/commit/bc300d81d9490e718cb024145dba4a19af5619ce
