### ISSUE TITLE
bug: patched tiktok can't login via Twitter

### ISSUE THREAD

**Issue by KamiyaMinoru** [ReVanced/revanced-manager#1866]
### Bug description

patched Tiktok with assigned version 32.5.3 via updated (1.2) revanced manager
1. Seems Hanging during installed
2. Anyway installed, by export APK to install

→ 3. The real problem is this version of Tiktok do not allow Twitter API login ←

### Version of ReVanced Manager and version & name of app you are patching

Revanced manager 1.2
Tiktok 32.5.3

### Installation method

None

### ReVanced Manager logs

```shell
not applicable
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [ ] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
Either an issue with TikTok, as reported online or an artifact from patching similar to Google login. Test the unpatched app.

**Comment by KamiyaMinoru** [comment]
I guess this is because twitter turned to X
Anyway I log-in with unpatched Tiktok, thanks.

oSumAtrIX ***@***.***> 於 2024年4月14日 週日 上午8:03寫道：

**Comment by oSumAtrIX** [comment]
Check the same version as you patch

**Comment by oSumAtrIX** [comment]
Wrong repository, open an issue with the requested information in the patches repo
