### ISSUE TITLE
feat: Check the URL before setting Alternative Sources

### ISSUE THREAD

**Issue by validcube** [ReVanced/revanced-manager#1868]
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/validcube/validcube/main/assets/ReVancedManager/dynamic-dark.webp">
  <img alt="" src="https://raw.githubusercontent.com/validcube/validcube/main/assets/ReVancedManager/dynamic-light.webp">
</picture>

## 😊 Issue
Alternative Sources needs to check if the repository is accessible or is properly configured or not.

> [!NOTE]
> The design is made for **ReVancie☆Managerie☆Weberie!** (Lotus Iteration 1), might not consistent with Flutter manager.
> In the context of ReVanced Manager Flutter, the feature need to check if the GitHub repository is accessible or not.

![image](https://github.com/ReVanced/revanced-manager/assets/93124920/237c1369-4e6d-47c0-ab11-cf48d614e669)

https://www.figma.com/file/hvgC1Mu2srypqC4EfaXDDL/(General-Public)-ReVancie%E2%98%86Managerie%E2%98%86Weberie!?type=design&node-id=0%3A1&mode=design&t=FV7iQ4k1iPUc5cVl-1

> [!TIP]
> There are additional comments about Alternative Sources
> @ **(Lesser General Public) ReVancie☆Managerie☆Weberie!** (Lotus Iteration 1)

**Comment by oSumAtrIX** [comment]
Test URL could be a button somewhere on the dialog next to an Ok button. It should not prevent the user from setting that custom source. What can be done is, to check if it's working after clicking okay or whenever the app tries to contact it, so the user sees a dialog that the repo doesn't exist
