### ISSUE TITLE
Check this bug

### ISSUE THREAD

**Issue by venkat2305** [revanced/revanced-manager#187]
It shows multiple times for a single app

![Screenshot_2022-09-18-13-57-58-207_app.revanced.manager.flutter.jpg](https://user-images.githubusercontent.com/55329452/190893313-b3cbcd24-32f9-4f9c-a63f-857509e1c8a2.jpg)

![Screenshot_2022-09-18-13-57-54-872_app.revanced.manager.flutter.jpg](https://user-images.githubusercontent.com/55329452/190893317-e2b9cf43-ca44-4193-a8cb-4d0818387db2.jpg)

**Comment by pietryszak** [comment]
Manager version ?

**Comment by harry590** [comment]
> It shows multiple times for a single app
> 
> ![Screenshot_2022-09-18-13-57-58-207_app.revanced.manager.flutter.jpg](https://user-images.githubusercontent.com/55329452/190893313-b3cbcd24-32f9-4f9c-a63f-857509e1c8a2.jpg)
> 
> ![Screenshot_2022-09-18-13-57-54-872_app.revanced.manager.flutter.jpg](https://user-images.githubusercontent.com/55329452/190893317-e2b9cf43-ca44-4193-a8cb-4d0818387db2.jpg)
> 
> 
> 

Reinstall or clear data it will get solved

**Comment by venkat2305** [comment]
> Manager version ?

0.0.13

**Comment by venkat2305** [comment]
> Reinstall or clear data it will get solved

It's solved for now. I hope they fix this so it doesn't occur in the first place
