### ISSUE TITLE
bug: Apps disappeared!

### ISSUE THREAD

**Issue by xinos89** [ReVanced/revanced-manager#1872]
### Bug description

https://github.com/ReVanced/revanced-manager/assets/33432716/54b6104a-de29-47c5-9bff-66dccc571355
----
After installing revanced and patching three apps or four, all the apps disappeared, it shows up after restarting the device (Motorola g14), and after a while I notice that the apps disappeared without a certain action. I tried opening revanced after restart and the apps didn't disappear, I tried opening YouTube also nothing happened!, But after a while the apps disappear! Any clues or tests or logs you need ?
Android v13 
Build number: TLBS33.78-180-1-3
![Screenshot_20240419-022903](https://github.com/ReVanced/revanced-manager/assets/33432716/c178c9c2-debd-4328-838e-bb47eeaa3846)
[revanced-manager_logcat_20240419024923464489.log](https://github.com/ReVanced/revanced-manager/files/15031481/revanced-manager_logcat_20240419024923464489.log)

### Version of ReVanced Manager and version & name of app you are patching

Version: 1.20.1
Model: moto g14
Android Version: 13
Supported Archs: arm64-v8a, armeabi-v7a, armeabi

### Installation method

None

### ReVanced Manager logs

```shell
Attached!
```

### Patch logs

```shell
I don't know where to find or to export this!
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by xinos89** [comment]
https://github.com/ReVanced/revanced-manager/assets/33432716/4f717a36-e3fa-4bfa-93e5-6ef23901e4b1

**Comment by oSumAtrIX** [comment]
Did you uninstall ReVanced Manager after installing the patched apps?

**Comment by xinos89** [comment]
No, I didn't!

**Comment by oSumAtrIX** [comment]
Reinstall ReVanced Manager and check if the issue still occurs

**Comment by xinos89** [comment]
I did reinstall (without uninstalling), but nothing happened!

**Comment by oSumAtrIX** [comment]
Add a complete recording of the following steps:

1. Uninstall ReVanced Manager
2. Install ReVanced Manager
3. Patch an app
4. Show its missing in ReVanced Manager

**Comment by xinos89** [comment]
Bro! The issue which bothers me not it is not showing in revanced manager!
It is just symptoms, the main issue that my original apps disappeared! And
it appears after restarting the phone like just now! I restarted the phone
for this apps to appear.

**Comment by oSumAtrIX** [comment]
If your apps disappear then your system is at fault and not ReVanced Manager. Otherwise include the recording as requested

**Comment by xinos89** [comment]
> VID-20240419-WA0000.mp4

@oSumAtrIX Bro this is the recording.. I cut some for the size but it still shows the issue.

**Comment by oSumAtrIX** [comment]
ReVanced is not at fault here. You can export the app after patching and install it manually as well and debug your system error.

**Comment by aaronaan** [comment]
![Image](https://github.com/user-attachments/assets/80441f71-9f97-4004-887e-66d9411df8bf)
![Image](https://github.com/user-attachments/assets/5fc15e59-0f0d-470d-86b7-5200381c67ac)
![Image](https://github.com/user-attachments/assets/7766b1f6-541f-4bed-98bf-137845ac0f6c)

I have the same bug.
App disappears after 3-4 days

If i type youtube into playstore it says "update" and "deinstall" but app is no where to find in the drawer. 

[revanced-manager_logcat_20251229215420527436.log](https://github.com/user-attachments/files/24374463/revanced-manager_logcat_20251229215420527436.log)
