### ISSUE TITLE
bug: Manager shows magnified view while nothing is typed

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-manager#1876]
### Bug description

When nothing is typed, the manager search or type-in boxes shouldn't show the magnified view of what's written, especially when it's blank.
![Screenshot_20240421_205201_ReVanced Manager](https://github.com/ReVanced/revanced-manager/assets/117499019/b3760650-a1c4-47d2-ad9a-44d0b1ee203d)

This issue is consistent throughout the manager UI.

### Version of ReVanced Manager and version & name of app you are patching

v1.20.1

### Installation method

Regular

### ReVanced Manager logs

```shell
Nil
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
This is more like an issue with the components library we are using than with ReVanced Manager itself. As such, it would be worth reporting this to them.

**Comment by ILoveOpenSourceApplications** [comment]
Will someone from the ReVanced team report this or should I do it?

**Comment by oSumAtrIX** [comment]
I meant the UI library, not ReVanced Library. It would be nice if you could report it.

**Comment by ILoveOpenSourceApplications** [comment]
Sure. Do you mind pointing me to where I should report it then?

**Comment by oSumAtrIX** [comment]
I am not sure myself. But I am sure that the magnifier is part of the implementation of the UI library used by ReVanced Manager. Possibly, @Aunali321 or @BenjaminHalko could identify which library

**Comment by validcube** [comment]
> I am not sure myself. But I am sure that the magnifier is part of the implementation of the UI library used by ReVanced Manager. Possibly, @Aunali321 or @BenjaminHalko could identify which library

The UI is from Flutter itself which can be disabled.

**Comment by oSumAtrIX** [comment]
In that case the issue should be reported to Flutter
