### ISSUE TITLE
bug: Can't accept or refuse cookies

### ISSUE THREAD

**Issue by Skuidius** [ReVanced/revanced-manager#1882]
### Bug description

Hello, I rarely use GitHub, I hope this is the correct place to ask, excuse me if I am wrong...
I installed the last manager version (1.20.1) and used the recommended Youtube APK (19.11.43). The app starts with no problem and it asks me to accept all cookies or deny them all. I can't click any of these. I tried everything, it's been hours now. I tried older versions, nothing works.
When I start the youtube app with no internet connection, I can access the youtube app and settings without having the cookies pop-up, but as soon as I enable internet, it asks for the cookies and I can't click anything...

Thank you if any of you can help for this <3

![Screenshot_20240426-161930](https://github.com/ReVanced/revanced-manager/assets/76495936/86735d24-289a-4a5d-99e7-bc204298c0fb)
![Screenshot_20240426-161934](https://github.com/ReVanced/revanced-manager/assets/76495936/8c874d5e-ca45-4364-a360-22a41b38f2fd)

### Version of ReVanced Manager and version & name of app you are patching

Revanced manager : 1.20.1
Youtube app : 19.11.43

### Installation method

None

### ReVanced Manager logs

```shell
--------- beginning of main
04-26 16:22:20.006  8192  8192 E BpSurfaceComposerClient: Failed to transact (-1)
04-26 16:22:20.006  8192  8192 E BpSurfaceComposerClient: Failed to transact (-1)
04-26 16:22:41.706  8192  8192 E BpSurfaceComposerClient: Failed to transact (-1)
04-26 16:22:41.706  8192  8192 E BpSurfaceComposerClient: Failed to transact (-1)
```

### Patch logs

```shell
Nothing here sorry.
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
Signing into GmsCore should prevent the popup. Apart from that it's an issue with YouTube itself. This repository is for ReVanced Manager as you have knowingly ticked.

For ReVanced support, move to one of our links at https://revanced.app.

**Comment by Skuidius** [comment]
Thank you very much for your quick answer mate. I feel bad / stupid for asking here.
This was probably due to GmsCore that wasn't connected indeed or maybe because Google Chrome and a few google apps weren't updated. I think it might have a link because of the web popup for the cookies that might be handled by chrome.
Sorry if what I say isn't really clear, I'm french and my english isn't perfect. I just wanna help! 

Have a good day, thank you again...
