### ISSUE TITLE
Publication of ReVanced Manager on F-Droid

### ISSUE THREAD

**Issue by mikebrusko** [ReVanced/revanced-manager#1885]
### Feature description

Hello. You can publish a ReVanced Manager on F-Droid? This is a large store of free and open source applications.

### Motivation

It is a large open source app store. And it's free. Revanced will become more popular, f-droid is loved for application security, it is popular.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-manager/issues/1708
