### ISSUE TITLE
bug: Pressing Suggested App Version Opens Wrong Browser

### ISSUE THREAD

**Issue by WesternGamer** [ReVanced/revanced-manager#1893]
### Bug description

Pressing the suggested app version button will open the device's default system browser instead of the default browser that the user selected in settings. 

In my case when pressing the button on a Samsung device, it opens Samsung Internet instead of Google Chrome, which is the default browser I selected. 

Image to show what button I am referring to: 
![image](https://github.com/ReVanced/revanced-manager/assets/80211714/bccde919-ae74-4c65-a4ad-1e6f6b264e1b)

[revanced-manager_logcat_20240501141543233805.log](https://github.com/ReVanced/revanced-manager/files/15179870/revanced-manager_logcat_20240501141543233805.log)

### Version of ReVanced Manager and version & name of app you are patching

Manager Version: 1.20.1
Name of app getting patched: N/A as this is an issue with the manager itself.

### Installation method

Regular

### ReVanced Manager logs

```shell
See attached file.
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
It doesn't open wrong one, it starts a query, the rest is handled by your OS. For support, move to one of our links at https://revanced.app.
