### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by rthfhgyhy567** [ReVanced/revanced-manager#1894]
### Bug description

The following patches dont seem like they are working:

- Hide 'get music premium' label
- remove upgrade button

Also I am seeing a full screen ad for premium occasionally as well.

### Version of ReVanced Manager and version & name of app you are patching

revanced: 1.20.1
YT Music: 6.47.50

### Installation method

Regular

### ReVanced Manager logs

```shell
https://pastebin.com/mF2jgYFb
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [ ] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [ ] The bug is only related to ReVanced Manager

**Comment by rthfhgyhy567** [comment]
![Screenshot_20240501_190803_YouTube Music](https://github.com/ReVanced/revanced-manager/assets/104237805/28bb30ec-7f0a-4254-9ee9-e681252a8f04)
![Screenshot_20240429_131415_YouTube Music](https://github.com/ReVanced/revanced-manager/assets/104237805/bfe53e85-740c-4ea0-adaa-fc20834f43b8)
![Screenshot_20240421_120415_YouTube Music](https://github.com/ReVanced/revanced-manager/assets/104237805/df72a506-41d3-4720-a113-3620f0f3042a)

**Comment by rthfhgyhy567** [comment]
Wtf?  Closed as NOT PLANNED?  Its a bug for christ sake.  If you are looking for reasons to not fix bugs then you should get out of the software industry.

**Comment by oSumAtrIX** [comment]
Acknowledgements not met.
