### ISSUE TITLE
bug: Patched YouTube v19.11.43 (recommended) Can't play videos. Videos getting stuck after 1sec of playing. 

### ISSUE THREAD

**Issue by sid308** [ReVanced/revanced-manager#1898]
### Bug description

So recently reser my phone and got Vanced Manager for patching youtube. But after patching videos are not playing further than 1 second. I also tried on my friend's phone but had the same problem 

### Version of ReVanced Manager and version & name of app you are patching

Manager: v1.20.1
YT: v19.11.43

### Installation method

Regular

### ReVanced Manager logs

```shell
--------- beginning of main
05-06 13:12:33.519 11103 11103 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
05-06 13:12:33.661 11103 11124 E OpenGLRenderer: Unable to match the desired swap behavior.
--------- beginning of kernel
05-06 13:12:30.566 11143 11143 E audit   : rate limit exceeded
05-06 13:12:37.289 12348 12348 E audit   : rate limit exceeded
05-06 13:13:06.011 11103 11124 E OpenGLRenderer: Unable to match the desired swap behavior.
05-06 13:13:58.947 11103 11124 E OpenGLRenderer: Unable to match the desired swap behavior.
05-06 13:14:27.543 11103 11124 E OpenGLRenderer: Unable to match the desired swap behavior.
05-06 13:15:30.689 11103 11124 E OpenGLRenderer: Unable to match the desired swap behavior.
05-06 13:15:57.234 11103 11132 E libEGL  : call to OpenGL ES API with no current context (logged once per thread)
05-06 13:16:11.861 14507 14507 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
05-06 13:16:11.961 14507 14527 E OpenGLRenderer: Unable to match the desired swap behavior.
05-06 13:16:08.850 14547 14547 E audit   : rate limit exceeded
05-06 13:16:28.320 14507 14527 E OpenGLRenderer: Unable to match the desired swap behavior.
05-06 13:17:51.084 16598 16598 E audit   : rate limit exceeded
05-06 13:18:01.977 16931 16931 E audit   : rate limit exceeded
05-06 13:24:15.880 20719 20719 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
05-06 13:24:15.969 20719 20741 E OpenGLRenderer: Unable to match the desired swap behavior.
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by validcube** [comment]
👋 Hello, @sid308!

Thanks for filing this issue, but however this issue is out-of-scope for this repository (ReVanced Manager), the correct repository to file this issue in would be our [ReVanced Patches repository](https://github.com/ReVanced/revanced-patches).

##### Check your Acknowledgement list, if this look wrong, feels free to let's me know and I'll reopen it for you!
