### ISSUE TITLE
0.0.13 Grey screen after successful patch

### ISSUE THREAD

**Issue by pietryszak** [revanced/revanced-manager#190]
### Type

Error at runtime

### Branch

Flutter

### Bug description

After successful patch and install Yt vanced created by 0.0.13 only gray screen is visible and not working.

### Steps to reproduce

1) Download 0.0.13
2) Use all patch except debugging. Yt 17. 36.37
3) Install patched app and open it
4) Gray screen

### Relevant log output

```shell
.
```

### Screenshots or videos

![Screenshot_20220918-105556](https://user-images.githubusercontent.com/45850093/190894080-10755f5c-72a0-481b-afbc-5fd0a1516122.jpg)

### Additional context

Android 12
Microg installed 
Samsung S21 fe

**Comment by Aunali321** [comment]
Use full apk from apkmirror. You're using split.

**Comment by pietryszak** [comment]
> Use full apk from apkmirror. You're using split.

Nope. I use the same app like before. Full APK from APK mirror. With 0.0.7 works everything fine

**Comment by Aunali321** [comment]
Need logs

**Comment by pietryszak** [comment]
My mistake. A recommended version change from 17.33 to 17.36.
With recommended version all works fine
