### ISSUE TITLE
bug: root install not working after patching apk

### ISSUE THREAD

**Issue by thecodymetalist** [revanced/revanced-manager#191]
### Type

Error while running the manager

### Branch

Flutter 0.0.13

### Bug description

Root install not working

### Steps to reproduce

Select Twitter apk
Patch
after successful patching
Press root install

### Relevant log output

```shell
Log output attached to additional context because of exceeds maximum body of 65536 chars.
```

### Screenshots or videos

![Screenshot_2022-09-18-11-58-12-655_app revanced manager flutter](https://user-images.githubusercontent.com/3031096/190894234-136327bd-09b9-4b1b-a1e5-869fb18cf69d.png)

### Solution

.

### Additional context

Also didn't find patched apk in any folder. So I had to patch and install again from the beginning. Can we export patched apk somehow?

[revanced-manager_logcat_20220918115937104075.log](https://github.com/revanced/revanced-manager/files/9593488/revanced-manager_logcat_20220918115937104075.log)

**Comment by joseph-20** [comment]
Same issue here, I'm patching YouTube v17.36.37 and root install just doesn't do anything.

Pressing on root install makes you wait just like before but then opening YouTube shows that nothing changed, and it's not a matter of patches failing to apply because if I install the patched apk in nonroot mode it works (and YouTube crashes too so there's something wrong in the updated patches too)

**Comment by AndryOut** [comment]
> Same issue here, I'm patching YouTube v17.36.37 and root install just doesn't do anything.
> 
> Pressing on root install makes you wait just like before but then opening YouTube shows that nothing changed, and it's not a matter of patches failing to apply because if I install the patched apk in nonroot mode it works (and YouTube crashes too so there's something wrong in the updated patches too)

I had problems with version 17.36.37, gray screen or crash. Then out of curiosity I tried to use the version 17.33.42 And it worked properly without any problems

**Comment by joseph-20** [comment]
ReVanced Manager v0.0.12 is able to successfully patch and root install Youtube v.17.36.37, so something broke in 0.0.13

**Comment by NextGenOP** [comment]
Same here, can't install the patched apps, so I copy the patched apk. But don't know how to install it manually

**Comment by Jnss98b** [comment]
I was able to patch twitter 9.62.0-release.0 with v0.0.28 but twitter crashes a few seconds after opening

**Comment by ILoveOpenSourceApplications** [comment]
Looks like an issue which existed with older versions of manager. So closing it.
