### ISSUE TITLE
feat: add `ripLibs` settings

### ISSUE THREAD

**Issue by kazimmt** [ReVanced/revanced-manager#1913]
### Feature description

In ReVanced Manager, the `ripLibs` feature can be accessed through the settings menu. Users can select which libraries to remove during the patching process. The interface is designed to be user-friendly, allowing even those with limited technical knowledge to take advantage of this powerful tool.

### Motivation

The addition of `ripLibs` in ReVanced Manager significantly enhances the app’s functionality by providing users with a way to remove unnecessary libraries. This results in more efficient, secure, and customized apps, aligning with ReVanced Manager’s goal of empowering users to take full control over their app experiences.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by KobeW50** [comment]
https://github.com/ReVanced/revanced-manager/issues/1666

**Comment by kazimmt** [comment]
> #1666

I've searched for ripLib & didn't found it :(

**Comment by oSumAtrIX** [comment]
Removing libraries is not ReVanced Managers job. ReVanced Manager handles executing the patcher and repacking repacking the app patched app. If you don't want libs, remove them from the APK prior patching or a patch can do it.
