### ISSUE TITLE
feat: Integrate `SafetyNet` and `PlayIntegrity` check

### ISSUE THREAD

**Issue by cyberboh** [ReVanced/revanced-manager#1915]
### Feature description

After recent changes were made by Google, as revanced user there is an impact like buffering issue, even it's not a part by A/B testing in the past. The problem is device is not pass SafetyNett and PlayIntegrity. Then they blame revanced for that or even spamming bug report about buffering issue.

So, from now on, passing SafetyNet and PlayIntegrity is a must. For this case I'd like to request to devs about to:
1. Add SafetyNet and PlayIntegrity check on app start-up. User can deactivate check after that on settings.
2. If the check are passing, users can continue patching revanced otherwise warn the users to passing SafetyNet and PlayIntegrity first.
3. Add manually check for SafetyNet and PlayIntegrity in settings, it will simplify users without download any other apps for manually checking

### Motivation

*Why should this feature be implemented?*
To simplify users to check SafetyNet and PlayIntegrity. 

*What is the explicit use case?*
Checking SafetyNet and PlayIntegrity from the manager

*What are the benefits?*
Minimilize the bugs caused by SafetyNet and PlayIntegrity if they are broken

*What makes this feature important?*
To use revanced,SafetyNet and PlayIntegrity passing is a must

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [ ] The feature request is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
ReVanced Manager is agnostic to patches or specific scenarios to YouTube.
