### ISSUE TITLE
feat: "Search button" in YouTube Channel 

### ISSUE THREAD

**Issue by sid24op** [ReVanced/revanced-manager#1922]
### Feature description

Please add " Search on Channel" option which is already there in desktop version only.
When we search on that, it shows results only from the channel contents. Check the screenshot 
![Screenshot_20240529_133443](https://github.com/ReVanced/revanced-manager/assets/98143336/a6c63c84-3c38-4f6d-9170-4a849973e8a3)

### Motivation

When we really like some channel, we try to watch more vudeos made by the same channel. And when we want to search specific title on their channel it becomes easy. On the normal search bar it will show multiple results 

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
![Screenshot_20240529-120308](https://github.com/ReVanced/revanced-manager/assets/13122796/dd0a2ca7-578b-45fa-a96c-09a195f60368)

Regular search works good enough for that purpose
