### ISSUE TITLE
Add VirusTotal scan link and SHA256 checksum on release tab

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-manager#193]
### Type

Other

### Branch

Doesnt matter

### Issue

Now we have no way to ensure the file is intact
The file will be downloaded and scanned on virustotal already

### Feature

Checksums like SHA256, SHA1 can verify file integrity
Having a link for virustotal can be convenient for us

### Motivation

To ensure the file is intact
To provide third-party virus analysis for worried users (more easily), enhancing trust

### Additional context

I remember theres a github action to submit to VT

**Comment by Canny1913** [comment]
VirusTotal is not reliable for APK virus detection.

**Comment by SodaWithoutSparkles** [comment]
Better than nothing. At least I havent found a way to use hatching triage automatically.

**Comment by Canny1913** [comment]
It's not better than nothing because it's misleading

**Comment by Aunali321** [comment]
No need. Everything is open source. And virustotal is not reliable for apk.

**Comment by SodaWithoutSparkles** [comment]
how about checksums?
