### ISSUE TITLE
Supports Tiktok latest versions

### ISSUE THREAD

**Issue by Monvey0** [ReVanced/revanced-manager#1939]
### Feature description

From version 34.9.5 beta and above tiktok supports Dark mode for android, it's still in testing phase and it always appears and disappears, it will be nice if the team can_ support the latest versions with revanced patches and force "dark mode" option to be always there

### Motivation

Tiktok one of fews apps that doesn't supports dark mode on android

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [ ] The feature request is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
Acknowledgements not met
