### ISSUE TITLE
bug: don't work for android 14. 

### ISSUE THREAD

**Issue by T43D0c70r** [ReVanced/revanced-manager#1940]
### Bug description

Patched apk don't Play 

### Version of ReVanced Manager and version & name of app you are patching

YouTube v. 19.11.43

### Installation method

Regular

### ReVanced Manager logs

```shell
https://quickshare.samsungcloud.com/eby8G0YAYD1n
```

### Patch logs

```shell
https://quickshare.samsungcloud.com/eby8G0YAYD1n
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [ ] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
Provide all requested information correctly.

**Comment by T43D0c70r** [comment]
It doesn't work on Android 14. No matter which version I try, it's not good. It stops in 10 seconds, for sure. Please correct

Androidos Outlookból<https://aka.ms/AAb9ysg> küldve
________________________________
