### ISSUE TITLE
bug: Strange wording in updates popup 

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1956]
### Bug description

This should be simplified to something like "Do you want ReVanced Manager to periodically check for updates for the following components? "

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/d9111e69-f050-4507-8d20-a871dc7e15d3)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Ushie** [comment]
What do you think about "Choose your update preferences" for the title?

**Comment by oSumAtrIX** [comment]
Maybe "Configure updates"?
