### ISSUE TITLE
bug: Battery optimization notice in wrong place

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1964]
### Bug description

The notice should be on the home screen not hidden in the settings:

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/45e29aea-e295-4066-b443-e17fc0b976d0)

Ideally the user is never asked to enter the settings, and right now they have to.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Axelen123** [comment]
Apps can request to turn off battery optimizations without going through settings in newer versions of Android but I don't think its avoidable for older versions.
