### ISSUE TITLE
bug: Split downloads presented as a feature

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1969]
### Bug description

Splits are not a supported concept yet therefore this toggle should not be present:

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/5d74a6db-25e4-437b-b00f-7b76c4bf8637)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Axelen123** [comment]
Resolved in downloader plugin branch.
