### ISSUE TITLE
bug: Clicking on "Reset patch options" does nothing

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1970]
### Bug description

The same issue applies to all other settings in that screen.

https://github.com/ReVanced/revanced-manager/assets/13122796/eef24852-006f-403c-87c4-0e270771b367

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Ushie** [comment]
Do you mean they do not function as intended? or the fact they provide no feedback on interaction?

**Comment by oSumAtrIX** [comment]
I believe both. Note I have not patched any app yet. may be related.

**Comment by Axelen123** [comment]
Everything on that page has click handlers. This issue should be closed or renamed.

**Comment by Wuttachai29** [comment]
https://github.com/ReVanced/revanced-manager/issues/1970#issuecomment-2184203574

**Comment by Axelen123** [comment]
I have added toasts for each option on that page
