### ISSUE TITLE
bug: Odd usage of icon for API URL popup

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1972]
### Bug description

A better icon should be used as the current one does not properly convey the semantics, maybe the wifi icon:

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/67e4031c-d59a-4ee3-a39d-3d45a383f871)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Axelen123** [comment]
Why would the Wi-Fi Icon be better here? Please elaborate

**Comment by validcube** [comment]
Wi-Fi icon is universally recognised as basically the internet, I believe the correct icon should be the API icon from Material Symbol

https://fonts.google.com/icons?selected=Material+Symbols+Outlined:api:FILL@0;wght@400;GRAD@0;opsz@24&icon.size=24&icon.color=%235f6368

**Comment by oSumAtrIX** [comment]
I think semantics is correct here as well. Abusing another icon that is supposed to mean something different is probably not a good idea. The correct approach I suppose would be to suggest changes to the API icon

**Comment by Ushie** [comment]
Closing as out of scope
