### ISSUE TITLE
bug: Messy advanced settings screen

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1974]
### Bug description

The screen contains settings,  but some don't have a description when they should. For example, what does "Resetting a bundle" mean? Why would you "Redownload" all bundles? Does this apply to local bundles? 

A separate section should also be added only for patches screen-related toggles (also because there will be added more in the future) and patcher toggles should get their own section.

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/24caaf2d-d96a-4cec-a1ef-ad04b1b55af7)
screen-related

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Axelen123** [comment]
The screen has been reorganized. The "patch bundles" section has been moved to a new developer options screen as they are mainly intended for patch bundle developers.
