### ISSUE TITLE
feat: Add more safe guards

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1975]
### Feature description

While the first one is somewhat present,  when the user enables changing the selection , there's no way for them to toggle them off again. The setting should effectively be controlled through a toggle in the settings and not made comfortably available through a popup in the patch selector screen. The user should be discouraged from changing the patch selection by making it a chore to go back to the settings.

In addition to that a toggle for universal patches could be added. Those have a more generalized use and do not work as reliably as the ones that have specific target apps. Either that, or universal patches should be made distinguishable from patches with a target.

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/ea500819-460b-4ff4-8fb9-915c8369aafd)

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by Ushie** [comment]
The universal patches will be displayed in their own section, and maybe a filtering/sorting feature will be added to the patch selector screen

**Comment by oSumAtrIX** [comment]
They should also come with a warning or disclaimer for the reasons mentioned in my OP.
