### ISSUE TITLE
feat: Simplify device section

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1977]
### Feature description

There is no need to add a preference item for every detail about the device. Adding a "Device details" preference with the description containing all the info should be enough.

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/d1801528-7abb-4dfe-b267-c63b6df3ccc5)

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by Ushie** [comment]
![image](https://github.com/ReVanced/revanced-manager/assets/79272171/f5f36cd2-bf61-4505-928f-8d137946a537)

**Comment by oSumAtrIX** [comment]
Could try making the titles bold, if looks odd, simply keep as is.

About device being the only list item under that section is weird, but this is something for another issue.
