### ISSUE TITLE
feat: Improve apps list label

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1979]
### Feature description

This should probably also say. Click on the plus button to patch an app to suggest an action for the user.

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/072aae9a-ee12-4cc1-ac18-223ba8143602)

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by Ushie** [comment]
#1500
