### ISSUE TITLE
feat: Use patch bundle manifest name by default

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1980]
### Feature description

Main should probably be renamed to "Default". A description for the bundle can also be present or in the bundle screen that says "This is the default bundle that comes with the configured API in the settings".

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/ee5b6acf-f453-4648-8bf8-0d749b2a6f58)

### Motivation

Main doesn't really say much

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by Ushie** [comment]
I got an idea for this

The ReVanced API has an info endpoint, what's stopping us from using the name from there for the patch bundle?

${apiName} Bundle would work good

**Comment by oSumAtrIX** [comment]
That makes sense, so you use the domain. In ReVanceds case it would be revanced.app. But what if we host two bundles? Or say, people do it on GitHub?

**Comment by Ushie** [comment]
This is for the API based bundle, for standalone bundle, the user has to input a name for it anyways

Default is not very much of a name, nor was main
No, I wasn't suggesting using the domain, I was suggesting to use https://api.revanced.app/v2/info

**Comment by oSumAtrIX** [comment]
I see, that sounds reasonable

**Comment by indrastorms** [comment]
> This is for the API based bundle, for standalone bundle, the user has to input a name for it anyways
> 
Manually putting name is so annoying, why manager can't read the name from bundle's manifest?

**Comment by Ushie** [comment]
Yeah that makes sense, ReVanced Manager can populate the name with the bundle's manifest, and allow the user to edit it if they want

**Comment by oSumAtrIX** [comment]
This also makes more sense in the case of the API based bundle.
