### ISSUE TITLE
bug: Update button in bundle screen does nothing

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1982]
### Bug description

Clicking this does nothing:

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/a9aae8c6-dc35-446d-8e28-ee29f83d77ce)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Axelen123** [comment]
That is an update button

**Comment by oSumAtrIX** [comment]
That confusion needs to be looked into. Clearly it resembles a reset button. For example, ReVanced Manager flutter uses this icon, to reset the patch options.

**Comment by Axelen123** [comment]
@PalmDevs @Ushie do you have any suggestions for a replacement icon?

**Comment by oSumAtrIX** [comment]
I have opened an issue for this specifically https://github.com/ReVanced/revanced-manager/issues/2002

**Comment by Axelen123** [comment]
> I have opened an issue for this specifically https://github.com/ReVanced/revanced-manager/issues/2002

In that case this issue should be closed because the button works. If I am wrong, reopen it.
