### ISSUE TITLE
feat: Improve bundle screen

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1983]
### Feature description

Right now the bundle screen looks unorganized:

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/7811fe2c-0949-448f-b805-8c986060e8be)

The version having its own list item doesn't really make sense, it should maybe be added next to the name.
The patches could be listed directly on that screen under a section, simply scrolling down could show all the patches without a submenu.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by Ushie** [comment]
> it should maybe be added next to the name

As a listitem? or next to the name value?

**Comment by oSumAtrIX** [comment]
I am not sure, this should be looked at in Figma as a mockup. Design restrictions may be applying here, @Axelen123 would know more.

**Comment by Axelen123** [comment]
The "Patches" item only exists in development versions. Bundle type could maybe be removed.

@PalmDevs what do you think?
