### ISSUE TITLE
bug: Bundle screen patches not showing all relevant information

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1984]
### Bug description

Doing what the banner suggests does nothing:

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/ec452615-3e2e-497d-ae3b-c0c5351578bc)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Axelen123** [comment]
The bundle patches page needs to be redesigned, which is why it is hidden in release builds.
