### ISSUE TITLE
feat: Improve bundle patches list by adding more info to the patch items

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1985]
### Feature description

Right now each item only shows the patch title and description:

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/fb3a8c63-c885-4167-98c2-7014f39f997c)

It should also show compatible packages and their version and available options.

A good reference is our website , but can be improved:

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/0640df77-f2d4-4f81-ba2f-bf58289d464b)

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by Ushie** [comment]
How would you improve it? I can recreate the website's implementation

**Comment by Axelen123** [comment]
I believe this should be considered low priority because the bundle patch list page does not exist in release builds

**Comment by oSumAtrIX** [comment]
@Ushie Well, I am only saying in my OP that it's missing those metadata. How it looks isn't really too important. Making it similar to website is fine, but if you have better ideas, simply apply them. I guess this can be looked at in Detail on Figma

**Comment by Axelen123** [comment]
Closing for the same reason as https://github.com/ReVanced/revanced-manager/issues/1984#issuecomment-2227136193
