### ISSUE TITLE
feat: Add "What do do here" hints to various screens

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1986]
### Feature description

To the user it may be unclear what this screen is:

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/37bd5106-0fe6-4b6e-9301-2d34937eac20)

Some description, label, an initial dialog or similar should be present that explains to the user what this screen is,  its purpose and so on. Same goes for the apps screen.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by Ushie** [comment]
You can make suggestions in this issue https://github.com/ReVanced/revanced-manager/issues/1500
