### ISSUE TITLE
bug: Android icon not loading in app selector

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1989]
### Bug description

When the item renders a second time, the pp icon appears, until then it shows up like this:

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/27e97f2d-769b-404b-9076-12dce6faf863)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Axelen123** [comment]
Only apps that are not installed will be missing icons. There is no reason to show those apps after the downloader is removed, so I am going to label this as "Depends on Downloader".

**Comment by oSumAtrIX** [comment]
If you do not show the apps, how does the user know patches for it exist?
