### ISSUE TITLE
bug: Remove the option to toggle between bundle types

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1991]
### Bug description

Right now changing the type is possible:

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/07886f3b-04c2-44fb-90b9-32882dbc4d96)

Then why was a dialog previously shown to chose the type? The type should be removed. If the user wants to "change" the type they intend to replace whatever they have with something new. The simplest and most intuitive course of action is to delete the old bundle and add the new one  .

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Ushie** [comment]
I believe the bundle type should still be displayed, just not togglable

**Comment by oSumAtrIX** [comment]
That should be implicit. Instead of saying "This is remote bundle" or "This is a local bundle" you would for example display its URL or file path.

**Comment by Axelen123** [comment]
I don't think it is necessary to show the bundle type in the page because the UI already tells you which type it is. The update button and auto update setting don't exist for local bundles
