### ISSUE TITLE
bug: Some option types are unsupported

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1997]
### Bug description

Clicking here does nothing for example:

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/227ea7d7-adcd-467d-ba4d-78002e21327b)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Axelen123** [comment]
I have already implemented this in a branch. I will finish it when I have time
