### ISSUE TITLE
bug: Downloadable versions missing

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#1999]
### Bug description

YouTube has for example multiple versions that can be patched,  but the downloader only ever offers one:

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/1ea1b221-0e37-4a0a-b487-6269ec57d788)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Axelen123** [comment]
This behavior is intentional. The page will hide all other versions if the suggested version safeguard is enabled to avoid overwhelming the user with versions that cannot be selected.
