### ISSUE TITLE
feat: Improve labels in patcher screen

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#2000]
### Feature description

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/321def81-d844-48aa-9f9e-3cbe50920d0a)

From top to bottom:

- #### Preparing

- Download APK file
- Load patches
- Read APK file
- Merge integrations (Not something Manager should show at all)

- #### Executing

- Executing [patch name]

- #### Saving

- Writing patched APK file
- Signing patched APK file
- Cleaning up (If such a step exists to assure a clean and tidy behaviour to the user)

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by Ushie** [comment]
With the upcoming rename of Integrations to Extensions, maybe the integrations step can be changed to Adding extensions

**Comment by oSumAtrIX** [comment]
Such progress won't be reported by Patcher. Extensions are applied JIT right before a patch is executed as extensions are per patch.

**Comment by Ushie** [comment]
Then it can be removed ahead of time

**Comment by CnC-Robert** [comment]
Wouldn't applying be a better term for patches? That way you can also show "Applied patches" in the app info screen.
And isn't "Patching" a better term for the header than executing?

**Comment by oSumAtrIX** [comment]
Executing is a more general term. A patch could technically just read from an app instead of applying something to it for example. Applying is a sub term of executing and not the other way round. Internally patcher also executes patches through the execute function
