### ISSUE TITLE
bug: Odd UI in version selector screen when safe guards enabled

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#2001]
### Bug description

![image](https://github.com/ReVanced/revanced-manager/assets/13122796/1ea1b221-0e37-4a0a-b487-6269ec57d788)

When safe guards are enabled there shows up a radio item list with one item. This doesn't make sense. If only the recommended version is ever available why even let the user select it? Skip that page and select that version automatically. If the safe guards is enabled, probably other pages need to change as well. Presenting "suggested version" in the app selector for example also doesn't make sense, because it's not a suggestion anymore at this point.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Axelen123** [comment]
Downloader plugin branch now shows all versions
