### ISSUE TITLE
bug: Change `Change package name succeeded` to `Changing package name`

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-manager#2004]
### Bug description

I noticed that the process of changing the app package name is mentioned during the process pf building, which confused me at first, as the sentence was `Change package name succeeded`, as if I selected such a patch and hence I had to cancel and check again. The word succeeded is used for patches selected by the user and hence should be removed from that sentence. Instead, `Changing package name` can be used. This is, unless the patch gets added which allows to change the package name, at which point it would be fine.

![Screenshot_20240624_203748~2](https://github.com/ReVanced/revanced-manager/assets/117499019/acbfb106-4dda-469b-ab60-69b691c45dd4)

### Version of ReVanced Manager and version & name of app you are patching

v1.20.1

### Installation method

Regular

### ReVanced Manager logs

```shell
Nil
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by ILoveOpenSourceApplications** [comment]
I don't know whether this issue is strictly for the Manager or the Patcher. Please transfer if it's the wrong place.

**Comment by validcube** [comment]
> I don't know whether this issue is strictly for the Manager or the Patcher. Please transfer if it's the wrong place.

👋 Hello, @ILoveOpenSourceApplications!

Unfortunately, this is intended behaviour, the ReVanced Manager Patch log shows what patch is being (or not) applied properly _(format: patch_name + succeeded)_ for diagnostic purposes.

"Change package name" is the patch's name, so "Change package name **succeeded**" is correct.

Thanks for the bug report/request!

**Comment by Ushie** [comment]
A patch you included depends on the Change package name patch, most likely

**Comment by ILoveOpenSourceApplications** [comment]
Is it GmsCore support?

**Comment by oSumAtrIX** [comment]
It's a dependency of another patch you executed, not really a bug.

**Comment by ILoveOpenSourceApplications** [comment]
> Is it GmsCore support?

?

**Comment by ILoveOpenSourceApplications** [comment]
Yes, it's GmsCore support which has a dependency to Change package name. Since the user hasn't selected the patch personally, does it really have to show up during the patching process? Similar to how Spoof client, even if not included, currently has a dependency to GmsCore support and will be added but doesn't show up during patching process.

**Comment by oSumAtrIX** [comment]
Unrelated to this issue but this is caused by dependencies being added to the set of executed patches which if closeable are logged: https://github.com/ReVanced/revanced-patcher/blob/main/src/main/kotlin/app/revanced/patcher/Patcher.kt#L252

Open an issue in Patcher repository
