### ISSUE TITLE
feat: Download Apk directly from Google

### ISSUE THREAD

**Issue by mat926** [ReVanced/revanced-manager#2014]
### Feature description

On unrooted devices where split Apk is not supported, try to automatically download the full Apk directly from Google before applying a patch.

### Motivation

This helps with time and convenience as this wouldn't require the user to manually find and download an Apk. And some Apk sources wouldn't be as safe since they inject their own ads into the Apk. Here's an example repo that does this https://github.com/onyxbits/raccoon4

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
#722
