### ISSUE TITLE
feat(compose): Save selected patches with better structure

### ISSUE THREAD

**Issue by kitadai31** [ReVanced/revanced-manager#2030]
### Feature description

I have a suggestion for manager rewriting:

Save selected patches in two lists: added patches and removed patches.
In other words, save only the differences from the default patches.

Current data structure (Flutter Manager):

```json
{
    "com.google.android.youtube": [
        "Always repeat",
        "Annoucements",
        "Bypass URL redirects",
        "Change start page",
        "Comments",
        "..."
    ]
}
```

New data structure (just an example):

```json
{
    "com.google.android.youtube": {
        "userManualAddedPatches": [
            "Custom branding",
            "Remove player controls background"
        ],
        "userManualRemovedPatches": [
            "Alternative thumbnails",
            "Swipe controls",
            "SponsorBlock",
            "Theme"
        ]
    }
}
```

### Motivation

- This data structure matches the policy of ReVanced that the patch selection should not be changed from the default.
- There is a problem in the current data structure. If a patch developer makes a default patch non-default, that patch will remain selected for users who have previously patched by default.
  - A case: In the ReX, a ReVanced fork patches, the developer chose to leave the deprecated "Spoof player parameters" (Spoof app signature) patch as a non-default patch rather than removing it, but the Manager remembered the previous patch selection. That caused many people to apply the deprecated problematic patch.
- This data structure is robust to patch renaming.
- With this new structure, you will no longer need to keep a list of all previous patches just to display the "New" label on a new patch.  New default patches will be added naturally.
- Current Flutter Manager has a logic that adds new default patches to the selected patches, but this structure will allow you to remove that logic.
- Currently, every time a patch is renamed, a worrying "The following patches has been removed." warning is displayed to users.  This warning will be unnecessary.  (Even if a default patch is renamed, user don't need to care about it.)

-> For these reasons, in the past, I hesitated to rename the "MicroG support" patch to "GmsCore support" in my patch bundle.
If the compose rewrite will use this data structure, there will be no need to consider the specifications of the Manager anymore.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
I don't see what the problem is with saving a list of patches that the user selected keyed by the app for example. If the patch gets renamed, itll be selected if it is used by default. If the patch changed the use value from true to false, and the user had previously not manually selected it, itll be unselected, vice versa. If theres a good reason I'll reopen

**Comment by kitadai31** [comment]
Oh, I didn't know that ReVanced Manager (Flutter one) doesn't save selected patches if "Allow changing patch selection" is disabled.
It's still an issue if "Allow changing patch selection" is on, but it's not a big issue.
Thank you.
