### ISSUE TITLE
feat: add ability to view patch bundle loading errors

### ISSUE THREAD

**Issue by Axelen123** [ReVanced/revanced-manager#2031]
### Feature description

An item in the bundle information screen should be added for viewing tracebacks.

### Motivation

Currently, there is no way to see the traceback for bundle loading errors. This makes it hard to share tracebacks with developers.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
Notable issues that can occur when trying to load patches are typical class loading issues as well as incompatible APIs

**Comment by Axelen123** [comment]
A dialog has been added to view and share tracebacks. In the future we could provide information based on the exception class
