### ISSUE TITLE
feat: better manager update experience

### ISSUE THREAD

**Issue by KiGamji** [revanced/revanced-manager#204]
### Type

Cosmetic

### Branch

Flutter

### Issue

Currently, there is no downloading update process indication, and when update is downloaded, you have to press update manager button once again.

### Feature

When you press update button, there should be downloading process notification, and when app is downloaded, it should show apk update dialogue automatically

### Motivation

Sometimes people have troubles with manager updates, and asks many question about why something is not working, like:
Why download is so slow? I pressed the button and nothing happened, what did i do wrong? I cant update my manager, any ideas???

**Comment by Aunali321** [comment]
My next implementation hopefully.

**Comment by KiGamji** [comment]
@Aunali321, also consider merging annon's prs. ty

**Comment by ponces** [comment]
Update button is fixed. Check v0.0.15 and try to update to v0.0.16.
