### ISSUE TITLE
feat: Add reset API to default button

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#2051]
### Feature description

If a custom API is set, theres no way to reset it back to default:

![image](https://github.com/user-attachments/assets/a42ab214-8fe7-4c20-b199-22a630299c5b)

### Motivation

You could forget the original API url.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by Ushie** [comment]
There is no constant API_URL in the app, there is only a preference with a default value

How should I add a constant like this? @Axelen123

**Comment by oSumAtrIX** [comment]
Can't you access the preference?

**Comment by Ushie** [comment]
The value of the preference is changed by setting the custom URL, you wouldn't be able to get the default API_URL through it

**Comment by oSumAtrIX** [comment]
Oh yeah you'll need a constant.

**Comment by Axelen123** [comment]
> There is no constant API_URL in the app, there is only a preference with a default value
> 
> How should I add a constant like this? @Axelen123 

I am pretty sure the `Preference` has a `default` field. If not, you can add it
