### ISSUE TITLE
feat: Add confirm dialogs when toggling dangerous settings

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#2055]
### Feature description

Right now safeguards for example can be simply toggled (even accidentally):

![image](https://github.com/user-attachments/assets/e97c9a80-5648-47f2-9f20-3b001c6ddffb)

When toggling them yet another warning should be shown to clarify why it is unsuggested.

### Motivation

The user might toggle them without knowing that they shouldnt.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager

**Comment by TheAabedKhan** [comment]
Is everything ok apart from the description?
https://github.com/user-attachments/assets/8f3df7c0-bde5-4190-9e56-ee3e1474ffa6

**Comment by Axelen123** [comment]
"Require suggested app version" is on by default, so the dialog should be shown when it goes from true -> false

**Comment by TheAabedKhan** [comment]
Fixed✅

**Comment by Ushie** [comment]
Open a PR so we can review
