### ISSUE TITLE
bug: Enabling safeguards does not restore default states

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#2057]
### Bug description

When you disable the safeguard to change the patches selection, then change it and enable the safe guard again the selection will remain changed:

![image](https://github.com/user-attachments/assets/756e67ae-1393-46a4-aef5-30f220a45f9d)

Instead it should restore the respective "default" state the safeguard was made for.

### Version of ReVanced Manager and version & name of app you are patching

-

### Installation method

None

### ReVanced Manager logs

```shell
-
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Buchimi** [comment]
I tried this on the most recent version of the manager, what version is this on?

**Comment by oSumAtrIX** [comment]
The compose-dev branch
