### ISSUE TITLE
bug: YouTube ReVanced - Live Videos Not Playing in Background

### ISSUE THREAD

**Issue by FSSocrates** [ReVanced/revanced-manager#2063]
### Bug description

# Bug Report: YouTube ReVanced - Live Videos Not Playing in Background

**Summary:**
YouTube ReVanced is not playing live videos in the background, which is a key feature for continuous listening.

**Steps to Reproduce:**
1. Open the YouTube ReVanced app.
2. Navigate to any live video stream.
3. Start playing the live video.
4. Minimize the app or switch to another app.

**Expected Behavior:**
The live video should continue playing in the background, allowing the audio to be heard while using other apps or when the device screen is off.

**Actual Behavior:**
The live video stops playing as soon as the app is minimized or another app is opened, interrupting the audio playback.

**Frequency:**
Every time a live video is played and the app is minimized or another app is opened.

**Device Information:**
- Device Model: Realme 9
- Operating System: Android 14
- YouTube ReVanced Version: 19.16.39
- YouTube Base Version: 19.16.39

**Additional Information:**
- The issue does not occur with regular (non-live) videos; they continue to play in the background as expected.
- I have tried clearing the cache and data of the app, but the issue persists.
- I have also tried reinstalling the app, but the problem remains.

**Possible Related Issues:**
- The issue might be related to the background play feature specifically for live streams.

**Comments:**
This functionality is crucial for users who want to listen to live streams without actively watching the video. It is especially useful for music or talk shows.

### Version of ReVanced Manager and version & name of app you are patching

Downloaded from https://revanced.to/youtube/

### Installation method

Regular

### ReVanced Manager logs

```shell
N/A
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [ ] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
![image](https://github.com/user-attachments/assets/40d2ebaf-dc8d-408f-9a71-824f643a4bd4)

https://github.com/ReVanced/revanced-patches/issues/3208
