### ISSUE TITLE
bug: mix content 

### ISSUE THREAD

**Issue by Aleksandrt6** [ReVanced/revanced-manager#2085]
### Bug description

![Screenshot_20240725_214038_One UI Home](https://github.com/user-attachments/assets/e25f4f4e-aa91-4c30-aec3-c19bb27ea320), remove erase ,don't replace 

### Version of ReVanced Manager and version & name of app you are patching

https://revanced.net/,scroll down see it revanced manager 

### Installation method

None

### ReVanced Manager logs

```shell
No,first time help it handle
```

### Patch logs

```shell
No, first time handling
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [ ] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
https://github.com/orgs/ReVanced/discussions/1051#discussioncomment-10150485
