### ISSUE TITLE
bug: Not able to download patches. Showing error

### ISSUE THREAD

**Issue by vippium** [ReVanced/revanced-manager#2087]
### Bug description

Not able to download patches from any source. Showing error

### Version of ReVanced Manager- Latest action build and version & name of app you are patching

![Screenshot_20240727_111850](https://github.com/user-attachments/assets/9830b475-7a5a-4e5a-a011-30c4abf748d8)

### Installation method

None

### ReVanced Manager logs

```shell
...
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by Axelen123** [comment]
Your link is invalid. It 404s outside revanced manager as well.

**Comment by vippium** [comment]
But I used the same link from `Revanced Patches Bundles`.

**Comment by oSumAtrIX** [comment]
For support, move to one of our links at https://revanced.app.

**Comment by Axelen123** [comment]
> But I used the same link from `Revanced Patches Bundles`.

Open an issue on that repo

**Comment by vippium** [comment]
> Open an issue on that repo

I opened it recently

**Comment by Jman-Github** [comment]
This was a mistake on my end. It should now be fixed. Sorry for the inconveniences!
