### ISSUE TITLE
bug: Patched app doesn't opening/crashing always

### ISSUE THREAD

**Issue by vippium** [ReVanced/revanced-manager#2089]
### Bug description

IDK what is the reason but patched apps (yt and YTM tested) are not opening with the manager. I've tried so many times but same issue. So just opened and crashes. Please check once. I'll share the recording after I get time.

### Version of ReVanced Manager and version & name of app you are patching

Latest Action Build

### Installation method

None

### ReVanced Manager logs

```shell
...
```

### Acknowledgements

- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

**Comment by oSumAtrIX** [comment]
For support, move to one of our links at https://revanced.app.
