### ISSUE TITLE
bug: Wrong arch version

### ISSUE THREAD

**Issue by gynom** [ReVanced/revanced-manager#2091]
### Bug description

Revanced community manager downloads the wrong arch for my phone so I end up getting not compatible. It'd be nice if you could pick the arch version.

### Version of ReVanced Manager and version & name of app you are patching

1.9.2.5
This is almost all apps only YouTube worked but I assume that's because it downloaded a multi arch supported apk.

### Installation method

None

### ReVanced Manager logs

```shell
There are no settings (Or I'm blind)
```

### Patch logs

```shell
No settings.
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
You are using counterfeit. https://revanced.app
