### ISSUE TITLE
Your device isn't certified to run Google apps or use Google services. Contact the device manufacturer or retailer and ask for a certified device. Learn more

### ISSUE THREAD

**Issue by bphd** [ReVanced/revanced-manager#2094]
### Bug description

Your device isn't certified to run Google
apps or use Google services. Contact
the device manufacturer or retailer and
ask for a certified device. Learn more

### Version of ReVanced Manager and version & name of app you are patching

Your device isn't certified to run Google
apps or use Google services. Contact
the device manufacturer or retailer and
ask for a certified device. Learn more

### Installation method

None

### ReVanced Manager logs

```shell
Your device isn't certified to run Google
apps or use Google services. Contact
the device manufacturer or retailer and
ask for a certified device. Learn more
```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [ ] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
Your device isn't certified to run Google
apps or use Google services. Contact
the device manufacturer or retailer and
ask for a certified device.

**Comment by bphd** [comment]
> Your device isn't certified to run Google apps or use Google services. Contact the device manufacturer or retailer and ask for a certified device.

It is certified, it's an official supported device that comes with Google services. But upon patching application, it starts to say that
