### ISSUE TITLE
feat: Support `Pre-release` patches

### ISSUE THREAD

**Issue by Kuddus73** [ReVanced/revanced-manager#2096]
### Feature description

Support patching with pre-realease versions of patches.

RVX Manager has this feature:
![Screenshot_20240731_210716_RVX Manager](https://github.com/user-attachments/assets/034832b4-bfe6-40c1-be29-f13fc36495de)

### Motivation

YouTube patches have many pre-release patches before the stable one is released, which causes a long time to pass from one stable release to another.
So this feature will allow users to try the new features or bug fixes as soon as they get released.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-manager/issues/1867
