### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Zusyaku** [revanced/revanced-manager#210]
why revanced manager not showing youtube and yt musik app and pacther only show tiktok

samsung a10s arm7

**Comment by pietryszak** [comment]
First of all use bug template, second add proper title for bug, third add any steps to reproduce issue, forth add screenshots, logs.
Without that that kind of bug report is ussless.

**Comment by ponces** [comment]
Please, use the issue template and provide as much info as you can.
Closed.
