### ISSUE TITLE
bug(ReVanced Manager compose): Unselect new bundles patches or to add a button to quickly reset the selection of patches

### ISSUE THREAD

**Issue by MarcaDian** [ReVanced/revanced-manager#2108]
### Bug description

When you add a third-party bundles, all patches are selected by default. And there will be an error during patching. It is necessary to manually reset the patches of the currently unnecessary bundle.
It is probably more correct to make the added new bundles without selected patches, or to add a button to quickly reset the selection of patches of the currently unnecessary bundle.

<details>

By default there should be 57 patches.
109 = 57 `ReVanced Patches` bundle + 52 `inotia00` bundle:

![Screenshot_2024-08-02-14-30-09-672-edit_app revanced manager debug](https://github.com/user-attachments/assets/a0185365-d83d-4821-917c-c2faed5b6b1f)
![Screenshot_2024-08-02-14-30-14-455_app revanced manager debug](https://github.com/user-attachments/assets/4a1c0afb-aece-4700-aec6-8490c6a87d27)
![Screenshot_2024-08-02-14-30-17-343_app revanced manager debug](https://github.com/user-attachments/assets/4a5457ba-3d2f-4b92-ad12-928b8d286f7f)
![Screenshot_2024-08-02-14-45-31-220_app revanced manager debug](https://github.com/user-attachments/assets/81a68de3-27c6-47cf-a98c-acdee832feea)

</details>

### Version of ReVanced Manager and version & name of app you are patching

last ReVanced Manager compose dev (https://github.com/ReVanced/revanced-manager/commit/c18901c35ba170c27b3db412116e6a0b62278d65)

### Installation method

None

### ReVanced Manager logs

```shell
NaN
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
The default selection applies by default. You have conflicting patches and thus they wont work together.
