### ISSUE TITLE
bug: `Save` button doesn't work 

### ISSUE THREAD

**Issue by Kuddus73** [ReVanced/revanced-manager#2109]
### Bug description

The `Save` button to save the patched APK doesn't work with alternative sources (tried with _inotia00_ and _crimera_).

https://github.com/user-attachments/assets/8231350c-ec97-4da3-ba65-60f15d8415c4

### Version of ReVanced Manager and version & name of app you are patching

ReVanced Manager v1.21.1
YouTube v19.16.39

### Installation method

Regular

### ReVanced Manager logs

The log might be too long to paste it:
[revanced-manager_logcat_20240802215606862640.log](https://github.com/user-attachments/files/16475370/revanced-manager_logcat_20240802215606862640.log)

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
Reset Manager to default, check if it works.

**Comment by Kuddus73** [comment]
> Reset Manager to default, check if it works.

My bad, as I don't use the default source and only use alternative sources to patch, I thought it wasn't working only with alternative sources.
