### ISSUE TITLE
bug: can't uninstall vanced client/stock app

### ISSUE THREAD

**Issue by pcwizard7** [revanced/revanced-manager#212]
### Type

Error while running the manager

### Branch

Flutter

### Bug description

My first install issue was when it was finally installed I opened the app, and it opens to blank app then if you closed the app it would crash it

I uninstalled it to reinstall it but when I tried too it said an app already existed even tho I uninstalled it, and it's not in the apps lists so i m stcuk

### Steps to reproduce

none

### Relevant log output

```shell
none
```

**Comment by ponces** [comment]
YouTube version? Selected patches? Root or non-root?

**Comment by pcwizard7** [comment]
> YouTube version? Selected patches? Root or non-root?
Non-Root

![Screenshot_20220919-164504](https://user-images.githubusercontent.com/28586567/190963160-d61feaba-cd53-4cd6-89a2-ea4420ed566a.jpg)

**Comment by ponces** [comment]
You're missing MicroG patch if you are non-root. You need MicroG installed and patch selected.
Closed.

**Comment by pcwizard7** [comment]
Now I back to the initial issue after it's done patching, and you open the app for the first time and just blank screen. And close and reopen it doesn't make a difference
