### ISSUE TITLE
feat: Show list of unselected patches

### ISSUE THREAD

**Issue by traeu** [revanced/revanced-manager#213]
### Type

Functionality

### Branch

Flutter

### Issue

After selecting patches, revanced manager shows a list of all selected patches. I always select all patches except of logging and microg (I guess other users do it too?), so this list is long and not really helpful for me.

### Feature

If there would also be a list of unselected but available patches, maybe as separate list below the list of selected patches or maybe crossed out at the end of the selected patches list, it would be easy to quickly check if everything is selected (or unselected) correctly.

### Motivation

Be sure to select everything correctly. Instead of scrolling to the list twice just to make sure, one could view instantly if the correct patches are selected and unselected, even if a lot of patches are activated.

**Comment by Aunali321** [comment]
It would clutter the screen.
