### ISSUE TITLE
bug: Tiktok unremovable, intrusive pop up

### ISSUE THREAD

**Issue by FeralWriting** [ReVanced/revanced-manager#2130]
### Bug description

Tiktok Revanced continues to have some Olympics pop up in the corner of the screen that is unremovable and redirects on click.
![Screenshot_20240810-144310](https://github.com/user-attachments/assets/43f8c66e-a621-4fda-89e2-ac82544103ca)

### Version of ReVanced Manager and version & name of app you are patching

Revanced 1.9.25. Tiktok 32.5.3.

### Installation method

Regular

### ReVanced Manager logs

```shell
Don't see this option in app.
```

### Patch logs

```shell
The patcher still does not work on my Tiktok app, despite me already creating an issue about this.
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
Thats not a bug, let alone by ReVanced

**Comment by FeralWriting** [comment]
This is specifically only in Tiktok Revanced. Are you suggesting it's
intentional to have an unremovable pop up in an app for removing ads?

**Comment by FeralWriting** [comment]
This isn't the Revanced manger app?
![Screenshot_20240810-145925](https://github.com/user-attachments/assets/cf2c8b06-99fa-4b8b-ae3e-fcbd9aa5a053)

**Comment by Ushie** [comment]
No

**Comment by FeralWriting** [comment]
Thanks

**Comment by FeralWriting** [comment]
The real app will not download. Keeps saying "needs authorization". How am
I supposed to download it?

**Comment by oSumAtrIX** [comment]
For support move to the links at https://revanced.app

**Comment by FeralWriting** [comment]
Yes, that's where I'm downloading it from and having the issue
