### ISSUE TITLE
bug: Change version code doesn't work

### ISSUE THREAD

**Issue by morkovkaTelegram** [ReVanced/revanced-manager#2136]
### Bug description

https://gachi.gay/2i3N1

### Version of ReVanced Manager and version & name of app you are patching

- Device Info
ReVanced Manager: 1.21.2
Model: M2101K6G
Android version: 11
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.twoheadedshark.tco v2.4139 (Suggested: Any)
Patches version: v4.12.0
Patches added: Change version code
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 1 patches
Compiling patched dex files
Compiled 10 dex files
Compiling modified resources
Aligning APK
Signing APK
Patched APK

### Installation method

Regular

### ReVanced Manager logs

```shell
- Device Info
ReVanced Manager: 1.21.2
Model: M2101K6G
Android version: 11
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.twoheadedshark.tco v2.4139 (Suggested: Any)
Patches version: v4.12.0
Patches added: Change version code
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 1 patches
Compiling patched dex files
Compiled 10 dex files
Compiling modified resources
Aligning APK
Signing APK
Patched APK
```

### Acknowledgements

- [ ] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-manager/issues/2037

**Comment by viiktr** [comment]
Issue continues as of patches verson 5.20.1
