### ISSUE TITLE
bug: Error when patching Google Photos

### ISSUE THREAD

**Issue by NichirinSword** [ReVanced/revanced-manager#2137]
### Bug description

Error when patching Google Photos

### Version of ReVanced Manager and version & name of app you are patching

ReVanced Manager Version: 1.21.2
Model: RMX3472
Android Version: 14

App: com.google.android.apps.photos v6.94.0.659749309 (Suggested: Any)

### Installation method

Regular

### ReVanced Manager logs

```shell
--------- beginning of crash
08-13 10:58:38.747 18365 18365 E AndroidRuntime: FATAL EXCEPTION: main
08-13 10:58:38.747 18365 18365 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 18365
08-13 10:58:38.747 18365 18365 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver app.revanced.manager.flutter.utils.packageInstaller.InstallerReceiver: java.lang.NullPointerException
08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4722)
08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2439)
08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:257)
08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:368)
08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8826)
08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
08-13 10:58:38.747 18365 18365 E AndroidRuntime: Caused by: java.lang.NullPointerException
08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.packageInstaller.InstallerReceiver.onReceive(Unknown Source:63)
08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4706)
08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	... 9 more
--------- beginning of system
08-13 11:27:37.120 19069 19069 D ActivityThread: do gfx trim 40 success
--------- beginning of main
08-13 11:27:37.121 19069 21761 D OpenGLRenderer: RenderThread::destroyRenderingContext: this=0xb400007989aaec00
08-13 11:27:37.121 19069 21761 D OpenGLRenderer: SkiaOpenGLPipeline::onContextDestroyed: this=0xb4000079b4f15bc0
08-13 11:27:37.122 19069 21761 D OpenGLRenderer: EglManager::destroy: mEglDisplay=0xb4000079b4f14680, mEglContext=0xb400007916c17400, mCurrentSurface=0x0
08-13 11:27:39.180 19069 21887 D VRI[MainActivity]: dispatchAppVisibility visible:true
08-13 11:27:39.185 19069 19069 D VRI[MainActivity]: setWindowStopped stopped:false
08-13 11:27:39.194 19069 19069 D ScrollOptim [SceneManager]: updateCurrentActivity: mCurrentActivityName=app.revanced.manager.flutter.MainActivity, isOptEnable=true, isAnimAheadEnable=true, isFrameInsertEnable=true, InsertNum=1, isEnabledForScrollChanged=false
08-13 11:27:39.194 19069 19069 D ActivityThread: ComponentInfo{app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity} checkFinished=false 2
08-13 11:27:39.194 19069 19069 D ResourcesManagerExtImpl: applyConfigurationToAppResourcesLocked app.getDisplayId() return callback.displayId:-1
08-13 11:27:39.196 19069 19069 D ViewRootImplExtImpl: wrapConfigInfoIntoFlags rotation=0, smallestScreenWidthDp=360, relayoutAsync=false, newFlags=23592960, title=app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity
08-13 11:27:39.225 19069 19069 D VRI[MainActivity]: relayoutWindow result, sizeChanged:false, surfaceControlChanged:true, transformHintChanged:false, mSurfaceSize:Point(1080, 2412), mLastSurfaceSize:Point(1080, 2412), mWidth:1080, mHeight:2412, requestedWidth:1080, requestedHeight:2412, transformHint:0, lastTransformHint:0, installOrientation:0, displayRotation:0, isSurfaceValid:true, attr.flag:-2122252032, useBlast:true, tmpFrames:ClientWindowFrames{frame=[0,0][1080,2412] display=[0,0][1080,2412] parentFrame=[0,0][0,0]}, params:{(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION fmt=TRANSLUCENT wanim=0x1030001
08-13 11:27:39.225 19069 19069 D VRI[MainActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
08-13 11:27:39.225 19069 19069 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND USE_BLAST APPEARANCE_CONTROLLED FIT_INSETS_CONTROLLED
08-13 11:27:39.225 19069 19069 D VRI[MainActivity]:   vsysui=LAYOUT_STABLE LAYOUT_HIDE_NAVIGATION LAYOUT_FULLSCREEN
08-13 11:27:39.225 19069 19069 D VRI[MainActivity]:   bhv=DEFAULT
08-13 11:27:39.225 19069 19069 D VRI[MainActivity]:   fitSides= CLP[ ]}
08-13 11:27:39.225 19069 19069 W VRI[MainActivity]: updateBlastSurfaceIfNeeded, surfaceSize:Point(1080, 2412), lastSurfaceSize:Point(1080, 2412), format:-3, blastBufferQueue:null
08-13 11:27:39.225 19069 19069 D BufferQueueConsumer: [](id:4a7d0000000d,api:0,p:-1,c:19069) connect: controlledByApp=false
08-13 11:27:39.231 19069 19069 D BufferQueueConsumer: [](id:4a7d0000000e,api:0,p:-1,c:19069) connect: controlledByApp=false
08-13 11:27:39.232 19069 19069 I SurfaceView: 77306299 visibleChanged -- surfaceCreated 
08-13 11:27:39.232 19069 21775 D BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#14(BLAST Consumer)14](id:4a7d0000000e,api:1,p:19069,c:19069) connect: api=1 producerControlledByApp=true
08-13 11:27:39.234 19069 21761 D BufferQueueProducer: [VRI[MainActivity]#13(BLAST Consumer)13](id:4a7d0000000d,api:1,p:19069,c:19069) connect: api=1 producerControlledByApp=true
08-13 11:27:39.234 19069 21761 E OpenGLRenderer: Unable to match the desired swap behavior.
08-13 11:27:39.236 19069 19069 D SurfaceView: 77306299 handleSyncNoBuffer
08-13 11:27:39.237 19069 19069 D SurfaceView: 77306299 finishedDrawing
08-13 11:27:39.237 19069 19069 D SurfaceView: 77306299 performDrawFinished mAttachedToWindow true
08-13 11:27:39.238 19069 19069 I SurfaceControl:  setExtendedRangeBrightness sc=Surface(name=app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity)/@0x66bcc94,currentBufferRatio=1.0,desiredRatio=1.0
08-13 11:27:39.238 19069 19069 D SurfaceView: 77306299 dispatchDraw mDrawFinished true isAboveParent false (mPrivateFlags & PFLAG_SKIP_DRAW) 128
08-13 11:27:39.238 19069 19069 D SurfaceView: 77306299 clearSurfaceViewPort mCornerRadius 0.0
08-13 11:27:39.243 19069 21761 D BLASTBufferQueue: [VRI[MainActivity]#13](f:0,a:1) acquireNextBufferLocked size=1080x2412 mFrameNumber=1 applyTransaction=true mTimestamp=43425662860776(auto) mPendingTransactions.size=0 graphicBufferId=81900731367460 transform=0
08-13 11:27:39.243 19069 21761 D VRI[MainActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
08-13 11:27:39.245 19069 19069 D VRI[MainActivity]: draw finished.
08-13 11:27:39.245 19069 19069 D VRI[MainActivity]: reportDrawFinished
08-13 11:27:39.246 19069 19069 D ViewRootImplExtImpl: setMaxDequeuedBufferCount: 2
08-13 11:27:39.246 19069 19069 I Quality : Skipped: false 1 cost 11.394218 refreshRate 8333801 bit true processName app.revanced.manager.flutter
08-13 11:27:39.258 19069 19069 D VRI[MainActivity]: onFocusEvent true
08-13 11:27:39.264 19069 21775 D BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#14](f:0,a:1) acquireNextBufferLocked size=1080x2412 mFrameNumber=1 applyTransaction=true mTimestamp=43425682896662(auto) mPendingTransactions.size=0 graphicBufferId=81900731367461 transform=0
08-13 11:27:40.264 19069 22671 D OplusScrollToTopManager: app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity,This DecorView@e0a3948[MainActivity] change focus to true
08-13 11:27:40.512 19069 19069 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=935.5, y[0]=2311.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=43426929, downTime=43426826, deviceId=2, source=0x1002, displayId=0, eventId=587397256 } handled by client, just return
08-13 11:27:41.195 19069 19069 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=916.5, y[0]=1656.75, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=43427614, downTime=43427499, deviceId=2, source=0x1002, displayId=0, eventId=1014363469 } handled by client, just return
08-13 11:27:42.688 19069 19069 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=811.5, y[0]=1698.5, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=43429107, downTime=43429005, deviceId=2, source=0x1002, displayId=0, eventId=969785441 } handled by client, just return
08-13 11:27:44.764 19069 19069 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=109.75, y[0]=1224.75, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=43431181, downTime=43431100, deviceId=2, source=0x1002, displayId=0, eventId=44111238 } handled by client, just return
```

### Patch logs

```shell
- Device Info
ReVanced Manager: 1.21.2
Model: RMX3472
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.photos v6.94.0.659749309 (Suggested: Any)
Patches version: v4.12.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 2 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~VXBdXRjTMR7D3sueHKtNHA==/app.revanced.manager.flutter-utne6xueD6WP5_8kNwLedg==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BNXJFV/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BNXJFV/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:462)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~VXBdXRjTMR7D3sueHKtNHA==/app.revanced.manager.flutter-utne6xueD6WP5_8kNwLedg==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BNXJFV/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BNXJFV/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BNXJFV/out.apk' (OS Error: No such file or directory, errno = 2)
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by shmaaaaa** [comment]
Also having the same issue here.

**Comment by oSumAtrIX** [comment]
Moving to https://github.com/ReVanced/revanced-manager/issues/2142

**Comment by MultimodeG** [comment]
> ### Bug description
> Error when patching Google Photos
> 
> ### Version of ReVanced Manager and version & name of app you are patching
> ReVanced Manager Version: 1.21.2 Model: RMX3472 Android Version: 14
> 
> App: com.google.android.apps.photos v6.94.0.659749309 (Suggested: Any)
> 
> ### Installation method
> Regular
> 
> ### ReVanced Manager logs
> ```shell
> --------- beginning of crash
> 08-13 10:58:38.747 18365 18365 E AndroidRuntime: FATAL EXCEPTION: main
> 08-13 10:58:38.747 18365 18365 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 18365
> 08-13 10:58:38.747 18365 18365 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver app.revanced.manager.flutter.utils.packageInstaller.InstallerReceiver: java.lang.NullPointerException
> 08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4722)
> 08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
> 08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2439)
> 08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:257)
> 08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:368)
> 08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8826)
> 08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
> 08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
> 08-13 10:58:38.747 18365 18365 E AndroidRuntime: Caused by: java.lang.NullPointerException
> 08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at app.revanced.manager.flutter.utils.packageInstaller.InstallerReceiver.onReceive(Unknown Source:63)
> 08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4706)
> 08-13 10:58:38.747 18365 18365 E AndroidRuntime: 	... 9 more
> --------- beginning of system
> 08-13 11:27:37.120 19069 19069 D ActivityThread: do gfx trim 40 success
> --------- beginning of main
> 08-13 11:27:37.121 19069 21761 D OpenGLRenderer: RenderThread::destroyRenderingContext: this=0xb400007989aaec00
> 08-13 11:27:37.121 19069 21761 D OpenGLRenderer: SkiaOpenGLPipeline::onContextDestroyed: this=0xb4000079b4f15bc0
> 08-13 11:27:37.122 19069 21761 D OpenGLRenderer: EglManager::destroy: mEglDisplay=0xb4000079b4f14680, mEglContext=0xb400007916c17400, mCurrentSurface=0x0
> 08-13 11:27:39.180 19069 21887 D VRI[MainActivity]: dispatchAppVisibility visible:true
> 08-13 11:27:39.185 19069 19069 D VRI[MainActivity]: setWindowStopped stopped:false
> 08-13 11:27:39.194 19069 19069 D ScrollOptim [SceneManager]: updateCurrentActivity: mCurrentActivityName=app.revanced.manager.flutter.MainActivity, isOptEnable=true, isAnimAheadEnable=true, isFrameInsertEnable=true, InsertNum=1, isEnabledForScrollChanged=false
> 08-13 11:27:39.194 19069 19069 D ActivityThread: ComponentInfo{app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity} checkFinished=false 2
> 08-13 11:27:39.194 19069 19069 D ResourcesManagerExtImpl: applyConfigurationToAppResourcesLocked app.getDisplayId() return callback.displayId:-1
> 08-13 11:27:39.196 19069 19069 D ViewRootImplExtImpl: wrapConfigInfoIntoFlags rotation=0, smallestScreenWidthDp=360, relayoutAsync=false, newFlags=23592960, title=app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity
> 08-13 11:27:39.225 19069 19069 D VRI[MainActivity]: relayoutWindow result, sizeChanged:false, surfaceControlChanged:true, transformHintChanged:false, mSurfaceSize:Point(1080, 2412), mLastSurfaceSize:Point(1080, 2412), mWidth:1080, mHeight:2412, requestedWidth:1080, requestedHeight:2412, transformHint:0, lastTransformHint:0, installOrientation:0, displayRotation:0, isSurfaceValid:true, attr.flag:-2122252032, useBlast:true, tmpFrames:ClientWindowFrames{frame=[0,0][1080,2412] display=[0,0][1080,2412] parentFrame=[0,0][0,0]}, params:{(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION fmt=TRANSLUCENT wanim=0x1030001
> 08-13 11:27:39.225 19069 19069 D VRI[MainActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
> 08-13 11:27:39.225 19069 19069 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND USE_BLAST APPEARANCE_CONTROLLED FIT_INSETS_CONTROLLED
> 08-13 11:27:39.225 19069 19069 D VRI[MainActivity]:   vsysui=LAYOUT_STABLE LAYOUT_HIDE_NAVIGATION LAYOUT_FULLSCREEN
> 08-13 11:27:39.225 19069 19069 D VRI[MainActivity]:   bhv=DEFAULT
> 08-13 11:27:39.225 19069 19069 D VRI[MainActivity]:   fitSides= CLP[ ]}
> 08-13 11:27:39.225 19069 19069 W VRI[MainActivity]: updateBlastSurfaceIfNeeded, surfaceSize:Point(1080, 2412), lastSurfaceSize:Point(1080, 2412), format:-3, blastBufferQueue:null
> 08-13 11:27:39.225 19069 19069 D BufferQueueConsumer: [](id:4a7d0000000d,api:0,p:-1,c:19069) connect: controlledByApp=false
> 08-13 11:27:39.231 19069 19069 D BufferQueueConsumer: [](id:4a7d0000000e,api:0,p:-1,c:19069) connect: controlledByApp=false
> 08-13 11:27:39.232 19069 19069 I SurfaceView: 77306299 visibleChanged -- surfaceCreated 
> 08-13 11:27:39.232 19069 21775 D BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#14(BLAST Consumer)14](id:4a7d0000000e,api:1,p:19069,c:19069) connect: api=1 producerControlledByApp=true
> 08-13 11:27:39.234 19069 21761 D BufferQueueProducer: [VRI[MainActivity]#13(BLAST Consumer)13](id:4a7d0000000d,api:1,p:19069,c:19069) connect: api=1 producerControlledByApp=true
> 08-13 11:27:39.234 19069 21761 E OpenGLRenderer: Unable to match the desired swap behavior.
> 08-13 11:27:39.236 19069 19069 D SurfaceView: 77306299 handleSyncNoBuffer
> 08-13 11:27:39.237 19069 19069 D SurfaceView: 77306299 finishedDrawing
> 08-13 11:27:39.237 19069 19069 D SurfaceView: 77306299 performDrawFinished mAttachedToWindow true
> 08-13 11:27:39.238 19069 19069 I SurfaceControl:  setExtendedRangeBrightness sc=Surface(name=app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity)/@0x66bcc94,currentBufferRatio=1.0,desiredRatio=1.0
> 08-13 11:27:39.238 19069 19069 D SurfaceView: 77306299 dispatchDraw mDrawFinished true isAboveParent false (mPrivateFlags & PFLAG_SKIP_DRAW) 128
> 08-13 11:27:39.238 19069 19069 D SurfaceView: 77306299 clearSurfaceViewPort mCornerRadius 0.0
> 08-13 11:27:39.243 19069 21761 D BLASTBufferQueue: [VRI[MainActivity]#13](f:0,a:1) acquireNextBufferLocked size=1080x2412 mFrameNumber=1 applyTransaction=true mTimestamp=43425662860776(auto) mPendingTransactions.size=0 graphicBufferId=81900731367460 transform=0
> 08-13 11:27:39.243 19069 21761 D VRI[MainActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
> 08-13 11:27:39.245 19069 19069 D VRI[MainActivity]: draw finished.
> 08-13 11:27:39.245 19069 19069 D VRI[MainActivity]: reportDrawFinished
> 08-13 11:27:39.246 19069 19069 D ViewRootImplExtImpl: setMaxDequeuedBufferCount: 2
> 08-13 11:27:39.246 19069 19069 I Quality : Skipped: false 1 cost 11.394218 refreshRate 8333801 bit true processName app.revanced.manager.flutter
> 08-13 11:27:39.258 19069 19069 D VRI[MainActivity]: onFocusEvent true
> 08-13 11:27:39.264 19069 21775 D BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#14](f:0,a:1) acquireNextBufferLocked size=1080x2412 mFrameNumber=1 applyTransaction=true mTimestamp=43425682896662(auto) mPendingTransactions.size=0 graphicBufferId=81900731367461 transform=0
> 08-13 11:27:40.264 19069 22671 D OplusScrollToTopManager: app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity,This DecorView@e0a3948[MainActivity] change focus to true
> 08-13 11:27:40.512 19069 19069 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=935.5, y[0]=2311.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=43426929, downTime=43426826, deviceId=2, source=0x1002, displayId=0, eventId=587397256 } handled by client, just return
> 08-13 11:27:41.195 19069 19069 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=916.5, y[0]=1656.75, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=43427614, downTime=43427499, deviceId=2, source=0x1002, displayId=0, eventId=1014363469 } handled by client, just return
> 08-13 11:27:42.688 19069 19069 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=811.5, y[0]=1698.5, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=43429107, downTime=43429005, deviceId=2, source=0x1002, displayId=0, eventId=969785441 } handled by client, just return
> 08-13 11:27:44.764 19069 19069 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=109.75, y[0]=1224.75, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=43431181, downTime=43431100, deviceId=2, source=0x1002, displayId=0, eventId=44111238 } handled by client, just return
> ```
> 
> ### Patch logs
> ```shell
> - Device Info
> ReVanced Manager: 1.21.2
> Model: RMX3472
> Android version: 14
> Supported architectures: arm64-v8a, armeabi-v7a, armeabi
> Root permissions: No
> 
> - Patch Info
> App: com.google.android.apps.photos v6.94.0.659749309 (Suggested: Any)
> Patches version: v4.12.0
> Patches added: Default
> Patches removed: None
> Default patch options changed: None
> 
> - Settings
> Allow changing patch selection: true
> Version compatibility check: true
> Show universal patches: false
> Patches source: revanced/revanced-patches
> Integration source: revanced/revanced-integrations
> 
> - Logs
> Reading APK
> Decoding app manifest
> Loading patches
> Merging integrations
> Deleting existing temporary files directory
> Decoding resources
> Executing patches
> Applied 2 patches
> Compiling patched dex files
> Compiled 8 dex files
> Compiling modified resources
> An error occurred:
> brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~VXBdXRjTMR7D3sueHKtNHA==/app.revanced.manager.flutter-utne6xueD6WP5_8kNwLedg==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BNXJFV/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BNXJFV/revanced-temporary-files/apk/build/resources.zip]
> 	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
> 	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
> 	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
> 	at app.revanced.patcher.Patcher.get(SourceFile:0)
> 	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:462)
> 	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
> 	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
> 	at java.lang.Thread.run(Thread.java:1012)
> Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~VXBdXRjTMR7D3sueHKtNHA==/app.revanced.manager.flutter-utne6xueD6WP5_8kNwLedg==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BNXJFV/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BNXJFV/revanced-temporary-files/apk/build/resources.zip]
> 	at brut.util.OS.exec(Unknown Source:75)
> 	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
> 	... 7 more
> Something went wrong:
> PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BNXJFV/out.apk' (OS Error: No such file or directory, errno = 2)
> ```
> 
> ### Acknowledgements
> * [x]  I have checked all open and closed bug reports and this is not a duplicate.
> * [x]  I have chosen an appropriate title.
> * [x]  All requested information has been provided properly.
> * [x]  The bug is only related to ReVanced Manager.

bro I am Having same problem

**Comment by MultimodeG** [comment]
same problem
