### ISSUE TITLE
feat(Flutter/Compose): Improve the message of incompatible installation

### ISSUE THREAD

**Issue by kitadai31** [ReVanced/revanced-manager#2140]
### Feature description

It says "Contact the developer of the app and ask for support."
However, in most cases, this is caused by the user has used the wrong APK.

I think this message can be like "Check if you are using a correct APK for your device and try again."
Or just only "The app is incompatible with this device." would be fine.

![installation_incompatible](https://github.com/user-attachments/assets/215fd7d7-b3e0-430c-a8a9-6d6d28d7380e)

This is related to compose manager for #1473 

### Motivation

In most cases, this is caused by the user has used the wrong architecture APK.
In this case, asking developer for support is wrong solution.
Therefore, this one sentence is no point.
I think the dialog should only contain instructions that actually lead to a solution.

(I know this may also happen when the device hardware does not meet \<uses-feature\>, but this is a rare case.)

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager.

**Comment by KobeW50** [comment]
What a lovely world :)
I cannot be happier

![image](https://github.com/user-attachments/assets/c22036fb-0c87-48a3-be0f-9aa60a14d39f)

**Comment by Ushie** [comment]
There's no restriction to how many repos you can fork, you just had to rename the repo when forking

**Comment by KobeW50** [comment]
inotia00's rvx manager repository is a fork of this repository, so GitHub considers my fork of inotia00's repository as a fork of this repository.

Here is a screenshot from the fork creation page.
![Screenshot_20240827_015507_Firefox](https://github.com/user-attachments/assets/e78cbbde-4774-49a2-86df-e8d42b8f497c)

**Comment by kitadai31** [comment]
@KobeW50 
> (Made a new GH account to PR for this, since my main account has a fork for inotia00's rvx-manager, which prevents me from creating a fork of this repo)

You don't have to that.
Both your RVX Manager fork and inotia00's RVX Manager belong to the "fork network" of ReVanced/revanced-manager.
So you can open a PR to ReVanced/revanced-manager directly from a fork of another fork.
(That's why GitHub restricts multiple creation of fork.)
Checkout the dev branch of ReVanced/revanced-manager, then create a new branch from the official dev branch, add changes, push the new branch to your fork, and open a PR.

Look this, I opened a PR to compose-dev branch from ReVanced Manager for Android 5-7 repository.
https://github.com/ReVanced/revanced-manager/pull/2147
https://github.com/kitadai31/revanced-manager-android5-7/tree/fix/keep-screen-on
