### ISSUE TITLE
bug:brut.common.BrutException

### ISSUE THREAD

**Issue by np84295** [ReVanced/revanced-manager#2142]
### Bug description

**An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~9eVt2X873U6hrflJIuBFNg==/app.revanced.manager.flutter-Fan930Ft9a-j0mtAlCHU0A==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-LJPSVO/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-LJPSVO/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:462)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~9eVt2X873U6hrflJIuBFNg==/app.revanced.manager.flutter-Fan930Ft9a-j0mtAlCHU0A==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-LJPSVO/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-LJPSVO/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more**

### Version of ReVanced Manager and version & name of app you are patching

- Device Info
ReVanced Manager: 1.21.2
Model: SM-S911B
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v4.13.2
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

[revanced-manager_logcat_20240816012424228918.log](https://github.com/user-attachments/files/16629766/revanced-manager_logcat_20240816012424228918.log)
![Snip](https://github.com/user-attachments/assets/1702cf24-40a4-4346-9dc6-74eb96024327)

### Installation method

Regular

### ReVanced Manager logs

```shell
Attached link
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by np84295** [comment]
> Patches 4.13.3 fixes this for YouTube
> https://github.com/ReVanced/revanced-patches/issues/3547
> 
> Issue is still present when patching Google Photos.
> 
> Patching with CLI does not have this issue.

Thanks !! Let me try

**Comment by np84295** [comment]
> Patches 4.13.3 fixes this for YouTube
> https://github.com/ReVanced/revanced-patches/issues/3547
> 
> Issue is still present when patching Google Photos.
> 
> Patching with CLI does not have this issue.

But where i can find the links for patch 
I could see only few files are updated on the thread but not patch file

**Comment by typecasto** [comment]
Still happening for me, even on 4.13.3

```
- Device Info
ReVanced Manager: 1.21.2
Model: moto g stylus 5G (2022)
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v4.13.3
Patches added: Change header, Custom branding
Patches removed: Copy video URL, Remove viewer discretion dialog, Disable precise seeking gesture, Seekbar tapping, Swipe controls, Disable auto captions, Hide autoplay button, Hide captions button, Hide player buttons, Comments, Hide endscreen cards, Hide filter bar, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Disable rolling number animations, Hide seekbar, Disable suggested video end screen, Hide timestamp, Disable player popup panels, Custom player overlay opacity, Restore old seekbar thumbnails, Spoof app version, Enable tablet layout, Always repeat, Disable zoom haptics, Remember video quality, Playback speed, GmsCore support
Default patch options changed: Theme [Dark theme background color: @android:color/system_neutral1_900]

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: anddea/revanced-patches
Integration source: anddea/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 32 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~sjQb_fbi-BHO6yGE51Fynw==/app.revanced.manager.flutter-30oA--p-aMLyzJ5TCiepgg==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BEYJEY/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL8610547322561586292.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BEYJEY/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BEYJEY/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BEYJEY/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:563)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:462)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~sjQb_fbi-BHO6yGE51Fynw==/app.revanced.manager.flutter-30oA--p-aMLyzJ5TCiepgg==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BEYJEY/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL8610547322561586292.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BEYJEY/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BEYJEY/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BEYJEY/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:542)
	... 7 more
```

**Comment by np84295** [comment]
Mine got fixed !!
Reinstall revanced manager and update the patch 
Allow the permissions before doing patching 

It took 3 re installation for the app to work properly
Was freezed almost all the time

**Comment by np84295** [comment]
> It's the latest release, [4.13.3](https://github.com/ReVanced/revanced-patches/releases/tag/v4.13.3)

Thanks buddy it did worked

**Comment by oSumAtrIX** [comment]
Anyone else experiencing the issue please try the new Compose manager: https://github.com/ReVanced/revanced-manager/actions/runs/10406703145/artifacts/1816419368

You will need to be logged into GitHub to download it. If you still get the error, send it & try the experimental and the multithreading toggle the advanced settings. If it errors out again, send the error logs.

**Comment by IntelCorei5-8350u** [comment]
Tried the debug manager with latest patches, v4.13.3 with different options, same issue with Gphotos v6.95.0. App patch options are default.

Logs with default advanced options:
`````
[INFO]: Merging integrations
[INFO]: Applying patches...
[INFO]: Merging integrations
[INFO]: Deleting existing temporary files directory
[INFO]: Decoding resources
[INFO]: Loading resource table...
[INFO]: Decoding file-resources...
[INFO]: Loading resource table from file: /data/user/0/app.revanced.manager.debug/cache/framework/1.apk
[INFO]: Decoding values */* XMLs...
[INFO]: Decoding AndroidManifest.xml with resources...
[INFO]: Regular manifest package...
[INFO]: Executing patches
[INFO]: GmsCore support succeeded
[INFO]: Spoof features succeeded
[INFO]: Writing patched files...
[INFO]: Compiling patched dex files
[INFO]: Compiled classes.dex
[INFO]: Compiled classes2.dex
[INFO]: Compiled classes3.dex
[INFO]: Compiled classes4.dex
[INFO]: Compiled classes5.dex
[INFO]: Compiled classes6.dex
[INFO]: Compiled classes7.dex
[INFO]: Compiled classes8.dex
[INFO]: Compiling modified resources
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-ar/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-ar/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-az/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-az/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-b+sr+Latn/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-b+sr+Latn/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-bg/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-bg/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-bn/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-bn/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-cs/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-cs/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-da/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-da/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-de/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-de/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-el/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-el/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-es/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-es/strings.xml: error: file failed to compile.
```


Logs with both multithreaded and experimental enabled
`
[INFO]: Memory limit: 700MB
[INFO]: Merging integrations
[INFO]: Applying patches...
[INFO]: Merging integrations
[INFO]: Deleting existing temporary files directory
[INFO]: Decoding resources
[INFO]: Loading resource table...
[INFO]: Decoding file-resources...
[INFO]: Loading resource table from file: /data/user/0/app.revanced.manager.debug/cache/framework/1.apk
[INFO]: Decoding values */* XMLs...
[INFO]: Decoding AndroidManifest.xml with resources...
[INFO]: Regular manifest package...
[INFO]: Executing patches
[INFO]: GmsCore support succeeded
[INFO]: Spoof features succeeded
[INFO]: Writing patched files...
[INFO]: Compiling patched dex files
[INFO]: Compiled classes.dex
[INFO]: Compiled classes2.dex
[INFO]: Compiled classes3.dex
[INFO]: Compiled classes4.dex
[INFO]: Compiled classes5.dex
[INFO]: Compiled classes6.dex
[INFO]: Compiled classes7.dex
[INFO]: Compiled classes8.dex
[INFO]: Compiling modified resources
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-ar/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-ar/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-az/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-az/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-b+sr+Latn/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-b+sr+Latn/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-bg/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-bg/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-bn/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-bn/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-cs/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-cs/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-da/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-da/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-de/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-de/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-el/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-el/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-es/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-es/strings.xml: error: file failed to compile.
```
Logs with none enabled
```
[INFO]: Merging integrations
[INFO]: Applying patches...
[INFO]: Merging integrations
[INFO]: Deleting existing temporary files directory
[INFO]: Decoding resources
[INFO]: Loading resource table...
[INFO]: Decoding file-resources...
[INFO]: Loading resource table from file: /data/user/0/app.revanced.manager.debug/cache/framework/1.apk
[INFO]: Decoding values */* XMLs...
[INFO]: Decoding AndroidManifest.xml with resources...
[INFO]: Regular manifest package...
[INFO]: Executing patches
[INFO]: GmsCore support succeeded
[INFO]: Spoof features succeeded
[INFO]: Writing patched files...
[INFO]: Compiling patched dex files
[INFO]: Compiled classes.dex
[INFO]: Compiled classes2.dex
[INFO]: Compiled classes3.dex
[INFO]: Compiled classes4.dex
[INFO]: Compiled classes5.dex
[INFO]: Compiled classes6.dex
[INFO]: Compiling modified resources
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-ar/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-ar/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-az/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-az/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-b+sr+Latn/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-b+sr+Latn/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-bg/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-bg/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-bn/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-bn/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-cs/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-cs/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-da/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-da/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-de/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-de/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-el/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-el/strings.xml: error: file failed to compile.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-es/strings.xml:0: error: xml parser error: reference to invalid character number.
[WARN]: /data/user/0/app.revanced.manager.debug/app_ephemeral/patcher/apk/res/values-es/strings.xml: error: file failed to compile.
```
The other option with experimental on and multithreaded off has the same result.

**Comment by oSumAtrIX** [comment]
I think this is some regional issue. I remember a similar issue from a past time which we solved by explicitly setting the local in the code, otherwise on chinese locales CLI would spit an error (iirc aapt). So affected users should try setting their language to English and confirm this hypothesis

**Comment by oSumAtrIX** [comment]
> Figuring out why this works on CLI but fails when running in Manager is the best answer.

Perhaps it's an issue with where AAPT is running. Have you tried running CLI via a terminal emulator like termux? You need to pass an AAPT binary compiled for your arch, preferably the ones checked in Managers source (or compile from source https://github.com/revanced/aapt2)

**Comment by oSumAtrIX** [comment]
Are the decoded strings.xml files same? Maybe the issue occurs at decoding, not compiling.

**Comment by oSumAtrIX** [comment]
It creates a temporary folder under /data/data/<application-path>/cache. You'd need to have root access on your Android emulator to read that folder via another app like a file manager.

**Comment by Einheit-101** [comment]
I am using latest 1.21.2 manager and 19.16.39 youtube and it still aborts with the error even when using patch version 4.13.3. So there is absolutely no fix at least for me.

**Comment by avinashkarhana** [comment]
Exactly same issue, no solution worked

**Comment by MerBudd** [comment]
Seems like the issue on Photos is related to the GmsCore patch specifically, every other patch other than GmsCore works fine but GmsCore causes the error for some reason.

**Comment by oSumAtrIX** [comment]
Try any resource patch such as change package name patch

**Comment by np84295** [comment]
> Mine got fixed !!
> Reinstall revanced manager and update the patch 
> Allow the permissions before doing patching 
> 
> It took 3 re installation for the app to work properly
> Was freezed almost all the time 

@Einheit-101 @avinashkarhana @MerBudd

**Comment by MerBudd** [comment]
> Try any resource patch such as change package name patch

Yeah they work too I already checked

**Comment by oSumAtrIX** [comment]
Interesting, reach out to photo+gmscore@revanced.app so we can test changes and see if it fixes the issue

**Comment by MerBudd** [comment]
> Interesting, reach out to photo+gmscore@revanced.app so we can test changes and see if it fixes the issue

Hmm, and what should I write to them? I didn't even know they had an e-mail address like that.

**Comment by CiRiX-** [comment]
Any updated on this?

**Comment by covid696969** [comment]
Can someone from the ReVanced team shed some light on when this issue might be fixed? I’ve spent hours trying to figure it out – tested different versions of the Google Photos APK from various sources and even tried it on three different stock Android phones (Android 14, 13, and 8.1) – but still no luck.

- Device Info
ReVanced Manager: 1.22.0
Model: moto g84 5G
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.photos v6.97.0.671023488 (Suggested: Any)
Patches version: v4.13.3
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 3 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~Gnoy4eMlOtb1JFSorieYrQ==/app.revanced.manager.flutter-y1fRNlRFCXGdjXVtL5Acfw==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-WYASVH/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-WYASVH/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~Gnoy4eMlOtb1JFSorieYrQ==/app.revanced.manager.flutter-y1fRNlRFCXGdjXVtL5Acfw==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-WYASVH/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-WYASVH/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/files/patcher/tmp-WYASVH/out.apk' (OS Error: No such file or directory, errno = 2)

**Comment by oSumAtrIX** [comment]
@np84295 https://github.com/ReVanced/revanced-manager/issues/2192#issuecomment-2333319258 please do what's described in this discussion.

**Comment by Anujkaushik01** [comment]
I noticed that if you only apply 'spoof features' to Google photos then it succeeded with compiling but the apk doesn't installs and says installation failed (though I have already uninstalled pre-built photos app with adb). And if I select 'GmsCore support' patch then it also patches another patch automatically which is 'Change package name' and throws an error (errno 2)mostly at 'compiling modified resources'. 
I have tried different versions of revanced manager with/without default patches and settings.
The latest version that I can successfully compile with both patches is '6.40.0.540337868-release 48363351' after this version, every patch shows an error.

**Comment by IntelCorei5-8350u** [comment]
- Device Info
ReVanced Manager: 1.22.0
Model: A101SH
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.photos v6.98.0.670003362 (Suggested: Any)
Patches version: v4.13.3
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 3 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~pq1DXtqxr8tHcdEwjezbEQ==/app.revanced.manager.flutter-oRzi3BOoUVTpn4NRylOxaw==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-KIAVUA/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-KIAVUA/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~pq1DXtqxr8tHcdEwjezbEQ==/app.revanced.manager.flutter-oRzi3BOoUVTpn4NRylOxaw==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-KIAVUA/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-KIAVUA/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/files/patcher/tmp-KIAVUA/out.apk' (OS Error: No such file or directory, errno = 2)

Manager Data was cleared, all patching options were selected.

**Comment by IntelCorei5-8350u** [comment]
> I noticed that if you only apply 'spoof features' to Google photos then it succeeded with compiling but the apk doesn't installs and says installation failed (though I have already uninstalled pre-built photos app with adb). And if I select 'GmsCore support' patch then it also patches another patch automatically which is 'Change package name' and throws an error (errno 2)mostly at 'compiling modified resources'. I have tried different versions of revanced manager with/without default patches and settings. The latest version that I can successfully compile with both patches is '6.40.0.540337868-release 48363351' after this version, every patch shows an error.

I can confirm that version worked.

**Comment by jddcef** [comment]
> Patching using CLI tools in Termux works without problems. I guess that is expected since it's still running in a Java JRE which makes it the same as patching on a computer.

Yes, using Termux Monet to run Revancify script worked for me perfectly, even the latest photos version is auto pulled. Official app for revanced failed on different devices that I tested with.
I just had to install the compiled apk from file manager.

**Comment by Anujkaushik01** [comment]
> > Patching using CLI tools in Termux works without problems. I guess that is expected since it's still running in a Java JRE which makes it the same as patching on a computer.
> 
> Yes, using Termux Monet to run Revancify script worked for me perfectly, even the latest photos version is auto pulled. Official app for revanced failed on different devices that I tested with. I just had to install the compiled apk from file manager.

Can you please tell the instructions to do it? I and others also want to patch latest photos app.

**Comment by oSumAtrIX** [comment]
Such tools are not supported here. You can use ReVanced CLI and follow it's documentation for usage instructions

**Comment by jddcef** [comment]
> > > Patching using CLI tools in Termux works without problems. I guess that is expected since it's still running in a Java JRE which makes it the same as patching on a computer.
> > 
> > 
> > Yes, using Termux Monet to run Revancify script worked for me perfectly, even the latest photos version is auto pulled. Official app for revanced failed on different devices that I tested with. I just had to install the compiled apk from file manager.
> 
> Can you please tell the instructions to do it? I and others also want to patch latest photos app.

1. Install Termux:Monet from [github ](https://github.com/Termux-Monet/termux-monet/releases)(download and install the apk from its Releases, it still works even though not maintained).
2. Open Termux:Monet, and install [Revancify](https://github.com/decipher3114/Revancify)  (basically, Copy and paste this command into it  `curl -sL "https://raw.githubusercontent.com/decipher3114/Revancify/main/install.sh" | bash`
3. After installation, type `revancify` in termux and press enter.
The rest is just following the instructions, pressing the arrows up and down etc to go through the menus.
