### ISSUE TITLE
bug (compose): Not able to rename patches like old

### ISSUE THREAD

**Issue by vippium** [ReVanced/revanced-manager#2152]
### Bug description

In latest Compose version, there is no way to rename the patches. It helps us to early find the appropriate developer patches. Previously, we can rename the patch name from `Revanced Patches` to anything, like `inotia patches`. But it is not possible in latest version of compose.

### Version of ReVanced Manager and version & name of app you are patching

Latest Action

### Installation method

Regular

### ReVanced Manager logs

```shell
...
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
The name of patches comes from the api. Api does not supply dev patches. Local patches should be nameable

**Comment by vippium** [comment]
> The name of patches comes from the api. Api does not supply dev patches. Local patches should be nameable

But it can be done previously with API too. I think that it is removed in latest one. I'll share a SS of that.

**Comment by oSumAtrIX** [comment]
v2 is deprecated

**Comment by vippium** [comment]
https://github.com/user-attachments/assets/c53e7c75-63cf-44e7-8592-2c1ecf26a75b

Like this. This is from version 2.

> v2 is deprecated

I think it should be there as it is very useful. If we have more than 2 or 3 Patches API. Using that, we can directly separate and distinguish b/w different patches.

**Comment by vippium** [comment]
As in the rec. This will directly help. As all patches have same name i.e. `Revanced Patches`. This will confuse user so much. The feature must be ported from there. I think it can be possible.

**Comment by oSumAtrIX** [comment]
dev branch is not a production branch like a beta channel. The name is specified in the manifest file. If your patches don't have a proper name, you need to fix it on your end

**Comment by kitadai31** [comment]
> Local patches should be nameable

After https://github.com/ReVanced/revanced-manager/commit/edb4e421e26bdaadc9795066185a0edf45a5d224, local patches also lost the ability to rename

**Comment by Ushie** [comment]
ReVanced Manager reads the patch bundle name from the patch bundle itself, the developer needs to change the name of their bundle in the manifest

This issue comes from the fact that they have forked the ReVanced Patches repo instead of using the patch bundle template
