### ISSUE TITLE
feat(compose): Add ability to download split-apk for patching other revanced apps

### ISSUE THREAD

**Issue by vippium** [ReVanced/revanced-manager#2153]
### Feature description

In future release, if there can be a support for split apk, then it will be great. 

### Motivation

This will help users to patch other revanced apps like Google Recorder, etc which only supports split apk directly from the manager.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
Split apks are not supported by Patcher, therefore not by Manager
