### ISSUE TITLE
bug (ReVanced Manager compose): Sometime shows dev patches

### ISSUE THREAD

**Issue by MarcaDian** [ReVanced/revanced-manager#2156]
### Bug description

I don't know if it's a bug, but sometimes the manager shows dev patches. Later, release patches are shown again.

Yesterday:
![Screenshot_2024-08-19-23-05-47-257_app revanced manager debug](https://github.com/user-attachments/assets/831e05c6-ff4f-4840-a1ff-022d80a2e829)

Today:
![Screenshot_2024-08-21-00-54-35-669_app revanced manager debug](https://github.com/user-attachments/assets/388b4e77-b2b5-4961-973c-5542a9572324)

### Version of ReVanced Manager and version & name of app you are patching

Last compose

### Installation method

None

### ReVanced Manager logs

```shell
NaN
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by Axelen123** [comment]
@oSumAtrIX I am pretty sure the previous API implementation didn't return prereleases unless you enabled it with a parameter. This seems like an API issue.

**Comment by oSumAtrIX** [comment]
v3 is not supplying any pre releases anymore so switching to it from v2 should fix the issue on Managers end.

**Comment by MarcaDian** [comment]
I think it can be closed.
