### ISSUE TITLE
feat: Ability to switch to dev patches for Revanced Patches without adding new bundle

### ISSUE THREAD

**Issue by vippium** [ReVanced/revanced-manager#2162]
### Feature description

There can be a ability or toggle to activate the dev patches in default revanced patches, instead of adding new dev bundles.

### Motivation

This will directly allow user to switch to dev patches for default bundle. Rather than adding new bundle for the default.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
dev patches won't be available in manager in the future. They are for development purposes and not production.
