### ISSUE TITLE
bug: [ROOT] [HYPEROS] After shutdown YouTube breaks.

### ISSUE THREAD

**Issue by deniskqa** [ReVanced/revanced-manager#2167]
### Bug description

Step 1: Install YouTube ReVanced via mount in manager.
Step 2: Restart your phone via shut dow and turn on or via hard reset.
Step 3: Try to run YouTube 

### Error logs

```shell
java.lang.UnsatisfiedLinkError: dlopen failed: library "libelements.so" not found

at

java.lang.Runtime.loadLibrary0 (Runtime.java:1082)

at

java.lang.Runtime.loadLibrary0 (Runtime.java:1003) at java.lang.System.loadLibrary (System.java:1661)

at fyf.<clinit>(PG:21)

at java.lang.Class.newInstance(Native Method)

at

android.app.AppComponentFactory.instantiateAppl ication(Unknown Source:4)

at

androidx.core.app.CoreComponentFactory.instantia teApplication (PG:1)

at

android.app.Instrumentation.newApplication(Unkn own Source:8)

at

android.app.LoadedApk.makeApplicationInner (Unk nown Source:174)

at

android.app.LoadedApk.makeApplicationInner(Unk nown Source:1)

at

android.app.ActivityThread.handle BindApplication( Unknown Source:867)

at android.app.ActivityThread.-$ $Nest$mhandleBindApplication(Unknown

Source:0)

at

android.app.ActivityThread$H.handleMessage(Unk nown Source:1082)
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Did you install a full APK beforehand?

**Comment by deniskqa** [comment]
Yes.

**Comment by oSumAtrIX** [comment]
Run `pm path com.google.android.youtube` in your terminal, send the output.
Run `mount | grep youtube` and send the output.
CD into `data/adb/service.d` and run the mount script at last, check if it makes any difference.
Unmount the patched app by running the unmount command that's also present in the mount script, see if that fixes launching the app.
At last try adding `sleep 100` at the beginning to the mount script to sleep for 100 seconds to check if the issue is caused by some timing issue which Android doesn't like.

**Comment by deniskqa** [comment]
`pm path com.google.android.youtube` return nothing 
After `mount | grep youtube` returns `/dev/block/dm-43 on /data/app/~~4jfJATdnGwCUK1Nh3pd74g==/com.google.android.apps.youtube.music-AHoQ0u54kWF49VY6_wPlFA==/base.apk type f2fs (rw,lazytime,seclabel,nosuid,nodev,noatime,background_gc=on,discard,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,flush_merge,extent_cache,mode=adaptive,active_logs=6,reserve_root=32768,resuid=0,resgid=1065,inlinecrypt,alloc_mode=default,checkpoint_merge,fsync_mode=nobarrier,discard_unit=block,memory=normal)
Running the script: Nothing changed.
Unmounting app: not helped
Adding sleep 100 into script: Same

**Comment by oSumAtrIX** [comment]
Remove the mount script (or move the mount script out of that folder) and reboot, check if youtube launches.

**Comment by deniskqa** [comment]
1. Nothing 
2. /dev/block/dm-43 on /data/app/~~4jfJATdnGwCUK1Nh3pd74g==/com.google.android.apps.youtube.music-AHoQ0u54kWF49VY6_wPlFA==/base.apk type f2fs (rw,lazytime,seclabel,nosuid,nodev,noatime,background_gc=on,discard,no_heap,user_xattr,inline_xattr,acl,inline_data,inline_dentry,flush_merge,extent_cache,mode=adaptive,active_logs=6,reserve_root=32768,resuid=0,resgid=1065,inlinecrypt,alloc_mode=default,checkpoint_merge,fsync_mode=nobarrier,discard_unit=block,memory=normal)
3. Running script manually doesn't help
4. Unmounting doesn't help
5. Adding sleep 100 doesn't help

**Comment by deniskqa** [comment]
I removed script, not helped.

**Comment by oSumAtrIX** [comment]
Reboot again and check if it helps, if not, as you can see ReVanced isn't active and your app is still breaking. Try installing YouTube after your phone reboots again

**Comment by deniskqa** [comment]
Reinstalling and repatching helps.

**Comment by oSumAtrIX** [comment]
Not sure what you mean, but reboot the device and check if it works

**Comment by deniskqa** [comment]
Suddenly, all fixed! Now after reset YouTube not breaking.
