### ISSUE TITLE
feat: Disable High Comtrast YT UI

### ISSUE THREAD

**Issue by arichorn** [revanced/revanced-manager#217]
### Type

Cosmetic

### Branch

Flutter

### Issue

I think YouTube Revanced needs to have at least an option to improve the UI by removing some of the High Contrast Elements of the app.

### Feature

It’s not fully a new feature, I’m just trying to give everyone like me a new toggle on ReVanced their way of being able to reduce High Contrast in Dark Mode/Light Mode. Ever since August 2020, YouTube changed the way the UI should’ve looked which effects a lot of texts with new contrast icons, settings being brighter/darker and eye strain across the UI, not all of the UI will be modified since some elements of the app uses server side stuff but either way it still improves the UI and really deserves a feature.

### Motivation

Prevent Eye Strainage or any other eye problems, headaches and some others that I can’t confirm and definitely makes ReVanced like it is today! ⭐️

### Additional context

An image of It in OLED Mode
![68CCF927-86EB-468A-9CAF-58FEFABB0F1D](https://user-images.githubusercontent.com/78001398/190920695-b8f05886-205a-4bde-8e2b-3eb2b422c70d.jpeg)

colors that should help the ReVanced team. ⬇️
TextPrimary+TextSecondary YT Dark/OLED Mode Hex Code: #909090
TextPrimary+TextSecondary YT Light Mode Hex Code: #606060

**Comment by Aunali321** [comment]
Not in manager's scope. Open a request in revanced-patches.

**Comment by arichorn** [comment]
I’m sorry. I’m stupid alright but I did what you said and moved it here https://github.com/revanced/revanced-patches/issues/#530
