### ISSUE TITLE
feat: Please add Change package name option 

### ISSUE THREAD

**Issue by vivekguthikonda** [ReVanced/revanced-manager#2170]
### Feature description

I have seen "Change package name" option in Revanced Manager Compose 0.0.1
Can you please add it to current manager.

### Motivation

- We can have custom package name so that we can have features that only some apps support like Display enhancement, memc etc if we change any package name present in list of supported apps..we can get that feature working in Revanced too

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
That patch already exists as a universal patch you can enable in the settings
