### ISSUE TITLE
Hide Home advertising suggestions 

### ISSUE THREAD

**Issue by smgchosen** [revanced/revanced-manager#218]
### Type

Other

### Branch

Hi everybody. Do you know how to hide advertising suggestions in home page? 
![Screenshot_20220918_193950](https://user-images.githubusercontent.com/55053403/190921038-1f4e0eb3-e6ed-44ad-bf21-82406b6fc9cf.jpg)

### Issue

I don't need advertising suggestions. 

### Feature

Hide home advertising suggestions 

### Motivation

I don't like advertising

**Comment by Aunali321** [comment]
Not a manager issue. Open the issue on revanced-patches.

**Comment by smgchosen** [comment]
I'm stupid, it's exactly that I wanted like to do, but I selected manager issue! Thx

**Comment by arichorn** [comment]
I was stupid too smgchosen but I moved it my previous suggestion in revanced-patches
