### ISSUE TITLE
bug: Manager not downloading APK

### ISSUE THREAD

**Issue by vippium** [ReVanced/revanced-manager#2184]
### Bug description

![Screenshot_20240901_100059](https://github.com/user-attachments/assets/ea4180eb-28b3-47bd-b00d-11611e5bb186)

### Version of ReVanced Manager and version & name of app you are patching

Latest Action

### Installation method

Regular

### ReVanced Manager logs

```shell
... Already in Screenshot
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by Ushie** [comment]
This is an issue with the experimental APKMirror plugin, which isn't going to be in the final result

**Comment by vippium** [comment]
So when we'll be able to download it in debug releases(action) now? As final result is far away
