### ISSUE TITLE
feat: Add options to export & import manager's settings

### ISSUE THREAD

**Issue by Kuddus73** [ReVanced/revanced-manager#2196]
### Motivation

The process will be much faster when you need to uninstall and reinstall the manager.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager.

**Comment by YarosMallorca** [comment]
This can be closed already as implemented in #2268
