### ISSUE TITLE
bug: invalid request to oath API

### ISSUE THREAD

**Issue by Dwtsed** [ReVanced/revanced-manager#2197]
### Bug description

Attempted to patch RIF then Boost, using separate Reddit apps for each with separate keys. Login redirect to Reddit within both apps either flags wrong password (RIF) or server error, and with Boost it states oath error.

### Version of ReVanced Manager and version & name of app you are patching

![Screenshot_20240908_064628_Boost](https://github.com/user-attachments/assets/118cdf01-a5fe-48d1-b056-d7f15e34c2c7)
1.21.1
[revanced-manager_logcat_20240908070058255043.log](https://github.com/user-attachments/files/16919926/revanced-manager_logcat_20240908070058255043.log)

### Installation method

Mount

### ReVanced Manager logs

```shell
Tried to paste but file too long. Attached separately
```

### Patch logs

```shell
See attached
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by KobeW50** [comment]
Seek help on one of the ReVanced support platforms, which can be found at https://revanced.app

This is not a ReVanced Manager bug.
