### ISSUE TITLE
feat: Store patch selection separately for each source

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#2198]
### Feature description

Currently, if a user saves a patch selection while using one patch source and then switches to a different source, the patch selection will only include the patches that share the same name as the selected patches from the first source.

> Example: Imagine while using the ReVanced patches I set the patch selection for YouTube to include the `Hide ads` and `Announcements` patches. I then switch the source to inotia00's patches. The patch selection for YouTube will just be the `Hide ads` patch, instead of the Default patch selection or the patch selection I set the last time I used inotia00's patches.

**Feature**

Save the patch selection for each source separately. If a user switches to a source that has never been used, the default patches should be selected. If a user switches to a source that they have used in the past, the patch selection should be the same as what they left it as the last time they used this source.

When the `Export patch selection` option is used, the highest level of organization in the JSON should be the source. 

Ideally, when the `Import patch selection` option is used, the manager should be backwards compatible with the old JSON format.

### Motivation

The current behavior of the Manager is not intuitive and less useful than the proposed behavior in this request.

The use case is given in the example above.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
Every patch will have it's selection distinctively by patch bundle in the compose version.

**Comment by Axelen123** [comment]
Is this for flutter manager or compose?

**Comment by Ushie** [comment]
Flutter

**Comment by KobeW50** [comment]
It is aimed for the flutter manager, while it is still the main manager. IK priority has shifted to the compose manager, so if this festure request will not be completed for flutter, it can be closed as not planned.
