### ISSUE TITLE
Full screen section and "hide end cards on full screen" option are missing

### ISSUE THREAD

**Issue by WilliamTael** [ReVanced/revanced-manager#2209]
### Feature description

Full screen section and "hide end cards on full screen" option are missing.

### Motivation

These features were available in previous versions.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
The first never existed, the second one existe

**Comment by WilliamTael** [comment]
Full screen section under Revanced section inside the YouTube Revanced app.
It existed. I was just using Inotia00 patched version a while ago before
using default Revanced Manager.

Em seg., 9 de set. de 2024 23:22, oSumAtrIX ***@***.***>
escreveu:

**Comment by oSumAtrIX** [comment]
This is ReVanced, unofficial patches are not supported here.
