### ISSUE TITLE
Manager crashes (?) while patching

### ISSUE THREAD

**Issue by Vexz00** [revanced/revanced-manager#221]
Manager version: v0.0.13

I've been trying to patch the YouTube app but I think the manager is crashing during the compilation process. The reason why I'm not sure about that is because the manager closes but I can still see the notification that says it's patching. But when I tap on the notification I don't see it patching anymore. Maybe I'm just doing something wrong?

I hope the logs help:
https://pastebin.com/76YGx9fJ

**Comment by Aunali321** [comment]
Please open the issue again with the proper template. Also include yt version and where did you download it from.
