### ISSUE TITLE
bug: 'Patches removed' warning shows patches that were renamed

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVanced/revanced-manager#2210]
### Bug description

https://github.com/orgs/ReVanced/discussions/1071

![Not the end of the world](https://github.com/user-attachments/assets/2979cc0f-d72c-4ea2-b1e3-874c1a66599f)

Users are regularly confused by this warning when a patch is not removed but instead is renamed.

The simplest solution is if new patches were also added then this prompt should also show the patches added.

### Version of ReVanced Manager and version & name of app you are patching

All

### Installation method

None

### ReVanced Manager logs

```shell
Na
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
The issue is that it does not show that patches were added at the same time. The issue is that Manager can not distinguish between deleted and renamed patches, so a rename is a delete & add at the same time, whereas the old name was deleted and the new name was added.

**Comment by oSumAtrIX** [comment]
This should be a feature request and not a bug report.

**Comment by oSumAtrIX** [comment]
Created here: https://github.com/ReVanced/revanced-manager/issues/2212
