### ISSUE TITLE
bug: unable to install on Pico 4 headset

### ISSUE THREAD

**Issue by NightShadow02** [ReVanced/revanced-manager#2211]
### Bug description

unable to install on pico 4 headset, installation fails

using default patches and recommended youtube .apk

here is the revanced manager log: 
[revanced-manager_logcat_20240911021632565368[1].log](https://github.com/user-attachments/files/16949207/revanced-manager_logcat_20240911021632565368.1.log)

### Version of ReVanced Manager and version & name of app you are patching

latest version of revanced manager on revanced.app/download and recommended version of youtube from apkmirror

### Installation method

Regular

### ReVanced Manager logs

```shell
--------- beginning of main
09-11 01:48:47.872 12579 12579 I chatty  : uid=10131(app.revanced.manager.flutter) expire 32 lines
09-11 01:48:47.888 12579 14582 I chatty  : uid=10131(app.revanced.manager.flutter) Binder:12579_1 expire 3 lines
09-11 01:48:47.889 12579 14583 I chatty  : uid=10131(app.revanced.manager.flutter) Binder:12579_2 expire 7 lines
09-11 01:48:47.925 12579 14587 I chatty  : uid=10131(app.revanced.manager.flutter) Binder:12579_3 expire 3 lines
09-11 01:48:47.944 12579 

incomplete log because the issue form template seems to be unable to allow something this long. please check Bug description above for attachment
```

### Patch logs

```shell
https://pastebin.com/Gib64biu
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-manager/issues/2142
