### ISSUE TITLE
feat: more instagram patches

### ISSUE THREAD

**Issue by alreadyhaveanaccount-signin** [ReVanced/revanced-manager#2213]
### Feature description

it'd be nice if we got more patches on instagram, considering that the only one we have right now is hiding ads, here is a list of suggestions I made

Adding custom themes to chat
Adding story Fonts (from device storage)
Changing the speed of a reel/voice message
Copy Caption
Copy Comments
Disable auto-opening the next story
Download Posts
Ghost Mode
Hide call button
Hide typing indicator for everyone
Hide video call button
Material You
Opening links with the default system browser
Pinning more than three chats
Remove reels on the explore page
Remove reels page
Removing reels on the home page
Rounded posts on the story
Show ReVanced settings
Show deleted messages (something like this)
![Untitled717_20240906134332](https://github.com/user-attachments/assets/06345597-9147-484b-86ba-8ed8f66fde4e)

Showing Image Albums in the story
![Screenshot_20240912_223420_Instagram](https://github.com/user-attachments/assets/55b86b31-12d2-4ff7-b4fc-4172465fce99)

### Motivation

most Instagram modded/patched apps are closed-source, have stolen code, ad-infested, full of bugs or just outdated, some examples of these include

Honista - full of bugs, most of its code is stolen from sunista, and is full of ads
Aeroinsta - stolen code
Instander - outdated (I think)

why?
• adding custom themes, fonts (in stories) and material you makes people more able to personalize the app more
• Changing reels/voice messages speed would give users more flexibility, for example; a person who wants to play a voice message fast because he needs to do something important
• Copying comments/captions would be a useful feature when you want to type other comments/a post's caption without having to type it manually
• disabling auto-opening the next story would be a good feature because sometimes when you want to view one story it opens the next one so there should be an option for disabling this
• downloading posts can be a useful feature and is faster than going to a third party site, 
You could use seal for that since it supports instagram posts, also it downloads the videos without watermarks
• ghost mode would be a good feature for people who don't want to be seen when seeing a person's story, or when active
• hiding both the call and video call buttons would be useful, sometimes my hand slips and I click on them by accident
• hiding the typing indicator for everyone would be a useful feature if you don't want to see if somebody is typing or not
• opening links with the default browser is better and convenient since in instagram's built in browser does not feature desktop mode or auto-signing in
• pinning more than 3 chats would give easy access to a user's chats if he has lots of them
• Removing the reels page or reels from the explore page would be useful to stop people from getting distracted sometimes
• making the posts/reels Rounded on the edges provides a modern look and would be nice if it was added
• show revanced settings in the app so the person can toggle on/off patches  (eg. ghost mode, material you, etc)
• showing deleted messages allows showing messages that were deleted accidentally 
• showing image albums when adding an image sticker to a story would be useful since unfortunately instagram does not have this feature

also as I mentioned earlier, there is no patches except one for hiding ads

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager.

**Comment by alreadyhaveanaccount-signin** [comment]
the first image is what I think the deleted messages should look like
The second is because there is no albums when adding an image sticker

**Comment by KobeW50** [comment]
This is unrelated to the ReVanced Manager. Patches requests can be made in the revanced-patches repository
