### ISSUE TITLE
Inbuilt apk extractor

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [ReVanced/revanced-manager#2214]
### Feature description

I want to patch an third party app for which revanced has universal patch but being a non root user i cant directly patch it and need the apk and when i try to use other apk extractor idk why but the extracted apk does not get installed even when im on A10 a less retricted android version. So inbuilt apk extractor would be nice

### Motivation

This removee the hassle of using other apk extractor for non superusers and would make the revanced manager a go to patcher easily.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
Non split apks can be selected regularly

**Comment by ALMIGHTY-VC** [comment]
> Non split apks can be selected regularly

Know but the non split apk i extract using third party apk extractor the extracted apks dont even install even without patches idk why thats why i needed an apk extractor in revanced manager thanks for your time

**Comment by oSumAtrIX** [comment]
ReVanced Manager is an application to patch apps, not an APK extractor

**Comment by ALMIGHTY-VC** [comment]
> ReVanced Manager is an application to patch apps, not an APK extractor

I know im taking but just to make it clear with apk extractor it would be a complete patching tool from choosing the app we need to patch apk's then to pathcing it and installing it hope you get my point i just want some additional feature in addition to patching
