### ISSUE TITLE
feat: add proxy

### ISSUE THREAD

**Issue by optimatrix0** [ReVanced/revanced-manager#2220]
### Motivation

This feature would greatly enhance the privacy of user data, all I'm asking is to add the ability for the user to provide their own proxy.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [ ] The feature request is only related to ReVanced Manager.

**Comment by optimatrix0** [comment]
Proxi sock5 or http

**Comment by optimatrix0** [comment]
I apologize if I did something wrong, but I'm still getting the hang of this platform and I don't see it.

**Comment by oSumAtrIX** [comment]
Not sure wym but a proxy doesn't change anything and if you need it for whatever reason you can use a vpn

**Comment by optimatrix0** [comment]
I know that this project cares about user privacy, so that's why I ask for this, but sometimes the user just doesn't use it because they don't think it's safe to reveal their IP and can't use a VPN, so you can help.

**Comment by optimatrix0** [comment]
Think about those users who, if they activate VPN on their devices, some certain banking services or something like that may stop working, so in order not to compromise access to other services, please

**Comment by oSumAtrIX** [comment]
Activate the VPN when you use ReVanced Manager, disable it when you don't.
