### ISSUE TITLE
Not installed patch

### ISSUE THREAD

**Issue by Mrunknow3** [ReVanced/revanced-manager#2223]
### Bug description

- Device Info
ReVanced Manager: 1.22.1-dev.2
Model: 2201117PI
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v4.14.1
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 60 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Aligning APK
Signing APK
Patched APK
Installing patched app
Installation failed
Installing patched app
Installation failed

### Version of ReVanced Manager and version & name of app you are patching

Latest

### Installation method

Regular

### ReVanced Manager logs

```shell
Nothing
```

### Patch logs

```shell
Nothing
```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
Send manager logs

**Comment by Mrunknow3** [comment]
Now working I'm closing this issue.

**Comment by oSumAtrIX** [comment]
Please add the logs as requested three times now already

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-manager/issues/2223

**Comment by KobeW50** [comment]
> #2224

This issue (2223) has "Installation failed" printed in the patch log, while 2224 has "Installation canceled" printed in the log

**Comment by oSumAtrIX** [comment]
Could be related because both are resolved by similar actions
