### ISSUE TITLE
feat: A Patch That remove the Addicting Horizontal-Scrolling on Reddit Video player

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [ReVanced/revanced-manager#2225]
### Feature description

Reddit added a feature where scrolling sideways when you click on a video/picture show you more of them. 
It can be addicting, and it would be great if there is a patch which will remove the feature.

### Motivation

- Why should this feature be implemented?
     The same reason shorts can be disabled in YouTube ReVanced. To stop people from scrolling for hours and become addicted
- What are the benefits?
     Combat addictions
- What makes this feature important?
     To stop people from scrolling for hours on the videos

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager.

**Comment by KobeW50** [comment]
Patch requests belong in the revanced-patches repository 

https://github.com/ReVanced/revanced-patches

**Comment by ImGGAAVVIINN** [comment]
sorry
