### ISSUE TITLE
feat: 4k downloads support

### ISSUE THREAD

**Issue by gamerfunky78** [ReVanced/revanced-manager#2227]
### Feature description

an addition to 4k video and more qualities added should be really helpful for a lot of people

### Motivation

4k video downloads are not on the default youtube app and an addition to this  makes the app unique.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] The feature request is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
You can use the existing external downloader.

**Comment by gamerfunky78** [comment]
isnt that troublesome as some users want to be organised ,external downloads have cons too since they can fail unlike downloading them while in the app.

**Comment by oSumAtrIX** [comment]
Choosers can't be beggars. External downloading is good enough

**Comment by gamerfunky78** [comment]
i guess it is then, sadly the main reason i downloaded the app was because i thought it supports higher downloading quality options atleast even 720p. but its still good i guess i just wanted to mention it
