### ISSUE TITLE
bug: Android VR client not working in Spoof Video Stream.

### ISSUE THREAD

**Issue by njihil** [ReVanced/revanced-manager#2245]
### Bug description

When the default client is selected to 'Android VR', no kind of video play, but with IOS as the default client, it works but the side effects of the IOS client got me crazy (stream opening from the very start).

### Version of ReVanced Manager and version & name of app you are patching

Android Version: 14 (with Realme UI 5.0)
ReVanced Manager Version: 1.22.0
Youtube Version: 19.16.39 (as recommended by the RV manager)

### Installation method

None

### ReVanced Manager logs

--------- beginning of main
10-04 12:18:01.565  9279  9279 E manager.flutter: Unknown bits set in runtime_flags: 0x40000000
10-04 12:18:01.565  9279  9279 I manager.flutter: Using CollectorTypeCC GC.
10-04 12:18:01.570  9279  9279 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
10-04 12:18:01.579  9279  9279 D nativeloader: Load libframework-connectivity-tiramisu-jni.so using APEX ns com_android_tethering for caller /apex/com.android.tethering/javalib/framework-connectivity-t.jar: ok
10-04 12:18:01.584  9279  9279 D OplusActivityThreadExtImpl: java.lang.NoSuchMethodException: dalvik.system.VMRuntime.SupressionGC [int, int]
10-04 12:18:01.584  9279  9279 W libc    : Access denied finding property "persist.vendor.sys.activitylog"
10-04 12:18:01.584  9279  9279 I OneTrace: Mark active for pid=9279? true
10-04 12:18:01.584  9279  9279 D cutils-dev: otrace_set_tracing_enabled? true tag:0
10-04 12:18:01.585  9279  9279 D cutils-dev: properties changed in otrace_seq_number_changed!
10-04 12:18:01.597  9279  9297 D OplusAppHeapManager: java.lang.NoSuchMethodException: dalvik.system.VMRuntime.updateProcessValue [int, int, int]
10-04 12:18:01.598  9279  9297 D CompatibilityInfo: setOverrideInvertedScale  1.0 to 1.0
10-04 12:18:01.623  9279  9279 D OplusActivityManager: get AMS extension: android.os.BinderProxy@4e68933
10-04 12:18:01.625  9279  9279 D nativeloader: Load libsigprotector_jni.so using system ns (caller=/system/framework/oplus-framework.jar): ok
10-04 12:18:01.626  9279  9279 D callGcSupression: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])' on a null object reference
10-04 12:18:01.626  9279  9279 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10568; state: ENABLED
10-04 12:18:01.631  9279  9279 I OplusFeatureCache: Milliseconds spent on init(): 5
10-04 12:18:01.631  9279  9279 D CompactWindowAppManager: initCompactApplicationInfo CompactMode: , NormalMode: 
10-04 12:18:01.635  9279  9279 D OplusScrollToTopManager: setIsInWhiteList false
10-04 12:18:01.635  9279  9279 D OplusViewDebugManager: OplusViewDebugManager Constructor android.view.debug.OplusViewDebugManager@8f6858f [mHasViewDebugProperty true] [mHasMsgDebugProperty false] [DEBUG false] [EXTRAINFOENABLE false] [LIGHT_OS false]
10-04 12:18:01.637  9279  9279 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10568; state: ENABLED
10-04 12:18:01.639  9279  9279 W libc    : Access denied finding property "ro.odm.prev.product.name"
10-04 12:18:01.647  9279  9279 D nativeloader: Configuring clns-4 for other apk /system_ext/framework/androidx.window.extensions.jar. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~-C6Kve6IqAcn6p698eX6gA==/app.revanced.manager.flutter-9y93xraDfs6m-k11oLr3sg==/lib/arm64:/data/app/~~-C6Kve6IqAcn6p698eX6gA==/app.revanced.manager.flutter-9y93xraDfs6m-k11oLr3sg==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/app.revanced.manager.flutter
10-04 12:18:01.647  9279  9279 D nativeloader: Extending system_exposed_libraries: libbinauralrenderer_wrapper.qti.so:libhoaeffects.qti.so:libSloganJni.oplus.so:libsuperNight.oplus.so:libAPSClient-cmd-jni-extension.oplus.so:libupdateprof.qti.so:libQOC.qti.so:libthermalclient.qti.so:libqape.qti.so:libqesdk_ndk_platform.qti.so:liblistenjni.qti.so
10-04 12:18:01.650  9279  9279 D nativeloader: Configuring clns-5 for other apk /system_ext/framework/androidx.window.sidecar.jar. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~-C6Kve6IqAcn6p698eX6gA==/app.revanced.manager.flutter-9y93xraDfs6m-k11oLr3sg==/lib/arm64:/data/app/~~-C6Kve6IqAcn6p698eX6gA==/app.revanced.manager.flutter-9y93xraDfs6m-k11oLr3sg==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/app.revanced.manager.flutter
10-04 12:18:01.650  9279  9279 D nativeloader: Extending system_exposed_libraries: libbinauralrenderer_wrapper.qti.so:libhoaeffects.qti.so:libSloganJni.oplus.so:libsuperNight.oplus.so:libAPSClient-cmd-jni-extension.oplus.so:libupdateprof.qti.so:libQOC.qti.so:libthermalclient.qti.so:libqape.qti.so:libqesdk_ndk_platform.qti.so:liblistenjni.qti.so
10-04 12:18:01.671  9279  9279 D nativeloader: Configuring clns-6 for other apk /data/app/~~-C6Kve6IqAcn6p698eX6gA==/app.revanced.manager.flutter-9y93xraDfs6m-k11oLr3sg==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~-C6Kve6IqAcn6p698eX6gA==/app.revanced.manager.flutter-9y93xraDfs6m-k11oLr3sg==/lib/arm64:/data/app/~~-C6Kve6IqAcn6p698eX6gA==/app.revanced.manager.flutter-9y93xraDfs6m-k11oLr3sg==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/app.revanced.manager.flutter
10-04 12:18:01.683  9279  9279 D nativeloader: Load libframework-connectivity-jni.so using APEX ns com_android_tethering for caller /apex/com.android.tethering/javalib/framework-connectivity.jar: ok
10-04 12:18:01.690  9279  9279 V GraphicsEnvironment: Currently set values for:
10-04 12:18:01.690  9279  9279 V GraphicsEnvironment:   angle_gl_driver_selection_pkgs=[]
10-04 12:18:01.690  9279  9279 V GraphicsEnvironment:   angle_gl_driver_selection_values=[]
10-04 12:18:01.690  9279  9279 V GraphicsEnvironment: ANGLE GameManagerService for app.revanced.manager.flutter: false
10-04 12:18:01.690  9279  9279 V GraphicsEnvironment: app.revanced.manager.flutter is not listed in per-application setting
10-04 12:18:01.690  9279  9279 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
--------- beginning of system
10-04 12:18:01.696  9279  9279 D ResourcesManagerExtImpl: applyConfigurationToAppResourcesLocked app.getDisplayId() return callback.displayId:-1
10-04 12:18:01.735  9279  9279 D nativeloader: Load libSchedAssistJni.so using system ns (caller=/system/framework/oplus-framework.jar): ok
10-04 12:18:01.735  9279  9279 D ExtensionsLoader: createInstance(64bit) : createExtendedFactory
10-04 12:18:01.736  9279  9279 D ExtensionsLoader: Opened libSchedAssistExtImpl.so
10-04 12:18:01.736  9279  9279 E SchedAssist: ofbOpen failed with error=No such file or directory
10-04 12:18:01.736  9279  9279 E SchedAssist: sysOpen failed with error=No such file or directory
10-04 12:18:01.736  9279  9279 E SchedAssist: sharedImFd failed with error=Permission denied
10-04 12:18:01.738  9279  9279 D OplusGraphicsEvent: OplusGraphicsEventListener create now!
10-04 12:18:01.739  9279  9279 D OplusGraphicsEvent: addEventListener success!
10-04 12:18:01.750  9279  9279 D ScrollOptim [ConfigManager]: initOptConfig: pkg= app.revanced.manager.flutter, mOptEnable= true, mAnimAheadEnable= true, mInsertDefaultNum= 1, mFrameInsertEnableList= {}, mSCEnableList= []
10-04 12:18:01.754  9279  9279 D callGcSupression: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])' on a null object reference
10-04 12:18:01.759  9279  9279 D ResourcesManagerExtImpl: applyConfigurationToAppResourcesLocked app.getDisplayId() return callback.displayId:-1
10-04 12:18:01.800  9279  9333 D nativeloader: Load /data/app/~~-C6Kve6IqAcn6p698eX6gA==/app.revanced.manager.flutter-9y93xraDfs6m-k11oLr3sg==/lib/arm64/libflutter.so using ns clns-6 from class loader (caller=/data/app/~~-C6Kve6IqAcn6p698eX6gA==/app.revanced.manager.flutter-9y93xraDfs6m-k11oLr3sg==/base.apk): ok
10-04 12:18:01.834  9279  9279 I AdrenoGLES-0: QUALCOMM build                   : e7626cbb06, If33672715f
10-04 12:18:01.834  9279  9279 I AdrenoGLES-0: Build Date                       : 01/24/23
10-04 12:18:01.834  9279  9279 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.35.01.12
10-04 12:18:01.834  9279  9279 I AdrenoGLES-0: Local Branch                     : 
10-04 12:18:01.834  9279  9279 I AdrenoGLES-0: Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.9.14.11.00.00.571.148
10-04 12:18:01.834  9279  9279 I AdrenoGLES-0: Remote Branch                    : NONE
10-04 12:18:01.834  9279  9279 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
10-04 12:18:01.834  9279  9279 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
10-04 12:18:01.834  9279  9279 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
10-04 12:18:01.837  9279  9279 I AdrenoGLES-0: PFP: 0x016ee201, ME: 0x00000000
10-04 12:18:01.865  9279  9279 D FlutterFileDialogPlugin: onAttachedToEngine - IN
10-04 12:18:01.865  9279  9279 D FlutterFileDialogPlugin: doOnAttachedToEngine - IN
10-04 12:18:01.865  9279  9279 D FlutterFileDialogPlugin: doOnAttachedToEngine - OUT
10-04 12:18:01.865  9279  9279 D FlutterFileDialogPlugin: onAttachedToEngine - OUT
10-04 12:18:01.865  9279  9279 D FlutterFileDialogPlugin: onAttachedToActivity
10-04 12:18:01.865  9279  9279 D FlutterFileDialogPlugin: doOnAttachedToActivity - IN
10-04 12:18:01.865  9279  9279 D FlutterFileDialogPlugin: doOnAttachedToActivity - OUT
10-04 12:18:01.872  9279  9279 I oplus.android.OplusFrameworkFactoryImpl: Unknow feature:IOplusTextViewRTLUtilForUG
10-04 12:18:01.873  9279  9279 D nativeloader: Load liboplushwui_jni.so using system ns (caller=/system/framework/oplus-framework.jar): ok
10-04 12:18:01.876  9279  9279 D ExtensionsLoader: createInstance(64bit) : createExtendedFactory
10-04 12:18:01.876  9279  9279 D ExtensionsLoader: Opened libguiextimpl.so
10-04 12:18:01.876  9279  9279 D nativeloader: Load liboplusgui_jni.so using system ns (caller=/system/framework/oplus-framework.jar): ok
10-04 12:18:01.878  9279  9279 D OplusInputMethodUtil: init sDebug to false, init sDebugIme to false, init sAlwaysOn to false
10-04 12:18:01.878  9279  9279 D OplusInputMethodUtil: updateDebugToClass InputMethodManager.DEBUG = false
10-04 12:18:01.878  9279  9279 D OplusInputMethodUtil: updateDebugToClass ImeFocusController.DEBUG = false
10-04 12:18:01.878  9279  9279 D OplusInputMethodUtil: updateDebugToClass BaseInputConnection.DEBUG = false
10-04 12:18:01.900  9279  9279 D ScrollOptim [SceneManager]: updateCurrentActivity: mCurrentActivityName=app.revanced.manager.flutter.MainActivity, isOptEnable=true, isAnimAheadEnable=true, isFrameInsertEnable=true, InsertNum=1, isEnabledForScrollChanged=false
10-04 12:18:01.900  9279  9279 D ActivityThread: ComponentInfo{app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity} checkFinished=false 2
10-04 12:18:01.901  9279  9279 D ResourcesManagerExtImpl: applyConfigurationToAppResourcesLocked app.getDisplayId() return callback.displayId:-1
10-04 12:18:01.903  9279  9279 D CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10568; state: DISABLED
10-04 12:18:01.906  9279  9279 I DynamicFramerate [FRTCConfigManager]: initFrameRateConfig: 
10-04 12:18:01.906  9279  9279 I DynamicFramerate [FRTCConfigManager]: 	levels: [120, 60]
10-04 12:18:01.906  9279  9279 I DynamicFramerate [FRTCConfigManager]: 	thresholds: [200]
10-04 12:18:01.906  9279  9279 I DynamicFramerate [FRTCConfigManager]: 	scrollbar fade frame rate: 0
10-04 12:18:01.906  9279  9279 I DynamicFramerate [FRTCConfigManager]: FRTCConfigManager: FRTC_CAPABILITY = 120, package name = app.revanced.manager.flutter, WINDOW_ANIMATION_SPEED_RATE = 10, SCROLL_ANIMATION_SPEED_RATE = 20, MuitiWindowIdleFramerate = 60, PACKAGE_ENABLE = false
10-04 12:18:01.906  9279  9279 I DynamicFramerate [DynamicFrameRateController]: init info: mPackageName = app.revanced.manager.flutter, mIsEnabled = false
10-04 12:18:01.906  9279  9279 D WindowManager: Add to mViews: DecorView@8011c58[MainActivity],pkg= app.revanced.manager.flutter
10-04 12:18:01.907  9279  9329 D ExtensionsLoader: createInstance(64bit) : createExtendedFactory
10-04 12:18:01.909  9279  9329 D ExtensionsLoader: Opened libhwuiextimpl.so
10-04 12:18:01.909  9279  9279 D ExtensionsLoader: createInstance(64bit) : createExtendedFactory
10-04 12:18:01.909  9279  9279 D ExtensionsLoader: Opened libSchedAssistExtImpl.so
10-04 12:18:01.919  9279  9279 D InputEventReceiver: Input log is disabled in InputEventReceiver.
10-04 12:18:01.921  9279  9279 D callGcSupression: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])' on a null object reference
10-04 12:18:01.921  9279  9279 D ResourcesManagerExtImpl: applyConfigurationToAppResourcesLocked app.getDisplayId() return callback.displayId:-1
10-04 12:18:01.924  9279  9279 I Quality : Skipped: false 2 cost 23.49724 refreshRate 8333414 bit true processName app.revanced.manager.flutter
10-04 12:18:01.925  9279  9279 E OplusBracketLog: [OplusViewMirrorManager] updateHostViewRootIfNeeded, not support android.view.ViewRootImpl@f759622
10-04 12:18:01.941  9279  9279 I SurfaceView: 258359444 onAttachedToWindow
10-04 12:18:01.942  9279  9279 D ViewRootImplExtImpl: wrapConfigInfoIntoFlags rotation=0, smallestScreenWidthDp=450, relayoutAsync=false, newFlags=29491200, title=app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity
10-04 12:18:01.950  9279  9279 D VRI[MainActivity]: relayoutWindow result, sizeChanged:true, surfaceControlChanged:true, transformHintChanged:true, mSurfaceSize:Point(1080, 2412), mLastSurfaceSize:Point(0, 0), mWidth:-1, mHeight:-1, requestedWidth:1080, requestedHeight:2412, transformHint:0, lastTransformHint:-2147483648, installOrientation:0, displayRotation:0, isSurfaceValid:true, attr.flag:-2122252032, useBlast:true, tmpFrames:ClientWindowFrames{frame=[0,0][1080,2412] display=[0,0][1080,2412] parentFrame=[0,0][0,0]}
10-04 12:18:01.950  9279  9279 W VRI[MainActivity]: updateBlastSurfaceIfNeeded, surfaceSize:Point(1080, 2412), lastSurfaceSize:Point(0, 0), format:-3, blastBufferQueue:null
10-04 12:18:01.959  9279  9279 D BufferQueueConsumer: [](id:243f00000000,api:0,p:-1,c:9279) connect: controlledByApp=false
10-04 12:18:01.960  9279  9279 D ExtensionsLoader: createInstance(64bit) : createExtendedFactory
10-04 12:18:01.960  9279  9279 D ExtensionsLoader: Opened libSchedAssistExtImpl.so
10-04 12:18:01.967  9279  9329 D BufferQueueProducer: [VRI[MainActivity]#0(BLAST Consumer)0](id:243f00000000,api:1,p:9279,c:9279) connect: api=1 producerControlledByApp=true
10-04 12:18:01.967  9279  9329 E OpenGLRenderer: Unable to match the desired swap behavior.
10-04 12:18:01.970  9279  9279 D BufferQueueConsumer: [](id:243f00000001,api:0,p:-1,c:9279) connect: controlledByApp=false
10-04 12:18:01.973  9279  9279 I SurfaceView: 258359444 visibleChanged -- surfaceCreated 
10-04 12:18:01.973  9279  9336 D BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1(BLAST Consumer)1](id:243f00000001,api:1,p:9279,c:9279) connect: api=1 producerControlledByApp=true
10-04 12:18:01.977  9279  9279 D SurfaceView: 258359444 handleSyncNoBuffer
10-04 12:18:01.977  9279  9279 D SurfaceView: 258359444 finishedDrawing
10-04 12:18:01.977  9279  9279 D SurfaceView: 258359444 performDrawFinished mAttachedToWindow true
10-04 12:18:01.978  9279  9279 D ViewRootImplExtImpl: setMaxDequeuedBufferCount: 2
10-04 12:18:01.979  9279  9279 I Quality : Skipped: false 3 cost 33.089012 refreshRate 8334910 bit true processName app.revanced.manager.flutter
10-04 12:18:01.979  9279  9279 W VRI[MainActivity]: handleResized, msg:5, frameChanged:false, configChanged:false, displayChanged:false, attachedFrameChanged:false, compatScaleChanged:false, pendingDragResizing=false
10-04 12:18:02.414  9279  9279 I Choreographer: Skipped 47 frames!  The application may be doing too much work on its main thread.
10-04 12:18:02.415  9279  9279 I Quality : Skipped: false 47 cost 393.8761 refreshRate 8332718 bit true processName app.revanced.manager.flutter
10-04 12:18:02.830  9279  9279 I Choreographer: Skipped 47 frames!  The application may be doing too much work on its main thread.
10-04 12:18:02.830  9279  9279 I Quality : Skipped: false 47 cost 392.75558 refreshRate 8332718 bit true processName app.revanced.manager.flutter
10-04 12:18:02.856  9279  9279 D ViewRootImplExtImpl: wrapConfigInfoIntoFlags rotation=0, smallestScreenWidthDp=450, relayoutAsync=false, newFlags=29491200, title=app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity
10-04 12:18:02.860  9279  9279 D VRI[MainActivity]: relayoutWindow result, sizeChanged:false, surfaceControlChanged:false, transformHintChanged:false, mSurfaceSize:Point(1080, 2412), mLastSurfaceSize:Point(1080, 2412), mWidth:1080, mHeight:2412, requestedWidth:1080, requestedHeight:2412, transformHint:0, lastTransformHint:0, installOrientation:0, displayRotation:0, isSurfaceValid:true, attr.flag:-2122252032, useBlast:true, tmpFrames:ClientWindowFrames{frame=[0,0][1080,2412] display=[0,0][1080,2412] parentFrame=[0,0][0,0]}
10-04 12:18:02.860  9279  9279 W VRI[MainActivity]: updateBlastSurfaceIfNeeded, surfaceSize:Point(1080, 2412), lastSurfaceSize:Point(1080, 2412), format:-3, blastBufferQueue:android.graphics.BLASTBufferQueue@a9466f
10-04 12:18:02.861  9279  9336 D BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1(BLAST Consumer)1](id:243f00000001,api:1,p:9279,c:9279) disconnect: api 1
10-04 12:18:02.861  9279  9336 D BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1(BLAST Consumer)1](id:243f00000001,api:1,p:9279,c:9279) connect: api=1 producerControlledByApp=true
10-04 12:18:02.861  9279  9279 D SurfaceView: 258359444 handleSyncNoBuffer
10-04 12:18:02.861  9279  9279 D SurfaceView: 258359444 finishedDrawing
10-04 12:18:02.861  9279  9279 D SurfaceView: 258359444 performDrawFinished mAttachedToWindow true
10-04 12:18:02.876  9279  9335 I flutter : dynamic_color: Core palette detected.
10-04 12:18:02.905  9279  9336 D BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#1](f:0,a:1) acquireNextBufferLocked size=1080x2412 mFrameNumber=1 applyTransaction=true mTimestamp=37945236862294(auto) mPendingTransactions.size=0 graphicBufferId=39853001539584 transform=0
10-04 12:18:03.417  9279  9279 D SurfaceView: 258359444 handleSyncNoBuffer
10-04 12:18:03.417  9279  9279 D SurfaceView: 258359444 finishedDrawing
10-04 12:18:03.417  9279  9279 D SurfaceView: 258359444 performDrawFinished mAttachedToWindow true
10-04 12:18:03.419  9279  9279 I Choreographer: Skipped 64 frames!  The application may be doing too much work on its main thread.
10-04 12:18:03.419  9279  9279 I Quality : Skipped: false 64 cost 539.68695 refreshRate 8332718 bit true processName app.revanced.manager.flutter
10-04 12:18:03.426  9279  9279 I SurfaceControl:  setExtendedRangeBrightness sc=Surface(name=app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity)/@0xf16f196,currentBufferRatio=1.0,desiredRatio=1.0
10-04 12:18:03.427  9279  9279 D SurfaceView: 258359444 dispatchDraw mDrawFinished true isAboveParent false (mPrivateFlags & PFLAG_SKIP_DRAW) 128
10-04 12:18:03.427  9279  9279 D SurfaceView: 258359444 clearSurfaceViewPort mCornerRadius 0.0
10-04 12:18:03.434  9279  9329 D BLASTBufferQueue: [VRI[MainActivity]#0](f:0,a:1) acquireNextBufferLocked size=1080x2412 mFrameNumber=1 applyTransaction=true mTimestamp=37945766596877(auto) mPendingTransactions.size=0 graphicBufferId=39853001539587 transform=0
10-04 12:18:03.435  9279  9329 D VRI[MainActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
10-04 12:18:03.435  9279  9279 D VRI[MainActivity]: draw finished.
10-04 12:18:03.435  9279  9279 D VRI[MainActivity]: reportDrawFinished
10-04 12:18:03.974  9279  9279 D VRI[MainActivity]: onFocusEvent true
10-04 12:18:04.073  9279  9279 V AutofillManager: requestHideFillUi(null): anchor = null
10-04 12:18:04.157  9279  9279 D OplusInputMethodManagerInternal: get inputMethodManager extension: com.android.internal.view.IInputMethodManager$Stub$Proxy@803b62f
10-04 12:18:04.158  9279  9279 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=946.5, y[0]=2200.5, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=37946483, downTime=37946398, deviceId=-1, source=0x1002, displayId=0, eventId=191364069 } handled by client, just return
10-04 12:18:04.987  9279 10324 D OplusScrollToTopManager: app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity,This DecorView@8011c58[MainActivity] change focus to true
10-04 12:18:05.666  9279  9279 V AutofillManager: requestHideFillUi(null): anchor = null
10-04 12:18:06.026  9279  9279 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=675.25, y[0]=590.25, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=37948355, downTime=37947993, deviceId=-1, source=0x1002, displayId=0, eventId=894840160 } handled by client, just return
10-04 12:18:06.337  9279  9279 V AutofillManager: requestHideFillUi(null): anchor = null
10-04 12:18:07.578  9279 10344 D ProfileInstaller: Skipping profile installation for app.revanced.manager.flutter
10-04 12:18:07.648  9279  9279 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=759.25, y[0]=465.75, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=37949977, downTime=37948665, deviceId=-1, source=0x1002, displayId=0, eventId=586024644 } handled by client, just return
10-04 12:18:08.112  9279  9279 V AutofillManager: requestHideFillUi(null): anchor = null
10-04 12:18:09.154  9279  9279 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=688.25, y[0]=622.5, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=37951480, downTime=37950440, deviceId=-1, source=0x1002, displayId=0, eventId=649229953 } handled by client, just return
10-04 12:18:10.335  9279  9279 V AutofillManager: requestHideFillUi(null): anchor = null
10-04 12:18:10.929  9279  9279 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=816.75, y[0]=628.5, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=37953257, downTime=37952662, deviceId=-1, source=0x1002, displayId=0, eventId=595059088 } handled by client, just return
10-04 12:18:11.277  9279  9279 V AutofillManager: requestHideFillUi(null): anchor = null
10-04 12:18:11.610  9279  9292 W manager.flutter: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~S6UoflhKTvcp9cglg8NOnA==/app.revanced.android.youtube-TiAE9RDBi1GAyBeANKGb5Q==/base.apk' with 1 weak references
10-04 12:18:11.718  9279  9279 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=842.75, y[0]=605.25, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=37954047, downTime=37953606, deviceId=-1, source=0x1002, displayId=0, eventId=300400283 } handled by client, just return
10-04 12:18:13.666  9279  9279 V AutofillManager: requestHideFillUi(null): anchor = null
10-04 12:18:13.731  9279  9279 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=579.25, y[0]=1340.25, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=37956058, downTime=37955994, deviceId=-1, source=0x1002, displayId=0, eventId=794476218 } handled by client, just return
10-04 12:18:13.812  9279  9279 I Quality : Skipped: false 4 cost 74.68181 refreshRate 16663687 bit true processName app.revanced.manager.flutter
10-04 12:18:13.831  9279  9279 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10568; state: ENABLED
10-04 12:18:13.878  9279  9279 D callGcSupression: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])' on a null object reference
10-04 12:18:13.879  9279  9279 D callGcSupression: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])' on a null object reference
10-04 12:18:13.879  9279  9279 D ScrollOptim [SceneManager]: updateCurrentActivity: mCurrentActivityName=null, isOptEnable=true, isAnimAheadEnable=true, isFrameInsertEnable=true, InsertNum=1, isEnabledForScrollChanged=false
10-04 12:18:13.968  9279  9279 D VRI[MainActivity]: onFocusEvent false
10-04 12:18:14.972  9279 10324 D OplusScrollToTopManager: app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity,This DecorView@8011c58[MainActivity] change focus to false
10-04 12:18:17.683  9279  9279 D callGcSupression: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])' on a null object reference
10-04 12:18:17.687  9279  9279 D callGcSupression: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])' on a null object reference
10-04 12:18:17.688  9279  9279 D CompatibilityChangeReporter: Compat change id reported: 78294732; UID 10568; state: ENABLED
10-04 12:18:17.688  9279  9279 D ScrollOptim [SceneManager]: updateCurrentActivity: mCurrentActivityName=app.revanced.manager.flutter.MainActivity, isOptEnable=true, isAnimAheadEnable=true, isFrameInsertEnable=true, InsertNum=1, isEnabledForScrollChanged=false
10-04 12:18:17.688  9279  9279 D ActivityThread: ComponentInfo{app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity} checkFinished=false 4
10-04 12:18:17.689  9279  9279 D ResourcesManagerExtImpl: applyConfigurationToAppResourcesLocked app.getDisplayId() return callback.displayId:-1
10-04 12:18:17.702  9279  9279 D VRI[MainActivity]: onFocusEvent true
10-04 12:18:18.707  9279 10324 D OplusScrollToTopManager: app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity,This DecorView@8011c58[MainActivity] change focus to true
10-04 12:18:23.466  9279  9279 V AutofillManager: requestHideFillUi(null): anchor = null
10-04 12:18:23.548  9279  9279 D ViewRootImplExtImpl: MotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=99.25, y[0]=1299.5, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=37965875, downTime=37965790, deviceId=-1, source=0x1002, displayId=0, eventId=201376860 } handled by client, just return

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [ ] The bug is only related to ReVanced Manager.

**Comment by zainarbani** [comment]
Can you enable debugging then grab the log?

**Comment by validcube** [comment]
👋 Hello, @njihil!

Thanks for filing this issue, but however this issue is out-of-scope for this repository (ReVanced Manager), the correct repository to file this issue in would be our [ReVanced Patches repository](https://github.com/ReVanced/revanced-patches).

Your issue has been updated with list of acknowledgement that hadn't been ment.
