### ISSUE TITLE
Bug: Tiktok showing as [value removed]

### ISSUE THREAD

**Issue by steve51184** [revanced/revanced-manager#225]
### Type

Cosmetic

### Branch

Flutter/Android 

### Bug description

Incorrect name for Tiktok is shown only started in .14

### Steps to reproduce

Go to patcher click select app

### Relevant log output

```shell
None
```

### Screenshots or videos

![Screenshot_20220919-021015](https://user-images.githubusercontent.com/12534098/190936558-85d0ffb2-cd8d-44ea-987c-d07071367c46.jpg)
![Screenshot_20220919-021020](https://user-images.githubusercontent.com/12534098/190936561-c8b0c46e-a8fa-44a7-a468-b6b7b3e15b79.jpg)

**Comment by Aunali321** [comment]
Reinstall manager and tiktok and see ifs its fixed.

**Comment by Aunali321** [comment]
Closing because no user response.

**Comment by xNombre** [comment]
> Closing because no user response.

Hi, I'm experiencing same problem with TikTok and YouTube.
If I uninstall one of the apps and install it again from play store it starts working normally. However, after rebooting the phone apps break again. I don't even have Manager installed now nor patched any of the apps after reinstalling. It started happening after patching apps once.

**Comment by Tiebe** [comment]
@Aunali321 same problem here, please reopen

**Comment by steve51184** [comment]
It seems to happen on the second patch of the app for me

**Comment by xNombre** [comment]
Here is a logcat when Im trying to open Tiktok
[tiktok_logcat.txt](https://github.com/revanced/revanced-manager/files/9675507/tiktok_logcat.txt)

**Comment by devlocalhost** [comment]
Any fix for this issue? This also happens with other apps, like reddit and twitter. And just because of that, I have to reinstall TikTok, reddit and twitter almost EVERYDAY. I don't even have the manager installer. The only way to fix this issue is by formatting the phone

**Comment by devlocalhost** [comment]
> > Any fix for this issue? This also happens with other apps, like reddit and twitter. And just because of that, I have to reinstall TikTok, reddit and twitter almost EVERYDAY. I don't even have the manager installer. The only way to fix this issue is by formatting the phone
> 
> I found out that Vanced Manager leaves addon scripts in magisk directory for overlaying base apks. You can either remove them manually or install Manager and remove them using it. I think user should be clearly warned about this or script should be modified to trigger only on some condition met (Vanced manager installed?)

Where (path) exactly? There's too much in /data/adb/magisk. I followed #425 solution, and now I'm waiting to see if it's fixed or not
