### ISSUE TITLE
Adding split APKs support

### ISSUE THREAD

**Issue by Bazixv13** [ReVanced/revanced-manager#2250]
### Feature description

Users won’t have to download separate APKs for each app and I'd they are split apks converting them. 

### Why would I like to see this feature:
- Users won’t need to download individual APKs for each app.

- For example, APK Mirror (like X) often lacks newer releases that aren’t split APKs.

### Solution idea:
- When a user selects a split APK, inform them that converting is required.

- Implement functionality similar to [AntiSplit-M](https://github.com/AbdurazaaqMohammed/AntiSplit-M) for conversion.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] The feature request is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
Split apk support will require overhaul in patcher and not merging into a full apk
