### ISSUE TITLE
bug: Unable to install any patches through Revanced

### ISSUE THREAD

**Issue by Autumnleafsandcats** [ReVanced/revanced-manager#2251]
### Bug description

When trying to install any Patches using Revanced it throws a whole crap load of errors at me

### Version of ReVanced Manager and version & name of app you are patching

revanced-manager-v1.22.1-dev.2.apk
com.google.android.apps.photos
Photos_7.2.0.680709391

### Installation method

Regular

### ReVanced Manager logs

--------- beginning of main
10-08 15:29:18.739 10914 10914 I manager.flutter: Using CollectorTypeCMC GC.
10-08 15:29:18.744 10914 10914 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
10-08 15:29:18.753 10914 10914 D nativeloader: Load libframework-connectivity-tiramisu-jni.so using APEX ns com_android_tethering for caller /apex/com.android.tethering/javalib/framework-connectivity-t.jar: ok
10-08 15:29:18.755 10914 10914 D ActivityThread: setConscryptValidator
10-08 15:29:18.756 10914 10914 D ActivityThread: setConscryptValidator - put
10-08 15:29:18.783 10914 10914 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10486; state: ENABLED
10-08 15:29:18.785 10914 10914 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10486; state: ENABLED
10-08 15:29:18.798 10914 10914 W ziparchive: Unable to open '/data/app/~~i7hrtpQ4uXU6kVmaqfxJLw==/app.revanced.manager.flutter-M7gqNtTJ87ke59VyITCVUQ==/base.dm': No such file or directory
10-08 15:29:18.798 10914 10914 W ziparchive: Unable to open '/data/app/~~i7hrtpQ4uXU6kVmaqfxJLw==/app.revanced.manager.flutter-M7gqNtTJ87ke59VyITCVUQ==/base.dm': No such file or directory
10-08 15:29:18.986 10914 10914 D nativeloader: Configuring clns-4 for other apk /data/app/~~i7hrtpQ4uXU6kVmaqfxJLw==/app.revanced.manager.flutter-M7gqNtTJ87ke59VyITCVUQ==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~i7hrtpQ4uXU6kVmaqfxJLw==/app.revanced.manager.flutter-M7gqNtTJ87ke59VyITCVUQ==/lib/arm64:/data/app/~~i7hrtpQ4uXU6kVmaqfxJLw==/app.revanced.manager.flutter-M7gqNtTJ87ke59VyITCVUQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/app.revanced.manager.flutter
10-08 15:29:19.007 10914 10914 D nativeloader: Load libspeg.so using system ns (caller=/system/framework/framework.jar): ok
10-08 15:29:19.007 10914 10914 I SPEG    : Preparing application
10-08 15:29:19.007 10914 10914 E libsigchain: Setting SIGSEGV to SIG_DFL
10-08 15:29:19.141 10914 10914 E libsigchain:   #00 pc 00006ac8  /apex/com.android.art/lib64/libsigchain.so (LogStack()+200) (BuildId: 1dfc84ea17eda8296164845381922b35)
10-08 15:29:19.141 10914 10914 E libsigchain:   #01 pc 000075e0  /apex/com.android.art/lib64/libsigchain.so (sigaction+216) (BuildId: 1dfc84ea17eda8296164845381922b35)
10-08 15:29:19.141 10914 10914 E libsigchain:   #02 pc 0000bc54  /system/lib64/libspeg.so (JNI_OnLoad+180) (BuildId: 3b04f3af65d2a82bb7f4e5f9a060bdb4)
10-08 15:29:19.141 10914 10914 E libsigchain:   #03 pc 0066fb80  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::LoadNativeLibrary(_JNIEnv*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, _jobject*, _jclass*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)+1280) (BuildId: 27d824f901af23b82abd1f08138ee412)
10-08 15:29:19.141 10914 10914 E libsigchain:   #04 pc 00005914  /apex/com.android.art/lib64/libopenjdkjvm.so (JVM_NativeLoad+356) (BuildId: 52e480f4d160d1f919dafa72cae26e8a)
10-08 15:29:19.141 10914 10914 E libsigchain:   #05 pc 00388794  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+148) (BuildId: )
10-08 15:29:19.141 10914 10914 E libsigchain:   #06 pc 0043bf58  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.lang.Runtime.loadLibrary0+744) (BuildId: )
10-08 15:29:19.141 10914 10914 E libsigchain:   #07 pc 0043cc70  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.lang.Runtime.loadLibrary0+400) (BuildId: )
10-08 15:29:19.141 10914 10914 E libsigchain:   #08 pc 00714618  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.LoadedApk.registerAppInfoToArt+2472) (BuildId: )
10-08 15:29:19.141 10914 10914 E libsigchain:   #09 pc 00711010  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.LoadedApk.createOrUpdateClassLoaderLocked+6272) (BuildId: )
10-08 15:29:19.141 10914 10914 E libsigchain:   #10 pc 00717638  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.LoadedApk.getResources+680) (BuildId: )
10-08 15:29:19.141 10914 10914 E libsigchain:   #11 pc 00807640  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ContextImpl.createAppContext+176) (BuildId: )
10-08 15:29:19.141 10914 10914 E libsigchain:   #12 pc 007dd668  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread.handleBindApplication+3080) (BuildId: )
10-08 15:29:19.141 10914 10914 E libsigchain:   #13 pc 007d31b8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread$H.handleMessage+7848) (BuildId: )
10-08 15:29:19.141 10914 10914 E libsigchain:   #14 pc 00a65798  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Handler.dispatchMessage+152) (BuildId: )
10-08 15:29:19.141 10914 10914 E libsigchain:   #15 pc 00a69344  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Looper.loopOnce+980) (BuildId: )
10-08 15:29:19.141 10914 10914 E libsigchain:   #16 pc 00a68ed4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Looper.loop+916) (BuildId: )
10-08 15:29:19.141 10914 10914 E libsigchain:   #17 pc 007e85ec  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread.main+2044) (BuildId: )
10-08 15:29:19.141 10914 10914 E libsigchain:   #18 pc 00362a40  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640) (BuildId: 27d824f901af23b82abd1f08138ee412)
10-08 15:29:19.141 10914 10914 E libsigchain:   #19 pc 0035e42c  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+732) (BuildId: 27d824f901af23b82abd1f08138ee412)
10-08 15:29:19.141 10914 10914 E libsigchain:   #20 pc 006c8b78  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*) (.__uniq.165753521025965369065708152063621506277)+32) (BuildId: 27d824f901af23b82abd1f08138ee412)
10-08 15:29:19.141 10914 10914 E libsigchain:   #21 pc 0038e244  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+116) (BuildId: )
10-08 15:29:19.141 10914 10914 E libsigchain:   #22 pc 00dbe1d4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+116) (BuildId: )
10-08 15:29:19.141 10914 10914 E libsigchain:   #23 pc 00dc9724  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (com.android.internal.os.ZygoteInit.main+3396) (BuildId: )
10-08 15:29:19.141 10914 10914 E libsigchain:   #24 pc 00362a40  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640) (BuildId: 27d824f901af23b82abd1f08138ee412)
10-08 15:29:19.141 10914 10914 E libsigchain:   #25 pc 0034df38  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+204) (BuildId: 27d824f901af23b82abd1f08138ee412)
10-08 15:29:19.141 10914 10914 E libsigchain:   #26 pc 0034beec  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+512) (BuildId: 27d824f901af23b82abd1f08138ee412)
10-08 15:29:19.142 10914 10914 E libsigchain:   #27 pc 00739bf4  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+104) (BuildId: 27d824f901af23b82abd1f08138ee412)
10-08 15:29:19.142 10914 10914 E libsigchain:   #28 pc 000e0ca8  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+104) (BuildId: 0984e0fc426299504cd605d070122ba4)
10-08 15:29:19.142 10914 10914 E libsigchain:   #29 pc 000ed5dc  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+860) (BuildId: 0984e0fc426299504cd605d070122ba4)
10-08 15:29:19.142 10914 10914 E libsigchain:   #30 pc 0000256c  /system/bin/app_process64 (main+1292) (BuildId: 9e5f6cbeaf43b41301834b80c238018a)
10-08 15:29:19.142 10914 10914 E libsigchain:   #31 pc 0008c5b8  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+104) (BuildId: 59cafcd8c6514064584f920f18ea8760)
10-08 15:29:20.756 11086 11086 I spqr    : Size: 1220, waiting time: 10ms
10-08 15:29:20.887 11086 11086 I spqr    : spqr v4.3s took 143ms
10-08 15:29:30.512 11678 11678 I manager.flutter: Using CollectorTypeCMC GC.
10-08 15:29:30.516 11678 11678 E manager.flutter: Not starting debugger since process cannot load the jdwp agent.
10-08 15:29:30.527 11678 11678 D nativeloader: Load libframework-connectivity-tiramisu-jni.so using APEX ns com_android_tethering for caller /apex/com.android.tethering/javalib/framework-connectivity-t.jar: ok
10-08 15:29:30.530 11678 11678 D ActivityThread: setConscryptValidator
10-08 15:29:30.531 11678 11678 D ActivityThread: setConscryptValidator - put
10-08 15:29:30.556 11678 11678 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10486; state: ENABLED
10-08 15:29:30.556 11678 11678 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10486; state: ENABLED
10-08 15:29:30.591 11678 11678 D nativeloader: Configuring clns-4 for other apk /data/app/~~i7hrtpQ4uXU6kVmaqfxJLw==/app.revanced.manager.flutter-M7gqNtTJ87ke59VyITCVUQ==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~i7hrtpQ4uXU6kVmaqfxJLw==/app.revanced.manager.flutter-M7gqNtTJ87ke59VyITCVUQ==/lib/arm64:/data/app/~~i7hrtpQ4uXU6kVmaqfxJLw==/app.revanced.manager.flutter-M7gqNtTJ87ke59VyITCVUQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/app.revanced.manager.flutter
10-08 15:29:30.602 11678 11678 D nativeloader: Load libframework-connectivity-jni.so using APEX ns com_android_tethering for caller /apex/com.android.tethering/javalib/framework-connectivity.jar: ok
10-08 15:29:30.613 11678 11678 V GraphicsEnvironment: Currently set values for:
10-08 15:29:30.613 11678 11678 V GraphicsEnvironment:   angle_gl_driver_selection_pkgs=[]
10-08 15:29:30.613 11678 11678 V GraphicsEnvironment:   angle_gl_driver_selection_values=[]
10-08 15:29:30.614 11678 11678 V GraphicsEnvironment: ANGLE GameManagerService for app.revanced.manager.flutter: false
10-08 15:29:30.614 11678 11678 V GraphicsEnvironment: app.revanced.manager.flutter is not listed in per-application setting
10-08 15:29:30.614 11678 11678 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
10-08 15:29:30.650 11678 11678 D OpenGLRenderer: HWUI - treat SMPTE_170M as sRGB
10-08 15:29:30.659 11678 11691 D libMEOW : meow new tls: 0xb400007db9a7f940
10-08 15:29:30.660 11678 11691 D libMEOW : meow reload base cfg path: na
10-08 15:29:30.660 11678 11691 D libMEOW : meow reload overlay cfg path: na
10-08 15:29:30.662 11678 11691 W QT      : qt_process_init() called
10-08 15:29:30.662 11678 11691 E QT      : [QT]file does not exist
10-08 15:29:30.662 11678 11691 W QT      : Support!!
10-08 15:29:30.663 11678 11691 D libMEOW : applied 0 plugin for [app.revanced.manager.flutter].
10-08 15:29:30.771 11678 11709 D nativeloader: Load /data/app/~~i7hrtpQ4uXU6kVmaqfxJLw==/app.revanced.manager.flutter-M7gqNtTJ87ke59VyITCVUQ==/lib/arm64/libflutter.so using ns clns-4 from class loader (caller=/data/app/~~i7hrtpQ4uXU6kVmaqfxJLw==/app.revanced.manager.flutter-M7gqNtTJ87ke59VyITCVUQ==/base.apk): ok
10-08 15:29:30.855 11678 11678 D libMEOW : applied 0 plugin for [app.revanced.manager.flutter].
10-08 15:29:30.869 11678 11714 D libMEOW : meow new tls: 0xb400007d4163abc0
10-08 15:29:30.869 11678 11714 D libMEOW : applied 0 plugin for [app.revanced.manager.flutter].
10-08 15:29:30.930 11678 11678 D FlutterFileDialogPlugin: onAttachedToEngine - IN
10-08 15:29:30.930 11678 11678 D FlutterFileDialogPlugin: doOnAttachedToEngine - IN
10-08 15:29:30.930 11678 11678 D FlutterFileDialogPlugin: doOnAttachedToEngine - OUT
10-08 15:29:30.930 11678 11678 D FlutterFileDialogPlugin: onAttachedToEngine - OUT
10-08 15:29:30.930 11678 11678 D FlutterFileDialogPlugin: onAttachedToActivity
10-08 15:29:30.930 11678 11678 D FlutterFileDialogPlugin: doOnAttachedToActivity - IN
10-08 15:29:30.930 11678 11678 D FlutterFileDialogPlugin: doOnAttachedToActivity - OUT
10-08 15:29:30.980 11678 11678 D SurfaceView@7722273: 124920435 setAlpha: alpha=0.0
10-08 15:29:30.980 11678 11678 D SurfaceView@7722273: 124920435 updateSurface: has no frame
10-08 15:29:31.052 11678 11678 I DecorView: setWindowBackground: isPopOver=false color=ff000000 d=android.graphics.drawable.ColorDrawable@ab5ea1d
10-08 15:29:31.066 11678 11678 D CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10486; state: DISABLED
10-08 15:29:31.072 11678 11678 W OpenGLRenderer: Unknown dataspace 0
10-08 15:29:31.073 11678 11691 D NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::BpCustomFrequencyManager()
10-08 15:29:31.090 11678 11678 I InsetsController: onStateChanged: host=app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity, from=android.view.ViewRootImpl.setView:1753, state=InsetsState: {mDisplayFrame=Rect(0, 0 - 1080, 2340), mDisplayCutout=DisplayCutout{insets=Rect(0, 80 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(472, 0 - 608, 80), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]} cutoutPathParserInfo={CutoutPathParserInfo{displayWidth=1080 displayHeight=2340 physicalDisplayWidth=1080 physicalDisplayHeight=2340 density={2.8125} cutoutSpec={M 0,0 H -24.177777778 V 28.4444444444 H 24.177777778 V 0 H 0 Z @dp} rotation={0} scale={1.0} physicalPixelDisplaySizeRatio={1.0}}}}, mRoundedCorners=RoundedCorners{[RoundedCorner{position=TopLeft, radius=0, center=Point(0, 0)}, RoundedCorner{position=TopRight, radius=0, center=Point(0, 0)}, RoundedCorner{position=BottomRight, radius=0, center=Point(0, 0)}, RoundedCorner{position=BottomLeft, radius=0, center=Point(0, 0)}]}  mRoundedCornerFrame=Rect(0, 0 - 1080, 2340), mPrivacyIndicatorBounds=PrivacyIndicatorBounds {static bounds=Rect(956, 0 - 1080, 80) rotation=0}, mDisplayShape=DisplayShape{ spec=-311912193 displayWidth=1080 displayHeight=2340 physicalPixelDisplaySizeRatio=1.0 rotation=0 offsetX=0 offsetY=0 scale=1.0}, mSources= { InsetsSource: {3 mType=ime mFrame=[0,0][0,0] mVisible=false mFlags=[]}, InsetsSource: {27 mType=displayCutout mFrame=[0,0][1080,80] mVisible=true mFlags=[]}, InsetsSource: {ff60001 mType=navigationBars mFrame=[0,2205][1080,2340] mVisible=true mFlags=[]}, InsetsSource: {ff60004 mType=systemGestures mFrame=[0,0][0,0] mVisible=true mFlags=[]}, InsetsSource: {ff60005 mType=mandatorySystemGestures mFrame=[0,2205][1080,2340] mVisible=true mFlags=[]}, InsetsSource: {ff60006 mType=tappableElement mFrame=[0,2205][1080,2340] mVisible=true mFlags=[]}, InsetsSource: {ff60024 mType=systemGestures mFrame=[0,0][0,0] mVisible=true mFlags=[]}, InsetsSource: {26400000 mType=statusBars mFrame=[0,0][1080,80] mVisible=true mFlags=[]}, InsetsSource: {26400005 mType=mandatorySystemGestures mFrame=[0,0][1080,114] mVisible=true mFlags=[]}, InsetsSource: {26400006 mType=tappableElement mFrame=[0,0][1080,80] mVisible=true mFlags=[]} }
10-08 15:29:31.091 11678 11678 I ViewRootImpl@78badbf[MainActivity]: synced displayState. AttachInfo displayState=2
10-08 15:29:31.094 11678 11678 I ViewRootImpl@78badbf[MainActivity]: setView = com.android.internal.policy.DecorView@65766db TM=true
10-08 15:29:31.095 11678 11678 I IDS_TAG : Starting IDS observe window
10-08 15:29:31.096 11678 11678 I IDS_TAG : Getting Shared Preference for android.app.Application@cefb578 uid = 10486
10-08 15:29:31.099 11678 11678 I IDS_TAG : App android.app.Application@cefb578 has not finished training
10-08 15:29:31.101 11678 11678 I IDS_TAG : Closing IDS observe window
10-08 15:29:31.101 11678 11678 I IDS_TAG : Getting Shared Preference for android.app.Application@cefb578 uid = 10486
10-08 15:29:31.109 11678 11678 I IDS_TAG : IDS count updated to 1 for android.app.Application@cefb578
10-08 15:29:31.185 11678 11678 I SurfaceView@7722273: onWindowVisibilityChanged(0) true io.flutter.embedding.android.FlutterSurfaceView{7722273 V.E...... ......I. 0,0-0,0} of ViewRootImpl@78badbf[MainActivity]
10-08 15:29:31.185 11678 11678 D SurfaceView@7722273: 124920435 updateSurface: has no frame
10-08 15:29:31.267 11678 11678 D BufferQueueConsumer: [](id:2d9e00000000,api:0,p:-1,c:11678) connect: controlledByApp=false
10-08 15:29:31.269 11678 11678 I BLASTBufferQueue_Java: new BLASTBufferQueue, mName= ViewRootImpl@78badbf[MainActivity] mNativeObject= 0xb400007db2850100 sc.mNativeObject= 0xb400007d416b4900 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:3028 android.view.ViewRootImpl.relayoutWindow:10131 android.view.ViewRootImpl.performTraversals:4110 android.view.ViewRootImpl.doTraversal:3288 android.view.ViewRootImpl$TraversalRunnable.run:11344 android.view.Choreographer$CallbackRecord.run:1689 android.view.Choreographer$CallbackRecord.run:1698 android.view.Choreographer.doCallbacks:1153 android.view.Choreographer.doFrame:1079 android.view.Choreographer$FrameDisplayEventReceiver.run:1646 
10-08 15:29:31.270 11678 11678 I BLASTBufferQueue_Java: update, w= 1080 h= 2340 mName = ViewRootImpl@78badbf[MainActivity] mNativeObject= 0xb400007db2850100 sc.mNativeObject= 0xb400007d416b4900 format= -3 caller= android.graphics.BLASTBufferQueue.<init>:89 android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:3028 android.view.ViewRootImpl.relayoutWindow:10131 android.view.ViewRootImpl.performTraversals:4110 android.view.ViewRootImpl.doTraversal:3288 android.view.ViewRootImpl$TraversalRunnable.run:11344 
10-08 15:29:31.281 11678 11678 E FBI     : Can't load library: dlopen failed: library "libmagtsync.so" not found
10-08 15:29:31.291 11678 11678 I ViewRootImpl@78badbf[MainActivity]: Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) relayoutAsync=false req=(1080,2340)0 dur=77 res=0x403 s={true 0xb400007d41826000} ch=true seqId=0
10-08 15:29:31.292 11678 11678 I ViewRootImpl@78badbf[MainActivity]: performConfigurationChange setNightDimText nightDimLevel=0
10-08 15:29:31.293 11678 11678 D ViewRootImpl@78badbf[MainActivity]: mThreadedRenderer.initialize() mSurface={isValid=true 0xb400007d41826000} hwInitialized=true
10-08 15:29:31.295 11678 11678 D SurfaceView@7722273: 124920435 updateSurface: has no frame
10-08 15:29:31.296 11678 11678 I SurfaceView@7722273: windowStopped(false) true io.flutter.embedding.android.FlutterSurfaceView{7722273 V.E...... ......ID 0,0-1080,2205} of ViewRootImpl@78badbf[MainActivity]
10-08 15:29:31.296 11678 11678 D SurfaceView@7722273: 124920435 updateSurface: has no frame
10-08 15:29:31.299 11678 11678 D ViewRootImpl@78badbf[MainActivity]: reportNextDraw android.view.ViewRootImpl.performTraversals:4718 android.view.ViewRootImpl.doTraversal:3288 android.view.ViewRootImpl$TraversalRunnable.run:11344 android.view.Choreographer$CallbackRecord.run:1689 android.view.Choreographer$CallbackRecord.run:1698 
10-08 15:29:31.299 11678 11678 I SurfaceView: 124920435 Changes: creating=true format=true size=true visible=true alpha=true hint=false visible=true left=true top=true z=false attached=true lifecycleStrategy=false
10-08 15:29:31.302 11678 11678 D BufferQueueConsumer: [](id:2d9e00000001,api:0,p:-1,c:11678) connect: controlledByApp=false
10-08 15:29:31.303 11678 11678 I BLASTBufferQueue_Java: update, w= 1080 h= 2205 mName = null mNativeObject= 0xb400007db28ce900 sc.mNativeObject= 0xb400007d416b4e40 format= 4 caller= android.view.SurfaceView.createBlastSurfaceControls:1517 android.view.SurfaceView.updateSurface:1193 android.view.SurfaceView.lambda$new$0:258 android.view.SurfaceView.$r8$lambda$cm3nmzErr-srXoT_KjIYQgdhFN

### Patch logs

- Device Info
ReVanced Manager: 1.22.1-dev.2
Model: SM-S156V
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.photos v7.2.0.680709391 (Suggested: Any)
Patches version: v4.16.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 4 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~i7hrtpQ4uXU6kVmaqfxJLw==/app.revanced.manager.flutter-M7gqNtTJ87ke59VyITCVUQ==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-FMRHRY/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-FMRHRY/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~i7hrtpQ4uXU6kVmaqfxJLw==/app.revanced.manager.flutter-M7gqNtTJ87ke59VyITCVUQ==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-FMRHRY/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-FMRHRY/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/files/patcher/tmp-FMRHRY/out.apk' (OS Error: No such file or directory, errno = 2)

### Acknowledgements

- [ ] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
![Image](https://github.com/user-attachments/assets/5f25a7a2-8da8-4d59-a97a-d39d60bb41e3)
