### ISSUE TITLE
bug: <YouTube not loading all the while after installing>

### ISSUE THREAD

**Issue by Vegetagiy123** [revanced/revanced-manager#226]
### Type

Other

### Branch

YouTube just shows a grey screen and is not loading all the way 

### Bug description

I found the bug after I patched YouTube and installed it through YouTube Revanced manger 

### Steps to reproduce

Step 1 make sure YouTube loads all the way
Step 2 make sure YouTube doesn't show the grey screen 

### Relevant log output

```shell
YouTube doesn't load all the way on Revanced manger after I patch it and install it on manger
```

### Screenshots or videos

![Screenshot_20220918-183445](https://user-images.githubusercontent.com/113322179/190937739-f9d91f15-cba8-481a-b488-54566f6ef95a.png)

### Additional context

Make sure YouTube runs all the way and loads on the latest version 17.36.37

**Comment by Aunali321** [comment]
Use the full apk from apk mirror.

**Comment by pietryszak** [comment]
And install gmicro vanced if it's non-root install

**Comment by Dakile007** [comment]
> Use the full apk from apk mirror.

Where in apkmirror can I get this? Theres multiple youtube apps there

**Comment by pietryszak** [comment]
> > Use the full apk from apk mirror.
> 
> Where in apkmirror can I get this? Theres multiple youtube apps there

C'mon it's only one version of 17.36 apk version
![obraz](https://user-images.githubusercontent.com/45850093/191021192-f9f0bb8a-2db3-45b7-a5c9-d62974eba743.png)

**Comment by Dakile007** [comment]
> > > Use the full apk from apk mirror.
> > 
> > 
> > Where in apkmirror can I get this? Theres multiple youtube apps there
> 
> C'mon it's only one version of 17.36 apk version ![obraz](https://user-images.githubusercontent.com/45850093/191021192-f9f0bb8a-2db3-45b7-a5c9-d62974eba743.png)

Cheers mate

**Comment by Palocay** [comment]
Got the same error, either it stays like this or closes immediatly

**Comment by piotor87** [comment]
Had same problem, fixed it by using APK from storage.
