### ISSUE TITLE
feat: Sponsor block Highlight option

### ISSUE THREAD

**Issue by bellehop** [ReVanced/revanced-manager#2261]
### Feature description

The Highlight segment in revanced for Sponsorblock does not work the same way as it should in a desktop browser. For example, in revanced you have to have a start time and and end time even when it's a highlight, in desktop browser you only need 1 timestamp and then you can submit a highlight.

### Motivation

In revanced you have to have a start time and and end time even when it's a highlight, in desktop browser you only need 1 timestamp and then you can submit a highlight. Improving this feature would the functionality more accurate and would benefit both applications greatly.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [ ] The feature request is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
Acknowledgements not met. This is not the patches repo

**Comment by bellehop** [comment]
My mistake, where is the patches repo?
