### ISSUE TITLE
feat: Spoof build info: Add presets

### ISSUE THREAD

**Issue by NatoBoram** [ReVanced/revanced-manager#2264]
### Feature description

Provide a list of presets for the patch *Spoof build info* that the user can select. Selecting one applies it to the fields, but leaves those fields editable. Provided presets should be there provided that they solve a problem (ex: Pixel 1 for Google Photos, Pixel 9 & 9 Pro for Pixel Screenshot).

### Motivation

I want to spoof my device for this app:

![Image](https://github.com/user-attachments/assets/6086df07-ffe8-416e-9fe5-bf3e886e869e)

However, I don't know what's all the information about the Pixel 9 Pro. I can google and find "caiman" easily, but what if something else was required? I'd need more of its information.

Someone with the appropriate device could extract the information and provide it to ReVanced for inclusion in a default preset.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [ ] The feature request is only related to ReVanced Manager.

**Comment by YarosMallorca** [comment]
This issue is more relevant for the [Revanced Patches Repository](https://github.com/ReVanced/revanced-patches/issues). Report there.

**Comment by VeryUsual** [comment]
Looks like it never got reported there... I would really like this feature.
