### ISSUE TITLE
bug: "Replying to" not working in patched twitter/x

### ISSUE THREAD

**Issue by Cloud-Mak** [ReVanced/revanced-manager#2266]
### Bug description

You patch the reccomended version of X/twitter app with default patches. After installation when you try to reply to tweets that have mutiple handles you can actually unselect/uncheck few handles while replying. The list that appears after one tap on "replying to" remains blank. Thus one can not unselect hanldes. Thus you're limited to reply to all handles present in original tweet. 
Have a look at below screenshot. the list of handles is not visible at all. 

![Image](https://github.com/user-attachments/assets/08c612b3-2626-4781-866a-409d33f81271)

### Version of ReVanced Manager and version & name of app you are patching

RV Manager - [v1.22.0](https://github.com/ReVanced/revanced-manager/releases/tag/v1.22.0)
X/Twitter - v10.48.0 (this is what was reccomend in RV manager

![Image](https://github.com/user-attachments/assets/b9678a1b-b3ce-4462-970d-5570ecb1661d)

### Installation method

None

### ReVanced Manager logs

10-20 22:29:53.617 19904 19904 I SurfaceView@6b0c68b: updateSurface: mVisible = false mSurface.isValid() = true
10-20 22:29:53.617 19904 19904 I SurfaceView@6b0c68b: tryReleaseSurfaces: set mRtReleaseSurfaces = true
10-20 22:29:53.617 19904 19924 I SurfaceView@6b0c68b: 34067693 wPL, frameNr = 0
10-20 22:29:53.617 19904 19924 I SurfaceView@6b0c68b: remove() from RT android.view.SurfaceView$SurfaceViewPositionUpdateListener@207d4ed Surface(name=SurfaceView - app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity@6b0c68b@3)/@0xc840f22
10-20 22:29:53.617 19904 19924 I SurfaceView@6b0c68b: remove() io.flutter.embedding.android.FlutterSurfaceView{6b0c68b V.E...... ........ 0,0-720,1600} Surface(name=SurfaceView - app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity@6b0c68b@3)/@0xc840f22
10-20 22:29:53.618 19904 19924 I SurfaceView@6b0c68b: aOrMT: uB = true t = android.view.SurfaceControl$Transaction@d46e73c fN = 0 android.view.SurfaceView.access$500:124 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionLost:1785 android.graphics.RenderNode$CompositePositionUpdateListener.positionLost:326 
10-20 22:29:53.618 19904 19924 I SurfaceView@6b0c68b: aOrMT: vR.mWNT, vR = ViewRootImpl@840fbac[MainActivity]
10-20 22:29:53.618 19904 19924 I ViewRootImpl@840fbac[MainActivity]: mWNT: t = android.view.SurfaceControl$Transaction@d46e73c fN = 0 android.view.SurfaceView.applyOrMergeTransaction:1628 android.view.SurfaceView.access$500:124 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionLost:1785 
10-20 22:29:53.618 19904 19924 I ViewRootImpl@840fbac[MainActivity]: mWNT: merge t to BBQ
10-20 22:29:53.619 19904 19924 D OpenGLRenderer: setSurface called with nullptr
10-20 22:29:53.619 19904 19924 D OpenGLRenderer: setSurface() destroyed EGLSurface
10-20 22:29:53.619 19904 19924 D OpenGLRenderer: destroyEglSurface
10-20 22:29:53.620 19904 19924 I BufferQueueProducer: [ViewRootImpl@840fbac[MainActivity]#7(BLAST Consumer)7](id:4dc000000007,api:1,p:19904,c:19904) disconnect: api 1
10-20 22:29:53.624 19904 19904 I BLASTBufferQueue: [ViewRootImpl@840fbac[MainActivity]#7] destructor()
10-20 22:29:53.624 19904 19904 I BufferQueueConsumer: [ViewRootImpl@840fbac[MainActivity]#7(BLAST Consumer)7](id:4dc000000007,api:0,p:-1,c:19904) disconnect
10-20 22:29:53.625 19904 19904 I ViewRootImpl@840fbac[MainActivity]: Relayout returned: old=(0,0,720,1600) new=(0,0,720,1600) req=(720,1600)8 dur=3 res=0x5 s={false 0} ch=true fn=2
10-20 22:29:53.625 19904 19904 I SurfaceView@6b0c68b: windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{6b0c68b V.E...... ........ 0,0-720,1600} of ViewRootImpl@840fbac[MainActivity]
10-20 22:29:53.625 19904 19904 D SurfaceView@6b0c68b: updateSurface: surface is not valid
10-20 22:29:53.625 19904 19904 D SurfaceView@6b0c68b: updateSurface: surface is not valid
10-20 22:29:53.967 19904 19904 I ViewRootImpl@840fbac[MainActivity]: stopped(true) old=false
10-20 22:29:53.968 19904 19904 D SurfaceView@6b0c68b: updateSurface: surface is not valid
10-20 22:29:53.979 19904 19904 D SurfaceView@6b0c68b: updateSurface: surface is not valid
10-20 22:29:54.054 19904 19904 D InputTransport: Input channel destroyed: 'ClientS', fd=127
10-20 22:30:21.710 19904 19904 I ViewRootImpl@840fbac[MainActivity]: handleAppVisibility mAppVisible=false visible=true
10-20 22:30:21.721 19904 19904 I SurfaceView@6b0c68b: onWindowVisibilityChanged(4) false io.flutter.embedding.android.FlutterSurfaceView{6b0c68b G.E...... ......I. 0,0-720,1600} of ViewRootImpl@840fbac[MainActivity]
10-20 22:30:21.721 19904 19904 D SurfaceView@6b0c68b: updateSurface: surface is not valid
10-20 22:30:21.722 19904 19924 D OpenGLRenderer: setSurface called with nullptr
10-20 22:30:21.726 19904 19904 I ViewRootImpl@840fbac[MainActivity]: Relayout returned: old=(0,0,720,1600) new=(0,0,720,1600) req=(720,1600)4 dur=3 res=0x1 s={false 0} ch=false fn=-1
10-20 22:30:21.726 19904 19904 D SurfaceView@6b0c68b: updateSurface: surface is not valid
10-20 22:30:21.730 19904 19904 D FileDialog: Picked file: content://com.android.externalstorage.documents/document/primary%3ADownload%2Fcom.twitter.android_10.48.0-release.0-310480000_minAPI26(arm64-v8a%2Carmeabi-v7a%2Cx86%2Cx86_64)(nodpi)_apkmirror.com.apk
10-20 22:30:21.754 19904 19904 I ViewRootImpl@840fbac[MainActivity]: stopped(false) old=true
10-20 22:30:21.754 19904 19904 D SurfaceView@6b0c68b: updateSurface: surface is not valid
10-20 22:30:21.756 19904 19904 I ViewRootImpl@840fbac[MainActivity]: stopped(false) old=false
10-20 22:30:21.758 19904 19904 D FileDialog: Launch...
10-20 22:30:21.758 19904 19904 D FileDialog: Copy on background...
10-20 22:30:21.777 19904 19904 I SurfaceView@6b0c68b: onWindowVisibilityChanged(0) false io.flutter.embedding.android.FlutterSurfaceView{6b0c68b V.E...... ......ID 0,0-720,1600} of ViewRootImpl@840fbac[MainActivity]
10-20 22:30:21.777 19904 19904 D SurfaceView@6b0c68b: updateSurface: surface is not valid
10-20 22:30:21.778 19904 19924 D OpenGLRenderer: setSurface called with nullptr
10-20 22:30:21.780 19904 30241 D FileDialog: Copying 'content://com.android.externalstorage.documents/document/primary%3ADownload%2Fcom.twitter.android_10.48.0-release.0-310480000_minAPI26(arm64-v8a%2Carmeabi-v7a%2Cx86%2Cx86_64)(nodpi)_apkmirror.com.apk' to '/data/user/0/app.revanced.manager.flutter/cache/com.twitter.android_10.48.0-release.0-310480000_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk'
10-20 22:30:21.786 19904 19904 I BufferQueueConsumer: [](id:4dc000000009,api:0,p:-1,c:19904) connect: controlledByApp=false
10-20 22:30:21.786 19904 19904 I BLASTBufferQueue: [ViewRootImpl@840fbac[MainActivity]#9] constructor()
10-20 22:30:21.787 19904 19904 I ViewRootImpl@840fbac[MainActivity]: Relayout returned: old=(0,0,720,1600) new=(0,0,720,1600) req=(720,1600)0 dur=8 res=0x7 s={true -5476376606556198912} ch=true fn=-1
10-20 22:30:21.787 19904 19904 I SurfaceView@6b0c68b: windowStopped(false) true io.flutter.embedding.android.FlutterSurfaceView{6b0c68b V.E...... ......ID 0,0-720,1600} of ViewRootImpl@840fbac[MainActivity]
10-20 22:30:21.787 19904 19924 I BufferQueueProducer: [ViewRootImpl@840fbac[MainActivity]#9(BLAST Consumer)9](id:4dc000000009,api:1,p:19904,c:19904) connect: api=1 producerControlledByApp=true
10-20 22:30:21.790 19904 19904 I BufferQueueConsumer: [](id:4dc00000000a,api:0,p:-1,c:19904) connect: controlledByApp=false
10-20 22:30:21.790 19904 19924 D OpenGLRenderer: eglCreateWindowSurface
10-20 22:30:21.790 19904 19904 I BLASTBufferQueue: [SurfaceView - app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity@6b0c68b@4#10] constructor()
10-20 22:30:21.790 19904 19904 I SurfaceView@6b0c68b: pST: sr = Rect(0, 0 - 720, 1600) sw = 720 sh = 1600
10-20 22:30:21.790 19904 19904 I SurfaceView@6b0c68b: onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
10-20 22:30:21.791 19904 19904 I SurfaceView@6b0c68b: pST: mTmpTransaction.apply, mTmpTransaction = android.view.SurfaceControl$Transaction@b9f5c0e
10-20 22:30:21.791 19904 19904 I SurfaceView@6b0c68b: updateSurface: mVisible = true mSurface.isValid() = true
10-20 22:30:21.791 19904 19904 I SurfaceView@6b0c68b: updateSurface: mSurfaceCreated = false surfaceChanged = true visibleChanged = true
10-20 22:30:21.791 19904 19904 I SurfaceView@6b0c68b: surfaceCreated 1 #1 io.flutter.embedding.android.FlutterSurfaceView{6b0c68b V.E...... ......ID 0,0-720,1600}
10-20 22:30:21.791 19904 19959 I BLASTBufferQueue: [SurfaceView - app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity@6b0c68b@3#8] destructor()
10-20 22:30:21.792 19904 19959 I BufferQueueConsumer: [SurfaceView - app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity@6b0c68b@3#8(BLAST Consumer)8](id:4dc000000008,api:0,p:-1,c:19904) disconnect
10-20 22:30:21.792 19904 19959 I BufferQueueProducer: [SurfaceView - app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity@6b0c68b@4#10(BLAST Consumer)10](id:4dc00000000a,api:1,p:19904,c:19904) connect: api=1 producerControlledByApp=true
10-20 22:30:21.794 19904 19904 I SurfaceView@6b0c68b: surfaceChanged (720,1600) 1 #1 io.flutter.embedding.android.FlutterSurfaceView{6b0c68b V.E...... ......ID 0,0-720,1600}
10-20 22:30:21.802 19904 19904 I ViewRootImpl@840fbac[MainActivity]: [DP] dp(1) 1 android.view.SurfaceView.updateSurface:1375 android.view.SurfaceView.setWindowStopped:383 android.view.SurfaceView.surfaceCreated:2051 
10-20 22:30:21.802 19904 19904 I ViewRootImpl@840fbac[MainActivity]: [DP] pdf(0) 1 android.view.SurfaceView.notifyDrawFinished:599 android.view.SurfaceView.performDrawFinished:586 android.view.SurfaceView.$r8$lambda$st27mCkd9jfJkTrN_P3qIGKX6NY:0 
10-20 22:30:21.802 19904 19904 I ViewRootImpl@840fbac[MainActivity]: [DP] rdf()
10-20 22:30:21.802 19904 19904 D ViewRootImpl@840fbac[MainActivity]: reportDrawFinished (fn: -1) 
10-20 22:30:21.803 19904 19904 I ViewRootImpl@840fbac[MainActivity]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11420 android.view.ViewRootImpl.performTraversals:4193 android.view.ViewRootImpl.doTraversal:2919 
10-20 22:30:21.803 19904 19904 D ViewRootImpl@840fbac[MainActivity]: Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
10-20 22:30:21.803 19904 19904 D ViewRootImpl@840fbac[MainActivity]: Creating frameCompleteCallback
10-20 22:30:21.805 19904 20897 I SurfaceView@6b0c68b: uSP: rtp = Rect(0, 0 - 720, 1600) rtsw = 720 rtsh = 1600
10-20 22:30:21.805 19904 20897 I SurfaceView@6b0c68b: onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
10-20 22:30:21.805 19904 20896 D ViewRootImpl@840fbac[MainActivity]: Received frameDrawingCallback frameNum=1. Creating transactionCompleteCallback=false
10-20 22:30:21.805 19904 20897 I SurfaceView@6b0c68b: aOrMT: uB = true t = android.view.SurfaceControl$Transaction@84ff621 fN = 1 android.view.SurfaceView.access$500:124 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1728 android.graphics.RenderNode$CompositePositionUpdateListener.positionChanged:319 
10-20 22:30:21.805 19904 20897 I SurfaceView@6b0c68b: aOrMT: vR.mWNT, vR = ViewRootImpl@840fbac[MainActivity]
10-20 22:30:21.805 19904 20897 I ViewRootImpl@840fbac[MainActivity]: mWNT: t = android.view.SurfaceControl$Transaction@84ff621 fN = 1 android.view.SurfaceView.applyOrMergeTransaction:1628 android.view.SurfaceView.access$500:124 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1728 
10-20 22:30:21.805 19904 20897 I ViewRootImpl@840fbac[MainActivity]: mWNT: merge t to BBQ
10-20 22:30:21.817 19904 19924 D ViewRootImpl@840fbac[MainActivity]: Received frameCompleteCallback  lastAcquiredFrameNum=1 lastAttemptedDrawFrameNum=1
10-20 22:30:21.818 19904 19904 I ViewRootImpl@840fbac[MainActivity]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4995 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
10-20 22:30:21.818 19904 19904 I ViewRootImpl@840fbac[MainActivity]: [DP] rdf()
10-20 22:30:21.818 19904 19904 D ViewRootImpl@840fbac[MainActivity]: reportDrawFinished (fn: -1) 
10-20 22:30:21.818 19904 19904 D InsetsSourceConsumer: ensureControlAlpha: for ITYPE_NAVIGATION_BAR on app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity
10-20 22:30:21.819 19904 19904 D InsetsSourceConsumer: ensureControlAlpha: for ITYPE_STATUS_BAR on app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity
10-20 22:30:21.840 19904 19904 I ViewRootImpl@840fbac[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
10-20 22:30:21.841 19904 19904 D InputMethodManager: startInputInner - Id : 0
10-20 22:30:21.841 19904 19904 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
10-20 22:30:22.951 19904 30241 D FileDialog: Successfully copied file to '/data/user/0/app.revanced.manager.flutter/cache/com.twitter.android_10.48.0-release.0-310480000_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk, bytes=121032236'
10-20 22:30:22.953 19904 19904 D FileDialog: ...copied on background, result: /data/user/0/app.revanced.manager.flutter/cache/com.twitter.android_10.48.0-release.0-310480000_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk
10-20 22:30:22.953 19904 19904 D FileDialog: ...launch
10-20 22:30:26.212 19904 19904 I ViewRootImpl@840fbac[MainActivity]: ViewPostIme pointer 0
10-20 22:30:26.276 19904 19904 I ViewRootImpl@840fbac[MainActivity]: ViewPostIme pointer 1
10-20 22:30:27.013 19904 19904 I DecorView: notifyKeepScreenOnChanged: keepScreenOn=true
10-20 22:30:27.038 19904 19904 I ViewRootImpl@840fbac[MainActivity]: Relayout returned: old=(0,0,720,1600) new=(0,0,720,1600) req=(720,1600)0 dur=9 res=0x1 s={true -5476376606556198912} ch=false fn=2
10-20 22:30:27.038 19904 19904 I ViewRootImpl@840fbac[MainActivity]: updateBoundsLayer: t = android.view.SurfaceControl$Transaction@4ef2b11 sc = Surface(name=Bounds for - app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity@4)/@0xea18fcb frame = 2
10-20 22:30:27.039 19904 19904 I ViewRootImpl@840fbac[MainActivity]: mWNT: t = android.view.SurfaceControl$Transaction@4ef2b11 fN = 2 android.view.ViewRootImpl.prepareSurfaces:2778 android.view.ViewRootImpl.performTraversals:4024 android.view.ViewRootImpl.doTraversal:2919 
10-20 22:30:27.039 19904 19904 I ViewRootImpl@840fbac[MainActivity]: mWNT: merge t to BBQ
10-20 22:30:27.045 19904 19904 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10503; state: ENABLED
10-20 22:30:28.961 19904 19913 I manager.flutte: Background concurrent copying GC freed 227821(8991KB) AllocSpace objects, 1(68KB) LOS objects, 47% free, 27MB/51MB, paused 85us,180us total 144.266ms
10-20 22:30:29.621 19904 19913 I manager.flutte: Background concurrent copying GC freed 496498(21MB) AllocSpace objects, 0(0B) LOS objects, 36% free, 41MB/65MB, paused 206us,96us total 249.269ms
10-20 22:30:30.323 19904 19913 I manager.flutte: Background concurrent copying GC freed 620850(25MB) AllocSpace objects, 0(0B) LOS objects, 28% free, 60MB/84MB, paused 186us,46us total 357.974ms
10-20 22:30:31.102 19904 19913 I manager.flutte: Background concurrent copying GC freed 776803(32MB) AllocSpace objects, 0(0B) LOS objects, 23% free, 79MB/103MB, paused 83us,128us total 463.074ms
10-20 22:30:31.998 19904 19913 I manager.flutte: Background concurrent copying GC freed 1119355(39MB) AllocSpace objects, 5(10MB) LOS objects, 20% free, 93MB/117MB, paused 123us,42us total 549.845ms
10-20 22:30:31.999 19904 19915 W System  : A resource failed to call close. 
10-20 22:30:32.801 19904 19913 I manager.flutte: Background concurrent copying GC freed 594707(16MB) AllocSpace objects, 8(544KB) LOS objects, 20% free, 90MB/114MB, paused 166us,314us total 212.083ms
10-20 22:30:33.401 19904 19913 I manager.flutte: Background concurrent copying GC freed 1214534(31MB) AllocSpace objects, 1(68KB) LOS objects, 19% free, 97MB/121MB, paused 105us,189us total 206.029ms
10-20 22:30:33.886 19904 19913 I manager.flutte: Background concurrent copying GC freed 1633125(36MB) AllocSpace objects, 2(96KB) LOS objects, 17% free, 111MB/135MB, paused 109us,55us total 285.222ms
10-20 22:30:34.335 19904 19913 I manager.flutte: Background concurrent copying GC freed 2028639(45MB) AllocSpace objects, 2(96KB) LOS objects, 16% free, 122MB/146MB, paused 257us,172us total 307.989ms
10-20 22:30:34.864 19904 19913 I manager.flutte: Background concurrent copying GC freed 2278924(51MB) AllocSpace objects, 1(80KB) LOS objects, 15% free, 135MB/159MB, paused 229us,67us total 399.456ms
10-20 22:30:35.510 19904 19913 I manager.flutte: Background concurrent copying GC freed 2526177(56MB) AllocSpace objects, 1(80KB) LOS objects, 13% free, 151MB/175MB, paused 201us,356us total 484.256ms
10-20 22:30:36.318 19904 19913 I manager.flutte: Background concurrent copying GC freed 2841099(62MB) AllocSpace objects, 0(0B) LOS objects, 12% free, 171MB/195MB, paused 242us,85us total 650.333ms
10-20 22:30:37.273 19904 19913 I manager.flutte: Background concurrent copying GC freed 3238366(72MB) AllocSpace objects, 0(0B) LOS objects, 10% free, 208MB/232MB, paused 198us,139us total 799.313ms
10-20 22:30:37.690 19904 19904 I ViewRootImpl@840fbac[MainActivity]: ViewPostIme pointer 0
10-20 22:30:37.812 19904 19904 I ViewRootImpl@840fbac[MainActivity]: ViewPostIme pointer 1
10-20 22:30:38.389 19904 19913 I manager.flutte: Background concurrent copying GC freed 4345169(95MB) AllocSpace objects, 0(0B) LOS objects, 9% free, 222MB/246MB, paused 296us,162us total 967.329ms
10-20 22:30:39.929 19904 19913 I manager.flutte: Background concurrent copying GC freed 2308631(70MB) AllocSpace objects, 0(0B) LOS objects, 8% free, 250MB/274MB, paused 178us,183us total 1.219s
10-20 22:30:41.846 19904 19913 I manager.flutte: Background concurrent copying GC freed 1618483(70MB) AllocSpace objects, 0(0B) LOS objects, 7% free, 305MB/329MB, paused 306us,151us total 1.602s
10-20 22:30:43.873 19904 19913 I manager.flutte: Background concurrent copying GC freed 2120668(88MB) AllocSpace objects, 4(15MB) LOS objects, 6% free, 337MB/361MB, paused 125us,52us total 1.735s
10-20 22:30:46.305 19904 19913 I manager.flutte: Background concurrent copying GC freed 2406038(99MB) AllocSpace objects, 1(68KB) LOS objects, 6% free, 355MB/379MB, paused 212us,63us total 2.117s
10-20 22:30:49.148 19904 19913 I manager.flutte: Background concurrent copying GC freed 2005908(110MB) AllocSpace objects, 8(10MB) LOS objects, 6% free, 330MB/354MB, paused 182us,46us total 2.119s
10-20 22:30:49.151 19904 19915 W System  : A resource failed to call close. 
10-20 22:30:51.918 19904 19913 I manager.flutte: Background concurrent copying GC freed 1568394(93MB) AllocSpace objects, 2(84KB) LOS objects, 7% free, 316MB/340MB, paused 150us,238us total 1.997s
10-20 22:30:54.810 19904 19913 I manager.flutte: Background concurrent copying GC freed 1478844(79MB) AllocSpace objects, 4(128KB) LOS objects, 7% free, 317MB/341MB, paused 178us,50us total 2.006s
10-20 22:30:57.878 19904 19913 I manager.flutte: Background concurrent copying GC freed 1461087(79MB) AllocSpace objects, 15(524KB) LOS objects, 7% free, 300MB/324MB, paused 136us,191us total 1.862s
10-20 22:31:01.005 19904 19913 I manager.flutte: Background concurrent copying GC freed 1229071(63MB) AllocSpace objects, 4(176KB) LOS objects, 6% free, 336MB/360MB, paused 226us,298us total 1.975s
10-20 22:31:03.979 19904 19913 I manager.flutte: Background concurrent copying GC freed 2201425(88MB) AllocSpace objects, 4(132KB) LOS objects, 6% free, 334MB/358MB, paused 250us,47us total 2.318s
10-20 22:31:06.724 19904 19913 I manager.flutte: Background concurrent copying GC freed 2353070(87MB) AllocSpace objects, 2(92KB) LOS objects, 6% free, 328MB/352MB, paused 141us,392us total 1.990s
10-20 22:31:09.698 19904 19913 I manager.flutte: Background concurrent copying GC freed 2174320(81MB) AllocSpace objects, 0(0B) LOS objects, 6% free, 331MB/355MB, paused 143us,199us total 2.146s
10-20 22:31:12.520 19904 19913 I manager.flutte: Background concurrent copying GC freed 2227235(85MB) AllocSpace objects, 0(0B) LOS objects, 6% free, 329MB/353MB, paused 181us,51us total 2.036s
10-20 22:31:15.233 19904 19913 I manager.flutte: Background concurrent copying GC freed 2194162(83MB) AllocSpace objects, 0(0B) LOS objects, 6% free, 328MB/352MB, paused 170us,62us total 1.970s
10-20 22:31:17.980 19904 19913 I manager.flutte: Background concurrent copying GC freed 2165896(81MB) AllocSpace objects, 0(0B) LOS objects, 6% free, 327MB/351MB, paused 170us,58us total 2.001s
10-20 22:31:20.039 19904 30669 I manager.flutte: Waiting for a blocking GC Alloc
10-20 22:31:20.505 19904 19913 I manager.flutte: Background concurrent copying GC freed 2622327(92MB) AllocSpace objects, 1(72KB) LOS objects, 5% free, 419MB/443MB, paused 140us,54us total 1.956s
10-20 22:31:20.505 19904 30669 I manager.flutte: Waiting for a blocking GC Alloc
10-20 22:31:20.505 19904 30669 I manager.flutte: WaitForGcToComplete blocked Alloc on HeapTrim for 466.235ms
10-20 22:31:20.505 19904 30669 I manager.flutte: Starting a blocking GC Alloc
10-20 22:31:20.515 19904 19915 W System  : A resource failed to call close. 
10-20 22:31:21.237 19904 30669 I manager.flutte: Waiting for a blocking GC Alloc
10-20 22:31:21.511 19904 19913 I manager.flutte: Background concurrent copying GC freed 5689996(293MB) AllocSpace objects, 1(68KB) LOS objects, 9% free, 218MB/242MB, paused 202us,42us total 797.179ms
10-20 22:31:21.511 19904 30669 I manager.flutte: WaitForGcToComplete blocked Alloc on Background for 273.986ms
10-20 22:31:21.511 19904 30669 I manager.flutte: Starting a blocking GC Alloc
10-20 22:31:22.462 19904 19913 I manager.flutte: Background concurrent copying GC freed 4201249(99MB) AllocSpace objects, 8(468KB) LOS objects, 9% free, 223MB/247MB, paused 298us,140us total 840.125ms
10-20 22:31:23.685 19904 19913 I manager.flutte: Background concurrent copying GC freed 4248869(99MB) AllocSpace objects, 25(940KB) LOS objects, 6% free, 323MB/347MB, paused 370us,111us total 925.989ms
10-20 22:31:24.444 19904 31388 I manager.flutte: Waiting for a blocking GC Alloc
10-20 22:31:24.444 19904 31390 I manager.flutte: Waiting for a blocking GC Alloc
10-20 22:31:24.444 19904 31387 I manager.flutte: Waiting for a blocking GC Alloc
10-20 22:31:24.444 19904 31389 I manager.flutte: Waiting for a blocking GC Alloc
10-20 22:31:24.913 19904 19913 I manager.flutte: Background concurrent copying GC freed 9200785(191MB) AllocSpace objects, 0(0B) LOS objects, 6% free, 320MB/344MB, paused 296us,64us total 1.155s
10-20 22:31:24.914 19904 31388 I manager.flutte: WaitForGcToComplete blocked Alloc on Background for 469.423ms
10-20 22:31:24.914 19904 31388 I manager.flutte: Starting a blocking GC Alloc
10-20 22:31:24.914 19904 31390 I manager.flutte: WaitForGcToComplete blocked Alloc on Background for 469.556ms
10-20 22:31:24.914 19904 31390 I manager.flutte: Starting a blocking GC Alloc
10-20 22:31:24.915 19904 31387 I manager.flutte: WaitForGcToComplete blocked Alloc on Background for 470.494ms
10-20 22:31:24.915 19904 31387 I manager.flutte: Starting a blocking GC Alloc
10-20 22:31:24.915 19904 31389 I manager.flutte: WaitForGcToComplete blocked Alloc on Background for 470.585ms
10-20 22:31:24.915 19904 31389 I manager.flutte: Starting a blocking GC Alloc
10-20 22:31:25.665 19904 31390 I manager.flutte: Waiting for a blocking GC Alloc
10-20 22:31:25.665 19904 31387 I manager.flutte: Waiting for a blocking GC Alloc
10-20 22:31:25.665 19904 31389 I manager.flutte: Waiting for a blocking GC Alloc
10-20 22:31:25.665 19904 31388 I manager.flutte: Waiting for a blocking GC Alloc

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [ ] The bug is only related to ReVanced Manager.

**Comment by Cloud-Mak** [comment]
for anyone reading this - https://github.com/crimera/piko

these patches worked for me. 

I am not sure what does not planned mean as reason to close this? This is the basic functionality. not sure why it wasn't working in 1st place.

**Comment by oSumAtrIX** [comment]
Acknowledgements not met
