### ISSUE TITLE
feat: Add automatically the integrations version when saving APK

### ISSUE THREAD

**Issue by Kuddus73** [ReVanced/revanced-manager#2273]
### Feature description

I think this PR can be quite useful to implement the feature as it is basically the same feature, but this time it appends the integrations version: [feat: append patch version to the APK name while sharing/exporting](https://github.com/ReVanced/revanced-manager/pull/1547)

When saving a patched APK, add also the integrations version next to the patches version (like _**youtube-revanced_v19.16.39-patches_v4.17.0-integrations_v1.16.0.apk**_).
![Image](https://github.com/user-attachments/assets/07d348d2-f907-4b61-b072-086de124d793)

### Motivation

The version of the integrations might not be important with ReVanced source because with the release of a new patches version also a new integrations version gets released.

**However, other resources, like [piko](https://github.com/crimera/piko), many times they only release a new version of integrations <ins>without releasing a new version of patches</ins>**, so automatically adding also the integrations version when saving the APK would help to not overwrite by mistake a previously saved APK with the same version, which is <ins>very useful if the current/latest release has a bug that causes a crash on startup, and so making it impossible to use that app until a fix is released</ins>.

I know we can just manually write the integrations version when saving, but this way would save time and also make the process more automatic and quick.</ins>

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] The feature request is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
Integrations version can be determined by the release time of the patches. Besides integrations are merged into patches in Patcher v20
