### ISSUE TITLE
bug: 3rd party allow screenshot not working

### ISSUE THREAD

**Issue by AntarCrypto** [ReVanced/revanced-manager#2287]
### Bug description

Tried to patch 3rd party app bigo live version 5.35.5
To remove screenshot restrictions but the showing installed from unauthorised sources,i was using lspatch and disable flag secure module to patch the app it was working fine but recently that module stopped working 
Step 1 -selected bigo live app 
Step 2- patched allow screenshot ![Image](https://github.com/user-attachments/assets/1c2a6bf4-d2ca-48a4-a600-b6900f450e5d)

### Version of ReVanced Manager and version & name of app you are patching

Revanced manager version -1.22.0
Bigo live -5.35.5[revanced-manager_logcat_20241104003242950925.log](https://github.com/user-attachments/files/17611698/revanced-manager_logcat_20241104003242950925.log)

### Installation method

Regular

### ReVanced Manager logs

Shared file

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
The patch worked but the app has different checks that prevent it from modification.
