### ISSUE TITLE
feat: UI Toggle Support for Non-multithreaded

### ISSUE THREAD

**Issue by rouxsean** [ReVanced/revanced-manager#2289]
### Feature description

revanced-manager/android/app/src/main/kotlin/app/revanced/manager/flutter/MainActivity.kt

Line 281: true // TODO: Add option to disable this

Please include a UI option to toggle this to "false".

### Motivation

Patching large applications (e.g. TikTok) on Android with multithreading simply doesn't work on multicore devices where the amount of memory given to the manager (regardless of the system RAM) is not sufficient.

Manually changing this to "false" and rebuilding the APK with every successive release is a chore. 

Alternatively, the default could be "false" until UI toggling is built? Which is more important: patching succeeds for all available use cases or only some patching succeeds with faster performance?

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] The feature request is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
The argument has been removed as memory consumption issues have been mitigated in new versions of ReVanced Patcher.

**Comment by rouxsean** [comment]
This argument is still there. [v1.23.0-dev.4] Line 186.

[v1.22.0] Sill has memory problems with large applications, particularly TikTok.

**Comment by oSumAtrIX** [comment]
Already fixed by https://github.com/ReVanced/revanced-manager/pull/2242
