### ISSUE TITLE
bug: App list shows empty [1.23.0-dev.4]

### ISSUE THREAD

**Issue by SayanthD** [ReVanced/revanced-manager#2297]
### Bug description

- The app list shows empty.

Steps to reproduce:
1. Patcher section 
2. "Select an app"
![Image](https://github.com/user-attachments/assets/1bcf157e-ee2d-479d-86c5-79e8ba3669ef)

Last working version: 1.23.0-dev.3

### Version of ReVanced Manager and version & name of app you are patching

Version: 1.23.0-dev.4
Model: RMX1971
Android Version: 10
Supported Archs: arm64-v8a, armeabi-v7a, armeabi

### Installation method

None

### ReVanced Manager logs

```shell
Nil
```

### Patch logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
That's because it is using patcher v21 and patches are currently patches v19. This is working as intended

**Comment by drooooov** [comment]
Same for me

**Comment by drooooov** [comment]
> That's because it is using patcher v21 and patches are currently patches v19. This is working as intended
 How do I get my apps to show then

**Comment by oSumAtrIX** [comment]
By using the release for everyone and not a dev release.
