### ISSUE TITLE
bug: new revanced app installing as a separate app (Debug signed)

### ISSUE THREAD

**Issue by Shazzkid** [ReVanced/revanced-manager#2299]
### Bug description

When updating the app through the revanced app, it is installing a separate revanced app (Debug signed)![Image](https://github.com/user-attachments/assets/c2a127d7-32ee-4383-bfb7-7aec6e86ba6e)

### Version of ReVanced Manager and version & name of app you are patching

1.23.0

### Installation method

None

### ReVanced Manager logs

```shell
N/a
```

### Patch logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
Should be just a visual bug.

**Comment by Shazzkid** [comment]
> Should be just a visual bug.

Both might be working fine but i now have 2 revanced apps, the original one, and a (Debug signed) version. ![Image](https://github.com/user-attachments/assets/ed969b2b-ac77-4861-a364-80673f47cfe1)

**Comment by oSumAtrIX** [comment]
I've pulled that release so that it wont get downloaded for now until the hotfix is pushed.

**Comment by oSumAtrIX** [comment]
Not sure, why but it branches off to the debug:

**Comment by Hikarikun42** [comment]
Btw why is the 1.23.0 marked as pre release on the github release page

**Comment by oSumAtrIX** [comment]
Might be fixed with https://github.com/ReVanced/revanced-manager/actions/runs/11766475941/job/32774048116

**Comment by oSumAtrIX** [comment]
I am not sure what you are referring to here.

**Comment by wolf-yuan-6115** [comment]
> I am not sure what you are referring to here.

I've updated the link, it said `signedConfigs` is debug

**Comment by oSumAtrIX** [comment]
Yes, but it is overriden by the release profile

**Comment by wolf-yuan-6115** [comment]
Aw I see

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-manager/actions/runs/11766634218 Another shot ;)

**Comment by Lassie111** [comment]
![Image](https://github.com/user-attachments/assets/ec14293a-946d-4f2f-848c-c3f6af6bb751)
Doesn't that last `}` become part of the filename?

**Comment by oSumAtrIX** [comment]
Good catch

**Comment by yonggamer** [comment]
i see this ![Image](https://github.com/user-attachments/assets/9fff4d21-e944-45a2-a0e2-4594f39492b2)

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-manager/actions/runs/11766663908 next attempt

**Comment by Shazzkid** [comment]
> https://github.com/ReVanced/revanced-manager/actions/runs/11766663908 next attempt

We have a winner!

**Comment by yonggamer** [comment]
but it failded

**Comment by Shazzkid** [comment]
> https://github.com/ReVanced/revanced-manager/actions/runs/11766663908 next attempt

Hmm, it has installed correctly, but it won't connect to the API. The Debug version does connect fine, so i think the issue is with this latest release. I've cleared the cache, restarted the app, no difference. Latest version won't connect to API, Debug version does.

**Comment by oSumAtrIX** [comment]
Can you connect to https://api.revanced.app/v4/patches?

**Comment by Vucko130** [comment]
> > https://github.com/ReVanced/revanced-manager/actions/runs/11766663908 next attempt
> 
> Hmm, it has installed correctly, but it won't connect to the API. The Debug version does connect fine, so i think the issue is with this latest release. I've cleared the cache, restarted the app, no difference. Latest version won't connect to API, Debug version does.

It connects. i am patching now.

**Comment by yonggamer** [comment]
yes but is this name by chioce?
![Image](https://github.com/user-attachments/assets/9fff4d21-e944-45a2-a0e2-4594f39492b2)

**Comment by Vucko130** [comment]
> yes but is this name by chioce? ![Image](https://github.com/user-attachments/assets/9fff4d21-e944-45a2-a0e2-4594f39492b2)

download latest one now from github releases.

**Comment by Shazzkid** [comment]
> > > https://github.com/ReVanced/revanced-manager/actions/runs/11766663908 next attempt
> > 
> > Hmm, it has installed correctly, but it won't connect to the API. The Debug version does connect fine, so i think the issue is with this latest release. I've cleared the cache, restarted the app, no difference. Latest version won't connect to API, Debug version does.
> 
> Resetting API URL fixed it for me.

Yes it seemed that is it automatically using the old API, instead of the new default API. Resetting it so it to force it to update to the new API works.
