### ISSUE TITLE
bug: Dashboard displays latest release timestamp incorrectly

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#2304]
### Bug description

On the cards in the dashboard that display when the last release for the ReVanced Manager and ReVanced Patches was, it displays "now ago" even though the most releases for the Manager and Patches were more than two hours ago.

![Image](https://github.com/user-attachments/assets/252e3461-01c2-4568-bb3f-4f5f89a36acb)

(Also, the text does not change even after the Manager is open for more than 1 minute)

### Version of ReVanced Manager and version & name of app you are patching

1.23.1

### Installation method

None

### ReVanced Manager logs

[revanced-manager_logcat_20241110133056042083.log.txt](https://github.com/user-attachments/files/17692574/revanced-manager_logcat_20241110133056042083.log.txt)

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
Shows the correct time on my end. Reinstall and try again.

**Comment by KobeW50** [comment]
The issue still occurs on a clean install. Interestingly, it works properly for the ReVanced Patches card when the `Use alternative sources` toggle is enabled (even though the sources are set to default).

https://github.com/user-attachments/assets/92947ff4-bc49-4589-8e97-57408e1985c1

Additionally, you can briefly see at 0:43 in the above video that after disabling the `Use alternative sources` toggle, the "Show changelog" button changes to the "Show update" button. 

In the below video I demonstrate this bug better:

https://github.com/user-attachments/assets/a889b654-0ea8-47b7-92f6-236bd7f73a46
