### ISSUE TITLE
bug: cant setup integrations in alternative sources menu anymore

### ISSUE THREAD

**Issue by isillo** [ReVanced/revanced-manager#2308]
### Bug description

In version 1.23.1 in Alternative Sources menu now we can only type in two fields - patches organization and patches sources. In previous manager versions we had two more fields: integrations organization and integrations source. Need all four to be able to use manager with other patches, i.e. crimera piko for twitter. Please give them back.

### Version of ReVanced Manager and version & name of app you are patching

1.23.1

### Installation method

None

### ReVanced Manager logs

```shell
N/A
```

### Patch logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
Theres no more integrations in Patcher v21 which ReVanced Manager uses.
