### ISSUE TITLE
bug: "Installation cancelled" error appears when patching an app using the latest version of ReVanced Manager even though the installation was not cancelled

### ISSUE THREAD

**Issue by Gestrid** [ReVanced/revanced-manager#2317]
### Bug description

1. Start patching with the default patches and recommended APK.
2. Patch appears to finish successfully.
3. Tapping "Install" shows the dialogue notifying the user to disable automatic updates for the patched APK.
4. After tapping okay, the app says the installation was cancelled.
5. Tapping the button to save the APK file itself does nothing.

### Version of ReVanced Manager and version & name of app you are patching

ReVanced Manager v1.23.2
YouTube v19.43.41

### Installation method

Regular

### ReVanced Manager logs

```shell
Pasting the contents of the file is making GitHub give a character length error. See first comment for log file upload.
```

### Patch logs

```shell
- Device Info
ReVanced Manager: 1.23.2
Model: Pixel 6 Pro
Android version: 15
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.43.41 (Suggested: 19.43.41)
Patches version: v5.0.2
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches

- Logs
Reading APK
Decoding app manifest
Loading patches
Deleting existing temporary files directory
Decoding resources
Initializing lookup maps
Executing patches
Applied 52 patches
Compiling modified resources
Aligning APK
Signing APK
Patched APK
Installing patched app
Installation canceled
Installing patched app
Installation canceled
Installing patched app
Installation canceled
Installing patched app
Installation canceled
```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] The bug is only related to ReVanced Manager.

**Comment by Gestrid** [comment]
[revanced-manager_logcat_20241115105449930406.log.txt](https://github.com/user-attachments/files/17778094/revanced-manager_logcat_20241115105449930406.log.txt)

**Comment by oSumAtrIX** [comment]
Uncheck save patched apk in settings. Check if you can reproduce the issue. If not, enable it again and check if you can reproduce it

**Comment by Gestrid** [comment]
Unchecking that option fixed the issue, though I'm not sure why. Assuming the option was available in previous versions of the ReVanced Manager (I rarely ever need to go to the options menu), it hasn't given me trouble before. Is it a recent problem caused by Android 15?

**Comment by KobeW50** [comment]
https://github.com/ReVanced/revanced-manager/issues/2224

**Comment by Gestrid** [comment]
> [#2224](https://github.com/ReVanced/revanced-manager/issues/2224)

Thanks for linking the issue here. I somehow missed it when I was searching for related issues before posting this one.

Maybe you or someone else could mention this issue in that one. I'd like to upload my logs to that issue, but the conversation is limited to contributers.

By the way, on a related note, I actually have the Google Play Store disabled (not uninstalled, just disabled), which, if I'm not mistaken, also disables both Play Services and Play Protect.
