### ISSUE TITLE
feat: patch options

### ISSUE THREAD

**Issue by yonggamer** [ReVanced/revanced-manager#2318]
### Feature description

i want 
Export patch options
Export patch options to a JSON file
Import patch options
Import patch options from a JSON file
![Image](https://github.com/user-attachments/assets/26d14425-670f-4a22-96be-667d567a7370)

### Motivation

it is handy to have

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] The feature request is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
All of this should be merged into the export and import settings preference. More granularity isn't really needed.
