### ISSUE TITLE
bug: what happen? I received this message when after i about to play a video

### ISSUE THREAD

**Issue by DeGretWar** [ReVanced/revanced-manager#2326]
### Bug description

There was a problem with the server
[400]
(Playback ID: tiSoFVCWHqq2ANXL

### Version of ReVanced Manager and version & name of app you are patching

Revanced Manager - 1.23.2

Youtube - 19.16.39

### Installation method

None

### ReVanced Manager logs

```shell
201822217922
```

### Patch logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [ ] The bug is only related to ReVanced Manager.

**Comment by Ushie** [comment]
Join the [Discord](https://revanced.app/discord) server for support
