### ISSUE TITLE
bug: Gray screen in patch settings

### ISSUE THREAD

**Issue by Lolisocks3** [ReVanced/revanced-manager#2327]
### Bug description

pixel 6 pro
android 15 (stock)
When you try to patch the application If you go to the patch settings, instead of the settings there will be a gray screen without the ability to set any settings for the patch 

Steps to reproduce a bug
1) Open manager
2) Select any application 
3) go to tab "select patches"
4) Open any patch settings

video: https://drive.google.com/file/d/10Ep46KQYpmlD6aFyXFQoGQhftikcCagG/view?usp=drivesdk

Note: This bug does not appear in all patches, but in large numbers. Some of them are very important to me
Also same bug on pixel 6 (android 15 stock)
### Version of ReVanced Manager and version & name of app you are patching

revanced manager 1.23.2
absolutely any app

### Installation method

None

### ReVanced Manager logs

```shell
The logs are empty, because I did not patch the applications because of this bug with the gray screen
```

### Patch logs

```shell
The logs are empty, because I did not patch the applications because of this bug with the gray screen
```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
Please attach the manager logs from the settings when the grey screen appears

**Comment by Lolisocks3** [comment]
> Please attach the manager logs from the settings when the grey screen appears

the logs are empty, the log file weighs 0 bytes and there is nothing in it

**Comment by Lolisocks3** [comment]
I have a feeling that manager completely broken on pixel os

**Comment by oSumAtrIX** [comment]
Please attach a recording how you click share logs and it's empty

**Comment by Lolisocks3** [comment]
> Please attach a recording how you click share logs and it's empty

https://drive.google.com/file/d/12hBsVio3kQkg22k8VcHyB3MgAgUkJzzD/view?usp=drivesdk

**Comment by Lolisocks3** [comment]
> > Please attach a recording how you click share logs and it's empty
> 
> https://drive.google.com/file/d/12hBsVio3kQkg22k8VcHyB3MgAgUkJzzD/view?usp=drivesdk

In the video did not notice that I opened the old logs. but this does not change the essence, the logs are still empty, even after trying to patch the app

**Comment by oSumAtrIX** [comment]
In your video use a different log viewer/text editor as well as open the correct log file

**Comment by Lolisocks3** [comment]
> In your video use a different log viewer/text editor as well as open the correct log file

![Image](https://github.com/user-attachments/assets/80f93ee1-df94-4fa1-b0dc-f668791951b6)
app name: LogLog. Still empty

**Comment by oSumAtrIX** [comment]
Please record the requested video.
