### ISSUE TITLE
bug: back button causing app close!

### ISSUE THREAD

**Issue by kazimmt** [revanced/revanced-manager#233]
### Type

Other

### Manager Branch

Flutter

### Bug description

After opening the app, if i go to patch menu or settings menu & click on back.
App close

Normally on any app, back button works to back to the previous page.

### Steps to reproduce

1. Open ReVanced Manager
2. Go to patcher page or settings page
3. Press back button
4. App close

### Android version

12

### Manager version

0.0.14

### Target package name

Not related

### Target package version.

Not related

### Installation type

Non-root

### Patches selected.

Not related

### Device logs (exported using Manager settings).

```shell
Not related i guess
```

### Screenshots or videos

https://user-images.githubusercontent.com/82371061/191083525-ef08ba4c-5914-41c8-8148-ebb1d570edc3.mp4

### Solution

Back button should come back to the previous page or Homepage (Dashboard)

**Comment by ILoveOpenSourceApplications** [comment]
Can this be classified as a bug or is it done intentionally?

**Comment by Ushie** [comment]
It is not intentional

**Comment by kazimmt** [comment]
> Can this be classified as a bug or is it done intentionally?

Can you explain what makes you think it's intentional? 
I guess it's not.

**Comment by ILoveOpenSourceApplications** [comment]
> > Can this be classified as a bug or is it done intentionally?
> 
> Can you explain what makes you think it's intentional? 
Not thinking. Just asking.

**Comment by EvadeMaster** [comment]
🎉 The fix for this issue have been applied in #1019 and released in ReVanced Manager v1.4.1

If problem persist, feels free to reopen this issue!

**Comment by kazimmt** [comment]
> If problem persist, feels free to reopen this issue!
> 

No need to reopen i guess
Looks like it fixed
