### ISSUE TITLE
feat: Option to see patches of a app without installation

### ISSUE THREAD

**Issue by Shane9248** [ReVanced/revanced-manager#2330]
### Feature description

I was trying to what kinds of patches some apps offer and to see the patches u have to install the apk which is fine if u are checking 1 or 2 apps ..but if u are checking multiple apps it becomes an annoyance as u will need to install so many apk's 

It will be really helpful if we can see the patches without needing to install the apk

### Motivation

It makes the user experience better

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] The feature request is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-manager/issues/2093
