### ISSUE TITLE
bug: Youtube interface with a lot of lag.

### ISSUE THREAD

**Issue by jhonnyn5** [revanced/revanced-manager#234]
### Type

Other

### Manager Branch

Compose

### Bug description

the interface has a lot of lag, and don't say it's because of the 60 fps screen.  The official vanced app is not that slow.

### Steps to reproduce

just navigate the interface.

### Android version

Android 12 One ui 4.1

### Manager version

0.0.14

### Target package name

app.revanced.android.youtube

### Target package version.

17.36.37

### Installation type

Non-root

### Patches selected.

Client spoof
Custom video buffer
Downloads 
Enable debugging
General ads
microG support
Minimized playback
Old quality layout
Premium heading
Return youtube dislike button
Theme
Video ads

### Device logs (exported using Manager settings).

```shell
Noone
```

**Comment by Aunali321** [comment]
Not manager issue. Wrong repository.
