### ISSUE TITLE
bug: (compose) - Not showing any plugins in Downloads.

### ISSUE THREAD

**Issue by vippium** [ReVanced/revanced-manager#2345]
### Bug description

There is no plugins showing in the downloads. It only shows `No plugins installed`.
![Image](https://github.com/user-attachments/assets/9d54b48a-5be3-4153-b104-33183059b24a)

### Version of ReVanced Manager and version & name of app you are patching

Lastest Action Build

### Installation method

None

### ReVanced Manager logs

```shell
...
```

### Patch logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] The bug is only related to ReVanced Manager.

**Comment by Axelen123** [comment]
Compose manager does not bundle any plugins. You install them separately as android apps. You can build the `example-downloader-plugin` folder in the [`compose/downloader-system`](https://github.com/ReVanced/revanced-manager/tree/compose/downloader-system) branch if you want to try it out.

**Comment by vippium** [comment]
Which plugins are there? Can you share some, so I can install them as separate app.

**Comment by Axelen123** [comment]
[This](https://github.com/ReVanced/revanced-manager/tree/compose/downloader-system/example-downloader-plugin) is the only one available (as far as I know). There are no prebuilt versions of it.

**Comment by Axelen123** [comment]
I don't know why it is not being built by CI. Still, the problem isn't high priority since compose manager is in beta.
