### ISSUE TITLE
bug(compose): Shows `Installation failed` dialog after installing the app.

### ISSUE THREAD

**Issue by vippium** [ReVanced/revanced-manager#2346]
### Bug description

The bug is that compose shows installation failed error even the app gets installed. The bug need a fix.
![Image](https://github.com/user-attachments/assets/826afc48-03c5-489d-9b23-b8c69e4b641d)
As you can see the OPEN button on the right-down side. And the gets installed in actually.

### Version of ReVanced Manager and version & name of app you are patching

Latest Action

### Installation method

Regular

### ReVanced Manager logs

```shell
...
```

### Patch logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] The bug is only related to ReVanced Manager.

**Comment by Axelen123** [comment]
Should be fixed by https://github.com/ReVanced/revanced-manager/commit/49f75f9edda5f217d561024f1f13969a490357a3
