### ISSUE TITLE
feat(compose): Add updated `.rvp patch bundle` support in manager.

### ISSUE THREAD

**Issue by vippium** [ReVanced/revanced-manager#2351]
### Feature description

Some of the patches are upgraded to. Rvp support which is still not supported by manager for auto update. If we choose it using file, it adds the bundle. Afterall Manager needs an update.

![Image](https://github.com/user-attachments/assets/070ac645-8600-451e-9124-1f946e299703)

### Motivation

It will help user in using all patch bundle enem with rvp support. More useful for those who are usetoo with compose.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] The feature request is only related to ReVanced Manager.

**Comment by Axelen123** [comment]
The `compose-dev` branch supports `rvp`. Only the latest commit of the branch supports the new json format used by that repo, so make sure you are using it.

**Comment by vippium** [comment]
Can you share that commit?

**Comment by Axelen123** [comment]
This one: https://github.com/ReVanced/revanced-manager/commit/9dc716b1c80dd9105ca9e8ee9de9dd6e60d52aae
