### ISSUE TITLE
bug: Incorrect themed icon in YouTube

### ISSUE THREAD

**Issue by ManWhoIsSus** [ReVanced/revanced-manager#2353]
### Bug description

YouTube when patched, with themed icins enabled system wide, shows the themed logo of revanved manager instead of YouTube![Image](https://github.com/user-attachments/assets/1f3437a4-e2ef-445b-a183-90dee4e2b1a9)
![Image](https://github.com/user-attachments/assets/ae398699-3876-45f7-9134-05270a07aa0f)
 

### Version of ReVanced Manager and version & name of app you are patching

Revanved manager is 1.23.2
YouTube is 19.46.42

### Installation method

Regular

### ReVanced Manager logs

```shell
--------- beginning of system
12-19 22:56:13.002 31653 31653 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-QEOWXQ/out.apk Binary XML file line #2
12-19 22:56:13.011 31653 31653 W PackageParser: Unknown element under <application>: property at /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-QEOWXQ/out.apk Binary XML file line #149
12-19 22:56:13.019 31653 31653 W PackageParser: No actions in intent filter at /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-QEOWXQ/out.apk Binary XML file line #483
--------- beginning of main
12-19 23:16:38.876  9819  9819 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=io.flutter.embedding.android.FlutterActivity$1@3b5a721
```

### Patch logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [ ] The bug is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
Probably some cache. Unless you applied the branding patch this can't happen. The branding patch does not include a monochrome icon either

**Comment by ManWhoIsSus** [comment]
I did not enable branding patch, I patched again for a good measure, same thing ![Image](https://github.com/user-attachments/assets/31baec2b-c14f-49bd-84cd-aa4ebf7c1783)

**Comment by oSumAtrIX** [comment]
[Follow and report back ](https://i.imgur.com/wTvWZMC.png)
