### ISSUE TITLE
bug(compose): Not allowing to patch above or below suggested version.

### ISSUE THREAD

**Issue by vippium** [ReVanced/revanced-manager#2358]
### Bug description

While using downloader, Manager is not allowing to patch other versions other than suggested version. If the patch support to higher version is provided but the suggested version is still lower, then it shows an error after downloading the apk.
But if we select apk from local and then patch, it'll patch it without errors. This error only happens while downloading apk through downloader.
![Image](https://github.com/user-attachments/assets/98c4871f-a9d6-42bb-8bb9-d689f39fca2c)

### Version of ReVanced Manager and version & name of app you are patching

Latest Action Build.

### Installation method

Regular

### ReVanced Manager logs

```shell
...
```

### Patch logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] The bug is only related to ReVanced Manager.

**Comment by Axelen123** [comment]
The downloader system was built around the assumption that the recommended version is the one most people want to use. This helps keep the code and user interface simple. Users that want to use a different version can download it manually.

**Comment by vippium** [comment]
> The downloader system was built around the assumption that the recommended version is the one most people want to use.

But can't you make little changes in it. So that if user wants to patch higher or lower version can patch it.

> Users that want to use a different version can download and select it from storage.

Then what will downloader make use of.

**Comment by Axelen123** [comment]
> But can't you make little changes in it. So that if user wants to patch higher or lower version can patch it.

The ApkMirror plugin for example doesn't know which version you actually picked. It is a browser that just waits until you attempt to download something. The app is not downloaded until patching starts, but the patching process cannot proceed if the version is incorrect since the patches were selected assuming a different version.

> Then what will using downloader make sense?

You can just pick the version that the downloader searched for. Users that want to use a different version can download manually.
