### ISSUE TITLE
feat: A tweak to remember the selected patches

### ISSUE THREAD

**Issue by erenmete** [revanced/revanced-manager#236]
### Type

Functionality

### Manager Branch

Flutter

### Issue

Selecting the patches over and over is too much work.

### Feature

A simple tweak in the app so that it remembers the selected patches for the next patch

### Motivation

Because it takes too long to select the patches every single time and it's impractical.

**Comment by Aunali321** [comment]
It already remembers it

**Comment by erenmete** [comment]
> It already remembers it

Not that I've seen so far, I still have to reselect the patches all over on latest update.

**Comment by Aunali321** [comment]
On home page, click on installed chip, on any app you have patched click on info -> patch

**Comment by erenmete** [comment]
> On home page, click on installed chip, on any app you have patched click on info -> patch

Yeah, that's what i did. Maybe it doesn't remember if the patching process crashed. I haven't tried yet with a successful patching, app seems to crash. I'll get back to you when i have a successful patch.

**Comment by TheJeterLP** [comment]
When I want to update my revanced app to the latest YouTube app I still have to select all the patches I want again, it would be nice to remember it for that case too

**Comment by Aunali321** [comment]
@TheJeterLP On homepage, click on installed chip, click on info button the app, click on patch and it should select the same patches and allow you to change selection.

**Comment by TheJeterLP** [comment]
> @TheJeterLP On homepage, click on installed chip, click on info button the app, click on patch and it should select the same patches and allow you to change selection.

Just tried it, doesn't work always. Sometimes it shows me the selection, sometimes it just straight away repatchey with the remembered patches

**Comment by erenmete** [comment]
Maybe remembering the selections whether or not the patching is successful would be a better option since there is a lot that can go wrong at this point and not every patch is successful so we lose the selected patches all the time.

**Comment by erenmete** [comment]
> There was a bug but it was fixed on v0.0.17. Can you confirm @erenmete ?

Which bug are you referring to? I've been using that version and there are a bunch of bugs.

 - YouTube app remains stock even though patching is successful
 - App crashes during patching and only fixed by a reboot
 - Patch selections are still not remembered unless patching is successful.

It occasionally works if you start completely fresh and avoid certain patches.

Patch selection is a rather big issue because sometimes you have to uninstall and reinstall the YouTube app and then the remembered patches are deleted. There is a lot of reasons that cause the remembered patches getting wiped.
