### ISSUE TITLE
feat: Add option to use old revanced patches

### ISSUE THREAD

**Issue by MrHuaweiFan** [ReVanced/revanced-manager#2364]
### Feature description

Just add an option to import .rvp files, and use old patches instead of the current one. 

### Motivation

I think its a pretty neat and basic option to have

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] The feature request is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patcher/issues/328#issuecomment-2560415388
