### ISSUE TITLE
feat: Add an option to edit the patch bundle's name in ReVanced Manager Compose

### ISSUE THREAD

**Issue by keepitlalala** [ReVanced/revanced-manager#2366]
### Feature description

Add an option to edit the patch bundle's name in RV Manager Compose.
![Image](https://github.com/user-attachments/assets/a4fae875-a87b-45ee-90de-0c5b9eeddcf9)
Instead of like this in the image, there could be an option to edit the patch bundle's name.

### Motivation

While using multiple patch bundles in ReVanced Manager Compose, it can be hard to differentiate between them since most of the patches forked from ReVanced have the same name, "ReVanced Patches". 

![Image](https://github.com/user-attachments/assets/61cdbab7-fc09-456e-a514-8f26a7f1b2d5)
This is the correct source, but all the patch bundles are named 'ReVanced Patches'.

It can be only differentiated using version number and variations in patches. Allowing users to edit the patch bundle's name would make it easier to identify and select the correct patches, improving the user experience while patching an app.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] The feature request is only related to ReVanced Manager.

**Comment by oSumAtrIX** [comment]
The name is retrieved from the manifest in the patches file. The respective sources are supposed to name them properly.
