### ISSUE TITLE
feat: Updating progress need some improvements

### ISSUE THREAD

**Issue by trmdi** [revanced/revanced-manager#239]
### Type

Cosmetic

### Manager Branch

Flutter

### Issue

When I press the Update button to update the manager, only a popup text appears and nothing more.
-> there should be a progress bar somewhere and the Update button should be disabled.

**Comment by Aunali321** [comment]
I will work on this soon!

**Comment by Lugieda** [comment]
What's the progress?

**Comment by SodaWithoutSparkles** [comment]
> I will work on this soon!

@Aunali321 Soon™?

**Comment by Aunali321** [comment]
Added in latest commit!
