### ISSUE TITLE
bug: Will not work on Galaxy S22

### ISSUE THREAD

**Issue by yusuo1** [revanced/revanced-manager#246]
### Type

Error at runtime

### Manager Branch

Flutter

### Bug description

Basically if you use the app as intended once it creates the YouTube Revanced app the app just will not open, it either flashes back to the app draw or just loads to a black screen

### Steps to reproduce

Install app to Galaxy S22

### Android version

Android 12

### Manager version

Version: 0.0.16
Model: SM-S901B
Android Version: 12
Arch: arm64-v8a

### Target package name

Youtube

### Target package version.

17.36.37

### Installation type

Non-root

### Patches selected.

General Ads
Video Ads
Micro G support

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Deleting existing resource cache directory
Decoding resources
Reading dex files
Merging integrations
Applying all patches
Executing 'resource-id-mapping-provider-resource-patch-dependency' of type: resource
Executing 'integrations' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'locale-config-fix' of type: resource
Skipping 'resource-id-mapping-provider-resource-patch-dependency' because it has already been applied
Executing 'settings-resource-patch' of type: resource
Executing 'settings' of type: bytecode
Executing 'general-ads' of type: bytecode
[success] general-ads
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'video-ads' of type: bytecode
[success] video-ads
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings-resource-patch' because it has already been applied
Executing 'microg-resource-patch' of type: resource
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-cast-button' of type: bytecode
Executing 'client-spoof' of type: bytecode
Executing 'microg-support' of type: bytecode
[success] microg-support
Skipping 'settings' because it has already been applied
[success] settings
Repacking patched apk
Compiling resources
Creating new dex file
Writing modified dex files
Finished!
Installing patched file using nonroot method
Installed!
```

### Screenshots or videos

![Screenshot_20220920-155430_YouTube](https://user-images.githubusercontent.com/36933650/191291811-c18628bc-50dd-4d73-82c1-2f4ef603a922.jpg)

**Comment by Aunali321** [comment]
Where did you get youtube from? you can't use one from play store.

**Comment by unshDee** [comment]
> Where did you get youtube from? you can't use one from play store.

I was also facing problems to get the patched app (using the stock YouTube app) to run on my S22. It also showed me a dialogue box, while applying the patch, saying something about split APK being detected.

I'll try to do it with my YouTube Vanced app.

**Comment by Aunali321** [comment]
Using youtube from play store wont work. Download full yt apk from apkmirror (17.36.37) (120mb+).

**Comment by unshDee** [comment]
> Using youtube from play store wont work. Download full yt apk from apkmirror (17.36.37) (120mb+).

Yes did that, it works with the downloaded APK.

**Comment by yusuo1** [comment]
Yes, installing apkmirror download as an update and them applying patches worked fine.

Doesn't see my shield tvs to cast to but I can live with that
