### ISSUE TITLE
no ?support for bot

### ISSUE THREAD

**Issue by AbsoluteStruukz** [revanced/revanced-manager#25]
#fuck dyno copy paste this in your source:

@client.command()
async def support(ctx):
    revancedsexier = discord.Embed(
        title = '',
        url= '',
        description = '\n',
        color=0xcc7ec1
    )
    guild = ctx.guild
    #revancedsexier.set_footer(text=f'{guild.name}',icon_url='')
    revancedsexier.set_thumbnail(url='https://cdn.discordapp.com/icons/952946952348270622/d011f1dc1d27e9001d243bdedaf7443b.webp?size=512')
    revancedsexier.add_field(name='**Do you have a problem or need help ❓**', value='You have asked a question that has already been answered in the <#953993848374325269> channel. Make sure to read it as it will answer a lot of your questions guaranteed.\n**🔸 Regarding your question**\nPlease make sure to read the second half of <#953993848374325269> `XV` if you have enough knowledge, otherwise, the first half applies.')
    await ctx.send(embed=revancedsexier)

**Comment by oSumAtrIX** [comment]
Please reopen your issue with proper wording and issue description

**Comment by TheJeterLP** [comment]
Also wrong place for that.
