### ISSUE TITLE
bug: manager crashes when using "text editing" gboard feature

### ISSUE THREAD

**Issue by devlocalhost** [revanced/revanced-manager#250]
### Type

Error while running the manager

### Manager Branch

Flutter

### Bug description

If you go to settings, click API URL, and use gboards text editing feature, the manager crashes

### Steps to reproduce

Step 1: open the manager, and go to settings
Step 2: click API URL, and "select all" using text editing feature
Step 3: manager crashes 

### Android version

13

### Manager version

0.0.16

### Target package name

None

### Target package version.

None

### Installation type

Root

### Patches selected.

None

### Device logs (exported using Manager settings).

```shell
Gist link because "body is too long"

https://gist.github.com/devlocalhost/03aefbb7a9349c332f5c85c9ff14b556
```

### Screenshots or videos

https://user-images.githubusercontent.com/56504654/191344540-e1afa25e-fb25-47c7-81c2-4e508011e0fd.mp4

**Comment by Aunali321** [comment]
Leaving this for later.
https://github.com/flutter/flutter/issues/110640

**Comment by Aunali321** [comment]
fixed.
