### ISSUE TITLE
Feature Request: Youtube Revanced for Android TV Support 

### ISSUE THREAD

**Issue by briantho** [revanced/revanced-manager#252]
### Type

Other

### Manager Branch

Flutter

### Issue

PLease add support for Android TV. I really would like to have Youtube Revanced on my android TV Box. Can this be added?

### Feature

Add support for youtube for android TV. Primarily, I'm looking for ad blocking support, as well as sponsorblock. Casting support is also a must. 

### Motivation

IMHO, there really isn't a good way for android tv devices such as the chromecast with google tv, to have the full revanced feature set. I'm aware there are apps like smarttubenext, and whatnot, but there are a number of features missing from them. For instance one cannot do true casting to smarttubenext, instead you have to input a code generated from smarttube next for the youtube app on your phone to find it. There are a number of problems with this approach, as not only is it considered legacy, but it does not work for programs like chrome, or youtube music. Anyway, I would really like support for patching the real youtube app on android tv. 

### Additional context

Again, I'm aware of smarttubenext, but for me that won't cut it. Please consider adding android tv support for revanced

**Comment by Canny1913** [comment]
Wrong repository.

**Comment by briantho** [comment]
ok, well which repo should i request this in then???

**Comment by Canny1913** [comment]
1)Patches.
2)It is already suggested.
