### ISSUE TITLE
feat: select all patches on second tap of `PatchesSelectorViewModel.onSelectAll`

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/revanced-manager#253]
### Type

Functionality

### Manager Branch

Flutter

### Issue

Since not all patches are recommended to be included by default, the deceiving `Select All` button at the patches selection screen causes issues later on for those who simply include all patches.

### Feature

Instead of toggling all patches, the following selections should be possible in the following order:

1. Select Recommended
2. Select All
3. Select None

 A warning should pop up when all patches are selected at step `2.` to inform the user, that patches, which are not recommended by default are included.

### Motivation

This feature will prevent users who simply include all patches, from getting commonly seen errors and instead, allow the user to select `all` recommended patches, or `all` patches if they explicitely opt in to not recommended patches.

### Additional context

![Select all patches button](https://user-images.githubusercontent.com/13122796/191381701-51c27f94-a8f6-4444-b8c2-ff4645e34141.png)

Related code:
https://github.com/revanced/revanced-manager/blob/70159b8cd85fc47e1a895f76574e12654c49a67b/lib/ui/views/patches_selector/patches_selector_view.dart#L76

**Comment by Aunali321** [comment]
It's already like that. 
By default all recommend patches are selected.
On the second tap all patches including the not recommended ones are selected. On third tap all patches are deselected. Make sure you used the latest build

**Comment by oSumAtrIX** [comment]
Is a warning included when all patches are selected?

**Comment by Aunali321** [comment]
No, will add it thanks.

**Comment by ponces** [comment]
> It's already like that. By default all recommend patches are selected. On the second tap all patches including the not recommended ones are selected. On third tap all patches are deselected. Make sure you used the latest build

I made a change on that logic but I regret. I can revert it to the way it was and a warning on select all as suggested.

**Comment by Aunali321** [comment]
Implemented in https://github.com/revanced/revanced-manager/commit/d8df377427f2be90b52a8833f8e61709a4b65e8c.
