### ISSUE TITLE
bug: Localization files should not use two characters code as file names

### ISSUE THREAD

**Issue by chiyi4488** [revanced/revanced-manager#254]
### Manager Branch

Flutter

### Bug description
As written in https://github.com/revanced/revanced-manager/pull/240#issuecomment-1252440963, although both Traditional Chinese and Simplified Chinese are Chinese, their characters and words are very different and cannot be shared in use.

The current situation in #248  is that the translations of Simplified Chinese and Traditional Chinese replace the contents of the zh file with each other. Therefore, using locale-containing language codes is a must and a solution to this problem. (zh-tw for traditional Chinese(Taiwan), zh-hk for traditional Chinese(Hong Kong), zh-cn for simplified Chinese(China))

**Comment by Aunali321** [comment]
Already fixed.
