### ISSUE TITLE
bug: Return YouTube Dislike not working 

### ISSUE THREAD

**Issue by BinaryBenevolence** [revanced/revanced-manager#255]
### Type

Error at runtime

### Manager Branch

Flutter

### Bug description

Even though the Return YouTube Dislike feature is enabled, the dislike counter is not showing. 

### Steps to reproduce

1. Enable Return YouTube Dislike
2. Load a video 

### Android version

13

### Manager version

0.0.16

### Target package name

YouTube 

### Target package version.

17.36.37

### Installation type

Non-root

### Patches selected.

Every patch except for the debug patch. 

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
09-20 20:51:41.807 31789 31789 E SurfaceSyncer: Failed to find sync for id=0
09-20 20:51:41.807 31789 31789 E SurfaceSyncer: Failed to find sync for id=1
09-20 20:51:41.807 31789 31789 E SurfaceSyncer: Failed to find sync for id=2
09-20 20:51:41.807 31789 31789 E SurfaceSyncer: Failed to find sync for id=3
09-20 20:51:41.807 31789 31789 E SurfaceSyncer: Failed to find sync for id=4
09-20 20:51:41.807 31789 31789 E SurfaceSyncer: Failed to find sync for id=5
```

### Screenshots or videos

![Screenshot_20220920-204544](https://user-images.githubusercontent.com/52634889/191391005-7d252f09-313d-4ab1-91c5-d43018638abd.png)

**Comment by BinaryBenevolence** [comment]
Why did you close this without explanation?

**Comment by oSumAtrIX** [comment]
Wrong repository/ Dupe issue on another.
