### ISSUE TITLE
bug: <YouTube music doesn't work even I. Apk mirror file latest version >

### ISSUE THREAD

**Issue by Vegetagiy123** [revanced/revanced-manager#256]
### Type

Error while running the manager

### Manager Branch

Compose

### Bug description

YouTube Revanced music from apk mirror latest version 5.25.51 does work even I tried patching if from YouTube apk mirror and it Revanced manger just crashes 

### Steps to reproduce

Step 1 fix YouTube music from crashing the manger 
Step 2 make sure YouTube music works 

### Android version

Android 13

### Manager version

Version 0.0.16

### Target package name

YouTube music Revanced 

### Target package version.

Apk mirror tried to install it and patch it through apk mirror 

### Installation type

Non-root

### Patches selected.

I selected all the options for patching 

### Device logs (exported using Manager settings).

```shell
The manger keeps crashing while I patch YouTube music
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Installing the YouTube music app keeps crashing the manger
```

### Screenshots or videos

YouTube music Revanced keeps crashing the manger while patching

**Comment by Aunali321** [comment]
Use recommend version not latest.

**Comment by Abilash-22** [comment]
Hey,
When can we expect the revanced manager to support 5.24.50 or higher version youtube music?
Because on Android 12 version, youtube music version 5.23.50 (latest supported version by revanced manager) is crashing and unbable to patch or anything.

**Comment by Aunali321** [comment]
> Hey, When can we expect the revanced manager to support 5.24.50 or higher version youtube music? Because on Android 12 version, youtube music version 5.23.50 (latest supported version by revanced manager) is crashing and unbable to patch or anything.

Not a manager issue. Needs to be bumped in revanced-patches.

**Comment by Abilash-22** [comment]
well, absolutely not a manager issue. Just wanted to know the progress like when can it support higher versions.
btw thanks for the quick response.

**Comment by Aunali321** [comment]
@Vegetagiy123 Try again on latest manager build.
