### ISSUE TITLE
bug: remove unused duplicate resources that exist in res/

### ISSUE THREAD

**Issue by dib12** [revanced/revanced-manager#257]
### Type

Other

### Manager Branch

Flutter

### Bug description

Remove duplicate resources that exist in res(not in the subfolders of res

### Steps to reproduce

After complied

### Android version

Android12

### Manager version

Latest

### Target package name

com.google.android.youtube

### Target package version.

17.36.37

### Installation type

Non-root

### Patches selected.

All

### Device logs (exported using Manager settings).

```shell
Null
```

### Screenshots or videos

![Screenshot_20220921-095818_Shady_Launcher](https://user-images.githubusercontent.com/61652361/191414461-94c294dd-5fa2-454d-956e-4b4b75a46487.png)

**Comment by Aunali321** [comment]
Not the job of the manager.
