### ISSUE TITLE
Bug: Blank Screen after Patching  

### ISSUE THREAD

**Issue by pcwizard7** [revanced/revanced-manager#258]
### Type

Error while running the manager

### Manager Branch

Flutter

### Bug description

after it's done patching, and you open the app for the first time and just blank screen. And close and reopen it doesn't make a difference

### Steps to reproduce

None

### Android version

Android 12

### Manager version

0.0.16

### Target package name

none

### Target package version.

none

### Installation type

Non-root

### Patches selected.

Note this is an old screenshot I have MicroG iselected too

### Device logs (exported using Manager settings).

```shell
none
```

### Screenshots or videos

![190963160-d61feaba-cd53-4cd6-89a2-ea4420ed566a](https://user-images.githubusercontent.com/28586567/191417937-76cce545-0066-4b5d-b5ed-3414d85d0716.jpg)

**Comment by Aunali321** [comment]
Provide device logs.

**Comment by pcwizard7** [comment]
[revanced-manager_logcat_20220921212120161738.log](https://github.com/revanced/revanced-manager/files/9616059/revanced-manager_logcat_20220921212120161738.log)

**Comment by Aunali321** [comment]
Try again with latest build of manager.

**Comment by pcwizard7** [comment]
It will now try to open then automatic close as you see in my clip. I have also attached screenshot of patches selected and new log

![Screenshot_20220922-192409](https://user-images.githubusercontent.com/28586567/191746840-92bf6402-9cbc-4d6a-b651-15e2e611388a.jpg)

https://user-images.githubusercontent.com/28586567/191747509-d6a9105d-36c8-4728-9b54-20d9982042f2.mp4

**Comment by pcwizard7** [comment]
Log
[revanced-manager_logcat_20220922192423771850.log](https://github.com/revanced/revanced-manager/files/9625669/revanced-manager_logcat_20220922192423771850.log)

**Comment by pcwizard7** [comment]
> Hey, @pcwizard7 , trh downloading the YouTube app from apk mirror, the standalone apk. Bundled one (also the one from play store) seems to do the same for me.
> 
> Try the standalone apk and report back if it works 🤎

Where the links, you used original and prebuild apk (I only see the apk for the manager)

**Comment by kenethc** [comment]
Use the apk from apkmirror - i used the nodpi file apk - YouTube v17.36.37

Also after installing, delete cache and delete data for YouTube. 

I patched only the below patches after and had no issues patching with Manager v0.0.21 and v0.0.22.

![IMG_20220923_131920](https://user-images.githubusercontent.com/20010886/192083621-9c0038b4-d86a-4560-83f2-934dae1423a0.jpg)
