### ISSUE TITLE
Screen rotation when full screen

### ISSUE THREAD

**Issue by TheTreebrook** [revanced/revanced-manager#259]
### Type

Cosmetic

### Manager Branch

Flutter

### Bug description

When full screening a video on samsung s22, video does not rotate unless auto rotate phone setting is on.

### Steps to reproduce

Full screen any video into landscape and then try to turn phone to flip orientation without having phones auto rotate setting on. 

### Android version

Android version 12

### Manager version

Manager version 0.0.16

### Target package name

Default youtube app

### Target package version.

Default youtube app version 17.33.42

### Installation type

Non-root

### Patches selected.

Everything available.

### Device logs (exported using Manager settings).

```shell
Cannot open .log file on phone, sorry.
```

**Comment by Aunali321** [comment]
Not manager issue. Open issue in revanced-patches.
