### ISSUE TITLE
gradle linux build failed

### ISSUE THREAD

**Issue by Emteckos2** [revanced/revanced-manager#26]
Welcome to Gradle 7.5-rc-1!

FAILURE: Build failed with an exception.

* Where:
Build file '/home/####/revanced-manager-main/app/build.gradle.kts' line: 20

* What went wrong:
null cannot be cast to non-null type kotlin.String

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 34s

Debian 11 testing

**Comment by Aunali321** [comment]
Add your credentials in build.gradle.kts.
