### ISSUE TITLE
feat: Custom keystores

### ISSUE THREAD

**Issue by PalmDevs** [ReVanced/revanced-manager#263]
**This is more detailed version of #184!**

### Type

Functionality

### Manager Branch

Flutter

### Issue

Let's say you messed up something and needed to reinstall Manager, you'll get a new keystore which means you'll need to reinstall the patched apps again.

### Feature

*Introducing... custom keystores!*  
Since keystores needed to be same to make apps updatable (for non-root users), why not add this as an option? This would make it easy for anyone trying to migrate from CLI or builders to Manager too!

You should be able to both use custom keystores AND save the current keystore file. I'm thinking we should add this into the Patcher or Dashboard page of Manager (but, preferably Patcher page). We could have a section that looks similar to

---
## Patcher
...
...

### Keystore
```
/-------------------------------------\
| Using manager.keystore     (Select) |
\-------------------------------------/
```

---

### Motivation

After all, CLI and many builders do support this feature. By replacing a file in a directory, you could achieve this. However, Manager is a different story, the keystore file is inaccessible without root. You wouldn't need to use custom keystores if you had root anyway.

**Comment by PandoraHayami** [comment]
I feel that this could be acomplished by adding importing of a keystore (With the user specifying the password) or  making that the manager doesn't save it's files in root but rather on /sdcard/*folder* or in the android directory.

**Comment by Aunali321** [comment]
Track for custom-keystore branch for updates.

**Comment by ILoveOpenSourceApplications** [comment]
Isn't this also already achieved?
