### ISSUE TITLE
Add Picture in picture on/off toggle in settings

### ISSUE THREAD

**Issue by VakHub** [revanced/revanced-manager#265]
### Type

Functionality

### Manager Branch

Flutter

### Issue

On Vanced we could play audio only on background 
automatically without the video and extra clicks. It had a PIP on/off toggle in Vanced settings. Now we have to find PIP in phone settings and turn off PIP access from there for Revanced. 

### Feature

Add toggle to turn off/on Picture in picture mode in Revanced settings

### Motivation

Easier for users to disable or enable PIP instead of going in phone settings and look for those settings which aren't easily accessible

**Comment by Aunali321** [comment]
Not a manager issue.
