### ISSUE TITLE
bug: <[error] *PATCH* depends on 'integrations' but the following error was raised>

### ISSUE THREAD

**Issue by muhammadbahaa2001** [revanced/revanced-manager#267]
### Type

Other

### Manager Branch

Flutter

### Bug description

I downloaded latest version of Revanced Manager, however every time I apply any patch it gives me this error [error] *PATCH* depends on 'integrations' but the following error was raised except theme patch although I tried to select YouTube.apk non split base and I get the same result/log and after that I try to launch the patched YouTube it doesn't work, just blank white/dark screen or it opens then crashes. 
PATCH = name of patch without stars*

### Steps to reproduce

Patcher --> Selected pre-Installed YouTube --> Selected Patches I need --> Installed --> Doesn't work white/dark screen or it might open but crashes

Patcher --> Selected YouTube.apk rom local storage  --> Selected Patches I need --> Installed --> Doesn't work white/dark screen or it might open but crashes

### Android version

DescendantOS Android 12L GSI VNDKLite

### Manager version

0.0.17

### Target package name

com.google.android.youtube

### Target package version.

YouTube 17.33.42 & 17.36.37

### Installation type

Non-root

### Patches selected.

Video Ads, Theme, Return YouTube Dislike, MicroG Suport & General Ads.

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Deleting existing resource cache directory
Decoding resources
Reading dex files
Merging integrations
Applying all patches
Executing 'integrations' of type: bytecode
[error] video-ads:app.revanced.patcher.patch.PatchResultError: 'video-ads' depends on 'integrations' but the following error was raised: java.lang.IllegalStateException: Encountered 1 parser syntax errors and 0 lexer syntax errors!
[error] return-youtube-dislike:app.revanced.patcher.patch.PatchResultError: 'return-youtube-dislike' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Executing 'locale-config-fix' of type: resource
Skipping 'locale-config-fix' because it has already been applied
Executing 'resource-id-mapping-provider-resource-patch-dependency' of type: resource
Executing 'settings-resource-patch' of type: resource
Executing 'microg-resource-patch' of type: resource
[error] microg-support:app.revanced.patcher.patch.PatchResultError: 'microg-support' depends on 'hide-cast-button' but the following error was raised: 'hide-cast-button' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
[error] settings:app.revanced.patcher.patch.PatchResultError: 'settings' depends on 'integrations' but the following error was raised: 'integrations' did not succeed previously
Repacking patched apk
Compiling resources
Creating new dex file
Writing modified dex files
Finished!
```

**Comment by Aunali321** [comment]
It's fixed. Try patching again.
