### ISSUE TITLE
feat: Mark errors in red

### ISSUE THREAD

**Issue by RobotHanzo** [ReVanced/revanced-manager#269]
### Type

Cosmetic

### Manager Branch

Flutter

### Issue

Currently, there are no differences between messages marked with [success] and [error]
This makes the logs harder to read

### Feature

Mark messages prefixed with [error] in red

### Motivation

To make the logs more readable

**Comment by RobotHanzo** [comment]
The line I'm referring to: 
![image](https://user-images.githubusercontent.com/36107150/191649998-4692db63-1133-4480-9e52-58737be713aa.png)

**Comment by ILoveOpenSourceApplications** [comment]
We've simplified the error message by specifying which patch failed during the patching process? Is it necessary to further change the colour of the error message?
