### ISSUE TITLE
bug: 'YouTube ReVanced freeze couple of seconds after every first opening'

### ISSUE THREAD

**Issue by sorgnar79** [revanced/revanced-manager#270]
### Type

Other

### Manager Branch

Flutter

### Bug description

YT ReVanced freeze couple of seconds after every first opening. Compare to official YT app it's the same time(in seconds) --> show adds on official app.
After that everything run normally.

### Steps to reproduce

Open ReVanced app
Freeze for couples of seconds than run normally 
Sound volume freeze too. 

![Screenshot_2022-09-21-20-16-17-789_app revanced android youtube](https://user-images.githubusercontent.com/114100483/191576260-a1906d35-0d52-4887-b46a-b376b51b9375.jpg)
![Screenshot_2022-09-21-20-16-37-573_app revanced android youtube](https://user-images.githubusercontent.com/114100483/191576296-329db27d-c301-46f5-9130-dabf2cbb12f8.jpg)

### Android version

Mi 9T Pro Android v.11

### Manager version

0.0.17

### Target package name

com.google.android.youtube

### Target package version.

17.36.37-1531571648_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk
### Installation type

Non-root

### Patches selected.

![Screenshot_2022-09-21-19-50-35-098_app revanced manager flutter](https://user-images.githubusercontent.com/114100483/191576000-961c0a70-ed68-4cbf-8a9b-ef098069e9ab.jpg)

### Device logs (exported using Manager settings).

```shell
Don't have.
The problem is in YouTube app after patching.
```

### Screenshots or videos

![Screenshot_2022-09-21-20-16-17-789_app revanced android youtube](https://user-images.githubusercontent.com/114100483/191576260-a1906d35-0d52-4887-b46a-b376b51b9375.jpg)
![Screenshot_2022-09-21-20-16-37-573_app revanced android youtube](https://user-images.githubusercontent.com/114100483/191576296-329db27d-c301-46f5-9130-dabf2cbb12f8.jpg)

### Solution

I'll ask ET's, better;)

### Additional context

.

**Comment by oSumAtrIX** [comment]
Please record everything from the beginning to this issue.

**Comment by sorgnar79** [comment]
https://s.go.ro/9u7kg4av

U have all u need

**Comment by sorgnar79** [comment]
Hello my brother.....
Please translate ....
Serios de ce ai pus pe net fără să mă întrebi?
Mi-ai trimis email și atât (aici trebuie sa vorbim). De ce apare și e
GitHub?

**Comment by sorgnar79** [comment]
https://github.com/revanced/revanced-manager/issues/270#issue-1381295689

**Comment by sorgnar79** [comment]
U have all u need...
https://s.go.ro/9u7kg4av

**Comment by sorgnar79** [comment]
Have Vanced, the original, still the best out there..... after mostly one year dead....
Still have, and working flawless

**Comment by oSumAtrIX** [comment]
Same behavior on regular YouTube.
