### ISSUE TITLE
bug: manager closes before ever going to the install part

### ISSUE THREAD

**Issue by Amby713** [revanced/revanced-manager#271]
### Type

Error at runtime

### Manager Branch

Flutter

### Bug description

Trying to update the patches on my YouTube and using revanced manager. Everything is fine, patches work and all, but it force closes

### Steps to reproduce

Run patcher
Select patch on YouTube
Run the process
Wait for it to do its job
It crashes

### Android version

Version: 0.0.17
Model: M2007J3SY
Android Version: 12
Arch: arm64-v8a

### Manager version

Version: 0.0.17
Model: M2007J3SY
Android Version: 12
Arch: arm64-v8a

### Target package name

com.google.android.youtube

### Target package version.

version 17.36.37

### Installation type

Root

### Patches selected.

All except autorepeat and microg 

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
09-14 14:07:22.198 15562  9383 W System  : A resource failed to call end. 
09-14 14:07:22.199 15562  9383 W System  : A resource failed to call end. 
09-14 14:07:22.199 15562  9383 W System  : A resource failed to call end. 
09-14 14:10:30.492 15562 15562 W DEVICE_APPS: Application with package name "com.google.android.youtube" is not installed on this device
09-14 14:10:41.507 15562  9383 W System  : A resource failed to call close.
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Logcat
```

### Screenshots or videos

Logcat 
[logs-2022-09-21-15-46-52.zip](https://github.com/revanced/revanced-manager/files/9620390/logs-2022-09-21-15-46-52.zip)

https://user-images.githubusercontent.com/105613369/191610671-c3432bab-a1b4-4ed2-b854-4101dd1b28f9.mp4

**Comment by ConnorJC3** [comment]
Same issue, logs: [revanced-manager_logcat_20220921193556870704_20220921193820.log.txt](https://github.com/revanced/revanced-manager/files/9621015/revanced-manager_logcat_20220921193556870704_20220921193820.log.txt)

**Comment by Aunali321** [comment]
Install same version of stock youtube first. Then patch it in manager. make sure to exclude microg.

**Comment by Amby713** [comment]
Did all of that before I posted here
Did it again after you replied

No go

**Comment by Amby713** [comment]
Did this before you replied, no go
Did this after you replied, no go
