### ISSUE TITLE
bug: Navigation bar covers bottom of patching log screen

### ISSUE THREAD

**Issue by bassmadrigal** [revanced/revanced-manager#272]
### Type

Cosmetic

### Manager Branch

Flutter

### Bug description

Using a rooted Pixel 6 on stock Android 13.0 with 3-button navigation enabled (gesture based navigation disabled)..

When Revanced Manager has finished patching and offers to install, the app doesn't resize to sit on top of the navigation bar. This leaves the bottom half of the buttons to be covered by the navigation bar.

### Steps to reproduce

Go through a patching of YouTube with 3-button navigation enabled and the install buttons on the bottom will be half covered.

### Android version

Stock Android 13.0, rooted with Magisk 25.2.

### Manager version

0.0.17

### Target package name

YouTube

### Target package version.

17.36.37

### Installation type

Root

### Patches selected.

Client Spoof
Custom Playback Speed
Disable Auto Captions
Disable Auto Player Popup Panels
Downloads
Hdr Auto Brightness
Hide Create Button
Hide Shorts Button
Old Quality Layout
Return YouTube Dislike
Seekbar Tapping
Sponsorblock
Swipe Controls
Settings

### Device logs (exported using Manager settings).

```shell
Log file does not save (possibly due to opening YouTube and then going back into ReVanced Manager).
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
N/A
```

### Screenshots or videos

![Screenshot_20220921-180616](https://user-images.githubusercontent.com/7354680/191640978-5ffb9cd6-6a06-4f94-a6d5-f4c692772010.png)

### Additional context

Unsure if the downloaded APK from the releases is flutter or compose. Kept it on the default of flutter.

**Comment by ponces** [comment]
You are using it wrong! Use gestures!
Just kidding :P
We'll look into it! Thanks

**Comment by escape0707** [comment]
> You are using it wrong! Use gestures!
> Just kidding :P
> We'll look into it! Thanks

https://developer.android.com/develop/ui/views/layout/edge-to-edge#handle-overlaps

**Comment by Aunali321** [comment]
Fixed in https://github.com/revanced/revanced-manager/commit/32fabcfa3fce73e04f243d22c381eddc3c71d6fe.

**Comment by prat89** [comment]
Was it reverted in v0.24? Why?

**Comment by Aunali321** [comment]
It other thing that was reverted not this.

**Comment by bassmadrigal** [comment]
> You are using it wrong! Use gestures!
> Just kidding :P 
> We'll look into it! Thanks

🤣 I wish I liked gestures... I tried it years ago when it was added to CyanogenMod and again when it was added to stock Android. It's just not my thing.

I'm a bit delayed, but I can confirm it is fixed on my phone. Thanks for the fix!
