### ISSUE TITLE
feat: When trying to patch a bundled/split apk the manager should refuse to patch with a message

### ISSUE THREAD

**Issue by thepcwiz101** [ReVanced/revanced-manager#273]
### Type

Functionality

### Manager Branch

Flutter

### Issue

Bundle apk files don't work. I confirmed through testing and found the notice isn't helpful and should be reworked.

### Feature

The manager should deny patching the apk with a message saying: "Bundle APK's are not supported. Make sure the apk you download is not a bundle. apkmirror.com is a good source of apk files and clearly states if the file you download is a bundle or not"

### Motivation

It clears up confusion i've noticed on reddit especially. Someone on r/revancedapp asked me how to find the correct apk.

**Comment by Aunali321** [comment]
Split apks do work but only for root. And we can not add apkmirror as source as it's third party.

**Comment by escape0707** [comment]
> And we can not add apkmirror as source as it's third party.

Just an after thought inspired by this issue but, can we add a button with a customizable url to open next to each apps' update available panel? Or something?

**Comment by escape0707** [comment]
I second this. Actually many people got confused when they patched over bundled APK but they force quit upon launch. That's a very odd UX because they won't directly learn which step is wrong before consulting at GitHub or discord.

**Comment by Aunali321** [comment]
Yupp already working on redoing dialog.

**Comment by Aunali321** [comment]
> "root not detected - split apk unable to be patched. Verify you have a non-bundled apk to patch with non-root"

Thing is we check root when they click on install as root.

**Comment by Aunali321** [comment]
> Yea after they spent several minutes patching the apk lol.

There is no other way though. We can't have a universal settings toggle because you would have to change settings for every app.
But i want to reimplement it inspired by the above issue.

**Comment by avarayr** [comment]
Please give some love to this issue :)) I ignored the warning prompt, but turns out it should've been a strict error prompt for nonroot.

**Comment by ILoveOpenSourceApplications** [comment]
Isn't this achieved with #973 ?
