### ISSUE TITLE
feat: Select versions of the Youtube APK before downloading and view available patches

### ISSUE THREAD

**Issue by VictorGamerLOL** [revanced/revanced-manager#277]
### Type

Cosmetic

### Manager Branch

Flutter

### Issue

You have to download youtube APKs in order to check which patches will be available on them. Only once you downloaded a youtube APK that is not supported you can view supported versions for every patch individually.

### Feature

A little dropdown menu to view all available youtube APK versions on something like APKmirror. If you select one of them it will show you which patches are supported on it and which are not. 

Or at least show us a list of versions that each patch supports without having to download one that is not supported every time.

### Motivation

Downloading an additional APK because you downloaded one that is too new is very annoying. I downloaded the lastest thing from APKmirror and then I see that very little patches are supported and then I had to go back. This will also help people tell when they can go ahead and download a newer version of the youtube APK instead of downloading 2 APKs every time.

**Comment by Aunali321** [comment]
> You have to download youtube APKs in order to check which patches will be available on them. Only once you downloaded a youtube APK that is not supported you can view supported versions for every patch individually.
> A little dropdown menu to view all available youtube APK versions on something like APKmirror. If you select one of them it will show you which patches are supported on it and which are not.
> Or at least show us a list of versions that each patch supports without having to download one that is not supported every time.

If you click on unsupported version button when you using unsupported version, it will show you what version that patch supports.

**Comment by Purexo** [comment]
Hello, I think from a user perspective it could be great to be able youtube apk from ReVanced Manager. But if Vanced is dead is mainly because they were redistributing the apk (and directly patched).
So for the perenity of the project, it's maybe safer users find by them self where download youtube apk.

But, an improvement could be allow from the manager to select an APK file instead the youtube app currently installed.
In general, once you have the patched version of the app, you don't want the original keep install and the OS prefer open the original in place of the patched version.

So please at least, give the possibility in the manager to select an apk file instead rely on currently installed version.

**Comment by reisxd** [comment]
> Hello, I think from a user perspective it could be great to be able youtube apk from ReVanced Manager.

I think you meant APK downloader, which won't be added
> But, an improvement could be allow from the manager to select an APK file instead the youtube app currently installed.

This already exists in Manager. Just press the "Storage" button while selecting the app you want to patch.

**Comment by Purexo** [comment]
1. Yes, and I understand why
2. Oh, I didn't seen the button 😅
I find the UI not clear.

I think the App selector should show all the apps the manager is able to patch (+prefered version).
Once the app is selected, a selector of the apk (currently installed, button "From storage", compatible apk from a predefined folder in settings)

**Comment by d1g33k** [comment]
It would be better to mention the supported versions upfront so that the most compatible version can be downloaded upfront. Right now it requires the APK to be selected to identify which was the last supported version, which then needs to be redownloaded.

**Comment by Aunali321** [comment]
Added in https://github.com/revanced/revanced-manager/commit/cbb36f2ec72d2fbafd582170972cbfac50a7a63e.
