### ISSUE TITLE
bug: <Aborting>

### ISSUE THREAD

**Issue by ESCORPDROID2002** [revanced/revanced-manager#279]
### Type

Error at runtime

### Manager Branch

Flutter

### Bug description

![Screenshot_20220922-205115](https://user-images.githubusercontent.com/89296947/191878953-c86467c2-4574-41f4-a60c-56a486e4f519.png)

### Steps to reproduce

![Screenshot_20220922-203610](https://user-images.githubusercontent.com/89296947/191878978-f24a6f57-be55-484d-809a-f3438e4cd0c0.png)

### Android version

11.0

### Manager version

Last

### Target package name

Spotify 

### Target package version.

Hidden bar premium 

### Installation type

Non-root

### Patches selected.

Spotify (hidden bar premium)
Version Spotify (last)

### Device logs (exported using Manager settings).

```shell
Motorola g9 power
```

### Screenshots or videos

![Screenshot_20220922-203600](https://user-images.githubusercontent.com/89296947/191879112-5a3e23e1-361b-4e94-98c8-3620def71d08.png)

**Comment by oSumAtrIX** [comment]
Not a manager issue.
