### ISSUE TITLE
Setting to add a Copy Link/Copy Link with timestamp buttons

### ISSUE THREAD

**Issue by essam87** [revanced/revanced-manager#281]
### Type

Other

### Manager Branch

Flutter

### Issue

It's not really a problem but it's a convenience issue where I have to click on the share button then click on copy link to copy the link of the video

### Feature

It's a feature that makes you choose where to add your Copy Link/Copy Link with timestamp buttons
![SmartSelect_20220923-071048_YouTube](https://user-images.githubusercontent.com/17764523/191896078-85c8f430-d004-48cd-87ec-a542a90086ea.jpg)
![SmartSelect_20220923-071059_YouTube](https://user-images.githubusercontent.com/17764523/191896110-860bddec-fbb8-4d27-b0e9-b987ae8db556.jpg)
![SmartSelect_20220923-071108_YouTube](https://user-images.githubusercontent.com/17764523/191896141-2482a827-9c61-4acb-b9fd-6e2c7e16a3e4.jpg)
![image](https://user-images.githubusercontent.com/17764523/191896629-cec6db39-b949-4819-9248-1e7456e0e31a.png)

I think this is a more convenient way to copy a video link and especially the link with a timestamp. 

### Motivation

Because I think people would love it and find it more convenient to copy the link of the video in one click instead of clicking the share button. And the copy link with timestamp is even more convenient because you can't really copy the link with timestamp without going into your browser and opening the video at the timestamp that you like then copying the link.

### Additional context

thanks for reading

**Comment by oSumAtrIX** [comment]
Wrong place to submit patch requests

**Comment by essam87** [comment]
where do I submit it?
