### ISSUE TITLE
feat: debugging options

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/revanced-manager#282]
### Type

Functionality

### Manager Branch

Flutter

### Issue

Currently debugging the manager is difficult. It is often necessary to reinstall the manager.

### Feature

Implement basic debugging options, such as:

- Delete the temporal manager folder
- Force update patches and integrations
- Export the manager folder to /sdcard/
- Delete the keystore
- Delete the logs
- Verbose logging
- Diagnose patched apps by logging exceptions via logcat

### Motivation

This feature will allow end users and developers to quickly debug issues.

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by vamsee9** [comment]
Is any started working on this ?, I have would like to work on this issue already cloned this project to local system. @oSumAtrIX please give me confirmation about working status. So i can start working on it.

**Comment by Aunali321** [comment]
Current progress of the issue:
- [X] Delete the temporal manager folder
- [X] Force update patches and integrations
- [X] Export the manager folder to /sdcard/
- [X] Delete the keystore
- [X] Delete the logs
- [X] Verbose logging
- [ ] Diagnose patched apps by logging exceptions via logcat
