### ISSUE TITLE
An Amoled Black Theme

### ISSUE THREAD

**Issue by Fatcakes** [revanced/revanced-manager#284]
I know it's not a priority, but would be nice at some point.

**Comment by PalmDevs** [comment]
It already exists named as the `theme` patch.

**Comment by PalmDevs** [comment]
Manager follows Material You's color scheme. If you use Repainter like me, it just works. But it would be nice though.
![Screenshot_20220923-143252_ReVanced Manager](https://user-images.githubusercontent.com/67689562/191911831-34e251e3-5260-43d3-a111-7085cda5378c.png)

**Comment by Aunali321** [comment]
Manager already has 4 themes. Light/Dark and Material You Light/Dark. Anymore themes is not needed for manager. It's not an app you would you for hours.
