### ISSUE TITLE
bug: Errors regarding resource patching not being available when trying to patch and install via root method hangs aftewards.

### ISSUE THREAD

**Issue by grian32** [revanced/revanced-manager#287]
### Type

Error at runtime

### Manager Branch

Flutter

### Bug description

I was trying to patch youtube with the `Minimized Play` and `Always Autorepeat` extensions, it started, got a few errors about resource patching not being enabled when trying to install Always Autorepeat then it finished, afterwards I tried to install it via the root method where it hanged.

I also tried exporting the apk and installing it that way, which resulted in an App not installed error.

### Steps to reproduce

1. Go to the patcher tab, select youtube as the application, select `Always Autorepeat` and Minimized Play` as the patches, tap Patch, wait for it to be finished, then tap install via root method

### Android version

11

### Manager version

0.0.20

### Target package name

com.google.android.youtube

### Target package version.

v17.36.37

### Installation type

Root

### Patches selected.

Always Autorepeat 0.0.1
Minimized Playback 0.0.1

### Device logs (exported using Manager settings).

```shell
https://pastebin.com/KuGWxmWu
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
https://pastebin.com/DJGXjnaN
```

### Screenshots or videos

![Screenshot_20220923-120744](https://user-images.githubusercontent.com/54550982/191929055-eb53b457-7f02-4c35-9285-3817788232e0.jpg)

### Solution

N/A

### Additional context

Im on a Samsung Note10+ with the default android distro installed(no custom ROMs or stuff like that)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Should be fixed in latest version if not open the issue with updates steps and details.
