### ISSUE TITLE
feat: Option to download patchable APK files

### ISSUE THREAD

**Issue by quillfires** [revanced/revanced-manager#289]
### Type

Functionality

### Issue

No option to download the stock APK files and PlayStore versions are ahead of the recommended versions of the patches 

### Feature

A tab or card that shows the latest APK files and option to download them from the manager app

### Motivation

Its hard to look for the specific versions of the apps and then comeback to the manager to patch them

### Additional context

PlayStore version of YouTube is not recommended for patching 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by escape0707** [comment]
This project can't directly promote or include apkpure or apkmirror list.

But I do think add a button to open a customizable URL is probably helpful.

**Comment by quillfires** [comment]
Yes, that would be a great workaround

**Comment by Delphox** [comment]
> This project can't directly promote or include apkpure or apkmirror link.
> 
> But I do think add a button to open a customizable URL is probably helpful.

In theory you can get any version from PlayStore API by specifying the versionCode (you can do it with Aurora Store for example). I don't know if you can specify to download non-split apk tho, but Patcher will eventually support splits anyway. So I believe this is how it's gonna be done in the future.

**Comment by erenmete** [comment]
You can actually patch a few versions ahead if you are specific in your patch selections. I am currently on the latest YouTube app version and patched it with these: 

![Screenshot_20220924-010430](https://user-images.githubusercontent.com/58091473/192062928-4a862213-c25d-4369-ad79-4034f6173fa1.png)

And it all works fine

**Comment by erenmete** [comment]
You can actually patch a few versions ahead if you are specific in your patch selections. I am currently on the latest YouTube app version and patched it with these: 

![Screenshot_20220924-010430](https://user-images.githubusercontent.com/58091473/192062928-4a862213-c25d-4369-ad79-4034f6173fa1.png)
![Screenshot_20220924-010629](https://user-images.githubusercontent.com/58091473/192063134-6044d5ca-a2bd-4f5d-8c60-d913b1fb3a90.png)

And it all works fine, except premium header but I am not sure that it is the latest versions fault. It works sometimes when i repatch it.

**Comment by escape0707** [comment]
I won't risk patching unsupported version so I'm fine with OP's suggestion.

**Comment by masterflitzer** [comment]
> This project can't directly promote or include apkpure or apkmirror link.
> 
> But I do think add a button to open a customizable URL is probably helpful.

what about using aurora? or does aurora only serve split apks?

if yes wouldn't it be time to support split apks anyway?

**Comment by hridoysarkar050** [comment]
Where can I get apk file of YouTube not xapk.

**Comment by escape0707** [comment]
> Where can I get apk file of YouTube not xapk. 

Be careful when you download, the us a single APK option on both APKPure and APK mirror.
