### ISSUE TITLE
bug: impossible installation state

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/revanced-manager#291]
### Type

Error while running the manager

### Bug description

Impossible installation state:

```text
Root: You can't install since it is from storage use non root instead
Non-root: Selected patches are for rooted phones, select Root
```

### Steps to reproduce

1. Select the YouTube application from the storage
2. Do not include the patch `microg-support`

### Manager version

`v0.0.23`

### Target package name

`com.google.android.youtube`

### Possible solution

The ReVanced Manager does not allow rooted installation from storage, for example when a base or full APK is chosen. 
The ReVanced Manager should allow mounting apps selected from storage.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by ReptilianEvolve** [comment]
Report the same issue:
![Screenshot_20220924-230032_ReVanced Manager](https://user-images.githubusercontent.com/55086576/192120135-b7a4dc2b-dc89-426e-9cd3-846c4760aeb5.png)

**Comment by ILoveOpenSourceApplications** [comment]
Eh, @oSumAtrIX ?
