### ISSUE TITLE
bug: Updates Patcher and Manager stuck on "loading..."

### ISSUE THREAD

**Issue by ljo123** [revanced/revanced-manager#292]
### Type

Error while running the manager

### Bug description

Fresh install of Revanced Manager on OnePlus 8, non-root. When I open the app under Dashboard, the Update section has patcher and manager stuck on loading... and if I select an apk (YT 17.33.42) in the Patcher screen, it can't find any patches for it.

### Steps to reproduce

Fresh install of manager...

### Android version

Android 12

### Manager version

0.0.24

### Target package name

Youtube

### Target package version.

17.33.42

### Installation type

Non-root

### Patches selected.

n/a no patches found

### Device logs (exported using Manager settings).

```shell
n/a no logged errors
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by tensor-programming** [comment]
Saw this same issue while rooted on `0.22`.  When attempting to patch youtube as well, it seemed like it had no internet connection because it showed no patches nor did it show any of the installed apps.

**Comment by ljo123** [comment]
> Saw this same issue while rooted on `0.22`. When attempting to patch youtube as well, it seemed like it had no internet connection because it showed no patches nor did it show any of the installed apps. Fix for me was to downgrade to `0.21`, but like the OP mentioned, it was all a fresh install originally.

Thanks! Downgrading to 0.21 fixed the issue.

**Comment by 3pic-person** [comment]
Same problem on a Pixel 3 XL

**Comment by SkeleBones** [comment]
Same issue on Pixel 2 XL.

**Comment by Freepony** [comment]
I'm experiencing this on 0.0.26. Reinstalling, clearing data won't help.

**Comment by GarnetSunset** [comment]
Same issue on 0.0.26!

**Comment by Devo7v** [comment]
I have the same issue on 0.26, 0.27, & 0.28.

If I clear data and reboot it works properly, but if I refresh the home screen it gets stuck on loading as described in the bug report. I have granted ReVanced root and I'm also using AdAway if that matters.

**Comment by PicoPlanetDev** [comment]
Same issue here on `0.0.28` and `0.0.27` (product of me not remembering which was the last working version mentioned in this issue) but reverting to `0.0.21` worked for me. I'm running Android 13 on a Pixel 6a.

**Comment by GarnetSunset** [comment]
Reverting to ``0.0.21`` and upgrading worked

**Comment by mohamedamrnady** [comment]
Issue faced on 0.0.28 too, downgrading too 0.0.21 didn't work, but using Mobile Data instead of WiFi worked

Android 13

**Comment by the-nothingman** [comment]
> Issue faced on 0.0.28 too, downgrading too 0.0.21 didn't work, but using Mobile Data instead of WiFi worked
> 
> Android 13

Same, manager does not seem to work over wifi

**Comment by mohamedamrnady** [comment]
> > Issue faced on 0.0.28 too, downgrading too 0.0.21 didn't work, but using Mobile Data instead of WiFi worked
> > 
> > Android 13
> 
> Same, manager does not seem to work over wifi 

One of the APIs is returns null when on wifi

**Comment by Aunali321** [comment]
Fixed in https://github.com/revanced/revanced-manager/commit/78428f6bd3876162a1a70be5ae570d6278156edd

**Comment by mohamedamrnady** [comment]
> Fixed in [78428f6](https://github.com/revanced/revanced-manager/commit/78428f6bd3876162a1a70be5ae570d6278156edd)

Now app doesn't start.

`Launching lib\main.dart on M2102J20SG in debug mode...
Parameter format not correct -
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at 
W/SQLiteLog(22732): (28) double-quoted string literal: "3724CEF9BAF2F2930E2C169DBBF10D15"
W/SQLiteLog(22732): (28) double-quoted string literal: "22D1CC376C54BE531C0A569AA1492CA8"
I/DynamiteModule(22732): Considering local module com.google.android.gms.cronet_dynamite:0 and remote module com.google.android.gms.cronet_dynamite:1611
I/DynamiteModule(22732): Selected remote version of com.google.android.gms.cronet_dynamite, version >= 1611
V/DynamiteModule(22732): Dynamite loader version >= 2, using loadModule2NoCrashUtils
W/System  (22732): ClassLoader referenced unknown path:
W/manager.flutter(22732): ClassLoaderContext type mismatch. expected=PCL, found=DLC (PCL[] | DLC[];PCL[/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk*1388070714:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes2.dex*3313865753:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes3.dex*1392199187:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes4.dex*3326672379:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes5.dex*844133489:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes6.dex*1358221380:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes7.dex*3591929989:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes8.dex*2495316140:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes9.dex*3390550838:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes10.dex*1052147583:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes11.dex*1858205109:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes12.dex*1219502823:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes13.dex*3529776866:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes14.dex*3805757262:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes15.dex*2464319290:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes16.dex*1618311556:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes17.dex*3774864599:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes18.dex*2907536369:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes19.dex*2753801563:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes20.dex*392541211:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes21.dex*3774364494:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes22.dex*3191993809:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes23.dex*289319675:/data/app/~~UeXO9oE-C83AoJJVHQnuYA==/app.revanced.manager.flutter-hJHGtKoEFLcdYz2yMzAZMw==/base.apk!classes24.dex*1735244391])
I/cr_CronetLibraryLoader(22732): Cronet version: 106.0.5249.23, arch: aarch64
E/cr_CronetUrlRequestContext(22732): Exception in onFailed method
E/cr_CronetUrlRequestContext(22732): java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter info
E/cr_CronetUrlRequestContext(22732): 	at io.flutter.plugins.cronet_http.CronetHttpPlugin$createRequest$cronetRequest$1.onFailed(Unknown Source:7)
E/cr_CronetUrlRequestContext(22732): 	at fp.onFailed(:com.google.android.gms.dynamite_cronetdynamite@223913044@22.39.13 (190400-0):0)
E/cr_CronetUrlRequestContext(22732): 	at er.run(:com.google.android.gms.dynamite_cronetdynamite@223913044@22.39.13 (190400-0):1)
E/cr_CronetUrlRequestContext(22732): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/cr_CronetUrlRequestContext(22732): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/cr_CronetUrlRequestContext(22732): 	at java.lang.Thread.run(Thread.java:1012)
`

**Comment by SkeleBones** [comment]
Having the same issue on 0.0.29. It works fine with only mobile data enabled.

**Comment by Aunali321** [comment]
Closed in favour of #379.

**Comment by LavaCreeperYT** [comment]
The same issue on Redmi Note 12 Pro Plus 5g running EvolutionX (app ver: 1.25.1)
Update: actually the API website is down lol
