### ISSUE TITLE
feat: MIRROR BUTTON FOR SMART TV 

### ISSUE THREAD

**Issue by Matheus-TestUser1** [revanced/revanced-manager#293]
### Type

Functionality

### Issue

mirror button for smart tv    

### Feature

![Screenshot_20220924-104404_YouTube](https://user-images.githubusercontent.com/99508668/192101644-aa472f13-8f17-4449-91ed-e26360561338.jpg)

### Motivation

I miss this feature 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Exclude hide cast button and microg patch (requires root).
