### ISSUE TITLE
feat: <Ability to save patched apk>

### ISSUE THREAD

**Issue by hridoysarkar050** [revanced/revanced-manager#297]
### Type

Functionality

### Issue

Manager isn't saving the patched apk on Storage.

### Feature

Add option for saving the patched apk

### Motivation

It would be a handy feature for everyone.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Already possible, click on ... after patching and share the app from there.
