### ISSUE TITLE
feat: generate signing key

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#304]
### Type

Functionality

### Issue

Currently, the manager exposes its signing password in version control: https://github.com/revanced/revanced-manager/blob/e12532ea4c149bde6e78efe5d3e27283d3909f80/android/app/src/main/kotlin/app/revanced/manager/flutter/MainActivity.kt#L244

### Feature

Auto-generate the password. Allow to change it in the settings.

### Motivation

This way, the password would not be leaked, strong through a default random key and thus the keystore file would remain secure.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by ILoveOpenSourceApplications** [comment]
Isn't this also achieved by letting the user pick their own keystore password?

**Comment by ILoveOpenSourceApplications** [comment]
@oSumAtrIX?

**Comment by Ushie** [comment]
Yes but that's a more complicated process as keystore files are generally somewhat complicated to make
