### ISSUE TITLE
App info button is placed in a wrong position

### ISSUE THREAD

**Issue by HeroGalak** [revanced/revanced-manager#309]
### Type

Cosmetic

### Bug description

Title is self explanatory

### Steps to reproduce

Install manager v0.0.26

### Android version

Android 12

### Manager version

v0.0.26

### Target package name

//

### Target package version.

//

### Installation type

Non-root

### Patches selected.

//

### Device logs (exported using Manager settings).

```shell
//
```

### Screenshots or videos

Screenshot:
![Screenshot_20220926-095755](https://user-images.githubusercontent.com/69464248/192234837-f1538381-da7d-4639-ab96-f19ef6453358.jpg)

### Additional context

Device: Samsung A52s 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by pietryszak** [comment]
Android 12 Samsung S21 FE, looks good![Screenshot_20220926-132241.jpg](https://user-images.githubusercontent.com/45850093/192264413-8bb93aaf-67b4-40dc-8344-16f4a9b5c9b5.jpg)

**Comment by HeroGalak** [comment]
Solved by reinstalling from zero the manager

**Comment by HeroGalak** [comment]
Installed from zero v0.0.34 and the bug is still there.

![Screenshot_20220926-095755.jpg](https://user-images.githubusercontent.com/69464248/196431680-3ad0088a-ba3d-420d-8766-b2b2ae563a06.jpg)

**Comment by Ushie** [comment]
Closed in favor of #333
