### ISSUE TITLE
bug: Manager v25 shows v24 in About screen 

### ISSUE THREAD

**Issue by kenethc** [revanced/revanced-manager#310]
### Type

Other

### Bug description

Manager v25 shows v24 in About screen 
Manager shows there's an update forever

### Steps to reproduce

None

### Android version

12

### Manager version

0.0.25

### Target package name

None

### Target package version.

None

### Installation type

Root

### Patches selected.

Not applicable

### Device logs (exported using Manager settings).

```shell
None
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Known. Will be fixed in next build.

**Comment by kenethc** [comment]
Well noted. Will not report similar bug in the future.
