### ISSUE TITLE
feat: intrigue reading warnings on patches selector

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/revanced-manager#313]
### Type

Cosmetic

### Issue

If a patch is unsupported, the manager will display a warning saying it is unsupported. The UX of this element leaves room for improvement, because the user does not know they can click on it.

### Feature

Change the text to "Warning". This intrigues the user to click on it because it does not explicitly name the warning.

### Motivation

This change will reduce the amount of confusion when a user is confronted with a warning.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
Completed in a5511c2a2cfc10995d7908341b44b465588d6c86
