### ISSUE TITLE
feat: Ability to clean build cache manually w/o deleting keystore

### ISSUE THREAD

**Issue by ktheticdev** [revanced/revanced-manager#316]
### Type

Functionality

### Issue

Automatic cache cleaning sometimes does not happen.

### Feature

Ability to clean cache manually would solve that.

### Motivation

Nobody likes when the manager app takes up to 800 mb.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
In 0.0.31, the keystore is now stored in Android/data/app.revanced.manager.flutter/files. Clearing the cache now won't delete the keystore.
