### ISSUE TITLE
feat: side buttons at the bottom of the video player

### ISSUE THREAD

**Issue by justAMZ** [revanced/revanced-manager#317]
### Type

Functionality

### Issue

theres no side buttons at the bottom right of the youtube player (not in fullscreen, minimized or normally)

### Feature

basically, youtube vanced had options to add a loop button, a copy link button and a copy link with set time button at the bottom right of the video player (next to the fullscreen button). i, and prolly a lot of other people use those features a lot and we would love if we got em in revanced

### Motivation

because its a very important feature (especially the loop one) that i think everyone would use and need in the revanced patch

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Not a manager issue. Open the issue on revanced-patches but it's already suggested.
