### ISSUE TITLE
feat: feature to go instantly to quality options in youtube revanced

### ISSUE THREAD

**Issue by justAMZ** [revanced/revanced-manager#318]
### Type

Functionality

### Issue

to go change the quality (which youtube has made hella fucking hard these days) you have to go to the cog in the video player, pick quality, and then pick one of the 4 other fucking options to go to the real quality settings (by this i mean 144p, 240p, 360p, 480p, 720p, 1080p etc)

### Feature

youtube vanced already had the option to go instantly to the quality picker so it wouldnt be a bad idea to implement it on to revanced with a patch

### Motivation

everyone hates the new youtube quality picker so id say thats a good reason why lmao

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
@justAMZ reminding you again, manager has nothing to do with youtube features. Open an issue on revanced-patches.

**Comment by justAMZ** [comment]
> 

i just wanted to say im really sorry
how do i delete the post and send it to revanced patches

**Comment by Aunali321** [comment]
No need to delete. That feature you're talking about already exists. It's called old quality layout.

**Comment by Aunali321** [comment]
There isn't a patch for that but it's already suggested.

**Comment by justAMZ** [comment]
> There isn't a patch for that but it's already suggested.

will it be implemented into ytrv? also where do i talk about this one issue ive been having with revanced manager, where youtube never goes past the youtube logo and crashes? right now i used another manager for youtube revanced but i really wanna use the official one

**Comment by Aunali321** [comment]
Well be implemented but no eta. For manager issue, open issue properly fill asked questions.
