### ISSUE TITLE
Remember checked patches 

### ISSUE THREAD

**Issue by vasile-coste** [revanced/revanced-manager#321]
### Type

Functionality

### Issue

It is kind of redundant to have to re-select all the patches every time you want to patch an app

### Feature

Remember selected patches for next use for each app

### Motivation

Make it easier to patch and re-patch the app

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by bassmadrigal** [comment]
It does remember them. If you click `info` next to the app(s) you have installed, then click on `patch` and it'll allow you to run an update.

I would like an option to save patch selections if you need to remove the patched version for some reason.

**Comment by vasile-coste** [comment]
> It does remember them. If you click `info` next to the app(s) you have installed, then click on `patch` and it'll allow you to run an update.
> 
> I would like an option to save patch selections if you need to remove the patched version for some reason.

Yes that works if i want to repatch the same version of app with updated patches, but it resets if i select a newer version of it

**Comment by fallingcats** [comment]
> It does remember them. If you click `info` next to the app(s) you have installed, then click on `patch` and it'll allow you to run an update.

It does not in my case: I patched an APK file from storage, then installed as user.
Neither the original APK nor the resulting installed app with package name "app.revanced.android.youtube" are shown. When selecting the same file again no patches are preselected.
