### ISSUE TITLE
feat: automatically detect root

### ISSUE THREAD

**Issue by OxrxL** [revanced/revanced-manager#322]
### Type

Functionality

### Issue

At the current time many users encountered problems with their patched version of YouTube, due to missing microG patch.

### Feature

Add a routine to automatically detect root access...and subsequently unflag (or vice versa) microG patch.

### Motivation

To avoid users misunderstanding about their platform target (intended as root or non-root).

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by OxrxL** [comment]
Less interactions = Less trouble

**Comment by Aunali321** [comment]
We had root detection before. But using it to include or exclude microg is not valid. Manager is app agnostic. It does not care what apps or patches you select. If we do if(root) {//include microg.} It will make it specific to yt and ytm because other apps don't have microg patch.
