### ISSUE TITLE
feat: make it more clear what patches require root.

### ISSUE THREAD

**Issue by JaydenDev** [revanced/revanced-manager#323]
### Type

Functionality

### Issue

So basically, I tried to use Youtube Revanced (manager) to patch my YouTube installation. However, every patch that I have tried requires root. 

### Feature

add a label for what patches require root

### Motivation

It's frustrating picking and choosing every patch finding out what requires root.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
We cannot. Needs to be supported by patcher.
