### ISSUE TITLE
feat: Please Add Fullscreen Brightness Remember Patch

### ISSUE THREAD

**Issue by lillian3yay** [revanced/revanced-manager#324]
### Type

Functionality

### Issue

It would be great if we don't need to adjust screen brightness every time on restarting the YouTube Revanced,
So it's a request to add patch for remembering brightness on full-screen.
Thankyou

### Feature

Fullscreen Brightness Remembering Patch

### Motivation

Remeber Fullscreen Brightness Level 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Wrong repository. Open the issue on revanced-patches.
