### ISSUE TITLE
feat: View & Select Patcher Version

### ISSUE THREAD

**Issue by hibikidesuuu** [revanced/revanced-manager#325]
### Type

Functionality

### Issue

While the patcher can be update by pulling down and refreshing it (apparently). It would be nice if we could actually see what the patch version is currently used on the manager. Idk about others but having this "~1d ago" is kinda vague for me imho 

### Feature

Put the patcher version on like
Patcher: 5.1.1(should probably a dropdown list where when you tap, you could see a list of patcher versions)
And there should be a button to check if there are any updates or maybe in the settings there should be an option to [automatically check for updates for patcher when you open the manager and updates automatically]. And if you or the manager checks for updates, there should be a toast notification that says if it has any updates or not or has been updated.

The select patcher version would be a nice addition. if ever there were a case where "this certain version has some issues in it", giving us the option to select/downgrade the patcher version would probably help some users with issues to the current patcher version they're using to some extent. (probably idk)

### Motivation

QoL ig? Manually refreshing could sometimes be a bit cumbersome. Because you don't actually know if it's updated or not (for me idk about others).  Having to see which patcher version you're on should be of great help.

### Additional context

checking for updates for the manager should be moved in the settings imho.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Canny1913** [comment]
You cannot change the patcher version in-app, you need to downgrade or upgrade the manager.

**Comment by hibikidesuuu** [comment]
> You cannot change the patcher version in-app, you need to downgrade or upgrade the manager.

That's why i labeled this as feature request.

**Comment by Aunali321** [comment]
> That's why i labeled this as feature request.

Not possible.

**Comment by Canny1913** [comment]
> > That's why i labeled this as feature request.
> 
> Not possible.

Unless you know, c o r e l i b

**Comment by Aunali321** [comment]
> Unless you know, c o r e l i b
I fully support that idea.
