### ISSUE TITLE
feat: Revanced Patch update availability notification

### ISSUE THREAD

**Issue by Michael1999US** [revanced/revanced-manager#326]
### Type

Functionality

### Issue

It's hard to tell right now if there are any new available patches in the revanced manager.
And if there are any, we don't know what has changed

### Feature

Revanced Patch update availability notification provides users visual feedback that there a new/available update to the patch compared to their previously patched app.

### Motivation

It is necessary for the revanced team to implement this new feature. This gives users sense of caring. We can feel and see that Revanced team is doing something to the patches and the app itself.

Secondly the more users test new patches the more issue we can catch early on. Thats why you also should encourage devs to add beta/dev version so users can test them out.

### Additional context

Revanced Patch update availability notification should also show change log.
IE: New features, Fixes, security fixes. 
.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
It already shows that. Checked installed section and expand patched apps. if you have any updates it will show in changelog.
