### ISSUE TITLE
feat: enable resource patching for twitter

### ISSUE THREAD

**Issue by ganchair** [revanced/revanced-manager#327]
### Type

Functionality

### Issue

A new patch for Twitter requires resource patching (https://github.com/revanced/revanced-patches/commit/127c8e54e54709c2716029044ae337ad53daafad)

![photo_2022-09-28_14-52-11](https://user-images.githubusercontent.com/105324789/192772341-8d16aa17-0e6e-4f25-b0e2-38b7985abb09.jpg)

### Feature

Enabling resource patching for Twitter should make the patch apply. 

### Motivation

To improve patching capabilities for Twitter.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by ganchair** [comment]
one more patch has been added that requires this (https://github.com/revanced/revanced-patches/commit/a16575b984354138b9ab175307be8d15de60b6a6)

![photo_2022-09-29_23-48-35](https://user-images.githubusercontent.com/105324789/193139084-b224e595-bbca-4822-9b51-3bcece0551fb.jpg)

**Comment by Ushie** [comment]
Done in 5418c36716a7f28fd12b809f316ad28d0abdfccd, v0.0.27 will be available shortly
