### ISSUE TITLE
Add revanced-patches version

### ISSUE THREAD

**Issue by aleks01100001** [revanced/revanced-manager#328]
### Type

Cosmetic

### Issue

Add patches version in app info screen in the manager 

### Feature

We will be able to see which version we patched the aplications

### Motivation

we would be able to see which revanced-patches version we updated the app because it too is quite important and we can see if there are any new updates regarding the patches for the app

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
added in 0.0.33 in patches selector screen.
