### ISSUE TITLE
bug: make manager responsive

### ISSUE THREAD

**Issue by xafn** [ReVanced/revanced-manager#333]
### Type

Cosmetic

### Bug description

With how it is currently, the text in cards is hardcoded to shorten after a set amount of characters. This should be changed to shorten based on the available width. 

Also, if there is no space for buttons on the same line, replace them with an icon or put in on a newline.

This is how the dashboard looks right now with largest font and largest display size. Everything gets clipped.
![image](https://user-images.githubusercontent.com/47723802/193204194-7a91c021-7bdc-406a-b638-22ffe09b9745.png)

### Steps to reproduce

1. Increase font size/display size
2. Look at Dashboard or Patch selection

### Android version

any

### Manager version

0.0.26

### Target package name

why is this required

### Target package version.

why is this required

### Installation type

Non-root

### Patches selected.

why is this required

### Device logs (exported using Manager settings).

```shell
guhhh
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Your fault for using manager designed for a modern smartphone on a 2 inch device.

**Comment by afnzmn** [comment]
The reason I opened this issue was because of[ this reddit post](https://www.reddit.com/r/revancedapp/comments/xpdilc/larger_font_support_needed_im_unable_to_use_a/). It's for accessibility.

**Comment by afnzmn** [comment]
Also, this issue still occurs to people with regular phones. One person in the Discord had the Info buttons going off the card with a OnePlus 6T.

**Comment by BrentBoyMeBob** [comment]
I'll look into it real quick. This can probably be handled with [flutter_screenutil](https://pub.dev/packages/flutter_screenutil).

**Comment by ILoveOpenSourceApplications** [comment]
Does #1017 fix this @TheAabedKhan?

**Comment by Ushie** [comment]
no, it only improves certain text, something like #361 would be necessary to resolve UI components going out of frame etc
