### ISSUE TITLE
feat: Rename package name for apps like Twitter 

### ISSUE THREAD

**Issue by sanjeevstunner** [revanced/revanced-manager#335]
### Type

Functionality

### Issue

The current implementation doesn't rename the package name of Twitter app (observed in my usage, IDK about other apps), means that when my phone is at rest, the app gets auto updated, and is getting crashed everytime I open the app. 

### Feature

Renaming the package name with app.revanced prefix means, it gets treated as a separate app, hence it wont get auto update or smth 

### Motivation

Better usability of the MOD

### Additional context

IDK if this is the only way to do this, or even a working way. Maybe you can inject some code, so the app gets excluded from the update list, or smth like that. I'm really not sure about the possibilities of this working, but something I think can improve the overall usability of the app 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [x] The issue is related solely to the ReVanced Manager

**Comment by mexon86** [comment]
and if it install as seperated app we dont need to delete first app when installing and download apk and patch every time we can still have updated original app ready to patch

**Comment by sanjeevstunner** [comment]
> and if it install as seperated app we dont need to delete first app when installing and download apk and patch every time we can still have updated original app ready to patch

Just like the YouTube app.

**Comment by Aunali321** [comment]
Out of scope for manager.

**Comment by sanjeevstunner** [comment]
Could you please explain the issue better, so maybe I, or someone, can help
