### ISSUE TITLE
feat: Check for apk version mismatches

### ISSUE THREAD

**Issue by reisxd** [revanced/revanced-manager#338]
### Type

Functionality

### Issue

Currently, if you install as root and have version mismatch between the app and the APK you patched, the app will crash.

### Feature

Maybe check the patched apps version and the installed version(?)

### Motivation

This'll avoid issues in the future like this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by reisxd** [comment]
Looks like manager only allows to patched already installed apps as root, which makes this issue invalid. But still, you have to install a full apk, which isn't a good solution, users should be able to patch full apks and install them as root.

**Comment by Aunali321** [comment]
> But still, you have to install a full apk, which isn't a good solution, users should be able to patch full apks and install them as root.

@reisxd can you do this?

**Comment by reisxd** [comment]
> > But still, you have to install a full apk, which isn't a good solution, users should be able to patch full apks and install them as root.
> 
> @reisxd can you do this?
> 

sadly i dont talk in flutter/dart
