### ISSUE TITLE
feat: Remove install as root/ normal install button if they are unavailable

### ISSUE THREAD

**Issue by Iaotle** [revanced/revanced-manager#339]
### Type

Cosmetic

### Issue

both buttons are active, but you can't use one of them when installing from apk, and can't use the other when installing certain patches.

### Feature

just hide the buttons

### Motivation

having buttons that don't work is kinda bad

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
If you select microg patch, install as root is not shown.

**Comment by Iaotle** [comment]
Buttons still show up when installing from APK and both are unavailable with certain patches, so this is still an issue unless you fixed it after I posted this.
