### ISSUE TITLE
bug: Using custom sources is not working.

### ISSUE THREAD

**Issue by E85Addict** [revanced/revanced-manager#340]
### Type

Error while running the manager

### Bug description

I tried using my personal patches, as I have some custom branding I like to use and it breaks the app. I believe since switching to HTTP/2 it broke access to GH as no apps are select-able or able to be picked and using one from storage doesn't work. Using version v0.0.21 before the change works with no issue.

### Steps to reproduce

Step 1. Install Latest manager and accept all prompts on initial launch.
Step 2. Go to the settings and input the custom source in my case E85Addict/revanced-patches
Step 3. Close the app and open it to refresh the changes.
Step 4. Try and select a app that's preinstalled and you will see an empty list.
Step 5. Select a storage app and no patches will populate the list.

### Android version

Android 12 and 13 where tested. Arm64-v8a

### Manager version

Every version after v0.0.21 is broken while version v0.0.21 works.

### Target package name

YouTube, YouTube Music, TikTok

### Target package version.

The recommended versions of each app.

### Installation type

Root

### Patches selected.

Non came up to select, both root and non root.

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
09-24 01:51:53.094 11422 11422 D OplusInputMethodUtil: init sDebug to false, init sDebugIme to false, init ALWAYS_ON to false
09-24 01:51:53.094 11422 11422 D OplusInputMethodUtil: updateDebugToClass InputMethodManager.DEBUG = false
09-24 01:51:53.094 11422 11422 D OplusInputMethodUtil: updateDebugToClass ImeFocusController.DEBUG = false
09-24 01:51:53.094 11422 11422 D OplusInputMethodUtil: updateDebugToClass BaseInputConnection.DEBUG = false
09-24 01:51:53.215 11422 11422 V ZoomWindowDecorView: setLastReportedMergedConfiguration mZoomDisplayHeight: 3216 getDecorView.96762620
09-24 01:51:53.233 11422 11422 I Quality : Skipped: false 1 cost 17.6576 refreshRate 16662098 bit true processName app.revanced.manager.flutter
09-24 01:52:02.621 11422 11422 D OplusInputMethodManagerInternal: get inputMethodManager extension: com.android.internal.view.IInputMethodManager$Stub$Proxy@16d2d7b
09-24 01:52:20.045 12367 12367 D OplusInputMethodUtil: init sDebug to false, init sDebugIme to false, init ALWAYS_ON to false
09-24 01:52:20.045 12367 12367 D OplusInputMethodUtil: updateDebugToClass InputMethodManager.DEBUG = false
09-24 01:52:20.045 12367 12367 D OplusInputMethodUtil: updateDebugToClass ImeFocusController.DEBUG = false
09-24 01:52:20.045 12367 12367 D OplusInputMethodUtil: updateDebugToClass BaseInputConnection.DEBUG = false
09-24 01:52:20.096 12367 12367 V ZoomWindowDecorView: setLastReportedMergedConfiguration mZoomDisplayHeight: 3216 getDecorView.249962458
09-24 01:52:22.570 12367 12367 D OplusInputMethodManagerInternal: get inputMethodManager extension: com.android.internal.view.IInputMethodManager$Stub$Proxy@ec70d5a
09-24 01:52:32.817 12367 13045 D ActivityThread: do gfx trim 40
--------- beginning of main
09-24 01:56:44.353 12367 14115 D ColorModeChangeItem: preExecute mColorMode=0,token=android.os.BinderProxy@d12a447
09-24 01:56:44.376 12367 12367 D BufferQueueConsumer: [](id:304f00000002,api:0,p:-1,c:12367) connect: controlledByApp=false
09-24 01:56:44.377 12367 13051 D BufferQueueProducer: [VRI[MainActivity]#2(BLAST Consumer)2](id:304f00000002,api:1,p:12367,c:12367) connect: api=1 producerControlledByApp=true
09-24 01:56:44.378 12367 12367 D BufferQueueConsumer: [](id:304f00000003,api:0,p:-1,c:12367) connect: controlledByApp=false
09-24 01:56:44.379 12367 13057 D BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#3(BLAST Consumer)3](id:304f00000003,api:1,p:12367,c:12367) connect: api=1 producerControlledByApp=true
09-24 01:56:44.380 12367 12367 E SurfaceSyncer: Failed to find sync for id=0
09-24 01:56:44.380 12367 12367 E SurfaceSyncer: Failed to find sync for id=1
09-24 01:56:44.380 12367 12367 E SurfaceSyncer: Failed to find sync for id=2
09-24 01:56:44.388 12367 14115 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff]
09-24 01:56:44.389 12367 12367 D VRI[MainActivity]: onFocusEvent true
09-24 01:56:44.396 12367 13045 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff]
09-24 01:56:45.361 12367 12367 V AutofillManager: requestHideFillUi(null): anchor = null
09-24 01:56:45.362 12367 12367 D OplusSystemUINavigationGesture: [GESTURE_BUTTON] swipe from 1
09-24 01:56:45.362 12367 12367 D OplusSystemUINavigationGesture: [GESTURE_BUTTON] Hit Gesture Region !
09-24 01:56:45.440 12367 12367 D Activity: dispatchKeyEvent to app.revanced.manager.flutter.MainActivity@26b64b7 will call onBackPressed
09-24 01:56:45.855 12367 12367 V AutofillManager: requestHideFillUi(null): anchor = null
09-24 01:56:46.485 12367 12367 V AutofillManager: requestHideFillUi(null): anchor = null
09-24 01:56:46.486 12367 12367 D OplusSystemUINavigationGesture: [GESTURE_BUTTON] swipe from 1
09-24 01:56:46.486 12367 12367 D OplusSystemUINavigationGesture: [GESTURE_BUTTON] Hit Gesture Region !
09-24 01:56:46.560 12367 12367 D Activity: dispatchKeyEvent to app.revanced.manager.flutter.MainActivity@26b64b7 will call onBackPressed
09-24 01:56:46.866 12367 12367 V AutofillManager: requestHideFillUi(null): anchor = null
09-24 01:56:47.550 12367 12367 V AutofillManager: requestHideFillUi(null): anchor = null
09-24 01:56:48.453 12367 12367 V AutofillManager: requestHideFillUi(null): anchor = null
09-24 01:56:49.188 12367 12367 V AutofillManager: requestHideFillUi(null): anchor = null
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Not able to reach this point.
```

### Screenshots or videos

https://cdn.discordapp.com/attachments/1022943028559757379/1023155028988538940/Record_2022-09-24-01-51-43.mp4

https://cdn.discordapp.com/attachments/1022943028559757379/1023157354398748712/Record_2022-09-24-02-00-34.mp4

### Solution

Revert to HTTP/1 or add fallback for it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by cvphat4796** [comment]
Confirm that still happening in v0.0.28

**Comment by cvphat4796** [comment]
An update for this bug
I see the manager can not download patches json file from github custom source with 403 error :(
I suggest we allow user select patches json file and patches jar file if the manager can not download these files.
I also pushed the code with my idea in [my repository](https://github.com/cvphat/revanced-manager). If Revanced Manager Team happies with my idea I will create a pull request.

**Comment by E85Addict** [comment]
This is now fixed with https://github.com/revanced/revanced-manager/commit/78428f6bd3876162a1a70be5ae570d6278156edd

Just needs to be built in the next release.
