### ISSUE TITLE
Downloading Feature

### ISSUE THREAD

**Issue by Freyus** [revanced/revanced-manager#342]
### Type

Functionality

### Issue

There is no download feature for the patch of Youtube Music Vanced yet. I think the majority of the users would really appreciate the downloading feature for the Youtube Music specifically.

### Feature

It would be very appreciated if in the final product later on, for the patch of Youtube Music to also have a download feature just like the regular Youtube Vanced version. Most people (including myself) would love to be able to hear songs without using wifi or internet data, especially while being out. It can also help to lessen the consumption of the battery from the use of them.

### Motivation

Because it can reduce the amount of internet data that is used when going out, a lot of the userbase would really appreciate such a feature, etc.

### Additional context

-

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by its0x08** [comment]
The same feature would be great for Spotify and/or YouTube
At the moment it doesn't work, at least for me.

**Comment by Aunali321** [comment]
Wrong repository. Open the issue on revanced-patches if it isn't already suggested.
