### ISSUE TITLE
Custom speed like 1.4, 1.5, 1.6, 1.7 etc feat: <title>

### ISSUE THREAD

**Issue by pedrynh** [revanced/revanced-manager#344]
### Type

Functionality

### Issue

There's no problem just the future request actually I mean it's great I can't say shit about it you know thank God revanced exist

I mean thank you guys for grammers in you guys will know how to to do this kind of stuff a kiss on the dick or something I mean I really appreciate like what do you want bitches money you deserve it

### Feature

It's in the title bro

### Motivation

Because the new pipe we have this feature and also the YouTube at desktop we also have this feature so and there is my personal reason that I simply love it and I use it personally the 1.35 and 1.70 and also sometimes the 0.70 so there's that you know

### Additional context

Nah I guess I have said everything that is it

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Wrong repository. Open the issue on revanced-patches if it isn't already suggested.
