### ISSUE TITLE
bug: Patch search quite broken

### ISSUE THREAD

**Issue by PalmDevs** [revanced/revanced-manager#347]
### Type

Error while running the manager

### Bug description

Patch search only searches for their IDs *(eg. hide-cast-button, microg-support)*, but not their listed names *(eg. Hide Cast Button, MicroG Support)*.

### Steps to reproduce

1. Launch Manager
2. Go to the Patcher tab
3. Select an app to patch
4. Go into the patch selector screen
5. Search using the listed name for a specific patch
6. Observe the queries
7. Now search with patch IDs
8. Observe the differences

### Android version

12.1 (12L)

### Manager version

0.0.28

### Target package name

unrelated

### Target package version.

unrelated

### Installation type

Root

### Patches selected.

unrelated

### Device logs (exported using Manager settings).

```shell
unrelated
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
unrelated
```

### Screenshots or videos

![20221003_222318-COLLAGE](https://user-images.githubusercontent.com/67689562/193615372-7b80a465-29f1-4c96-b539-fbb17acb6e78.jpg)
![20221003_222303-COLLAGE](https://user-images.githubusercontent.com/67689562/193615386-4488c17e-ee79-4139-ae0a-e7849bb2ed36.jpg)

### Solution

None for now.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by j4k0xb** [comment]
it only has a name (what you refer to id), the displayed one is just formatted a bit differently:
https://github.com/revanced/revanced-manager/blob/d8df377427f2be90b52a8833f8e61709a4b65e8c/lib/models/patch.dart#L28-L35

should be pretty easy to fix by adding `.replaceAll(' ', '-')` here:
https://github.com/revanced/revanced-manager/blob/d8df377427f2be90b52a8833f8e61709a4b65e8c/lib/ui/views/patches_selector/patches_selector_viewmodel.dart#L76-L78
