### ISSUE TITLE
bug: ReVanced Manager still very buggy

### ISSUE THREAD

**Issue by kenethc** [revanced/revanced-manager#350]
### Type

Other

### Bug description

Manager is very buggy. Any version for instance.

What patches and works on 1 version breaks in the next version. Though patch versions itself have no updates.

### Steps to reproduce

What works on 1 phone doesn't work on another 

### Android version

12

### Manager version

v28

### Target package name

YouTube
Reddit
Twitter

### Target package version.

.... 

### Installation type

Non-root

### Patches selected.

All for Twitter and Reddit

All for YouTube except:
Video Buffer
Video Speed
Custom Branding (ReVanced)
MicroG support
Debugging

### Device logs (exported using Manager settings).

```shell
Too much to log so skipping.

Probably best the Dev's test out the manager and patching thoroughly instead of aimlessly release new updates to the Manager.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Patches updates almost everyday. just a skill issue.
