### ISSUE TITLE
bug: unable to patch, gets aborted with error log

### ISSUE THREAD

**Issue by subraths** [revanced/revanced-manager#352]
### Type

Error while running the manager

### Bug description

Tried patching, and get aborted with error log, I've tried with just video ads patch and get aborted with and same with sponsors block, and general but succeeded with premium heading patch

### Steps to reproduce

1. Download YouTube 17.36.37
2. Latest revanced manager
3. Choose video ads patch 
4. Gets aborted with error log

### Android version

Android 12

### Manager version

Manager 0.0.28

### Target package name

YouTube 17.36.37

### Target package version.

17.36.37

### Installation type

Root

### Patches selected.

Video ads,sponsors block, general ads patch

### Device logs (exported using Manager settings).

```shell
No device log
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applying all patches
Executing 'integrations' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'locale-config-fix' of type: resource
Executing 'resource-mapping' of type: resource
Executing 'settings-resource-patch' of type: resource
Executing 'settings' of type: bytecode
Executing 'video-ads' of type: bytecode
[success] video-ads
Skipping 'settings' because it has already been applied
[success] settings
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~0NcyjCXu05lAweWhzpkYng==/app.revanced.manager.flutter-IUP0pmo5ZEr_TCLMYxti8A==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NATBHX/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NATBHX/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:375)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629)
	at app.revanced.patcher.Patcher.save(Patcher.kt:158)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-19(MainActivity.kt:215)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$aEBH7QyMEVbzs_zgD8iozv3hwbI(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:920)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~0NcyjCXu05lAweWhzpkYng==/app.revanced.manager.flutter-IUP0pmo5ZEr_TCLMYxti8A==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NATBHX/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NATBHX/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:371)
	... 6 more
```

### Screenshots or videos

![Uploading Screenshot_20221004-220822_ReVanced Manager.png…]()
![Screenshot_20221004-220815_ReVanced Manager](https://user-images.githubusercontent.com/46223342/193876991-ada1195f-cfb7-409c-b2ba-182a2e7e75c4.png)

![Screenshot_20221004-220819_ReVanced Manager](https://user-images.githubusercontent.com/46223342/193876990-ca72bec8-4149-44db-9426-5fcc8fb4e22e.png)

### Solution

First apply the single patch which works(in my case it is 'Premium heading patch') and then apply more patches on top of it
1. Go to dashboard in Revanced Manager
2. Select Installed
3. Choose Youtube > Tap on info > patch > add more patches

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by subraths** [comment]
For now this could be my device only, and since I had a work around for the bug, and updated the solution above, I'm closing the issue

**Comment by Hebgbs** [comment]
_I actually get a bug too._ It has to do with MicroG support. I have the APK as provided by Vanced Manager installed, and trying to use MicroG support for YouTube aborts the patching process.
