### ISSUE TITLE
Some customisation and download functionalities.

### ISSUE THREAD

**Issue by IshuPrabhakar** [revanced/revanced-manager#353]
### Type

Functionality

### There are lots of features I want🙃.

- It looks odd to me, previously when youtube vanced was not banned then the app icon and app name was same as original youtube. That was cool but now it has changed although I know it is basically another version of YouTube which we call YouTube ReVanced now, it basically belongs to ReVanced family so the name is appropriate. But having an option to rename and change icon will be a plus point.

- Missing download functionalities although YouTube yanced never had funtionalty to download videos directly. But after applying patches I noticed there is an  icon to download videos but when I click on it shows a dialog Box saying "org.schabi.newpipe" is not installed on my non rooted Android 11 device. Basically what I is that this application should be integrated with the YouTube ReVanced patches.  Then on one click only I can download videos directly.
- - Every time when I need to download some videos always I have to copy Link and paste it to my browser to download videos but this is frustrating sometimes.
- - There is a application called snaptube which has same feature which I want. 

### Feature

- To download videos there should be an icon near the forward icon when we watch any video. The a dialog box should be appear whether you want to download video or audio with variable download quality option.
- - Like for audio -> 128kbps, 192 kbps, 320kbps in case of MP3 format, ACC,  mp4a etc.
- - Incase of video option should be like 240p, 360p, 480p, 720p, 1080p etc.
- All this should also work on non rooted devices also.

- There should be an option to change application name and icon for more customisation.

### Motivation

Every time when I need to download some videos always I have to copy Link and paste it to my browser to download videos but this is frustrating sometimes.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
>   But having an option to rename and change icon will be a plus point.
Will be possible after implementation of patcher options.

>     * Missing download functionalities although YouTube yanced never had funtionalty to download videos directly. But after applying patches I noticed there is an  icon to download videos but when I click on it shows a dialog Box saying "org.schabi.newpipe" is not installed on my non rooted Android 11 device. Basically what I is that this application should be integrated with the YouTube ReVanced patches.  Then on one click only I can download videos directly.

You need to download newpipe or you can use any other downloader by changing package name in settings.

> 
>     * To download videos there should be an icon near the forward icon when we watch any video. The a dialog box should be appear whether you want to download video or audio with variable download quality option.
> 
>     * * Like for audio -> 128kbps, 192 kbps, 320kbps in case of MP3 format, ACC,  mp4a etc.
> 
>     * * Incase of video option should be like 240p, 360p, 480p, 720p, 1080p etc.
> 
>     * All this should also work on non rooted devices also.
> 
>     * There should be an option to change application name and icon for more customisation.

Not the job of manager. open an issue on revanced-patches

> Every time when I need to download some videos always I have to copy Link and paste it to my browser to download videos but this is frustrating sometimes.

Include downloads patch and install newpipe or any other downloader and change package name to that in revanced yt settings.
