### ISSUE TITLE
feat: simple and advanced patching

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#360]
### Type

Functionality

### Issue

Currently the user is required to use a complex and non intuitive way to patch applications.

### Feature

Initially on the first launch of the manager, allow to set the manager up in simple or advanced mode:

- Simple mode will only require to select the application and start patching and installing the application. A setting in the settings can be then configured to make it install or mount, while installation should be default.

- Advanced installation mode should be what currently is available.

### Motivation

This feature will allow users with low experience with our toolings to seamlessly use the manager without the hassle to chose the correct application, patches and way of installation, but instead just the application to patch and nothing else.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [x] The issue is related solely to the ReVanced Manager

**Comment by PandoraHayami** [comment]
They would work something like presets, right?

**Comment by MaXfAa** [comment]
Oh it seems that the "feature-request" label is missing...

**Comment by erik9012** [comment]
Wouldnt it be useful to wait for bundle apk support before this get integrated? Users who are unable to select patches are probably not used to download full apks from apkmirror either.

**Comment by rootback123** [comment]
If it's to make it easier for users to put split app support it's much more needed for now.

**Comment by Ushie** [comment]
Resolved by the upcoming design
