### ISSUE TITLE
Youtube revanced shows nothing

### ISSUE THREAD

**Issue by jonnykni** [revanced/revanced-manager#362]
### Type

Other

### Bug description

Youtube revanced get patched and downloads fine but when it launches nothing shows.

### Steps to reproduce

Just any any or all pathches for youtube. Youtube version is 17.36.37.

### Android version

12

### Manager version

0.0.29

### Target package name

Youtube

### Target package version.

17.36.37

### Installation type

Non-root

### Patches selected.

I tried with all and selected ones, but still the same result.

### Device logs (exported using Manager settings).

```shell
I can't find it
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
You need full apk from apkmirror not bundle(120mb+)
