### ISSUE TITLE
feat: export and import chosen patches

### ISSUE THREAD

**Issue by flame-0** [revanced/revanced-manager#365]
### Type

Functionality

### Issue

Currently, user cannot export, import, and share of their chosen patches.

### Feature

Ability to export, copy, or share, and import the chosen patches in JSON format. And, add an ability to auto-paste the copied JSON-formatted chosen patches.

_Note: In ability to auto-paste, ReVanced Manager must have the settings to opt out in the settings._

### Motivation

With this feature and alternatively for remember chosen patches, user can save their chosen patches in the future if something bad happens.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by SodaWithoutSparkles** [comment]
This is very needed as the patcher does not remember the patches selected when repatching. If a patch was updated then we need to repatch, but we will have to select the patches again. This is very annoying, considering it knows what I have selected last time but dont tick them for you.

**Comment by geominorai** [comment]
It may be helpful to store not only the selected patches but also the ones available at the time of backup, in the event they are removed or deprecated, and possibly as a way to highlight new patches that did not exist at the time of backup.
