### ISSUE TITLE
Root Method

### ISSUE THREAD

**Issue by tryigit** [revanced/revanced-manager#369]
### Type

Functionality

### Issue

I try to install with root, applications are kept in a directory and when the device is restarted, the applications return to their old version. this is a big problem. It is dangerous for the app to hold anything in the root partition of the device.
Im in favor of the root install method only install.

### Feature

Root Installer

### Motivation

Short and concise application

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

![Screenshot_2022-10-08-23-32-21-437_ru.zdevs.zarchiver-edit.jpg](https://user-images.githubusercontent.com/40565628/194726850-ab1e1e71-0bab-4fe4-9355-5785a026ec42.jpg)

**Comment by Relected** [comment]
why would you make a separate manager just for root install?

**Comment by tryigit** [comment]
> why would you make a separate manager just for root install?

I did not understand what you wanted to say. I just think the root method is unnecessary. Having my signature verification turned off is a much better option or just clean install like old vanced manager.

**Comment by Ushie** [comment]
> > why would you make a separate manager just for root install?
> 
> I did not understand what you wanted to say. I just think the root method is unnecessary. Having my signature verification turned off is a much better option or just clean install like old vanced manager.

The root installation with ReVanced Manager follows the same method as Vanced Manager

**Comment by Ushie** [comment]
However we will probably migrate to Magisk Modules as the default installation method for root, and keep the previous method (and same as vanced)  as a Legacy option in settings

**Comment by tryigit** [comment]
> > > why would you make a separate manager just for root install?
> > 
> > I did not understand what you wanted to say. I just think the root method is unnecessary. Having my signature verification turned off is a much better option or just clean install like old vanced manager.
> 
> The root installation with ReVanced Manager follows the same method as Vanced Manager 

No, It saves APK files in the root directory. Even if I update the application through the play store and patch it again, when I restart the phone, it returns to the version in the root directory.

Root installation method is a major problem. It is much more logical to create an apk and install it without Microg. This kind of nonsense is irrelevant as long as signature verification is turned off.

It just makes the app overly complex.

**Comment by Aunali321** [comment]
> Having my signature verification turned off is a much better option or just clean install like old vanced manager.
Do you even know how much security risk is that?

**Comment by Relected** [comment]
>Root installation method is a major problem. It is much more logical to create an apk and install it without Microg. This kind of nonsense is irrelevant as long as signature verification is turned off.

1. there are good reasons to use root variant (a lot of downloaded videos, saving space, not needing to relogin every time you change password, no need for microg)

2. revanced yt is a mod of the original yt, you need the app to be signed to work properly otherwise google will detect that you are using a modded version of their official client and prevent you from watching anything (hence why microg is needed for non-root)

**Comment by tryigit** [comment]
> > Having my signature verification turned off is a much better option or just clean install like old vanced manager.
> Do you even know how much security risk is that?
> 
> 

Are you aware that we are talking about root?
Anyway, root permission means that an app can do anything while rebooting the device. Unnecessary detail.

**Comment by Aunali321** [comment]
Manager is open source, if you are unhappy with a feature simple fork it suit it according to your needs. Disabling signature verification is a huge security and privacy risk. 

>  Anyway, root permission means that an app can do anything while rebooting the device. Unnecessary detail.

That's just how android works.

**Comment by tryigit** [comment]
> >Root installation method is a major problem. It is much more logical to create an apk and install it without Microg. This kind of nonsense is irrelevant as long as signature verification is turned off.
> 
> 1. there are good reasons to use root variant (a lot of downloaded videos, saving space, not needing to relogin every time you change password, no need for microg)
> 
> 2. revanced yt is a mod of the original yt, you need the app to be signed to work properly otherwise google will detect that you are using a modded version of their official client and prevent you from watching anything (hence why microg is needed for non-root)

You don't understand what I'm talking about.
I'm already advocating the root method. The issue I'm complaining about here is that the application behaves like a module, not like vanced manager.
The problem here is probably constantly generating randomly signed applications. But the people who take root should turn off signature verification.

**Comment by tryigit** [comment]
> Manager is open source, if you are unhappy with a feature simple fork it suit it according to your needs. Disabling signature verification is a huge security and privacy risk. 
> 
> >  Anyway, root permission means that an app can do anything while rebooting the device. Unnecessary detail.
> 
> That's just how android works.

The only thing I want is to be able to install and open the application I created with signature verification turned off. This is true freedom.
It's ridiculous to constantly clean application files in the root directory when I root install.

If that sounds right to you, you can continue like this.
If I need to clarify for the last time, the application I installed is the application I installed myself, even if I turned off the signature verification. So there is no point in talking about security here.

**Comment by Canny1913** [comment]
If you want something to work the way you want it, then fork it and do it yourself.

**Comment by tryigit** [comment]
> If you want something to work the way you want it, then fork it and do it yourself.

I just opened the topic as a feature suggestion.
The main problem that many people with whom I share the application complain about is the root method.

I dont know why the topic was moved to the problem section.

**Comment by tryigit** [comment]
![Screenshot_2022-10-08-23-41-04-519_app.revanced.manager.flutter.jpg](https://user-images.githubusercontent.com/40565628/194727097-adc90214-39d1-4451-97e3-4188f80c9c71.jpg)![IMG_20221008_234153.jpg](https://user-images.githubusercontent.com/40565628/194727102-add1de95-8618-4896-8dd6-2bf416110be8.jpg)
i solve my problem by removing it from the list for now and it works great. I'll wait for the autoloading of the app on device reboot event to be removed to avoid conflicts.

**Comment by SeregaKR** [comment]
I tried using Manager to patch the Youtube app. It gives me the message that root is required. Any way to do it without root? Or at least where can I read about it in more detail?
If it can be done only with root, please add the note about it

**Comment by SeregaKR** [comment]
> > I tried using Manager to patch the Youtube app. It gives me the message that root is required. Any way to do it without root? Or at least where can I read about it in more detail?
> > If it can be done only with root, please add the note about it
> 
> Select the microg option and you can install it without root.

thank you for the tip
