### ISSUE TITLE
feat: Make it clear to the user that some patches can be disabled later

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-manager#373]
### Type

Functionality

### Issue

Some patches seems that it would disrupt the app too much and the user does not want to incorporate it. But it turns out it is needed then they want it later. E.g. disable auto caption, popup panels, etc.

### Feature

Make it clear to user that the patch can be enabled/disabled during runtime so they are not afraid to include it during patch-time

### Motivation

The current description provides too little infomation for a educated guess on if the patch supports settings. It also does not provide a recommendation for what should be included. As patching takes way longer time, telling the user that the patch can be disabled during runtime can allow the user to try out new patches without fear, knowing that they could disable it later

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Not the job of the manager. Patch description are from revanced-patches.

**Comment by SodaWithoutSparkles** [comment]
Or detect from the patches.json to see if it supports settings. If no, change the text colour to something else. Or if yes, add a icon (maybe a gear icon?) to show that it supports settings. This would be way easier and faster comparing with asking each of the maintainer to change the patch

**Comment by SodaWithoutSparkles** [comment]
Any opinions? @oSumAtrIX

**Comment by oSumAtrIX** [comment]
Settings is a specific patch to YouTube, it doesn't make sense to design an architecture just for it for the manager.
