### ISSUE TITLE
feat: select patches before selecting an app 

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#381]
### Type

Functionality

### Issue

Currently, one has to first choose an application, then confirm if the version is compatible with the patches they want to apply, and then be able to patch the app.

### Feature

The CLI can read the patches compatibilities before having to pass an application as an option. This means it is not necessary to first test an apk for compatibility.

### Motivation

Allow users to easily figure out the version they might want to patch.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Redjard** [comment]
Shares parts with #239

**Comment by sinni800** [comment]
I don't know if this is separate, but we should be able to see all supported applications and their recommended versions without having to either install one of them or download a random APK first.

Right now, if you don't have YouTube installed, for example, there doesn't seem to be a way to check compatibility. Checking the patches first, then seeing the recommended version would be a way to solve this.

**Comment by Tillo7** [comment]
I was here just to open a feature request for that same. As I've removed the original YouTube and YT Music using ADB, I'm no longer able to see the recommend patches in the Manager. Btw, thank you so much for your contribution.

**Comment by ILoveOpenSourceApplications** [comment]
I believe this feature request is not valid anymore as currently the user is no longer required to select an app inorder to find the supported app version.

**Comment by Ushie** [comment]
Solved by the upcoming design
