### ISSUE TITLE
bug: Updating Revanced Manager clears installed/available patch update

### ISSUE THREAD

**Issue by Michael1999US** [revanced/revanced-manager#385]
### Type

Other

### Bug description

Before updating Revanced Manager I noticed that I have new available patch for Youtube. I decided to update Manager first then the Youtube app. But after updating Revanced Manager, my Patched Applications (Youtube in this case) vanished.

### Steps to reproduce

Update Vanced Manager before updating app patches.

### Android version

Android 12, OneUI 4.1.1.

### Manager version

0.0.30 to 0.0.31

### Target package name

-

### Target package version.

-

### Installation type

Non-root

### Patches selected.

-

### Device logs (exported using Manager settings).

```shell
I don't know how to make a log, but would love to hear from devs if they need them for this case
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by GabiRP** [comment]
Also happening in a rooted poco x3 nfc with android 12.

I just downloaded revanced after rooting the phone and patched youtube but it is not showing any installed patches on the dashboard

**Comment by Hedemands** [comment]
Clear your data in revanced manager app

**Comment by Fertanima** [comment]
What is the latest version of ReVanced?

**Comment by Fertanima** [comment]
My version is 17.36.47, there is no update.

**Comment by Enivex** [comment]
That is the YouTube client version number. The latest version of revanced is whatever is current in the patches repository.

**Comment by Fertanima** [comment]
This is the latest version.

**Comment by Enivex** [comment]
That's impossible to know based on the information you've provided, because 17.36.37 is the version number of the original YouTube app, not revanced.

It's the latest if you've patched it in the last 8 hours or so (again, see the patches repo)

**Comment by Fertanima** [comment]
No

**Comment by Fertanima** [comment]
After all, a notification should appear when an update arrives.

**Comment by Fertanima** [comment]
There are no updates in the manager.

**Comment by Enivex** [comment]
> After all, a notification should appear when an update arrives.

Not necessarily

**Comment by Fertanima** [comment]
The latest YouTube version is 17.39.34 and most of the patches are not compatible with it

**Comment by Fertanima** [comment]
17.36.37 is recommended.

**Comment by Enivex** [comment]
I give up. You're not reading what I'm writing, and this comment section is not a chat room.

**Comment by Fertanima** [comment]
17.36.37 version does not open.

**Comment by Canny1913** [comment]
> Now it appears, but I get the message "Update functionality not implemented yet" if I attempt to patch it
> 
> Edit: I ended up repatching from the original apk instead, and now it seems to appear correctly. That shouldn't be necessary though.

yeah update function is removed for now

**Comment by Enivex** [comment]
> > Now it appears, but I get the message "Update functionality not implemented yet" if I attempt to patch it
> > Edit: I ended up repatching from the original apk instead, and now it seems to appear correctly. That shouldn't be necessary though.
> 
> yeah update function is removed for now

That explains it
