### ISSUE TITLE
feat: Retro-compatibility / old versions builds

### ISSUE THREAD

**Issue by tt-thoma** [revanced/revanced-manager#386]
### Type

Other

### Issue

I have a really old Android 6 phone that could install the original Vanced manager, but it refused to elaborate the installation of this one.

### Feature

Just adding an "old versions" build with maybe less features but compatible with old devices

### Motivation

I'd really like to use the continuation of YouTube Vanced since I just love the app, but since the original will end soon, I won't be able to use it anymore, neither all the old phone users that can't afford a new one. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
youtube only supports android 8+ now.

**Comment by tt-thoma** [comment]
That's lame but okay

**Comment by k2helix** [comment]
Yeah it's a shame, but the YouTube version Revanced targets has a minSdk of 26. 

You can stick with Vanced while it works and when/if it stops working you could use NewPipe whose minSdk is 19 (Android 4.4) and import your subscriptions there (it won't be as comfy as regular YouTube but it's ok). Else just use YouTube in a browser with adblock (such as Firefox (Android 5+) or its forks)
