### ISSUE TITLE
Then install it.

### ISSUE THREAD

**Issue by ghost** [ReVanced/revanced-manager#393]
### Type

Functionality

### Issue

Option to delay installation after application is patched.

### Feature

If you don't want to install the app after I patch it, install it later.

### Motivation

It could be a good feature in my opinion

### Additional context

No

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
After patching and before leaving the screen, click on three dots on top right and select share apk and copy it in another directory.
