### ISSUE TITLE
bug: hide-shorts-button patch fails

### ISSUE THREAD

**Issue by Frontline11** [revanced/revanced-manager#395]
### Type

Error while running the manager

### Bug description

Patch with error in hiding Shorts, could fix it urgently

### Steps to reproduce

Patch with error in hiding Shorts, could fix it urgently

### Android version

12

### Manager version

0.0.32

### Target package name

app.revanced.android.youtube

### Target package version.

17.36.37

### Installation type

Non-root

### Patches selected.

Patch Shorts hide

### Device logs (exported using Manager settings).

```shell
Patch Shorts
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Patch Shorts
```

### Screenshots or videos

![Screenshot_20221013-195941](https://user-images.githubusercontent.com/101657790/195953400-ea0a3a09-ca77-4796-9a53-cf3de02db4f7.jpg)

### Solution

pack urgently

### Additional context

pack urgently

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
The error is irreproducible, please include a full recording that includes:

- Downloading the Manager.
- Downloading the application you want to patch
- Patching the application

**Comment by YouSummoner** [comment]
Same problem here, Realme XT Android 12.1
