### ISSUE TITLE
bug: unable to sign in

### ISSUE THREAD

**Issue by ImaMity** [revanced/revanced-manager#399]
### Type

Error at runtime

### Bug description

I have just gotten revanced, but I am unable to sign into any of my Google accounts. Whenever I click on the sign in button it just stays on the loading screen.

### Steps to reproduce

Open the  revanced youtube app. Then click on the upper right corner icon. (The account icon). Once it says to add an account or sign in, it will only load and not do anything.

### Android version

12

### Manager version

0.0.32

### Target package name

Youtube revanced

### Target package version.

17.36.37

### Installation type

Non-root

### Patches selected.

• Custom Branding
• Custom Playback Speed
• Disable Auto Captions
• Disable Auto Player Popup
Panels
• Downloads
General Ads
• MicroG Support
• Minimized Playback
· Old Quality Layout
• Premium Heading
Remember Video Quality
• Theme
• Video Ads
• Settings

### Device logs (exported using Manager settings).

```shell
I'm unable to add any log output
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Not a manager issue
