### ISSUE TITLE
feat: <Future Request - Revanced Manager to install Vanced MicroG?>

### ISSUE THREAD

**Issue by mire777** [revanced/revanced-manager#401]
### Type

Functionality

### Issue

When user patch youtube apk, patched version wont even start without Vanced MicroG, and you cant login on youtube.. Downloading it separately requires more unnecessary steps for user, and its confusing for newbee.. 

### Feature

When you select "MicroG Support", this also should install Vanced Microg automaticaly. Vanced MicroG can be downloaded directly from github, and installed when user select patch? 

### Motivation

Usability.. This require less steps for user.. 

### Additional context

I hope you will maintain Vanced Microg, and change its icon and name it to "Revanced MicroG". Thanks. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Manager is a manager. Downloading is manager's job. Manager doesn't know what patches you include by design.
