### ISSUE TITLE
bug: 0.0.33 Not opening.

### ISSUE THREAD

**Issue by Aunali321** [revanced/revanced-manager#402]
### Type

Error while running the manager

### Bug description

I am pretty sure it's caused by app not able to find google service json but can't confirm. I will resolve this as soon as I can.

### Steps to reproduce

1. Download latest release from manager.
2. Open it.

### Android version

13

### Manager version

0.0.33

### Target package name

Not relevant 

### Target package version.

Not relevant 

### Installation type

Non-root

### Patches selected.

Not relevant 

### Device logs (exported using Manager settings).

```shell
Can't get it right now
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Not relevant
```

### Screenshots or videos

Just a black screen 

### Solution

Add google-services.json to repo if that's what causing the error.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by 420aakura** [comment]
Experiencing same issue on Android 10 OnePlus 7 pro.

**Comment by MinionAttack** [comment]
I just updated the application and I am encountering the same problem.

**Comment by Nitroandaccounts** [comment]
Same

**Comment by Valiceemo** [comment]
same, on a pixel 6 pro, Android 12

**Comment by Valiceemo** [comment]
> Same with 0.0.34 on OnePlus 7, Android 11

v0.0.34 seems to have vanished now?!

**Comment by WesternGamer** [comment]
I also have the same issue on the Samsung Note 10, running Android 12.

**Comment by Vertixty** [comment]
I have the same issue on Oneplus Nord n200.

**Comment by Vertixty** [comment]
I have the same issue on Oneplus Nord n200.

**Comment by Aunali321** [comment]
Fixed in v0.0.34
