### ISSUE TITLE
material you support

### ISSUE THREAD

**Issue by Nitroandaccounts** [revanced/revanced-manager#404]
### Type

Cosmetic

### Issue

I would love to have a feature that allows material you support.

### Feature

It would make the app significantly more cosmetically appealing

### Motivation

It would make the app more visually appealing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Issue not detailed. material you is already supported. Material you requires A12 or higher.
