### ISSUE TITLE
v0.0.34 manager shows a black screen

### ISSUE THREAD

**Issue by lavanya2199** [revanced/revanced-manager#407]
### Type

Error while running the manager

### Bug description

updated from v0.0.32 to v0.0.34 using the in-manager updater. after update is complete i open the manager to a black screen. so i force stopped it and also cleared cache but the issue still persists.

### Steps to reproduce

update revanced manager in-app from v0.0.32 to v0.0.34 in Motorola edge 30

### Android version

12

### Manager version

v0.0.34

### Target package name

revanced manager 

### Target package version.

v0.0.34

### Installation type

Non-root

### Patches selected.

v0.0.34

### Device logs (exported using Manager settings).

```shell
black screen in app
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by smgchosen** [comment]
You tried to download 0.0.34 version directly in github?

**Comment by lavanya2199** [comment]
> You tried to download 0.0.34 version directly in github? 

No. I downloaded v0.0.32 from github page, then updated to 0.0.34 in-app

**Comment by smgchosen** [comment]
Uninstall manager. And try to download apk from Github and re-install it

**Comment by lavanya2199** [comment]
> Uninstall manager. And try to download apk from Github and re-install it

its works now but i wonder what caused it to go black screen when updated in-app

**Comment by smgchosen** [comment]
Because version you installed with manager is 0.0.33.

**Comment by lavanya2199** [comment]
> Because version you installed with manager is 0.0.33.

im pretty sure manager gave me the option to update to v0.0.34 so i dont know how v0.0.33 snuck in-between haha

**Comment by smgchosen** [comment]
😉

**Comment by smgchosen** [comment]
The important is you have resolved the problem 😉
