### ISSUE TITLE
bug: unable to share patched apk on latest release

### ISSUE THREAD

**Issue by PatrzKomuUfaszGb** [revanced/revanced-manager#410]
### Type

Other

### Bug description

Share APK don't work in last release 

### Steps to reproduce

After patching is not possible to share APK. In one release before that was working. Now when I tap on that is no reaction 

### Android version

A13 pixel 7 pro

### Manager version

0.0.34

### Target package name

YouTube 17.36.37

### Target package version.

17.36.37

### Installation type

Non-root

### Patches selected.

All except custom video buffer, custom speed, download

### Device logs (exported using Manager settings).

```shell
content://app.revanced.manager.flutter.shareextend.fileprovider/%252Fdata%252Fuser%252F0%252Fapp.revanced.manager.flutter%252Fcache%252Flogs%252Frevanced-manager_logcat_20221018072242849221.log
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
content://app.revanced.manager.flutter.shareextend.fileprovider/%252Fdata%252Fuser%252F0%252Fapp.revanced.manager.flutter%252Fcache%252Flogs%252Frevanced-manager_patcher_20221018072006571600.log
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by bastele7** [comment]
Same on Samsung Galaxy S22+

**Comment by Ushie** [comment]
Can you edit your message with the proper content of the logs?

**Comment by Ushie** [comment]
Reproduced and discovered the cause, will report back
