### ISSUE TITLE
feat: select recommended patches

### ISSUE THREAD

**Issue by trmdi** [revanced/revanced-manager#418]
### Type

Other

### Issue

If you've unchecked all default patches and check all patches again, it shows a warning about selecting all patches including unrecommended patches... How do you select recommended ones? There should be a button for that.

### Feature

.

### Motivation

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
It auto selected recommended patches before. it doesn't anymore. It's a bug.

**Comment by trmdi** [comment]
> It auto selected recommended patches before. it doesn't anymore. It's a bug.

On my side, it does not choose any patch by default, even after I clear the manager's data.

**Comment by Aunali321** [comment]
fixed in https://github.com/revanced/revanced-manager/commit/0c4b7c96abdc377cdbf233d1d86f59696de3df00.

**Comment by trmdi** [comment]
> fixed in https://github.com/revanced/revanced-manager/commit/0c4b7c96abdc377cdbf233d1d86f59696de3df00.

Does it just select recommend patches by default? Is there a button to select the default after the user changed it?

**Comment by Ushie** [comment]
> Does it just select recommend patches by default? Is there a button to select the default after the user changed it?

I believe that's also a function of the "Select all" button top right, it goes like this:
press 1: select recommended (skip if already recommended)
press 2: select all
press 3: unselect all

though im unsure if that behavior is still within the app, @Aunali321 ?

**Comment by trmdi** [comment]
Maybe you can add a new button here? E.g. "Default"?
![Screenshot_2022-11-12-22-12-10-728_app revanced manager flutter](https://user-images.githubusercontent.com/11857205/201480720-4de4d115-1600-451d-85c1-ac11a6259b4f.jpg)

**Comment by Aunali321** [comment]
> I believe that's also a function of the "Select all" button top right, it goes like this: press 1: select recommended (skip if already recommended) press 2: select all press 3: unselect all

no no, when you open the app it will select recommended patches by default. to select all or none you click top right button.

if you want you can implement chips for selecting recommended and all patches. @Ushie
