### ISSUE TITLE
bug: YouTube ReVanced stuck at its opening logo

### ISSUE THREAD

**Issue by shokin01** [revanced/revanced-manager#420]
### Type

Error at runtime

### Bug description

After installing the manager and patching the youtube, when i opened the ReVanced YouTube app; it just stuck at the initial stage only youtube logo appear.

### Steps to reproduce

1. Download Revanced Manager apk
2. Download Vanced MicroG
3. Installed above 
4. Download youtube apk
5. Patch it 
6. Opened Revanced Youtube but stuck at YT logo

### Android version

Android version 9.0

### Manager version

0.0.36

### Target package name

app.revanced.android.youtube

### Target package version.

17.36.37

### Installation type

Non-root

### Patches selected.

v2.83.2

### Device logs (exported using Manager settings).

```shell
can't get it
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Tillo7** [comment]
Please whitelist Revanced Manager from the Adblocker (if any), clear data and open. It worked for me :)

**Comment by Aunali321** [comment]
You are using split apk. uninstall yt. download it from apk mirror. Make sure its full apk and not a bundle. For yt recommended version is 17.36.37.
