### ISSUE TITLE
feat: Option for user to change icon and name of patched apk?

### ISSUE THREAD

**Issue by mire777** [revanced/revanced-manager#421]
### Type

Other

### Issue

After patching, "YT Music" was renamed to "Youtube Music Revanced". And this can't be changed.. I think many of us would like future to change name and icon of patched apk..

![Screenshot_20221020_221513_app revanced manager flutter](https://user-images.githubusercontent.com/3661484/197051877-d9f6ec5e-a078-4c59-ba3c-bc2f94cc712e.jpg)

### Feature

User can click on image or name, and change that, before or after apk is patched.. 

At least you should alow changing name.. 

Thanks.

### Motivation

Name and icon for apk should be optional, and package name should be same for everyone..

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
It will be possible after patch options are implemented.
