### ISSUE TITLE
feat: Clear cache after generating an APK 

### ISSUE THREAD

**Issue by UltraHDR** [revanced/revanced-manager#422]
### Type

Functionality

### Issue

Revanced Manager takes up 1GB of cache and this has to be manually cleared after creating an APK

### Feature

Clear cache after generating an APK to save about 1GB

### Motivation

Auto-clean device storage

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Already an option in manager. Check advanced settings.
