### ISSUE TITLE
Armv7 support?

### ISSUE THREAD

**Issue by Loup-Garou911XD** [revanced/revanced-manager#423]
### Type

Error while running the manager

### Bug description

Will armv7 be supported by the manager?Its unclear whether there are plans for supporting it because the the readme says might not work on some armv7 device so whether that will be fixed in future or not?

### Steps to reproduce

N/A

### Android version

Android 10

### Manager version

0.0.36

### Target package name

N/A

### Target package version.

N/A

### Installation type

Root

### Patches selected.

N/A

### Device logs (exported using Manager settings).

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Yes that is in plan. It will be supported but not so soon. Track #268 for updates.
