### ISSUE TITLE
bug: failing to install patched app, patched app still shows up in manager

### ISSUE THREAD

**Issue by flleeppyy** [revanced/revanced-manager#424]
### Type

Other

### Bug description

I patched Twitter with the "no ads" patch, then tried to install it but it failed with no reason given (which is not what im concerned about), so I went back to the dashboard to see Twitter right there, even though I never installed the patched app.

### Steps to reproduce

1. Install Twitter from Play Store
2. Use Twitter (not really necessary)
3. Open Vanced Manager
4. Patch Twitter with "Timeline Ads"
5. Install the patched Twitter
6. It fails
7. Go to dashboard
8. See Twitter

### Android version

9

### Manager version

0.0.36

### Target package name

com.twitter.android

### Target package version.

9.63.0-release-0

### Installation type

Non-root

### Patches selected.

Timeline Ads

### Device logs (exported using Manager settings).

<a href="https://haste.fleepy.tv/qusamuyotefi.yaml" target="_blank">https://haste.fleepy.tv/qusamuyotefi.yaml</a> (Way too long to put in a github issue)

### Screenshots or videos

[<img src="https://user-images.githubusercontent.com/18307183/197308767-6aef8959-57d2-42ba-9198-5d21c9027fb4.png" width="130"/> ](https://user-images.githubusercontent.com/18307183/197308767-6aef8959-57d2-42ba-9198-5d21c9027fb4.png) [<img src="https://user-images.githubusercontent.com/18307183/197308772-9ea8706e-070f-4854-840b-961d0d3f0d7d.png" width="130"/> ](https://user-images.githubusercontent.com/18307183/197308772-9ea8706e-070f-4854-840b-961d0d3f0d7d.png) [<img src="https://user-images.githubusercontent.com/18307183/197308775-d08e658a-2119-4d5a-9aef-47ecec449979.png" width="130"/> ](https://user-images.githubusercontent.com/18307183/197308775-d08e658a-2119-4d5a-9aef-47ecec449979.png) [<img src="https://user-images.githubusercontent.com/18307183/197308782-9919c55d-144c-4428-a566-70de6f81566e.png" width="130"/> ](https://user-images.githubusercontent.com/18307183/197308782-9919c55d-144c-4428-a566-70de6f81566e.png) [<img src="https://user-images.githubusercontent.com/18307183/197308784-addf4ede-c1fa-4cd3-a3f7-6e6055e270a3.png" width="130"/> ](https://user-images.githubusercontent.com/18307183/197308784-addf4ede-c1fa-4cd3-a3f7-6e6055e270a3.png) [<img src="https://user-images.githubusercontent.com/18307183/197308786-9e5e7d91-1f4a-478d-8c8d-aff89a6383fb.png" width="130"/> ](https://user-images.githubusercontent.com/18307183/197308786-9e5e7d91-1f4a-478d-8c8d-aff89a6383fb.png) 

### Solution

Make the manager searched for patched apps instead of (im assuming) storing patched apps in a local db without checking if they actually are patched or not.

### Additional context

Version: 0.0.36
Model: SM-N950U
Android Version: 9
Arch: arm64-v8a

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Haxorzz** [comment]
Having the same issue, I don't think the manager actually knows if an app is patched or not, it just knows if it patched an app previously.

**Comment by wolferburg** [comment]
Same issue, not just twitter only but every single apps in my case. Fortunately, I was able to pinpoint the problem by installing the patched apk via SAI. The error is `INTALL_FAILED_UPDATE_INCOMPATIBLE: Package <package name (in my case its com.spotify.music> signatures do not match previously installed version`. This error seems to happen only if you have the patched apps as bloatware or pre-installed. The only workaround for this problem imo is to have the installation of the patched app as a clone version, so that its signature would not conflict with pre-existing signature of the original app in your phone. And no uninstalling the bloatware through ADB doesn't work

**Comment by Aunali321** [comment]
I know a fix to this problem but i am on a trip this week, i will fix it as soon as i come back.

**Comment by Aunali321** [comment]
Twitter from playstore won't work. you need full apk from apk mirror. uninstall twitter, open manager select apk file from storage that you downloaded from apkmirror and patch.
