### ISSUE TITLE
YouTube TV app support

### ISSUE THREAD

**Issue by Ramhoe** [revanced/revanced-manager#429]
### Type

Other

### Issue

Please add support for the android tv YouTube app

### Feature

Add patches for YouTube TV app. Revanced manager already installs and work perfectly fine on Android tv

### Motivation

Currently the only TV app close to this is smarttube tv, but it's ui is ugly yet it's "the best app". Shouldn't the patches be the same? Wouldn't u just have to tell the manager app to let users use the YouTube for Android tv app? Or are there outside factors preventing this? Either way it would make the revanced project 1000x better 

### Additional context

Please and thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
This issue is not related to ReVanced Manager, please open this in the correct repository (revanced/revanced-patches)
