### ISSUE TITLE
bug: Two YouTube Patches not working

### ISSUE THREAD

**Issue by Someguy1519** [revanced/revanced-manager#431]
### Type

Other

### Bug description

Randomly when watching YouTube Videos, Video ads still  show even with Video Ads Patch enabled. Shorts button still shows with patch enabled.

### Steps to reproduce

Step 1: Patch YouTube 17.41.37 with Video Ads patch

Step 2: Patch YouTube 17.41.37 with Hide Shorts Button patch

### Android version

12

### Manager version

0.0.36

### Target package name

YouTube

### Target package version.

17.41.37

### Installation type

Non-root

### Patches selected.

![Screenshot_20221022-214231](https://user-images.githubusercontent.com/27980228/197374272-cb2f17f7-d43e-4c24-8951-4e5920ba4001.jpg)

### Device logs (exported using Manager settings).

```shell
Executing 'hide-shorts-button' of type: bytecode
[error] hide-shorts-button:kotlin.Unit

Executing 'video-ads' of type: bytecode
[error] video-ads:kotlin.Unit
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Executing 'video-ads' of type: bytecode
[error] video-ads:kotlin.Unit

Executing 'hide-shorts-button' of type: bytecode
[error] hide-shorts-button:kotlin.Unit
```

### Screenshots or videos

![Screenshot_20221022-214439](https://user-images.githubusercontent.com/27980228/197374320-5410f707-2ff1-41c6-b303-bbd8eedf14aa.jpg)
![Screenshot_20221022-214515](https://user-images.githubusercontent.com/27980228/197374322-f56447f7-0c89-4645-9ac0-f8366d53698b.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Canny1913** [comment]
1) Not related to ReVanced Manager
2) 17.41.37 is unsupported.
