### ISSUE TITLE
feat: Show the patched apk in the main UI

### ISSUE THREAD

**Issue by trmdi** [revanced/revanced-manager#432]
### Type

Functionality

### Issue

Sometimes after patching done, I accidentally close the final screen where has the Install button. Then I try to search for the patched one to install but I can't find it anywhere in the Manager. So there should be a place where the user can quickly find their patched apk.

### Feature

.

### Motivation

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Manager doesn't store patched apks. If you want to save apk click on three dots on top right area after patching and click on share apk. You can't share apk after you close that screen.

**Comment by trmdi** [comment]
> Manager doesn't store patched apks. If you want to save apk click on three dots on top right area after patching and click on share apk. You can't share apk after you close that screen.

Omg. Imagine you've waited minutes for the patching progress, but accidentally close it. The only thing you can do is to run it again from the scratch. That's a bad design!

Ok, so can you make it more difficulty to quit that screen? For example show a confirmation before let it close?

**Comment by flleeppyy** [comment]
bump
please implement a change, this is super annoying.

**Comment by flleeppyy** [comment]
Aliucord Manager did it
Vendetta does it
Lucky Patcher does it

what is the issue that's stopping this from being implemented? Many people have requested it and I have no coding experience with Dart to make a PR.

The original issue to this is #285, which hasn't been updated.

**Comment by Ushie** [comment]
#285 has nothing to do with this

**Comment by flleeppyy** [comment]
> #285 has nothing to do with this

Apologies, fixed.

**Comment by trmdi** [comment]
> bump please implement a change, this is super annoying.

To anyone who finds this issue annoying, try using github building templates like j-hc's one. You will never miss a file. It's completely automatic, save you lots of time.
