### ISSUE TITLE
feat: <Block videos and channels>

### ISSUE THREAD

**Issue by Abdullah-07** [revanced/revanced-manager#434]
### Type

Functionality

### Issue

As you know that YouTube is a space where we find all kinds of videos ranging from productivity to cringe ones🤢. And some cringe ones are more attractive or say more appealing and attention seeking, which in a sense reduce productivity.

### Feature

So to tackle this issue, there should be a feature to block channels completely even from search as extensions are also available for PC for this purpose too.

### Motivation

This feature will help to reduce distractions to great extend, IDK if it is possible or not but it will be fabulous if it is.. 

### Additional context

I often find myself watching cringe content and spending hours, and I think there are certainly people like me who feel very bad every time they do so. So I think this feature to block channels altogether from showing you videos will be very helpful.
Thanks. 

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by reisxd** [comment]
This is the manager repo, not patches repo.

**Comment by Abdullah-07** [comment]
I should put it on patches?
