### ISSUE TITLE
feat: aurora store integration through intents to download recommended app version 

### ISSUE THREAD

**Issue by Quackdoc** [revanced/revanced-manager#436]
### Type

Functionality

### Issue

needing to get a download of the current recommended version of the app can be hard and risky if the user downloads from an untrusted source.

### Feature

It would be nice to have an intent to download the recommended app as well as version code of said app. this can easily be done with aurora store in a relatively convenient way.

aurora store can work with playstore URI intents. aurora store also has the ability to install older versions of the apps directly from google.

How I personally see this being implemented would be a "download" icon that would first show a warning that aurora store is needed, copy the version code to clipboard and send a playstore intent, assuming aurora store is installed, and the user has it setup up, aurora store will then open the app's download page, and from there the user can click the 3 dot menu button, Manual download. paste the code and download and install the recommended version of the app.

### Motivation

This would be a great convenience feature to have that should be low risk to implement.

### Additional context

Possibly related to #289 , it was marked as completed but I am not sure what features if any where implemented for this and see no obvious changes for it as of 0.0.36

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
It is not manager's responsibility to download the app. It's simply a tool to patch apps. It is designed to be app agnostic. For more read #125.

**Comment by Quackdoc** [comment]
Hello, sorry for taking a while to reply to this

The point of the feature request is *explicitly* because it's not the apps responsibility to download the apps, this would simply be two small features that play together in a way to help the user, not take responsibility for getting the app. 

1. send an intent to open the apps google play store, this can be easily done by simply reading the apps name and doing `https://play.google.com/store/apps/details?id=com.android.id`. this can easily be done for any app, even apps that aren't supported. so this shouldn't hurt app agnosticism in anyway at all.

this isn't even useful unless the user has an app that can handle gplay store intents, so this shouldn't lead to any trouble at all, nor does it make the app into a downloader or put the responsibility of downloading the app do be patched on revanced. 

2. Report the version code as well as the version, Revanced already reports the recommended version of apps. so it would be (hopefully) minimal effort to report that as well since version name and version code are both within an apps version information. Reporting the version code would lead to no less agnosticism then what Revanced already has.
