### ISSUE TITLE
YouTube Sponsors Block non-root

### ISSUE THREAD

**Issue by PeterKW** [revanced/revanced-manager#437]
### Type

Error while running the manager

### Bug description

Sorry, not very clear on what's happening/if I'm doing something wrong.

Do I need to use an apk installer that handles apk bundles? Where does it say which plugins require root?
Is there a list of which applications can be changed somewhere? YouTube, Spotify, Twitter, etc.

### Steps to reproduce

.

### Android version

11

### Manager version

0.0.36

### Target package name

YouTube

### Target package version.

?

### Installation type

Non-root

### Patches selected.

SponsorBlock

### Device logs (exported using Manager settings).

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by PeterKW** [comment]
Not sure if it's a bug, didn't particularly try to apply that label to the question

**Comment by Aunali321** [comment]
Check revanced-patches repo.

**Comment by jean-raphael** [comment]
> Check revanced-patches repo.

thanks, next time ill sugest you to reply directly with this reply

**Comment by jean-raphael** [comment]
> Check revanced-patches repo.

thanks
