### ISSUE TITLE
[discussion] integrate tournesol app 

### ISSUE THREAD

**Issue by jean-raphael** [revanced/revanced-manager#438]
### Type

Functionality

### Issue

everyone knows that the suggestion algorithm of YouTube is very bad, from the oppacity of these algorithms to the propagation of false information through the recommendation of poor quality videos

### Feature

looking for this problem the mathematician Lé of the science4all channel has proposed a transparent answer to this problem of artificial intelligence

he created the platform sunflower app
https://github.com/tournesol-app/tournesol
https://addons.mozilla.org/fr/firefox/addon/tournesol-extension
https://tournesol.app/recommendations?date=Month&language=en

the objective is to allow the Internet users to vote to determine and to emphasize the video judged of public utility

I think that this platform would deserve much more visibility and I think that an integration in revanced would be ideal for that, even if, given its nature, its integration will probably be a difficult task.
 If it were possible to simply start a discussion between the two teams it would be a big step forward to me

https://www.youtube.com/watch?v=HTzEkz8sFEE
https://www.youtube.com/watch?v=fe9u6YQTsWY

### Motivation

propose a solution to the worrying problem of the opacity of recommendation algorithms and limit the propagation of fake news

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Not related to manager.

**Comment by jean-raphael** [comment]
> Not related to manager.

hmm what ? this is afeater like sponsor block and it is no related ?

**Comment by jean-raphael** [comment]
> How is this related to manager? This is manager repo not patch request repo.

o sorry i am stupid i think there is only one repo
