### ISSUE TITLE
Can Android 7 be supported at least?

### ISSUE THREAD

**Issue by BlasterOverlord** [revanced/revanced-manager#440]
### Type

Functionality

### Issue

The current banded manager supposedly only supports Android 8 and up.
Can you please allow android 7 users to install the manager as well?

### Feature

Android 7 support

### Motivation

Because vanced was always accessible to lower android versions.
But it's predecessor seems to have chosen to completely ignore older android versions. Very sad.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Canny1913** [comment]
ReVanced Manager depends on Java Files class, which was added in Android 8.0 (26)

**Comment by DraconicNEO** [comment]
They're never going to do that because that would take work and they don't like doing work. Remember how long it took for them to release a working manager.

**Comment by Ushie** [comment]
> They're never going to do that because that would take work and they don't like doing work. Remember how long it took for them to release a working manager.

Would you like to do it?
