### ISSUE TITLE
bug: <adds showing on YouTube>

### ISSUE THREAD

**Issue by Vegetagiy123** [revanced/revanced-manager#442]
### Type

Other

### Bug description

I found the adds while I was patching it from storage from YouTube APK mirror 

### Steps to reproduce

Step 1 fix the add video removal
Step 2 remove the video adds 

### Android version

Android 13

### Manager version

0.0.36

### Target package name

I tried to patch video add removal and it doesn't work 

### Target package version.

I tried to patch YouTube 

### Installation type

Non-root

### Patches selected.

I used all the patches in the YouTube revanced manger 

### Device logs (exported using Manager settings).

```shell
I found the adds showing in YouTube revanced after I patched it from YouTube APK mirror from storage
```

### Screenshots or videos

![Uploading Screenshot_20221026-113622.png…]()

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by ExperiencersInternational** [comment]
I think this should have been in the revanced-patches GitHub page. I've been experiencing the same issues as well, but I suspect it's an issue with 17.4x.xx+, standard Vanced on 17.03.(something) still works fine with blocking video ads for example.
