### ISSUE TITLE
bug: Manager not getting up to date patches

### ISSUE THREAD

**Issue by ExperiencersInternational** [revanced/revanced-manager#443]
### Type

Error at runtime

### Bug description

Basically, when you open the app, it won't show the up to date patches version, for example, according to the manager the last one was 22 days ago, when in reality, it was about 2 hours ago.

### Steps to reproduce

Step 1. Open the Manager
Step 2. On the updates page, patches should say something like last updated 22 days ago

### Android version

Android 12 (MIUI 13)

### Manager version

0.36

### Target package name

com.google.android.youtube

### Target package version.

17.42.33

### Installation type

Non-root

### Patches selected.

is this necessary?

### Device logs (exported using Manager settings).

```shell
https://1drv.ms/u/s!AgNafXziV9SskjfW1vyQJCJ9M3cV
```

### Screenshots or videos

![Screenshot_2022-10-26-23-45-49-039_app revanced manager flutter](https://user-images.githubusercontent.com/56035537/198152771-e9aff924-f812-413d-a474-7634f3324aea.jpg)
![Screenshot_2022-10-26-23-45-38-727_app revanced manager flutter](https://user-images.githubusercontent.com/56035537/198152774-10420e41-db9b-4271-95da-1d2f8a96c993.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
That is updates for patcher not patches.
