### ISSUE TITLE
Copying the youtube apk file to fix broken update feature

### ISSUE THREAD

**Issue by aleks01100001** [ReVanced/revanced-manager#445]
### Type

Functionality

### Issue

The update funktion on revanced manager is broken or doesnt work properly

### Feature

Copy the used apk file (for example youtube) to the managers file folder where the keystore is stored to fix the update funktion in the manager

### Motivation

I think it will be a nice workaround to fix the update funktion and i think it wont be so difficult to implement this.
And it will be easier for us the users to just tap update and all the patches that we previously selected will be automatically selected so we dont have to do it again or remember which of the patches we selected.

### Additional context

For clarification i mean this path  /storage/emulated/0/Android/data/app.revanced.manager.flutter/files

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
There is an open PR for exporting patched APKs

**Comment by aleks01100001** [comment]
i didnt mean that.
You guys said that the update funktion is not working when there is a new patch available, so i thought that this could fix it.
For example when there is a new version of patches available, we can select the apk file and the patches all again and its not a problem like we do it right now, but i thought it will be easier for the manager to do it for us.
I mean if its possible to just copy the selected apk file from vanilla youtube (not revanced youtube) in the managers file folder where the keystore is stored, then the manager could theoretically use that apk file to repatch the app and reselect all the patches we selected, to make it all automatically

**Comment by Aunali321** [comment]
That's the plan, but i am not having time to implement it.

**Comment by Ushie** [comment]
Update has been removed
