### ISSUE TITLE
Video Ads Patch Bug

### ISSUE THREAD

**Issue by hgunduz295** [revanced/revanced-manager#446]
### Type

Error while running the manager

### Bug description

Video ads patch issue 
![Screenshot_20221027-232810](https://user-images.githubusercontent.com/36344949/198391991-cb9608d5-cce6-467e-88b4-90ac6d21a208.jpg)

### Steps to reproduce

Open revanced manager》select patcher >select youtube app>select patches 》apply 
No problem about patching but youtube app not open and also video ads patch not work.

### Android version

12

### Manager version

0.0.36

### Target package name

Youtube

### Target package version.

17.41.36

### Installation type

Root

### Patches selected.

General ads, VideoAds,download,minimized playback

### Device logs (exported using Manager settings).

```shell
https://drive.google.com/file/d/11k28nzmQlgvNIooH0KGrA56XGsh6xHbf/view?usp=drivesdk
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
https://drive.google.com/file/d/11k28nzmQlgvNIooH0KGrA56XGsh6xHbf/view?usp=drivesdk
```

### Screenshots or videos

![Screenshot_20221027-232810](https://user-images.githubusercontent.com/36344949/198393273-ca792613-ab3f-4033-b0e8-0320b295b1dc.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aurobindoji** [comment]
![Screenshot_2022-10-28-12-08-13-377_app revanced manager flutter](https://user-images.githubusercontent.com/114210081/198520792-4985d883-d47e-4d06-bc31-b19a8343eff0.jpg)
Yt 17.41.37 from apkmirror
Manager 0.0.36

**Comment by bigbadmoshe** [comment]
I am having ad issues as well with 17.41.37 from apkmirror
And Manager 0.0.36 using patch v2.93.0

**Comment by oSumAtrIX** [comment]
Reverted compatibility with that version.
