### ISSUE TITLE
bug: Patched app crashes always

### ISSUE THREAD

**Issue by emgaurav** [revanced/revanced-manager#448]
### Type

Error at runtime

### Bug description

Patched youtube app never opens. Always crashes 

### Steps to reproduce

Simply patch and install and open the patched app

### Android version

12 on IQOO3 

### Manager version

0.0.36

### Target package name

Youtube

### Target package version.

17.41.36

### Installation type

Non-root

### Patches selected.

Background play and microg

### Device logs (exported using Manager settings).

```shell
Nothing there
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Lolen10** [comment]
I have the same problem, but with root install.

**Comment by fmajestic** [comment]
Same error, I am patching the split-config app installed from apkmirror

Managed to get some logs with Android Studio: [revanced.log](https://github.com/revanced/revanced-manager/files/9894832/revanced.log)

This seems to be the main exception:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{app.revanced.android.youtube/com.google.android.apps.youtube.app.application.Shell_HomeActivity}: android.content.res.Resources$NotFoundException: Drawable app.revanced.android.youtube:drawable/quantum_launchscreen_youtube with resource ID #0x7f080906
[...]
Caused by: android.content.res.Resources$NotFoundException: Drawable app.revanced.android.youtube:drawable/quantum_launchscreen_youtube with resource ID #0x7f080906
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/quantum_launchscreen_youtube.xml from drawable resource ID #0x7f080906
[...]
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #6: <bitmap> requires a valid 'src' attribute
```

**Comment by flAmEDIEU** [comment]
Same here

**Comment by marcofugaro** [comment]
I think this may be related to youtube releasing a redesign of the app, I think ReVanced install always the latest version of the youtube app.
I guess we just have to wait until the ReVanced team adapts it to the new YouTube app.

**Comment by x1404x** [comment]
I'm having the same problem

**Comment by Aunali321** [comment]
Uninstall yt updates, go to apkmirror and download 17.36.37 yt. make sure you download nodpi apk (120mb+) and patch that.

**Comment by emgaurav** [comment]
What patches are you selecting?

**Comment by emgaurav** [comment]
I am getting "non root install not possible with this selection of patches
" everytime.

**Comment by Ushie** [comment]
You aren't selecting the Microg-Support patch

**Comment by emgaurav** [comment]
Worked. Thank you very much.

**Comment by marcofugaro** [comment]
I'm still having the crashes after I followed @Aunali321 suggestions, but after a restart.
I am installing ReVanced via the root method.

**Comment by justatestaccountfortdl** [comment]
Obviously @Ushie's suggestion is incorrect, hence no idea what could case that, on top of it there's an issue when you select premium header too, it will notify you that resource does no exist.

**Comment by Ushie** [comment]
> Obviously @Ushie's suggestion is incorrect, hence no idea what could case that, on top of it there's an issue when you select premium header too, it will notify you that resource does no exist.

Then you have failed to follow @Aunali321's instructions, your issue is offtopic to this issue.

**Comment by justatestaccountfortdl** [comment]
> your issue is offtopic to this issue.

Well if you cannot see the relation between my message and the latest posts in this issue, then yeah, definitely an off topic comment in the issue related topic.

I just stated that your comment has nothing to do with this issue since the micro-g option was enabled, even tho it clearly states that this problem was related to DPI related resources, you can just observe it in the log, yes, @Aunali321's comment is more suitable for resolving this issue, but the main problem is, people tend to download the app via google play, which pushes dpi related bundles, so it has to be stated somewhere in readme that nodpi is the mandatory.

**Comment by Ushie** [comment]
> you can just observe it in the log, yes

The log was not provided by the person who opened this issue

> in fixing root related installation

There was no mention of root installation in this issue, only non-root
