### ISSUE TITLE
Video Speed

### ISSUE THREAD

**Issue by Lorestan00** [revanced/revanced-manager#452]
### Type

Functionality

### Issue

There is no way to set a default video speed

### Feature

Having a setting to change video speed 1.25, 1.50, 2.00 etc which applies to all videos

### Motivation

Useful in watching videos more quickly and also speed up anyone who speak slowly

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by Lorestan00** [comment]
Any chance this could be added to the road map even if it's in the future?

Vanced had this feature

**Comment by pilothaz** [comment]
I'd love to see this feature as well as I would have all my stuff defaulted to 1.75x
