### ISSUE TITLE
Check whether a patch needs root before patching

### ISSUE THREAD

**Issue by dongle-the-gadget** [revanced/revanced-manager#453]
### Type

Functionality

### Issue

Currently, ReVanced Manager only checks whether a specific patch requires root before installation, which could lead to some frustrating scenarios like:
- The user is only aware rooting is required after patching, in which they would have to go through the patching process again after installing root.
- In case a user chooses to apply a root-required patch to an APK on local storage, the user would find it impossible to install the app, since the manager doesn't allow root installation of APKs in local storage, nor does it allow nonroot installation of the patched APK.

### Feature

Show whether a specific patch needs a rooted device before the manager starts patching. Additionally disable root-required patches when the source APK is in local storage.

It helps solve the issue by letting the user know ahead of time whether a patch they like requires a root installation, in which they can root their device if necessary. It also helps prevent such scenarios where installation is impossible.

### Motivation

It would be a time saver, since this prevents the user from having to patch the app multiple times.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by ILoveOpenSourceApplications** [comment]
Do we even have patches that are specifically for rooted users?

**Comment by oSumAtrIX** [comment]
By design, no.

**Comment by ILoveOpenSourceApplications** [comment]
So this issue request is irrelevant?

**Comment by dongle-the-gadget** [comment]
I wasn't talking about the patches specifically, more of whether a combination of patches would result in a root-only binary. For example, patching YouTube without "use microG" would give a root-only binary, but the app doesn't notify the user of that before reaching the installation screen.

**Comment by Aunali321** [comment]
Added in https://github.com/revanced/revanced-manager/commit/74e0c09b543fe70b70cd917e6e21ceb0f46f3533.
