### ISSUE TITLE
feat: Easier apk sharing for adb

### ISSUE THREAD

**Issue by DATL4G** [revanced/revanced-manager#456]
### Type

Functionality

### Issue

I'm in Googles [advanced protection program](https://landing.google.com/advancedprotection/).
Because of it's security options I can't install apps on-device, instead I have to install them with adb.

### Feature

A simple option to share the apk with my computer.
Currently I patch my apps on-device and share in my cloud then download it on PC and install it.

Something like displaying the path of the patched apk and maybe an option to move it to another path would be nice.
Then I can easily copy it from device to PC without sharing in cloud.

### Motivation

Google pushes their advanced protection and plans to enable it by default.
I think you can already just enable this protection feature, I had to apply for it previously.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
You could share the APK in the mean time, however there is an open PR for exporting the patched Apk that seems like it may fulfill your usage needs #439

**Comment by Ushie** [comment]
In the future there may be Shizuku integration to allow prompt-less installation which would sort your issue as a by-product as it is the same as installing with ADB
