### ISSUE TITLE
Feature Request: Slideable volume/brightness controls

### ISSUE THREAD

**Issue by LightslicerGP** [revanced/revanced-manager#457]
### Type

Functionality

### Issue

So for youtube, in the original youtube vanced you had the option to have swipe controls, on the left if you wipe up/down you would increase/decrease brightness, while on the right side it would change volume, but there's no apk addon in the feature selector in revanced manager

### Feature

Adding these swipe controls as a selectable option would make it better, and fix what was missing.

### Motivation

I had gotten used to the controls and it was so easy to have those controls handy whenever you change environments or need to adjust volume really quickly without needing to move the phone physically, only needing to swipe on the screen.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Not a manager issue.
