### ISSUE TITLE
feat: display timed warning for armv7 users on app launch

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-manager#458]
### Type

Functionality

### Issue

People dont realize that armv7 is not supported and kept asking on reddit and github issues, wasting time and resources

### Feature

When manager is opened, check if the arch is armv7 (or other unsupported versions). If so, a pop-up saying "{arch} was not, is not, and will probably not be supported. If you encounter any issues while patching, this is probably why. Visit {link} for more infomation" should be shown.

### Motivation

- saves time
- get rid of unsupported arch issues and requests

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Canny1913** [comment]
Patching with ARMv7 only fails on certain devices, not all.

**Comment by reisxd** [comment]
It shouldn't fully restrict the usage of Manager, but only as a warning that you have to mark as read and wait to continue using Manager. Compiling resources work on some devices and not on some.

**Comment by Canny1913** [comment]
Also bytecode patches work fine on ARMv7, only resource patches fail due to AAPT2.

**Comment by SodaWithoutSparkles** [comment]
> It shouldn't fully restrict the usage of Manager, but only as a warning that you have to mark as read and wait to continue using Manager. Compiling resources work on some devices and not on some.

Thats exactly what I mean

**Comment by SodaWithoutSparkles** [comment]
Possibily solved by https://github.com/revanced/revanced-manager/commit/cdfb09fbfa8e74d84ddcc91565489c3c5b61dfa2

**Comment by reisxd** [comment]
I think this won't be necessary after the ArcsLib implementation for resource patching, because it doesn't depend on AAPT2.

**Comment by SodaWithoutSparkles** [comment]
The warning was triggered by a discord user @LAUGHING CAT MEME#5354 on an armv7 device. Nevertheless, the user ignored the warning and asked for tech support anyways. We should make it clear that the patch will likely not success. We should also make it clear that what should the user do when patcher aborted.

![image](https://cdn.discordapp.com/attachments/1102217799566360629/1102219718221377667/IMG_0232.jpg)

**Comment by SodaWithoutSparkles** [comment]
I think this could be closed for now.
