### ISSUE TITLE
Youtube Music Casting Ads are not blocked

### ISSUE THREAD

**Issue by jordaninthesky** [revanced/revanced-manager#459]
### Type

Other

### Bug description

Casting a patched version of Youtube Music does not carry the benefits of ad-skip/block when casting to a Android TV.  Even when the Android TV doesn't have YT Music installed, it still handles the casting, and it appears that everything is controlled by the app that is on the phone.  Fringe use?  I am very happy with this project.  Wasn't sure if to request a new feature or report as bug.  I have a feeling this is client-side related.

### Steps to reproduce

Make sure Android TV doesn't have Youtube music (or Youtube) installed.  Run a known working patched version of YT Music on a phone or android device.  Cast to Smart TV.  Experience ads.  Device hosting patched YT Music app will occasionally confirm that an ad is running and offer premium.

### Android version

Android 11.  Don't quite know how to navigate to anything more specific/relevent.  Please inform.

### Manager version

0.0.36

### Target package name

youtube music 5.29.52-52952240

Seems to work on the phone itself.  No issues so far.

### Target package version.

5.29.52-52952240

### Installation type

Root

### Patches selected.

Music Video Ads 0.0.1 / Hide Get Premium 0.0.1 / Upgrade Button Remover 0.0.1

### Device logs (exported using Manager settings).

```shell
Please let me know how to share this information if it is necessary.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [x] The issue is related solely to the ReVanced Manager

**Comment by reisxd** [comment]
Wrong repo and this is a normal behaviour. Casting is like a TV controller, not like miracasting

**Comment by jordaninthesky** [comment]
> Wrong repo and this is a normal behaviour. Casting is like a TV controller, not like miracasting

Can you be more technical?

**Comment by reisxd** [comment]
> > Wrong repo and this is a normal behaviour. Casting is like a TV controller, not like miracasting
> 
> Can you be more technical?

Casting only sends what to play to the TV client, ads aren't controlled by casting.

**Comment by jordaninthesky** [comment]
> Casting only sends what to play to the TV client, ads aren't controlled by casting.

Does the TV client confirm the credentials of the account to determine ads, even if no account is associated with the TV?

**Comment by reisxd** [comment]
> > Casting only sends what to play to the TV client, ads aren't controlled by casting.
> 
> Does the TV client confirm the credentials of the account to determine ads, even if no account is associated with the TV?  

No. Again, casting has nothing to do with ads, the ad information is on the TV client.

**Comment by jordaninthesky** [comment]
> No. Again, casting has nothing to do with ads, the ad information is on the TV client.

Information is being sent by the source (patched app) to to confirm ads.  If it cannot be touched, I'd understand.
