### ISSUE TITLE
bug: unable to sign in

### ISSUE THREAD

**Issue by emgaurav** [revanced/revanced-manager#462]
### Type

Error at runtime

### Bug description

Unable to sign in. Keeps giving me network error. Please check your network connection.
My network is fine. 

### Steps to reproduce

Simply click on user icon on top right corner in youtube. It shows my email id there which is not click able. 

### Android version

12

### Manager version

0.0.36

### Target package name

Youtube 

### Target package version.

.37 no dpi

### Installation type

Non-root

### Patches selected.

Background play, no ads, swipe controls 

### Device logs (exported using Manager settings).

```shell
na
```

### Screenshots or videos

![Screenshot_20221101_220604](https://user-images.githubusercontent.com/38912972/199287971-af1c0be4-b1a5-4a07-954d-c5c55b84c77c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
This is not related to ReVanced Manager, please read the FAQ in the Vanced Discord Server as this issue concerns their MicroG, not us.
