### ISSUE TITLE
feat: <Color Coding Elements During Patching>

### ISSUE THREAD

**Issue by Matty003** [revanced/revanced-manager#468]
### Type

Cosmetic

### Issue

When **Patching** process is going on , it's sometimes a bit `time consuming` to find which patch has shown error as both  [success] **and** [error] are **shown** in same **color** .

### Feature

It `will` help if [success] **and** [error] are shown in different color.

### Motivation

It `might` help in **trying** and **testing** non-supported versions with different or unsupported patches.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
Dupe of #269

**Comment by Matty003** [comment]
Although i've searched by term ”color" and not by "red" or "error" but thanks for checking .
