### ISSUE TITLE
YoutubeNonStop

### ISSUE THREAD

**Issue by jacc555** [revanced/revanced-manager#47]
Hi.
After a few pieces of music, the music stops playing, a question arises. "Do you want to continue"
Is it possible to add solution, colleague's @lawfx [YoutubeNonStop](https://github.com/lawfx/YoutubeNonStop)
Unless a bypass of retention already exists? tell me how to turn it on?
Can this option be added to revanced?

**Comment by Aunali321** [comment]
@jacc555 wrong place for this.
