### ISSUE TITLE
feat: Download whole playlists in YouTube revanced

### ISSUE THREAD

**Issue by IdontPlayz343** [revanced/revanced-manager#474]
### Type

Functionality

### Issue

If I wanted to download a playlist of music on YouTube revanced, i would have to download each song individually. For large playlists, that is tedious.

### Feature

Add a patch that lets you download whole playlists (this would be for the normal YouTube app, not for the YouTube music app.)

### Motivation

Downloading every video in a playlist is way too tedious for larger playlists.

### Additional context

This isn't a request for the music version, mainly since the music app has half of the songs on it unavailable, and this can be used for series of tutorials.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
This issue belongs to the patches repository, it is unrelated to the Manager.

**Comment by IdontPlayz343** [comment]
> This issue belongs to the patches repository, it is unrelated to the Manager.

Apologies! Very good point.
