### ISSUE TITLE
bug: <YT back button doesn't close patched yt app>

### ISSUE THREAD

**Issue by Aurobindoji** [revanced/revanced-manager#479]
### Type

Other

### Bug description

Pressing back button doesn't close youtube and stucks at yt homepage.
Manager latest
Yt apk (recommended)
Problem has been with every version of manager and yt.

### Steps to reproduce

Pressing back button

### Android version

Android 10
MIUI 12.5
REDMI 8A dual

### Manager version

0.0.39

### Target package name

Yt 17.41.37

### Target package version.

Yt 17.41.37

### Installation type

Non-root

### Patches selected.

Except debug, cast button

### Device logs (exported using Manager settings).

```shell
Not avalable
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by Aurobindoji** [comment]
https://user-images.githubusercontent.com/114210081/199909903-c93daa7e-0760-4150-9748-da63b5d47133.mp4

**Comment by Ushie** [comment]
This issue belongs to the revanced patches repository, not revanced manager
