### ISSUE TITLE
Stuck at "creating working directory"

### ISSUE THREAD

**Issue by Bluscream** [ReVanced/revanced-manager#483]
### Type

Error while running the manager

### Bug description

![Screenshot_2022-11-05-13-09-34-800](https://user-images.githubusercontent.com/3318223/200119179-4df7313f-33c3-4d1f-a5bd-daa6cf2b5d35.jpeg)

### Steps to reproduce

Open vanced manager
Select youtube and any patch
Wait

### Android version

Idk?

### Manager version

Version 0.0.39 (39)

### Target package name

youtube stock

### Target package version.

17.43.36

### Installation type

Root

### Patches selected.

First one

### Device logs (exported using Manager settings).

```shell
No idea
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by vibbow** [comment]
I have the same issue

Samsung One UI 4.1 (Android 12)
Revanced manager 0.0.40

target package:
youtube stock 17.43.36

**Comment by Holguitar** [comment]
Same here on different devices (Moto G5+ A8 up to Xiaomi Mi9T A11) rooted and non rooted.

**Comment by HalfArrow** [comment]
Same issue, Android 13 One UI 5.

**Comment by Mygod** [comment]
Clearing app data fixed it for me.

**Comment by trmdi** [comment]
> Clearing app data fixed it for me.

But it clears the Cert key too, that sucks.

**Comment by oSumAtrIX** [comment]
Did you exit the app while it was patching?

**Comment by trmdi** [comment]
> Did you exit the app while it was patching?

Can't reproduce in this way.

**Comment by oSumAtrIX** [comment]
Not sure what you are saying. Please explain.

**Comment by trmdi** [comment]
> Not sure what you are saying. Please explain.

I mean I tried to exit the app while patching as you said to reproduce this bug but I can't.

**Comment by oSumAtrIX** [comment]
I asked wether you exited the app; I didn't say you should.

**Comment by trmdi** [comment]
> I asked wether you exited the app

No, I didn't.

**Comment by oSumAtrIX** [comment]
Please attach a complete recording of the following steps to understand your issue better:

1. Open and close ReVanced Manager
2. Review the settings of ReVanced Manager
3. Patch the app

**Comment by terrytw** [comment]
I had the exact same issue. Out of desperation, I turned off Adguard and tried again, and it works!

So when stuck at creating work directory, it could be network issues. Try looking into that direction if you have the same problem.

**Comment by ILoveOpenSourceApplications** [comment]
The manager version mentioned in this issue is very old. But the bug is still existing till date? Are any of the solutions mentioned above are of help?

**Comment by terrytw** [comment]
> The manager version mentioned in this issue is very old. But the bug is still existing till date? Are any of the solutions mentioned above are of help?

Yes it still exists in the latest version, and I was able to fix it by turning off my VPN based adblocker(adguard).

**Comment by CnC-Robert** [comment]
> The manager version mentioned in this issue is very old. But the bug is still existing till date? Are any of the solutions mentioned above are of help?

One workaround is reinstalling the app

**Comment by ILoveOpenSourceApplications** [comment]
> One workaround is reinstalling the app

Every time you're patching an app?

**Comment by CnC-Robert** [comment]
> Every time you're patching an app?

Every time this issue occurs

**Comment by ILoveOpenSourceApplications** [comment]
> Every time this issue occurs

And how often does that happen?

**Comment by trmdi** [comment]
I can't reproduce it in recent releases.

**Comment by terrytw** [comment]
> > Yes it still exists in the latest version, and I was able to fix it by turning off my VPN based adblocker(adguard).
> 
> Wouldn't that make it an issue of adguard and not the manager?

Yes and No.
The issue with manager is that:

1. It is not correctly communicating with the user. When it is stuck at "creating working directory", most normal user would not know what is happening, some advanced user would think it might be a permission issue, but as someone in the XDA forum post pointed out, the manager uses Android/data/*** directory which should not cause any permission issue. Then we as user are out of wit. But in reality the manager is downloading or connecting to the internet, when it shows "creating working directory". If it shows "downloading" or "connecting", then users would go and see if there is any problem with their connection. 
2. Since the manager is meant to be a user friendly GUI, I think it does not make any sense to have the progress hang forever unless the app itself crushed. In this case, the app is working, it is just unable to get the resources it needs to progress to the next step, and it is stuck there forever. A sensible thing to do is at least set a timeout, and maybe run a simple diagnostic and tell the user what to do.

**Comment by ILoveOpenSourceApplications** [comment]
> There are multiple possibilities that could cause this problem, mine is just one of them. It happens in the latest version, and clearing data/cache or reinstalling app did not fix it for me.

Now that you know what caused issue on your side implies that this issue is clearly solved. Not everyone is having the same issue and if you've tried opening the app without internet at some point you'll know that the app requires internet to function, atleast that's how things are for now. If you want to apply what you said in the first two points that's a different case and would be a feature request and not a bug.

**Comment by ILoveOpenSourceApplications** [comment]
@oSumAtrIX or @Ushie, this bug report is no longer related to manager and can be closed right?

**Comment by oSumAtrIX** [comment]
Are you sure this issue is solved?

**Comment by trmdi** [comment]
Maybe the manager should stop when the connection is lost?

**Comment by oSumAtrIX** [comment]
The app should not require any connection to begin with.

**Comment by trmdi** [comment]
> The app should not require any connection to begin with.

Is it correct? It definitely requires internet to download patches.

**Comment by oSumAtrIX** [comment]
That shouldn't be a requirement. Choosing sources locally should be always available.

**Comment by trmdi** [comment]
Ah yes, just checked again. Once the patch has been downloaded completely it could work without internet.

**Comment by ILoveOpenSourceApplications** [comment]
> Are you sure this issue is solved?

The issue isn't related to manager as for the OP it was caused by adguard.

**Comment by terrytw** [comment]
I am not the OP. And I think displaying wrong/misleading information is a bug, not a feature request.

**Comment by oSumAtrIX** [comment]
I am not sure what you mean.

**Comment by trmdi** [comment]
> > Are you sure this issue is solved?
> 
> The issue isn't related to manager as for the OP it was caused by adguard.

Adguard causes the connection corrupted but Revanced Manager need to handle the case when it can't get patches.

**Comment by Bluscream** [comment]
I agree with @terrytw. Yes it's not strictly a bug caused by Revanced in that case, but it's still a bug that effects Revanced and should therefor atleast be handled approriatly (no need to workaround, just show a normal HTTP error and move on)

**Comment by terrytw** [comment]
> AG is probably not; or atleast won't be the only app causing this

Indeed, it may not even necessarily be an app, it could be a custom rom, an internet censorship, etc., anyway, user should be notified of the current situation.

**Comment by Lggggggg** [comment]
> I had the exact same issue. Out of desperation, I turned off Adguard and tried again, and it works!
> 
> So when stuck at creating work directory, it could be network issues. Try looking into that direction if you have the same problem.

Thank you, it works!

**Comment by ILoveOpenSourceApplications** [comment]
Can this considered as complete with the merge of #1114?

**Comment by Ushie** [comment]
If the issue still happens in the latest version of ReVanced Manager, open a new issue
