### ISSUE TITLE
Incorrect notification

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-manager#486]
### Type

Cosmetic

### Bug description

Manager displays notification about updating the manager at the wrong timing

### Steps to reproduce

1. Install an older manager version, like .36 to update
2. Termux might need to be installed to have another choice when installing an apk
3. Tap update manager and confirm, switch manager to background
4. wait until download completed
5. A notification popped up. It said "Manager was updated" but it should be "Manager is ready to update. Click to install", as the manager has not been updated **yet**

### Android version

13

### Manager version

0.0.36 → 0.0.39

### Target package name

N/A

### Target package version.

N/A

### Installation type

Non-root

### Patches selected.

N/A

### Device logs (exported using Manager settings).

```shell
N/A
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
N/A
```

### Solution

Change it to something like "Manager is ready to update. Click to install"

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
fixed in #496.
