### ISSUE TITLE
feat: yt kids patches

### ISSUE THREAD

**Issue by Koognod** [revanced/revanced-manager#487]
### Type

Functionality

### Issue

I don't like that youtube advertises to my child.

### Feature

add yt kids to manager and patches so I can remove ads.

### Motivation

its wrong to advertise to yound children. lots of people have kids and can relate, I'm sure .

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
This issue belongs to the [patches repository](https://github.com/revanced/revanced-patches)
