### ISSUE TITLE
Play Next option

### ISSUE THREAD

**Issue by Ramanand11** [revanced/revanced-manager#489]
### Type

Functionality

### Issue

For better user experience

### Feature

Please give play naxt option in next update

### Motivation

For better user experience

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
This issue belongs to the patches repository
