### ISSUE TITLE
feat: Add Unpatch & Re-patch feature for Root users after the app is updated.

### ISSUE THREAD

**Issue by n-core** [ReVanced/revanced-manager#490]
### Type

Functionality

### Issue

I've faced this several times, that apps became corrupted after they are updated, like this #237. When you rebooted your phone, those apps became corrupted, and you have to manually unpatch and re-patch the app again.

### Feature

So it would be nice to add a feature to unpatch and re-patch the app with just a single button.

### Motivation

Also, after they updated, it seems like those apps are nowhere to be seen on "Patched Applications" section. Basically renders you unable to unpatch the app, and you have to patch it -> unpatch it -> re-patch it again.
![image](https://user-images.githubusercontent.com/110832881/200530295-54149ab5-64a7-463e-8ac6-26a0e04e2595.png)
So many times just wasted waiting for the patching and re-patching process.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by ILoveOpenSourceApplications** [comment]
Doesn't rooted users already have a un-patch option?

**Comment by oSumAtrIX** [comment]
ReVanced Manager will soon be released as [a full rewrite](https://github.com/ReVanced/revanced-manager/tree/compose-dev). Over time, many feature requests have been made for the current version of ReVanced Manager, but to accelerate the development of the new version of ReVanced Manager, we have to focus on it, which I am closing this issue according to the [contribution guidelines](https://github.com/ReVanced/revanced-manager/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long/ Low priority/ Maintainers un-interested/ Too complex to realize
- Feature planned/ already implemented for the new version of ReVanced Manager

Regardless, anyone who comes across this feature request can PR it to the current version of ReVanced Manager until the new version is ready. Thanks for your feature request!
