### ISSUE TITLE
bug: Can not update patched apps

### ISSUE THREAD

**Issue by trmdi** [revanced/revanced-manager#493]
### Type

Other

### Bug description

Maybe this does not happen on all devices but on some ones. See users' reports:
- https://www.reddit.com/r/revancedapp/comments/yph4zh/updating_apps_doesnt_work/
- https://www.reddit.com/r/revancedapp/comments/yh2aoh/revanced_manager_does_not_let_you_savekeep_track/
- https://www.reddit.com/r/revancedapp/comments/yr9art/error_when_i_try_to_update/

### Steps to reproduce

.

### Android version

12

### Manager version

0.0.39

### Target package name

Youtube

### Target package version.

any version newer than the installed one.

### Installation type

Non-root

### Patches selected.

All patches excluding Debugging

### Device logs (exported using Manager settings).

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by trmdi** [comment]
I know there will be a feature that let the user import/export the keystore, but that would be a bad experience. It should work out of the box.

**Comment by trmdi** [comment]
My guess: is the valid days of certification too short?
Can you set it to forever?

![Screenshot_2022-11-09-10-27-57-135_sk styk martin apkanalyzer](https://user-images.githubusercontent.com/11857205/200731252-b6359628-f5b0-4801-9e9c-dae75a1dd681.jpg)

**Comment by Rafii2198** [comment]
I am one of those that can't update apps, but weird thing is that I could do it before, like a week after manager was released I installed YouTube like 3 times because I was testing patches but now it just says "App was not installed".
Is it an issue with manager or did I break something?

**Comment by trmdi** [comment]
> I am one of those that can't update apps, but weird thing is that I could do it before, like a week after manager was released I installed YouTube like 3 times because I was testing patches but now it just says "App was not installed". Is it an issue with manager or did I break something?

Somehow Revance Manager lost its keystore and have to generate a new one, so you can't update it.

**Comment by ILoveOpenSourceApplications** [comment]
Does come under #494 in a manner right?
