### ISSUE TITLE
feat: encourage to reinstall instead of updating, on signature missmatch

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#494]
### Type

Functionality

### Issue

If an app is installed with a different signature, updating with the patched app will fail.

### Feature

Android PM can install an app instead of updating (similar to what Play Store does to update apps despite different signatures). If the signatures miss-match, the manager should suggest to install the app instead of updating.

### Motivation

This will get rid of package conflicts.

### Additional context

It should be investigated, if installing deletes the data of the existing app installation in contrast to an update, if so, this should be explained to the user, in case they do not want to proceed the installation.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by validcube** [comment]
💫 Closing this as it has been completed in #1528
