### ISSUE TITLE
feat: Option to keep system font

### ISSUE THREAD

**Issue by xerta555** [ReVanced/revanced-manager#502]
### Type

Functionality

### Issue

ReVanced app use custom font

### Feature

Please add an option to keep system font

### Motivation

If the users want, they would enable the option and the app would keep the system font.
In this way, if a user use a custom font which break the app display, he will just have to delete app's data to get it works again.

With this option, all users will be happy.

### Additional context

Users who install custom fonts are aware of this, so if their custom font has a problem, they will know what to do about it.

The fact that a font is forced by the application itself is very annoying, at least leaving the choice to the users seems to be the best idea.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by ILoveOpenSourceApplications** [comment]
Is this feature request actually attainable?

**Comment by oSumAtrIX** [comment]
Should be. But it's quite irrelevant.

**Comment by ILoveOpenSourceApplications** [comment]
I guess since it's a feature request it depends on y'all developers to decide to keep it open or not.

**Comment by xerta555** [comment]
I thought adding an option to keep the system default font instead of an imposed font was so complicated.
I have the impression that the problem is more at the decision level than at the technical level.

**Comment by oSumAtrIX** [comment]
ReVanced Manager will soon be released as [a full rewrite](https://github.com/ReVanced/revanced-manager/tree/compose-dev). Over time, many feature requests have been made for the current version of ReVanced Manager, but to accelerate the development of the new version of ReVanced Manager, we have to focus on it, which I am closing this issue according to the [contribution guidelines](https://github.com/ReVanced/revanced-manager/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long/ Low priority/ Maintainers un-interested/ Too complex to realize
- Feature planned/ already implemented for the new version of ReVanced Manager

Regardless, anyone who comes across this feature request can PR it to the current version of ReVanced Manager until the new version is ready. Thanks for your feature request!
