### ISSUE TITLE
YouTube Revanced opening issue

### ISSUE THREAD

**Issue by NishantDangi** [revanced/revanced-manager#503]
### Type

Error at runtime

### Bug description

After clicking on Patch this issue shows up and after clicking on ok, and install YouTube Revanced is not opening and just logo pops up and app exits.
![Screenshot_2022-11-12-12-53-18-08_a85b47aaa863e3bc831e16d29c27a79c](https://user-images.githubusercontent.com/97536873/201462732-7826f9c3-fc15-407b-8eb7-702a71c98114.jpg)

### Steps to reproduce

Step 1. Open manager
Step 2. Select youtube under application to patch
Step 3. Apply patches
Step 4. Click on patch
Step 5. A warning pops up click on ok
Step 6. After some operations click on install

### Android version

Android 12

### Manager version

0.0.40

### Target package name

com.google.android.youtube

### Target package version.

17.43.36

### Installation type

Non-root

### Patches selected.

Selected patches (19)

Disable Startup Shorts Player (v0.0.1)

Sponsorblock (v0.0.1) Disable Auto Captions (v0.0.1)

Return Youtube Dislike (v0.0.1) Custom Branding (v0.0.1)

Premium Heading (v0.0.1)

General Ads (v0.0.1)

Video Ads (v0.0.1)

Swipe Controls (v0.0.3)

Downloads (v0.0.1)

Seekbar Tapping (v0.0.1)

Open Links Directly (v0.0.1)

MicroG Support (v0.0.1)

Client Spoof (v0.0.1) Debugging (v0.0.1)

Minimized Playback (v0.0.1) Custom Video Speed (v0.0.1)

Remember Video Quality (v0.0.1)

Hdr Auto Brightness (v0.0.2)

### Device logs (exported using Manager settings).

```shell
NA
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by NishantDangi** [comment]
--------- beginning of system
11-12 12:58:56.136 12724 12724 I Quality : Skipped: false 3 cost 39.02048 refreshRate 0 processName app.revanced.manager.flutter
11-12 12:58:56.183 12724 12724 I Quality : Skipped: false 1 cost 19.0258 refreshRate 0 processName app.revanced.manager.flutter
11-12 12:59:58.810 12724 12724 I Quality : Skipped: false 3 cost 34.34287 refreshRate 0 processName app.revanced.manager.flutter
11-12 12:59:58.883 12724 12724 I Quality : Skipped: false 3 cost 39.835506 refreshRate 0 processName app.revanced.manager.flutter
11-12 13:00:48.329 12724 12724 I Quality : Skipped: false 2 cost 26.342976 refreshRate 0 processName app.revanced.manager.flutter
11-12 13:01:13.558 12724 12724 I Quality : Skipped: false 1 cost 21.201223 refreshRate 0 processName app.revanced.manager.flutter
11-12 13:01:13.631 12724 12724 I Quality : Skipped: false 2 cost 26.837631 refreshRate 0 processName app.revanced.manager.flutter
11-12 13:01:35.698 12724 12724 I Quality : Skipped: false 2 cost 28.322245 refreshRate 0 processName app.revanced.manager.flutter
11-12 13:02:46.596 12724 12724 I Quality : Skipped: false 1 cost 29.066605 refreshRate 0 processName app.revanced.manager.flutter
--------- beginning of main
11-12 13:03:29.035 12724 12724 I BufferQueueConsumer: [](id:31b400000014,api:0,p:-1,c:12724) connect: controlledByApp=false
11-12 13:03:29.036 12724 12724 I BLASTBufferQueue: [ViewRootImpl[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#20] constructor()
11-12 13:03:29.037 12724 12747 I BufferQueueProducer: [ViewRootImpl[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#20(BLAST Consumer)20](id:31b400000014,api:1,p:12724,c:12724) connect: api=1 producerControlledByApp=true
11-12 13:03:29.040 12724 12724 I BufferQueueConsumer: [](id:31b400000015,api:0,p:-1,c:12724) connect: controlledByApp=false
11-12 13:03:29.040 12724 12724 I BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#21] constructor()
11-12 13:03:29.041 12724 12753 I BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#21(BLAST Consumer)21](id:31b400000015,api:1,p:12724,c:12724) connect: api=1 producerControlledByApp=true
11-12 13:03:29.063 12724 12780 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
11-12 13:03:29.069 12724 12856 I OpenGLRenderer: Davey! duration=135523ms; Flags=1, FrameTimelineVsyncId=42166360, IntendedVsync=542971651988447, Vsync=542971663099558, InputEventId=314535483, HandleInputStart=542971673337670, AnimationStart=542971673339824, PerformTraversalsStart=542971673340747, DrawStart=542971735680131, FrameDeadline=542971683099558, FrameInterval=542971673189670, FrameStartTime=11111111, SyncQueued=542971735878670, SyncStart=542971736072131, IssueDrawCommandsStart=542971736170901, SwapBuffers=542971742201670, FrameCompleted=543107175340524, DequeueBufferDuration=1235770, QueueBufferDuration=1031384, GpuCompleted=543107175340524, SwapBuffersCompleted=542971745454670, DisplayPresentTime=0,
11-12 13:03:29.088 12724 12856 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
11-12 13:03:29.742 12724 12724 V AutofillManager: requestHideFillUi(null): anchor = null
11-12 13:03:29.870 12724 13085 E BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#21](f:0,a:2) isEGL=1, mPendingRelease.size()=1, mMaxAcquiredBuffers=4, currentMaxAcquiredBufferCount=2

**Comment by TroubleDog54** [comment]
I'm not an expert, so take my word with a grain of salt, but I'm pretty sure you have downloaded a bundle apk. Revanced only supports single apks, so you can't patch with them. I've attached an image below, see how there is two apks, one labelled "bundle"? This means that the apk is split across multiple packages, and isn't in one apk file. Try downloading the regular "apk 24bb" and see if it works. Sorry if this isn't any help. 
![image](https://user-images.githubusercontent.com/115918107/201464935-d64175c1-eee8-4ecf-917a-2f7bd079dac8.png)

**Comment by Canny1913** [comment]
The log you sent doesn't contain anything useful.

**Comment by NishantDangi** [comment]
Thanks for the help @TroubleDog54 my issue is resolved.
