### ISSUE TITLE
bug: Use different icons for Youtube Revanced and Revanced Manager

### ISSUE THREAD

**Issue by trmdi** [revanced/revanced-manager#504]
![image](https://user-images.githubusercontent.com/11857205/225191190-480b1581-07c0-4e8c-9fef-3b2765711f1f.png)

We should use a different icon for the Manager to distingush Youtube Revanced and RM.

**Comment by trmdi** [comment]
@kazimmt

**Comment by kazimmt** [comment]
> @kazimmt

Added to my to-do list
I'll leave a PR soon

**Comment by ILoveOpenSourceApplications** [comment]
Isn't this acknowledged and fixed with one of the recent releases?

**Comment by trmdi** [comment]
@ILoveOpenSourceApplications 
#505 is still opened and the icon of Revanced Manager in the newest release 0.0.56 is still low quality.

**Comment by ILoveOpenSourceApplications** [comment]
I've reopened it.

**Comment by trmdi** [comment]
> Issue was fixed with [dc665f2](https://github.com/revanced/revanced-manager/commit/dc665f227e58bfe310bdedb3c8ca674b34a6be26)

Now I think we should use different icons for different apps to distingush them better.

**Comment by kazimmt** [comment]
> Now I think we should use different icons for different apps to distingush them better.

That's a different topic.
Wait for logo poll.

**Comment by oSumAtrIX** [comment]
The logos are decided by the [branding guidelines](https://github.com/revanced/revanced-branding).
