### ISSUE TITLE
bug: ads showing

### ISSUE THREAD

**Issue by rejuanad99** [revanced/revanced-manager#506]
### Type

Cosmetic

### Bug description

![Screenshot_2022-11-12-21-09-13-74_64ef5fc2000c1caa954c114bb372e1d5](https://user-images.githubusercontent.com/49226370/201495499-dca21a81-57d9-4a2d-839b-8cf0e909d76f.jpg)
I'm seeing ads from yesterday, just like in the picture.

### Steps to reproduce

It just show ads every now and again.

### Android version

Android 12

### Manager version

0.0.40

### Target package name

Youtube revanced

### Target package version.

17.43.36

### Installation type

Non-root

### Patches selected.

All

### Device logs (exported using Manager settings).

```shell
content://app.revanced.manager.flutter.shareextend.fileprovider/%252Fdata%252Fuser%252F0%252Fapp.revanced.manager.flutter%252Fcache%252Flogs%252Frevanced-manager_logcat_20221112224059740297.log
```

### Screenshots or videos

![Screenshot_2022-11-12-21-09-13-74_64ef5fc2000c1caa954c114bb372e1d5](https://user-images.githubusercontent.com/49226370/201495676-aec0c2f3-0feb-41bb-b5ab-2fb68014448e.jpg)

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
This issue belongs to the [ReVanced Patches](https://github.com/revanced/revanced-patches) repository

**Comment by rejuanad99** [comment]
> This issue belongs to the [ReVanced Patches](https://github.com/revanced/revanced-patches) repository

Thanks
