### ISSUE TITLE
feat: Add installation type on Patcher

### ISSUE THREAD

**Issue by kazimmt** [revanced/revanced-manager#507]
### Type

Functionality

### Issue

Confused which patch should we select & what not (new users)

### Feature

Add installation type on Patcher, so user can select root installation or non-root from patcher page.

- If someone select root installation, microg-support will not show on patch selection page.

- If someone select non-root installation, microg-support will automatic selected. & Users can't unselect it.

& if anyone select root-installation, he'll not be able to select YouTube / YouTube music from storage.

![manager-screenshot](https://user-images.githubusercontent.com/82371061/201522480-4bab1cce-cc45-4cf6-baba-ffa56a743225.jpg)

### Motivation

It'll fix some confusion for new users.
I've seen many post on telegram & discord,, people select microg & try to install as root. 
Then they failed,,, They need to patch full app again. (Time killing)
If we select installation type first (As we did it on Vanced), i'll save valuable times for many users.

### Additional context

Thank you for everything.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Added in https://github.com/revanced/revanced-manager/commit/74e0c09b543fe70b70cd917e6e21ceb0f46f3533.
