### ISSUE TITLE
feat: other languages.

### ISSUE THREAD

**Issue by dark-caster** [revanced/revanced-manager#511]
### Type

Cosmetic

### Issue

I would like to suggest that it is possible to translate the functions of Revanced Manager and Revanced YouTube to the device language.

### Feature

All default YouTube settings are in the device language, I would suggest that the advanced settings in revanced also follow the device language.

### Motivation

Anyone who doesn't understand English can easily configure revanced.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Not a manager issue.
