### ISSUE TITLE
feat: <Revanced app - Choose specific video quality>

### ISSUE THREAD

**Issue by saver711** [revanced/revanced-manager#516]
### Type

Other

### Issue

No issues 

### Feature

![Screenshot_2022-11-16-03-25-59-214_com vanced android youtube](https://user-images.githubusercontent.com/28202010/202060576-74fab20a-7e09-4664-9f0e-b3ce01e68157.jpg)

### Motivation

So that the video quality still static till i change it

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by saver711** [comment]
@oSumAtrIX can u at least say something?

**Comment by Ushie** [comment]
> @oSumAtrIX can u at least say something?

acknowledgements aren't met
