### ISSUE TITLE
bug: <Revanced app - video doesn't continue where from i left it>

### ISSUE THREAD

**Issue by saver711** [revanced/revanced-manager#517]
### Type

Error at runtime

### Bug description

video doesn't continue where from i left it
It starts to play from start again

### Steps to reproduce

Null

### Android version

9

### Manager version

It is Revanced app, not manager

### Target package name

Revanced app 

### Target package version.

Latest

### Installation type

Non-root

### Patches selected.

Null

### Device logs (exported using Manager settings).

```shell
Null
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by TroubleDog54** [comment]
Is the video appearing in your YouTube history?

**Comment by saver711** [comment]
@TroubleDog54 
Yes
@oSumAtrIX 
Why did u closed it as completed?

**Comment by Canny1913** [comment]
Acknowledgements are not met.

**Comment by Canny1913** [comment]
> @Canny1913 Is video screen record enough to show the issue? I can do that

The issue you're having is not related to manager.

**Comment by saver711** [comment]
@Canny1913 
I couldn't find a repo for the Revanced YT app
Where do u recommend to declare my issue?

**Comment by Canny1913** [comment]
> @Canny1913 I couldn't find a repo for the Revanced YT app Where do u recommend to declare my issue?

revanced-patches

**Comment by saver711** [comment]
Thanks man
