### ISSUE TITLE
MicroG

### ISSUE THREAD

**Issue by Nizami20052022** [revanced/revanced-manager#518]
### Type

Other

### Issue

Check out the project https://github.com/inotia00/VancedMicroG
 This project is an updated version of MicroG.

### Feature

The developer of this project is updating MicroG.It is necessary to support them.

### Motivation

MicroG updates are needed.

### Additional context

The app is released compatible with ReVanced. MicroG updates are essential.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Some commits obfuscate the history & releases are created by hand. There is no need to update Vanced MicroG yet.
