### ISSUE TITLE
Hi, I can help you build an application similar to ReVanced Manager

### ISSUE THREAD

**Issue by kakathic** [revanced/revanced-manager#52]
Looks like you are having problems with the ReVanced Manager application

 I can help you build a ReVanced Manager that can build apk or apks files

 I need about few hours to make arm64 based app and if you guys agree I can fully support phone models.

 I make it completely free without asking for anything

 It works based on jdk 17 or jdk 18

 I can help you because I'm your crazy fan :))

**Comment by Aunali321** [comment]
We're are not having any issues. Also manager shouldn't rely on any jdk. Relying on jdk means you are wrapping cli which shouldn't be done for manager. Manager will use patcher directly without needing any jdk.

**Comment by kakathic** [comment]
> We're are not having any issues. Also manager shouldn't rely on any jdk. Relying on jdk means you are wrapping cli which shouldn't be done for manager. Manager will use patcher directly without needing any jdk.

I look forward to the release date of the revanced manager .
