### ISSUE TITLE
feat: Create folders for patches 

### ISSUE THREAD

**Issue by Mrgaton** [revanced/revanced-manager#522]
### Type

Cosmetic

### Issue

Upgrade the patches selector 

### Feature

When I was patching YouTube I see a lot of hide x thing patches and I get the idea to make folders to select the patches because is little messy all now 

### Motivation

Idk 😐

### Additional context

Hi..

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Manager by design doesnt know which patches are in patch bundle. So we cannot categorize patches without hardcoding. We avoid hardcoding as much as possible to be able to support patch bundles of other devs.
