### ISSUE TITLE
Android 13, rooted method, not working

### ISSUE THREAD

**Issue by joihn** [revanced/revanced-manager#523]
### Type

Error at runtime

### Bug description

**summary**
install process goes without any problem, but ads are still there

### Steps to reproduce

**to reproduce:**
1. uninstall youtube update via Gplay
2. reboot
3. install recommend version (apk from apkmirror) 
https://www.apkmirror.com/apk/google-inc/youtube/youtube-17-43-36-release/youtube-17-43-36-2-android-apk-download/
4. select the 2 patch against ads
5. install via root method 
6. ads are still there

### Android version

android 13

### Manager version

0.0.40

### Target package name

Youtube
https://www.apkmirror.com/apk/google-inc/youtube/youtube-17-43-36-release/youtube-17-43-36-2-android-apk-download/

### Target package version.

17-43-36

### Installation type

Root

### Patches selected.

General Ads, video ads

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing all patches
Executing 'locale-config-fix' of type: resource
Executing 'integrations' of type: bytecode
Executing 'Class' of type: bytecode
general-ads failed.
Error:
kotlin.Unit
Skipping 'integrations' because it has already been applied
Skipping 'integrations' because it has already been applied
Skipping 'locale-config-fix' because it has already been applied
Executing 'resource-mapping' of type: resource
Executing 'settings-resource-patch' of type: resource
Executing 'settings' of type: bytecode
Skipping 'integrations' because it has already been applied
Skipping 'integrations' because it has already been applied
Executing 'video-information' of type: bytecode
Skipping 'settings' because it has already been applied
Skipping 'integrations' because it has already been applied
Executing 'video-id-hook' of type: bytecode
Executing 'fix-playback' of type: resource
Executing 'video-ads' of type: bytecode
Applied video-ads
Skipping 'settings' because it has already been applied
Applied settings
Repacking patched apk
Compiling resources
Creating new dex file
Writing modified dex files
Finished!
Installing patched file using root method
Installed!
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
this belongs to the [revanced-patches](https://github.com/revanced/revanced-patches)

**Comment by Canny1913** [comment]
This issue is already fixed. Please update patches and try again.

**Comment by joihn** [comment]
thanks for the quick answer, 
I'm using latest manager, doesn't that imply latest patch ?
how can I manually update them ?

**Comment by joihn** [comment]
solved,
Manager > Settings > enable experimental patches
Restart manager and patch with 2.111.3. That fixed it for me

Thanks for this repo
