### ISSUE TITLE
bug: The patch version is not showing well

### ISSUE THREAD

**Issue by jiyongwoo** [revanced/revanced-manager#525]
### Type

Cosmetic

### Bug description

The patch version is not showing well. It is partially covered.

### Steps to reproduce

In android settings, select a large font.

### Android version

12

### Manager version

0.0.40

### Target package name

.

### Target package version.

2.114.2

### Installation type

Non-root

### Patches selected.

.

### Device logs (exported using Manager settings).

```shell
.
```

### Screenshots or videos

![Screenshot_2022-11-21-12-41-30-782-edit_app revanced manager flutter~2](https://user-images.githubusercontent.com/41583431/202962864-fd934533-7b12-4565-b9cc-bc821b5080e4.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by MinionAttack** [comment]
In my case no number appears and the coloured background shrinks to the minimum width.

**Comment by ILoveOpenSourceApplications** [comment]
This has been fixed with the recent version. Can be closed.
