### ISSUE TITLE
bug: Manager Update keep asking for an update

### ISSUE THREAD

**Issue by JanWaldhorn** [revanced/revanced-manager#529]
### Type

Other

### Bug description

After update to v0.0.41 the manager still wants to update.

### Steps to reproduce

open app an select update. 

### Android version

13, Pixel 6

### Manager version

v0.0.4 -> v0.0.41

### Target package name

None

### Target package version.

None

### Installation type

Non-root

### Patches selected.

None

### Device logs (exported using Manager settings).

```shell
None
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
None
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by ultraboost** [comment]
Same here. The sideloaded APK and update manager shows version 0.0.40 even after updating. Tried uninstalling and reinstalling too.

**Comment by maj113** [comment]
Same issue here, app still shows 0.0.40
