### ISSUE TITLE
System theme.

### ISSUE THREAD

**Issue by ghost** [ReVanced/revanced-manager#532]
### Type

Cosmetic

### Issue

The app should automatically use the system theme.

### Feature

ReVanced Manager uses a system theme.
![Screenshot_20221124-103351_Vanced Manager](https://user-images.githubusercontent.com/112704336/203711076-8a2dfeaa-bce3-4591-9ba0-0196b6bf3962.jpg)

### Motivation

I think it's a good feature.

### Additional context

No

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by bagarwa** [comment]
Not only just the Light or Dark theme; but it'd be cool if the app can use Material You theme. (i.e. Monet)

**Comment by Ushie** [comment]
#532

**Comment by ILoveOpenSourceAppications** [comment]
> #532

Did you mean #276 ?

**Comment by Ushie** [comment]
> > #532
> 
> Did you mean #276 ?

Yes, edited thanks

**Comment by validcube** [comment]
Already fixed
