### ISSUE TITLE
Accent color.

### ISSUE THREAD

**Issue by Fertanima** [revanced/revanced-manager#533]
### Type

Cosmetic

### Issue

Option to change the accent color.

### Feature

Ability to better customize ReVanced Manager.

### Motivation

I dont know.

### Additional context

![Screenshot_20221124-103329_Vanced Manager](https://user-images.githubusercontent.com/112704336/203711566-48df86d9-0a98-425a-954a-f62faf15d3af.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Not planned. Manager already has light/dark and material you dark/light. Anything more than that use unnecessary for manager. It's not something you would use for hours.
