### ISSUE TITLE
feat: language repo

### ISSUE THREAD

**Issue by nguyentumine** [ReVanced/revanced-manager#534]
### Type

Functionality

### Issue

No.

### Feature

An option to import strings from an external source such as a JSON file on a github repository. 

youtube/values/strings.xml:
`<string name="revanced_action_button_off">Buttons are shown</string>`

```
{
	"locale": "vi",
	"packages":
	{
		"package": "com.google.android.youtube",
		"strings":
		{
			"revanced_action_button_off": "Buttons are shown"
		}
	}
}
```
If the key is added to **values/strings.xm**l, then this key and the translated value are also added to **values-{locale}/strings.xml** (if exists).

### Motivation

This makes it easy for the local community to publish their own translations.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by CennoxX** [comment]
We use Crowdin to translate ReVanced (https://de.crowdin.com/project/revanced)

**Comment by Ushie** [comment]
This is an issue for the ReVanced Patches repository, and likely very difficult to achieve
