### ISSUE TITLE
bug: There was a problem parsing the package.

### ISSUE THREAD

**Issue by daf0x** [revanced/revanced-manager#538]
### Type

Other

### Bug description

When I try to install the .apk I get an error message that say "There was a problem parsing the package.". I tried to download the release several times, but the problem remains.

### Steps to reproduce

1. download apk from https://github.com/revanced/revanced-manager/releases/download/v0.0.41/revanced-manager-v0.0.41.apk
2. try to install apk
3. error message instead of app installing

### Android version

Android 7.1.1 Nougat

### Manager version

https://github.com/revanced/revanced-manager/releases/tag/v0.0.41

### Target package name

n/a

### Target package version.

n/a

### Installation type

Non-root

### Patches selected.

n/a

### Device logs (exported using Manager settings).

```shell
n/a
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
n/a
```

### Screenshots or videos

n/a

### Solution

The package should install without errors.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Canny1913** [comment]
Manager is not supported for below A8.
