### ISSUE TITLE
feat: Restore "Root Script Sleep Time" from Vanced Manager

### ISSUE THREAD

**Issue by blackwind** [ReVanced/revanced-manager#540]
### Type

Functionality

### Issue

On Reddit and elsewhere, you'll note that many users complain of root ReVanced reverting to stock YouTube on every reboot. This is because older, slower phones require a longer delay before mounting the modified APK.

### Feature

To combat this, Vanced Manager offered a setting called "Root Script Sleep Time", which "adjusts sleep time value used in /data/adb/service.d/app.sh script, useful for fixing mounting issues". On my older phone, I configured a 15s sleep for Vanced and never ever had a problem. ReVanced has the same issue in its default state and disappears on reboot every single time on my older phone, until I manually added an extra "sleep 15" to the service.d script. Now, it persists after reboot every time, just as Vanced did.

### Motivation

For the benefit of those on older, slower phones, this setting needs to be added to ReVanced Manager.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
ReVanced Manager will soon be released as [a full rewrite](https://github.com/ReVanced/revanced-manager/tree/compose-dev). Over time, many feature requests have been made for the current version of ReVanced Manager, but to accelerate the development of the new version of ReVanced Manager, we have to focus on it, which I am closing this issue according to the [contribution guidelines](https://github.com/ReVanced/revanced-manager/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long/ Low priority/ Maintainers un-interested/ Too complex to realize
- Feature planned/ already implemented for the new version of ReVanced Manager

Regardless, anyone who comes across this feature request can PR it to the current version of ReVanced Manager until the new version is ready. Thanks for your feature request!
