### ISSUE TITLE
feat: New Features?

### ISSUE THREAD

**Issue by kevinr99089** [revanced/revanced-manager#542]
### Type

Functionality

### Issue

I don't know if I'm in the right room, but do you plan to add the possibility to add Enchancer for Youtube features (and/or) the possibility to whitelist a channel for ads via a button in the like/dislike, share, download bar, like on Youtube Vanced?
![Screenshot_20221126_162220](https://user-images.githubusercontent.com/93716347/204096631-7bdf1ede-b009-4ce9-ae68-c635efb8d5a2.png)
![Screenshot_20221126_162241](https://user-images.githubusercontent.com/93716347/204096633-f6ca995d-bb62-4036-ab5e-9e4234f22506.png)

### Feature

There is not problems, just to support the creators I wish to

### Motivation

To help content creators by watching ads, This request is not only for me, but especially for content creators

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by CennoxX** [comment]
Please always set a meaningful title. 
The correct place for requests like that would probably be https://github.com/revanced/revanced-patches
