### ISSUE TITLE
bug: heavy load on api

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#545]
### Type

Error while running the manager

### Bug description

The ReVanced Manager hits the API multiple times when not necessary. Relevant code is used in multiple places:
https://github.com/revanced/revanced-manager/blob/f1261398e927903f6c75c44f5d03fdff562bda47/lib/services/revanced_api.dart#L83-L100

### Screenshots or videos

[All of these call the API each time](https://github.com/revanced/revanced-manager/blob/0faf86c9e949f82e8fdc6e33ae561cc5cca5b42f/lib/services/manager_api.dart):
![image](https://user-images.githubusercontent.com/13122796/204113521-fc920ddc-3332-4821-8ac4-5c9c73b5d7f3.png)

### Solution

Instead of hitting the API multiple times, it is only necessary to do so once and then read the fields from the parsed model.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by rootback123** [comment]
that must be why the app doesn't open if offline, right? and I also wanted to ask if the application can work in the future without any connection, of course, except for updating. Thank you

**Comment by Ushie** [comment]
> that must be why the app doesn't open if offline, right? 

Yes

**Comment by Ushie** [comment]
Closing as ReVanced API is fine with burst-requests and dio_cache_interceptor is now being used to cache responses anyways
