### ISSUE TITLE
bug: YouTube v17.46.37 crashes on launch

### ISSUE THREAD

**Issue by TurtleIdiot** [revanced/revanced-manager#550]
### Type

Error at runtime

### Bug description

YouTube crashes on launch after patching and installing with root

While v17.46.37 is not supported, I believe this version should work after a quick patch, explained by the Logs and possible solution fields

### Steps to reproduce

1. Download latest YouTube app from the play store (currently v17.46.37)
2. Enable experimental patches
3. Patch YouTube (I have only applied General Ads and Video Ads)
4. Install as Root
5. Open

### Android version

Android 13.0 (crDroid 9.0 custom ROM)
Using MicroG 0.2.25.223616 instead of Google Play Services

### Manager version

0.0.42

### Target package name

com.google.android.youtube

### Target package version.

v17.46.37

### Installation type

Root

### Patches selected.

- General Ads
- Video Ads

### Device logs (exported using Manager settings).

```shell
Error collected from system logs using logcat:

11-28 13:42:25.186 E/ErrorLoggingExecutor(31751): com.google.android.gms.common.GooglePlayServicesIncorrectManifestValueException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 224700000 but found 224400000.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
```

### Solution

Judging from the logcat output, this should be possible to solve by having revanced manager write the correct version to AndroidManifest.xml (in this case 224700000)

If i'm going to guess what went wrong here, I *think* revanced manager wrote the version of the latest supported version (17.43.36) instead of the version being patched (17.46.37)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by TurtleIdiot** [comment]
I will use apktool to try and edit the manifest and repack the app to see if this is the issue

**Comment by Ushie** [comment]
closing due to acknowledgements not being met, this issue is unrelated to ReVanced Manager, this issue belongs to the [ReVanced Patches repository](https://github.com/revanced/revanced-patches).

P.S. please use recommended/supported versions, if the issue occurs when patching a recommended version that's when an issue should be created, issues created due to the user themselves ignoring the recommended/supported version will likely be ignored.
