### ISSUE TITLE
bug: Remove Debugging patch from the Recommend list

### ISSUE THREAD

**Issue by trmdi** [revanced/revanced-manager#553]
### Type

Other

### Bug description

The Debugging patch is known to slow down Youtube Revanced, so it should be removed from the Recommend patch list.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
It does not slow down unless you explicitely change the patch option to enable app debugging to true which is not yet possible on the manager.
