### ISSUE TITLE
Add the 'load patchs selection' to the tiles feat: <title>

### ISSUE THREAD

**Issue by praveenpkallambalam** [revanced/revanced-manager#554]
### Type

Functionality

### Issue

Currently the load patches selection is under a sub menu.
![Screenshot_20221130-104124_ReVanced Manager](https://user-images.githubusercontent.com/71561106/204713331-4785a283-ac7b-4e0a-848f-e1f15f85127c.png)

### Feature

Is it possible to add this option next to recommended, all and none tiles.!? By doing that all options will be closer and easy to find.

### Motivation

It will help newbies like me in future.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
That section is for chips not buttons. Also you don't have to click load patches button everytime. Manager auto remembers it. It's only used when you reinstall manager and need to use exported json file from before.

**Comment by praveenpkallambalam** [comment]
Patches selection is not retaining on my device .I think it might be a bug in my device. I will try a clean install.
