### ISSUE TITLE
bug: Wrong renaming of exported apk if there is already an apk with the same name.

### ISSUE THREAD

**Issue by d3EyedRaven** [revanced/revanced-manager#559]
### Type

Other

### Bug description

saving apk in same folder and with same name, saves apk with changed extension instead of , rendering apk useless.
on personal level, issue can be fixed by simple renaming.

example:
should save second export as
youtube-revanced_v17.45.36 1.apk
currently saves second export as : youtube-revanced_v17.45.36.apk 1

### Steps to reproduce

1: export the apk after patching. save it in file manager (in my case mixplorer) with default naming "youtube-revanced_v17.45.36.apk"

2: patch youtube again with different patches, export again in the same folder as previously exported apk. and same name. it does not ask to change name or whether to replace old file.

3: instead it renames to "youtube-revanced_v17.45.36.apk 1" which renders apk useless due to the wrong extention. however a simple rename solve sthe issue.
it should be asking if to replace the old file or rename the filename, not with the extention.

### Relevant log output

```shell
none
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
This still exists and needs to be looked into.
