### ISSUE TITLE
Export keystore

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-manager#563]
### Type

Functionality

### Issue

When reverting to previous versions of the manager you will need to delete the app and then install the old version again, thus deleting the Keystore. 
People who are migrating between phones might not have the original Keystore moved as well, so they will have to delete patched apps to update again, losing all configs
On rare cases where the Keystore was lost/deleted for whatever reason, this could serve as a backup to not lose the  Keystore

### Feature

Under "Import & Export", allow the keystore to be imported/exported with/without a password

### Motivation

Solves issues mentioned above in the Issue section

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by SodaWithoutSparkles** [comment]
It seems that the branch custom-keystore is here but has gone stale for 2 months. Doesn't it have a PR associated?

**Comment by Issam28** [comment]
Yeah this would be great. It's the only reason preventing me from using the manager as of now. Having the ability to import Keystores would be great.

**Comment by GuyInCanada** [comment]
This would be great. I use Revanced-Builder (reisxd/revanced-builder) and keep a copy of revanced.keystore on OneDrive.

**Comment by SodaWithoutSparkles** [comment]
https://www.reddit.com/r/revancedapp/comments/105rqat/exporting_the_keystore/?utm_term=1

**Comment by Tasin5541** [comment]
I had to clear the app data to fix compiling errors on 2 occasions. This feature would be a great addition

**Comment by Aunali321** [comment]
Added in https://github.com/revanced/revanced-manager/commit/dca2d4fe126a6966a094d335e0f27bb62d76c5e8
