### ISSUE TITLE
Change the name of the manager.

### ISSUE THREAD

**Issue by Dertyiula** [revanced/revanced-manager#564]
### Type

Cosmetic

### Issue

You need to change the manager's name.Because the manager is not only designed for ReVanced.Name the application Android Manager.

### Feature

It is incorrect to name the manager ReVanced.

### Motivation

Don't let anyone know it's ReVanced.

### Additional context

The application can also be named Android Patcher.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by SlyPredator** [comment]
ReVanced is app-agnostic, meaning the name/patches within it does not apply to any one app alone. Hence there's no need to "hide" the name ReVanced.

**Comment by Canny1913** [comment]
> Don't let anyone know it's ReVanced.

Why?
> It is incorrect to name the manager ReVanced.

Why?
> Because the manager is not only designed for ReVanced.

Not a valid reason. Manager is designed for utilizing ReVanced patcher in a user friendly way.
>Name the application Android Manager.

No. Doesn't make sense.
