### ISSUE TITLE
bug: No patched applications installed shown

### ISSUE THREAD

**Issue by DarkSkull91** [revanced/revanced-manager#565]
### Type

Error while running the manager

### Bug description

In the Dashboard section, under the installed patched applications there are nothing even if I have patched both Youtube and Twitter.

### Steps to reproduce

1. Open the vanced manager
2. See that in the installed section under patched application you have the message: "No patched applications installed"

### Android version

Android 12.1

### Manager version

0.0.44

### Target package name

com.google.android.youtube
com.twitter.android

### Target package version.

Youtube 17.45.36
Twitter 9.65.6-release.0

### Installation type

Root

### Patches selected.

All

### Device logs (exported using Manager settings).

```shell
N/A
```

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by SodaWithoutSparkles** [comment]
1. Its revanced manager
2. This is a known issue.

**Comment by PalmDevs** [comment]
This is caused by the update functionality being disabled.
@Aunali321 You might want to enable it back, or just remove it completely for now.

**Comment by SodaWithoutSparkles** [comment]
@PalmDevs can this be re-enabled without first fixing the spilt-apk patch issue?

**Comment by PalmDevs** [comment]
> @PalmDevs can this be re-enabled without first fixing the spilt-apk patch issue?

Of course

**Comment by adanvdo** [comment]
If you re-patch the apk for the app you have installed, but then do not install it, the manager will list it under patched applications again (at least for a couple days...)

**Comment by kenethc** [comment]
ReVanced Manager:

Clear cache 
Clear data

Open app

All good ?

**Comment by SodaWithoutSparkles** [comment]
> ReVanced Manager:
> 
> Clear cache 
> Clear data
> 
> Open app
> 
> All good ? 

1. Dont try this before you backup your keystore, or you wont be able to update and have to delete revanced and re-install
2. Clear data also clears cache

**Comment by kenethc** [comment]
Never had an issue tbh
Not once !

**Comment by ILoveOpenSourceAppications** [comment]
Isn't this related to #674 ?

**Comment by oSumAtrIX** [comment]
Iirc it only shows for mounted apps.

**Comment by ILoveOpenSourceAppications** [comment]
Isn't the OP talking about the patched applications only right?

**Comment by oSumAtrIX** [comment]
Yes, but for regularly patched and installed apps iirc it doesn't show.

**Comment by ILoveOpenSourceAppications** [comment]
What do you mean by mounted and regular apps?

**Comment by SodaWithoutSparkles** [comment]
This has a high chance of being fixed. The logic seems to be correct. Maybe wait for a few days and close this. If so adding a label like "fix: verifying" would be nice. 

Side note: Please also add labels like "fix: WIP", "fix: in next release", "bug: confirmed", "bug: needs confirmation" for easier tracking.

**Comment by SodaWithoutSparkles** [comment]
> Yes, but for regularly patched and installed apps iirc it doesn't show.

Regularly patched does show. 

Confirm that by mounted you mean installed as root? If so regularly patched app now shows. I dont know whats before as I dont have root, but apps are not shown.

**Comment by ILoveOpenSourceAppications** [comment]
> > Yes, but for regularly patched and installed apps iirc it doesn't show.
> 
> Regularly patched does show.
> 
> Confirm that by mounted you mean installed as root? If so regularly patched app now shows. I dont know whats before as I dont have root, but apps are not shown.

Okay, I see the OP had the rooted version. Same as I'm not a rooted user, I can't confirm this issue exists or not. So let it be open then.

**Comment by SodaWithoutSparkles** [comment]
> Okay, I see the OP had the rooted version.

How did you get the conclusion? I didnt see that mentioned.

**Comment by ILoveOpenSourceAppications** [comment]
> ### Installation type
> Root

**Comment by SodaWithoutSparkles** [comment]
> > ### Installation type
> > Root
> 

Ah sorry!

**Comment by ILoveOpenSourceAppications** [comment]
So this is a known issue and can't be closed I guess.

**Comment by Aunali321** [comment]
https://github.com/revanced/revanced-manager/commit/5d63d5c2d3b4f22e9f65384e06a0a31660988816 this is supposed to fix the issue. But it's not tested enough. Code wise everything should work fine now.

**Comment by ILoveOpenSourceAppications** [comment]
> [5d63d5c](https://github.com/revanced/revanced-manager/commit/5d63d5c2d3b4f22e9f65384e06a0a31660988816) this is supposed to fix the issue. But it's not tested enough. Code wise everything should work fine now.

This was pushed during 0.0.55. I believe the "potentially" in the title suggests it requires some more refining as I have raised an issue myself #692 reporting several issues that came with it.

**Comment by Aunali321** [comment]
> I have raised an issue myself #692 reporting several issues that came with it.

Those are different issues. The only issue it is supposed to solve is avoid patched apps disappearing when an "patch update" is available for the patched app. It showing outdated info is different issue.

**Comment by ILoveOpenSourceAppications** [comment]
But as I mentioned in the issues, I am still having no apps installed in my pixel device though.

**Comment by ILoveOpenSourceAppications** [comment]
![Screenshot_20230212-152849~2](https://user-images.githubusercontent.com/117499019/218304463-d594bc8e-13b1-45e3-bba6-a8628568478d.png)
How it is for me right now.

**Comment by kenethc** [comment]
I second this.
Uses to happen to me all the time.

I just cleared data for the Manager and then that would fix the issue.

**Comment by ILoveOpenSourceApplications** [comment]
> I second this. Uses to happen to me all the time. I just cleared data for the Manager and then that would fix the issue.
You my friend are talking about an issue which was present with older version of manager. This fix worked with those older versions, but not anymore.

**Comment by kenethc** [comment]
Ok thanks for the info.

**Comment by DarkSkull91** [comment]
Confirmed that works delete
