### ISSUE TITLE
Auto rotate issue

### ISSUE THREAD

**Issue by Atharkhan101** [revanced/revanced-manager#568]
### Type

Error while running the manager

### Bug description

Sometimes it does not auto rotate. 

### Steps to reproduce

Your phone should be on Auto rotate mode. 
Play a video in portrait mode
Play another video in portrait mode
Hold phone in landscape, some times it plays in full screen mode some times it doesn't very annoying. This was not happening on the YouTube version 17.36.37. 

### Android version

11

### Manager version

0.0.44 and 0.0.42 and 0.0.40 tried all

### Target package name

YouTube

### Target package version.

17.45.36

### Installation type

Root

### Patches selected.

![Screenshot_2022-12-08-23-49-12-039_app revanced manager flutter](https://user-images.githubusercontent.com/20039944/206534581-992cab1f-a334-4c50-adb5-2024eda1623f.jpg)
![Screenshot_2022-12-08-23-49-12-039_app revanced manager flutter](https://user-images.githubusercontent.com/20039944/206534581-992cab1f-a334-4c50-adb5-2024eda1623f.jpg)
![Screenshot_2022-12-08-23-49-12-039_app revanced manager flutter](https://user-images.githubusercontent.com/20039944/206534581-992cab1f-a334-4c50-adb5-2024eda1623f.jpg)

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
12-08 23:50:59.505 16519 16519 D MIUIInput: [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=1421608, downTime=1421608, deviceId=-1, source=0x101, displayId=0 }
12-08 23:50:59.571 16519 16519 D MIUIInput: [KeyEvent] ViewRootImpl KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=1421676, downTime=1421608, deviceId=-1, source=0x101, displayId=0 }
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
Acknowledgements are not met, this issue is unrelated to ReVanced Manager.
