### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by simlu** [revanced/revanced-manager#57]
Please add readme with at least a link to where the docs can be found...

**Comment by Canny1913** [comment]
Manager is not supposed to be built as it's under heavy development.

**Comment by simlu** [comment]
@Canny1913 Would be great to put that into the readme: Purpose, status, etc - Because right now I have a wild guess what this repo is, but don't actually know =)

**Comment by Canny1913** [comment]
sure will add it tomorrow

**Comment by Loup-Garou911XD** [comment]
> sure will add it tomorrow

Hmm 😆
