### ISSUE TITLE
feat: custom sources

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#572]
### Type

Functionality

### Issue

The ReVanced Manager allows to specify a source from GitHub and Co., but thats all.

### Feature

Support custom sources:

Remotes can host a JSON file which contains everything necessary, to add patch bundles:

> **Note**: The JSON will be updated by the remote whenever it supplies new patches.

```json
{
    "patches": { "version": "0.1.0", "url": "https://customsour.ce/revanced-patches-v0.1.0.jar" },
    "integrations": { "version": "0.1.0", "url": "https://customsour.ce/revanced-integrations-v0.1.0.apk" },
}
```

In the ReVanced Manager users can now add the link to the JSON. The ReVanced Manager will download the patches and read (and cache) additional metadata for it such as the `patchBundle.version`. Whenever the user requests to check for updates, the ReVanced Manager checks the JSON from remote against the current `patchBundle.version`. If an update has been found it can prompt the user to update their patches.

### Motivation

Because not everyone can rely on GitHub, adding patches from different sources is adviced.

### Additional context

The implementation is propsed as an example on how the ReVanced Manager can implement this feature. Thus security was not considered. The remote supplies patches and requires the user to download and read the file without providing ways of verifications such as sources, hashes or signs. For that reason, the JSON can simply be furthermore enhanced to fulfill the security requirements. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by griffi-gh** [comment]
Maybe just allow input non-github git servers instead? Sounds simpler to implement if the app already does `git clone`?

**Comment by Ushie** [comment]
The app does not git clone, it uses the releases endpoint in API

**Comment by ILoveOpenSourceApplications** [comment]
@oSumAtrIX #84 can be bundled together with this feature request right?

**Comment by TeaEndsAcronyms** [comment]
seems that custom websites api feature has been added in the latest pre-release! (if im not mistaken.)

**Comment by Ushie** [comment]
technically, but it's very limited, it only works if the API is similar/same to that of github, this issue aims for a universal solution

**Comment by Ushie** [comment]
How is this supposed to function from a CI perspective?

**Comment by Axelen123** [comment]
Why was the ReVanced Manager Compose tag added? Compose manager already has this.
The json format used by compose manager is not very complicated. You should be able to generate it using CI without any issues.

**Comment by Ushie** [comment]
Because this feature is only planned for ReVanced Manager Compose, but how would the CI flow go? release to github releases then commit to main to update the links? so it'll be a file in main?

**Comment by Ushie** [comment]
Where should this issue be opened for the CI/API implementation? there currently has been no talks of implementing it after support in ReVanced Manager was added

**Comment by Axelen123** [comment]
Bundle maintainers are free to implement it however they like. An example CI workflow would make sense in a patch bundle template/example repo.

**Comment by alexandreteles** [comment]
> Why was the ReVanced Manager Compose tag added? Compose manager already has this. The json format used by compose manager is not very complicated. You should be able to generate it using CI or some other method without any issues.

What is the format used there?
