### ISSUE TITLE
Please add codec changerfeat: <title>

### ISSUE THREAD

**Issue by NotZezu** [revanced/revanced-manager#574]
### Type

Functionality

### Issue

i wantr to chance codec video to  h264

### Feature

codec changer button on settings

### Motivation

make me happy if you do.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
Not related to manager.
