### ISSUE TITLE
Patched YT does not install

### ISSUE THREAD

**Issue by kanehu** [revanced/revanced-manager#575]
### Type

Error while running the manager

### Bug description

After patching YT Error message pops up. "Error
Non-root install is not possible with the current
patches selection
Repatch your app or choose root install if you
have your device rooted."

### Steps to reproduce

Step1 Start revanced manager
Step 2 Select patcher
Step 3 Select YT to patch
Step 4 Select any patch 
Step 5 Patch
Step 6 Hit install
Step 7 Message appears.

### Android version

13

### Manager version

0.0.45

### Target package name

com.google.android.youtube

### Target package version.

17.48.32

### Installation type

Non-root

### Patches selected.

Any.

### Device logs (exported using Manager settings).

```shell
I tried to paste log here, it does not fit, it is too long, so I cannot paste it here.
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because
resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied client-spoof
Applied custom-branding
Applied debugging
Applied disable-zoom-haptics
Applied hide-cast-button
premium-heading failed
Error:
kotlin.Unit
Applied settings
Applied theme
Repacking patched apk
Compiling resources
Writing modified dex files
Finished!
```

### Screenshots or videos

![Screenshot_20221210_103119](https://user-images.githubusercontent.com/70489959/206870740-f11bac8b-7712-4507-b91f-501aa979da4b.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Erasial** [comment]
Try adding microG support in patches, fixed this for me. Needed only for non-root install.

**Comment by kanehu** [comment]
Thank you, this helped. Still the patched youtube crashes all the time, it is impossible to open it, but at least patching is possible. Thanks again.

**Comment by kanehu** [comment]
>

**Comment by ejlocop** [comment]
> Try adding microG support in patches, fixed this for me. Needed only for non-root install.

tried to install the microG support patch along with the general add patch. it was successfully installed but when I opened it, it keeps on crashing.

![photo_2023-01-06_02-05-02](https://user-images.githubusercontent.com/12082880/210849657-6b707cee-7f7f-436f-9178-6970fe02d520.jpg)
