### ISSUE TITLE
Patcher aborting after merging integrations

### ISSUE THREAD

**Issue by amidstdebug** [revanced/revanced-manager#576]
### Type

Error while running the manager

### Bug description

Followed instructions [here](https://www.reddit.com/r/revancedapp/comments/xlcny9/revanced_manager_guide_for_dummies/) and receive dthe error after merging integrations

### Steps to reproduce

1. Downloaded revanced patcher from github repo
2. Downloaded (non bundled) YouTube apk from mirror with matching version
3. Tried to install patches
4. Received NotFoundException

### Android version

13

### Manager version

0.0.45

### Target package name

com.google.android.youtube

### Target package version.

v17.45.36

### Installation type

Non-root

### Patches selected.

All except debug

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
An error occurred! Aborting
Error:
org.jf.dexlib2.DexFileFactory$DexFileNotFoundException: Could not find entry classes.dex in /data/user/0/app.revanced.manager.flutter/cache/libCachedImageData/c230b3d0-7911-11ed-aa55-6ba353306de3.bin.
	at org.jf.dexlib2.DexFileFactory$DexEntryFinder.findEntry(DexFileFactory.java:393)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:88)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:61)
	at app.revanced.patcher.util.patch.PatchBundle$Dex.loadPatches(PatchBundle.kt:71)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:176)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by reisxd** [comment]
This has been fixed, but there's a new issue.

**Comment by fargotable** [comment]
This is a problem with the patcher, not with the manager. When I changed to the data recently provided by PalmDevs, i.e. "Patches organization" and "patches source", everything works fine, but when I restore to original "revanced-patches", these errors happen.

**Comment by reisxd** [comment]
> This is a problem with the patcher, not with the manager. When I changed to the data recently provided by PalmDevs, i.e. "Patches organization" and "patches source", everything works fine, but when I restore to original "revanced-patches", these errors happen.

Wrong. This is an issue in Manager, not patcher. The Manager Dev Team says it's because of one of the patch not having compatiblePackages.

**Comment by adamisafk** [comment]
Same for me:
```
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
An error occurred! Aborting
Error:
java.lang.NullPointerException
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:177)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)
```

**Comment by thegravity98** [comment]
I changed the "patches organization" to "thegravity98" (my fork of Revanced) and its working. 

Is it really manager specific issue ?

**Comment by Canny1913** [comment]
> I changed the source "patches organization" to "thegravity98" (my fork of Revanced) and its working.
> 
> Is it really manager specific issue ?

Yes.

**Comment by tusharsnn** [comment]
Is there a known workaround for now?

**Comment by tusharsnn** [comment]
> I changed the source "patches organization" to "thegravity98" (my fork of Revanced) and its working. 
> 
> Is it really manager specific issue ? 

This worked! Thanks.
I suggest you to not sync your fork with *master* until this issue is fixed

**Comment by qandres12** [comment]
> I changed the source "patches organization" to "thegravity98" (my fork of Revanced) and its working.
> 
> Is it really manager specific issue ?

You saved me from bashing my head in. Nothing seemed to work until I found this. Thank you.
