### ISSUE TITLE
bug: unable to patch any app

### ISSUE THREAD

**Issue by aminehmida** [revanced/revanced-manager#578]
### Type

Error while running the manager

### Bug description

I get this error every time I try to apply a new patch. This happens regardless of the app I am trying to patch.

### Steps to reproduce

Step1: select an application

Step2: Select any patch

Step3: Click patch button

### Android version

Android 13

### Manager version

0.0.45

### Target package name

com.reddit.frontpage

### Target package version.

v2022.45.0

### Installation type

Non-root

### Patches selected.

General Reddit Ads

### Device logs (exported using Manager settings).

```shell
https://gist.github.com/aminehmida/ffe8f7f69f597cd17e5eed48bdf30c08
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
An error occurred! Aborting
Error:
java.lang.NullPointerException
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:177)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by trmdi** [comment]
> 0.0.45

The latest version is .46 now.

**Comment by mattcc23** [comment]
I have a very similar issue, but with a slightly different error, and on the latest version of the manager as of writing (.51).
Here's a the log file [revanced-manager_patcher_20221216003736336626.log](https://github.com/revanced/revanced-manager/files/10241269/revanced-manager_patcher_20221216003736336626.log)
