### ISSUE TITLE
Auto install prompt when updating manager

### ISSUE THREAD

**Issue by Pillow-Fan** [revanced/revanced-manager#583]
### Type

Functionality

### Issue

The user needs to click the "update manager" button two times, the second time a few seconds after the the first time.

### Feature

Just like many managers, the function of downloading the update apk and automatically start the install prompt would be just nicer for the app. More over, if the user has root or shizuku, the app could automatically close, update and reopen on its own, overall skipping a useless step

### Motivation

As stated above

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by trmdi** [comment]
Maybe related to https://github.com/revanced/revanced-manager/issues/239

**Comment by ILoveOpenSourceApplications** [comment]
@trmdi  can you open a new issue with more details of the issue so that I can close these other issues related to the same?

**Comment by TheAabedKhan** [comment]
Previously, the manager didn't have the Downloading dialog so the users couldn't know that the update was being downloaded. This resulted in making them feel that they needed to click on the Update button two times every time they wanted to update.

This issue no longer exists in newer builds as there is a dialog window that shows the download progress.
