### ISSUE TITLE
bug: <I can't patch anything >

### ISSUE THREAD

**Issue by Mrkiller1000** [revanced/revanced-manager#589]
### Type

Error while running the manager

### Bug description

Every time I patch YT it shows Error "Non-root is not possible with the current patches selection. Repatch your app or choose root install if you have your device rooted". My device is not rooted.

The second thing is whether it is possible to patch Twitter or Tiktok ?  It shows "App not installed as package conflicts with an existing package." or "Aborting..." while processing the patching and stuck.

Thank you 

### Steps to reproduce

Every time I patch YT it shows Error "Non-root is not possible with the current patches selection. Repatch your app or choose root install if you have your device rooted". My device is not rooted.

The second thing is whether it is possible to patch Twitter or Tiktok ?  It shows "App not installed as package conflicts with an existing package." or "Aborting..." while processing the patching and stuck.

Thank you 

### Android version

13

### Manager version

0.0.49

### Target package name

YouTube
Twitter
Tiktok

### Target package version.

YouTube
Twitter

### Installation type

Non-root

### Patches selected.

All

### Device logs (exported using Manager settings).

```shell
....
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by reisxd** [comment]
> Every time I patch YT it shows Error "Non-root is not possible with the current patches selection. Repatch your app or choose root install if you have your device rooted". My device is not rooted.


You did not select MicroG Support.


> The second thing is whether it is possible to patch Twitter or Tiktok ? It shows "App not installed as package conflicts with an existing package." 

You have to remove the old one.

> or "Aborting..." while processing the patching and stuck.

Saying Manager gives "Aborting" error without sending the actual error isn't helpful.



Next time, please open a discussion post for things like this. Not a bug.

**Comment by Mrkiller1000** [comment]
> > Every time I patch YT it shows Error "Non-root is not possible with the current patches selection. Repatch your app or choose root install if you have your device rooted". My device is not rooted.
> 
> You did not select MicroG Support. 
It says "Patch is not supported for this app version"
> 
> > The second thing is whether it is possible to patch Twitter or Tiktok ? It shows "App not installed as package conflicts with an existing package."
> 
> You have to remove the old one. 
I removed the old one and it opened but it called Twitter Not Twitter Revanced (did it become patched???)
> 
> > or "Aborting..." while processing the patching and stuck.
> 
> Saying Manager gives "Aborting" error without sending the actual error isn't helpful.
> this is the log
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied disable-login-requirement
Failed to apply downloads: 'downloads' depends on 'settings' but the following error was raised: Hardcode offset changed.
Failed to apply feed-filter: 'feed-filter' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Applied fix-google-login
Applied hide-ads
Applied playback-speed
Applied predictive-back-gesture
Failed to apply settings: 'settings' did not succeed previously
Applied show-seekbar
Failed to apply sim-spoof: 'sim-spoof' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~QKZdaod00qxojCYdvhRAog==/app.revanced.manager.flutter-B29A1pbwfDYY8epIC-1bDg==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IGJJSX/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IGJJSX/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:375)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629)
	at app.revanced.patcher.Patcher.save(Patcher.kt:235)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:218)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~QKZdaod00qxojCYdvhRAog==/app.revanced.manager.flutter-B29A1pbwfDYY8epIC-1bDg==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IGJJSX/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IGJJSX/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:371)
	... 6 more


> Next time, please open a discussion post for things like this. Not a bug.
I am so sorry i am new to all of this, my apologies.

**Comment by oSumAtrIX** [comment]
A duplicate post is in the patches repository.
