### ISSUE TITLE
Bundle apk with patcher

### ISSUE THREAD

**Issue by tt-thoma** [revanced/revanced-manager#594]
### Type

Functionality

### Issue

I have to manually download a random apk on the internet to install the patcher on because YouTube won't go back/can't let you go back on updates.

### Feature

Add another app on top of the app list in the patcher that says: "Download recommended version" and that will automatically download the recommended version apk, patch it and install it

### Motivation

Because of the multiple viruses third-party websites could include in their versions, and because it will be more user-friendly 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by reisxd** [comment]
Duplicate issue. An APK downloader won't be added.

**Comment by CnC-Robert** [comment]
> Because of the multiple viruses third-party websites could include in their versions

You can check the signature of the apk to verify it

**Comment by tt-thoma** [comment]
> Duplicate issue. An APK downloader won't be added.

I didn't see any other issue that looked like this one

**Comment by rootback123** [comment]
open a new issue asking for a reliable source for the user to download so there won't be any problems, the old project was discontinued for offering compilations so they don't want to risk it.

**Comment by rootback123** [comment]
By no means am I saying to put in a direct link to the desired build but rather a reminder that the apk mirror is trusted within the app would be a great idea.

**Comment by rootback123** [comment]
I didn't create the problem because I can't, I'm leaving it in the hands of those who can.
