### ISSUE TITLE
Make quality settings same as Vanced was

### ISSUE THREAD

**Issue by EhabxAlaa** [revanced/revanced-manager#596]
### Type

Functionality

### Issue

Make the quality and playback speed exactly like vanced was , which is that you can choose the quality and playback speed in the settings for WiFi and cellular, and any changes in the playing video won't affect the other videos

### Feature

The current version is pretty annoying to use especially if you use the default YouTube settings  , but even with patches it is still hard , despite the latest change being good i think it good still be much better and way simpler

### Motivation

I think i explained it enough but let me say again, this will make the viewing experience much better 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Canny1913** [comment]
> but even with patches it is still hard
You just select a quality in quality settings and that's it. Don't see how that's hard.

**Comment by Ushie** [comment]
Acknowledgements are not met, this issue is unrelated to ReVanced Manager, P.S. this is a duplicate issue but i couldnt find the related issue on the whim

**Comment by EhabxAlaa** [comment]
But, it is related to the YouTube revanced, how could i request a feature to YouTube revanced then?
