### ISSUE TITLE
feat: Save&Export logs from previous app use sessions

### ISSUE THREAD

**Issue by tempodat** [ReVanced/revanced-manager#597]
### Type

Functionality

### Issue

Currently the "Share Manager's logs" button exports only the logs from the current app session, meaning if I close and reopen the app or restart the device the logs are wiped clean. 

### Feature

Save logs from previous use sessions, and allow them to be exported, either as a single continuous .log file or by picking the specific session of interest.

### Motivation

Having previous session logs available would be very useful, both for end-user troubleshooting of failed patches and for development.

For instance, my specific reasoning for requesting this feature is a black screen whenever I try to patch TikTok a certain way. Due to the app being unusable after the bug and the logs being wiped there is no way of troubleshooting the issue. I imagine those logs would be useful for end-users in many other situations, as well as for debugging.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
ReVanced Manager will soon be released as [a full rewrite](https://github.com/ReVanced/revanced-manager/tree/compose-dev). Over time, many feature requests have been made for the current version of ReVanced Manager, but to accelerate the development of the new version of ReVanced Manager, we have to focus on it, which I am closing this issue according to the [contribution guidelines](https://github.com/ReVanced/revanced-manager/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long/ Low priority/ Maintainers un-interested/ Too complex to realize
- Feature planned/ already implemented for the new version of ReVanced Manager

Regardless, anyone who comes across this feature request can PR it to the current version of ReVanced Manager until the new version is ready. Thanks for your feature request!
