### ISSUE TITLE
Possible solution for the well-known androlib bug

### ISSUE THREAD

**Issue by tt-thoma** [revanced/revanced-manager#603]
### Type

Error while running the manager

### Bug description

When recompiling the APK, it raises an Androlib error.

### Steps to reproduce

1. Download any YouTube apk
2. Select the APK on the patcher
3. Select any patch
4. Click on the patch button
5. Wait

### Android version

Android 12

### Manager version

0.0.50

### Target package name

YouTube

### Target package version.

17.45.36

### Installation type

Non-root

### Patches selected.

Any, it doesn't matter

### Device logs (exported using Manager settings).

```shell
https://1drv.ms/u/s!Akjp_Fdn78PQibxKIFbjDEwbg2CTpQ (can't paste anything on my phone, sorry)
```

### Screenshots or videos

![Screenshot_20221217-091010](https://user-images.githubusercontent.com/72872981/208232507-1a858933-23de-4de2-893f-9c42abde6c4b.jpg)
![Screenshot_20221217-090901](https://user-images.githubusercontent.com/72872981/208232514-de948a47-1a5b-4a7f-bad5-c079eeefe72b.jpg)

### Solution

Here are some link on the topic
https://github.com/iBotPeaches/Apktool/issues/1880#issuecomment-434612109
https://stackoverflow.com/questions/57441409/how-fix-brut-androlib-androlibexception-brut-common-brutexception-could-not-ex
https://github.com/iBotPeaches/Apktool/issues/2674#issuecomment-939775548
https://github.com/iBotPeaches/Apktool/issues/2674#issuecomment-1232549828

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Canny1913** [comment]
This is not Androlib issue, AAPT2 throws segfault error when you try to compile APK with an ARMv7 architecture device.

**Comment by tt-thoma** [comment]
I am not on armv7

**Comment by Canny1913** [comment]
> I am not on armv7

Logs say otherwise.

**Comment by tt-thoma** [comment]
I don't know, CPU-Z tells me otherwise
