### ISSUE TITLE
feat: Add a button to delete vanilla app after patching apk

### ISSUE THREAD

**Issue by Dr-Sauce** [revanced/revanced-manager#604]
### Type

Functionality

### Issue

When you try to install the patched apk you get a warning because the vanilla app and the patched apk signature are different.

### Feature

There's two ways to solve it.

1. Show a button to delete the vanilla app if the vanilla app signature and patched apk signature conflicts.
OR
2.  Add a delete vanilla app button in the 3 dots menu on the top right. (If the signature comparing process won't be added.)

![image](https://user-images.githubusercontent.com/82555878/208241133-63fd61da-080d-4850-b310-f8c3d43e380c.png)

### Motivation

To improve users UX.

Currently users have to patch app -> go to home screen -> delete vanilla app -> come back to ReVanced Manager and press 'install'.

### Additional context

Hello 🖐️

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
#494
