### ISSUE TITLE
Update download notification activity.

### ISSUE THREAD

**Issue by ghost** [revanced/revanced-manager#605]
### Type

Functionality

### Issue

While the manager update is downloading, track the current progress in the notification bar.

### Feature

You can see when the update is downloaded from the notification panel.You can see the size of the downloaded Update.We may display a notification when the update is complete.

### Motivation

It will be useful for monitoring download activity.

### Additional context

It would also be nice to be able to pause the download and monitor the download activity in the app as well.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Fidannyan** [comment]
I know this is a duplicate.

**Comment by trmdi** [comment]
https://github.com/revanced/revanced-manager/issues/239
