### ISSUE TITLE
Error while patching tiktok

### ISSUE THREAD

**Issue by raaz2053** [revanced/revanced-manager#607]
### Type

Error while running the manager

### Bug description

![Screenshot_20221219-015511](https://user-images.githubusercontent.com/20854983/208317234-0325c8b2-2c87-4cae-9e26-05c3edec5213.jpg)

### Steps to reproduce

None

### Android version

12

### Manager version

0.0.51

### Target package name

Ss

### Target package version.

235

### Installation type

Root

### Patches selected.

All 9

### Device logs (exported using Manager settings).

```shell
Hh
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Hh
```

### Screenshots or videos

![Screenshot_20221219-015511](https://user-images.githubusercontent.com/20854983/208317323-3577d1a0-1106-47cf-a5d4-07279ab88ef1.jpg)
![Screenshot_20221219-015511](https://user-images.githubusercontent.com/20854983/208317340-5f29a38b-d7e3-40f2-9243-28fa29c6dbd5.jpg)

### Solution

Ijj

### Additional context

Hhj

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by Canny1913** [comment]
Acknowledgements are not met.
