### ISSUE TITLE
Supported version of YouTube at revanced manager. 

### ISSUE THREAD

**Issue by antoniosamantos** [revanced/revanced-manager#609]
### Type

Functionality

### Issue

Hi, my name is Antony Amantos and I use YouTube vanced and now revanced since March 2022. Thank you for all the features and improvements even thought Google makes a lot of obstacles to you. The only thing I have to ask is that: will be able the revanced manager patch newer versions of YouTube than 17.45.36? Does it need a more difficult type of patching a split apk? 

### Feature

I don't have something to say. 

### Motivation

I just only asked something that I want to know because if the revanced manager won't support newer versions of YouTube, then after some years it would be useless. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
This has nothing to do with the ReVanced Manager.
