### ISSUE TITLE
Youtube background play???? 

### ISSUE THREAD

**Issue by Spaceboy60** [revanced/revanced-manager#612]
### Type

Functionality

### Issue

I don't see any option for this in the manager, am I missing something obvious? I see the option in YouTube music, but no option when I select YouTube.  

### Feature

Audio continues to play when the screen is turned off

### Motivation

N/a

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by Yurieaijoker** [comment]
Enable the patch minimized playback

**Comment by Spaceboy60** [comment]
Don't work, gives me error: failed to resolve themeSetterAppFingerprint

**Comment by Ushie** [comment]
> Don't work, gives me error: failed to resolve themeSetterAppFingerprint
> 
> Failed to apply settings : settings did not succeed previously

Force stop ReVanced Manager, clear cache then try again, that's a bug in ReVanced Patches that is already fixed in latest patches, clearing cache should drop your local patches and get the latest one

**Comment by Spaceboy60** [comment]
> > Don't work, gives me error: failed to resolve themeSetterAppFingerprint
> > Failed to apply settings : settings did not succeed previously
> 
> Force stop ReVanced Manager, clear cache then try again, that's a bug in ReVanced Patches that is already fixed in latest patches, clearing cache should drop your local patches and get the latest one

Didn't make a difference, same errors

**Comment by Spaceboy60** [comment]
Anything else I can try?

**Comment by Ushie** [comment]
> Anything else I can try?

Attempt a reinstallation of ReVanced Manager

**Comment by Spaceboy60** [comment]
> > Anything else I can try?
> 
> Attempt a reinstallation of ReVanced Manager

OK, tried that but I'm stuck on the V splash screen, won't go any further

**Comment by Spaceboy60** [comment]
Oh, just to point out I've tried  this on my redmi and my LG phone  with exactly the same error message on both and I've tried reinstalling on both

**Comment by Ushie** [comment]
> Oh, just to point out I've tried this on my redmi and my LG phone with exactly the same error message on both and I've tried reinstalling on both

Can you show me the patches version? it's shown in the Select Patches screen, you may have to press Load patches selection from the dropdown menu top right for it to show

**Comment by Spaceboy60** [comment]
0.0.1

**Comment by Spaceboy60** [comment]
![Screenshot_20221227-105624_ReVanced Manager](https://user-images.githubusercontent.com/110767705/209656700-057113ef-2cb2-48ca-8371-8f9741e0af0e.png)

**Comment by Ushie** [comment]
![Screenshot_20221227_135747](https://user-images.githubusercontent.com/79272171/209656827-ca687ffd-6ee0-4975-96de-0662af946b23.jpg)
this is what I'm asking you to show me, you may need to press Load patches selection from the dropdown menu for it to show

**Comment by Spaceboy60** [comment]
Ok, here you go:

![Screenshot_20221227-111010_ReVanced Manager](https://user-images.githubusercontent.com/110767705/209658235-c8cdc56e-189a-4a35-88e9-2a9c446c4b73.png)

**Comment by Ushie** [comment]
> Ok, here you go:
> 
> ![Screenshot_20221227-111010_ReVanced Manager](https://user-images.githubusercontent.com/110767705/209658235-c8cdc56e-189a-4a35-88e9-2a9c446c4b73.png)

Try to patch again, you shouldn't be getting the error on that version

**Comment by Ushie** [comment]
Please make a screen recording of you patching

**Comment by Spaceboy60** [comment]
At the minute I'm stuck on the following screen at is getting no further despite force stopping and clearing cache:

![Screenshot_20221227-173707_ReVanced Manager](https://user-images.githubusercontent.com/110767705/209702227-9217f246-9460-4058-84ff-cc62117c072b.png)

**Comment by Spaceboy60** [comment]
Ok, tried on my other phone, here's screenshot:

![Screenshot_20221227-181037_ReVanced Manager](https://user-images.githubusercontent.com/110767705/209705930-7c8ee373-b9fc-4f6f-b02e-5bc2d33e1d57.png)

**Comment by Spaceboy60** [comment]
> Please make a screen recording of you patching

You want screenshot as above or video?

**Comment by FlaminSarge** [comment]
I'm getting this issue on 18.05.40 specifically for Live streams, regular videos have the Headphone (and Next) button appear on the PIP player just fine, next to the Pause button, but Live streams only have the Settings, Maximize, X, and Pause buttons (they also lack the Next button).

**Comment by oSumAtrIX** [comment]
Check with unpatched app.

**Comment by FlaminSarge** [comment]
> Check with unpatched app.

From my understanding, unpatched app will not show those options for live streams or any videos without having YT Premium.

**Comment by oSumAtrIX** [comment]
Yes, you need YouTube premium for minimized playback.

**Comment by FlaminSarge** [comment]
> Yes, you need YouTube premium for minimized playback.

Is the minimized-playback patch not also for that purpose? Or do you suspect that this is an issue for Premium users of the unpatched app as well when dealing with live streams? I'll see if I can contact somebody that has Premium to test as such.

**Comment by oSumAtrIX** [comment]
I suspect the latter.

**Comment by FlaminSarge** [comment]
A friend with premium confirmed that on 18.05.40, for the following livestream link, the PIP player _does_ show the headphone icon and allows background play:
https://www.youtube.com/live/jfKfPfyJRdk?feature=share

For me on ReVanced with the minimized-playback patch, I am not able to do the same. This is most likely a bug with that patch and not with stock YT.

**Comment by oSumAtrIX** [comment]
![Screenshot_2023-04-30-03-20-28-77_f9ee0578fe1cc94de7482bd41accb329](https://user-images.githubusercontent.com/13122796/235331034-27e6fc96-de2a-4ec1-9a2a-2991644b5cc6.jpg)
This is what i see.

**Comment by FlaminSarge** [comment]
I've just patched 18.15.40 and I continue to get the issue. The friend on stock YT Premium with 18.15.40 does not get the issue.

Here is what I see: 
![](https://i.imgur.com/tEcLinQ.jpg)

**Comment by oSumAtrIX** [comment]
Log into his account and try it on your device.

**Comment by FlaminSarge** [comment]
> Log into his account and try it on your device.

As a heads up, I haven't had a chance to coordinate with him yet to try this, but will update when we've tested it.

**Comment by FlaminSarge** [comment]
As a heads up, this was resolved with what seems like some kind of YT A/B test, as I have made no changes to the app settings. I believe updating to 18.19.35 does not cause any regressions either, but will doublecheck.
