### ISSUE TITLE
YouTube error applying "settings"

### ISSUE THREAD

**Issue by mkujer** [revanced/revanced-manager#614]
### Type

Error while running the manager

### Bug description

Found when updating to a newer version of YouTube App.

### Steps to reproduce

Open Revanced
Choose Patches and apply 
Errors occur for Patches that rely on "settings"

### Android version

Android 13

### Manager version

0.52

### Target package name

com.google.android.youtube

### Target package version.

17.49.37

### Installation type

Root

### Patches selected.

![Screenshot_20221219_134920](https://user-images.githubusercontent.com/65073624/208434287-71a4c0f7-a1e2-4c1f-9c97-059df0a841c9.jpg)

### Device logs (exported using Manager settings).

```shell
https://anonfiles.com/WaM9y0Nay9/revanced-manager_logcat_20221219133654059443_log

Not enough space to paste all info
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied client-spoof
Failed to apply disable-auto-captions: 'disable-auto-captions' depends on 'settings' but the following error was raised: Failed to resolve ThemeSetterAppFingerprint
Failed to apply disable-auto-player-popup-panels: 'disable-auto-player-popup-panels' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply disable-fullscreen-panels: 'disable-fullscreen-panels' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply disable-startup-shorts-player: 'disable-startup-shorts-player' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply disable-zoom-haptics: 'disable-zoom-haptics' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply downloads: 'downloads' depends on 'downloads-resource-patch' but the following error was raised: 'downloads-resource-patch' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply general-ads: 'general-ads' depends on 'GeneralAdsResourcePatch' but the following error was raised: 'GeneralAdsResourcePatch' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply hide-autoplay-button: 'hide-autoplay-button' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply hide-captions-button: 'hide-captions-button' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply hide-cast-button: 'hide-cast-button' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply hide-endscreen-cards: 'hide-endscreen-cards' depends on 'hide-endscreen-cards-resource-patch' but the following error was raised: 'hide-endscreen-cards-resource-patch' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply hide-info-cards: 'hide-info-cards' depends on 'HideInfocardsResourcePatch' but the following error was raised: 'HideInfocardsResourcePatch' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Applied hide-my-mix
Applied hide-video-buttons
Failed to apply hide-watch-in-vr: 'hide-watch-in-vr' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply hide-watermark: 'hide-watermark' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply minimized-playback: 'minimized-playback' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply old-quality-layout: 'old-quality-layout' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply open-links-directly: 'open-links-directly' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Applied predictive-back-gesture
Applied premium-heading
Failed to apply remember-video-quality: 'remember-video-quality' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Applied remove-player-button-background
Failed to apply return-youtube-dislike: 'return-youtube-dislike' depends on 'return-youtube-dislike-resource-patch' but the following error was raised: 'return-youtube-dislike-resource-patch' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply seekbar-tapping: 'seekbar-tapping' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply settings: 'settings' did not succeed previously
Failed to apply sponsorblock: 'sponsorblock' depends on 'sponsorblock-resource-patch' but the following error was raised: 'sponsorblock-resource-patch' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Failed to apply tablet-mini-player: 'tablet-mini-player' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Applied theme
Failed to apply video-ads: 'video-ads' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Repacking patched apk
Compiling resources
Writing modified dex files
Finished!
```

### Screenshots or videos

![Screenshot_20221219_133615](https://user-images.githubusercontent.com/65073624/208434691-2b4d2196-42d5-4d83-acf7-3a05ef7d087e.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by druidamix** [comment]
I'm having the same error with the same version 17.49.37

**Comment by Ushie** [comment]
Acknowledgements are not met, this issue is unrelated to ReVanced Manager.

**Comment by mkujer** [comment]
> Acknowledgements are not met, this issue is unrelated to ReVanced Manager.

Hi, what's the issue related to? I am not exactly someone who understands lots of code. Can we expect a fix? It's happening on every version of YouTube App and even with downgraded revanced Manager...

**Comment by Ushie** [comment]
https://github.com/revanced/revanced-patches

**Comment by oSumAtrIX** [comment]
You don't need to be tech-savy to be able to read:

![image](https://user-images.githubusercontent.com/13122796/208556056-39893283-844a-429f-a4c8-064d6f5cd24b.png)

Regardless of that all relevant repositories are listed [here](https://github.com/revanced#%EF%B8%8F-contributors).

**Comment by hyoretsu** [comment]
> Acknowledgements are not met, this issue is unrelated to ReVanced Manager.

revanced/revanced-patches#1323

So, can we reopen this issue already?

**Comment by Ushie** [comment]
> > Acknowledgements are not met, this issue is unrelated to ReVanced Manager.
> 
> [revanced/revanced-patches#1323](https://github.com/revanced/revanced-patches/issues/1323#issuecomment-1359566246)
> 
> So, can we reopen this issue already?

Can't recreate, likely to have just been cache not having expired yet, should no longer be an issue anymore

**Comment by hyoretsu** [comment]
Somehow even after another update from patches, I still can't patch it because of the same error.

**Comment by iamfraxel** [comment]
same issue here but I'm on Android 12

**Comment by Pandoriaantje** [comment]
Cleared /cache, /data/dalvik-cache  still no joy. I'm no longer able to patch youtube. So stuck with original client for now. I hope this gets fixed soon.

**Comment by Pandoriaantje** [comment]
> > Cleared /cache, /data/dalvik-cache still no joy. I'm no longer able to patch youtube. So stuck with original client for now. I hope this gets fixed soon.
> 
> Can you tell me the patch bundle version? in patches selection screen, open the dropdown top right and click Load patches selection, then you'll see the patches version in a little card on the top right

Now it says 2.147.0, but i edited my previous repy. I cleared data/cache for the app and its functional again.

**Comment by Ushie** [comment]
I see, thank you!

**Comment by Fractune** [comment]
For some reason I wish to include that my YT app on my new phone, version ends with 34 instead of 37 thus I'm unable to apply most of the patches, any ways to update to latest? It's something that my App Store doesn't offer. 

I also believe that may be the reason I am getting `'settings' did not succeed previously` in console when I attempt to patch.

**Comment by Leenoha** [comment]
Just wanted to say this is still a problem. I cleared the cache, restarted the phone, reinstalled manager, nothing worked. I'd be super grateful if you could look into the issue again. Thanks.
Android 10
Youtube v17.49.34
Manager v0.52
Patches 2.147.0

**Comment by null-zero** [comment]
> 

Seeing as you're using Youtube v17.49.34, are you using the split apk? If you are, that is the issue. Find the universal v17.49.37 apk

**Comment by Leenoha** [comment]
> 
> Seeing as you're using Youtube v17.49.34, are you using the split apk? If you are, that is the issue. Find the universal v17.49.37 apk

I'm actually using whatever version Play Store allows me to use, didn't install a split apk, since I just wanted a hassle-free solution with the manager (and for it to be the only apk I have to install).

**Comment by Ushie** [comment]
> > Seeing as you're using Youtube v17.49.34, are you using the split apk? If you are, that is the issue. Find the universal v17.49.37 apk
> 
> I'm actually using whatever version Play Store allows me to use, didn't install a split apk, since I just wanted a hassle-free solution with the manager (and for it to be the only apk I have to install).

Use a Universal APK from APKMirror, split apk support (playstore) is not yet finished

**Comment by Leenoha** [comment]
Alright, I've clearly confused the terminology here. I'll wait for the Google Play version support. Thanks a lot for help and for the work!

**Comment by hamzaarbeed** [comment]
This issue because you only chose recommended patches. that doesn't include theme 0.0.1
You want to include theme 0.0.1 in the patches to avoid this error

**Comment by hamzaarbeed** [comment]
Reinstall revanced manager. 
Don't give root access for the application.
The problem will be solved.

**Comment by Msprg** [comment]
> Reinstall revanced manager. Don't give root access for the application. The problem will be solved.

Can confirm this has worked for me.

**Comment by hyoretsu** [comment]
Didn't work for me at the time. It probably worked because the problem just fixed itself. (Like it did for me at vXX.149)

**Comment by zoidy** [comment]
> Reinstall revanced manager. Don't give root access for the application. The problem will be solved.

I can confirm this worked for me as well (I had previously cleared storage as well but it didn't work until I denied it root)

**Comment by oSumAtrIX** [comment]
Can someone include a recording of the following:

1. Close the ReVanced Manager
2. Ensure it has root privileges
3. Open it and patch the app, and reproduce the issue
4. Close the ReVanced Manager
5. Deny root access
6. Open it and patch the app, showing it works without any issue

**Comment by hamzaarbeed** [comment]
> Can someone include a recording of the following:
> 
>     1. Close the ReVanced Manager
> 
>     2. Ensure it has root privileges
> 
>     3. Open it and patch the app, and reproduce the issue
> 
>     4. Close the ReVanced Manager
> 
>     5. Deny root access
> 
>     6. Open it and patch the app, showing it works without any issue

It used to happen with me when the patch version was 2.148.0 but after that since 2.149.0, it stopped happening. I no longer have the issue

**Comment by RyanEwen** [comment]
> Can someone include a recording of the following:
> 
> 1. Close the ReVanced Manager
> 2. Ensure it has root privileges
> 3. Open it and patch the app, and reproduce the issue
> 4. Close the ReVanced Manager
> 5. Deny root access
> 6. Open it and patch the app, showing it works without any issue

I did it in the opposite order but it demonstrates the same thing either way:
https://photos.app.goo.gl/TiFEmxmenBDw78kd8

I tried force stopping, clearing app cache and storage, uninstalling, and reinstalling. It only works when I deny it root access. 

Thankfully if I deny it root access until the build is complete, it requests root access once more in order to Root Install the app (I'm not using microG so I rely on being able to Root Install).

**Comment by balls69** [comment]
As of 1/21/23 this still doesn't work after following the last comments steps that supposedly fixes the issues

**Comment by yurisilpess** [comment]
> > > Acknowledgements are not met, this issue is unrelated to ReVanced Manager.
> > 
> > [revanced/revanced-patches#1323](https://github.com/revanced/revanced-patches/issues/1323#issuecomment-1359566246)
> > 
> > So, can we reopen this issue already?
> 
> Can't recreate, likely to have just been cache not having expired yet, should no longer be an issue anymore

Im having this issue right now, reinstalled the app, force stopped it, erased cache + data, nothing worked... it's now happening to other apps

**Comment by PhillipRt** [comment]
I figured it out for me
1. Donwnload exactly this. https://www.apkmirror.com/apk/google-inc/youtube/youtube-18-05-40-release/youtube-18-05-40-2-android-apk-download/download/?key=00594c637cbce808e3ae50d310f9b31949e8312d&forcebaseapk=true
2. Do not try to install it
3. Go to patches, storage and select the download from point 1. (Do not select the YouTube from the list which is shown!)
4. Select your patches, click patch and install

**Comment by greenturtle3141** [comment]
Just wanted to mention that I got this error, but I was being _incredibly stupid_.  Instead of selecting the YouTube APK that I downloaded (which needs to be manually selected from storage), I selected the one that was already on my device (which was the first and seemingly obvious option, hence my error).

Following the very specific instruction from PhillipRt worked in particular.

**Comment by oSumAtrIX** [comment]
People were reporting videos that did not show doing that wrong.

**Comment by Aza1261** [comment]
Hello guys,
I have the same problem with the revanced manager not patching the things depending on settings.
I tried all of the solutions above. Different version, playstore/non playstore, root/non-root,...

It worked fine for me 3 days ago and after the last youtube update suddenly stopped working at all. 

Is there any folder which might contain old data and which I could delete?

**Comment by Snuux** [comment]
same here, for manager 1.1.0 and youtube 18.17.38

**Comment by Aunali321** [comment]
> same here, for manager 1.1.0 and youtube 18.17.38

Use recommend version.

**Comment by Pyroglyph** [comment]
This is still an issue.

I have the latest recommended YouTube version (v18.16.37 non-split from APKMirror) and manager version 1.1.0.

This combination worked just fine previously yet now it has this issue after accidentally letting the Play Store auto-update YouTube and downgrading back to the same older APK.

Both storage and cache have been cleared for both apps, and the manager has been reinstalled completely, and yet it still occurs. What else can be done?

[Manager log file](https://files.catbox.moe/yc27zr.log)

**Comment by Ushie** [comment]
Select the full APK from storage, it can be found on sites such as APKMirror

**Comment by Pyroglyph** [comment]
> Select the full APK from storage, it can be found on sites such as APKMirror

I forgot to mention: I've tried that too and the same issue still occurs.

[Here's the log](https://files.catbox.moe/35rvs0.log) from trying that, if it helps at all.

**Comment by Ushie** [comment]
Do you happen to be rooted?

**Comment by Pyroglyph** [comment]
> Do you happen to be rooted? 

Yes. Why?

**Comment by Ushie** [comment]
For now, deny root access until a solution has been found, it should work if you do that

**Comment by Pyroglyph** [comment]
Denying root access works!

For the benefit of other root users, it's still possible to patch the installed app without SU, then turn it back on just before you tap "Install as root". It just has to be off when the patches are being done.
