### ISSUE TITLE
Applying Timeline Ads to Twitter doesn't work

### ISSUE THREAD

**Issue by DarkSkull91** [revanced/revanced-manager#615]
### Type

Other

### Bug description

Applying the timeline ads patch, it doesn't result patched.

### Steps to reproduce

Open revanced 

### Android version

12.1

### Manager version

Open revanced patcher and patch Twitter 

### Target package name

com.twitter.android

### Target package version.

v.9.68.1-release.0

### Installation type

Root

### Patches selected.

Timeline Ads (0.0.1)

### Device logs (exported using Manager settings).

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by Canny1913** [comment]
Acknowledgements are not met.

**Comment by DarkSkull91** [comment]
Sorry, I was on my phone and I miss some parts. Hope, now you can understand.

**Comment by Ushie** [comment]
You should open this in the [ReVanced Patches repository](https://github.com/revanced/revanced-patches/)
