### ISSUE TITLE
bug: unable to detect applications

### ISSUE THREAD

**Issue by TheGoldenSun** [revanced/revanced-manager#616]
### Type

Error while running the manager

### Bug description

When selecting revanced manager's application it says no application for some reason.

### Steps to reproduce

1. Improve revanced manager's patching universal applications to be selected properly.
2. Improve loading sequence within revanced manager.

### Android version

Model: SM-A215U
Android Version: 12
Arch: arm64-v8a

### Manager version

0.0.52

### Target package name

YouTube 

### Target package version.

YouTube Version: 17.49.37

### Installation type

Non-root

### Patches selected.

YouTube 

### Device logs (exported using Manager settings).

```shell
https://pastebin.com/CdSei8bq

(I had to copy and paste my device logs onto paste bin website because it would cause extreme lag issues on GitHub whenever I try to copy and paste my full device log codes in here, apologies)
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
N/A
```

### Screenshots or videos

![Screenshot_20221220_113347](https://user-images.githubusercontent.com/104534608/208727364-9517abe5-de5b-4a96-9a2f-50816a98796e.png)
![Screenshot_20221220_113358](https://user-images.githubusercontent.com/104534608/208727369-3de52b11-6ab0-476e-9083-e19193ff0730.png)

### Solution

I hope there would be an implemented fix for this issue since it's been happening on my Model: SM-A215U
Android Version: 12
Arch: arm64-v8a

### Additional context

none.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Utsavkattel000** [comment]
It cannot block shorts ads.

**Comment by rootback123** [comment]
Make sure your current system is not 32-bit which is not officially supported

**Comment by Canny1913** [comment]
> Make sure your current system is not 32-bit which is not officially supported

x86 is supported. AAPT doesn't support ARMv7 tho.

**Comment by Utsavkattel000** [comment]
> > Make sure your current system is not 32-bit which is not officially supported
> 
> x86 is supported. AAPT doesn't support ARMv7 tho.
My system is not 32 bit its arm cortex A76 and cortex a55. I don't know what that means. I just saw that in cpuz.

**Comment by TheGoldenSun** [comment]
> Make sure your current system is not 32-bit which is not officially supported

So in other words you're telling me that Revanced Manager cuts off certain device versions that's not supported anymore? That's beyond a high priority for them to do that to 32-bit users is negligible, supporting all modern android devices wouldn't bare any trivial moments of unjust. 

Thank you for telling me as I'm going to go back and use YouTube Vanced until they resolve issues about contributing all modern android devices instead of one per device.

**Comment by Canny1913** [comment]
> > Make sure your current system is not 32-bit which is not officially supported
> 
> So in other words you're telling me that Revanced Manager cuts off certain device versions that's not supported anymore? That's beyond a high priority for them to do that to 32-bit users is negligible, supporting all modern android devices wouldn't bare any trivial moments of unjust.
> 
> Thank you for telling me as I'm going to go back and use YouTube Vanced until they resolve issues about contributing all modern android devices instead of one per device.

x86 works, AAPT (the thing we use to compile resources) doesn't work with ARMv7 due to a segmentation fault, it has nothing to do with Manager.

If you want ARMv7 support you can always find out why it doesn't work and PR a fix. Any contribution is welcome.

By the way your issue is not related to architecture.

**Comment by Utsavkattel000** [comment]
> 

Then how do i fix that problem ?

**Comment by Canny1913** [comment]
I cannot access pastebin since it's blocked in my country. Please use hastebin or something else

**Comment by Sculas** [comment]
> I cannot access pastebin since it's blocked in my country. Please use hastebin or something else

Here you go: https://hastebin.com/azuzeyixiy.yaml

**Comment by TheGoldenSun** [comment]
My apologies, I will use hastebin next time since pastepin has your country blocked, I hope this would be implemented with a change soon. 
   


I cannot access pastebin since it's blocked in my country. Please use hastebin or something else
