### ISSUE TITLE
feat: <Revanced Manager's AI system>

### ISSUE THREAD

**Issue by TheGoldenSun** [revanced/revanced-manager#617]
### Type

Functionality

### Issue

Copy and pasting logcats is wonderful for me and other revanced users but there's something else that needs a change. 

### Feature

Add automatic bug reports into revanced manager so it can detect a bug issue and send it onto revanced manager's GitHub where you'll be able to see the new ticket issue from there, users can also manually report their bug issue within revanced manager if the issue is extreme or glitchy on any device they use.

![Screenshot_20221220_122652](https://user-images.githubusercontent.com/104534608/208729203-a30e9431-6c2c-4cd2-bccf-6c3f0139c116.png)
![Screenshot_20221220_122708](https://user-images.githubusercontent.com/104534608/208729205-273db658-be64-4354-a49a-2ada7ecfca82.png)

### Motivation

I believe that it'll make more easier than having revanced users copy and paste their logcats, like aliucord's manager who also has logcats as well is quite difficult to copy and paste one huge bug report code onto GitHub that causes lag issues whenever it is reported or not.

### Additional context

none.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Sentry logging is already implemented
