### ISSUE TITLE
No progress bar when downloading manager updates

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-manager#620]
### Type

Error while running the manager

### Bug description

Theres no progress bar, or any sorts of sign to show that the manager update is being/was downloaded and ready to be installed

### Steps to reproduce

1. Have an older version of manager
2. Click update manager button
3. Notice there is no progress bar when downloading
4. Notice there is no notification after download is completed

### Android version

12

### Manager version

0.0.45

### Target package name

N/A

### Target package version.

N/A

### Installation type

Non-root

### Patches selected.

N/A

### Device logs (exported using Manager settings).

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by SodaWithoutSparkles** [comment]
I know theres a similar issue, but this issue also addresses the notification thats missing. I think there was one before, from my memory

**Comment by SodaWithoutSparkles** [comment]
The notification of download completed only seems to appear **AFTER** installing...

**Comment by rootback123** [comment]
I also think this feature is great they should implement this in the future, but let's understand their side it must not be easy to create an application from scratch.

**Comment by trmdi** [comment]
https://github.com/revanced/revanced-manager/issues/239
