### ISSUE TITLE
Gesture Swipe left and right for playback speed control

### ISSUE THREAD

**Issue by Aziixz** [revanced/revanced-manager#623]
### Type

Functionality

### Issue

Currently it's a bit of a hassle to constantly change playback speeds via the settings option as it requires you to open setting thus blocking the video then open playback speed than select your playback speed, Its quite a hassle doing it constantly depending on the video since I some videos I would like normal others I would like to increase the playback speed since the brightness and volume gestures are already in the app, I think this feature wouldn't be that difficult to implement although i could be wrong.

### Feature

The feature would be a gesture setting for playback control when swiping left and right since currently those don't do anything i already have the brightness and volume gestures which I use very frequently and am very thankfull for, I would like to request a playback speed control when swiping left and right as I think it would no 1 feel very intuitive since brightness and volume are already in there and no 2 save people so much time constantly having to hit 4 different options to change playback speed

### Motivation

It would save people alot of time instead of manually having to go through 3 different settings to change playback speed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by ryanwwest** [comment]
+1. Not sure if closing this issue means it could still be considered.
