### ISSUE TITLE
No seek bar progress update on notification bar in Android 12

### ISSUE THREAD

**Issue by bhaskarvilles** [revanced/revanced-manager#624]
### Type

Other

### Bug description

While playing something there should be time stamps shown in the progress bar, but always showing nothing.

### Steps to reproduce

Step 1: Install any version of Revanced and play anything
Step 2: Minimize the player to notification bar
Step 3: you can see there is no change in the timings of playback.

### Android version

12

### Manager version

Latest

### Target package name

Latest

### Target package version.

Latest

### Installation type

Non-root

### Patches selected.

None

### Device logs (exported using Manager settings).

```shell
None
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
None
```

### Screenshots or videos

![Screenshot_2022-12-28-01-25-17-978_com miui home](https://user-images.githubusercontent.com/39507881/209717110-12926344-0b36-444f-832a-6642f3262c3b.jpg)
![Screenshot_2022-12-28-01-25-12-131_com miui home](https://user-images.githubusercontent.com/39507881/209717119-63dd7f91-576e-43ff-9eb9-32578b573a74.jpg)

### Solution

None

### Additional context

None

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
Acknowledgements are not met, this issue is unrelated to ReVanced Manager.

**Comment by bhaskarvilles** [comment]
> Acknowledgements are not met, this issue is unrelated to ReVanced Manager.

Yes it was, I've attached screenshots also.

**Comment by Ushie** [comment]
> > Acknowledgements are not met, this issue is unrelated to ReVanced Manager.
> 
> Yes it was, I've attached screenshots also.

ReVanced Manager is a **Manager**, it patches and installs patched applications and manages them, it is not involved with the content of these patches or any side effects that may arise, this issue might belong to [revanced-patches](https://revanced/revanced-patches) but this is unlikely to be an issue of revanced, it may be a stock youtube bug
