### ISSUE TITLE
country restriction remover patch

### ISSUE THREAD

**Issue by tahirjamil** [revanced/revanced-manager#627]
### Type

Functionality

### Issue

I am in Bangladesh YouTube music is not available in Bangladesh

### Feature

Is it possible to add country restriction removal path on YouTube music

### Motivation

It will be very helpful for me

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by reisxd** [comment]
Acknowledgements not met. Also, use a VPN.
