### ISSUE TITLE
feat: <title> Removal of navigation panel (HOME LIBRARY etc) while watching SHORTS 

### ISSUE THREAD

**Issue by AanooBeta** [revanced/revanced-manager#629]
### Type

Cosmetic

### Issue

It's like hide create patch 
CREATE BUTTON WAS ANNOYING
And so the navigation panel while watching shorts doesn't seem useful alot and it takes so much space I'm talking about this by the way:
![Screenshot_20230102-151041](https://user-images.githubusercontent.com/108539997/210217689-8df33379-bfd3-49bd-a359-edfedfcc6ef0.jpg)

### Feature

Adding a patch to remove the home library shorts etc button while watching shorts For instance:
![Screenshot_20221224-193404](https://user-images.githubusercontent.com/108539997/210217619-cdbda369-ae61-4b34-b0a6-1330bb777bd0.jpg)

### Motivation

I think alot of people will prefer it as i think it's useful 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
Acknowledgements are not met, this issue is unrelated to ReVanced Manager.
