### ISSUE TITLE
Add hide notification and comments etc

### ISSUE THREAD

**Issue by csc-chicken** [revanced/revanced-manager#636]
### Type

Functionality

### Issue

I think YouTube take me too much time, you cannot help but clicking when you see a notification or home feed that suggest some videos. I want to get rid of it

### Feature

I want to see some combo box that can let us choose to disable some distraction functionality made from YouTube, such as home feed suggestion and comments etc. Just like the unhook extension from chrome or Firefox.

### Motivation

I think recently YouTube algorithms and the notification took me too much time, so I want to have a functionality to prevent me from distraction.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
You can already hide comments and disable notifications in your device.

**Comment by Kunal-Mestry-3dfreelancer** [comment]
Hi, I'm Kunal. Hello, Revanced Team. Quick issue: the short player is not working properly. Please fix that issue ASAP.

https://github.com/user-attachments/assets/f4b91e4c-d6de-4317-a20d-4381e94f92f2
