### ISSUE TITLE
Set default video speed 

### ISSUE THREAD

**Issue by Lorestan00** [revanced/revanced-manager#637]
### Type

Functionality

### Issue

- Currently there is now way to set the video speed by default. 

### Feature

Add in toggle to allow users to watch by default at a faster speed than 1x

### Motivation

Adds the convenience of allowing users to watch  videos at a speed they are comfortable with.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Already available.

**Comment by Lorestan00** [comment]
Where is the setting to set the default speed?

**Comment by oSumAtrIX** [comment]
The one named "Remember playback rate"

**Comment by Lorestan00** [comment]
I can only see 'remember video quality' under misc.. See below. 


![Screenshot_20230110_162042.jpg](https://user-images.githubusercontent.com/81394097/211605613-0baabd31-4515-437a-8de8-f168bc0e5d5e.jpg)

**Comment by Lorestan00** [comment]
I've installed all the patches and am up to date with the latest version

**Comment by oSumAtrIX** [comment]
Yes, enable the switch, select any playback speed and disable the switch whenever you want to "lock" it.

**Comment by Lorestan00** [comment]
So they playback quality toggle works for playback speed as well?

I've tried it and it doesn't work

**Comment by oSumAtrIX** [comment]
The setting is enabled by default and works automatically when the patch is included. I can confirm that the setting to toggle it off it is missing though. 

Though, according to the following commit it should be present:

https://github.com/revanced/revanced-patches/commit/177e908dba260f184a2835b73b834563ca9c29fd#diff-3c9cfc4182f44ff2c8ad8561c5c47a9ab60d1ff884a478547f1aa5760dacc33dR60

For that reason, an issue should be opened for this.

**Comment by Lorestan00** [comment]
Okay so it should work in the background but doesn't? And a toggle needs to be added to turn it off?

**Comment by oSumAtrIX** [comment]
The patch is enabled by default and works. The switch to turn it off is missing.

Patch in action:

![Screenshot_2023-01-10-17-44-37-45_64ef5fc2000c1caa954c114bb372e1d5](https://user-images.githubusercontent.com/13122796/211611430-c84c8a5d-ec03-4917-be8f-2f49ef381744.jpg)

**Comment by Lorestan00** [comment]
So that message doesn't pop up for me after changing the speed

**Comment by Lorestan00** [comment]
The playback speed is lost from video to video

**Comment by oSumAtrIX** [comment]
In that case you are not up to date with the latest patches.

**Comment by Lorestan00** [comment]
Oh I'm on 0.0.5.2 of the manager. No new patches are showing up on updates.

**Comment by Lorestan00** [comment]
How can I update it? When I go to patcher section I've got all patches selected...
