### ISSUE TITLE
feat: installation improvement 

### ISSUE THREAD

**Issue by kaiminz** [ReVanced/revanced-manager#643]
### Type

Functionality

### Issue

The patched app cannot be installed again once we exported the patched apk and shut down the manager. Manager should be used to install the patched app or other app in both root and normal mode at any time. 

### Feature

Installation improvement 

### Motivation

APK installation 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by KobeW50** [comment]
Is this still not possible in current Manager versions?

**Comment by Ushie** [comment]
Yes, it isn't

**Comment by oSumAtrIX** [comment]
ReVanced Manager will soon be released as [a full rewrite](https://github.com/ReVanced/revanced-manager/tree/compose-dev). Over time, many feature requests have been made for the current version of ReVanced Manager, but to accelerate the development of the new version of ReVanced Manager, we have to focus on it, which I am closing this issue according to the [contribution guidelines](https://github.com/ReVanced/revanced-manager/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long/ Low priority/ Maintainers un-interested/ Too complex to realize
- Feature planned/ already implemented for the new version of ReVanced Manager

Regardless, anyone who comes across this feature request can PR it to the current version of ReVanced Manager until the new version is ready. Thanks for your feature request!
