### ISSUE TITLE
installation error: different packages (twitch)

### ISSUE THREAD

**Issue by Wjxfi** [revanced/revanced-manager#646]
### Type

Error while running the manager

### Bug description

manager did everything well, no errors, but when I want to download what it did android says different packages and can not install

### Steps to reproduce

patch twitch

### Android version

12

### Manager version

0.0.52

### Target package name

Screenshot

### Target package version.

Screenshot

### Installation type

Non-root

### Patches selected.

Screenshot

### Device logs (exported using Manager settings).

```shell
not available
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
not available
```

### Screenshots or videos

![302359](https://user-images.githubusercontent.com/113500363/212933157-e3efed0b-6d4d-43ae-bf32-55a1e724e8b3.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Ushie** [comment]
For now, after successful patching, don't press install, leave the app, uninstall twitch then come back to ReVanced Manager and install

I'm closing this issue because of #494
