### ISSUE TITLE
feat: Has application development been terminated?

### ISSUE THREAD

**Issue by dark-caster** [ReVanced/revanced-manager#650]
### Type

Other

### Issue

I noticed that the recommended version of YouTube is still 17.49.37, will it still be possible to apply the patches in future versions of YouTube or will Revanced Manager stop at this version?

### Feature

None 

### Motivation

None

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by reisxd** [comment]
Please open a discussion and not an issue.

**Comment by dark-caster** [comment]
I don't know much about Github, how do I open a discussion?
