### ISSUE TITLE
Can revanced manager patch newer versions of YouTube than 17.49.37 and why after installing a patched application it doesn't appear at the dashboard? 

### ISSUE THREAD

**Issue by antoniosamantos** [revanced/revanced-manager#653]
### Type

Cosmetic

### Issue

Hi,
 to make it simple I am just writing to let you know about some things that you could if you want make better.
  First of all, will the revanced manager remain a patcher application for YouTube v17.49.37? I recommend you to update often the version of YouTube that the manager has as recommended
, so we won't need to download the apks of YouTube of older versions that definitely are slower and sometimes buggy. Also after the update of v0.0.52 the patched applications don't show on the dashboard after installing. Ago the transition between the buttons: dashboard, patcher and settings are slow and sometimes stuck. Furthermore the patching and installation progress is slow. 

### Feature

Lowering transition scale, updating supported versions of YouTube, patch for making YouTube lighter. 

### Motivation

If you want, you hear my opinion. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
The patches have nothing to do with the ReVanced Manager.
