### ISSUE TITLE
bug: 0.0.53 android 13 fail to start

### ISSUE THREAD

**Issue by mactrash** [revanced/revanced-manager#654]
### Type

Error while running the manager

### Bug description

It just stuck in the logo and do nothing.

### Steps to reproduce

no

### Android version

nokia, android 13

### Manager version

0.0.53

### Target package name

no

### Target package version.

no

### Installation type

Non-root

### Patches selected.

no

### Device logs (exported using Manager settings).

```shell
no
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by LufyCZ** [comment]
S20, Android 13 (tried both Nov and Dec patch), same

**Comment by HamoBoker** [comment]
Same here, app stuck on blank screen and never loads

Device: Samsung C9 Pro (android 8.0)

**Comment by imadarsh1001** [comment]
Same issue for nothing phone 1

**Comment by mactrash** [comment]
Sorry just a wrong click in my phone so I reopen it

**Comment by fisforfaheem** [comment]
Not working please use a fix

**Comment by ApurvZ** [comment]
I have the same issue. Black screen or revanced logo. The issue started when i was using predictive back gesture on phone app. Then suddenly google logo, and G logo ( pixel bootanimation) and the. Yt music and YouTube apps were gone. Even rolled back to previous version, still issue persists.

**Comment by oSumAtrIX** [comment]
Patches have nothing to do with the ReVanced Manager.

**Comment by nukdokplex** [comment]
I think it's because the ReVanced API is not available. You just have to wait until they start working again

**Comment by K-plus69** [comment]
I have android 9 and have the same issue

**Comment by pressRtowin** [comment]
Surprised that it hasn't been mentioned yet that this has nothing to do with Android 13

**Comment by GodsMasterpiece509** [comment]
Not just on Android 13 it's also happening on Android 12 as I'm using Poco X3 nfc

**Comment by damadorPL** [comment]
it was DNS "issue" now it load corectly

**Comment by Ushie** [comment]
Closed in favor of #658
