### ISSUE TITLE
Where is the actual YouTube appfeat: <title>

### ISSUE THREAD

**Issue by fisforfaheem** [revanced/revanced-manager#655]
### Type

Functionality

### Issue

It is not available in any place so I don't know from this website is it true is it
https://revanced.io/#download-apk
Please tell me the YouTube app and how to apply this all there's no literally anything you want Is it the real appetite I'm using

### Feature

Please read

### Motivation

Read sur

### Additional context

https://revanced.io/#download-apk

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by PalmDevs** [comment]
We own revanced.app, not revanced.io.

**Comment by fisforfaheem** [comment]
But where is the YouTube app? Apk file

**Comment by oSumAtrIX** [comment]
You can get the ReVanced Manager on this repositories releases page.

**Comment by fisforfaheem** [comment]
The app manager is not working on my Pixel 4 XL It is just blank I even installed the old December 2022 version but it still has the same issue It won't long

**Comment by oSumAtrIX** [comment]
#654
