### ISSUE TITLE
bug: Revanced Manager Fails to Start Stuck on Startup Logo

### ISSUE THREAD

**Issue by Razor221** [revanced/revanced-manager#656]
### Type

Error while running the manager

### Bug description

program fails to launch, gets stuck on startup logo

### Steps to reproduce

just start the application

### Android version

Android 13

### Manager version

0.0.53

### Target package name

no packages

### Target package version.

no version

### Installation type

Root

### Patches selected.

none selected

### Device logs (exported using Manager settings).

```shell
can't access any logs.
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
can't access any logs.
```

### Screenshots or videos

no screenshot or video

### Solution

no solution

### Additional context

same as #654. I cleared the cache and data. Downgraded to 0.0.52 and upgraded to 0.0.53 and it didn't help. The program also gets stuck on bluestacks emulator too.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [x] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by oSumAtrIX** [comment]
#654

**Comment by ApurvZ** [comment]
I have the same issue. Black screen or revanced logo. The issue started when i was using predictive back gesture on phone app. Then suddenly google logo, and G logo ( pixel bootanimation) and the. Yt music and YouTube apps were gone. Even rolled back to previous version, still issue persists.

**Comment by fisforfaheem** [comment]
Please update not close the issues
