### ISSUE TITLE
bug: <title> Revanced Manager app freezes on lunch.

### ISSUE THREAD

**Issue by Peet-R** [revanced/revanced-manager#657]
### Type

Error while running the manager

### Bug description

When i try to open the Manager, the app freezes on the Revanced logo. My device is a Samsung Galaxy S22 Ultra (EU model), Android 13, with the latest January security update installed. Clear cache and clear data on the app did not solve the problem.

### Steps to reproduce

I just try to open the app.

### Android version

Android 13 (Build TP1A.220624.014.S908BXXS2BWA2)

### Manager version

0.0.53.

### Target package name

I can't patch anything, because the app is not loading.

### Target package version.

Can't patch anything.

### Installation type

Non-root

### Patches selected.

No patches can be selected, because the manager app won't load.

### Device logs (exported using Manager settings).

```shell
Can't make any log, because the app not loads.
```

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by oSumAtrIX** [comment]
#654
