### ISSUE TITLE
feat: make app less dependent on the API

### ISSUE THREAD

**Issue by nukdokplex** [ReVanced/revanced-manager#658]
### Type

Functionality

### Issue

Now the problem is that the application just hangs and won't initialize. I assume this is because the Revanced API located on the releases.revanced.app domain has gone down.

### Feature

Make the application show the start screen when the API is unavailable for one reason or another. If the API is unavailable, display a message about it and let users understand why they can't use the app now

### Motivation

Because it is not obvious what is the reason why the application does not work. There is no message about it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [x] The issue is related solely to the ReVanced Manager

**Comment by reisxd** [comment]
> is this issue still open?

If you have two functioning eye balls, yes.

**Comment by KobeW50** [comment]
Related to https://github.com/ReVanced/revanced-manager/issues/1441

(I can't comment on that thread because it's locked)

**Comment by oSumAtrIX** [comment]
This should be finished now in the form the issue describes the issue. Closing in favour of #1441
