### ISSUE TITLE
bug: root install failed

### ISSUE THREAD

**Issue by Amby713** [revanced/revanced-manager#66]
### Type

Functionality

### Branch

Patched the apk and installed it using the root install method

Did not install/update my YouTube

### Issue

Fails at root install

### Feature

Fix the patcher so that install as root works

### Motivation

Because it's broken

### Additional context

--------- beginning of main
09-14 14:07:22.198 15562  9383 W System  : A resource failed to call end. 
09-14 14:07:22.199 15562  9383 W System  : A resource failed to call end. 
09-14 14:07:22.199 15562  9383 W System  : A resource failed to call end. 
09-14 14:10:30.492 15562 15562 W DEVICE_APPS: Application with package name "com.google.android.youtube" is not installed on this device
09-14 14:10:41.507 15562  9383 W System  : A resource failed to call close.

**Comment by Aunali321** [comment]
Please specify the youtube version you used

**Comment by smgchosen** [comment]
Same problem. YouTube root crash. Version 17.33.42.

**Comment by Aunali321** [comment]
Download full apk from apkmirror and use that to patch

**Comment by smgchosen** [comment]
> Download full apk from apkmirror and use that to patch

It's exactly that I did.

**Comment by Aunali321** [comment]
oh for root you need to install youtube first. install the apk you downloaded and use the same one for patching.

**Comment by Amby713** [comment]
> Please specify the youtube version you used

It was the latest patch from apkmirror 17.35.36

I know it's not supported yet, but am just trying out the manager .

I saw your other reply , about installing the YouTube app first and then patching, so I'm doing that now and will update

**Comment by Aunali321** [comment]
Use 17.29.34 and retry. 17.35.36 is not recommended.

**Comment by smgchosen** [comment]
I tried 17.29.34 and 33.42, same problem. Fully uninstalled, install original apk from apkmirror, patch, root, open, crash.

**Comment by Amby713** [comment]
So I downloaded 17.29.34, selected all patches and patched it, installed as root and opened it.

YouTube kept crashing

Redid the process with microg unselected and it worked.

Maybe do a prepatch to ask if intending to tweet root so you can disable patches not intended for root install

**Comment by ponces** [comment]
MicroG is for non-root installs.
