### ISSUE TITLE
bug: version of patch is no longer displayed

### ISSUE THREAD

**Issue by trmdi** [revanced/revanced-manager#670]
### Bug description

The version of patch is no longer displayed as it was before. Please see the screenshot:

![IMG_20230130_211732](https://user-images.githubusercontent.com/11857205/215502801-1daedc73-2701-4eac-ad08-908876e6eb0b.jpg)

**Comment by TheUntouchable** [comment]
Same, even after choosing the "..." and "Load patches selection", which fixed it in the previews version.

**Comment by Windows200000** [comment]
> Same, even after choosing the three dots and "Load patches selection", which fixed it in the previews version.
> Edit: I don't know why the hell this is marked as spam.probably because you say "same"

**Comment by Windows200000** [comment]
I still have the same issue after the update (note10+)
