### ISSUE TITLE
App is not selected

### ISSUE THREAD

**Issue by BadBoy-Github** [revanced/revanced-manager#673]
### Type

Error while running the manager

### Bug description

We cannot select the application to be patched.

### Steps to reproduce

Open revanced manager
Open patch tab
Select an application for applying patch

### Android version

12

### Manager version

0.0.54(latest)

### Target package name

Youtube and youtube music

### Target package version.

Youtube: 18.03.36
Youtube music: 5.41.50

### Installation type

Non-root

### Patches selected.

Can't even select the app, then how can i select the patches?
No patches selected

### Device logs (exported using Manager settings).

```shell
No logs at all
```

### Screenshots or videos

https://user-images.githubusercontent.com/119521952/215643545-0cb438d4-7444-4077-86b7-ed7929378fc7.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Ushie** [comment]
I will fix this tomorrow, please use v0.0.53 in the mean time

**Comment by BadBoy-Github** [comment]
ok 
thanks for the timely reply

**Comment by Ushie** [comment]
I cannot recreate this issue

**Comment by BadBoy-Github** [comment]
nope this issue is only with the version 0.0.53

**Comment by ILoveOpenSourceAppications** [comment]
Doesn't seem to be a common issue as this doesn't happen to me.

**Comment by BadBoy-Github** [comment]
You can check the screen record linked in my report.

**Comment by ILoveOpenSourceAppications** [comment]
I watched the video. What I meant is the issue doesn't seem to be something that's common to everyone. Have you tried to do the same in another device?

**Comment by vlrn-stu** [comment]
I have the same issue,

**Comment by BadBoy-Github** [comment]
Now the bug had gone with some unknown unidentified trick.

I just reset the patch in the revanced manager and now it is working smoothly.
But i cannot patch any applications with all the patches. I can now patch the applications(yt and yt music) with recomended patches only.

**Comment by vlrn-stu** [comment]
Error fixed itself without doing anything, and it successfully patched for me.

**Comment by ILoveOpenSourceAppications** [comment]
So this issue can be closed then?

**Comment by vlrn-stu** [comment]
> So this issue can be closed then?

If the error where it only lets him patch with recommended patches is an error than no.

**Comment by oSumAtrIX** [comment]
@vlrn-stu This issue has nothing to do with the selection of patches. For that reason it means yes.
