### ISSUE TITLE
feat: Dark theme on tiktok

### ISSUE THREAD

**Issue by EldonX** [revanced/revanced-manager#682]
### Type

Functionality

### Issue

none

### Feature

Can you make a patch for dark mode in TikTok if it's possible?

### Motivation

because only iOS has it and I don't want to burn my eyes at night

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Axelen123** [comment]
There is already an issue over on the patches repository: https://github.com/revanced/revanced-patches/issues/1537
