### ISSUE TITLE
feat: Background Patching

### ISSUE THREAD

**Issue by HifeFish** [ReVanced/revanced-manager#684]
### Type

Functionality

### Issue

Patching an app sometimes takes a long time on my phone and it at least seems to not make any progress while ReVanced Manager is in the background, even though background activity is allowed and sleep disabled.

Even worse, if I use other apps, sometimes when I return to ReVanced Manager, it shows the app's home screen with no indication if the patching was successful or any way to install the patched .apk. So my only choice seems to be to restart the whole process.

In this instance, I was trying to apply 10 patches to the Youtube app yesterday and I had to start over at least three times and it never concluded. Then today it took at most a few minutes to finish, so there might be a time-dependent issue involved, but that doesn't change the original issue.

### Feature

a) Make Revanced Manager continue patching in the background 

and maybe additionally:

b) provide a notification, when patching has concluded.

c) If patching is still interrupted somehow, provide a resume option, if some of the steps had already completed; e.g. if patching was successful, then the app was closed, provide an option to install the patched .apk.

### Motivation

I would like to be able to still use my phone while a lengthy patching operation is in progress and moreover not risk having to restart the process.

### Additional context

ReVanced Manager 
Version: 0.0.54
Build: release
Model: SM-G955F
Android Version: 9
Arch: arm64-v8a

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by NotHuza** [comment]
You closet this here this mean you guys cant do this?

**Comment by GarvinSchaub** [comment]
The issue could occure since there is no real state management in place.
Rewriting this to include a persistent state management could be a ton of work in my unasked opinion.
