### ISSUE TITLE
bug: (Reddit) hide-subreddit-banner patch not getting applied

### ISSUE THREAD

**Issue by Tasin5541** [revanced/revanced-manager#688]
### Type

Error while patching

### Bug description

Revanced Manager v0.0.55
I tried patching reddit v2023.05.0

Selected 3 patches:
1. General Reddit ads
2. Hide subreddit banner
3. Premium icon reddit 

Patch no. 2 is not getting applied and I'm still seeing banner ads in comments. 

### Steps to reproduce

1. Select 3 patches for reddit:
1.1. General Reddit ads
1.2. Hide subreddit banner
1.3. Premium icon reddit 
2. Patch the app

### Relevant log output

```shell
Initializing installer 
Creating working directory 
Copying original apk
Unpacking input apk 
Reading dex files 
Decoding AndroidManifest.xml only, because resources are not needed
Applied general-reddit-ads 
Applied premium-icon-reddit 
Repacking patched apk 
Not compiling resources because resource patching is not required
Writing modified dex files Finished!
```

### Screenshots or videos

![Screenshot_2023-02-10-11-24-37-261-edit_app revanced manager flutter](https://user-images.githubusercontent.com/42533823/218009616-208f667c-78bd-4002-8707-97efdb8ac61a.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kazimmt** [comment]
Pull down Manager homepage to refresh patches
It works without any issue
(Tested on Manager 0.0.54)

![Screenshot_2023-02-10-12-02-54-297_app revanced manager flutter-edit](https://user-images.githubusercontent.com/82371061/218015674-4108395d-c52a-429b-8bfd-3c84e6b90f97.jpg)

**Comment by kazimmt** [comment]
![Screenshot_2023-02-10-12-11-00-085_app revanced manager flutter-edit](https://user-images.githubusercontent.com/82371061/218016246-578cc0c8-f003-4157-9b84-c36ec088d1d3.jpg)

**Comment by kazimmt** [comment]
Result from Manager 0.0.55
![Screenshot_2023-02-10-12-16-27-791_app revanced manager flutter-edit](https://user-images.githubusercontent.com/82371061/218017071-5942fb7f-a048-41df-a6a7-bfeccb620e72.jpg)
