### ISSUE TITLE
bug: not all `Installed` apps show up if source is different

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-manager#692]
### Type

Error while running the manager

### Bug description

Even after the latest fix #1022, YouTube and YTM apps installed from custom sources (inotia00) don't show up under installed apps. Initially this was working fine, but after #674 this feature broke and is still broken till day. Shouldn't the manager know which app is installed by it even if it's a custom source.

### Steps to reproduce

1. Update to manager version to 1.4.1
2. Still there is no YT or YTM being shown under installed apps.

### Android version

Android 13

### Manager version

1.4.1

### Target package name

ReVanced Manager 

### Target package version.

Nil

### Installation type

Non-root

### Patches selected.

Nil

### Device logs (exported using Manager settings).

```shell
Nil
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Nil
```

### Screenshots or videos

![Screenshot_20230716-010304~2](https://github.com/ReVanced/revanced-manager/assets/117499019/8c306326-d584-4812-9721-9adba0affefa)

### Solution

Identify the latest version and date of installation.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by ILoveOpenSourceApplications** [comment]
Stock Android (Pixel running on android 13):
![Screenshot_20230214-000809~2](https://user-images.githubusercontent.com/117499019/218545581-e3b892c7-9035-4da6-97af-2eb67d9fdeb8.png)

**Comment by ILoveOpenSourceApplications** [comment]
#680 needs further refining.

**Comment by ILoveOpenSourceApplications** [comment]
Okay I seem to have found why in my device (Pixel) in particular was showing "no patched applications installed". I was having a custom source (inotia00). Today, due to a bug occuring in RVX I installed ReVanced and lo and behold, there's a YouTube app under patched applications. The date and app version is accurate to what ReVanced is offering currently but when I swapped back to custom source again and installed RVX, the installed time looks okay but the app version is still what ReVanced is offering and the applied patches list is showing RVX patches in it. And when I uninstalled ReVanced YouTube, it once again became "no patched applications installed".

**Comment by ILoveOpenSourceApplications** [comment]
So yes, this issue occurs due to the source option present in the manager.

**Comment by ILoveOpenSourceApplications** [comment]
This issue is related to the manager right? Cause for rooted users I've seen that even though they have custom sources they're still having the patched apps show up under installed section.

**Comment by ILoveOpenSourceApplications** [comment]
If one is not quick enough it'll disappear after a few seconds:

https://user-images.githubusercontent.com/117499019/234251990-9de9427c-19d4-447b-bf63-9ae5de43b07a.mp4

If one is quick enough they can go into info but when backing out it'll disappear:

https://user-images.githubusercontent.com/117499019/234251812-55c89e74-fd14-41a2-ac4e-4b8cd842f864.mp4

**Comment by TheAabedKhan** [comment]
@ILoveOpenSourceApplications, maybe we should wait until the next release to confirm this issue still exists and needs to be fixed. If it exists even after the release, then update the steps to reproduce in the description.

**Comment by ILoveOpenSourceApplications** [comment]
> If one is not quick enough it'll disappear after a few seconds.

> If one is quick enough they can go into info but when backing out it'll disappear.

This isn't happening anymore after #1022 either. Now there is no sign within the manager that such applications got installed.

**Comment by Ushie** [comment]
Is this considered resolved in that case?

**Comment by ILoveOpenSourceApplications** [comment]
No actually. Previously there was a second where the manager would show the installed app which can be seen in this [comment](https://github.com/ReVanced/revanced-manager/issues/692#issuecomment-1521564182). But now that's not even the case as it's completely blank irrespective of how many times the user installs the app.

**Comment by ILoveOpenSourceApplications** [comment]
I believe #1311 resolved this issue and can be closed. Thanks for the fix @oSumAtrIX .
