### ISSUE TITLE
feat: Showing progress while updating the manager

### ISSUE THREAD

**Issue by nabil-el-houssein** [revanced/revanced-manager#694]
### Type

Functionality

### Issue

While updating the manager, there isn't a progress bar showing % of completion or any information that ensures that the update is happening. 

This feature is vital for any process that takes time especially for people with slow internet. For example, concerning a user with 25-70 Kb/s, the user can't be sure if the manager is downloading the update and/or if he/she can exit the manager and the update will take place in the background. 

### Feature

A simple progress bar that shows % of completion or the number of mbs downloaded and the total size of the update (or possibly both: % and number)

This can be achieved in the manager itself or in the notification bar.

### Motivation

This feature will be highly appreciated by the users especially those with slow internet speeds. 

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
#239

**Comment by nabil-el-houssein** [comment]
> #239

Can you delete this issue please?

**Comment by oSumAtrIX** [comment]
Not necessary, closing is enough.

**Comment by nabil-el-houssein** [comment]
> Not necessary, closing is enough.

I understand. It is just that it is my first time and I don't want it visible on my profile. Thanks.
