### ISSUE TITLE
bug: patch version still doesn't show (#670)

### ISSUE THREAD

**Issue by Windows200000** [revanced/revanced-manager#697]
### Type

Error while running the manager

### Bug description

I still have issue #670 after updating. (note10+)
Probably reopen it?

### Steps to reproduce

see #670 

### Android version

12

### Manager version

0.0.55

### Target package name

any

### Target package version.

any

### Installation type

Non-root

### Patches selected.

any

### Device logs (exported using Manager settings).

```shell
Don't wanna do it again, just see #670, but shouldn't be relevant
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Ushie** [comment]
There has not been a version bump yet, once v0.0.56 is released it will be there.

@EvadeMaster

**Comment by Windows200000** [comment]
> There has not been a version bump yet, the fix will be found in the next release.
On #670 it says the fix was added 3 days ago and there's a new manager (0.55) version from yesterday.

**Comment by trmdi** [comment]
> > There has not been a version bump yet, the fix will be found in the next release.
> 
> On #670 it says the fix was added 3 days ago and there's a new manager (0.55) version from yesterday.

See this: https://github.com/revanced/revanced-manager/commits/flutter

**Comment by EvadeMaster** [comment]
> There has not been a version bump yet, the fix will be found in the next release.
> 
> @EvadeMaster 

I'm sleeping madgy >:|

**Comment by EvadeMaster** [comment]
You can use this version https://github.com/revanced/revanced-manager/actions/runs/4152323610 until 0.0.56 released
