### ISSUE TITLE
feat: Add the automatic theme changing.

### ISSUE THREAD

**Issue by ivan123-tty** [revanced/revanced-manager#70]
Basically, add a feature that makes an app follow the system theme. 

It will just make it look a bit more polished, nothing else.

**Comment by kazimmt** [comment]
Material You is already inside the app

**Comment by ivan123-tty** [comment]
> Material You is already inside the app

i'm not talking about that bruh

**Comment by nrobinson12** [comment]
Basically when opening the app for the first time, the app doesn't check what the os theme is. The app will always be light theme initially. This ask is for the app to automatically detect the os theme and apply it to the app on first startup.

**Comment by ponces** [comment]
Implemented on https://github.com/revanced/revanced-manager/commit/598f7571de874f70b0a304d2d4a740371636fbaa.

**Comment by Indranil012** [comment]
> Implemented on [598f757](https://github.com/revanced/revanced-manager/commit/598f7571de874f70b0a304d2d4a740371636fbaa).

But not working
