### ISSUE TITLE
bug: i dont get notifications in revanced youtube

### ISSUE THREAD

**Issue by IDLEGLANCE** [revanced/revanced-manager#701]
### Type

Other

### Bug description

i still have YouTube normal installed and i have notifications of subbed channels on, but i only get a notification of the original youtube app but not of the revanced youtube app

### Steps to reproduce

i uninstalled youtube then installed YouTube v18.03.36 on apkmirror then i installed YouTube revanced with my chosen patches in the revanced manager, after that i logged into my google account in youtube revanced 
and yea i dont get notifications 

### Android version

android 13

### Manager version

newest i think 

### Target package name

YouTube 

### Target package version.

youtube v18.03.36

### Installation type

Non-root

### Patches selected.

• Client Spoof
• Copy Video Url
• Custom Branding
• Debugging
• Disable Startup Shorts Player
• Downloads
• General Ads
• Hide Cast Button
• Hide Shorts Button
• MicroG Support
• Minimized Playback
• Open Links Directly
• Open Links Externally
• Remember Video Quality
• Sponsorblock
• Spoof App Version
• Theme
• Video Ads

### Device logs (exported using Manager settings).

```shell
-
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
-
```

### Screenshots or videos

-

### Solution

-

### Additional context

-

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by ILoveOpenSourceApplications** [comment]
First of all, wrong place to report this issue. This isn't an issue related to manager.
Secondly, the issue you mentioned is something that's related to microG. Do you have it restricted or under battery optimisation? If so please allow it to run in the background. Closing it for now.

**Comment by IDLEGLANCE** [comment]
> 

ohh im sorry, the first thing i thought of was like writing an issue here because i didnt knew it is because of microg, im sorry for the "wasted" time tysm

**Comment by ILoveOpenSourceApplications** [comment]
Try checking out the ReVanced reddit page and maybe somebody with similar issue can help you out with more clarity.

**Comment by IDLEGLANCE** [comment]
> Try checking out the ReVanced reddit page and maybe somebody with similar issue can help you out with more clarity.

tysm :D
