### ISSUE TITLE
bug: PathNotFoundException

### ISSUE THREAD

**Issue by thepwrtank18** [revanced/revanced-manager#709]
### Type

Error while running the manager

### Bug description

When trying to patch YouTube, I get the error "PathNotFoundException: Creation failed, path = '/storage/emulated/0/Android/data/app.revanced.manager.flutter/files' (OS Error: No such file or directory, errno = 2). This seems to be a problem with Android 13's permission system.

### Steps to reproduce

1. Get Galaxy S23
2. Install ReVanced Manager
3. Download APK of recommended version of YouTube
4. Attempt to patch YouTube
5. See error

### Android version

Android version: 13
One UI version: 5.1
Google Play system update: January 1, 2023
Kernel version: 5.15.31-android13-8-25800099-abS911USQU1AWA6
Build number: TP1A.220624.014.S911USQU1AWA6
Android security patch level: January 1, 2023

### Manager version

Version: 0.0.56
Build: release
Arch: arm64-v8a

### Target package name

YouTube

### Target package version.

v18.03.36

### Installation type

Non-root

### Patches selected.

client-spoof, custom-branding, custom-video-buffer, custom-video-speed, disable-startup-shorts-player, downloads, general-ads, hide-create-button, hide-shorts-button, microg-support, minimized-playback, old-quality-layout, open-links-directly, open-links-externally, premium-heading, remember-playback-rate, remember-video-quality, remove-screenshot-restriction, return-youtube-dislike, sponsorblock, theme, video-ads, predictive-back-gesture

### Device logs (exported using Manager settings).

```shell
See https://gist.github.com/thepwrtank18/7e4f7304329ffd14f0b9b26e8c8426a9
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by ILoveOpenSourceApplications** [comment]
First, are you able to patch any other applications other than YouTube, perhaps YT Music?
Second, try excluding remove-screenshot-restriction & predictive-back-gesture and try again.

**Comment by ILoveOpenSourceApplications** [comment]
Those two patches are universal patches and if included with certain apps may cause this issue. Closing as it is resolved now.

**Comment by amdRyzen5600X** [comment]
i have same issue with s22 android 12 and even disabling those patches doesn't help
