### ISSUE TITLE
feat: Option to choose own keystore to sign apks

### ISSUE THREAD

**Issue by LokNplay** [revanced/revanced-manager#71]
### Type

Other

### Branch

Flutter

### Issue

Currently there is no option to choose a keystore to sign apks.

### Feature

Adding this option may help us to update apks without any issues. Also I can share modified apks with my friends without any issue. 

### Motivation

[LSPatch](https://github.com/LSPosed/LSPatch) is a rootless implementation of LSPosed framework, integrating Xposed API by inserting dex and so into the target APK. It gives us an option to choose our own key.

**Comment by ponces** [comment]
Makes sense.
We'll look into this.
Thanks.

**Comment by Aunali321** [comment]
Closing in favour of #263 .
