### ISSUE TITLE
Patch from playstore

### ISSUE THREAD

**Issue by speedlorenzo12** [revanced/revanced-manager#711]
### Type

Functionality

### Issue

If a phone is ni rooted you cant patch a application if isnt in a site you can download 

### Feature

The possibility of patch a application from downloading a application from the playstore using the link

### Motivation

Make easier patch a application 

### Additional context

I can change the text in future

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
This is a a patcher feature which is in the works.

**Comment by speedlorenzo12** [comment]
Im good to spolier 😅. 
Good work
