### ISSUE TITLE
bug: integrations are merged at all time

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/revanced-manager#712]
### Type

Error while running the manager

### Bug description

ReVanced Manager forces the user to merge integrations. By design this is flawed. The user has to choose whether to merge the integrations or not at a time.  

RE: https://github.com/revanced/revanced-patches/pull/1672#issuecomment-1444265925

### Steps to reproduce

Patch Instagram with any patch. The patched application will fail at runtime. 
Patch Instagram via ReVanced CLI, make sure not to merge integrations, and see that the patched application will work at runtime.

### Solution

Allow the user to choose whether to merge integrations. By default, it should not merge:

1. User selects an app
2. User selects patches
3. User clicks patch (a popup can ask if they want to merge the integrations)

or

1. User selects an app
2. User selects patches and turns on the switch to merge integrations
3. User clicks patch

### Additional context

The merge configuration should be remembered for each app in the same way it does for the patches.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Indranil012** [comment]
how user could know if if integration is required or not?
the patch need to instruct the manager that integration need to merge or not.

**Comment by oSumAtrIX** [comment]
This has been solved in the latest patcher version, it automatically determines, if merging integrations is required
