### ISSUE TITLE
Naming issue when default APK export path alreadyexist

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-manager#716]
### Type

Error while running the manager

### Bug description

When default export filename already exist in default export path, the new name would be `<appName>-revanced_<version>.apk (1)`, which modified the extension

### Steps to reproduce

1. Patch whatever app
2. After patching, don't install, but export the apk
3. Do not modify any default naming and save
4. Repeat above steps once
5. Go to your favorite file manager and look at the filenames of the exported files

### Android version

13

### Manager version

0.0.56

### Target package name

Does not matter, but have to be the same

### Target package version.

Does not matter, but have to be the same

### Installation type

Non-root

### Patches selected.

Does not matter

### Device logs (exported using Manager settings).

```shell
N/A
```

### Solution

Dont append after the `.apk` part, but right befor that

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by ILoveOpenSourceApplications** [comment]
#559

**Comment by SodaWithoutSparkles** [comment]
Oh sorry for that, apparently my search term is not exact enough
