### ISSUE TITLE
feat: Support for Android 6.0

### ISSUE THREAD

**Issue by jcperil** [revanced/revanced-manager#720]
### Type

Functionality

### Issue

I downloaded the latest apk on a device with Android 6.0. When I clicked to install, it says: "**There was a problem parsing the package**".

### Feature

Please support Android 6.0.

### Motivation

Official YouTube client is too heavy for the 3GB RAM device.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by reisxd** [comment]
YouTube no longer supports Android =<7 and Manager uses some APIs that only works on Android >= 8. Also, your movitation won't fix anything after supporting Android 6 for Manager.

**Comment by jcperil** [comment]
Thanks for the clarification. Is there an older release of Revanced Manager that supported Android 6.0?

**Comment by reisxd** [comment]
No.
