### ISSUE TITLE
bug: Reset Sources throws a black screen 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [revanced/revanced-manager#726]
### Type

Error while running the manager

### Bug description

If we try to reset the custom sources, the manager throws in a black screen and will require an app restart inorder to continue working.

### Steps to reproduce

Step 1. Go into Manager settings.
Step 2. Open sources.
Step 3. Tap on reset and choose yes.
Step 4. Vola.

### Android version

Android 13

### Manager version

0.0.56

### Target package name

Nil

### Target package version.

Nil

### Installation type

Non-root

### Patches selected.

Nil

### Device logs (exported using Manager settings).

```shell
Nil
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by ILoveOpenSourceApplications** [comment]
@Aunali321 do you know why this happens?

**Comment by Aunali321** [comment]
> @Aunali321 do you know why this happens?

Yes. It's a 1 line fix.

**Comment by ILoveOpenSourceApplications** [comment]
Great. Please look into it whenever you're having time.

**Comment by Aunali321** [comment]
Fixed in https://github.com/revanced/revanced-manager/commit/d318224a6f5a1ce2e72b4793623aad7cdc406c3f.
