### ISSUE TITLE
feat: prompt user to update Manager and/or the patcher

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVanced/revanced-manager#728]
### Issue

A few users report seeing error messages that should be impossible, especially:
`SettingsEnum: (error message that has nothing to do with SettingsEnum)`

The error message is from code outside of SettingsEnum, and it appears that somehow during patching the class names of the patched app became goofed up.

All of these users were using either an outdated ReVanced Manager, or the latest Manager but an outdated patcher.

Multiple users reported the problem was fixed, by updating Manager and/or the patcher, re-patching, and then reinstalling the app in question.

### Feature

If an update to Manager or the patcher is available, then show a dialog prompting the user to update.

(optional): if the user ignores the update prompt and tries to start patching an app, then give another prompt explaining they may experience problems if they do not update before patching.

### Motivation

Save a potential headache for the user if they don't use the latest software.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
This might be caused due to ProGuard moving members to different classes.

**Comment by oSumAtrIX** [comment]
I am not sure what you refer to with "ReVanced.apk". I am talking about the release integrations.apk file.

**Comment by oSumAtrIX** [comment]
Have you made sure to look into the release build and not the debug build? The classes are identical before and after merge with an app, so patching shouldn't make a difference

**Comment by oSumAtrIX** [comment]
If there is a way to turn off ProGuard while allowing to remove unused members and classes, that would be fine.

**Comment by oSumAtrIX** [comment]
This is only keeling the package app.revanced. Other packages such as that of libraries or Kotlin remain minified/removed.

**Comment by oSumAtrIX** [comment]
Sounds good. This would also resolve #1583.
