### ISSUE TITLE
feat: <title> Gmail 

### ISSUE THREAD

**Issue by sliceanddice9** [revanced/revanced-manager#729]
### Type

App request.

### Issue

There are ads placed inside the 'Social' and 'Promotion' inbox tabs. 

### Feature

Have the ads removed with the creation of Gmail ReVanced. 

### Motivation

The ads can be annoying and distracting when scanning through your inbox within 'Social' and 'Promotion'. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by EvadeMaster** [comment]
This issue is not related to the ReVanced Manager. Please open the issue here https://github.com/revanced/revanced-patches/issues/new/choose
