### ISSUE TITLE
some patch descriptions get cut off

### ISSUE THREAD

**Issue by flleeppyy** [revanced/revanced-manager#734]
### Type

Error while running the manager

### Bug description

Scrolling through patches, some descriptions are cut off, and there's no way (at least to me) to view more details about the patch

### Steps to reproduce

Just find a patch that has a cut off description

### Android version

Android 9

### Manager version

0.0.5.6

### Target package name

any

### Target package version.

any

### Installation type

Non-root

### Patches selected.

.. 

### Device logs (exported using Manager settings).

```shell
i don't think this is necessary, theres no errors here.
```

### Screenshots or videos

![Screenshot_20230308-094219](https://user-images.githubusercontent.com/18307183/223789816-e1556797-869a-47e3-80a3-8513b6f3c7ff.jpg)

### Solution

Add a "View Details" or "Long hold patch to view details" that shows the title, description, apps the patch supports, and the size of the patch, or something like that. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Ushie** [comment]
Fixed, wait for 0.0.57
