### ISSUE TITLE
bug: YouTube stuck in the middle of the video, song etc because there's no buffer 

### ISSUE THREAD

**Issue by mohaaw** [revanced/revanced-manager#735]
### Type

Error while running the manager

### Bug description

I was playing videos for 3 days..it was annoying to listen to one song without lag or freezing 

### Steps to reproduce

android 12 MIUI 13

### Android version

android 12 MIUI 13

### Manager version

latest 

### Target package name

YouTube 

### Target package version.

revanced YouTube 

### Installation type

Non-root

### Patches selected.

all

### Device logs (exported using Manager settings).

```shell
none
```

### Solution

just go to settings... revanced settings...misc and then video buffer
make the value 0 to all of them 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [x] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Patient6038** [comment]
I'm also getting the same bug.
