### ISSUE TITLE
bug: show dialogs earlier

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/revanced-manager#738]
### Type

Error while running the manager

### Bug description

A dialog is shown after patching when it could be shown before patching:
https://github.com/revanced/revanced-manager/blob/5d63d5c2d3b4f22e9f65384e06a0a31660988816/lib/ui/views/installer/installer_viewmodel.dart#L169-L190

This popup requires the user to repatch when not required to begin with. Additionally, the dialog in the image below does not give insight into what the problem is.

### Steps to reproduce

Patch YouTube without the `microg-support` patch. After patching, click on install.

### Installation type

Non-root

### Screenshots or videos

![image](https://user-images.githubusercontent.com/13122796/224633186-fe2ce94f-a604-411f-a62c-7f5cfb05cd42.png)

### Solution

- Shown dialog before patching to prevent having to repatch.
- Currently, ReVanced Manager fails to be agnostic by checking for the `microg-support` patch. If we are at it, it can also explain that it needs the patch to be present, before patching, in order to clarify, why it does not allow patching.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Neglectfull** [comment]
This is less a bug and more a feature request... I agree with you tho!

**Comment by Aunali321** [comment]
Fixed in https://github.com/revanced/revanced-manager/commit/74e0c09b543fe70b70cd917e6e21ceb0f46f3533.
