### ISSUE TITLE
bug: prevent slow down when exiting app while patching

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-manager#739]
### Type

Other

### Bug description

When you exit the app, while it is patching, the process slows down.

### Steps to reproduce

1. Start patching an app
2. Exit the app
3. Open it again and observe the process slows down

### Android version

13.0

### Manager version

0.0.57

### Target package name

com.google.android.youtube

### Target package version.

18.05.XX

### Installation type

Non-root

### Patches selected.

Recommended set

### Solution

There might be none as the throttle might be under the control of the OS. Otherwise, a special manifest setting or API might be responsible to allow running at full speed in the background.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Ushie** [comment]
Closing in favor of #684
