### ISSUE TITLE
Open failed: ENOENT (no such file or directory)

### ISSUE THREAD

**Issue by mjain234** [revanced/revanced-manager#74]
Hi there, i just installed revanced manager apk and while patching YouTube v.17.33.42 ,faced an [error](https://spaceb.in/api/v1/documents/iIbtJQZX/raw) 

Android Device - Realme 2 Pro
Android version - Android 13
ROM - Arrow OS

**Comment by ponces** [comment]
Make sure you're patching a full apk and not a split one

**Comment by mjain234** [comment]
So, now what is happening, when totally done patching and clicked on "Install as Root", these 2 errors are coming 

1)[error1](https://spaceb.in/api/v1/documents/LYZljsJn/raw)

2)[error2](https://spaceb.in/api/v1/documents/mgJRWBpD/raw)

**Comment by ponces** [comment]
Did the patching finish with success?
Make sure you're not applying MicroG patch

**Comment by mjain234** [comment]
Ok, so I am a total fool, didn't thought of that😐.
Now it's totally working fine. But still I could see some ads in the app, it is a known issue?

See this video for more: https://user-images.githubusercontent.com/70900505/190494678-548f114a-e8d1-44e3-92b7-352ed247dfcd.mp4
