### ISSUE TITLE
bug: reset sources doesn't work untill restarting the app

### ISSUE THREAD

**Issue by kazimmt** [revanced/revanced-manager#740]
### Type

Error while running the manager

### Bug description

If you change sources to any custom sources & Press reset sources button
It doesn't reset sources untill restarting the app

### Steps to reproduce

- go to ReVanced Manager Settings
- Set any custom sources
- Tap reset sources button & press yes
- it just stays untill restarting the app

### Android version

13

### Manager version

0.0.57

### Target package name

N/A

### Target package version.

N/A

### Installation type

Non-root

### Patches selected.

N/A

### Device logs (exported using Manager settings).

```shell
N/A
```

### Screenshots or videos

https://user-images.githubusercontent.com/82371061/225123436-b66fbddb-3db8-436e-bb22-8a8bdc8ff485.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Aunali321** [comment]
This is by design.

**Comment by oSumAtrIX** [comment]
In that case the design should change in favour of UX or a restart dialog should be incorporated

**Comment by EvadeMaster** [comment]
> In that case the design should change in favour of UX or a restart dialog should be incorporated

Resolve in 56faced5a3e193acb4cff75cd240683ff339162e

**Comment by Aunali321** [comment]
Fiex in https://github.com/revanced/revanced-manager/commit/9e8c6383ccbbe5c3fec47be990542382bf56324e.
