### ISSUE TITLE
bug: YT Revanced (18.05.40) crashed on start after repatching with 0.0.57

### ISSUE THREAD

**Issue by ShadowOne333** [revanced/revanced-manager#743]
### Type

Error while running the manager

### Bug description

Non-root user. Recently saw the update to Revanced to 0.0.57 and updated the app, and then tried repatching the YouTube APK I had, and the one that's recommended for patching (v18.05.40).

Selected all 57 available patches for it, and then continued with the installation process. Both the patching and installation went on without issues.

However, upon trying to open up the patched YouTube Revanced, the app refused to boot, and it simply crashed right after the YouTube logo appears.

### Steps to reproduce

Step 1: Download YouTube's APK version 18.05.40 (recommended by Revanced) from apkmirror
Step 2: Download and install Revanced Manager 0.0.57
Step 3: Patch the YouTube APK with Revanced Manager
Step 4: Install the patched APK
Step 5: Try to launch the patched YouTube Revanced app.

### Android version

12 SP1A.210812.016

### Manager version

0.0.57 (I also tried with 0.0.56 and it gave me a similar result)

### Target package name

com.google.android.youtube_18.05.40-1535903168_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk

### Target package version.

YouTube v18.05.40

### Installation type

Non-root

### Patches selected.

[selected_patches_2023-03-15_08_42_23.zip](https://github.com/revanced/revanced-manager/files/10981040/selected_patches_2023-03-15_08_42_23.zip)

### Device logs (exported using Manager settings).

```shell
[revanced-manager_logcat_20230315084453882537.log](https://github.com/revanced/revanced-manager/files/10981063/revanced-manager_logcat_20230315084453882537.log)
```

### Screenshots or videos

This screenshots are from the crash report given when trying to open the app:
![Screenshot_2023-03-14-19-48-31-944_com miui bugreport](https://user-images.githubusercontent.com/13888698/225341583-48d313d1-1dcc-4675-babb-0f89c01f0d26.jpg)
![Screenshot_2023-03-14-19-48-28-209_com miui bugreport](https://user-images.githubusercontent.com/13888698/225341602-d88ecce6-3cb8-4bb2-9e03-38f019d724d6.jpg)
![Screenshot_2023-03-14-19-48-19-168_com miui bugreport](https://user-images.githubusercontent.com/13888698/225341611-7b2a6c4d-13da-42c5-b19e-424221ec86f0.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by oSumAtrIX** [comment]
Exclude patches until the error is gone. Also not an issue with ReVanced Manager

**Comment by damadorPL** [comment]
Don't use all patches. Just select recommended

**Comment by ShadowOne333** [comment]
I did just that, re-enabling the Screenshot patch as well, and it seems to work now. Thanks for the suggestion, and sorry for the hasty report.

Out of curiosity, which one of the not-recommended patches is the one that caused the crash?

**Comment by Kobewaxman** [comment]
Most likely the spoof wifi connection patch.
