### ISSUE TITLE
bug: Wifi Spoofing crashes the app

### ISSUE THREAD

**Issue by ParaliyzedEvo** [revanced/revanced-manager#745]
### Type

Error while running the manager

### Bug description

When trying to run youtube revanced with the patch wifi spoofing (or any spoofing patch) which I want so I can log into my account. But every time I run the app with the wifi spoof it crashes. Without it I can run the app normally.

### Steps to reproduce

1. Patch Youtube
2. Use the patch wifi spoofing (or any spoofing patch)

### Android version

Android 9

### Manager version

0.0.57

### Target package name

Youtube

### Target package version.

The recommended version (Version 18.05.40)

### Installation type

Non-root

### Patches selected.

Always Autorepeat
Comments
Copy Video Url
Custom Branding 
Custom Video Buffer
Custom Video Speed
Debugging
Disable Auto Captions
Disable Fullscreen Panels
Disable Player Popup Panels
Disable Shorts On Startup
Disable Zoom Haptics
Downloads
Enable Wide Searchbar
General Ads
Hdr Auto Brightness
Hide Album Cards
Hide Artist Card
Hide Autoplay Button
Hide Breaking News Shelf
Hide Captions Button
Hide Cast Button
Hide Create Button
Hide Crowdfunding Box
Hide Email Addresses
Hide Endscreen Cards
Hide Floating Microphone
Hide Info Cards
Hide My Mix
Hide Player Buttons
Hide Seekbar
Hide Shorts Button
Hide Timestamp
Hide Video Action Buttons
Hide Watch In Vr
Hide Watermark
MicroG Support
Minimized Playback
Old Quality Layout
Open Links Externally
Predictive Back Gesture
Premium Heading
Remember Playback Rate
Remember Video Quality
Remove Player Button Background
Remove Screenshot Restriction
Return Youtube Dislike
Seekbar Tapping
Sponserblock
Spoof Wifi Connection
Swipe Controls
Tablet Mini Player
Theme
Video Ads

### Device logs (exported using Manager settings).

```shell
https://pastebin.com/raw/CiazhKiy (Github wouldn't let me submit)
```

### Additional context

I hope you guys can help me, my Youtube Vanced just stopped working and went downloaded Youtube Revanced instead. Thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by oSumAtrIX** [comment]
Not related to this repo.
