### ISSUE TITLE
bug: Needs hours to load new patches/integrations in manager after patching with previous patches.

### ISSUE THREAD

**Issue by giwrgosmant** [revanced/revanced-manager#747]
### Type

Error while running the manager

### Bug description

I don't know if this is a bug or it supposed to work like that:
When there is a new release with patches/integrations and you patch in manager with these patches/integrations and after a while new patches/integrations getting released like a hotfix, the manager doesn't take/fetch/load immediately the new patches/integrations with "hotfix" and need a lot of hours to reset and load the new patches/integrations so you can patch with the new.
I've tried multiple times with inotia00 and official revanced sources. Changing the sources between them doesn't help either.

### Steps to reproduce

1. Release new patches/integrations
2. Patch with these patches/integrations
3. Release new patches/integrations again in short period, like a hotfix or something.
4. Try to patch again, you will see the loaded patches are the previous and not the new with the "hotfix".
5. Try again after ~6hours+. If you are lucky u will be able to patch with the new patches.

### Android version

13

### Manager version

0.57

### Target package name

YouTube

### Target package version.

Both recommended youtube versions 18.05.40 for ReVanced and 18.10.37 for ReVanced Extended.

### Installation type

Non-root

### Patches selected.

Recommended

### Device logs (exported using Manager settings).

```shell
-
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Ushie** [comment]
This is by design, it's called cache

You can force fetch new releases by swiping down in the home screen
