### ISSUE TITLE
feat: allow user to specify branch for patches & integrations

### ISSUE THREAD

**Issue by bennett-sh** [revanced/revanced-manager#749]
### Type

Functionality

### Issue

Currently the custom repositories for integrations & patches only allow the master branch to be used.

### Feature

It should allow you to specify a branch.

### Motivation

This is generally useful and my motivation is that I use a new branch for each patch I write and I'd like to use them in the manager before they get merged.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
GitHub support should entirely be removed. ReVanced should rely as little as possible on a single platform, like GitHub. For that reason, the ReVanced releases API acts as a middleware proxy and transformer for whatever backend service serving releases and the application using the API. This proxy allows us plug-and-play services, in the case you want to host your own instance you can simply switch out the backend, host your own API, people switch to it in the ReVanced Manager app settings and voila.
Depending on the API, it can also support branches, versions, and so on. In any case support for GitHub directly should be dropped on ReVanced Manager as quick as possible.
