### ISSUE TITLE
feat: arsclib/split

### ISSUE THREAD

**Issue by Axelen123** [ReVanced/revanced-manager#751]
### Type

Functionality

### Issue

We have to migrate to the upcoming patcher changes.

### Feature

Todos:
- [ ] Extract split bundles
- [X] Account for the api changes
- [ ] Remove warnings about splits
- [ ] Install split bundles or merge the bundle
- [ ] Root/from installed app (I have no idea how to deal with this)

### Motivation

Better performance and ARMv7 support.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
ARSCLib PR has been closed, so I'm closing this too
