### ISSUE TITLE
Can't patch any app other than YouTube 

### ISSUE THREAD

**Issue by EhabxAlaa** [revanced/revanced-manager#754]
### Type

Error while running the manager

### Bug description

Patching and installing YouTube works just fine , but  i tried patching Twitter and Photomath, although patching didn't have any errors, i got the message of app not installed, I tried several ways to fix this issue but nothing worked 

### Steps to reproduce

Use recommended apk versions of supported apps and try applying any patches 
You will get the message of "app not installed" 

### Android version

11

### Manager version

Latest 

### Target package name

Twitter/Photomath 

### Target package version.

Recommended/any

### Installation type

Non-root

### Patches selected.

Any

### Device logs (exported using Manager settings).

```shell
No need logs are perfect
```

### Screenshots or videos

![Screenshot_2023-03-22-15-59-08-960_com google android packageinstaller](https://user-images.githubusercontent.com/120474122/226996043-5f491607-3234-4a42-b790-58e7d39ccc60.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by oSumAtrIX** [comment]
#280

**Comment by EhabxAlaa** [comment]
Is this something that could be fixed by downloading the apk from a different source or any other way to fix it or is it an issue from your side?
