### ISSUE TITLE
Just a suggestion

### ISSUE THREAD

**Issue by antoniosamantos** [revanced/revanced-manager#755]
### Type

Functionality

### Issue

When someone changes the sources, presses the button OK and tries to patch YouTube it uses the previous organization patches and integration method and to apply the new settings you must restart the app. 

### Feature

In my opinion when someone changes the sources and presses OK the app could automatically refresh and use the new settings. 

### Motivation

It is something that could make the app better. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by ILoveOpenSourceApplications** [comment]
#740
