### ISSUE TITLE
feat: dark mode for tiktok

### ISSUE THREAD

**Issue by IDLEGLANCE** [revanced/revanced-manager#756]
### Type

Functionality

### Issue

-

### Feature

-

### Motivation

-

### Additional context

no one likes white mode

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by IDLEGLANCE** [comment]
i know that there are more than 1 posts about tiktok darkmode but no one added it into revanced manager/patches

**Comment by reisxd** [comment]
Acknowledgements not met.
