### ISSUE TITLE
Add download button in Shorts Videos

### ISSUE THREAD

**Issue by MrPro5** [revanced/revanced-manager#758]
### Type

Functionality

### Issue

So i have a Suggestion that can make download shorts videos faster= Add Download button in the short videos so i can directly download shorts into Seal or another video downloader app

### Feature

Add Download button in the short videos so i can directly download shorts into Seal or another video downloader app

### Motivation

So i can download short directly into Seal or another video downloader app

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by ILoveOpenSourceApplications** [comment]
This is the wrong place to request for features related to apps such as YouTube. For that please open a new issue under ReVanced patches.

**Comment by ILoveOpenSourceApplications** [comment]
Closing this as it's not related to manager.
