### ISSUE TITLE
feat: Add support for KernelSU

### ISSUE THREAD

**Issue by jordanyoong1** [revanced/revanced-manager#762]
### Type

Functionality

### Issue

If you use KernelSU as root method, Revanced Manager will output installation successful but in fact it isn't installed.

### Feature

-

### Motivation

-

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
Can you try the following:

- move the script from /data/local/tmp/revanced-manager to either /data/adb/service.d or /data/adb/post-fs-data.d

if that doesn't work, do `chmod +x` on the script and try one of the two above directories again (you have to reboot between each test)

**Comment by Ushie** [comment]
alternatively you can delete the /data/local/tmp/revanced-manager directory and try using the CLI to install the patched apk using the root method, and tell me if that works

**Comment by jordanyoong1** [comment]
> alternatively you can delete the /data/local/tmp/revanced-manager directory and try using the CLI to install the patched apk using the root method, and tell me if that works

Actually, KernelSU just updated yesterday, now it's working. My bad for no checking.

**Comment by AzusaHana** [comment]
> > alternatively you can delete the /data/local/tmp/revanced-manager directory and try using the CLI to install the patched apk using the root method, and tell me if that works
> 
> Actually, KernelSU just updated yesterday, now it's working. My bad for no checking.

Did you succeed with the cli? I still can’t install it using the manager

**Comment by jordanyoong1** [comment]
> > > alternatively you can delete the /data/local/tmp/revanced-manager directory and try using the CLI to install the patched apk using the root method, and tell me if that works
> > 
> > 
> > Actually, KernelSU just updated yesterday, now it's working. My bad for no checking.
> 
> Did you succeed with the cli? I still can’t install it using the manager

No, I'm using the manager, did you reboot after install? I had to reboot to make KernelSU execute the scripts. My KernelSU version is 10687 while the KernelSU Manager is 10699.

**Comment by AzusaHana** [comment]
> > > > alternatively you can delete the /data/local/tmp/revanced-manager directory and try using the CLI to install the patched apk using the root method, and tell me if that works
> > > 
> > > 
> > > Actually, KernelSU just updated yesterday, now it's working. My bad for no checking.
> > 
> > 
> > Did you succeed with the cli? I still can’t install it using the manager
> 
> No, I'm using the manager, did you reboot after install? I had to reboot to make KernelSU execute the scripts. My KernelSU version is 10687 while the KernelSU Manager is 10699.

yes, I have rebooted. My KernelSU version is 10703 while the KernelSU Manager is 10701.

**Comment by AzusaHana** [comment]
I have solved this problem, need to manually create two folders service.dand post-fs-data.d in the /data/adb.
but i still have the other problem, cannot install directly due to signature conflicts.
Failure [INSTALL_FAILED_DUPLICATE_PERMISSION: Package com.google.android.youtube attempting to redeclare permission com.google.android.youtube.permission.C2D_MESSAGE already owned by com.google.android.youtube]

**Comment by Kronodile** [comment]
X

> I have solved this problem, need to manually create two folders service.dand post-fs-data.d in the /data/adb. but i still have the other problem, cannot install directly due to signature conflicts. Failure [INSTALL_FAILED_DUPLICATE_PERMISSION: Package com.google.android.youtube attempting to redeclare permission com.google.android.youtube.permission.C2D_MESSAGE already owned by com.google.android.youtube]

Can you elaborate what folders to create, copy files, where to do please
