### ISSUE TITLE
ci(analyse-code): run only when necessary

### ISSUE THREAD

**Issue by Ushie** [revanced/revanced-manager#765]
### Type

Functionality

### Issue

Currently, `Analyse code` is run for every commit in every PR

### Feature

It should only run when changes to code are made, so perhaps when lib/ or app/ is modified

### Motivation

Prevent unnecessary workflow runs, wasting GA minutes and failing on unrelated PRs such as changes to docs or CI and such

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by PalmDevs** [comment]
Should it only ran manually like the PR Build workflow?
