### ISSUE TITLE
bug: Error while compiling YT Music v5.49.54

### ISSUE THREAD

**Issue by Vice-Manci** [revanced/revanced-manager#767]
### Type

Error while running the manager

### Bug description

[Logs](https://github.com/revanced/revanced-manager/files/11103279/252Fdata.252Fuser.252F0.252Fapp.revanced.manager.flutter.252Fcache.252Flogs.252Frevanced-manager_patcher_20230329134538557896.log) 

### Steps to reproduce

- Patch the latest YT Music APK (v5.49.54)
- Choose the patches already mentioned
- Get a compiler error

### Android version

Android 12

### Manager version

0.0.57

### Target package name

com.android.apps.youtube.music

### Target package version.

v5.49.54

### Installation type

Non-root

### Patches selected.

Background Play v0.0.1
Codecs Unlock v0.0.1
Exclusive Audio Playback v0.0.1
Minimized Playback Music v0.0.1
Music MicroG support v0.0.2
Music Video Ads v0.0.1
Tastebuilder Remover v0.0.1
Upgrade button removed v0.0.1

### Device logs (exported using Manager settings).

```shell
[Logs](https://github.com/revanced/revanced-manager/files/11103279/252Fdata.252Fuser.252F0.252Fapp.revanced.manager.flutter.252Fcache.252Flogs.252Frevanced-manager_patcher_20230329134538557896.log)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by oSumAtrIX** [comment]
https://github.com/revanced/revanced-manager/issues/480
