### ISSUE TITLE
Patch break Twitter

### ISSUE THREAD

**Issue by DG5312** [revanced/revanced-manager#769]
### Type

Other

### Bug description

Apply the patches and break the app

### Steps to reproduce

I use 9.71 what I downloaded from apkpure
Install
Open ReVanced Manager
Select app and apply parches

dynamic color
export all activities
hide ads
remove screenshot restriction

When finish creating the patched app, uninstall the apkpure app
Install the patched app

Trying to login, and cant login. 

### Android version

10

### Manager version

0.0.57

### Target package name

com.twitter.android

### Target package version.

9.71

### Installation type

Non-root

### Patches selected.

dynamic color
export all activities
hide ads
remove screenshot restriction

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied dynamic-color
Applied export-all-activities
Applied hide-ads
Applied remove-screenshot-restriction
Repacking patched apk
Compiling resources
Writing modified dex files
Finished!
Installing patched file using nonroot method
```

### Additional context

Here are links to the apk (patched and the apkpure) and log:
https://mega.nz/folder/Wo1B0LZL#2ENkbEQkJucjxRZjdfy1JQ

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by oSumAtrIX** [comment]
Select the recommended set of patches.

**Comment by DG5312** [comment]
Im using the Recommended patches and still happen :'v
Apk and log
https://mega.nz/file/n4t0nBYa#C2Pj6vPQjD1m5tubhSdsc_Ce2BdhAF_O9ksKaFAYLVc

**Comment by oSumAtrIX** [comment]
Please attach a complete recording of the patching process. Start by closing and reopening ReVanced Manager and finish the recording at the crash.

**Comment by DG5312** [comment]
https://user-images.githubusercontent.com/99689021/229947470-27690ee8-dd69-4f16-a6b3-ccecb67995ce.mp4

**Comment by oSumAtrIX** [comment]
You are patching and installing a split APK file. You need a full APK file though.

**Comment by DG5312** [comment]
I dont understand, because I cant install the patched apk so idk what I can make so... You tell me please :v

**Comment by DG5312** [comment]
Now I did it by patching the apk instead of the installed app, same result.

In ReVanced YT channel would make a video explaining this? Because I trying to make this work and i cant :'b

**Comment by oSumAtrIX** [comment]
Please send a full recording as previously with your new steps.

**Comment by DG5312** [comment]
https://user-images.githubusercontent.com/99689021/230308296-94db8774-41a8-4346-884b-a4f81fe8d2e8.mp4

**Comment by Ushie** [comment]
You can workaround this by switching from WiFi to mobile data (or vice versa) after launching the app before logging in

**Comment by oSumAtrIX** [comment]
Please attach a proper recording without weird cuts, jumps or quick actions. Also review all settings of the app in the video.

**Comment by DG5312** [comment]
> You can workaround this by switching from WiFi to mobile data (or vice versa) after launching the app before logging in

I dont have a network limitation, I can do it with a clean Twitter app, the problem is when I patch the app I cant login.

**Comment by DG5312** [comment]
> Please attach a proper recording without weird cuts, jumps or quick actions. Also review all settings of the app in the video.

Sure, I was trying to cut the video because I want no make too long some thing like can be see in short time.
And i put black/egg sticker because is my personal phone... And I have personal information that I dont want to be seen publicly.

I'll try to make it cleaner this time 👍

**Comment by DG5312** [comment]
I hope this can help... So heres the video, apk base, apk patched and log.
https://mega.nz/file/jp1wWZDY#KOaAB3YY54krZlNwEZkiq4dJ7qL6sxG56KBKX1i_Kmg
https://user-images.githubusercontent.com/99689021/230557497-d011bf7f-8088-4c53-b111-77aee00256f0.mp4

**Comment by DG5312** [comment]
Lol
Epic embed fail

**Comment by Ushie** [comment]
> > You can workaround this by switching from WiFi to mobile data (or vice versa) after launching the app before logging in
> 
> I dont have a network limitation, I can do it with a clean Twitter app, the problem is when I patch the app I cant login.

I know you can login on the unmodded twitter app, twitter login stops working properly when it's modded/signature is different, following the instructions I sent above will allow you to log in 👍

**Comment by oSumAtrIX** [comment]
Are you logging in with Google?

**Comment by DG5312** [comment]
> Are you logging in with Google?

Yes, im a idiot I use another method of login and works now.

**Comment by DG5312** [comment]
So, Google login is broken and another are working as expected.
