### ISSUE TITLE
YouTube Revanced and YouTube Music Revanced crash on opening after installing with root

### ISSUE THREAD

**Issue by Satanarious** [revanced/revanced-manager#77]
Tested on version 17.55.42 and 5.23.50 respectively, but working fine without root

**Comment by eisklwksjs** [comment]
crashes maybe due to "no" micro-G installation, install that

**Comment by Aunali321** [comment]
You need the same app version installed. Then patch the apk and test.

**Comment by Satanarious** [comment]
I don't think I understand you. I installed the supported versions of YouTube and YouTube Music and then patched them using revanced manager, but I was the apps kept crashing on opening, when installed without root.But worked flawlessly, when installed with root.

**Comment by eisklwksjs** [comment]
well, non root versions require micro-G, try installing micro-G first and open them

**Comment by eisklwksjs** [comment]
BTW, maybe you should edit the title of the issue at "with root" part

**Comment by Satanarious** [comment]
> well, non root versions require micro-G, try installing micro-G first and open them

I had micro-G already installed.

**Comment by eisklwksjs** [comment]
> > well, non root versions require micro-G, try installing micro-G first and open them
> 
> I had micro-G already installed.

i see, try clearing data of youtube and its music variant, allow background run for micro-G;this should solve your issue

**Comment by Satanarious** [comment]
> > > well, non root versions require micro-G, try installing micro-G first and open them
> > 
> > I had micro-G already installed.
> 
> i see, try clearing data of youtube and its music variant, allow background run for micro-G;this should solve your issue

Did exactly what you asked for, still crashing

**Comment by eisklwksjs** [comment]
😥just want to know,did you enable background playback?

**Comment by Satanarious** [comment]
yes

**Comment by eisklwksjs** [comment]
well, myself too faced a force-close issue now, i believe it has to do something with those patches; first one i tried worked fine, in that i used
-amoled, client spoofing, disable create button, general ads, hide infocard, premium header, return youtube dislike, sponsor block, theme, video ads

-you can try micro g support for non root ones, i don't know if that gives an error; when i tried minimized playback, hide shorts, full screen panels,auto captions it crashed on launch; so i think one of these is buggy; try your luck

**Comment by Satanarious** [comment]
> well, myself too faced a force-close issue now, i believe it has to do something with those patches; first one i tried worked fine, in that i used
> -amoled, client spoofing, disable create button, general ads, hide infocard, premium header, return youtube dislike, sponsor block, theme, video ads
> 
> -you can try micro g support for non root ones, i don't know if that gives an error;but when i tried enabling minimized playback, hide shorts, full screen panels,auto captions it crashed on launch; so i think one of these is buggy; try your luck

Well for the time being I'm using the non-root installation.I Will come back if there's a solution in the future.Also, since it is in alpha right now,so I'm just doing my job as a user.

**Comment by eisklwksjs** [comment]
This hide shorts patch is buggy, finally😂

**Comment by Satanarious** [comment]
> This hide shorts patch is buggy, finally😂

Thanks for the info, nice work

**Comment by ponces** [comment]
If you plan to install in root mode, then you can't select MicroG patch.
Can you try to patch without it selected?

**Comment by Satanarious** [comment]
Yes, it worked. Thanks for the help. But I think there should be clearer instructions for the same.

**Comment by Satanarious** [comment]
Now that It opened without crashing, It seems like none of the patches were applied in root installation

**Comment by Satanarious** [comment]
> If you plan to install in root mode, then you can't select MicroG patch.
> Can you try to patch without it selected?

Now that It opened without crashing, It seems like none of the patches were applied in root installation.I didn't check it earlier because I thought that shouldn't be necessary. Same for both YT and YT Music

**Comment by Aunali321** [comment]
Try patching again and share logs.

**Comment by Satanarious** [comment]
I tried patching again and it worked. I donno why it didn't the other time. I'm closing this.
