### ISSUE TITLE
bug: <vanced gets stuck on logo on startup>

### ISSUE THREAD

**Issue by Masterchina123** [ReVanced/revanced-manager#777]
### Type

Other

### Bug description

The app will just stay on the logo and won't go any further I can't access any part of the app

### Steps to reproduce

Download and just try to open 

### Android version

13 on a Samsung s22

### Manager version

Version 57

### Target package name

Nan

### Target package version.

Nan

### Installation type

Non-root

### Patches selected.

Nan

### Device logs (exported using Manager settings).

```shell
Nan
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Nan
```

### Screenshots or videos

[Video evidence ](https://photos.app.goo.gl/ssE4JMPUq62gHJJL7) 

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by oSumAtrIX** [comment]
#392
