### ISSUE TITLE
bug: Keyboard Shortcut List keeps popping up if i do Ctrl+ any keys

### ISSUE THREAD

**Issue by OilSubjectLoss7** [revanced/revanced-manager#779]
### Type

Cosmetic

### Bug description

Keyboard shortcut list or Command list keeps popping up if i do CTRL+any keys

### Steps to reproduce

Step 1. play video
Step 2. Click back and click the search box
Step 3. click Ctrl + any key i.e. 'a'

### Android version

Android 11

### Manager version

0.57

### Target package name

?

### Target package version.

?

### Installation type

Non-root

### Patches selected.

all but one

### Device logs (exported using Manager settings).

```shell
?
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Aunali321** [comment]
Not related to manager.

**Comment by oSumAtrIX** [comment]
Unofficial tools are unsupported
