### ISSUE TITLE
bug: revanced manager can't import patch

### ISSUE THREAD

**Issue by Nosaqnx** [revanced/revanced-manager#780]
### Type

Error while running the manager

### Bug description

My captions appear top of the video and I downloaded a patch to solve this issue but the manager isn't importing the patch.

### Steps to reproduce

Normal

### Android version

12

### Manager version

0.0.57

### Target package name

Youtube

### Target package version.

18.05.40

### Installation type

Non-root

### Patches selected.

The recommended 

### Device logs (exported using Manager settings).

```shell
I couldn't do this step
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by badawoll** [comment]
> Steps to reproduce
>
> Normal

Care to share more information? What did you download, where did you find it, what did you do with it after downloading, what did you do within the manager?

With information currently available, it's next to impossible to figure out what's going on.

**Comment by PalmDevs** [comment]
> > > Steps to reproduce
> > > Normal
> > 
> > Care to share more information? What did you download, where did you find it, what did you do with it after downloading, what did you do within the manager?
> > 
> > With information currently available, it's next to impossible to figure out what's going on.
> 
> same for me, I was trying to install https://github.com/inotia00/revanced-patches but when i click import patches, no file selctor is opened and instead i get this toast
> 

Screenshots or screen recordings would be helpful. Thanks.

**Comment by ILoveOpenSourceApplications** [comment]
This issue requires some further explanation of what the actual issue is by word, screenshot or screen recording. If not this issue has to be closed as the issue itself is unclear.

**Comment by PranavPurwar** [comment]
@ILoveOpenSourceApplications 

https://github.com/revanced/revanced-manager/assets/75154889/f2b3373a-fccb-4e70-ab84-2331ea5804a3

**Comment by ILoveOpenSourceApplications** [comment]
Please show the screen recording from the very beginning.

**Comment by PalmDevs** [comment]
> @ILoveOpenSourceApplications 
> 
> I'm on Android 9
> 
> https://github.com/revanced/revanced-manager/assets/75154889/f2b3373a-fccb-4e70-ab84-2331ea5804a3
> 
> 

Have you give ReVanced Manager storage permissions?

**Comment by PranavPurwar** [comment]
Even after providing the permission and restarting, its still the same
