### ISSUE TITLE
Video stops and buffer logo appears

### ISSUE THREAD

**Issue by chabuco** [revanced/revanced-manager#781]
### Type

Error while running the manager

### Bug description

The patched app installs well but when i play a video, the video stops and the buffer logo appears. Usually this happens under a minute or so but not always. It's like the app stops loading new video data.

### Steps to reproduce

Play video.
Wait a minute or so or scroll the suggested video list.

### Android version

13

### Manager version

0.0.57

### Target package name

Youtube

### Target package version.

18.05.40

### Installation type

Non-root

### Patches selected.

Genrals ads v0.0.1
MicroG Support v0.0.1
Minimized playback v0.0.1
Video Ads v0.0.1

### Device logs (exported using Manager settings).

```shell
Deosn't allow me to post the log because its too long...
```

### Screenshots or videos

![Screenshot_20230414_180805_YouTube](https://user-images.githubusercontent.com/102320635/232164343-c3a86775-0531-4542-988c-4da815e34e8f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Schmensch** [comment]
I still have this issue. It's listed as fixed, what do I have to do to apply the fix?

**Comment by YungGeckoDick** [comment]
> I still have this issue. It's listed as fixed, what do I have to do to apply the fix?

X2 Still not fixed

![Screenshot_20230418-134248](https://user-images.githubusercontent.com/125703666/232861283-e545d712-be0b-409f-acf6-dabc7e9ad0c3.jpg)

**Comment by AhmedYasinKUL** [comment]
Same here.

**Comment by kirenida** [comment]
@AhmedYasinKUL @YungGeckoDick @Schmensch 

I had the same problem. The solution is to select the "Spoof signature verification" patch.
