### ISSUE TITLE
feat: Better Non-Root Error Messages

### ISSUE THREAD

**Issue by TangledTris** [ReVanced/revanced-manager#784]
### Type

Functionality

### Issue

The following error message can have a variety of causes:

"Non-root install is not possible with the current patches selection. Repatch your app or choose root install if you have your device rooted."

The error can be caused by:
- Not having MicroG installed
- Trying to patch the YouTube app installed by the Play Store instead of an APK in storage
- Not selecting "MicroG Support" patch

### Feature

If the error cases can be detected during the install process, then the following error messages would be more informative:
- Not having MicroG installed -> "Non-root install is not possible without MicroG installed. Install MicroG before repatching or choose root install if you have your device rooted."
- Trying to patch the YouTube app installed by the Play Store instead of an APK in storage -> "Selected YouTube APK cannot be patched without root permissions. Select a downloaded YouTube APK via "Select an application -> Storage" or choose root install if you have your device rooted."
- Not selecting "MicroG Support" patch -> "Non-root install is not possible without MicroG Support patch. Select MicroG Support patch before repatching or choose root install if you have your device rooted."

### Motivation

Easier installation process for non-root users. Current install instructions are confusing if a previous step was not performed correctly. For example, selecting recommended patches with a Play Store YouTube APK will cause MicroG Support to not be enabled when a valid APK is chosen later.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by exadeci** [comment]
I have Vanced manager  version 0.2.25.224113
I downloaded and installed YouTube from apkmirror
I've selected the micro g patch


I already had revanced installed and working

And I get this error message

**Comment by Abilash-22** [comment]
My apologizes for commenting under this thread!
For some reason Revanced Manager is not detecting root rather manager forces the Magisk app to crash.
It's so weird that I couldn't figure out a thing.
Is anyone familiar with this issue?
Any response would be much appreciated. 

Cheers!
