### ISSUE TITLE
bug: Revancesd Music doesn't download for offline

### ISSUE THREAD

**Issue by randoomdude** [revanced/revanced-manager#785]
### Type

Error while running the manager

### Bug description

You can't download anything on Revancesd Music (or now that I check YouTube Revancesd, though that one gives a prompt for premium, Music just acts like you didn't even tap download, just nothing.

### Steps to reproduce

Never worked

### Android version

Using latest recommended versions which I just updated to today, old versions had same problem

### Manager version

Latest 0.57

### Target package name

Music 

### Target package version.

5.39.52

### Installation type

Non-root

### Patches selected.

Revanced

### Device logs (exported using Manager settings).

```shell
Can't find
```

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by oSumAtrIX** [comment]
You need premium.
