### ISSUE TITLE
feat: Publish to f-droid

### ISSUE THREAD

**Issue by rollingmoai** [ReVanced/revanced-manager#79]
### Type

Other

### Branch

flutter

### Issue

It would be great if Revanced Manager is on f-droid.

### Feature

Add Revanced Manager is on f-droid.

### Motivation

F-droid is a convenient way to install FOSS apps to those without the Google Playstore, therefore I see a need for this.

### Additional context

[F-droid Website](https://f-droid.org/)

**Comment by Aunali321** [comment]
Manager is still ln alpha and should not be available on any store fronts.

**Comment by rollingmoai** [comment]
Even though, this should not be closed until it is completed.

**Comment by Aunali321** [comment]
It will take some time to make the manager stable.

**Comment by shuvashish76** [comment]
RFP: https://gitlab.com/fdroid/rfp/-/issues/2206

**Comment by IzzySoft** [comment]
@Aunali321 may I ask what the current state is? I see a stable release was tagged in March, so maybe "now is the time"?

**Comment by Aunali321** [comment]
> @Aunali321 may I ask what the current state is? I see a stable release was tagged in March, so maybe "now is the time"?

There is no stable release and there no plans to launch on f-droid yet.

**Comment by IzzySoft** [comment]
Ah, then I misinterpreted the `latest` label on v0.0.57 (which is not marked pre-release).

Thanks for reopening btw – and we'll then wait for "things to come", wishing you the best progress!

**Comment by masterflitzer** [comment]
> There is no stable release

v0.0.57 wasn't tagged as pre-release
v1.0.0 got released some time ago
v1.2.0 removed the alpha disclaimer

why isn't it considered stable when it's indirectly communicated through these actions?

**Comment by Ushie** [comment]
At the time of the last comment, v0.0.57 was the **latest** release, which was still an Alpha

This issue has been reopened, there's nothing that's says v1.0.0 isn't a stable release, nobody here has said that, we just haven't had the time or interest exactly to release it to F-Droid

**Comment by Ushie** [comment]
@IzzySoft Hey, do you know if we meet the official F-Droid repository's requirements? if so, is it too time consuming to release there?

**Comment by IzzySoft** [comment]
There is an open RFP, and the issuebot report there looks good. It just states that Fastlane structures are missing here in your app's repo (that's the way you maintain description and graphics to represent your app in the F-Droid catalog). Mind setting those up here? Be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance. The minimum needed is creating `/fastlane/metadata/android/en-US` and adding hort_description.txt` plus `full_description.txt` there – though I'd strongly recommend to also include a few screenshots and an icon (see the Cheat Sheet on where they should go).

**Comment by Ushie** [comment]
I'll look into this soon! possibly after my graduation.

**Comment by IzzySoft** [comment]
Then best wishes for that process first! When will that be (so we have an approx. ETA)?

**Comment by Ushie** [comment]
You could expect it between tomorrow and before the end of June

**Comment by Aunali321** [comment]
@IzzySoft can you review https://github.com/revanced/revanced-manager/pull/889?

**Comment by IzzySoft** [comment]
@Aunali321 LGTM. The only things F-Droid needs are inside `/fastlane/metadata/android`, so you could leave the other parts out – unless the project plans to use the fastlane binaries (e.g. `fastlane supply`). Metadata is also easily maintained "manually" (which is what most projects do in this case, i.e. to provide the metadata to F-Droid).

**Comment by Aunali321** [comment]
> @Aunali321 LGTM.

Thank you!. hopefully will be merge today or tomorrow.

**Comment by NicoWeio** [comment]
Since this has been stale for a few months: From what I gather, all that's missing is the YAML metadata? Could you use help with that, or is there something else missing?

**Comment by Ushie** [comment]
Yeah, it's only the YAML missing

I'd spent a while on it a few months back, but I remember coming into issues (though don't remember what they were) and I haven't gotten back to it

**Comment by Ushie** [comment]
I'm working on it now

**Comment by Issues66010222** [comment]
> Manager is still ln alpha and should not be available on any store fronts.

F-Droid is a repository library, I'm just saying that it would be awfully convenient to have Revance's APKs and whatnot in there regardless if the manager itself is in alpha, because F-Droid would actually be the alternative to ReVanced Manager. What's convenient with F-Droid is that it tells us if the software is compatible with our device, and we can update our apps from it.

**Comment by dgw** [comment]
> F-Droid would actually be the alternative to ReVanced Manager

Not true. Pre-patched APKs _will not_ be made available through F-Droid; only the Manager app itself.

Plus, you are responding to an almost-year-old comment that no longer reflects the issue state. As of last week, a project member [is working on the F-Droid metadata requirements](https://gitlab.com/fdroid/rfp/-/issues/2206#note_1426064371).

**Comment by quazar-omega** [comment]
> F-Droid would actually be the alternative to ReVanced Manager

Set aside the problem with distributing the modified YouTube APKs (which is already a big can of worms in and of itself) you can't publish proprietary apps on F-droid, regardless if the patches are free software, because they are just patches, made onto YouTube's proprietary application, only the Manager itself could be published there.

Also, if you did distribute patched APKs somewhere, how would you account for the ability of the user to choose the patches they want applied? At most you could deliver it with every single one applied and tell the user to tweak the in-app settings instead, but that's not great user experience

**Comment by oSumAtrIX** [comment]
The patches do not consist of the proprietary YouTube code and are authored under ReVanced.

**Comment by quazar-omega** [comment]
Yes, I was referring to @Issues66010222 that said to distribute Revanced (as in the patched app) through F-droid, I meant to explain why it couldn't be possible, while of course the manager and the patches are fine, hence why I said
> only the Manager itself could be published there.

**Comment by IzzySoft** [comment]
You can always run your own "binary repo" for things not being eligible for F-Droid.org. See e.g. my articles on [Setting up a simple binary F-Droid repo](https://android.izzysoft.de/articles/named/fdroid-simple-binary-repo) and [Extend the „simple binary repo“: Screenshots & more](https://android.izzysoft.de/articles/named/fdroid-simple-binary-repo-2). Those who want to use it can add it to their clients then, like they do with mine.

**Comment by Issues66010222** [comment]
> See e.g. my articles on [Setting up a simple binary F-Droid repo](https://android.izzysoft.de/articles/named/fdroid-simple-binary-repo) and [Extend the „simple binary repo“: Screenshots & more](https://android.izzysoft.de/articles/named/fdroid-simple-binary-repo-2).

Too long; didn't read. I'm not a code person, sorry.

What I meant to say was that I just need to be able to update my ReVanced app thru F-Droid, not necessarily download a fully patched app from it. I mean, what address should I use to add to Repositories (in F-Droid; "Add additional sources of apps”) so it can update the build I already have? I can't really use the official Manager, not even kitadai's Android 6-7 version, and it already gives me a headache to try to work with it. I just managed to find someone else's APK that works on my phone, but now I'm having trouble with the buff issue and it really just needs an update. I don't even remember where I got the APK/build.

**Comment by oSumAtrIX** [comment]
> What I meant to say was that I just need to be able to update my ReVanced app

If you refer to ReVanced Manager, it features updates already. There is no other "ReVanced app" besides ReVanced Manager.

**Comment by Ushie** [comment]
Please keep this issue on topic, F-Droid can't EVER feature patched app updates, because there's no such thing

Updating a patched app is required to be done in ReVanced Manager, how would F-Droid patch the app for you and publish it as an update? it's impossible

This issue is strictly for the one ReVanced app which is ReVanced Manager

**Comment by Issues66010222** [comment]
I don't get it, because I didn't patch my YouTube, my ReVanced is a standalone app that's designed to work on my old device. Surely F-Droid would be able to find a way to update the app if it's technically not a modified YouTube app, I just need to give it the right web address for the repo (possibly GitHub), right? Because none of the managers can work with what I have; I just downloaded a working APK, not patch/modify my pre-existing YouTube app.

**Comment by oSumAtrIX** [comment]
This discussion is not about patched apps, it's about publishing ReVanced Manager to F-Droid.

**Comment by Issues66010222** [comment]
I know, I got off topic. You guys keep working on it, I'm just sad that there's no convenient support for old devices like mine.

**Comment by masterflitzer** [comment]
> support for old devices

you cannot expect people who sacrifice their own time doing this amazing app to support back to android 6 just for you, just get a cheap phone with android 10 or something (reminder: android 14 comes out this year)

**Comment by quazar-omega** [comment]
@Issues66010222 You can still build the APK with a PC with the [cli](https://github.com/ReVanced/revanced-cli/tree/main/docs) and then install it on your phone

**Comment by Issues66010222** [comment]
I'm too broke to even get a new phone, and this old phone is the only one I got (no PC). I really don't have any other options.

I'll just end it here.

**Comment by quazar-omega** [comment]
That's a pity, afraid I'm out of suggestions :/

**Comment by shuvashish76** [comment]
> I have Android 6.0.1 OS
ReVanced is a standalone app that's designed to work on my old device

No it's not which is clearly mentioned in [readme](https://github.com/ReVanced/revanced-manager#-prerequisites). For further discussion better join their official discord or reddit.

>  F-Droid would be able to find a way to update the app if it's technically not a modified YouTube app.

[F-Droid](https://f-droid.org/en/about/) is for FOSS apps only & unlike other app stores here applications in the repository are built from source doesn't matter if it's mod/fork or whatever you call it.

>  I just need to give it the right web address for the repo (_possibly GitHub_), right?

No that's not how F-Droid works, better ask F-Droid related questions in their [forum](https://forum.f-droid.org/).
For now no need to worry about any repo address as devs are trying to publish on _official_ F-Droid repo. [Docs/guide](https://github.com/ReVanced/revanced-documentation) will be updated with instructions if they decide to use their own repo instead.

**Comment by Ushie** [comment]
I've looked into this for a while, I tried to work with what we have right now but it just overcomplicated the build script, as we use GitHub Packages and that's not a trusted repo in F-Droid, so I've decided the best path going forward would be publishing our packages on maven

Once our repositories are setup to publish to a trusted maven repository, this can be continued as it would be a simple 3 command script then

**Comment by Ushie** [comment]
This is no longer planned due to complications with settling with a trusted maven repository, ReVanced has switched back to GH Packages.
