### ISSUE TITLE
question: location of apk file recompiled by revanced manager in the android file explorer?

### ISSUE THREAD

**Issue by SaiyajinK** [revanced/revanced-manager#790]
### Type

Other

### Bug description

Hi,

Like many people today, youtube vanced has stopped working. so I switched to official revanced with [this](https://www.reddit.com/r/revancedapp/comments/xlcny9/revanced_manager_guide_for_dummies/) tutorial

I recompiled the official youtube apk with the revamped manager 0.0.57, everything works fine.

My question is, could you tell me the directory where the rebuilt apk is stored please? because in my android file explorer I can't find it? (i'm on no rooted device)

Thanks in advance

### Steps to reproduce

-

### Android version

EMUI 12 (p30)

### Manager version

0.0.57 : [here](https://github.com/revanced/revanced-manager/releases/tag/v0.0.57)

### Target package name

com.google.android.youtube

### Target package version.

18.05.40 (nodpi) (Android 8.0+)

### Installation type

Non-root

### Patches selected.

Recommended

### Device logs (exported using Manager settings).

```shell
-
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
-
```

### Screenshots or videos

-

### Solution

-

### Additional context

-

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Julius8900** [comment]
The apk that the manager generates after patching is temporary. When you install ReVanced or exit the patcher, you lose it.

To prevent this issue, after patching finishes, you'll have the option to export the apk that the manager created by tapping the three-dot icon, and then tap "Export APK".

**Comment by SaiyajinK** [comment]
It was so simple... 😅 Thanks !
