### ISSUE TITLE
Have a different icon to the ReVanced app

### ISSUE THREAD

**Issue by RyanStarr** [revanced/revanced-manager#794]
### Type

Functionality

### Issue

I recently updated the manager. Now the manager and ReVanced app have the exact same icon. When you want to use the recommended app switcher in Samsung. It's a 50/50 chance of getting the correct app (sometimes it's easier to launch applications this way rather than scrolling through previous applications).
![Screenshot_20230420_031442_One UI Home](https://user-images.githubusercontent.com/16529414/233241129-9957e81a-ee09-467c-84bf-9ec4740600bc.png)

### Feature

By having a slightly different icon (like it used to be in the past) it will make it obvious that the recommended application is the ReVanced manager and not the ReVanced player

### Motivation

It isn't a difficult change to make and it makes interacting with the ReVanced applications more user friendly.

### Additional context

Likely only an issue for Samsung devices (unless other brands also have the same app switcher feature).

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Currently ReVanced only has this icon. For that reason another one is not present, will change soon though
