### ISSUE TITLE
feat: <Is MicroG still needed>

### ISSUE THREAD

**Issue by mklr95** [revanced/revanced-manager#796]
### Type

Other

### Issue

MicroG no longer appears in the prerequisites, is MicroG still needed and if yes why did it get removed from the prerequisites in the README.md?

### Feature

Editing the readme to include microg again or a warning that it isnt needed anymore.

### Motivation

Wanted to make a video showing a friend how to do it but saw that the readme was modified yesterday.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
MicroG is not a prerequisite, it never has been, it was incorrectly added to the README due to a few revanced patches that depended on it
