### ISSUE TITLE
bug: v0.1.0,v0.1.1 cannot be installed over v0.0.57

### ISSUE THREAD

**Issue by psydvl** [revanced/revanced-manager#802]
### Type

Other

### Bug description

v0.0.57 have version code 57 ~~1000001800~~ 
v0.1.0 have version code 1 ~~1000001798~~ 
So, for android, v0.1.0 is downgrade, but not update 

### Steps to reproduce

1. Install v0.0.57 
2. Try to update with v0.1.0
3. Face update error

### Android version

Any

### Manager version

v0.0.57

### Target package name

Not related

### Target package version.

Not related

### Installation type

Non-root

### Patches selected.

Not related

### Device logs (exported using Manager settings).

```shell
None
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Julius8900** [comment]
Try uninstalling 0.0.57, then install 0.1.0.

**Comment by psydvl** [comment]
> Try uninstalling 0.0.57, then install 0.1.0.

It's a crutch, not a solution: 
You need then backup+restore patches and keystore, and reclick not backupable settings

**Comment by psydvl** [comment]
I was wrong about version code 
The one in AndtoidManifest should be different too

<details>
![Screenshot_2023-04-21-00-50-42-63_824de691399edbc594a434a2aa0f3de5.jpg](https://user-images.githubusercontent.com/43755002/233495342-718b9982-dfa7-47fb-b480-8f14ac6e3ded.jpg)

![Screenshot_2023-04-21-00-50-24-04_824de691399edbc594a434a2aa0f3de5.jpg](https://user-images.githubusercontent.com/43755002/233495341-6c740738-b506-4ad3-8b54-9a7e25bd39c8.jpg)

**Comment by Aunali321** [comment]
Do you know any possible solutions?

**Comment by psydvl** [comment]
https://stackoverflow.com/questions/53570575

**Comment by Ushie** [comment]
Yeah, but that's not a good solution, we have no use for versionCode anymore and throwing a random permanent versionCode like 57 or anything above (ikr 100 just for the sake of it) is a terrible solution

**Comment by Ushie** [comment]
Is there a way to do this without explicitly stating versionCode anymore?

**Comment by Ushie** [comment]
Hey! thanks for your tip, I read the android docs about this and we'll go through with bumping the versionCode to 58 
![SmartSelect_20230421_012406_Chrome](https://user-images.githubusercontent.com/79272171/233499908-d22e44ab-9d5b-4020-8f55-7a8ae912f8ce.jpg)

**Comment by SodaWithoutSparkles** [comment]
Or alternatively, set the version code to the current date/GMT date/UNIX timestamp automatically such that the new version would never have a lower versionCode

**Comment by Masamune3210** [comment]
> > Try uninstalling 0.0.57, then install 0.1.0.
> 
> It's a crutch, not a solution: You need then backup+restore patches and keystore, and reclick not backupable settings

Just a heads up, at least for me, settings and selections persisted uninstalling the old app and installing the new version

**Comment by wolf-yuan-6115** [comment]
> > > Try uninstalling 0.0.57, then install 0.1.0.
> > 
> > It's a crutch, not a solution: You need then backup+restore patches and keystore, and reclick not backupable settings
> 
> Just a heads up, at least for me, settings and selections persisted uninstalling the old app and installing the new version

Probably not for keystores

**Comment by SodaWithoutSparkles** [comment]
Yeah, I have tried. Even if you have the cloned the orginal keystore in android/data, you could not put it back and expect it to work.
