### ISSUE TITLE
feat: would you put the app on fdroid soon?

### ISSUE THREAD

**Issue by not-programmer98** [revanced/revanced-manager#804]
### Type

Other

### Issue

Downloading APKs from GitHub doesn't seem a convenient way for installing apps 

### Feature

The app is open source why isn't on fdroid?

### Motivation

You mentioned here that it's still in beta #79 but it's working great now, actually fdroid is a great place for a beta app, you wouldn't get comments there because something is wrong or getting just one star bad review.
It's a good place for beta apps, all users there are expecting to find bugs

### Acknowledgements

- 

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.

- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
Closing this and re-opening #79
