### ISSUE TITLE
Add a **New** text on latest patches. 

### ISSUE THREAD

**Issue by fard33n** [ReVanced/revanced-manager#808]
### Type

Cosmetic

### Issue

Since a lot of patches are being added, it has become a but cluttered especially for the ReVanced YouTube patches. It is very difficult to keep track of the patches added in the manager. 

### Feature

The *NEW* highlight over the latest patches added with be very helpful for users are repatching the app for updates. Will help to create a distinction between older patches that may or may not have been already selected and the lastest added ones so that the user can easily go through them. 

### Motivation

This feature should be considered to improve the user experience which selecting patches whose number is increasing day by day. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
This feature should work as follows:

- If a new patch is recognized by ReVanced Manager, it must label it as new and highlight it by pinning it at the top of the patches list. Depending on if the patch is included by default or not, select it, or don't select it by default
- If the new patch is included by default, the patch should be included by default by ReVanced Manager provided that the user has never made their own custom selection even once and left the selection as it was originally
- If a patch has been deleted, ReVanced Manager must issue a notice.
- If a new patch is available or a patch has been deleted, the patcher screen of ReVanced Manager should let the user know
- Once the user patches their app at least once after the addition or removal of patches, all current "New" labels or notices must be removed until the next time, when new patches are added or removed

**Comment by fard33n** [comment]
Yes that is a better solution.

**Comment by ILoveOpenSourceApplications** [comment]
Completed with the merge of #1099.
