### ISSUE TITLE
bug: Uncheck "Hides the cast button in the video player" but run ReVanced and can't see the Chromecast function

### ISSUE THREAD

**Issue by minimoonleaf** [revanced/revanced-manager#809]
### Type

The manager repacking youtube, Chromecast function disappear

### Bug description

I use default repacking Youtube and open ReVanced Youtube and play a video can't see the chromecast button.
I try uncheck "Hides the cast button in the video player" repacking Youtube but run ReVanced still can't see the Chromecast function

### Steps to reproduce

Open Official Youtube play a video, and the screen have a chromecast buttom can send the screen to chrome.

Cast 1:
1.ReVanced manager patches Recommended to repacking Youtube.
2.Install ReVanced Youtube
3.Open ReVanced Youtube and play a video
4.The Chromecast function can't fund on video

Case 2:
1.ReVanced manager patches uncheck "Hides the cast button in the video player"  to repacking Youtube.
2.Install ReVanced Youtube
3.Open ReVanced Youtube and play a video
4.The Chromecast function can't fund on video

### Android version

Android 12
ROG phone 3 system:31.0210.0210.258

### Manager version

0.0.57

### Target package name

Youtube

### Target package version.

18.08.37

### Installation type

Non-root

### Patches selected.

Hide Cast Button
or
Recommended

### Device logs (exported using Manager settings).

```shell
Log is too long, so I put google drive:
https://drive.google.com/file/d/1TeLhdAJfVqYtSEMPShp4J9F__xyyT9nJ/view?usp=share_link
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Log is too long, so I put google drive:
https://drive.google.com/file/d/1-2-8zScKGDB87_9mr9pInUFsweYE2fwY/view?usp=share_link
```

### Screenshots or videos

Official Youtube:
https://photos.app.goo.gl/Vj9svkkScpfbUFBQA

ReVance Youtube:
https://photos.app.goo.gl/qKW113vRRvEg93HV9

### Solution

Fix chrome function buttom.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by ILoveOpenSourceApplications** [comment]
It's not a bug. `Vanced microg support` patch contains a hide-cast-button patch. So if you include the microg patch, it is forced to be included. It's done intentionally.

**Comment by minimoonleaf** [comment]
> It's not a bug. `Vanced microg support` patch contains a `hide cast button` patch. So if you include the microg patch, it is forced to be included. It's done intentionally.

Then why is there a Patch "Hides the cast button in the video player" to choose?
Why provide this feature if it cannot be customized?

The Chromecast function is already included in Youtube. Why does it want to remove this function by default? And it doesn’t allow users to choose?
And this topic does not solve the most fundamental problem, which is how to use Chromecast?

**Comment by Ushie** [comment]
> Why does it want to remove this function by default?

it's not by default, you're selecting the vanced microg support patch which includes it

you can configure it in settings to show the cast button again but you'll have to use TV code etc

**Comment by minimoonleaf** [comment]
> > Why does it want to remove this function by default?
> 
> it's not by default, you're selecting the vanced microg support patch which includes it
> 
> you can configure it in settings to show the cast button again but you'll have to use TV code etc

When "Vanced microg support" is not used, the mobile phone without Root will not be able to install and use, so the "Vanced microg support" function is almost necessary, so this is not called a default?
Or when you select the Recommand mode Patching, the preset includes "Vanced microg support", and when "Vanced microg support" is used, "Chromecast support" will be removed, so calling the ReVanced preset will remove "Chromecast support" shouldn't be a problem, right?

So the premise of the current discussion is that there must be "Vanced microg support" to complete the follow-up operations, right?
So how to make the "Chromecast" function available when there is "Vanced microg support"?
I tried to remove "Hides the cast button in the video player" when the Patch mode is Recommand, and connected Chromecast in ReVanced Youtube's settings > On TV watch function, but there is still no Chromecast function for playing videos can use

Pictures of the operation steps (sorry for the Chinese interface, but try to increase the English mark to know what the operation is)
https://photos.app.goo.gl/SzdD5hvqPLykbAXo6

**Comment by hros** [comment]
What are the steps for the current version of revanced youtube to enable the casting button on videos?

**Comment by Stan-Stani** [comment]
@hros Settings Revanced Player "Hide Cast Button"
