### ISSUE TITLE
bug: incorrect changelog for patched application

### ISSUE THREAD

**Issue by afnzmn** [revanced/revanced-manager#81]
### Type

Cosmetic

### Branch

flutter

### Bug description

The changelog for installed patched applications is the most recent update, instead of the changelog for the installed version.

### Steps to reproduce

1. have an installed patched app through manager
2. wait for app patches to get updates
3. check changelog in installed section

### Relevant log output

```shell
nop
```

### Screenshots or videos

![Screenshot_20220914-221135](https://user-images.githubusercontent.com/47723802/190296984-6ee6c434-5497-4bca-ad4e-c05232773cac.png)
![Screenshot_20220914-221131](https://user-images.githubusercontent.com/47723802/190296986-79b7d19b-0791-4614-979e-796e41e7fc7c.png)

### Additional context

:guh:

**Comment by ponces** [comment]
Makes sense.
I'll look into it.
Thanks!

**Comment by ponces** [comment]
"Fixed".
Apps with updates will only appear on "Updates available" page.
