### ISSUE TITLE
feat: Please separate the function of "Remove Chromecast" from the "Vanced microg support" patch

### ISSUE THREAD

**Issue by minimoonleaf** [revanced/revanced-manager#811]
### Type

Functionality

### Issue

Please separate the function of "Remove Chromecast" from the "Vanced microg support" patch or provide an option that can be enabled, otherwise Chromecast cannot be used, which is very troublesome

### Feature

Add a switch can enable chromecast or disable chromecast

### Motivation

Chromecast is the default function of Youtube, please restore the function to ReVanced for users to use.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Casting does not reliably work with Vanced MicroG. For that reason it is disabled when Vanced MicroG is used. You can enable it in the settings regardless of that.

**Comment by minimoonleaf** [comment]
> Casting does not reliably work with Vanced MicroG. For that reason it is disabled when Vanced MicroG is used. You can enable it in the settings regardless of that.

Have you really tried the Chromecast function? 
Are you sure that the Chromecast function can be enabled in the settings?

I've tried everything I know so far and can't get Chromecast to work
Even setting ReVanced Youtube > Settings > On TV watch > connecting chrome device
However, after the settings are completed, the Chromecast function still cannot be played when playing videos. Because of this, I suggest removing "Chromecast remove" from "Vanced microg support", because there is currently no way to make the Chromecast function work normally. It can even be said that the function of Chromecast is abnormal. I don’t understand why the developers keep emphasizing what they think is correct without trying to confirm that the function of Chromecast is completely unusable on ReVanced?
Pictures of the operation steps (sorry for the Chinese interface, but try to increase the English mark to know what the operation is)
https://photos.app.goo.gl/SzdD5hvqPLykbAXo6

I posted this question in the Bug issue in different ways, but I think everything is just perfunctory.
https://github.com/revanced/revanced-manager/issues/809

**Comment by adalast** [comment]
> Casting does not reliably work with Vanced MicroG. For that reason it is disabled when Vanced MicroG is used. You can enable it in the settings regardless of that.

Is there a way to use Vanced without MicroG?  I use casting a lot and I really would like to benefit from the ReVanced, but using the "connect to device" option means that I am still using the default YouTube casting app, complete with BS and ads.  I have found the option to turn on the cast button, but I cannot find anything in the MicroG settings.  I'm ok with it being unstable, but this implementation is a null method.

**Comment by oSumAtrIX** [comment]
This is ReVanced, if you need support from Vanced, please do so in their support places.

**Comment by adalast** [comment]
I'm confused, I'm trying to cast from ReVanced.  I just noticed I missed the "Re" on my post.

**Comment by Ushie** [comment]
Hide cast patch is included with MicroG Support for a reason, Cast v2 isn't supported by MicroG

You can unhide the cast button in YouTube ReVanced settings -> layout
