### ISSUE TITLE
bug: Chromecast > Connect to a device, show No device found, but chromecast is online, but can't be found.

### ISSUE THREAD

**Issue by minimoonleaf** [revanced/revanced-manager#812]
### Type

Other

### Bug description

Connect to a device, show No device found, but chromecast is online, but can't be found.

### Steps to reproduce

1.ReVanced manager > patch by Recommand > install
2.ReVanced Youtube> Settings > ReVanced > Layout > disable "Hide cast button" 
3.Play a video
4.Click chromecast > show "Connect to a device" > but wait a while show "No device found"

When use app "home" the chromecast is work. But In ReVanced Youtube can't be found.
https://photos.app.goo.gl/QdgiV3edMdXRpN7DA

### Android version

12
ROG 3

### Manager version

0.0.57

### Target package name

Youtube

### Target package version.

18.08.37

### Installation type

Non-root

### Patches selected.

Recommand

### Device logs (exported using Manager settings).

```shell
Need what? tell me
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Axelen123** [comment]
In order to work without root, we have to use Vanced MicroG instead of the Google play services implementation that comes with your device.  MicroG does not support chromecast, and that is why hide cast button is enabled by default when doing a non-root install.

Install with the root method or use another app if you want to chromecast

**Comment by minimoonleaf** [comment]
Maybe this Project can help
https://gitlab.gnome.org/GNOME/gnome-network-displays/-/merge_requests/171
Hope there is a chance that ReVanced can also support Chromecast functions
