### ISSUE TITLE
feat: Show installed patcher version on the main patcher tab

### ISSUE THREAD

**Issue by TheDeviantCrafter** [revanced/revanced-manager#814]
### Type

Functionality

### Issue

When installing an app via the ReVanced Manager, the patcher version is displayed in the top corner. After an app is installed the only way to get the patcher version is to try to patch a different app. The patcher version seems like important information when troubleshooting.

In my case, I had Youtube ReVanced installed already and wanted to verify that my patcher was up to date. The only way to get that info was to try to patch a different app and read the patcher version from the 

### Feature

Show the currently installed patcher version somewhere prominent. I suggest the top right corner of the main patcher tab.

### Motivation

The patcher version is important for troubleshooting. Making this information available may increase the quality of bug reports.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
The patcher version isn't really useful for the user and should instead be removed.
