### ISSUE TITLE
bug: <He doesn't buffer>

### ISSUE THREAD

**Issue by ibandino** [revanced/revanced-manager#815]
### Type

Error at runtime

### Bug description

So I'm just a Vanced user for years and I've noticed in the last few days that the app worked but then again not via account login and tell me something about a new version where........... Unfortunately, the new version doesn't work because it doesn't buffer ......... every video breaks off within the first 20 seconds at some point ......I use Android 12 on Huawei MatePad SE and MatePad Pro , with both devices the same problem with the buffer .... I therefore first looked at devices from other manufacturers and there are the same problems.....guys....please.....don't break the precious app that worked wonderfully until you tinkered with it the last few days , I still thought youtube or google is going against but when I noticed that the original vanced app disappeared from all app stores and this one appeared where the logo isn't right either , I got suspicious and now saw that you are the reason for the problems here .....please don't break the app for me ..... otherwise I have to look in the browser again .... put the original app back online and first tinker with the new one and put it online somewhere separately ....... I'll never watch YouTube with ads anyway, but if you bug the only smart app, then that's it...... Personally, I still think it's really easy to create a browser clone with YouTube native as a website variant , since version problems update themselves through the native website ..... but that doesn't exist and Vanced is the only app in the world "that's really good".... So please don't break this piece of gold my friends ..... you would put a tear in my eye with that 

### Steps to reproduce

android 12 all deviced

### Android version

android 12 \ HarmonyOS 3.x.x.x \

### Manager version

it doesn't matter ... the originals from back then via sd but the manager has apparently been replaced everywhere on all websites and he also publishes the buggy version 

### Target package name

keine ahnung ..... an der die letzten tage rum gebastelt wurde 

### Target package version.

an der die letzten tage rum gebastelt wurde 

### Installation type

Non-root

### Patches selected.

🤯

### Device logs (exported using Manager settings).

```shell
Bei allen geräten ... unabhängig vom model
```

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Androidonator** [comment]
I am having the same issue with the video not getting any data after first 20-50 seconds.

**Comment by SodaWithoutSparkles** [comment]
either you enable signature spoofing, or you close the video and start again.
