### ISSUE TITLE
feat: improve suggested app version text

### ISSUE THREAD

**Issue by Ushie** [revanced/revanced-manager#818]
### Type

Cosmetic

### Issue

Right now, ReVanced Manager shows a `recommended version` when selecting an application, the wording may be a bit confusing to the user as it's only a recommendation

### Feature

Switch `recommended` for `supported`, this will clarify that things are likely NOT going to work if you don't follow the supported version

### Motivation

Clarification for which version of the app should be patched and reduce the number of people confused due to their patched application not working

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by KobeW50** [comment]
I'm just confused as to why in 1.1.0 it says "Suggested" instead of "Supported" even after this was marked completed.

Suggested is a soft word.

**Comment by Ushie** [comment]
> I'm just confused as to why in 1.1.0 it says "Suggested" instead of "Supported" even after this was marked completed.
> 
> Suggested is a soft word.

You can read the associated issue where discussion happened
