### ISSUE TITLE
App is not actually installed (yet) when manager says so

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-manager#819]
### Type

Error while running the manager

### Bug description

Manager does not check if the installed version is the one patched just now

### Steps to reproduce

1. Patch YT with latest manager version
2. Make sure revanced is already installed
3. After patching, click install, but don't confirm the dialogue yet
4. Look at the bottom behind the blackened screen, revanced manager thinks the app was updated/installed when you havent actuallt installed it yet

### Android version

13

### Manager version

0.1.0 (or is it 0.1.1?)

### Target package name

com.google.youtube

### Target package version.

18.15.40

### Installation type

Non-root

### Patches selected.

Not relevant

### Device logs (exported using Manager settings).

```shell
Not relevant
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Not relevant
```

### Screenshots or videos

![IMG_20230428_160959](https://user-images.githubusercontent.com/64138578/235092351-ba3beb67-1bda-4ad3-8903-b18e826e02d1.jpg)
_Note that the red text have been translated into English_

### Solution

When patching, also modify the version code to include the UNIX timestamp or a nonce. Like changing it from `18.15.40` to `18.15.40-1682669613`. This way, RV manager can check it against the expected one and know if the new one is installed or not, instead of displaying it when the button is pressed

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by KobeW50** [comment]
This causes some people to wonder where the app went because it said it was installed but they don't see it in the app drawer

**Comment by KobeW50** [comment]
The app does not already need to exist on the device for this bug to occur. It always says "Installed!" when the install button is pressed, even if the package name does not exist on the device. But the timestamp solution will still be useful when dealing with app updates, (although wouldn't a hash be simpler? Idk these things though 🤷)

Also, if the user exits the manager app while the package installer pop-up prompt of "Do you want to install/update this app?" is present, the pop-up will disappear. And upon re-entering the manager, the manager will just say "Open" and makes it seem like it has been successfully installed.

Although the pop-up disappearing can be blamed on the package installer, the "Open" button and the "Installed!" text should not appear unless the app has indeed been installed.

https://github.com/revanced/revanced-manager/assets/84587632/8b81b280-a6ea-4ff5-9b25-37b736573eea

**Comment by Ushie** [comment]
There's no need for a hashmap, timestamp in the version code or anything of the likes of that, Package Manager will return a callback with the result of the installation

**Comment by SodaWithoutSparkles** [comment]
What if the user decides not to use package manager, but sth like SAI or Shizuku to install?

**Comment by EvadeMaster** [comment]
🎉 The fix for this issue have been in #1021 and released in ReVanced Manager v1.4.1

If problem persist, feels free to reopen this issue!
