### ISSUE TITLE
bug: downgraded / mirrored apk's dont get detected by Manager

### ISSUE THREAD

**Issue by EGirlEnthusiast** [revanced/revanced-manager#82]
### Type

Error while running the manager

### Branch

flutter

### Bug description

If you update youtube from playstore, and the app is required by the system, so the most you can do without root is disable it, installing a downgraded version will cause the app to downgrade properly, but stop revanced manager from finding it, meaning you cannot patch it.

### Steps to reproduce

Device must consider youtube as a system app.

Update app from playstore,
upon downgrading by installing an old apk youtube will not appear in revanced manager

### Relevant log output

```shell
n/a
```

**Comment by ponces** [comment]
> Upon downgrading by installing an old apk youtube will not appear in revanced manager

How can you even downgrade a system app? Is this really possible without some hacky tool?

**Comment by l-eber-a-c-87** [comment]
> > Upon downgrading by installing an old apk youtube will not appear in revanced manager
> 
> How can you even downgrade a system app? Is this really possible without some hacky tool?

Doesn't even need root, inside the App Info menu there's an option to uninstall all the updates from "system apps", then you can apply the update downloaded from ApkMirror since the PlayStore doesn't allow you to choose and you would be stuck with the latest version if someone wasn't using ReVanced before (or someone didn't know they needed a version that is already pretty old).

**Comment by EGirlEnthusiast** [comment]
> How can you even downgrade a system app? Is this really possible without some hacky tool?

The only thing it doesn't normally let you do is uninstall completely, so installing a youtube apk over top of it works as expected, treats it like an update for youtube, but for my OnePlus 7t renders the manager unusable, unfortunatly, as it doesnt give me the option to select it in the "Select Application" menu

**Comment by kgvarunkanth** [comment]
> ### Type
> Error while running the manager
> 
> ### Branch
> flutter
> 
> ### Bug description
> If you update youtube from playstore, and the app is required by the system, so the most you can do without root is disable it, installing a downgraded version will cause the app to downgrade properly, but stop revanced manager from finding it, meaning you cannot patch it.
> 
> ### Steps to reproduce
> Device must consider youtube as a system app.
> 
> Update app from playstore, upon downgrading by installing an old apk youtube will not appear in revanced manager
> 
> ### Relevant log output
> ```shell
> n/a
> ```
> 
> ### Screenshots or videos
> _No response_
> 
> ### Solution
> _No response_
> 
> ### Additional context
> _No response_

I got the same problem lol

**Comment by ILoveOpenSourceApplications** [comment]
Is this still an issue even with the recent manager versions?

**Comment by ILoveOpenSourceApplications** [comment]
@Ushie the reported issue doesn't seem to exist anymore, so can't this be closed?
