### ISSUE TITLE
bug: aborting, file not found during installation 

### ISSUE THREAD

**Issue by Zenahr** [ReVanced/revanced-manager#824]
### Type

Error while running the manager

### Bug description

followed the instructions outlined here: https://www.reddit.com/r/revancedapp/comments/xlcny9/revanced_manager_guide_for_dummies/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

while installing, getting an error. Seems to related to the app not finding a file in cache.

### Steps to reproduce

See link above

### Android version

13

### Manager version

latest

### Target package name

as per guide linked above

### Target package version.

latest supported as per the official docs

### Installation type

Non-root

### Patches selected.

chose "recommended" as per guide linked above.

### Device logs (exported using Manager settings).

```shell
Initializing installer

Creating working directory Copying original apk

Unpacking input apk.

Reading dex files

Decoding AndroidManifest.xml only, because An error occurred! Aborting org.jf.dexlib2.DexFileFactory$DexFileNotFoundEx unPatcher$lambda-20 (MainActivity.kt:170) at app.revanced.manager.flutter.MainActivity. $r8$lambda$kxvfcFiIKARIH6oxYjk9gWWxjp8 (Unknown Source:0)

resources are not needed Merging integrations

Error:

ception: 58e5ec30-

e5e8-11ed-9f12-67b562a14062.bin does not exist

at org.jf.dexlib2. DexFileFactory.loadDexFile(D

exFileFactory.java:83)

at org.jf.dexlib2.DexFileFactory.loadDexFile(D exFileFactory.java:61)

at app.revanced.patcher.util.patch. PatchBundle $Dex.LoadPatches (PatchBundle.kt:71)

at app.revanced.manager. flutter.MainActivity.r

at app.revanced.manager.flutter.MainActivity$ $ExternalSynthetic Lambda13.run(Unknown Source:22)
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer

Creating working directory Copying original apk

Unpacking input apk.

Reading dex files

Decoding AndroidManifest.xml only, because An error occurred! Aborting org.jf.dexlib2.DexFileFactory$DexFileNotFoundEx unPatcher$lambda-20 (MainActivity.kt:170) at app.revanced.manager.flutter.MainActivity. $r8$lambda$kxvfcFiIKARIH6oxYjk9gWWxjp8 (Unknown Source:0)

resources are not needed Merging integrations

Error:

ception: 58e5ec30-

e5e8-11ed-9f12-67b562a14062.bin does not exist

at org.jf.dexlib2. DexFileFactory.loadDexFile(D

exFileFactory.java:83)

at org.jf.dexlib2.DexFileFactory.loadDexFile(D exFileFactory.java:61)

at app.revanced.patcher.util.patch. PatchBundle $Dex.LoadPatches (PatchBundle.kt:71)

at app.revanced.manager. flutter.MainActivity.r

at app.revanced.manager.flutter.MainActivity$ $ExternalSynthetic Lambda13.run(Unknown Source:22)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by eliyahillel** [comment]
Happened to me too, even after cleaning app cache and updating "manager" to the new version, 
and it got resolved when I did an "unpatch".

**Comment by RePlay-be** [comment]
I had the same issue after upgrading from ReVanced Manager from December. Looks like I got fixed after clearing the temp files and doing a reinstall of the Manager.

**Comment by SodaWithoutSparkles** [comment]
> Happened to me too, even after cleaning app cache and updating "manager" to the new version, 
> and it got resolved when I did an "unpatch".

@eliyahillel how did you "unpatch"? Explain briefly

**Comment by SodaWithoutSparkles** [comment]
@Zenahr by any chance you are using a oppo device?

**Comment by eliyahillel** [comment]
> > Happened to me too, even after cleaning app cache and updating "manager" to the new version,
> > and it got resolved when I did an "unpatch".
> 
> @eliyahillel how did you "unpatch"? Explain briefly

Umm in the manager's dashboard when you press the "info" button for one of the apps, there's an "Unpatch" button.

**Comment by SodaWithoutSparkles** [comment]
> Umm in the manager's dashboard when you press the "info" button for one of the apps, there's an "Unpatch" button.

There is "uninstall", there is "patch", there isn't a button "unpatch"

**Comment by eliyahillel** [comment]
> > Umm in the manager's dashboard when you press the "info" button for one of the apps, there's an "Unpatch" button.
> 
> There is "uninstall", there is "patch", there isn't a button called "unpatch"

There is for me. maybe you aren't using the root installation method...
![Screenshot_20230507-152446_ReVanced Manager](https://user-images.githubusercontent.com/73447394/236677529-032c73a6-3a1a-466c-b4e7-eedc7e223d0b.png)

**Comment by Zenahr** [comment]
> @Zenahr by any chance you are using a oppo device?

yes.

**Comment by oSumAtrIX** [comment]
Should be fixed.
