### ISSUE TITLE
bug: App verification did not succeed.

### ISSUE THREAD

**Issue by 2021521** [revanced/revanced-manager#83]
### Type

Other

### Branch

#83  issue: Can't install the app.

### Bug description

Hi, I use the manager  to generate an app but my android, Harmony OS 2, said "App verfication did not succeed." What should I do?  

### Steps to reproduce

nothing.

### Relevant log output

```shell
nothing.
```

### Screenshots or videos

![image](https://user-images.githubusercontent.com/49866394/190299566-e324c664-a04f-4b4d-9d9a-5a6eb731789e.png)

**Comment by eisklwksjs** [comment]
Signature mismatch is most likely, uninstall previous version and clean install

**Comment by eisklwksjs** [comment]
non root? check package name (there shouldn't be any app with the same package name); if root, try "disable signature verification" patch in "patch to android" in luckypatcher and try installing your mod

**Comment by ponces** [comment]
You should not install your chosen app. Download it, open Manager, select it from storage (Storage button on Patcher screen) and then proceed with patching. Install should only be made after patching on Installer screen.
