### ISSUE TITLE
blackscreen after 40-50 sec

### ISSUE THREAD

**Issue by IDLEGLANCE** [revanced/revanced-manager#834]
### Type

Error while running the manager

### Bug description

i dont know where to report bugs for YouTube revanced itself but if i watch any video it doesnt matter which the video stops and instead of showing the video Thumbnail it is just a blackscreen and infinite loading Screen i tried multiple things such as Clearing the cache re-patching and reinstalling the app nothing helps. please help?

### Steps to reproduce

i dont really know how i did it but i just used the app

### Android version

13 One-UI 5.1

### Manager version

the latest i think, it doesnt say i need to update it in the Manager itself 

### Target package name

youtube

### Target package version.

v18.15.40

### Installation type

Non-root

### Patches selected.

• Client Spoof
• Copy Video Url
• Custom Branding
• Disable Shorts On Startup
• Disable Zoom Haptics
• Downloads
• General Ads
• Hide Cast Button
• Hide Player Buttons
• Hide Shorts Button
• Minimized Playback
• Open Links Externally
• Remember Video Quality
• Sponsorblock
• Spoof App Version
• Theme
• Vanced MicroG Support
• Video Ads

### Device logs (exported using Manager settings).

```shell
-
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
-
```

### Solution

-

### Additional context

-

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by reisxd** [comment]
Acknowledgements not met.

**Comment by IDLEGLANCE** [comment]
> Acknowledgements not met.

thanks for helping

**Comment by Ushie** [comment]
You can try checking the issues on the revanced patches repository, we don't have anything to do with patches so we can't really help you

**Comment by IDLEGLANCE** [comment]
> You can try checking the issues on the revanced patches repository, we don't have anything to do with patches so we can't really help you

thanks i found Something about that problem i think its fixed now, thanks:)
