### ISSUE TITLE
bug: can't import file from storage

### ISSUE THREAD

**Issue by lazyjinchuriki** [revanced/revanced-manager#840]
### Type

Error while running the manager

### Bug description

Can not import file from storage. It keeps crashing

### Steps to reproduce

Step 1 : updated to latest version
Step 2 : import from storage
Step 3 : app crashed and navigated to home screen.

### Android version

Android 13

### Manager version

0.1.0

### Target package name

Youtube

### Target package version.

18.15.40

### Installation type

Non-root

### Patches selected.

Can't select patch

### Device logs (exported using Manager settings).

```shell
No device logs.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by ILoveOpenSourceApplications** [comment]
This issue should be fixed with the latest release of the manager. Please check and reply.

**Comment by lazyjinchuriki** [comment]
Yes. I can import files now.
