### ISSUE TITLE
feat: Change patched YouTube icon

### ISSUE THREAD

**Issue by Tarek-Hasan** [revanced/revanced-manager#841]
### Type

Cosmetic

### Issue

Yea, I know, this issue has been discussed many times before and you guys have planned it for the future.
But in the meantime, you guys could have rotated the Revanced icon 90 degree and call it a day. Like the following example:

![101597779](https://user-images.githubusercontent.com/27731012/235629862-f8900c0c-4df8-49dd-8ade-0df3f9775a68.png)

Or you can use my modified version of the Revanced icon if you like.

![custom ytrevanced](https://user-images.githubusercontent.com/27731012/235634091-9a5e3c91-23a4-4333-ac1f-79b8076f363f.svg)

### Feature

as above

### Motivation

as above

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by ILoveOpenSourceApplications** [comment]
There's a [ReVanced Branding ](https://github.com/revanced/revanced-branding) repository present where these discussions can be made. The team is currently focusing on the manager and patched applications, hence not much attention is being provided to branding. This will change in the future.
