### ISSUE TITLE
bug: revanced manager v0.1.0 apk has wrong app version (v1.0.0)

### ISSUE THREAD

**Issue by masterflitzer** [revanced/revanced-manager#842]
### Type

Other

### Bug description

downloading and installing the revanced manager v0.1.0 apk from github results in app version v1.0.0

### Steps to reproduce

1. download revanced-manager-0.1.0.apk
2. install it
3. go to app info in android and scroll down to version

cli:

1. `curl -LsO https://github.com/revanced/revanced-manager/releases/download/v0.1.0/revanced-manager-0.1.0.apk`
2. `apkanalyzer manifest version-name revanced-manager-0.1.0.apk`

### Android version

Android 13 - OneUI 5.1

### Manager version

that's the issue, is it 0.1.0 or 1.0.0?

### Target package name

N/A

### Target package version.

N/A

### Installation type

Non-root

### Patches selected.

N/A

### Device logs (exported using Manager settings).

```shell
N/A
```

### Screenshots or videos

![screenshot](https://user-images.githubusercontent.com/60170948/235687902-61151d6a-3f87-4dca-860e-6ea8b9dee687.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by jaepil-choi** [comment]
@masterflitzer , I downloaded 0.1.0.apk while it was live and successfully installed it on my phone and it's working fine. Why has the 1.0.0 version been deleted? Also, README said that stale development state is now over but that has been rolled back as well. Was there a fatal flaw in version 0.1.0? (which is displayed as 1.0.0 in app info)

**Comment by masterflitzer** [comment]
@jaepil-choi well it was working for me too but obviously something went wrong because otherwise the versions would match

deleting this release made this issue redundant (I didn't notice the deletion until know)
