### ISSUE TITLE
bug: revanced manager offers wrong update version

### ISSUE THREAD

**Issue by masterflitzer** [revanced/revanced-manager#843]
### Type

Error while running the manager

### Bug description

revanced manager internal update functionality offers pre-releases from github instead of stable releases

pre-releases shouldn't be offered (or only from pre-release versions)

### Steps to reproduce

1. download the currently latest stable release (https://github.com/revanced/revanced-manager/releases/download/v0.1.0/revanced-manager-0.1.0.apk)
2. install and open app
3. on the dashboard revanced manager offers a dev version (pre-release on github)

### Android version

Android 13 - OneUI 5.1

### Manager version

github: v0.1.0
in app: v1.0.0

i opened a seperate issue about versions not matching: #842 

### Target package name

N/A

### Target package version.

N/A

### Installation type

Non-root

### Patches selected.

N/A

### Device logs (exported using Manager settings).

```shell
N/A
```

### Screenshots or videos

![screenshot](https://user-images.githubusercontent.com/60170948/235691693-e91e2b3e-1844-4d33-811a-a96ed61577b7.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Rafee-M** [comment]
The 1.0 release was removed

**Comment by AnonymouseHucker29** [comment]
> The 1.0 release was removed?

Yes, it's not in the _releases_ section already

**Comment by jaepil-choi** [comment]
But  why has it been removed? I installed it upon release and it's working fine.

**Comment by oSumAtrIX** [comment]
Because it was not working fine, please do not spam issues.

**Comment by masterflitzer** [comment]
the fundamental issue of offering pre-releases as updates to full releases is still there no? is this unwanted behavior or not? I mean if not everything can be a release and pre-releases don't matter at all

**Comment by Ushie** [comment]
The capability of returning pre-releases in the API is not yet achieved, it's likely that it was a mistake elsewhere such as the name of the release or the release type not being what it should've been
