### ISSUE TITLE
bug: Old Revanced maneger not working for new letest YouTube version need letest version of revanced maneger 🙂

### ISSUE THREAD

**Issue by gamerxgithub** [revanced/revanced-manager#846]
### Type

Error while running the manager

### Bug description

Old revanced maneger not working for YouTube letest version.. need updated new  revanced maneger 🙂

### Steps to reproduce

Null

### Android version

Null

### Manager version

Null

### Target package name

Null

### Target package version.

Null

### Installation type

Non-root

### Patches selected.

Null

### Device logs (exported using Manager settings).

```shell
Null
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by reisxd** [comment]
Acknowledgements not met.

**Comment by EvadeMaster** [comment]
👋 Hello, NullCube here!

You're required to use ReVanced Manager version 0.0.57 or newer, this is because ReVanced Patcher has major breaking changes. For more information on the changes on ReVanced Patcher, please check the repository for the patcher.
