### ISSUE TITLE
Question: Regarding architecture in the about section 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [revanced/revanced-manager#851]
### Type

Cosmetic

### Bug description

So if we visit the about section within the latest manager, the arch says the following: [arm64-v8a, armeabi-v7a, armeabi]. Is this supposed to mean that the manager supports the following architectures? If not then shouldn't it be only showing the architecture of the device in which the manager is installed? This was the way how it was in the past right? So is this a bug or is it an intended change?

### Steps to reproduce

Just go into manager settings and scroll down.

### Android version

Android 13

### Manager version

1.0.0

### Target package name

ReVanced Manager 

### Target package version.

Nil

### Installation type

Non-root

### Patches selected.

Nil

### Device logs (exported using Manager settings).

```shell
Nil
```

### Screenshots or videos

![Screenshot_20230506-055345](https://user-images.githubusercontent.com/117499019/236602948-43ad3e28-b331-4ed5-b8f9-ac1ae06f7b35.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Ushie** [comment]
Your device supports all these architectures

**Comment by ILoveOpenSourceApplications** [comment]
So if it's a device having arm-v7a architecture it'll only mention that?
