### ISSUE TITLE
Provide more information in the install/patch logs

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-manager#852]
### Type

Functionality

### Issue

Patch logs does not show the pkgName/version used to patch. When install/patch fails people usually do a screenshot and ask for help

### Feature

Showing the pkg name / version patched at both the start phase (initializing installer) and the final phase (Finished). Sth like this:

```
Initializing Installer
patching <package name> @<version>
...
Finished patching <package name> @<version>!
```

### Motivation

This can provide more information when doing tech support

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by SodaWithoutSparkles** [comment]
There should also be an entry in the logs saying what sources they are using. We ain't doing tech support for RVX.

**Comment by Ushie** [comment]
This might be relevant to the patcher repo instead, what do you think? @oSumAtrIX

**Comment by SodaWithoutSparkles** [comment]
So manager just use patcher under the hood?

**Comment by Ushie** [comment]
ofcourse

**Comment by SodaWithoutSparkles** [comment]
Yeah, then it would be better in the patcher repo. Cuz manager just dumps out patcher's output, so IF patcher knows the information, patcher should output it instead.

Could you please transfer this to the patcher repo?

**Comment by Ushie** [comment]
We don't have permissions to transfer issues to the patcher repository, you'll have to create a new one

**Comment by SodaWithoutSparkles** [comment]
@Ushie you can, if you have write permission. 

https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

**Comment by Ushie** [comment]
we don't have any permissions

**Comment by oSumAtrIX** [comment]
> This might be relevant to the patcher repo instead, what do _you_ think? @oSumAtrIX

Sure, they should open a new issue so it can be tracked.
