### ISSUE TITLE
Patches Not Showing bug: <title>

### ISSUE THREAD

**Issue by Prathamalhotra** [revanced/revanced-manager#855]
### Type

Error while running the manager

### Bug description

In the latest version revanced manager 1.0.0 patches of inotia00 not showing/available after selecting the recommended version of YouTube, But on 0.57 it shows patches on recommended version of YouTube but the selected patches have not effect on YouTube Yt shorts don't hide material you don't work and many other problem please look into this

### Steps to reproduce

No

### Android version

13

### Manager version

1.0.0
0.57

### Target package name

YouTube : com.google.android.youtube

### Target package version.

YouTube 18.16.39

### Installation type

Non-root

### Patches selected.

Recommended 

### Device logs (exported using Manager settings).

```shell
No
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
No
```

### Screenshots or videos

No

### Solution

No

### Additional context

No

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by oSumAtrIX** [comment]
Unofficial patches/Issue with them.

**Comment by Prathamalhotra** [comment]
> Unofficial patches/Issue with them.

What do you want to say, plz explain.
