### ISSUE TITLE
Create a different icon for manager

### ISSUE THREAD

**Issue by hichemfantar** [revanced/revanced-manager#856]
### Type

Cosmetic

### Issue

Both manager and youtube have the same icon which confuses the user causing him to open the wrong app sometimes.

### Feature

The manager should have a different icon than the YouTube revanced icon to remove confusion between the 2.

### Motivation

Reduce confusion between the manager and the YouTube player.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
This issue should be brought up in the ReVanced patches repository, as the ReVanced manager correctly represents the brand identity of ReVanced as it should be
