### ISSUE TITLE
bug: last patches timestamp showes pre-releases

### ISSUE THREAD

**Issue by Lugieda** [revanced/revanced-manager#858]
### Type

Cosmetic

### Bug description

The timestamp displayed under "Dashboard" -> "Updates" -> "Revanced Patches" displayes the timestamp of the most recent release, even if it is a pre-release. To show the timestamp for the release with the "latest"-tag woud make more sense

### Steps to reproduce

Open the app on the dashboard

### Android version

13

### Manager version

1.0.0 & 1.1.0

### Target package name

none

### Target package version.

none

### Installation type

Non-root

### Patches selected.

none

### Device logs (exported using Manager settings).

```shell
--------- beginning of main
05-08 18:40:44.903 26290 26290 E SurfaceSyncer: Failed to find sync for id=0
05-08 18:40:44.903 26290 26290 E SurfaceSyncer: Failed to find sync for id=1
05-08 18:40:44.903 26290 26290 E SurfaceSyncer: Failed to find sync for id=2
05-08 18:41:35.188 26290 26290 E SurfaceSyncer: Failed to find sync for id=0
05-08 18:41:35.188 26290 26290 E SurfaceSyncer: Failed to find sync for id=1
05-08 18:41:35.188 26290 26290 E SurfaceSyncer: Failed to find sync for id=2
05-08 18:41:35.188 26290 26290 E SurfaceSyncer: Failed to find sync for id=3
05-08 18:42:36.590 26290 26290 E SurfaceSyncer: Failed to find sync for id=0
05-08 18:42:36.590 26290 26290 E SurfaceSyncer: Failed to find sync for id=1
05-08 18:42:36.590 26290 26290 E SurfaceSyncer: Failed to find sync for id=2
05-08 18:42:36.590 26290 26290 E SurfaceSyncer: Failed to find sync for id=3
05-08 18:42:36.590 26290 26290 E SurfaceSyncer: Failed to find sync for id=4
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
none
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Ushie** [comment]
The correct place for this issue would be in the ReVanced Releases API repository
