### ISSUE TITLE
feat: Add a recommended app version section 

### ISSUE THREAD

**Issue by praveenpkallambalam** [revanced/revanced-manager#86]
### Type

Functionality

### Branch

The main branch.

### Issue

Currently no way to identify which version of app got the most patches and support.

### Feature

Add a section for recommended app version. Optionally can add download links to third-party websites to download these.

### Motivation

It really help some unguided souls in this ocean.

**Comment by ponces** [comment]
Not a bad idea. A screen/dialog which shows every compatible package and its latest compatible version.
I'll look into this.
Thanks.

**Comment by WelsonLiong** [comment]
This is pretty important for new users as many of them do not know which version of YouTube should be used.

**Comment by ponces** [comment]
Added on https://github.com/revanced/revanced-manager/commit/ce6f11f3f2c6188ac31a51a0aa2d3bb057326bb3.
Closed.
