### ISSUE TITLE
KernelSU post-fs-data & service.d

### ISSUE THREAD

**Issue by thepaleguy** [ReVanced/revanced-manager#860]
### Type

Functionality

### Issue

so root method is working with kernelSU and the patch is working. but if you reboot your device the patch is no longer working.
so i copy the folders "post-fs-data & service.d sh files included" to /data/adb and give them permission, and after rebooting the patch still working😁

### Feature

honestly no idea

### Motivation

kernel su is good

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Kronodile** [comment]
Can you specify a bit more. I have kernelsu too and after rebooting, all my patches disappeared

**Comment by LitoHDD** [comment]
> Can you specify a bit more. I have kernelsu too and after rebooting, all my patches disappeared

I have the same problem, do you know anything about it?

**Comment by LitoHDD** [comment]
I have the same problem, do you know anything about it?

**Comment by oldman20** [comment]
thank that a teporary solution until this time

**Comment by thepaleguy** [comment]
> thank that a teporary solution until this time
> 
> But where is the folders "post-fs-data & service.d sh files included"? in my case used Manager 1.3.2 only exist original.apk + base.apk in /data/local/tmp/revanced-manager

sh files not really needed, but before you patch make sure you have folders " post-fs-data.d & service.d" in /data/adb/ and chmod 755, sh files will be added to that after you patch.

**Comment by LitoHDD** [comment]
> > gracias que una solución temporal hasta este momento
> > Pero, ¿dónde están las carpetas "archivos post-fs-data & service.d sh incluidos"? en mi caso, Manager 1.3.2 usado solo existe original.apk + base.apk en /data/local/tmp/revanced-manager
> 
> Los archivos sh no son realmente necesarios, pero antes de parchear, asegúrese de tener las carpetas "post-fs-data.d & service.d" en /data/adb/ y chmod 755, los archivos sh se agregarán después de parchear.

I can't find the files anywhere, could you explain it better?

**Comment by Ushie** [comment]
Can you test if this is solved in the latest version?

**Comment by TBM13** [comment]
I can confirm this issue is still present on the latest manager version (v1.6.1).
@thepaleguy 's workaround worked for me too
