### ISSUE TITLE
bug: Spoof Signature Verification option not there

### ISSUE THREAD

**Issue by criticic** [revanced/revanced-manager#863]
### Type

Error while running the manager

### Bug description

Whenever i try to patch my yt with the spoof sognature patch, so as to avoid the buffering issue, i cannot find this patch in the patch selection menu

### Steps to reproduce

Goto patch selection 

### Android version

9

### Manager version

1.1.0

### Target package name

youtube

### Target package version.

18.16.37

### Installation type

Non-root

### Patches selected.

General Patches, except the spoof signature which is not visible

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
05-09 23:21:05.305 27607 27607 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.16.37-1537338816_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #41
05-09 23:26:41.997 27607 27607 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.16.37-1537338816_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #41
05-09 23:30:22.161   858   858 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.16.37-1537338816_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #41
05-09 23:46:37.289  6475  6475 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.google.android.youtube_18.16.37-1537338816_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #41
```

### Screenshots or videos

![Screenshot_20230509-234650](https://github.com/revanced/revanced-manager/assets/40538506/879431b2-9039-4627-af33-3afa61c71804)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by oSumAtrIX** [comment]
The patch does not exist. It is called spoof-client.

**Comment by criticic** [comment]
Still does not solve the buffering issue, video plays for a bit and starts buffering. I have to close and reopen video, so that it plays again for a bit.

**Comment by oSumAtrIX** [comment]
In that case you did something wrong.

**Comment by Kobewaxman** [comment]
> Still does not solve the buffering issue, video plays for a bit and starts buffering. I have to close and reopen video, so that it plays again for a bit.

When did you patch with the client spoof patch?
