### ISSUE TITLE
bug: "DexFileNotFoundException" while patching Youtube

### ISSUE THREAD

**Issue by Tenneb22** [revanced/revanced-manager#868]
### Type

Error while running the manager

### Bug description

I deleted temporary files, reinstalled Revanced Manager, etc. But I get the same error every time (even on Revanced v0.0.57)

### Steps to reproduce

Downloaded Revanced, MicroG, Youtube APK, installed Revanced and MicroG, selected the Youtube APK and the default patches, while Patching, i got the error.

### Android version

13

### Manager version

latest (v1.1.0)

### Target package name

Youtube 

### Target package version.

v18.16.37

### Installation type

Non-root

### Patches selected.

The default ones

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
An error occurred! Aborting
Error:
org.jf.dexlib2.DexFileFactory$DexFileNotFoundException: 584d8030-f182-11ed-ad47-1519cb894ccf.bin does not exist
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:83)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:61)
	at app.revanced.patcher.util.patch.PatchBundle$Dex.loadPatches(PatchBundle.kt:71)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:175)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
An error occurred! Aborting
Error:
org.jf.dexlib2.DexFileFactory$DexFileNotFoundException: 584d8030-f182-11ed-ad47-1519cb894ccf.bin does not exist
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:83)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:61)
	at app.revanced.patcher.util.patch.PatchBundle$Dex.loadPatches(PatchBundle.kt:71)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:175)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by sssh7710** [comment]
Version 18.16.36 is not in the support list

**Comment by andrisas** [comment]
> Version 18.16.37 is not in the support list

It is the latest supported youtube version

**Comment by SodaWithoutSparkles** [comment]
One user reported on discord that the issue seems to be the OS is aggressively deleting cache, causing the files manager is currently using to be deleted.

Source: https://discord.com/channels/952946952348270622/1089391900181676062

Does manager forgot to set a write lock?

**Comment by Tenneb22** [comment]
> One user reported on discord that the issue seems to be the OS is aggressively deleting cache, causing the files manager is currently using to be deleted.

Thanks for the info with the cache, I just disabled some optimization settings, deleted temporary files and it worked!
(don't know what exactly fixed it, but still fixed) 
 
> Also, check your phone arch version. Armv7 device may sometimes cause this issue

**Comment by Tenneb22** [comment]
>One user reported on discord that the issue seems to be the OS is aggressively deleting cache, causing the files manager is 
currently using to be deleted.

Thanks for the info with the cache, I just disabled some optimization settings, deleted temporary files and it worked!
(don't know what exactly fixed it)

>Also, check your phone arch version. Armv7 device may sometimes cause this issue

As Revanced manager say I have arm64-v8, this wasn't propably the issue
