### ISSUE TITLE
feat: Show screen DPI in Info About section

### ISSUE THREAD

**Issue by drobotk** [revanced/revanced-manager#870]
### Type

Functionality

### Issue

Some apps come in different target Screen DPI flavours, and currently one has to use tools like Droid Hardware Info to find out the screen DPI.

### Feature

Show Screen DPI in the About section in Manager Settings, in the Info section at the bottom (below Arch, for example).

### Motivation

It would make it easier to choose the correct APK to download for patching.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
Aren't full APKs always no-dpi?

**Comment by drobotk** [comment]
It seems like there is always a nodpi version available on APKMirror, but they say it's better to, if possible, choose a DPI version most suitable for your device.

https://www.apkmirror.com/faq/#If_there_are_both_nodpi_and_specific_dpi_APKs_available_which_one_should_I_download

**Comment by Ushie** [comment]
> It seems like there is always a nodpi version available on APKMirror, but they say it's better to, if possible, choose a DPI version most suitable for your device.
> 
> https://www.apkmirror.com/faq/#If_there_are_both_nodpi_and_specific_dpi_APKs_available_which_one_should_I_download

A DPI version means that it is a split APK, which is not supported by ReVanced Patcher at the moment, showing device DPI in ReVanced Manager is pointless in that case as its not needed to be used to pick the APK file.

For ReVanced, you'd always want to pick the nodpi version
