### ISSUE TITLE
bug/question: Can't update revanced youtube, only install from scratch

### ISSUE THREAD

**Issue by dajotim937** [revanced/revanced-manager#874]
### Type

Other

### Bug description

I would select question label, there isn't such issue type.

So, before 1.* version I could patch new youtube version and install it without uninstalling previous version.
With 1.* manager I can't do that. I have to remove previous version and then new one will install. This is annoying because I have to set settings every new youtube installation.

Is this bug or this is how it would be from now?

### Steps to reproduce

1. Have installed previous patched youtube.
2. Patch new one
3. Try to install without removing previous version.
4. Can't install.

### Android version

9

### Manager version

1.1.0

### Target package name

Youtube

### Target package version.

18.16.37 -- new one
And don't remember recommended previous version

### Installation type

Non-root

### Patches selected.

Client Spoof,
Copy Video Url,
Custom Branding,
Custom Video Speed,
Disable Auto Captions,
Disable Fullscreen Panels,
Disable Player Popup Panels,
Disable Shorts On Startup,
Disable Zoom Haptics,
Downloads,
General Ads,
Hdr Auto Brightness,
Hide Album Card,
Hide Artist Card,
Hide Autoplay Button,
Hide Breaking News Shelf,
Hide Cast Button,
Hide Crowdfunding Box,
Hide Email Address,
Hide Floating Microphone Button,
Hide Get Premium,
Hide Player Buttons,
Hide Video Action Buttons,
Hide Watch In Vr,
Hide Watermark,
Minimized Playback,
Navigation Buttons,
Old Quality Layout,
Open Links Externally,
Premium Heading,
Remember Video Quality,
Remove Screenshot Restriction,
Return Youtube Dislike,
Seekbar Tapping,
Spoof App Version,
Theme,
Vanced MicroG Support,
Video Ads,
Wide Searchbar

### Device logs (exported using Manager settings).

```shell
-
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by dajotim937** [comment]
Oh, okay. Thanks.

**Comment by Ushie** [comment]
alternatively if you intend to do any of those, you should use Export keystore in Settings to save your keystore and use Import keystore to restore it afterwards

**Comment by dajotim937** [comment]
Got it. Good to know that. Thank you.
