### ISSUE TITLE
feat: Remove ability to export root apks

### ISSUE THREAD

**Issue by KobeW50** [revanced/revanced-manager#875]
### Type

Functionality

### Issue

There is no use case where an apk that is missing the microg support patch can be installed after it has been exported from the Manager.

(Read B in the addition context section below if this is untrue for rooted users)

### Feature 

Remove the ability to export apks that will not be able to be installed (because it is missing the microg support patch).

This can be implemented as a pop-up that appears when the user attempts to use the 'Export APK' or 'Share APK' option. A warning will appear. The warning will be similar to the "Non-Root installation is not possible..." dialog that appears for non-root users when they press the "Install" button within the Manager. The wording of this error dialog needs to be modified slightly. Changes to the wording are in bold (for demonstration)

Non-root dialog:

"Error

Non-Root installation will not be possible with the current patches selection. Repatch your app or use the Install button within the Revanced Manager on a rooted device if you want to install as root."

Rooted dialog:

"Error

Root installation is not possible with an exported APK. Use the Install button to mount the app."

Tbh idk anything about root installs or mounting so I won't be surprised if the rooted dialog needs changes.

(Although I have many complaints with the wording of the normal warning dialog for when the install button is used on a non-rooted device, I'll wait for progress on #784. For now we'll keep both non-rooted warnings similar)

The dialog box will have an "OK" button.

### Motivation

I have seen some non-root users export the apk after accidentally excluding the Vanced MicroG Support patch. When they try to install it they get an "App not installed as package conflicts with an existing package." 

This is ofc because it's trying to update YouTube, but very few users would be able to figure this out on their own. Best to stop this from ever happening. 

### Additional context

A) Everything I said should also apply to YTM Revanced.

B) I may be completely mistaken about how root installs can work. But regardless of whether an exported root apk can be used by a rooted user, the warning should still pop-up for a non-rooted user. The popup's wording would be different than described above. And the popup would have a "Cancel" button and an "OK" button.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
> Remove the ability to export apks that will not be able to be installed (because it is missing the microg support patch).

"Root" APKs are not a thing. A full APK file can be patched, exported, and installed from the device. If we remove that feature, then it would be a feature regression. ReVanced Manager is agnostic to any patch, thus it can also not be aware of the "vanced-microg-support" patch.

What can be done is, that if a split apk is chosen, that ReVanced Manager does not allow exporting it, because split apk installation has to be done by ReVanced Manager with root. For that, please open a new issue specifically.
