### ISSUE TITLE
feat: improve UX in regards of displaying the suggested version in app list

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/revanced-manager#876]
### Type

Error while running the manager

### Bug description

ReVanced Manager shows the suggested version in the app list. This string can be interpreted as the app's version currently installed on the device.

### Manager version

1.1.0

### Installation type

Non-root

### Solution

Redesign the app card content. For example, the current app version may be shown next to the app name. The package name should be hidden as it has no actual use for the end user, and instead, the app card should clarify that the suggested version is a suggested version.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Ushie** [comment]
This issue is speaking about here 
![Screenshot_20230518_214306](https://github.com/revanced/revanced-manager/assets/79272171/4cc945c5-32f3-441a-b6bc-b64ff1fedc4c)

By the way, 1.0.0+ does still have what you're portraying 
![Screenshot_20230518_214255](https://github.com/revanced/revanced-manager/assets/79272171/c3dad671-8b0d-4bad-a00d-87edb7793747)

**Comment by theofficialgman** [comment]
where is the feature? there is only one version displayed. what is that version? is that suggested or current?
that is what this issue is about. the UI does NOT specify what the version is depicting.

**Comment by Ushie** [comment]
yes... that's what the issue is about

**Comment by theofficialgman** [comment]
> By the way, 1.0.0+ does still have what you're portraying ![Screenshot_20230518_214255](https://user-images.githubusercontent.com/79272171/239351822-c3dad671-8b0d-4bad-a00d-87edb7793747.jpg)

you can't get to this page without first selecting an apk from storage. negating the entire purpose of checking revanced manager for current vs recommended version.

this was a feature without selecting any apk from storage on pre-1.0.0 and is no longer the case on 1.0.0+, meaning this is a regression, a feature that was removed

**Comment by Ushie** [comment]
Yes, that is an issue, but it has nothing to do with what you said above, this issue is specifically about clarifying the suggested version in the **applist**, you mentioning the suggested version that is shown in the patcher screen (which is still an existing feature, that is not removed as you stated in your first comment) isn't directly tied to this issue, you saying this wasn't the case before v1.0.0 misleads into thinking it was a recent change that made it worse in the **applist**, when the suggested version wasn't ever shown there in the first place

**Comment by theofficialgman** [comment]
> Yes, that is an issue, but it has nothing to do with what you said above, this issue is specifically about clarifying the suggested version in the **applist**, you mentioning the suggested version that is shown in the patcher screen (which is still an existing feature, that is not removed as you stated in your first comment) isn't directly tied to this issue, you saying this wasn't the case before v1.0.0 misleads into thinking it was a recent change that made it worse in the **applist**, when the suggested version wasn't ever shown there in the first place

well the applist is worse now. it has a version that is meaningless where before it had none and you could actually enter the patcher screen without an apk to see both the current and recommended version. now you have an undefined version in the applist and no way to view the current/recommended version in the patcher screen.

**Comment by PalmDevs** [comment]
> > Yes, that is an issue, but it has nothing to do with what you said above, this issue is specifically about clarifying the suggested version in the **applist**, you mentioning the suggested version that is shown in the patcher screen (which is still an existing feature, that is not removed as you stated in your first comment) isn't directly tied to this issue, you saying this wasn't the case before v1.0.0 misleads into thinking it was a recent change that made it worse in the **applist**, when the suggested version wasn't ever shown there in the first place
> 
> well the applist is worse now. it has a version that is meaningless (what is it? current or recommended, that is the point of this issue) where before it had none and you could actually enter the patcher screen without an apk to see both the current and recommended version. now you have an undefined version in the applist and no way to view the current/recommended version in the patcher screen.
> 
> even if the string "suggested/recommended" is added before the version in the applist thats still useless without the current version also being listed. users don't have their current app version memorized. you might as well remove the number entirely until the current version can also be shown in the applist

That's literally what the issue is, and the proposed solution is that. Re-read the issue. 😕
