### ISSUE TITLE
bug: Selected patches re-used w/o checking for version compatibility

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-manager#883]
### Type

Error while running the manager

### Bug description

Manager remembers selected patches w/o checking if the patches are applicable to the app version

### Steps to reproduce

1. Patch YT 18.16.37 w/ all default patches, but don't install
2. Select any unsupported YT version (e.g. 17.32.38) to patch
3. Notice that the same set of patches are selected
4. Try to select patches manually
5. Notice that manager actually recognize the version is not supported, but it still auto-selects
6. The same issue also appear when importing patches selection

### Android version

13

### Manager version

1.2.0

### Target package name

com.android.google.youtube

### Target package version.

18.16.37
17.32.38 (factory defaults)

### Installation type

Non-root

### Patches selected.

All defaults

### Device logs (exported using Manager settings).

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by ILoveOpenSourceApplications** [comment]
Isn't this same as your issue #560?

**Comment by Ushie** [comment]
This issue regards remembering last selected patches, the other one regards importing patches, while the resulting issue is the same, the code is separate, though if this issue is edited to include the other issue, it can be closed in favor of this one

**Comment by SodaWithoutSparkles** [comment]
> Isn't this same as your issue #560?

It seems that it is the case. I am going to close #560 because that is well over half a years old and got 0 attention.

**Comment by TheAabedKhan** [comment]
Fixed by #942

**Comment by SodaWithoutSparkles** [comment]
@TheAabedKhan Maybe this should be left open until it got released to stable?

**Comment by TheAabedKhan** [comment]
@SodaWithoutSparkles It's already released with the version 1.3.6
