### ISSUE TITLE
Move Export button next to the Install button

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#886]
### Type

Cosmetic

### Issue

The export button is kinda hidden, and some people won't realize that it is an option.

### Feature

Place the Export/Save APK button beside the Install button at the patch end-screen.

### Motivation

Improved UX

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by tejasbadone** [comment]
Hey, I would like to work on this, can you please assign it to me?

**Comment by Ushie** [comment]
How would you achieve this? there are already 2 buttons (install and install as root) which is ideally the maximum amount of buttons

**Comment by oSumAtrIX** [comment]
@Ushie A popup can show the installation variants. The popup can be shown, when clicking on"Install". This would free the existing second button

**Comment by tejasbadone** [comment]
will add a new button in the row inside the Visibility widget and will use sizedbox for the space. and will remove "Export APK" from the CustomPopupMenu. the rooted devices will see three buttons and non-root will see two


Visibility(
                              visible: !model.isInstalled,
                              child: const SizedBox(
                                width: 16,
                              ),
                            ),

Visibility(
                              visible: !model.isInstalled,
                              child: CustomMaterialButton(
                                label: I18nText('installerView.exportApkMenuOption'),
                                isExpanded: true,
                                onPressed: () => model.exportResult(),
                              ),
                            ),

**Comment by Ushie** [comment]
> the rooted devices will see three buttons and non-root will see two

I'm not sure if we're meant to go with as many as 3 buttons in a single row, let's see what Palm says

**Comment by PalmDevs** [comment]
> How would you achieve this? there are already 2 buttons (install and install as root) which is ideally the maximum amount of buttons

@Ushie The new Installer screen design in the Figma somewhat already fixes that. Check it out.

**Comment by PalmDevs** [comment]
> > @Ushie A popup can show the installation variants. The popup can be shown, when clicking on"Install". This would free the existing second button
> 
> @PalmDevs Can you review this design proposal? 

Looks good to me. However, I'm adding on to the proposal that we do not need to show the dialog to non-root users because they can't select any other installation types anyway. I'm thinking of a dialog with list items that have radio buttons.

**Comment by oSumAtrIX** [comment]
@PalmDevs I'd suggest to simply disable selecting the radio option for root installation. This will allow the user to know that a root installation is available instead of hiding it completely which then the user wouldn't know the option even exists. A "?" button or similar means can then explain why it is disabled.
