### ISSUE TITLE
feat: Display app specific patches/universal patches in different tabs

### ISSUE THREAD

**Issue by n1cKz1** [ReVanced/revanced-manager#888]
### Type

Functionality

### Issue

Currently, while patching an app, the app's specific patches and the universal patches (aka the ones that can be used on every app) are all displayed on the same menu, together. This can be quite confusing for the average user. (e.g People reporting crashes after trying to use spoof wifi connection and remove screenshot restriction on YT, which makes zero sense)

### Feature

My idea is that these 2 categories of patches are separated in 2 different tabs/menus on top of the patches page. One for app-specific patches, and the other for universal patches. Ideally, there would also be an explanation box on the universal patches page about their use, and a warning to the user about the possible side effects or their compatibility.

### Motivation

This would be a huge improvement to the UI and would make the app much simpler to use for the average user, especially those who mostly care about having every feature and check every patch on the list without doing much research.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
@PalmDevs is something like this possible in the upcoming design?

**Comment by PalmDevs** [comment]
> @PalmDevs is something like this possible in the upcoming design? 

Sure, I can add filter chips below the tab selector.
