### ISSUE TITLE
YouTube Vanced ORI Patch

### ISSUE THREAD

**Issue by TheKingTermux** [revanced/revanced-manager#89]
### Type

Functionality

### Branch

https://github.com/TeamVanced/VancedManager

### Issue

Can't install YouTube Vanced Original with patch

### Feature

Please support the Vanced Original version 

### Motivation

Life is a journey to be experienced, not a problem to be solved.

### Additional context

Good job and thank you all <3

**Comment by Aunali321** [comment]
You need root to patch vanced. If you have please reopen the issue.
