### ISSUE TITLE
bug: Update option

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [revanced/revanced-manager#890]
### Type

Error at runtime

### Bug description

When we're opening the manager, the manager shows the update option which is clickable for a split second. Upon clicking you get the update pop-up and you're able to install the same version over and over again. 

### Steps to reproduce

Step 1: Make sure to close the manager.
Step 2: Open the manager and be quick enough to click the update option.
Step 3: You can go into a cycle of installing the same version if you're into it.

### Android version

Android 13

### Manager version

1.2.0

### Target package name

ReVanced Manager 

### Target package version.

1.0.0 and above I believe 

### Installation type

Non-root

### Patches selected.

Nil 

### Device logs (exported using Manager settings).

```shell
Nil
```

### Screenshots or videos

 Video:

https://github.com/revanced/revanced-manager/assets/117499019/7be4eb46-0b28-48bd-8d60-d99e7fc1b65c

Screenshot:

![Screenshot_20230524-125818](https://github.com/revanced/revanced-manager/assets/117499019/998743bb-4b05-4a86-90da-81add1712e0a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by ILoveOpenSourceApplications** [comment]
While capturing this issue I also noticed there's a second v in the version number when updating.
![Screenshot_20230524-130655](https://github.com/revanced/revanced-manager/assets/117499019/5b3376db-51a5-4f23-83b2-1dbbb24f322e)

**Comment by SpL1Ne** [comment]
1.3.0 Still there. After clicking update button it becomes disabled.

<details>
<summary>Screenshots</summary>

![Screenshot_20230529-145803](https://github.com/revanced/revanced-manager/assets/8836461/085bbb37-3426-4b3a-b0ef-99029c6d0f4d)
![Screenshot_20230529-145810](https://github.com/revanced/revanced-manager/assets/8836461/55e8226d-f5d3-4671-8dec-60c10b64b97f)
![Screenshot_20230529-145816](https://github.com/revanced/revanced-manager/assets/8836461/356ce79c-c03a-4b00-954a-80b14e584a04)
![Screenshot_20230529-145827](https://github.com/revanced/revanced-manager/assets/8836461/a269303b-6a01-412c-97c4-bb291aae0fae)
</details>

**Comment by YarostheLaunchpadder** [comment]
This issue seems to be fixed on the main branch.

Video:
https://drive.google.com/file/d/1xsXpb9f72ktn57sDPDJ2kN4hieqp6y9Y/view?usp=drivesdk

**Comment by ILoveOpenSourceApplications** [comment]
> Edit: It is still reproducible on slow internet connections. I'll look into it.

Didn't have to do us like that. But glad that you were able to replicate the issue.

**Comment by EvadeMaster** [comment]
:tada: This issue might have been fixed in #932, please wait for the next release of ReVanced Manager!

[![GitHub issue/pull request detail](https://img.shields.io/github/pulls/detail/state/revanced/revanced-manager/932?style=flat-square)](https://github.com/revanced/revanced-manager/pull/932)
