### ISSUE TITLE
bug: update download screen shows two "v"s

### ISSUE THREAD

**Issue by HokoraYinphineMPP** [revanced/revanced-manager#894]
### Type

Error while running the manager

### Bug description

Download Update screen shows `vv1.3.0` instead of `v1.3.0`

### Steps to reproduce

1) Update Manager
2) Bug visible

### Android version

11

### Manager version

1.2.0

### Target package name

N/A

### Target package version.

N/A

### Installation type

Non-root

### Patches selected.

N/A

### Device logs (exported using Manager settings).

```shell
N/A
```

### Screenshots or videos

![image](https://github.com/revanced/revanced-manager/assets/54823358/be62a7cf-71a1-4664-abe5-d685c0dbeae3)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by EvadeMaster** [comment]
🎉 This issue have been fixed by https://github.com/revanced/revanced-manager/pull/895, please wait for the next version of ReVanced Manager.

You are welcome to reopen this issue if the problem persists.
