### ISSUE TITLE
Background download feature should be available

### ISSUE THREAD

**Issue by Maremelows** [revanced/revanced-manager#898]
### Type

Functionality

### Issue

Since there is no background download feature, we have to wait while the app is open, and this time may increase depending on the internet speed.

### Feature

If Revanced Manager and Patches have the ability to download in the background when we download updates, we can save time and do other things while downloading.

### Motivation

Nowadays, most applications or sites where we can download files have a background download feature, and I think this feature should come in order for people who use the manager application to use the application better.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Aunali321** [comment]
It's not downloading a file. It's patching the app locally on device. And patching requires significant amount of RAM, so it's not possible to do it in background or Android will kill it.
