### ISSUE TITLE
Revanced Manager is locked at 60hz refresh rate

### ISSUE THREAD

**Issue by Shane9248** [revanced/revanced-manager#899]
### Type

Other

### Issue

https://github.com/revanced/revanced-manager/assets/83491863/096df6fd-8d5c-4e13-9ec3-7cba058c26c0

Revanced Manager is locked at 60hz refresh rate..so that means when my phone's refresh rate is set to 120hz the app seems laggy and slowish

### Feature

Make the app compatible with more than 60hz refresh rate

### Motivation

It makes the app much more upto date with other apps and will make it much smoother for people who use more than 60hz refresh rate

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Shane9248** [comment]
> Is the 120hz refresh rate really necessary for this application? 
> 
> I couldn't reproduce this at my own device, could you try using Android's built-in refresh rate checker?
>  _✨ The option is called "Show Refresh Rate" in Android's developer settings_

yes it's the same using Android's built in refresh rate checker ..but it doesn't show up on screen recording when i enabled it .. that's why i had to use a third party app

**Comment by TeaEndsAcronyms** [comment]
tried it, i had a 90hz phone and revanced seems to still be doing 90hz! don't know why its 60hz on your phone, maybe you have a phone with an adaptive refresh rate?

**Comment by TeaEndsAcronyms** [comment]
after searching it up, your phone (the nothing phone, i can tell by the glyphs toggle) does have an adaptive 60-120hz screen.. so maybe its that!

**Comment by Ushie** [comment]
Can't recreate, the app is capable of doing 120hz for me

**Comment by Shane9248** [comment]
> after searching it up, your phone (the nothing phone, i can tell by the glyphs toggle) does have an adaptive 60-120hz screen.. so maybe its that!

![Screenshot_20230526-155907~2.png](https://github.com/revanced/revanced-manager/assets/83491863/6586cfd4-655a-49e7-a8fb-2cc1666492a1)

this is very weird because i have **'Force Peak Refresh Rate'** always enabled ...this could be a phone issue with the app..let me try to find someone else with the same device

**Comment by Shane9248** [comment]
> > > after searching it up, your phone (the nothing phone, i can tell by the glyphs toggle) does have an adaptive 60-120hz screen.. so maybe its that!
> > 
> > ![Screenshot_20230526-155907~2.png](https://github.com/revanced/revanced-manager/assets/83491863/6586cfd4-655a-49e7-a8fb-2cc1666492a1)
> > 
> > this is very weird because i have **'Force Peak Refresh Rate'** always enabled ...this could be a phone issue with the app..let me try to find someone else with the same device ...if it's only me or not
> 
> Hey, I recently got the nothing phone and yes. I am experiencing the same issue... This seems to be a device issue.

yeah i guess we just have to keep using the way it is
