### ISSUE TITLE
support bundeled/split apks

### ISSUE THREAD

**Issue by theuserwhoisnotadeveloper** [revanced/revanced-manager#90]
### Type

Functionality

### Branch

Flutter

### Issue

installing a huge 150MB youtube apk might be struggling for people with low storage size. 

### Feature

the ability to support apk bundles like .apkm and .apks to use less storage.

### Motivation

by supporting split apk ( .apkm or .apks) the user will not need to install unnecessary .config files to run the app on their device. some people have limited storage so installing a a huge universal package might be struggling for them.  if a phone supports only armeabi_v7a, then installing armv8 or x86 config apks that comes with a universal apk is bloatware that uses storage for no reason.

**Comment by Aunali321** [comment]
Needs to implemented in patcher not manager.
