### ISSUE TITLE
feat: Send notifications for manager & patch releases

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-manager#902]
### Type

Functionality

### Issue

Currently one would need to check a 3rd platform, such as github or social media to find out if there has been any useful updates.

This is too much of an inconvenience for many users.

### Feature

The Manager would send push notifications when there has been a public Manager release.

It would also send push notifications when there has been a public patches release.

There will be a tab which shows the changelogs for the patches, similarly to how the changelogs are shown when you press the "Update" button for the manager at the top of the dashboard.

### Motivation

It will convenience many users, and motivate people to keep their manager and patched applications up-to-date.

### Additional context

I understand that the "Updates available" section is a WIP.

![Screenshot_20230525_160438](https://github.com/revanced/revanced-manager/assets/84587632/cc22b64f-61ce-4557-991d-e2808e065549)

Although I do not know what that feature is meant to be, I am guessing that it is different than what I am suggesting.

I imagine that will display the patched applications that you have installed which have updates available (because the installed ones were patched using older patches versions).

It would then show the patch changlelogs that are relevant to that app. It will also allow you to easily re-patch that app with the new patches.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by PalmDevs** [comment]
This won't probably be implemented, as it requires Manager to run in the background and fetch sources for an update repeatedly.

**Comment by KobeW50** [comment]
Closing this bec it's outdated and many improvements have already been made to the dashboard to ease the updating process
