### ISSUE TITLE
feat: Automatically download app for patching

### ISSUE THREAD

**Issue by 392781** [revanced/revanced-manager#903]
### Type

Functionality

### Issue

Every time a user decides to update their app or install a new one, they must provide their own APK.

### Feature

Include the ability to grab the recommended version of an app automatically from something like apkmirror.

### Motivation

* [xManager](https://github.com/Team-xManager/xManager) does it for Spotify patching (therefore Revanced should too)
* current state is very cumbersome 
* would improve ease of use

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by reisxd** [comment]
Acknowledgements not met.

**Comment by 392781** [comment]
@reisxd what do you mean?

I've met all 4 acknowledgements... unless my issue search wasn't thorough enough?

**Comment by reisxd** [comment]
> @reisxd what do you mean?
> 
> I've met all 4 acknowledgements... unless my issue search wasn't thorough enough?

This is a duplicate issue.

**Comment by 392781** [comment]
> > @reisxd what do you mean?
> > I've met all 4 acknowledgements... unless my issue search wasn't thorough enough?
> 
> This is a duplicate issue.

Right, I wasn't able to find it in my search, my bad.  Can you link it please so I could track it?

**Comment by Ushie** [comment]
#722

**Comment by Ushie** [comment]
> xManager does it for Spotify patching (therefore Revanced should too)

xManager does not patch on device, they distribute the modded APK themselves.
