### ISSUE TITLE
feat: Change "Aborting..." to "Aborted!"

### ISSUE THREAD

**Issue by kitadai31** [revanced/revanced-manager#906]
### Type

Cosmetic

### Issue

![192167547-e9a9a4c9-1f76-41fd-9e81-5fd4f30eda06](https://github.com/revanced/revanced-manager/assets/90122968/3363a134-d741-4138-8bc4-fe80c28ca40c)

When "Aborting..." is displayed, the abort has already been completed.
This is obvious from the [source code](https://github.com/revanced/revanced-manager/blob/main/android/app/src/main/kotlin/app/revanced/manager/flutter/MainActivity.kt#L267-L276).
Therefore, the past tense should be used, not the present progressive tense.

### Feature

Change "Aborting..." message to "Aborted!".

In addition, the log message `An error occurred! Aborting` should also be changed to `An error occurred! Aborted`.

### Motivation

1. Correct word
2. Accurately describe the status
3. Some non-tech users don't know the word "abort". (At least in my country forum.)

Users who don't know the word "abort" cannot be aware that patching has been stopped.
They speculate that "Aborting..." is part of the patching process.
And they ask questions like:

>"ReVanced Manager is stuck at "Aborting" for more than 20 minutes. Should I continue to wait?"
>"ReVanced patching says "Aborting" for 10 minutes now! why?????"

If "Aborting..." was "Aborted!", they they would have at least guessed that something had changed.

Correcting the message will also solve this problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by EvadeMaster** [comment]
:tada: This issue have been fixed by contributor, please wait for the next release of ReVanced Manager!

[![GitHub issue/pull request detail](https://img.shields.io/github/pulls/detail/state/revanced/revanced-manager/928?style=flat-square)](https://github.com/revanced/revanced-manager/pull/928)
