### ISSUE TITLE
bug: Compilation error on a rooted armv9 device

### ISSUE THREAD

**Issue by DeeparthGupta** [ReVanced/revanced-manager#908]
### Type

Error at runtime

### Bug description

I get a compilation error when trying to patch youtube v18.19.35 on a Oneplus 10 pro. I've unselected microG support. When I hit patch I get a dialog that says patching on arm-v7 is not supported. My phone runs on armv9. I had successfully patched 18.16 some time ago before the latest manager update. I found similar bug reports but the user was either on arm-v9 or trying to get microG support.

### Steps to reproduce

Patch youtube via the manager as intended.

### Android version

Oxygen OS 13.0

### Manager version

1.3.0

### Target package name

com.google.android.youtube

### Target package version.

18.19.35

### Installation type

Root

### Patches selected.

client-spoof
copy-video-url
custom-branding
disable-auto-captions
disable-fullscreen-panels
disable-player-popup-panels
disable-shorts-on-startup
disable-zoom-haptics
downloads
hide-ads
hide-cast-button
hide-crowdfunding-box
hide-get-premium
hide-player-overlay
hide-shorts-components
minimized-playback
navigation-buttons
open-links-externally
predictive-back-gesture
remember-video-quality
remove-screenshot-restriction
seekbar-tapping
swipe-controls
theme
video-ads

### Device logs (exported using Manager settings).

```shell
--------- beginning of system
05-28 20:41:26.479  9269  9269 I Quality : Skipped: false 1 cost 14.737514 refreshRate 8337187 bit true processName app.revanced.manager.flutter
05-28 20:42:27.579  9269  9269 I Quality : Skipped: false 6 cost 52.889637 refreshRate 8333333 bit true processName app.revanced.manager.flutter
--------- beginning of main
05-28 20:43:10.684  9269 13740 D VRI[MainActivity]: dispatchAppVisibility visible:true
05-28 20:43:10.692  9269 13740 D ColorModeChangeItem: preExecute mColorMode=0,token=android.os.BinderProxy@6d40057
05-28 20:43:10.692  9269  9269 D VRI[MainActivity]: setWindowStopped stopped:false
05-28 20:43:10.710  9269  9269 D BufferQueueConsumer: [](id:243500000018,api:0,p:-1,c:9269) connect: controlledByApp=false
05-28 20:43:10.710  9269  9269 E IPCThreadState: attemptIncStrongHandle(72): Not supported
05-28 20:43:10.710  9269  9269 E IPCThreadState: attemptIncStrongHandle(61): Not supported
05-28 20:43:10.713  9269  9269 D BufferQueueConsumer: [](id:243500000019,api:0,p:-1,c:9269) connect: controlledByApp=false
05-28 20:43:10.713  9269  9269 I SurfaceView: 49142516 visibleChanged -- surfaceCreated 
05-28 20:43:10.713  9269 12023 D BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#25(BLAST Consumer)25](id:243500000019,api:1,p:9269,c:9269) connect: api=1 producerControlledByApp=true
05-28 20:43:10.714  9269 12017 D BufferQueueProducer: [VRI[MainActivity]#24(BLAST Consumer)24](id:243500000018,api:1,p:9269,c:9269) connect: api=1 producerControlledByApp=true
05-28 20:43:10.715  9269  9269 I SurfaceView: 49142516 surfaceChanged -- format=4 w=1440 h=3216
05-28 20:43:10.717  9269  9269 E SurfaceSyncer: Failed to find sync for id=0
05-28 20:43:10.717  9269  9269 E SurfaceSyncer: Failed to find sync for id=1
05-28 20:43:10.717  9269  9269 E SurfaceSyncer: Failed to find sync for id=2
05-28 20:43:10.717  9269  9269 E SurfaceSyncer: Failed to find sync for id=3
05-28 20:43:10.717  9269  9269 E SurfaceSyncer: Failed to find sync for id=4
05-28 20:43:10.717  9269  9269 E SurfaceSyncer: Failed to find sync for id=5
05-28 20:43:10.717  9269  9269 E SurfaceSyncer: Failed to find sync for id=6
05-28 20:43:10.717  9269  9269 E SurfaceSyncer: Failed to find sync for id=7
05-28 20:43:10.717  9269  9269 E SurfaceSyncer: Failed to find sync for id=8
05-28 20:43:10.717  9269  9269 E SurfaceSyncer: Failed to find sync for id=9
05-28 20:43:10.717  9269  9269 E SurfaceSyncer: Failed to find sync for id=10
05-28 20:43:10.717  9269  9269 E SurfaceSyncer: Failed to find sync for id=11
05-28 20:43:10.717  9269  9269 E SurfaceSyncer: Failed to find sync for id=12
05-28 20:43:10.717  9269  9269 E SurfaceSyncer: Failed to find sync for id=13
05-28 20:43:10.717  9269  9269 E SurfaceSyncer: Failed to find sync for id=14
05-28 20:43:10.717  9269  9269 D VRI[MainActivity]: registerCallbacksForSync syncBuffer=false
05-28 20:43:10.720  9269 12017 D VRI[MainActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
05-28 20:43:10.720  9269  9269 D VRI[MainActivity]: draw finished.
05-28 20:43:10.836  9269  9269 D VRI[MainActivity]: onFocusEvent true
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied client-spoof
Applied copy-video-url
Applied custom-branding
Applied disable-auto-captions
Applied disable-fullscreen-panels
Applied disable-player-popup-panels
Applied disable-shorts-on-startup
Applied disable-zoom-haptics
Applied downloads
Applied hide-ads
Applied hide-cast-button
Applied hide-crowdfunding-box
Applied hide-get-premium
Applied hide-player-overlay
Applied hide-shorts-components
Applied minimized-playback
Applied navigation-buttons
Applied open-links-externally
Applied predictive-back-gesture
Applied remember-video-quality
Applied remove-screenshot-restriction
Applied seekbar-tapping
Applied swipe-controls
Applied theme
Applied video-ads
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~W74MAAzcx2fCAtrlsU1rIg==/app.revanced.manager.flutter-dV0w9hKB_CTx9BVNu8jrcw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ERRXTS/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1537727936, --version-name, 18.19.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL6142542904496432905.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ERRXTS/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ERRXTS/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ERRXTS/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:126)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:217)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~W74MAAzcx2fCAtrlsU1rIg==/app.revanced.manager.flutter-dV0w9hKB_CTx9BVNu8jrcw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ERRXTS/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1537727936, --version-name, 18.19.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL6142542904496432905.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ERRXTS/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ERRXTS/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ERRXTS/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by ILoveOpenSourceApplications** [comment]
Can you try patching without `predictive-back-gesture` and `remove-screenshot-restriction` and report back.

**Comment by DeeparthGupta** [comment]
Still fails to compile.

`Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied client-spoof
Applied copy-video-url
Applied custom-branding
Applied disable-auto-captions
Applied disable-fullscreen-panels
Applied disable-player-popup-panels
Applied disable-shorts-on-startup
Applied disable-zoom-haptics
Applied downloads
Applied hide-ads
Applied hide-cast-button
Applied hide-crowdfunding-box
Applied hide-get-premium
Applied hide-player-overlay
Applied hide-shorts-components
Applied minimized-playback
Applied navigation-buttons
Applied open-links-externally
Applied remember-video-quality
Applied seekbar-tapping
Applied swipe-controls
Applied theme
Applied video-ads
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~W74MAAzcx2fCAtrlsU1rIg==/app.revanced.manager.flutter-dV0w9hKB_CTx9BVNu8jrcw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-OPJQXV/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1537727936, --version-name, 18.19.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL476946670821494192.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-OPJQXV/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-OPJQXV/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-OPJQXV/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:126)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:217)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~W74MAAzcx2fCAtrlsU1rIg==/app.revanced.manager.flutter-dV0w9hKB_CTx9BVNu8jrcw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-OPJQXV/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1537727936, --version-name, 18.19.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL476946670821494192.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-OPJQXV/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-OPJQXV/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-OPJQXV/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more`

**Comment by m9dfukc** [comment]
I am getting the same error, except that I have a rooted Google Pixel 2 XL which runs on a ARMv9 architecture

**Comment by SakuraJensen** [comment]
Having a similar issue on OnePlus Nord N20 Rooted 

Saying not supported to compile on Arm v7a(I have arm v8a) then proceeds to try and compile and fails.   

Worked fine to compile on previous version but now background playback keeps stopping and I can't do anything about it.

![Screenshot_2023-05-31-22-28-47-87_a85b47aaa863e3bc831e16d29c27a79c](https://github.com/revanced/revanced-manager/assets/33555092/130ee975-b234-46be-825c-b1ba34e710bd)
![Screenshot_2023-05-31-22-32-47-24_a85b47aaa863e3bc831e16d29c27a79c](https://github.com/revanced/revanced-manager/assets/33555092/6c6db99d-73e3-4a2b-944a-58150c796b29)
![Screenshot_2023-05-31-22-36-32-74_84d3000e3f4017145260f7618db1d683__01](https://github.com/revanced/revanced-manager/assets/33555092/aa894514-7dee-492f-9aa9-3980e6f23984)

**Comment by oSumAtrIX** [comment]
This is not an issue with ReVanced Manager, but AAPT that is used by ReVanced Patcher. Closing therefor.
