### ISSUE TITLE
Change Package Name

### ISSUE THREAD

**Issue by ahmad-wahyudin** [ReVanced/revanced-manager#909]
### Type

Functionality

### Issue

There is patch Change Package Name, but where to write new name? It's only Checklist. 
Please let me know

### Feature

Easy changing package name

### Motivation

For easy operation 

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Julius8900** [comment]
That patch works only if you use CLI.

**Comment by PalmDevs** [comment]
This is an issue with Manager not supporting patch options. @Aunali321 When will this be implemented?

**Comment by adripo** [comment]
I am also interested in patch options. Is there any plan on implementing it?

**Comment by Aunali321** [comment]
> @Aunali321 When will this be implemented?


 Not in this version. Expect it in rewrite.

**Comment by oSumAtrIX** [comment]
This is because patch options are not yet implemented. An issue should be opened for it if not already.
