### ISSUE TITLE
Revanced

### ISSUE THREAD

**Issue by wolgangPH** [revanced/revanced-manager#91]
Its not working on latest official YouTube app

**Comment by SimplyVoid** [comment]
> Its not working on latest official YouTube app

If you've used vanced before you should know by now they typically doesn't work with latest version. For now all patches support `v17.33.42` . & Always check [revenced-patches](https://github.com/revanced/revanced-patches) to see which version of youtube you can patch.

**Comment by wolgangPH** [comment]
What YouTube app that i can use to watch without ads?

**Comment by ponces** [comment]
Please open a new issue providing more information.
