### ISSUE TITLE
bug: video playback suddenly stop issue persistent once again 

### ISSUE THREAD

**Issue by prakalpup** [revanced/revanced-manager#913]
### Type

Error while running the manager

### Bug description

bug: video playback suddenly stop issue persistent once again 
1. Everytime I am playing the video some playback stop certainly in video playing and error is created
Play back issues is persisting
2. Also video skip to second video in background it playback speed got lower to 1x 
3. If I have on the video ads and if the ad will come in revanced it gonna stop the whole playback due to some bug or error.
4. Request to remove all these bugs 
5. Play back issues is persisting
6. Play back speed issue in next video
7. Playback stops after the ad have come

### Steps to reproduce

Well if u use revanced there is many time playback issue coming in non rooted version of revanced
When ads will come in video video playback would stop
As u skip to next video in background playback speed got lower

### Android version

Android 12

### Manager version

Latest 

### Target package name

Some issue are coming after latest patch update 

### Target package version.

Latest version 

### Installation type

Non-root

### Patches selected.

Latest version 

### Device logs (exported using Manager settings).

```shell
I don't know
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
I don't know
```

### Solution

Its the bug so need update 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Ushie** [comment]
![image](https://github.com/revanced/revanced-manager/assets/79272171/a94acb4f-cbe7-4a19-b639-98a6268c5fa2)
