### ISSUE TITLE
feat: chromecast user interface enhance

### ISSUE THREAD

**Issue by kzajac83** [revanced/revanced-manager#916]
### Type

Functionality

### Issue

After download the manager to chromecast device, where controlling is by TV manager, is not possibile jumping on buttons and  therefore path YouTube app. General UI not work in chromecast. 

### Feature

Due to: 
1. Can please check if there chromecast dev / Android TV by eg. check app like android.chromecast, chromecast built-in, TV storage etc and based on it change UI and allow steering by remote pilot. Now is not possibile.
2. Allow save patched youtube apk in phone for further send to chromecast for simple install apk in chromecast 

### Motivation

New area of devices for the app

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
ReVanced Manager does not support Chromecast, and the YouTube app that runs on the Chromecast is not the same one as your phone, it's called YouTube for Android TV, which is unsupported by ReVanced
