### ISSUE TITLE
feat: Disable 'precise seeking' in youtube revanced

### ISSUE THREAD

**Issue by Anujkaushik01** [revanced/revanced-manager#917]
### Type

Functionality

### Issue

Precise seeking is a stock youtube feature but this feature is very annoying. While in landscape(full screen) mode when I swipe up for related videos, precise seeking activates and stops the video. It's very difficult to always keep track of not to swipe up from where the seekbar is and instead of getting related video Section, precise seeking is shown.
![Screenshot_20230603-203348](https://github.com/revanced/revanced-manager/assets/132915001/e6b27ef3-3162-4014-a88d-e31213f1a4ae)

### Feature

Please add an option to disable/turn off precise seeking just like existing options to remove player feature like, 'enable seekbar tapping'. 

### Motivation

Please add this feature because it makes a significant usability issues for users who use youtube in landscape(full screen) mode. This mode often leads to unintended interruptions of the video playback when users swipe up to access related videos.

### Additional context

You are the only one who can help in this matter because youtube will never gonna roll back 'precise seeking' feature and there are already many posts in youtube help website where users said to remove the feature but got no reply. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
Open this on the ReVanced Patches repository
