### ISSUE TITLE
bug: update progress bar glitching out

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [revanced/revanced-manager#936]
### Type

Error while running the manager

### Bug description

When an update for manager is out and if the user hits update, the download progress bar shows up. If the user accidentally taps anywhere on the screen, the pop up glitches out and the user if left with a tall grey pop up which says downloading at the top.

### Steps to reproduce

1) Make sure an update is available.
2) Tap the update button.
3) Tap somewhere on the screen after the update progresses.
4) Glitched out pop up shows up when pressing update again.

### Android version

Android 13

### Manager version

1.3.5

### Target package name

ReVanced Manager 

### Target package version.

Nil

### Installation type

Non-root

### Patches selected.

Nil

### Device logs (exported using Manager settings).

```shell
Nil
```

### Screenshots or videos

https://github.com/revanced/revanced-manager/assets/117499019/fd9f9144-e16a-4913-ac81-b5a83ab3652f

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by TheAabedKhan** [comment]
Fixed by #937
