### ISSUE TITLE
bug: How do I export the log correctly?

### ISSUE THREAD

**Issue by ripnonfegames** [ReVanced/revanced-manager#940]
### Type

Other

### Bug description

I'm trying to create a bug report but I can not because it will not allow me to export the right log, when I do export the log it's so big it doesn't let me copy and it's not the same as the one in the app.

### Steps to reproduce

Try to export log and copy it on android

### Android version

12

### Manager version

Most recent

### Target package name

None

### Target package version.

None

### Installation type

Non-root

### Patches selected.

None

### Device logs (exported using Manager settings).

```shell
NONE
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by TheAabedKhan** [comment]
Can you attach a screen recording of your issue? I am unable to reproduce the issue. It's working perfectly fine in my device.

**Comment by oSumAtrIX** [comment]
@TheAabedKhan offtopic, but thanks for your continuous interest in ReVanced through your recent contribution

**Comment by TheAabedKhan** [comment]
@oSumAtrIX I appreciate your unexpected gratitude! I'm truly filled with joy by your thanks. It means a lot to me that my actions had a positive impact.  I'm glad that I could make a difference. Your appreciation is truly heartwarming. It made my day!

**Comment by ILoveOpenSourceApplications** [comment]
Can we have some guide provided on how to export the log in the case of manager provided. It could be that the steps followed are not proper.

**Comment by Ushie** [comment]
Stale
