### ISSUE TITLE
feat: Built-in Custom Branding

### ISSUE THREAD

**Issue by Uryaaa** [revanced/revanced-manager#947]
### Type

Functionality

### Issue

The current custom branding (changing the brand to user desired branding) is only can be done via cli and building patches from the source *cmiiw. Where it needed some computer knowledge to do so. 

### Feature

A built-in Custom Branding would be nice, after choosing the patch if Custom Branding is selected there will be an additional process to specify the costum branding with some conditions.

### Motivation

To make costum branding more accessable.

### Additional context

Probably add some disclaimer about costum branding risk.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by reisxd** [comment]
Acknowledgements not met.
