### ISSUE TITLE
Youtube home page changed to subscriptions / hidden youtube homepage

### ISSUE THREAD

**Issue by Notrustfund** [revanced/revanced-manager#949]
### Type

Functionality

### Issue

Eveytime I  access the YouTube app I'm bombarded with  video suggestions I don't want to see. Also what this does is it causes users to mindlessly click on videos suggested by the youtube algorithm. This causes prolonged unnecessary use . Very easy to go down a rabbit hole and procrastinate. 

### Feature

So how this feature would work is that evrytime you access the YouTube app the homepage could be hidden, meaning there'd be no videos displayed. You would only see videos if you search for one. 

Or you could have it where everytime you access youtube your "homepage" is the videos you subscribe to and nothing else.

### Motivation

I think this should be considered because it allows the user to have alot more control in how they experience youtube without having to be subjected to a visual environment not designed by them but by people who's only objective is to get them to stay on the app for as long as possible.  This can make the use of the app alot more healthy and balanced for individuals!

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by NameLessGO** [comment]
Close this issue and post on https://github.com/revanced/revanced-patches

This repo is only for revanced manager, not yt
