### ISSUE TITLE
Error report.

### ISSUE THREAD

**Issue by Fertanima** [revanced/revanced-manager#95]
### Type

Functionality

### Branch

Flutter

### Issue

Errors cannot be sent with the copy option from the application.

### Feature

You're spending time in an app and suddenly an error occurs and the error is immediately displayed and you report it to GitHub with the copy option

### Motivation

I think it's a good feature.

### Additional context

You add it to YouTube ReVanced.

**Comment by ponces** [comment]
Errors should be sent using Logs entry on Settings.

**Comment by Fertanima** [comment]
The feature I mentioned is good.

**Comment by Fertanima** [comment]
Newpipe and LibreTube use it. And it's very good.
