### ISSUE TITLE
bug: App existing even if it's deleted, so I can't install It again

### ISSUE THREAD

**Issue by Natillax** [revanced/revanced-manager#954]
### Type

Other

### Bug description

I can't install again Youtube ReVanced

### Steps to reproduce

Step 1.
I downloaded the recommended Youtube version and patched it with ReVanced Manager without problems.

Step 2.
I exported It to "Download" folder.

Step 3.
I tried to install It and with SAI.

Step 4.
It didn't say to install, but to "update".

Step 5.
I got an error with both methods.

So... I can't install again Youtube ReVanced

### Android version

Android 13
MIUI Global 14.0.6

### Manager version

1.3.5

### Target package name

Youtube

### Target package version.

18.19.35

### Installation type

Non-root

### Patches selected.

Recommended ones.

### Device logs (exported using Manager settings).

```shell
All were ok.
```

### Screenshots or videos

![Screenshot_2023-06-16-16-35-59-229_com google android packageinstaller](https://github.com/revanced/revanced-manager/assets/57504354/076fc652-2a43-49dd-be91-6f4598357daa)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by TheAabedKhan** [comment]
Can you please attach a screen recording as well? It will be a lot easier to understand the issue.

**Comment by oSumAtrIX** [comment]
What does ReVanced Manager say. Does it show up in the installed section

**Comment by ILoveOpenSourceApplications** [comment]
Do you already have an existing version of ReVanced YouTube installed, this issue won't occur unless, as ReVanced YouTube is having a different package name than the stock YouTube and hence would get installed.

**Comment by rhayonne** [comment]
Please, show your Revanced manager screen like that

![Screenshot_2023-06-19-02-53-03-034_com.revanced.net.revancedmanager.jpg](https://github.com/revanced/revanced-manager/assets/5938446/15b6c8ae-2617-4508-8313-db4aa90de3fc)

You Will see if your manager recognize another youtube version, installed.

**Comment by oSumAtrIX** [comment]
@rhayonne  This is not ReVanced Manager in your screenshot. 

@Natillax You have a conflicting installation
