### ISSUE TITLE
save browsing time

### ISSUE THREAD

**Issue by FrontEnd07** [revanced/revanced-manager#956]
### Type

Other

### Bug description

Why doesn't revanced remember the time of watching when I go back to watching the video?

### Steps to reproduce

i just have a question

### Android version

i just have a question

### Manager version

i just have a question

### Target package name

i just have a question

### Target package version.

i just have a question

### Installation type

Root

### Patches selected.

i just have a question

### Device logs (exported using Manager settings).

```shell
i just have a question
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Ushie** [comment]
Not the right repository for this, try https://github.com/revanced/revanced-patches, also it's most likely because of adblock that you have installed such as Adaway or AdGuard
