### ISSUE TITLE
feat: A Patch to Move Reddit Upvote Button to the right side.

### ISSUE THREAD

**Issue by Kristijan1001** [revanced/revanced-manager#959]
### Type

Functionality

### Issue

Can't reach left side upvote button one handed. Custom reddit clients are going away so this is the way.

### Feature

Move the upvote botton on the right side.

### Motivation

Because custom clients are going away.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Julius8900** [comment]
Wrong place to ask. Ask in the patches repository.
