### ISSUE TITLE
README.md should have a link to instructions on how to use the app, not just to install it

### ISSUE THREAD

**Issue by szalapski** [ReVanced/revanced-manager#962]
### Type

Functionality

### Issue

I'm not sure how to use the app. Guess I'll Google it some more.

### Feature

README.md should have a link to instructions on how to use the app, not just to install it.

### Motivation

Links are easy

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Currently present in /docs, a link can be added

**Comment by Welding-Torch** [comment]
what docs dude? where are they?

**Comment by Welding-Torch** [comment]
I actually genuinely can't see any clear instructions on how to get YouTube working, isn't that the whole point of revanced?

**Comment by Ushie** [comment]
https://github.com/revanced/revanced-manager/tree/main/docs

**Comment by oSumAtrIX** [comment]
@Ushie Ideally the docs is linked in the readme & at some point added to the website
