### ISSUE TITLE
feat: <title>

### ISSUE THREAD

**Issue by ayoubelmhamdi** [revanced/revanced-manager#963]
### Type

Cosmetic

### Issue

![Screenshot_2023-06-23-04-40-48-762_app revanced android youtube-edit](https://github.com/revanced/revanced-manager/assets/34358145/591d264b-dca6-4594-aac1-f83ad2801e69)

### Feature

YouTube-rebanced, showing time is not good, is there any way to fixed, it  look like the time is white and the background is white too.

i think, the time should be in black, or reverse in color of video،

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by ayoubelmhamdi** [comment]
Was it closed for some reason?

**Comment by oSumAtrIX** [comment]
Yes:

![image](https://github.com/revanced/revanced-manager/assets/13122796/e8f9eb1e-9316-46ba-b1f0-26ade7051f3f)

**Comment by ILoveOpenSourceApplications** [comment]
Also this issue should be opened under ReVanced Patches.
