### ISSUE TITLE
feat: Use root access and/or lsposed to prevent the play store from updating patched apps

### ISSUE THREAD

**Issue by MulverineX** [revanced/revanced-manager#966]
### Type

Functionality

### Issue

To prevent apps from being updated it is an annoying task of changing settings in the play store, then every time you "Update All" you have to deny updates on all of those apps *again*.

### Feature

When the manager is in root mode, it will automatically prevent all apps you have patched from being updated by the play store.

### Motivation

Manually preventing updates every time you go to update your app library is frustrating, it'd be much nicer if the play store fails to update the apps that have been patched.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Play Store skips updates on apps where you disabled them.

**Comment by MulverineX** [comment]
@oSumAtrIX no that's the problem, whenever you go to update your apps it asks you for each one you have disabled. This suggestion is to prevent that

**Comment by oSumAtrIX** [comment]
No, if you press update, it asks you to skip the ones you disabled or not.

**Comment by MulverineX** [comment]
Well regardless of whatever A/B crap or changes to behavior, this still requires manual intervention. Much like being required to manually download the APK version, this should be automated.

**Comment by oSumAtrIX** [comment]
ReVanced Manager manages apps patched by ReVanced. It should not intervene with Play Store. You should complain to them if you have an issue with Play Store.

**Comment by MulverineX** [comment]
Aurora Store sucks and Play Store is the defacto solution. It's very inconvenient to manage your apps manually.

**Comment by Masamune3210** [comment]
If you truly do not want to deal with the "colossal" effort of hitting cancel on a couple of buttons every time you do a manual update run, why don't you just detach the modified apps from the market so they no longer show up

**Comment by MulverineX** [comment]
@Masamune3210 how do you do that without changing the app ID and screwing up integrations?

**Comment by Masamune3210** [comment]
If you aren't even going to put in the minor amount of effort it takes to even try to look up how, I guess you will never know

**Comment by MulverineX** [comment]
Oh this is, actually a thing https://github.com/Magisk-Modules-Repo/Detach. I apologize.

**Comment by MulverineX** [comment]
@Masamune3210 this tool hasn't been updated for over a year and is broken, it works initially but then breaks.

**Comment by Masamune3210** [comment]
It's just that implementation of it, there are countless other ways to do it. People have been hiding apps from the play store since before the Titanium Backup days

**Comment by MulverineX** [comment]
The thread on xda looked pretty dead, not sure where to find something that actually works

**Comment by MulverineX** [comment]
https://github.com/j-hc/zygisk-detach this actually works!!!
