### ISSUE TITLE
feat: improve UX for loaded patches selection

### ISSUE THREAD

**Issue by taku-nm** [revanced/revanced-manager#967]
### Type

Cosmetic

### Issue

Referring to [this thread](https://discord.com/channels/952946952348270622/1122167988276187228)

When loading an apk that has been patched previously it loads the patch selection but does not make it obvious that the selection can be changed, which is an issue for users that patched quite a while ago and don't quite remember how to do so.

Due to the microG patch being renamed, it also does not include it when the user patched ~2 months ago. Leading to confusion why the currently selected patches suddenly don't work anymore.

You can see an excellent example of that [here](https://cdn.discordapp.com/attachments/1122167988276187228/1122170928802041928/Screen_Recording_20230624_162552.mp4) ;
the user does not pick up on the fact that you can press the patch list again, even tho I specifically to "Select Patches" and "Load default patches"

### Feature

an edit button, preferably on the top right of the app and patch selection card. If it were at the bottom of the list, I can already see how people would miss it by not scrolling down;

maybe a warning icon (with tooltip) when the default patches are not loaded?

### Motivation

obviously improved UX, preventing confusion and therefore support requests.
Also I could see this as a significant issue going forwards, as the amount of people being forced to update from 18.05.40 due to playback issues will most likely increase in number. Those people patched months ago, which is apparently enough to forget about the patching process.
This could lead to a sort of second wave from the initial vanced death. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
This shouldn't be a feature request. The issue is that ReVanced Manager ignores the patches `included` field when it sees the patch for the first time. If the patch is renamed but is by default `included`, then ReVanced Manager should include it respectively. Please open an issue regarding this.

**Comment by taku-nm** [comment]
I'm not sure if I should make an issue for this, as it would be basically a duplicate of this issue
#900
its slightly different, but based on the same problem;
Since RV manager can't tell that a patch has been renamed, it would need to assume that every patch that hasn't been included last time but is included by default, might've been a renamed one and would therefore be included in the selection - kind of throwing out the whole point of remembering the selection in the first place. 

That's why it would be more sensible to encourage the user to actually check their automatically loaded selection the way I described it. This would also add some future proofing, in case new patches get added that the user may or may not want to select.
Just loading them in because they're a default patch and new or renamed would probably just lead to confusion.

One way to bypass the renaming issue would also be to separate the displayed name of the patch and a sort of identifier.

**Comment by oSumAtrIX** [comment]
> Just loading them in because they're a default patch and new or renamed would probably lead to confusion.

It's better than not including them when they are included by default. For "new" patches that the manager sees, it can show a notice such as "New patches added, click to view," and highlight or pin them at the top until the next patch or patch selection. Please create a new issue for this.
