### ISSUE TITLE
Add Shizuku support for Non-Rooted device

### ISSUE THREAD

**Issue by ClientBeta** [revanced/revanced-manager#968]
### Type

Functionality

### Issue

For Non rooted users Support only with android 11+

### Feature

It doesn't need magisk module when rooted

### Motivation

Because it's useful for non rooted user

### Additional context

Shizuku is like a Rooting app that is temporary it uses wireless debug and Can grant like Super-User request or Magisk Super-User it operates like a Temporary root like MTK Easy SU

Adding it to the Revanced manager is super useful because it can grant it as administrator to the device like a Super user request as I said in the top

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
And what would that achieve?

Shizuku is nothing like being rooted, you gain ADB permissions but that's still much less privilege than being rooted, it wouldn't bring feature parity with root users, however there are some features that can make use of shizuku, which are laid out in #357

**Comment by AlecMcCutcheon** [comment]
Check out LSPatch https://github.com/LSPosed/LSPatch, it allows you to patch pre-installed apps using shizuku, id look to see in place patching working on non-rooted devices on Revanced
