### ISSUE TITLE
feat: patching should use foreground service mechanism

### ISSUE THREAD

**Issue by escape0707** [revanced/revanced-manager#97]
### Type

Functionality

### Branch

Flutter ig, downloaded from GitHub release.

### Issue

I denied that background permission, but keep getting it every time I boot up the manager app.

### Feature

Don't prompt background permission after being denied (several times).

### Motivation

I'd like to propose to give people the choice if they prefer to let the manager finish it's job in the foreground while waiting.

**Comment by ponces** [comment]
Makes sense.
We'll look into it.
Thanks.

**Comment by wrongway213** [comment]
I came to report this as a bug, thanks for saving me the time. Watching this.

**Comment by ponces** [comment]
Yet it was working but had to be reverted as some users were having some issues with it.
We may already have a fix on the way which should arrive soon on an alpha release.

**Comment by escape0707** [comment]
Can we simply use a foreground service to do the patching job with a progress notification?

https://developer.android.com/guide/components/foreground-services

This way we only need to request a normal permission which is accepted upon installation.

**Comment by Aunali321** [comment]
No, android will kill the process.

**Comment by escape0707** [comment]
> No, android will kill the process.

I read some documents and blog posts. Do you mean third party ROM might kill the process or the behavior is intended in even the original AOSP?

The blog post I want to refer to is https://honesdev.com/how-dare-you-kill-my-foreground-service/

**Comment by escape0707** [comment]
Ping after 10 days

**Comment by Aunali321** [comment]
I use libretorrent. Libretorrent uses less than 10% cpu and 200mb ram. Manager uses minimum 70% cpu and 700mb ram. Android will most likely kill it.

**Comment by escape0707** [comment]
> I use libretorrent. Libretorrent uses less than 10% cpu and 200mb ram. Manager uses minimum 70% cpu and 700mb ram. Android will most likely kill it.

Oh, I see that's a fair reason that I didn't recognize.

Thank you for the explanation, and I think this issue is already fixed by the newer versions?

If so, feel free to close this issue.
