### ISSUE TITLE
feat:  Revanced Manager should work without internet with synced patches

### ISSUE THREAD

**Issue by cvhere** [ReVanced/revanced-manager#978]
### Type

Functionality

### Issue

I mostly keep my internet turned off(both mobile & wifi) in my mobile. I have synced latest revanced manager patches before that. 
I tried to patch Youtube application without internet turned on.  On list of  installed apps,  my installed apps(which do have support for patching) are not shown. However, I could select apk from storage and continue to next step. On the patch selection page, list of patches are not shown.

Revanced Manager version: 1.3.7
Android Version : 13

### Steps to reproduce
1). Turn off internet(both mobile & wifi) -> Open Revanced Manager -> Click Patcher button in bottom navigation menu  -> Click on "Select an application" -> **List of installed appplications are not shown**

2). Turn off internet(both mobile & wifi) -> Open Revanced Manager -> Click Patcher button in bottom navigation menu  -> Click on "Select an application" ->  Select Apk from storage -> Click on "Select Patches" -> **List of currently synced patches are not shown**

### Feature

Enable Revanced Manager to patch applications without internet if patches are already synced.

### Motivation

Removes the hard dependency of internet and enables the user patch at anywhere & anytime.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by sssh7710** [comment]
Then do you want me to get all the patches in advance and just apply them?
