### ISSUE TITLE
bug: manager keeps asking for All file access even after denying it a couple of times

### ISSUE THREAD

**Issue by P4R1H** [ReVanced/revanced-manager#979]
### Type

Error while running the manager

### Bug description

App shouldnt shove requesting the permission down our throat when we don't wanna provide it, if its intended then my bad 

### Steps to reproduce

open the revanced manager app

### Android version

oneui 5.1, android 13

### Manager version

1.37

### Target package name

NA

### Target package version.

NA

### Installation type

Non-root

### Patches selected.

NA

### Device logs (exported using Manager settings).

```shell
NA
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by roydenrego** [comment]
I have been facing the same issue and ngl it's kinda annoying. Also, is there a reason as to why the manager needs all files access?

**Comment by patrickli** [comment]
Same question have. The permission request was added in c876f2f, but the commit itself did not use this extra permission in anyway, merely requesting it.

Why request a permission that you don't use?

**Comment by Ushie** [comment]
The permission is used by some patches, it makes up for ReVanced Manager's lack of patch options support in the time being

**Comment by oSumAtrIX** [comment]
Patches make use of it

**Comment by MathewJake365** [comment]
I've been experiencing the same for a few months and reported it back then. But this annoying issue hasn't been fixed yet.

**Comment by oSumAtrIX** [comment]
Closing in favour of #1378
