### ISSUE TITLE
bug: ReVanced Manager hangs with black screen since v1.3.7 when using a custom source

### ISSUE THREAD

**Issue by Novgorod** [revanced/revanced-manager#982]
### Type

Error while running the manager

### Bug description

Phone: Samsung Glaxy S22 Ultra (Android 13, latest patch May 2023)

When using a custom source, the latest working version of ReVanced Manager is 1.3.6. It asks for all files permision on first run and then starts normally. After updating to 1.3.7 or 1.3.8 (while having a custom source in the settings) the screen stays black when running the app. I tried clean install, phone reboot and setting all prermissions prior to running the app, nothing works.

Side note: Downgrading to 1.3.6 doesn't work while a newer version is installed (invalid package), so I have to manually uninstall 1.3.8, only then I can install 1.3.6 which is the latest working version with a custom source.

Currently, the only "fix" is to downgrade to 1.3.6 as described, go to the settings and remove the custom source (set to default), then update to 1.3.8 because apparently the manager settings persist even after an uninstall. This is a separate issue which makes troubleshooting very difficult if the app breaks because of the settings and there is no obvious way to reset them.

### Steps to reproduce

Install ReVanced Manager 1.3.7 or 1.3.8, set a custom source and run.

### Android version

Android 13 (May 2023)

### Manager version

1.3.7 and 1.3.8

### Target package name

ReVanced Manager

### Target package version.

1.3.7 and 1.3.8

### Installation type

Non-root

### Patches selected.

-

### Device logs (exported using Manager settings).

```shell
-
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Novgorod** [comment]
I just saw [this](https://github.com/revanced/revanced-manager/issues/983) issue - turns out mine is the same, so this can be closed. I used a custom source before and the manager settings were preserved even after a complete uninstall, which is not a good idea if certain settings break the app.

Regardless, even if a custom source becomes incompatible, it should revert to defaults and not hang on startup...

**Comment by orfeous1** [comment]
Same here!
Black screen on 1.38 upgraded from 1.35
Custom source

**Comment by ILoveOpenSourceApplications** [comment]
It is indeed strange as the changelog from version 1.3.6 to 1.3.7 indicates that the possible reason for this issue is the bump to the patcher dependency.

**Comment by kenethc** [comment]
Facing same issue on v1.3.7 and v1.3.8 when using source - inotia00

**Comment by SuperCoolDude** [comment]
I also have this issue for 1.3.7 and 1.3.8, works in 1.3.6.

**Comment by kenethc** [comment]
v1.3.6 loads properly with custom source - inotia00. But not able to patch the recommended version of YouTube. Operation aborts mid way. Created another issue and posted log in there.

**Comment by ILoveOpenSourceApplications** [comment]
> v1.3.6 loads properly with custom source - inotia00. But not able to patch the recommended version of YouTube. Operation aborts mid way. Created another issue and posted log in there.

This has nothing to do with the manager. RVX hasn't updated it's patches to support the latest manager. So if you want to patch again you will have to rollback to the last supported manager version by RVX.

**Comment by EvadeMaster** [comment]
🎉 This issue have been fixed by #1003, please update to the latest version of ReVanced Manager (v1.3.9)

Feels free to reopen If you feels like the problem hasn't been resolved.
