### ISSUE TITLE
bug: Revanced Extended not loading

### ISSUE THREAD

**Issue by ItsSubhro** [revanced/revanced-manager#983]
### Type

Error at runtime

### Bug description

changing patches organization & integration organization to inotia00, with and without experimental patches makes the app stuck at loading. Just shows the logo.

### Steps to reproduce

1. Change patches organization & integration organization to "inotia00"
2. (Optional) Enabling the Experimental Patches support (Not the Universal).
3. Restart
Result - App won't load, stuck with the revanced logo

### Android version

13

### Manager version

1.3.8

### Target package name

Not necessary

### Target package version.

Not necessary

### Installation type

Non-root

### Patches selected.

None

### Device logs (exported using Manager settings).

```shell
None
```

### Installer logs (exported using Installer menu option) [unneeded if issue is not during patching].

```shell
None
```

### Screenshots or videos

![Screenshot_2023-07-01-15-39-24-205_app revanced manager flutter](https://github.com/revanced/revanced-manager/assets/87135944/f90185ec-9449-4f52-9249-27ca8cbe3496)

### Additional context

Tried with VPN(Netherlands)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Novgorod** [comment]
I had the same problem. The latest working version with custom sources is 1.3.6. If you install a later version, the custom source setting breaks the app and even uninstalling and reinstalling doesn't reset the settings. Instead, you have to uninstall 1.3.8, then install 1.3.6, run it and reset the source settings, then you can update to 1.3.8 and it should work again.

The main Revanced now seems to have default playback speed and default quality settings, so the Extended mod is obsolete.

**Comment by kenethc** [comment]
v1.3.7 was working just fine for me.

**Comment by Novgorod** [comment]
> v1.3.7 was working just fine for me.
> […](#)

Did you set "inotia00" (Revanced Extended) as the organization under sources? Both 1.3.7 and 1.3.8 hang on startup for me with the custom source setting (1.3.6 is the latest working version). With default source settings all versions work.

**Comment by oSumAtrIX** [comment]
Wrong repo
