### ISSUE TITLE
Adding support for more apps and splitted apks in manager

### ISSUE THREAD

**Issue by karthikvijay5227** [revanced/revanced-manager#985]
### Type

Functionality

### Issue

I am requesting the feature of support for patching more apps and also the splitted apks in the manager itself without root.I also want the feature of patches with ad removal feature working,spoofing or mimicking premium features in apps like hotstar,Amazon prime if possible.

### Feature

Ad removal feature in more apps and also in splitted apps in manager,mimicking premium features in apps like hotstar,Amazon prime,etc.

### Motivation

I am motivated of the existing capabilities of the app and this features make it a perfect one as of my opinion.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [ ] The issue is related solely to the ReVanced Manager

**Comment by Ushie** [comment]
Go to the patches repository
