### ISSUE TITLE
"Aborted"

### ISSUE THREAD

**Issue by Baphomeem** [ReVanced/revanced-manager#988]
### Type

Error while running the manager

### Bug description

this error appears  whenever I try to patch the YouTube app 

### Steps to reproduce

1-Download Revanced Manager.
2- Download the YouTube App from APKPure.
3-Patch Youtube

### Android version

13

### Manager version

1.3.8

### Target package name

Com.google.android.youtube

### Target package version.

18.19.35

### Installation type

Non-root

### Patches selected.

![Screenshot_20230701-144146](https://github.com/revanced/revanced-manager/assets/116759900/bec4e594-8bc8-470e-a831-cd4c40fb2e37)
![Screenshot_20230701-144140](https://github.com/revanced/revanced-manager/assets/116759900/5d5dc1d7-8221-4809-99ed-4a1a191d90a7)

### Device logs (exported using Manager settings).

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied always-autorepeat
Applied client-spoof
Applied comments
Applied copy-video-url
Applied custom-branding
Applied disable-auto-captions
Applied disable-fullscreen-panels
Applied disable-player-popup-panels
Applied disable-shorts-on-startup
Applied disable-zoom-haptics
Applied enable-debugging
Applied external-downloads
Applied hdr-auto-brightness
Applied hide-ads
Applied hide-album-cards
Applied hide-autoplay-button
Applied hide-breaking-news-shelf
Applied hide-captions-button
Applied hide-cast-button
Applied hide-crowdfunding-box
Applied hide-email-address
Applied hide-endscreen-cards
Applied hide-filter-bar
Applied hide-floating-microphone-button
Applied hide-info-cards
Applied hide-layout-components
Applied hide-load-more-button
Applied hide-player-buttons
Applied hide-player-overlay
Applied hide-seekbar
Applied hide-shorts-components
Applied hide-timestamp
Applied hide-video-action-buttons
Applied hide-watch-in-vr
Applied hide-watermark
Applied minimized-playback
Applied navigation-buttons
Applied old-quality-layout
Applied open-links-externally
Failed to apply premium-heading: The file /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-HEMQMF/cache/res/drawable-xxxhdpi/yt_premium_wordmark_header_light.png does not exist in the resources. Therefore, this patch can not succeed.
Applied remember-video-quality
Applied return-youtube-dislike
Applied seekbar-tapping
Applied sponsorblock
Applied spoof-app-version
Applied swipe-controls
Applied tablet-mini-player
Applied theme
Applied vanced-microg-support
Applied video-ads
Applied video-speed
Applied wide-searchbar
Repacking patched apk
Compiling resources
An error occurred! Aborted
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~KjQ9PujtY9-ykGB_V8ZLvQ==/app.revanced.manager.flutter-mcoEj6IZRbdOWdD0-berAQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-HEMQMF/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1537727936, --version-name, 18.19.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4801743045281267527.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-HEMQMF/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-HEMQMF/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-HEMQMF/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:128)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:217)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~KjQ9PujtY9-ykGB_V8ZLvQ==/app.revanced.manager.flutter-mcoEj6IZRbdOWdD0-berAQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-HEMQMF/cache/aapt_temp_file, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1537727936, --version-name, 18.19.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL4801743045281267527.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-HEMQMF/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-HEMQMF/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-HEMQMF/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by TheAabedKhan** [comment]
Can you also attach a screenshot of the `About` section located in the `Settings` page?

**Comment by kenethc** [comment]
I am facing the same issue

**Comment by Splarkszter** [comment]
I have the same problem. Samsung S9 Android 10.

At first it builded the app, but said it wasn't intalled (at the same time i had built the app to install it on an ARMV7 device [Samsung Galaxy Grand Prime] and it installed fine, that's odd).

Today i want to do it again for the S9 but now it aborts, though i intalled the 1.3.8 update and it builds again but still can't install the patched app.
I even did the delete app-data but same behaviour. Nothing seems off, just can't install it.

**Comment by Splarkszter** [comment]
> @Splarkszter if it finishes patching, install the export APK from outside Manager. 

I did it, same, can't install the app.

**Comment by BartAgterbosch** [comment]
Same here, upon "Decoding resources": java.lang.reflect.InvocationTargetException.
It does this wether cache and data is cleared or not, and the youtube app is at the recommended version of 18.19.35 downloaded from the official youtube repo on apkmirror, selected patches are only the recommended, and it's an unrooted device: galaxy S10+, android 12

**Comment by Earlopain** [comment]
Same issue here, I solved it by downloading the universal apk and using that to patch. I wanted to be clever and used one of these apk extractor apps. I suspect it has something to do with it still being split.

**Comment by rejuanad99** [comment]
![Screenshot_20230710_015237](https://github.com/revanced/revanced-manager/assets/49226370/fda407a0-b5b3-4d33-998c-653b13162014)
I'm getting this error.

**Comment by kvxrun** [comment]
Receiving the same error here. Tried clearing data, still doesn't work.

**Comment by kenethc** [comment]
> Receiving the same error here. Tried clearing data, still doesn't work.

Download the new version of ReVanced Manager v1.40

**Comment by hicsuntdragons** [comment]
> Same issue here, I solved it by downloading the universal apk and using that to patch. I wanted to be clever and used one of these apk extractor apps. I suspect it has something to do with it still being split.

This solved my issue. i was using an universal apk as well but I downloaded a version that was "broken" i guess. then I searched for a different source and it went through the "compiling resources" stage, now working

**Comment by Splarkszter** [comment]
> i was using an universal apk as well but I downloaded a version that was "broken" i guess. then I searched for a different source and it went through

I usually use apkmirror because seems reputable, don't know how much tho. Are there any truly reputable alternatives?

**Comment by Ushie** [comment]
APKMirror is the best and most reputable provider out there

**Comment by fettou** [comment]
![Screenshot_2023-07-21-18-56-28-085_app revanced manager flutter](https://github.com/ReVanced/revanced-manager/assets/138130685/78bb9b93-8084-4845-a1ce-25539a7c11ae)
i have this issue while patching any app

**Comment by rapdodge** [comment]
Same issues with when patching YT Music...

[revanced-manager_patcher_20230730152142205979.log](https://github.com/ReVanced/revanced-manager/files/12208758/revanced-manager_patcher_20230730152142205979.log)

**Comment by ShredRum** [comment]
> Same issues with when patching YT Music...
> 
> [revanced-manager_patcher_20230730152142205979.log](https://github.com/ReVanced/revanced-manager/files/12208758/revanced-manager_patcher_20230730152142205979.log)

Same

**Comment by xehpuk** [comment]
Same in v1.6.1.

**Comment by ThePillarist** [comment]
Still getting this issue identical to the #1069. Downloaded from APKMirror, deleted and reinstalled manager, deleted previous YouTube Music Revanced app. Nothing corrects it. Downloading the arm64 version because there isn't a universal for YT Music. Stumped.

**Comment by dusan-milanovic** [comment]
Seeing this issue as well.

Tried different yt versions (downloaded from apkmirror), but nothing has fixed the issue. I'm using the v1.7.0 of the manager

**Comment by oSumAtrIX** [comment]
May be fixed, if not, reopen an updated issue.
