### ISSUE TITLE
feat: Custom Output Directory (saves to storage when finished patching)

### ISSUE THREAD

**Issue by Alprnn357** [revanced/revanced-manager#99]
### Type

Functionality

### Branch

Flutter

### Issue

When app patching is finished, manager app doesn't move to storage and stays on app data files which is unable to reach the patched apk file on non-root users. Also patched apk can be deleted even when original yt app is uninstalled.

### Feature

Just make a function that saves it to internal storage or SD Card (by giving permission from file manager will open)
Also letting users set the output directory is fine.

### Motivation

It's useful and i think it should be implemented to the app

**Comment by SodaWithoutSparkles** [comment]
![Screenshot_2022-09-15-21-39-05-519-edit_app.revanced.manager.flutter.jpg](https://user-images.githubusercontent.com/64138578/190418695-123781c6-75d1-4723-8448-9a22508807df.jpg)

Where is it?

**Comment by Alprnn357** [comment]
> Use "Share APK" menu option on that screen which appears at the end of success patching

![Screenshot_20220915-174500](https://user-images.githubusercontent.com/37711793/190434470-1c761835-249e-4988-bcc3-24e2e0c1af54.jpg)
Same with @SodaWithoutSparkles . Also after clicking install button, there isn't any button to share apk.

**Comment by Spacellary** [comment]
As of 0.0.6 I also didn't get a "Share" button, only Install.

**Comment by SodaWithoutSparkles** [comment]
as of 0.0.17 I can finally see the button. It was at the top right
