### ISSUE TITLE
feat: be able to copy the recommended version

### ISSUE THREAD

**Issue by wiiznokes** [ReVanced/revanced-manager#990]
### Type

Functionality

### Issue

because it takes a long time to have to remember the right version and write it in a search engine.

### Feature

be able to copy the recommended version with its name, example: `twitter apk version v9.71.0-release0`

### Motivation

because it simple to implement

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by AdiAr11** [comment]
Hi, I would like to work on this issue. Can someone guide me where can i find the recommended version? where would the user have to click to be able to copy the recommended version with its name? Thank you.

**Comment by wiiznokes** [comment]
I feel like the best way of doing this is to add a screen when we click on a app which is not installed.
The screen will have a button 
- to comme back to the list
- copy the recommend version
- maybe open it on a navigator idk
- the floating button storage

**Comment by wiiznokes** [comment]
The version seems to be fetched via a PatcherApi. See the viewmodel:
https://github.com/ReVanced/revanced-manager/blob/main/lib/ui/views/app_selector/app_selector_viewmodel.dart

**Comment by oSumAtrIX** [comment]
I think instead of copying; it could launch the browser. In this case, it should be accompanied by a  "link" icon to signify an outgoing link.

**Comment by oSumAtrIX** [comment]
Next to the package name or version a "link" icon can be added to signify an outgoing link when the label is clicked on.

**Comment by AdiAr11** [comment]
@oSumAtrIX , sounds good. will try to implement this. could you help me finding the file where i will have to make this changes if possible? I'll also try to find it as well. Thank you!

**Comment by wiiznokes** [comment]
If we add a new screen, the list will be more "visible".
And it will be easier to add functionality like predefined website like appmirror etc.
But I am not a maintainer.

**Comment by AdiAr11** [comment]
@oSumAtrIX No worries, I will find it. Thank you

**Comment by wiiznokes** [comment]
I just saw it has been implemented, nice works!

**Comment by Indranil012** [comment]
Should be closed
