### ISSUE TITLE
bug: Unable to install revanced on my Galaxy Tab A.

### ISSUE THREAD

**Issue by CommicKick69ing** [revanced/revanced-manager#992]
### Type

Other

### Bug description

For some reason everytime I try to install the revanced manger APK on my Galaxy Tab A (7.1.1) I get this error saying "There was a problem parsing the package"

What's going on?

### Steps to reproduce

- Download the revanced manger apk from GitHub
- Click on "install" 
- get pop up error saying "There was a problem parsing the package"

### Android version

7.1.1

### Manager version

V1.3.8

### Target package name

N/A

### Target package version.

N/A

### Installation type

Non-root

### Patches selected.

N/A

### Device logs (exported using Manager settings).

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by Axelen123** [comment]
The minimum required android version for manager is 8
