### ISSUE TITLE
feat: Show applied patch version numbers in the 'Applied patches' dialog

### ISSUE THREAD

**Issue by 11BelowStudio** [revanced/revanced-manager#994]
### Type

Functionality

### Issue

* Selecting 'applied patches' in 'App info' for a patched app, shows the names of the patches installed, but doesn't say what version is installed.
    * Like so:
    * <img src="https://github.com/revanced/revanced-manager/assets/60523642/a6ab86cd-d33a-4706-8338-e7c1bf3b831f" alt="see https://github.com/revanced/revanced-manager/assets/60523642/a6ab86cd-d33a-4706-8338-e7c1bf3b831f (it's a list of patch names but there's no version numbers)" width="180" height="354">
* This makes it pretty hard to find out what version of a patch one currently has installed, in case there's a problem with the currently-installed patch version or in case one wants to check if an updated version of that patch exists.

### Feature

* Add the version number of the installed patch after the names of each patch in the 'applied patches' dialog
    * So, instead of saying `* Copy Video URL`, it would say `* Copy Video URL (0.0.1)` assuming one currently has version `0.0.1` of that patch patched in.

### Motivation

* Ensures that a user can manually check if an update to patch they are using has been released, in lieu of an automated means of telling a user that an updated version of their patches are available.
* Allowing a user to see what patch version they have installed allows users whom need to report a bug with a particular patch to verify that they aren't using an outdated version of the patch
* 

### Additional context

* If there already is something buried in the ReVanced Manager stating the installed versions of the patches one is using, it's rather poorly-signposted.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Patch versioning will be removed soon because it wasn't used

**Comment by 11BelowStudio** [comment]
So is there any means for an end-user to find out if the patches they currently have applied have updates available or not?

**Comment by oSumAtrIX** [comment]
Yes, the version of ReVanced Patches, not the individual ones

**Comment by 11BelowStudio** [comment]
welp, just made an amended feature request
