### ISSUE TITLE
bug: <App won't open if patch provider changes from latest version>

### ISSUE THREAD

**Issue by sssh7710** [revanced/revanced-manager#997]
### Type

Other

### Bug description

Found while trying to change provider because a new reband extend update was released

### Steps to reproduce

1. Installing the Revanced Manager 1.3.8 Version
2. Change provider to "inotia00"
3. Restart the app

### Android version

android 13
one ui 5.1

### Manager version

1.3.8

### Target package name

.

### Target package version.

.

### Installation type

Non-root

### Patches selected.

.

### Device logs (exported using Manager settings).

```shell
,
```

### Screenshots or videos

![Screenshot_20230705_224708](https://github.com/revanced/revanced-manager/assets/98168192/20f2d5f7-333e-464d-b7e6-b90e9303bd0c)

### Additional context

App data initialization is required for the app to work again

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by sssh7710** [comment]
Manager version 1.3.6 works fine

**Comment by oSumAtrIX** [comment]
#982
