### ISSUE TITLE
bug: Crash on launch when setting inotia00's repos in sources

### ISSUE THREAD

**Issue by AAGaming00** [revanced/revanced-manager#998]
### Type

Error while running the manager

### Bug description

Setting the ReVanced Extended repos in sources leads to a startup crash in manager.

### Steps to reproduce

Set `inotia00` as the username in Sources on both repos, then restart Manager.

### Android version

13 (TQ3A.230605.010)

### Manager version

1.3.8

### Target package name

N/A

### Target package version.

N/A

### Installation type

Root

### Patches selected.

N/A

### Device logs (exported using Manager settings).

```shell
Manager settings is inaccessible, but this appears in logcat.

07-06 11:37:52.864 E/flutter (24951): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (length): Invalid value: Not in inclusive range 0..29: 30
07-06 11:37:52.864 E/flutter (24951): #0      GithubAPI.getLatestRelease (package:revanced_manager/services/github_api.dart:71)
07-06 11:37:52.864 E/flutter (24951): <asynchronous suspension>
07-06 11:37:52.864 E/flutter (24951): #1      GithubAPI.getLatestReleaseFile (package:revanced_manager/services/github_api.dart:123)
07-06 11:37:52.864 E/flutter (24951): <asynchronous suspension>
07-06 11:37:52.864 E/flutter (24951): #2      GithubAPI.getPatches (package:revanced_manager/services/github_api.dart:146)
07-06 11:37:52.864 E/flutter (24951): <asynchronous suspension>
07-06 11:37:52.864 E/flutter (24951): #3      ManagerAPI.getPatches (package:revanced_manager/services/manager_api.dart:211)
07-06 11:37:52.864 E/flutter (24951): <asynchronous suspension>
07-06 11:37:52.864 E/flutter (24951): #4      PatcherAPI._loadPatches (package:revanced_manager/services/patcher_api.dart:49)
07-06 11:37:52.864 E/flutter (24951): <asynchronous suspension>
07-06 11:37:52.864 E/flutter (24951): #5      PatcherAPI.initialize (package:revanced_manager/services/patcher_api.dart:32)
07-06 11:37:52.864 E/flutter (24951): <asynchronous suspension>
07-06 11:37:52.864 E/flutter (24951): #6      main (package:revanced_manager/main.dart:27)
07-06 11:37:52.864 E/flutter (24951): <asynchronous suspension>
07-06 11:37:52.864 E/flutter (24951):
```

### Screenshots or videos

https://github.com/revanced/revanced-manager/assets/42613600/a4c2c47d-f567-4fda-a559-e32a5c5365b0

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager and not related to patching errors or patches

**Comment by oSumAtrIX** [comment]
https://github.com/revanced/revanced-manager/issues/982
