### ISSUE TITLE
feat: clarify patches card

### ISSUE THREAD

**Issue by taku-nm** [ReVanced/revanced-manager#999]
### Type

Cosmetic

### Issue

As seen [here](https://discord.com/channels/952946952348270622/1122167988276187228/1127032172491063366) ; 

Users that patched a while ago can forget, that the list of selected patches is clickable. This is a problem when the old list of patches got automatically loaded. 

### Feature

copied from #967

an edit button, preferably on the top right of the app and patch selection card. If it were at the bottom of the list, I can already see how people would miss it by not scrolling down;

### Motivation

same as issue #967
except that playback issues are less of a problem for now;

### Additional context

This came to be after a _lengthy_ [discussion](https://discord.com/channels/952946952348270622/952946952348270626/1127022080840445953). 

This link is just a refence for osu and me

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by ILoveOpenSourceApplications** [comment]
This issue was resolved with #1099 and can be closed right?

**Comment by taku-nm** [comment]
> This issue was resolved with #1099 and can be closed right?

No the issue just went stale

**Comment by oSumAtrIX** [comment]
ReVanced Manager will soon be released as [a full rewrite](https://github.com/ReVanced/revanced-manager/tree/compose-dev). Over time, many feature requests have been made for the current version of ReVanced Manager, but to accelerate the development of the new version of ReVanced Manager, we have to focus on it, which I am closing this issue according to the [contribution guidelines](https://github.com/ReVanced/revanced-manager/blob/main/CONTRIBUTING.md#-submitting-a-feature-request):

> Requests can be accepted or rejected at the discretion of maintainers of ReVanced Patches

This feature request has been closed for one or more of the following reasons:

- Stale for too long/ Low priority/ Maintainers un-interested/ Too complex to realize
- Feature planned/ already implemented for the new version of ReVanced Manager

Regardless, anyone who comes across this feature request can PR it to the current version of ReVanced Manager until the new version is ready. Thanks for your feature request!
